### ISSUE TITLE
Have an option for shortened custom URLs

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1008]
Right now our custom URLs that we use to track referrals from different sites is in the form sidewalk.umiacs.umd.edu/?referrer=google-adwords. There are some situations where we are not able to hyperlink to this URL with custom text, so the full text of the URL is shown to the user. In this situation, we want the URL to be as short as possible to reduce visual clutter (and long/confusing links seem more suspect and are less likely to be clicked, I am assuming).

I am thinking that we can give the option to use /?r=google-adwords instead of /?referrer=google-adwords. This is probably the best we can do. Then we would just decide on a short identifier for the site that they are being referred from.

**Comment by jonfroehlich** [comment]
Yes. We discussed this on Slack. I like the r option

**Comment by manaswis** [comment]
Closed via #1021
