### ISSUE TITLE
Can't see the labels on the street view!

### ISSUE THREAD

**Issue by ladann** [ProjectSidewalk/SidewalkWebpage#101]
Even when I move around I can't see my previous labels on the street view. Although I can see the labels on the map, the problem intensifies when I need to label, let's say the curb ramps, in the intersections, and I forgot which curb ramps I have already labeled. I tried to overcome this issue using the map, but it's  too small, and I can't zoom in/out.

**Comment by jonfroehlich** [comment]
Ladan, do you have a screenshot of this?

There is a "bug" for seeing your previous labels in Street View scenes where we do not have 3D-depth data. Kotaro and I discussed a solution, which, if I recall correctly is just to figure out the avatar's viewpoint angle and set the label a fixed distance away. Kotaro was going to experiment with this fixed distance. This way, even in the cases where a SV scene lacks 3D-depth information, we will still place labels on the top-down map.

**Comment by ladann** [comment]
Ok, I understand. Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/7192301/15827993/97a88032-2bdb-11e6-8dd6-a4a66f44585f.png)
In this case, the avatar on the map is disappeared, and I can't use the map to label the missing curb ramps in the intersection.

**Comment by jonfroehlich** [comment]
Yah, the avatar disappearing is a noted problem as well, not sure why that is happening (and I don't think Kotaro is either). He believes its a bug in GSV actually.

**Comment by kotarohara** [comment]
@ladann 

Is it the issue #84 ? Or is that you cannot see what you have labeled in one Street View image from another image? If it's the former, we'll address it in the future. In fact could be a task for the next iteration. 
If that's the latter, there is a no "good" way to implement it (errors in calculating label position from different angles too big, it's computationally expensive to the extent that the application hangs to compute labels' locations), so I won't fix it.
The pegman dissapearing is a known Google Street View bug, so I can't do anything about it :(
Thanks for the feedback!

**Comment by ladann** [comment]
I see what you're saying. I think, It's the combination of 'not being able to see the labels on other images' and 'the pegman disappearing', which could affect the labeling task. 
I noticed that the guide at the bottom-right could be useful, when such a problem happens. For instance, in the screenshot  above, the guide is saying to make a U-turn, meaning that the pegman is facing towards the green line (down).

**Comment by kotarohara** [comment]
> I see what you're saying. I think, It's the combination of 'not being able to see the labels on other images' and 'the pegman disappearing', which could affect the labeling task. 

I see. Yeah, it's a good point, but we don't have a good way to fix these problems due to the reasons I mentioned above... Thanks for pointing out though!

/cc @ladann
