### ISSUE TITLE
Modifications needed to allow turkers to perform audits on the production website

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1019]
The idea is to use the custom urls to automatically signup turkers with an account that will be accessible by them for a single session. These accounts will also be associated with a separate 'Turker' role rather than volunteer, administrator, or researcher. Within that session they can complete as many missions as they like. Completing the first mission will allow them to get a confirmation code to be submitted on MTurk for the base reward. They will be compensated for any other subsequent mission completions in the form of bonuses. 

- [x] Check if posting a link on mturk gives a query string with worker id, assignment id, hit id etc (It doesnt) 
- [x] Add a new Turker role in the role table.
- [x] If referrer is mturk then change the role of the user to Turker. 
- [x] Check if this turker was present in the list of turkers who've completed the controlled experiments.
- [x] Add a turkerId column to the amt_assignment table (modify evolutions file, modify amt_assignment_table model) 
- [x] Write code to display a confirmation code on completion of the first mission by a turker 
- [x] Write code to generate the confirmation code on the first mission completion.
- [x] Write a table to store previously used confirmation code. (Time generated, time used, associated user). (We can just add a column to the amt_assignment table)
- [x] Write code to approve assignments that have the correct confirmation code submitted.
- [x] Write code to prevent reuse of confirmation codes (this is not required since the confirmation code will be linked with the assignmentId and hitId in addition to workerId during the verification process).
- [x] Write code to automatically transfer a bonus reward to a turker on mission completion. (Add a column to the mission_user table to indicate if the user was monetarily compensated for completing the mission)

**Comment by maddalihanumateja** [comment]
There seem to issues with getting a mission for new anon users in this branch. Need to check if this is because of my database or if its something I changed accidentally in the code.

**Comment by maddalihanumateja** [comment]
The code to approve HITs and bonuses is actually pseudo-automated. It needs to be scheduled to run every 10 minutes or so by a cron job.

**Comment by manaswis** [comment]
Closed via #1021
