### ISSUE TITLE
The green path suddenly turned red.

### ISSUE THREAD

**Issue by ladann** [ProjectSidewalk/SidewalkWebpage#102]
I was following the red path, and the guide at the bottom-right notified me to make a U-turn, I did, and then the path I already passed, turned red. Not sure if it's important. 
![image](https://cloud.githubusercontent.com/assets/7192301/15814042/c83f4496-2b91-11e6-97cb-7bba792f20e7.png)

After I went through the path again, I ended up in a loop, meaning, that the the guide was telling me to move through the green path over and over again. When I hit the jump button, It brought me back to the mission I completed previously [just wanted to add that, every time I complete a new mission, I ended up jumping to the mission that I already done].

**Comment by kotarohara** [comment]
Thanks. I'll take a look at the log and see if I can figure out what's happening.

**Comment by kotarohara** [comment]
I think I fixed the issue... I'll reopen if it happens again. Thanks @ladann !
