### ISSUE TITLE
Project Sidewalk Appears Down

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1025]
I was going to send out a series of emails to bloggers tonight about Project Sidewalk but our site appears down. :(

![image](https://user-images.githubusercontent.com/1621749/29906549-9969a548-8dca-11e7-9981-9c92442df1e4.png)

![image](https://user-images.githubusercontent.com/1621749/29906562-ae0add6e-8dca-11e7-9c9c-0a2aa0839786.png)

**Comment by manaswis** [comment]
I checked the logs. I didn't see anything out of the ordinary and it seems to be running fine now. @jonfroehlich @misaugstad @maddalihanumateja 
 
@misaugstad I did see a warning saying "Unable to assign a task in region 282 to an anonymous user." That's invoked here - https://github.com/ProjectSidewalk/SidewalkWebpage/blob/bc65ce566f1113661d208942d98057b7d320b123/app/models/audit/AuditTaskTable.scala#L446 - However, that shouldn't bring the site down.

**Comment by misaugstad** [comment]
From email thread with UMIACS...
>Very sorry we had upgraded our configuration management yesterday and into last night breaking our iptables rules a bit.

>This was unforeseen human error that manifested itself when we upgraded our configuration management yesterday... We apologize again for the inconvenience. For known outages, we always make the best effort to inform our users in a timely manner prior to the maintenance occurring.

So it was partially human error that resulted in our surprise at the site being down. In an attempt to be more aware, we looking into ways of pinging the server frequently to make sure that it is up, ideally getting an email notification if the server is down. This is being discussed in #1027
