### ISSUE TITLE
Clicking outside the survey modal container dismisses it

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1030]
This is a problem that most of us would have come across before with the popups. Clicking anywhere outside the actual popup closes it. This is a problem for surveys, especially when it is mandatory to answer some of the questions. The users can just dismiss these by clicking on the background and is never shown the survey again. This happens inspite of setting the backdrop to be static. Needs to be resolved!!

**Comment by misaugstad** [comment]
Closing via #1031
