### ISSUE TITLE
Admin Interface: Add Turk Stats

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1034]
We should add MTurk stats to the admin interface, including for:

1. A row in this table
![image](https://user-images.githubusercontent.com/1621749/29992667-f6c52348-8f55-11e7-9450-03a5eee03f74.png)

2. Missions completed by users
3. Labels per user
4. Other areas? :)

**Comment by jonfroehlich** [comment]
I consider this an extremely important task and I want to see some discussion about it from the team. We simply cannot naively group turkers into the registered and anonymous user bins. We need them as a separate group and to be able to analyze their performance separately.

Given that we already have a nice infrastructure for visualizing stats, I believe that a half-day or a full-day of dedicated coding could allow us to accomplish this Issue.

So, to expand on what I wrote above. At a minimum, we should have:

1. A row in the total users table that is turkers
![image](https://user-images.githubusercontent.com/1621749/31191929-8d2bbd08-a8f4-11e7-8a89-285f4c99e1ad.png)

2. Missions completed by users. Make an additional bar graph for this user group.
![image](https://user-images.githubusercontent.com/1621749/31192059-f451bc26-a8f4-11e7-914b-0240d03ff55b.png)

3. Labels per user. Make an additional bar graph for this user group.
![image](https://user-images.githubusercontent.com/1621749/31192071-fd89c66c-a8f4-11e7-94d0-a2d9cca992a3.png)

4. Total time spent auditing. Make an additional bar graph for this user group.
![image](https://user-images.githubusercontent.com/1621749/31192103-180e2046-a8f5-11e7-888d-cf02d8364a7f.png)

**Comment by misaugstad** [comment]
@tongning do you think you might want to take this up?

**Comment by tongning** [comment]
Started the implementation at [1034-turker-stats](https://github.com/ProjectSidewalk/SidewalkWebpage/tree/1034-turk-stats). Hoping to have a PR within a week or so, but might have to delay due to midterms :(

**Comment by jonfroehlich** [comment]
Hi @tongning, thanks for getting started on this. Any more updates?

**Comment by tongning** [comment]
The current commits on the branch add the turker visitor count to the activities table. It also adds an endpoint to fetch labels counts for turkers, but doesn't add them to the graph yet. Would you like me to submit PRs for these before adding the others?

**Comment by jonfroehlich** [comment]
Yes please. Let’s do incremental PRs to get data on dashboard ASAP.

**Comment by misaugstad** [comment]
Maybe just submit a PR for the part that is done and visible, not for the query that hasn’t been added to the graphs yet.

**Comment by misaugstad** [comment]
@tongning During a meeting today, we realized that we also want to separate out researcher stats in addition to turker stats. This should be trivial to do, since researchers can be identified in the exact same way that turkers are identified (by looking for a researcher role in the user\_role table).

**Comment by misaugstad** [comment]
@jonfroehlich also mentioned wanting a column that has percent of total, so that we don't have to do the math in our heads when comparing each time. @jonfroehlich do you want just one new column for overall, or do you want to have the `today` and `yesterday` columns to have their own percentage columns as well?

**Comment by jonfroehlich** [comment]
@misaugstad % just for overall should be fine.

**Comment by jonfroehlich** [comment]
Nice job on this:

![image](https://user-images.githubusercontent.com/1621749/31836226-67444f5a-b589-11e7-9a9c-238667c4df0f.png)

I just added one additional small task to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1034#issuecomment-334243609 (TODO item number 5).

**Comment by misaugstad** [comment]
Implemented in PR #1161
