### ISSUE TITLE
Sidebar Counts Fall Onto Two Lines

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1042]
When you get over a certain # of miles and labels for a neighborhood, the sidebar counts fall onto two lines rather than one. The easiest solution would just be to, in these cases, shrink the fonts to fit or use abbreviations "mi" and "lbls"

![image](https://user-images.githubusercontent.com/1621749/29999694-5d907f12-9007-11e7-974c-1ad4e584b98e.png)

**Comment by misaugstad** [comment]
duplicate of #672
