### ISSUE TITLE
Keep difficult region overlay centered

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1044]
As mentioned in PR #1011 the overlay that says that you are going to audit a difficult region can be off-center, depending on the resolution of your monitor and zoom level. This should really be centered independent of those two variables. Here is an example of the worst-case:

![off-center-overlay](https://user-images.githubusercontent.com/6518824/29934912-f0e19364-8e4a-11e7-9b07-8bad4a03ae15.png)

An example of a "difficult" region is monumental core (which is the largest region when you look at one of our choropleths.

**Comment by sarahsmo** [comment]
Issue was our fixed sizing in the style sheet. 

Before: zooming would alter position
![image](https://user-images.githubusercontent.com/31173144/30007270-42b45ae2-90d9-11e7-9490-241807a58449.png)

After: remains in the center even when zooming in/out
![image](https://user-images.githubusercontent.com/31173144/30007298-a9467b46-90d9-11e7-8a05-96e00e4e02f9.png)

**Comment by manaswis** [comment]
Looks good!

**Comment by manaswis** [comment]
However, update your branch from develop. The message looks like the old one.

**Comment by sarahsmo** [comment]
Fixed!

**Comment by manaswis** [comment]
Closed via #1053

**Comment by misaugstad** [comment]
Currently testing on dev server. The overlay looks 10x better than before! It just does not look vertically centered. See below.

![image](https://user-images.githubusercontent.com/6518824/30782727-f2c1462a-a105-11e7-996b-e2cd481cfe4b.png)

Not sure that it is worth fixing, considering how few people will ever see it, thoughts?

**Comment by jonfroehlich** [comment]
Not worth fixing imo.
