### ISSUE TITLE
Need to exclude HITs performed by Researchers when performing calculations for condition assignment to Turkers

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1046]
We'd decided that a particular set of routes should have x=5 turkers assigned. The way these sets of routes are assigned is to look at the count of HIT assignments associated with each condition and select the one with the least number of past workers (round robin). This count calculation should exclude HIT assignment performed by researchers during ground truth collection. We may also want to exclude certain condition from being assigned at all due to some problems with routes (unable to complete the route for some reason).

**Comment by manaswis** [comment]
Closed via #1047
