### ISSUE TITLE
Moving with Arrow Keys in Street View

### ISSUE THREAD

**Issue by danZzyy** [ProjectSidewalk/SidewalkWebpage#105]
This is a feature I noticed we do not have that seems pretty simple to implement. It does not come by default in Google Street View but I have seen it in GeoGuesser.

**Comment by jonfroehlich** [comment]
I think it's a nice idea. I believe I previously pitched this to Kotaro but I can't remember his response. :)

**Comment by danZzyy** [comment]
I discussed it with him on Friday I think and he liked it

**Comment by kotarohara** [comment]
I think it could be useful. I'm not sure if it's a high priority task. Let's discuss if this should be one of your tasks for the next development iteration once you are done with the current task.

**Comment by kotarohara** [comment]
@danZzyy completed this. I'm closing this now.
