### ISSUE TITLE
With high label counts, label images go off screen

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1051]
I think the pictures speak for themselves!

![lotsolabels3](https://user-images.githubusercontent.com/6518824/30033140-6ffb871c-9167-11e7-8327-e3ae286e8f13.png)
![lotsolabels1](https://user-images.githubusercontent.com/6518824/30033089-2139493e-9167-11e7-945e-d991da43555c.png)
![lotsolabels2](https://user-images.githubusercontent.com/6518824/30033088-213770d2-9167-11e7-9e23-38ada783bfe9.png)

**Comment by johannkm** [comment]
Suggested fix: scaling down the circle sizes.

![screen shot 2017-09-20 at 1 48 39 am](https://user-images.githubusercontent.com/22018973/30628699-da318e34-9da5-11e7-89e5-2fde44344d3f.png)

To me, these circle indicators are not intuitive and don't seem to add to the user experience. I understood the significance of the larger circles by watching the animation as I added new labels. However, a volunteer would be looking at the map and not the status bar while they add a label. Thoughts?

**Comment by misaugstad** [comment]
Pasting Jon's comment related to this from issue #772 
>I agree that this interface isn't great... but we're not doing a full UI redesign this semester. So, let's just keep it for now.

And I think that scaling down the circles should work fine; quick and easy. For the size you are suggesting, how many labels does it take before they start getting cut off? If it's in the hundreds then that should be fine. 

Once the size is set appropriately and a PR is merged for issue #772 (since it adds a new label color) you can submit a PR for this as well.

**Comment by nomichka** [comment]
![Project Sidewalk Issue 1051 all Labels](https://user-images.githubusercontent.com/35845622/60451759-a9c94e80-9be1-11e9-97f3-25b28e36680b.PNG)
The specific label counts are for the current mission; they always get reset once a new mission begins. They are small enough that they only start being a tiny problem once a label counter gets up to 249 (very unlikely for a single mission), so it looks like this issue is out of date.
![Project Sidewalk Issue 1051](https://user-images.githubusercontent.com/35845622/60451930-25c39680-9be2-11e9-93c8-fcc69e2b8774.PNG)

**Comment by jonfroehlich** [comment]
I’m not sure we can close it without a solution. While I think it’s unlikely that this happens, it could happen especially for “no sidewalks” labels which are applied liberally to mark the lack of a sidewalk. 

Also, we may always change mission structures in the future as we have in the past to potentially make this bugmore common

**Comment by nomichka** [comment]
True, especially for "no sidewalks," could be a problem.
![Project Sidewalk Issue 1051 No Sidewalk](https://user-images.githubusercontent.com/35845622/60460024-7ee9f500-9bf7-11e9-93d8-649dfc497366.PNG)

**Comment by nomichka** [comment]
![Project Sidewalk Issue 1051 After 199](https://user-images.githubusercontent.com/35845622/60546301-deb4ce80-9cd1-11e9-836c-55f3e1625572.PNG)
![Project Sidewalk Issue 1051 After 249](https://user-images.githubusercontent.com/35845622/60546312-e2485580-9cd1-11e9-8541-1541edc182e6.PNG)
As is, there are circles representing one, ten, and fifty labels; I added a circle size representing a hundred labels.

**Comment by jonfroehlich** [comment]
Wo0t! Can we see more screenshots, particularly in the context of the full UI.

**Comment by nomichka** [comment]
![Project Sidewalk Issue 1051 screenshot](https://user-images.githubusercontent.com/35845622/60551230-7f5dbb00-9cdf-11e9-9bd8-53656ebb39c3.PNG)

![Project Sidewalk Issue 1051 screenshot 2](https://user-images.githubusercontent.com/35845622/60551237-85539c00-9cdf-11e9-8e2d-d0da9af164f9.PNG)

![Project Sidewalk Issue 1051 screenshot 3](https://user-images.githubusercontent.com/35845622/60551239-87b5f600-9cdf-11e9-80ff-b771184cd91a.PNG)

**Comment by misaugstad** [comment]
closing via #1769
