### ISSUE TITLE
Mission Complete Label Counts All Zero in Turk Branch?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1054]
![image](https://user-images.githubusercontent.com/1621749/30038282-8d8f05c8-9177-11e7-91f3-29e39ec39d35.png)

**Comment by jonfroehlich** [comment]
Just completed another mission. Still zero:

![image](https://user-images.githubusercontent.com/1621749/30038398-e66be1a6-9178-11e7-8f3e-0ac5bf0ee6c2.png)

**Comment by maddalihanumateja** [comment]
Resolved in #1057
