### ISSUE TITLE
Update/Modify GT resolution tool to fill in null severities for solo GT labels

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1056]
When labeling for GT, I have a suspicion that we occasionally miss the severity rating. This has been happening to me since I am using a different keyboard from normal while doing GT collection... As we have hundreds of labels, I suspect that must have made a mistake or two. 

And I think this would be quite an easy modification to the GT resolution tool.

The priority of this depends on how much we plan to use severity ratings in the paper. If we are going to include a breakdown of severities in the GT dataset or if we are going to do a type of accuracy calculation that takes into account severity, then this definitely needs to be done ASAP. If severity analysis will happen post-CHI, then this can be done post-CHI as well.

So, do we need this pre-CHI @jonfroehlich ?

**Comment by jonfroehlich** [comment]
I think we need it pre-CHI. My experience says that anything we push to post-CHI will not necessarily ever get done.

**Comment by manaswis** [comment]
Closed via #1097
