### ISSUE TITLE
Provide a way to retake onboarding tutorial for people who did not pay attention to the tutorial

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#106]
I was talking about the tutorial with Andrea today and we think a way to come back and take the tutorial is important (because anonymous users might just skip and registered users might go through quickly without paying much attention for the first time). I would put a small & subtle button somewhere in the interface that navigates users to retake the tutorial.

**Comment by kotarohara** [comment]
Done.

**Comment by jonfroehlich** [comment]
Screenshot?

**Comment by kotarohara** [comment]
![image](https://cloud.githubusercontent.com/assets/612263/16131178/e7445056-33da-11e6-9990-e996a2fe019b.png)

I still don't know if the top-level menu bar is the place to put it, but I think it's good enough for now.

**Comment by jonfroehlich** [comment]
I like it! :)

Now if we could only redesign those ugly '?' marks on the labeling buttons.... :-P
