### ISSUE TITLE
Buggy condition assignment to turkers 

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1060]
This affects the endpoint "/audit" which is used to assign conditions to turkers in a round robin fashion. The SQL Query that returns an available condition seems to have been implemented incorrectly:
 - The calculation for the number of times a condition has already been assigned does not take into account
    - filtering for completed assignments
    - multiple records in the amt_assignment table for different routes within a condition
- There is a default conditionId of 1 that is assigned when there is no condition actually available (something that should have been scrubbed from the code)

**Comment by manaswis** [comment]
Does the recent PR #1061 also address this issue? @maddalihanumateja @misaugstad

**Comment by maddalihanumateja** [comment]
No PR #1062 uses a different approach altogether. The endpoint mentioned in PR #1062 doesn't assign conditions in a (buggy) round robin fashion like '\audit'. It needs a conditionId to be specified like in '\auditCondition'.

**Comment by manaswis** [comment]
Okay thanks!

**Comment by misaugstad** [comment]
We have finished the mturk experiment and are no longer using this branch, so I'm closing this issue.
