### ISSUE TITLE
Need a different endpoint to assign conditions to Turkers

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1061]
We already have an endpoint that allows ground truth collectors to audit multiple conditions (by overwriting the conditionId assigned to them). A different endpoint is required for the Turkers to be assigned a certain conditionId if arent already associated with one. This will allow us to "block" them from attempting other HITs associated with different conditions. (Text in this issue needs to be updated)

**Comment by manaswis** [comment]
Closed via #1062
