### ISSUE TITLE
We Should Not Be Using Production Server Google Analytics on MTurk and Test Server

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1066]
I just thought of this: are we using Google Analytics on our MTurk and test servers? If so, are they hooked up to the production server Google Analytics account? If so, they shouldn't be :) We should have individual Google Analytics trackers for each of those sites (at least production and mturk; test server not necessary).

**Comment by manaswis** [comment]
I had created one for mturk server separately in the Spring semester's course project. That's being used for mturk.

Since dev server is a replica of production server, it uses the same as the production server.

**Comment by jonfroehlich** [comment]
OK, and since dev server usage is low, I'm sure it's not that big of deal. Closing.
