### ISSUE TITLE
Need to Better Explain and Show HIT Progress to Turkers

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1067]
In the initial HIT that we posted on Mturk one of the turkers said "I expressed concern over the length of the HIT because I mistakenly thought the neighborhood progress bar was also my progress to complete the HIT, and it was moving very slowly." .

To address this concern we could
(i) update mission complete dialog to have 1 of 3, 2 of 3 and 3 of 3 in title and maybe modify the button itself so that it shows how many missions are left; 
(ii) update the sidebar so that it also has HIT mission tracking.

**Comment by jonfroehlich** [comment]
I think the neighborhood completion bar could be removed for turk and instead replace it with HIT mission tracking. But we should do something quick-and-easy that is also super informative and obvious so that it can't be missed or easily misunderstood.
