### ISSUE TITLE
Make tutorial or promotional video for top-page

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#107]
Make tutorial or promotional video for top-page.

**Comment by nguyenist** [comment]
What should the criteria be to understand whether or not the promotional video is necessary? 

Would you like to test whether or not people understand how to label with the current step by step walkthrough/tutorial? And if they ask for a visual/step by step video then we consider the video?

**Comment by Soben713** [comment]
Based on our discussions in the Project Meeting, I am removing this issue from Public Deployment v2.

**Comment by misaugstad** [comment]
Oh hey, we have a video on the landing page :sunglasses:
