### ISSUE TITLE
Confusing implementation of labelTypeToId function (any idea why?)

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1070]
So in the label table, the label types are represented by an integer. The integers are then mapped to the string that represents that label type in the label_type table. Obviously, having a function that converts a label_type_id to a label_type string is very useful. I looked at the implementation in the LabelTypeTable.scala file...

But it doesn't make sense to me. It returns the correct result, but if the label type is not already in the label_type table, then it enters a new record in the table... This seems like a really weird side effect that shouldn't be happening. Does anyone know why it was designed this way..? If there is a good reason to do this, then at least the name of the function and the documentation on what it does should change, but I think that we should probably just get rid of that side-effect if no one knows why it is currently there.

**Comment by jonfroehlich** [comment]
Pinging @kotarohara

**Comment by misaugstad** [comment]
@wilsmic2 can you remove the weird side effect of this function? :blush:

**Comment by wilsmic2** [comment]
I am somewhat confused by what the correct functioning of this table should be. When would the label type not already be in the label_type table? Or is the function of entering a new record in the table if the label type  is not already there something in the code that should be removed?

**Comment by misaugstad** [comment]
it is something that should be removed. there shouldn't be a situation where this function is used and the label type is not already in the table.

**Comment by wilsmic2** [comment]
Ah ok that's what I thought. Just wanted to make sure that I understood it correctly!

**Comment by misaugstad** [comment]
closing via #1828
