### ISSUE TITLE
Contributions dashboard not accessible if username contains forward slash

### ISSUE THREAD

**Issue by tongning** [ProjectSidewalk/SidewalkWebpage#1075]
Currently the format of the URL for the user contributions page is:

`http://<sidewalk>/contribution/<username>`.

This is somewhat problematic if the username contains a forward slash, as it will be treated as a different endpoint resulting in a 404 error. I imagine the simple solution would be to change the endpoint to 

`http://<sidewalk>/contribution/<userid>`

instead. Url-encoding usernames might be another option.

**Comment by misaugstad** [comment]
I don't think we should surface the user_id to users. URL-encoding or just preventing them from using forwards slashes in their usernames are good options.

**Comment by jonfroehlich** [comment]
Agree with @misaugstad. I like keeping the username in the url (probably using url-encoding but may also want to prevent future usernames from using non-url friendly characters in their usernames).

**Comment by misaugstad** [comment]
We are using URL-encoding and this has been fixed.
