### ISSUE TITLE
Quality Control Methods

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1076]
We have been discussing quality control methods. There are a ton of possibilities here, including:

- Verification interfaces
- Analyzing behavior of worker via interaction logs
- Performing statistical verification of labeling activity. That is, does a labeler's mission have similar label distribution of prior routes in that (i) neighborhood or (ii) neighborhood land use type. This seems relatively easy. 

We could perform offline investigations for some of these to investigate further. 

For ideas, see Quinn and Bederson's overview of human computation ([link](http://alexquinn.org/papers/Human%20Computation,%20A%20Survey%20and%20Taxonomy%20of%20a%20Growing%20Field%20(CHI%202011).pdf)). There are lots of research papers on quality control methods for online work that we should examine for ideas as well.

**Comment by misaugstad** [comment]
We now have an earlier thread that has other ideas for reviewing/verifying labels in #535 , so pasted your comment into that thread and am going to close this one so that we keep all the ideas in the same place.
