### ISSUE TITLE
Neighborhood label count only updates after completing a mission

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1079]
Best shown by example...

Right before I finish a mission, I have placed 14 labels, but neighborhood label count is 0.
![nolabelupdate1](https://user-images.githubusercontent.com/6518824/30302257-c9d219a6-972d-11e7-86bb-1b7c12a385fa.png)

Then I take a step and the mission ends; now I have 14 neighborhood labels.
![nolabelupdate2](https://user-images.githubusercontent.com/6518824/30302275-e5b1de2c-972d-11e7-9012-f305aab64e08.png)

Not sure why this is only being updated after a mission and not whenever a new label is placed. Also, I couldn't find an issue that specifically talks about this, except I think that in #497 @manaswis gets at it at the end.

In any case, I think that @sarahsmo could start by making sure this updates, then possibly looking into the bug that is talked about in #497 which is also related to the neighborhood label count.

**Comment by manaswis** [comment]
Yeah I think this is by design, not saying its a good design :) But yes, should be updated.
