### ISSUE TITLE
Severity Rating Pop-Up: Not Sure I Agree with All Thumbnails

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1080]
I probably would never label something like this as an Obstacle in Path because it seems like there is plenty of room to pass this parking meter on the far side (away from street). There are tons of these sorts of objects on the sidewalk (poles, parking meters) that are placed closed to the curb but that I don't think present a problem. @misaugstad is this particular severity pop-up consistent with our codebook?

![image](https://user-images.githubusercontent.com/1621749/30336071-f425163e-9798-11e7-84db-e9a35d7819bc.png)

In general, I think we should review all pop-ups and ensure that they are consistent with our internal codebook (which we will also soon publish online--post-CHI task!).

**Comment by misaugstad** [comment]
@jonfroehlich I agree with you disagreement, that shouldn't be labeled as an obstacle at all. When preparing the labeling guide for public posting, we can also choose really good examples to include in here.

**Comment by misaugstad** [comment]
Link to issue for converting codebook to public labeling guide: #961

**Comment by jonfroehlich** [comment]
Thanks Mikey. I think changing the pop-up is actually a somewhat high priority since it could lead to poor quality results...

**Comment by misaugstad** [comment]
Yeah I can get behind that; I will get to this sooner rather than later.

**Comment by jonfroehlich** [comment]
@misaugstad I wanted to remind you of this issue because we now have turkers who are putting significant time into auditing and I would hate for them to misunderstand *what* they are supposed to label and/or the severities they are supposed to assign because of incorrect pop-up guides.

**Comment by misaugstad** [comment]
@jonfroehlich How do you feel about any of these?
![obs1-14155-3](https://user-images.githubusercontent.com/6518824/31396282-fd7cf020-adb0-11e7-8454-baf0c4bf4838.png)
![obs1-14155-2](https://user-images.githubusercontent.com/6518824/31396283-fd9cb072-adb0-11e7-8fb3-16f42040e240.png)
![obs1-14155](https://user-images.githubusercontent.com/6518824/31396284-fda708c4-adb0-11e7-8af6-a2a936cd7965.png)
![obs1-7871](https://user-images.githubusercontent.com/6518824/31396285-fdb2cab0-adb0-11e7-8473-e0659ca0642d.png)

**Comment by jonfroehlich** [comment]
1. I typically mark cars as obstacles in path with a 'temporary' flag. All three of those cars look passable with maybe a 2 or a 3 rating. The last one (Chevy SUV) looks worst, so maybe a 3.

2. The last picture has a number of obstacles. The electrical box (in gray) is not really an obstacle in path and only serves to clutter picture, so could be difficult as a thumbnail. The other potential obstacle, the tree plus support wires, is also complicated but seems to be a ~4 severity (hard to examine width, however and there is a visual illusion which affects interpretation of where support wires are going).

At the risk of sounding immodest, how about looking at 'objects in path" that I marked with different severity levels to see if any are nice exemplars that would look good cropped and thumbnailed?

**Comment by misaugstad** [comment]
>I typically mark cars as obstacles in path with a 'temporary' flag

Agreed

>All three of those cars look passable with maybe a 2 or a 3 rating.

The first one looks more like a 1 to me.

>At the risk of sounding immodest, how about looking at 'objects in path" that I marked with different severity levels to see if any are nice exemplars that would look good cropped and thumbnailed?

I am currently doing something akin to that, and I can continue looking.

**Comment by misaugstad** [comment]
How about any of these? I was going through panoramas where you had places severity 1 obstacles labels.

![obs1-inypvjdzkfkhfpsosqk4lg](https://user-images.githubusercontent.com/6518824/31399002-cdcc1bb4-adb8-11e7-910c-898f64c2055c.png)
![obs1-4qgawb3drvxgx3ccy2ljxq](https://user-images.githubusercontent.com/6518824/31399003-cdd50d1e-adb8-11e7-9ff0-79e0148bbb00.png)
![obs1-yphh_u-o3mva0y4cb8ykkg](https://user-images.githubusercontent.com/6518824/31399004-cdde7a0c-adb8-11e7-89f3-5d917b5a9339.png)
![obs1-ui-nawrkbmgadacvvvz44a](https://user-images.githubusercontent.com/6518824/31399005-cde9e1da-adb8-11e7-89e7-57daab4df10a.png)
![obs1-a6t2m4dxn34qbfadhc2-ta](https://user-images.githubusercontent.com/6518824/31399006-cdf5d954-adb8-11e7-9a7d-4df021101535.png)

**Comment by jonfroehlich** [comment]
1. Garbage bag I would probably label a 3 or 4 now
2. Car seems like it could be a 1
3. This pole seems more like a 4 or 5
4. This recycling bin seems like a 3
5. This garbage bin seems like a ~1

**Comment by misaugstad** [comment]
@jonfroehlich How do you like these...?
Severity 1:
![](https://user-images.githubusercontent.com/6518824/31399005-cde9e1da-adb8-11e7-89e7-57daab4df10a.png)

Severity 3:
![](https://user-images.githubusercontent.com/6518824/31396284-fda708c4-adb0-11e7-8af6-a2a936cd7965.png)

Severity 5
![image](https://user-images.githubusercontent.com/6518824/31404741-dde290a2-adca-11e7-951d-3a011c691128.png)

**Comment by jonfroehlich** [comment]
Argh, this is _so_ hard and essentially, this discussion says to me: a 5-point rating system for problems is probably not the way to go and that we should redesign this to use like 3 emojis or some other system. :)

For the pictures:

- Severity 1: This is fine. Not perfect but probably good enough. You'll have to zoom in, of course.
- Severity 3: Again, it's OK. Seems like this could be a ~2. :-p
- Severity 5: This one is perfect. :)

**Comment by misaugstad** [comment]
Cool. Regarding the 3 severity, I really think this isn't a 2. Of course it is always hard to tell exactly how much space there is in a given image, but it looks like there isn't that much space to me here. Also it requires one to go down the sloped driveway which can mess with one's balance.

And for the first one, I like it because the recycle bin is also like... you can just push it aside, so I can't imagine it being more than a severity 1 ;)

I will replace the images with these; they are certainly better than what we had before.

**Comment by jonfroehlich** [comment]
Sweet. Thank you Mikey!

**Comment by misaugstad** [comment]
Fixed in PR #1138
