### ISSUE TITLE
Turkers need to be able to sign back into the production site

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1087]
Currently the code handling turkers on the production site assumes that Turkers will be limited to working on missions in a single browser session. The intention was to reduce risk ( an example of where this needed and better solutions to it are proposed in #1082 ). However there might be cases where there is an accidental logout event. For example, closing the browser for any reason logs them out and they will not be able to accept another HIT to continue auditing. This might be confusing. Turkers need to be able to log back into the production site when they accept another HIT expecting to continue work.

**Comment by misaugstad** [comment]
Closed via #1088
