### ISSUE TITLE
Issue with dashboard: exploring other areas!

### ISSUE THREAD

**Issue by ladann** [ProjectSidewalk/SidewalkWebpage#109]
In dashboard, when I choose another area to explore (and click on 'sure'), it brings me back to the same location I was exploring previously. 
![image](https://cloud.githubusercontent.com/assets/7192301/15866950/ef379102-2cae-11e6-83d7-07b510e3ef19.png)

**Comment by kotarohara** [comment]
Fixed. I'm closing it.
