### ISSUE TITLE
After Completing a Neighborhood and Clicking "Audit Another", Mission Complete Immediately Pop-Ups In New Neighborhood 

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1095]
After completing a neighborhood and clicking "Audit Another", a mission complete dialog erroneously pops up immediately for that newly assigned neighborhood.

I think this is a higher priority now with the Turk production push.

See: https://youtu.be/6EnmhTRITdk?t=58s

**Comment by misaugstad** [comment]
This may not be *quite* as erroneous as it seems at first. What can happen is that when you audit a street edge that crosses multiple neighborhoods, this adds to your completion for the neighborhood you think you are working on, but also for the other neighborhood that the street edge overlaps with.

So if you have enough audited enough streets in adjacent neighborhoods, you may have completed enough distance to get have completed a mission. Then when you go there for the first time, maybe it is saying "oh look, you've finished a mission, yay!". You can definitely see in the video that you have street edges completed in that region that overlap with neighboring regions, so this is what I suspect is happening.

Also, this is just a UI bug that won't cause too much of a bother to anyone. They just kid annoying cheering and a congratulations when they don't expect it... I don't think turkers will be too hampered by this, so I am going to move it to low priority.

**Comment by jonfroehlich** [comment]
Sure, move to lower priority... but it's still a broken user experience imo and confusing. :)

PS I hate that kids cheering sound. Too jolting. We should completely redo sound design experience in Project Sidewalk :-D

**Comment by maddalihanumateja** [comment]
I love that you used "sound design experience" . Having the background music of sim city while auditing would make it an enjoyable task. I would spend hours on missions just for that. Maybe we should a/b test music versus no music :)

**Comment by misaugstad** [comment]
I believe the sound design UX issue is #331 :)

**Comment by misaugstad** [comment]
Fixed in #1319
