### ISSUE TITLE
Let users reset/change their password

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1101]
As far as I know, there is no mechanism right now for changing your password. And if a user forgets their password, there is no way for them to recover their account. Seems like a pretty basic thing that any account-holding user would expect to have.

**Comment by manaswis** [comment]
Bump to this! A good undergrad task to begin on (after the initial vetting tasks and first simple task).

**Comment by misaugstad** [comment]
Just had a user email asking us to help recover their account b/c they forgot their password.

**Comment by misaugstad** [comment]
Something like [this](https://github.com/mohiva/play-silhouette-seed/blob/894633ea65546d1a66e69d24031e24e17cfd5f47/app/controllers/ResetPasswordController.scala) is what we'll be doing, since that is the library we are using. Not sure if that will work out of the box though, we will want to look for an example that uses our exact version of the silhouette library.

**Comment by misaugstad** [comment]
Because I know we are using a relatively old version of that library and there have been significant changes to the syntax for it between our version and the current version.

**Comment by ThatOneGoat** [comment]
Just a quick clarification, I should implement BOTH changing and resetting passwords right? Not just one or the other?

**Comment by misaugstad** [comment]
I think it is most important that users be able to reset their password in the event that they have forgotten it. But adding the ability to just change their password is easy enough to add on top of it, I would go for it. If it isn't trivially easy, I would make a separate issue for it and start with just resetting if the password is forgotten.

**Comment by ThatOneGoat** [comment]
Does Project Sidewalk have a smtp host/email? I was thinking the best way to do the password reset would be to have the user type in their email and an email would be sent to the user with a link to the reset password page. I'm using my own email and gmail's smtp host right now for testing, but that's probably not ideal in the long run.

**Comment by misaugstad** [comment]
How would this work exactly? Like if we have a gmail account can we set it up using that? And will emails sent through it have the "sent" address as that gmail address? Will users be able to reply to those emails then? If so, we should probably create a new account for this purpose

**Comment by ThatOneGoat** [comment]
Yeah I think we could make like a Project Sidewalk gmail and it would have the sent address as that email. I'm not sure, but there's probably a way to prevent users from sending back emails (like a noreply). One thing I'm not sure about is that we'd have to have the account name and password in the appplication.conf, which might expose it on the git repo. I'm not sure how to prevent that.

**Comment by misaugstad** [comment]
That's something that we would make sure not to put in the Github repo. That's something like the API keys that we would put on the server manually and fill in for each person's dev environment (similar to how we set up the API keys for the dev environment).

**Comment by misaugstad** [comment]
But continue using your own email for now during testing. I'll set up a gmail account for this later on

**Comment by ThatOneGoat** [comment]
Alright, the reset password backend has been mostly finished (with a few small safety tweaks still left), so here is the frontend of what each step in the reset password process currently looks like:

**The "forgot password" redirect link on the signIn page:**
![Forgot Password Link](https://user-images.githubusercontent.com/37346427/78334659-02e35b80-7541-11ea-9ad7-419519ecf05b.png)

**The "forgot password" page:**
![Forgot Password Page](https://user-images.githubusercontent.com/37346427/78334680-0d9df080-7541-11ea-9470-cb0fe131b90e.png)

**The "reset password link sent" alert:**
![Reset Password Email Sent](https://user-images.githubusercontent.com/37346427/78334721-227a8400-7541-11ea-95b0-5655180885cd.png)

**The "reset password" page:**
![Reset Password Page](https://user-images.githubusercontent.com/37346427/78334738-29a19200-7541-11ea-8306-358606a88397.png)

**The "password reset successful" notification:**
![Password Reset Successful](https://user-images.githubusercontent.com/37346427/78334773-32926380-7541-11ea-81bf-6e3656fcc2d0.png)

**The "invalid reset password link" notification:**
![Invalid reset password link](https://user-images.githubusercontent.com/37346427/78341874-3d52f580-754d-11ea-83bf-19d120ac7524.png)


Currently the email being sent is just a link, so I'll update with a better mock of the email itself.

**Comment by misaugstad** [comment]
Great, thank you! We should also have this all translated to Spanish later today!

**Comment by ThatOneGoat** [comment]
Here's what the forget password link in the modal looks like:
![Screen Shot 2020-04-03 at 12 56 44 PM](https://user-images.githubusercontent.com/37346427/78399930-aae13f00-75aa-11ea-8461-643649b58799.png)

I think it looks a little weird (there's a lot of empty space at the bottom left) but I might be overanalyzing

**Comment by misaugstad** [comment]
Here are the Spanish translations, courtesy of @gari01234! There are a couple sign in/up translations I forgot to add earlier that are included here. Could you put those in for me as well @ThatOneGoat ?

Forgot your password?
Olvidaste tu contraseña

No worries, type in your email and we’ll send you a link to reset your password.
No te preocupes, escribe tu correo electrónico y te enviaremos un enlace para restablecer tu contraseña.

An email to reset your password has been sent.
Se ha enviado un correo electrónico para restablecer tu contraseña.

Type in your new password
Escribe tu nueva contraseña

Reset password
Restablecer la contraseña

Password reset!
¡Contraseña restablecida!

Error! Invalid Reset Link
¡Error! Enlace de reinicio inválido

Valid email required
Se requiere un correo electrónico válido

Error! Invalid credentials!
¡Error! Credenciales inválidas

Error! Email already exists
¡Error! El correo electrónico ya existe

Error! Password must be at least 6 characters
¡Error! La contraseña debe tener al menos 6 caracteres

Error! Passwords do not match
¡Error! Las contraseñas no coinciden

You recently asked to reset your password for your Project Sidewalk account. Click the link below to reset your password:
Recientemente solicitaste que se restablezca la contraseña de tu cuenta de Project Sidewalk. Haz clic en el siguiente enlace para restablecer tu contraseña:


If you did not request a password reset, please ignore this message or send us an email to let us know.
Si no has solicitado el restablecimiento de la contraseña, por favor, ignora este mensaje o envíanos un correo electrónico para informarnos.

The Project Sidewalk team
El equipo de Project Sidewalk

This password reset will be valid for the next 5 minutes
Este restablecimiento de contraseña será válido durante los próximos 5 minutos

**Comment by ThatOneGoat** [comment]
Great, thanks! Will do

**Comment by misaugstad** [comment]
closing via #2057
