### ISSUE TITLE
Change severity of labels placed in tutorial.

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1103]
As many users and interview participants have mentioned, the severity that we instruct users to give in the tutorial needs to be updated. In addition, after reading through the ADA guidelines and creating our labeling code book, I can definitively say that the ratings that we say to use for some of these does not reflect what we are hoping users to rate.

Here is what I think should be changed...

The 1st curb ramp. We instruct users to give a severity of 1. I think this should probably be severity 2, because the ramp directs pedestrians into traffic a bit.
![image](https://user-images.githubusercontent.com/6518824/30712621-9fb51ace-9eda-11e7-9703-768da4f2b3f4.png)

The 2nd curb ramp. We instruct users to give a severity of 1. I think this should probably be severity 2, because there is no landing space at the top of the ramp. I don't think the severity should be greater than 2, however, because the flares/sides of the ramp are not very steep, so it is not too hard to navigate even without landing space.
![image](https://user-images.githubusercontent.com/6518824/30712725-faf3f950-9eda-11e7-9280-f14f30c6813c.png)

@manaswis what have other suggested that the tutorial label severity ratings should be? And are there any others that people thought should be changed?

**Comment by jonfroehlich** [comment]
Thanks Mikey. Very good points. I also think the tutorial should also direct folks to look at the guide (that I hope we can publish soon, adapting it from our codebook).

**Comment by misaugstad** [comment]
Resolved via PR #1310
