### ISSUE TITLE
Onboarding labels show up on the mission stats sidebar

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1105]
During testing on dev server, the onboarding labels are found to be accounted for in the subsequent missions.

![image](https://user-images.githubusercontent.com/2873216/30862676-ba5452da-a283-11e7-9c14-17205593b59e.png)

The 7 onboarding labels shouldn't be part of the other missions. Some recent change has resulted into this side-effect.

**Comment by sarahsmo** [comment]
Hi @manaswis 
I am a bit confused about the source of this problem, and what you expect it to produce. If you have the time to add a bit more detail that would help a bunch!

Thanks!

**Comment by manaswis** [comment]
To verify/test this: Go to the site as an anonymous/registered *new user* by opening the tool in an incognito mode. After you finish the onboarding/tutorial (where you add 7 labels), the new mission that's loaded should have 0 labels set across all stats in the sidebar. **Caveat**: The 0 label counter is true only for new users. If you have already audited before in this neighborhood, the _current neighborhood label counter_ at the top of the sidebar won't have 0.

So if you see 7 labels in the _current neighborhood label counter_ then that confirms that onboarding labels are being counted within this neighborhood which shouldn't be the case.

**Comment by sarahsmo** [comment]
Hi @manaswis 

So I did some testing, was trying to recreate the problem you mentioned above. I went to incognito mode, I did the tutorial. Below is my screen after the tutorial. 
![image](https://user-images.githubusercontent.com/31173144/31186972-52abf9a4-a8fe-11e7-9364-79367a57378e.png)

Then I was directed to my first mission. Below is what my first mission looks like. 
![image](https://user-images.githubusercontent.com/31173144/31187060-a44b56b0-a8fe-11e7-87dd-1abd99525fb2.png)

Note no 7 labels in this mission. Let me know if I am missing something critical or if this problem has been resolved on its own somehow. I can't seem to recreate the problem. 

Thanks!

**Comment by sarahsmo** [comment]
@manaswis did you ever see my comment above? don't know what I should do with this issue because I still can't recreate it.

**Comment by manaswis** [comment]
I will test it again later today. And let you know here.

**Comment by sarahsmo** [comment]
Hi @manaswis 

I pulled recent develop changes, and retested this issue one more time, I believe that it is no longer an issue. Let me know if this is not the case. 

Sarah

**Comment by sarahsmo** [comment]
@manaswis Just wanted to know if you ever got around to this and found out anything?

**Comment by sarahsmo** [comment]
I am closing this issue. I just tested it on the development server and on production. Onboarding labels do not show up in the first mission. I also checked the code to be certain, and there is a condition around the setup of mission label counts that says if(!onboarding).
