### ISSUE TITLE
Legend on landing page choropleth has extra space

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1106]
On develop, space in the legend of the landing page choropleth is more than necessary:

![image](https://user-images.githubusercontent.com/2873216/30870596-19c27908-a299-11e7-99b8-1fd36d8e46d2.png)

This looks like a side-effect of the changes done to the results page choropleth.

**Comment by sarahsmo** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/31173144/30874945-e481698a-a2bf-11e7-9804-9c2c1ec49732.png)

**Comment by manaswis** [comment]
Closed via PR #1107
