### ISSUE TITLE
Fix widow in the advanced neighborhood ovelay

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1110]
From https://github.com/ProjectSidewalk/SidewalkWebpage/pull/1109#issuecomment-332347897:

> The widow is also very bothersome to me. Any ideas on how to fix this so
it's not so aesthetically displeasing?

![image](https://user-images.githubusercontent.com/2873216/30884757-a999ee04-a2c5-11e7-9812-9a0ff57c8f17.png)

**Comment by manaswis** [comment]
Most likely, by increasing the width of the text div, this can be fixed.

**Comment by sarahsmo** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/31173144/30932115-85afcaac-a394-11e7-86db-00cbe59c0253.png)

**Comment by manaswis** [comment]
Can you try reducing the width such that the text doesn't span outside the borders of the underlying  mission screen? I feel now its too wide.

**Comment by sarahsmo** [comment]
@manaswis  is this better?
![image](https://user-images.githubusercontent.com/31173144/30937958-6f752798-a3a6-11e7-9632-9ff01a969bb9.png)

**Comment by manaswis** [comment]
Yes! I like it. Thanks!

**Comment by sarahsmo** [comment]
@manaswis  changes are committed and in pull request

**Comment by manaswis** [comment]
Closed via #1111
