### ISSUE TITLE
Instead of using feet as a unit, use miles

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#112]
Instead of using 1000ft, 2000ft, and 4000ft in the missions, say "(roughly) 1/4 of a mile", "1/2 mile", and "3/4 mile".

**Comment by jonfroehlich** [comment]
I think it's probably OK to keep feet, to be honest, though I do like miles better (as I tend to think that this is the standard pedestrian unit when you talk about walking).

**Comment by kotarohara** [comment]
Updated. Screenshot on #125
