### ISSUE TITLE
HIT preview screen link gives an error

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1124]
Found this when I was testing out HITs for Turkers on production. Clicking the link to our website on the HIT description page throws an error:
![image](https://user-images.githubusercontent.com/3580069/31130827-7bdfe5c0-a826-11e7-9bf4-575a15ad1775.png)
It looks like the preview screen passes an empty string for turker id and the turker signup endpoint cant handle that. We need a quick fix message for this

**Comment by maddalihanumateja** [comment]
A quick fix for this would just be to do it on the HIT description page. I can redirect to a link that depends on whether the user is in preview mode or has already accepted the HIT. (This wont require a pull request for now. Just changing the javascript in the HIT description template)

**Comment by misaugstad** [comment]
As a quick fix, we just made the link not clickable until they accept the HIT. I think that we should still be able to handle this case though so I am thinking of leaving this open. Thoughts?

**Comment by misaugstad** [comment]
The fix we have seems sufficient.
