### ISSUE TITLE
Admin Interface: Coverage Stats

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1125]
Would be great to add some additional sub-rows for both 'Audited Streets' and 'Distance' that show contribution amounts from our various user groups: turkers, volunteers, and registered users.

![image](https://user-images.githubusercontent.com/1621749/31191989-c458b92a-a8f4-11e7-9251-f3dc8b959f76.png)

**Comment by misaugstad** [comment]
Would you want to take this one @tongning ?

**Comment by jonfroehlich** [comment]
Isn't this what @tongning is working on currently? I thought he made a PR but I don't see it referenced here...

**Comment by jonfroehlich** [comment]
As an update, here's a screenshot as of yesterday. Still some bugs to work out before pushed to production. 

![image](https://user-images.githubusercontent.com/1621749/31968292-8cb52b94-b8c5-11e7-8613-0aa832adcace.png)

See: https://github.com/ProjectSidewalk/SidewalkWebpage/pull/1161

**Comment by misaugstad** [comment]
Closing via #1161 and #1175
