### ISSUE TITLE
Simplify the Current Mission Labels field in the Status pane

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#113]
1. Remove the title "Current Mission Labels"
2. Move the Curb Ramp counter below the other counters

**Comment by kotarohara** [comment]
Removed the "Current Mission Labels"

**Comment by danZzyy** [comment]
[label_counter_layout1.pptx](https://github.com/ProjectSidewalk/SidewalkWebpage/files/324258/label_counter_layout1.pptx)

**Comment by kotarohara** [comment]
\cc @jonfroehlich 

I asked @danZzyy to make mocks of for what we discussed a while ago. I prefer the one on the left (which is what we have now); it has a better visual balance when green balls gets filled up. @danZzyy doesn't have preference. As we don't have strong preference within the team, I'm going to keep the current version & close this issue.

**Comment by jonfroehlich** [comment]
Fine. I agree that when there are actually a full set of circles, then it looks good... but when there are not lots of circles like this, I think it's unbalanced to have curb ramps at top.
