### ISSUE TITLE
Change the infrastructure for missions when launching in next city

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1130]
As we have discussed in many places ( #880 #767 #297 #992 #239 ), the architecture for missions is very confusing and inflexible. 
* Missions are specific to each neighborhood.
* Within each neighborhood, the missions have pre-defined distances in a pre-defined sequence that cannot be modified.
* The pre-defined sequence of missions has an odd ordering: 500ft, 500ft, 1000ft, 2000ft (0.38 miles), 1280ft (0.24 miles), 0.5 miles, 0.5 miles, ...
* There is no way to define any sort of mission that is not distance-based.
* The way missions are stored is that the "distance" for that mission is actually the cumulative distance that the user has audited in that neighborhood. So the user sees missions of 500ft, 500ft, 1000ft, but the backend has missions of 500ft, 1000ft, 2000ft; to figure out the distance of a given mission, you have to subtract the distance of the previous mission.

We need to think of an architecture that is much more flexible, where a mission is a central, important unit, not an afterthought like it is in the current system.

_I am creating this thread to consolidate thoughts and work towards a solution. The previous threads are mostly different members of the team being confused, asking for clarification, or talking about small tweaks that we can make to the live system. We clearly need to totally rework the mission structure for the next city, and finding a solution deserves its own, clean thread_

**Comment by jonfroehlich** [comment]
Thanks Mikey. I want to also add that for the distance-based missions, I think shorter is better. First few missions may only be ~one or two blocks and we should never go beyond like a ~7-10 minute mission (we can use past data to figure out what length this corresponds to).

**Comment by misaugstad** [comment]
@jonfroehlich how important would you say it is to have missions that are exactly the same distance across users like we have it right now? Like every user starts with two 500 foot missions. Do you find that consistency important for making comparisons across users and user groups? Is it only important that the first few missions are the same length, and then variation after the first 2 is fine?

I'm just trying to think through how to best organize the infrastructure for missions to make it as flexible as possible, so I will probably have more questions like these; I'm trying to figure out what the constraints are.

**Comment by jonfroehlich** [comment]
Yes, I think it's important that initial mission lengths be roughly the same distance across users--to, as you say, enable comparisons, etc. I also agree that this is probably most important for the first few missions and then could be more variable/flexible after that.

**Comment by misaugstad** [comment]
Closing via #1319
