### ISSUE TITLE
Add street_edge_id column to label table

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1132]
Current process:
* User starts auditing a street edge, and gets a personal audit task id for that street. Any labels they place right now are associated with that id.
* When the user gets near the end of the street, the next street they will audit is chosen, and they get a new audit task id. Any label they place starting now until the next street is chosen is associated with this new id.

Problems with it:
* A new street is chosen something like 20 meters before they reach the end of their current street, so any labels they place in those last 20 meters are actually associated with the _next_ street edge.
* If the user decides to go back and fix a mistake they remembered making, then the new label is associated with a street that it really shouldn't be.
* This all adds a lot of uncertainty into any analysis we may want to do of a specific street edge (for example, comparing audits of the same street from multiple different crowd workers).

So instead of just using the latest audit task id that has been generated, we could associate the audit task id of the nearest street that the user has audited (or is auditing).

Alternatively, any time we do analysis, we could figure out which street a label is closest to, doing that computation for all labels post-hoc. However, this could add a lot of complexity to analyses that shouldn't be that complicated.

Thoughts?

**Comment by jonfroehlich** [comment]
The current implementation seems icky. I'm curious why it was implemented that way.

Not sure how to move forward. Seems like something we'd want to fix for next city deployment at least.

**Comment by misaugstad** [comment]
Agreed. Let's start by planning to implement it for the next city. As we try to add tools for verification or the like, we will see how much this issue gets in our way. I do think that there is a way for us to make these modifications after the fact, but it may be tricky and imperfect, so it would be best to leave it for post DC.

**Comment by misaugstad** [comment]
Another alternative is to add a `street_edge_id` column to the `label` table. And whenever a label is placed, we find which street it is closest to and include that id along with the label.

**Comment by misaugstad** [comment]
clossing via #1470
