### ISSUE TITLE
Need to differentiate missions with bonus rewards from base reward missions for Turkers

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1137]
In our HIT description for Turkers on production we mention that the base reward is for completing the onboarding and first mission. Payment for any additional (non-mandatory) missions will be in the form of bonuses. Our UI should also explictly say this. The turker should could be shown a popup that says something on the lines of "You have successfully completed the missions required for the base reward. Would you like to continue working on some bonus missions?"

**Comment by jonfroehlich** [comment]
"You have successfully completed the missions required for the base reward. You can now continue completing as many missions as you'd like, which we will reward via bonuses"

**Comment by misaugstad** [comment]
Having run HITs on mturk for awhile now, it doesn't seem like turkers are really confused by the setup we have. So I don't think that adding in specific text to a mission like this is particularly useful. It's not a bad idea at all, but I think that our interface is so flexible right now that I don't want to add in something like this at specific times. Especially with the possibility for it to show up at the wrong time.
