### ISSUE TITLE
Update the Current Mission status during the onboarding

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#114]
![image](https://cloud.githubusercontent.com/assets/612263/15979926/32ccbbda-2f35-11e6-9ce0-0d6628119e6a.png)

The mission progress bar stays "0%." during the onboarding. Update the % as the onboarding progress.

**Comment by jonfroehlich** [comment]
Can you fix this before I do the planned think aloud pilot study?

**Comment by kotarohara** [comment]
done
