### ISSUE TITLE
Remove redundant choropleth code

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1144]
We now have 5 choropleths, where the code is nearly identical among them, with just small tweaks to the coloring of the regions, text in the popups, and possible addition of other layers (like the ones that include labels). It shouldn't be too hard to consolidate this code.

When creating a choropleth, I guess the script that calls this code could just pass in a few parameters that determine color/text in popups/etc. This could probably save us like 300-500 lines of code. And every time a change needs to be made to all the choropleths, we would no longer have to make that change to each choropleth individually.

**Comment by misaugstad** [comment]
I am going to be making another nearly identical choropleth (#1166), so I think it is really time that I do this!

**Comment by misaugstad** [comment]
Note that you can even pass in functions as parameters here. That might be useful as well.

**Comment by misaugstad** [comment]
@MattJ12 you've had to edit all 6 or so choropleths multiple times now. How would you like to take a stab at consolidating them??

**Comment by MattJ12** [comment]
> @MattJ12 you've had to edit all 6 or so choropleths multiple times now. How would you like to take a stab at consolidating their code??

Sure!
