### ISSUE TITLE
Admin Interface: Placement of label in the label view panorama seems to be incorrect

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1147]
This might be due to
 - Incorrect placement of labels by the user
 - Incorrect calculation of the position of the label in the panorama by the visualization code.
Needs investigation
![](https://files.slack.com/files-pri/T5G48AFJN-F7K5H26LV/image.png)

**Comment by maddalihanumateja** [comment]
![image](https://user-images.githubusercontent.com/3580069/31633727-4d3f25b4-b28f-11e7-83f8-2cbbf7ebed25.png)

**Comment by misaugstad** [comment]
This definitely seems to be that calculation of the position of the label on the panorama is off. @manaswis what do you think might be the cause? And do you think it is something that an undergrad could fix without too much trouble?

**Comment by misaugstad** [comment]
Closing via #1308
