### ISSUE TITLE
Admin Interface: Map Checkboxes Malfunctioning

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1150]
https://youtu.be/N5buE-SqwZU

Specifically seems to be No Sidewalk, Can't See Sidewalk, etc.; however, perhaps the problem is more widespread and it's just harder to detect with other label types (e.g., maybe the bug is that only a fraction of labels are shown and since we have so many labels, it's too hard to detect that).

**Comment by misaugstad** [comment]
Closing because it is a duplicate of #527
