### ISSUE TITLE
Registered User Completed 27 Missions But Provided Zero Labels

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1157]
We should check into this person:

![image](https://user-images.githubusercontent.com/1621749/31900444-33170d8e-b7d3-11e7-960b-11f3e4020d90.png)

**Comment by misaugstad** [comment]
I think that the bigger issue with this image is that it says that they've only audited 3 streets, but they have 27 completed missions :grimacing:

**Comment by jonfroehlich** [comment]
So. Definitely something seems wrong with the calculations, right?

**Comment by misaugstad** [comment]
This is part of the DC dataset, so I'm assuming that there isn't much value in investigating this. Closing for now.
