### ISSUE TITLE
"Nearly half of DC" text on the landing page needs to be updated

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1159]
![image](https://user-images.githubusercontent.com/2873216/31912099-b357ad2c-b7f7-11e7-8d38-9976cc96a5f4.png)

This should have been updated when we made the number of miles dynamic.

Anyway, here are some options for the updated text:

- Users like you have almost completely mapped the accessibility of Washington DC. That's 987 miles—more than the distance from DC to Boston.

- Users like you have almost mapped the accessibility of Washington DC. That's 987 miles—more than the distance from DC to Boston.

- Users like you have almost covered the entire city of Washington DC. That's 987 miles—more than the distance from DC to Boston.

Which do you prefer? Suggestions are welcome for more generic text or other options. @jonfroehlich @misaugstad @maddalihanumateja

**Comment by jonfroehlich** [comment]
I suggest a more generic version:
Users like you have already mapped XXX miles of Washington DC--that's nearly XX% of the city!

When we have reached 100%, change it to something like this:
We did it! Users like you have mapped all XXX miles of Washington DC. However, we are not done. The more users who contribute, the better quality data. So start mapping today!

**Comment by manaswis** [comment]
Yeah, I like that. It's a good sentence version of the stats.

And we can put an if clause for the 100% text. Based on the percent complete, the appropriate text would be selected. That way we don't have to do another PR.

**Comment by jonfroehlich** [comment]
Yes, sorry, I meant to explicitly say that my recommendation was dynamic text with a conditional on 100%

**Comment by manaswis** [comment]
Sounds good!

**Comment by misaugstad** [comment]
Closed via #1168
