### ISSUE TITLE
Bug in Froehlich Audit Data?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#116]
From the dashboard, it looks like I audited part of Potomac Park close to the federal monuments, but I don't remember every doing this. Is there a way to verify that I actually walked all of this way (also, based on the gray line, it looks like I didn't contribute very many--if any--labels during this part of my audit, which is unlike me).

![image](https://cloud.githubusercontent.com/assets/1621749/15985331/961b7ee2-2fb7-11e6-9ca9-a9681531e3a2.png)

Maybe something for @danZzyy to look into?

**Comment by jonfroehlich** [comment]
@kotarohara said this over email:

> Could be a bug. Actually could be because of really old bug in which incomplete tasks were marked as completed in the database. Or maybe the JavaScript code is just showing both completed and incomplete street edge. Or maybe the SV becomes unavailable in the mid-way and you skipped the task (the task will be marked completed if you skip and choose the option "There is no SV"). I'll take a look when I get a chance.

**Comment by jonfroehlich** [comment]
@kotarohara, can you investigate this as well?

**Comment by kotarohara** [comment]
It would be great if @manaswis or @Soben713 can try to figure out what happened, but I'll work on it if they don't think they can.

**Comment by jonfroehlich** [comment]
I think it's important to investigate in case it is a bug that affects other data as well. @Soben713 has an analysis tool that might help us investigate this a bit.

**Comment by kotarohara** [comment]
Cool. @Soben713 , do you want to spend < day looking into this? More specifically:

- the JavaScript code is just showing both completed and incomplete street edge (I don't think this is the case)
- the SV becomes unavailable in the mid-way and Jon skipped the task in the midway
- some other case.

**Comment by Soben713** [comment]
This is not part of v2, so I can take a look at this after mid-November, I'll probably have some useful metrics by then.

**Comment by misaugstad** [comment]
Whatever the cause of this issue, it is no longer a problem in the code we're using in our new cities.
