### ISSUE TITLE
Placed a label on the street view map, but the label does not show on smaller side map

### ISSUE THREAD

**Issue by sarahsmo** [ProjectSidewalk/SidewalkWebpage#1160]
![image](https://user-images.githubusercontent.com/31173144/31914945-b36a2df8-b81a-11e7-8e9c-0ad7db4a3b65.png)

When auditing the neighborhood above, my placed label was not showing up on the mini-map on the side (as seen in the picture above). 
This occurred for street edge id : 14435 and pano id: jjROv4904Zm4cQRP368BsQ

**Comment by jonfroehlich** [comment]
Like I said on Slack, which you didn't mention here, I suspect that this is because we either don't have depth map data for that pano or the depth data to location translation was off for this pano.

**Comment by misaugstad** [comment]
This has been fixed since we are now using a method of lat-lng estimation that does not use depth data. But Jon was right, if there was no depth data (or the call to the depth data API happened to fail that time), the label would not show up on the mini map.
