### ISSUE TITLE
Reviewing Anonymous Contributions: Many IPs Show High Audit Counts with Zero Labels

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1162]
From the Admin Interface, you can see that there is a large number of ip addresses that apparently have completed a large number of audits but have provided zero labels. These need to be reviewed and investigated:

![image](https://user-images.githubusercontent.com/1621749/31925667-1f40bee2-b83f-11e7-84b9-a8f86902f761.png)

Is there a bug in the table or are there literally dozens of ip addresses that completed audits with no labels... :(

I think @manaswis or @misaugstad should likely take this one.

**Comment by jonfroehlich** [comment]
It was also my understanding that four of the anon routes that we chose for GT had *zero* labels and that this was, unfortunately, never checked when deciding on anon routes to use for our GT experiments.

**Comment by misaugstad** [comment]
With PR #1215 we implemented a priority routing system which computes the labeling frequency for each user (including anon users), and significantly discounts audits made by users with low labeling frequencies (such as the users shown in the above image). Thus, I believe this is has now been addressed. Closing this now.
