### ISSUE TITLE
User contributions need to be weighted by their reliability as well

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1164]
![image](https://user-images.githubusercontent.com/3580069/32018383-b3fc7ed2-b997-11e7-8e4e-97b7db50ea84.png)

Something that surprised me was that the monumental core region had a relatively high severity rating according to the current publicly visible results page. This seems to be due to a single turker who might have misunderstood where issues like "Missing Curb Ramp" need to be placed. If we had a validation interface for the labels we could assign a ranking to PS users based on how many labels they got wrong. The reasons for why the user labelled incorrectly may not be malicious and the work might have been done in good faith. The user ranking can acts as weights for the AccessScore model. Removing labels of potentially malicious users is not a good alternate solution in my opinion. Weighting them is a better approach.

**Comment by jonfroehlich** [comment]
Yes. Thank you Teja for pointing this out along w an example. Everything in PS should be viewed probabilistically. We should design tools w that in mind. Should be key design principle. All labels should have confidence rankings. All labelers should have confidence rankings. Etc.

**Comment by misaugstad** [comment]
This is now reality! We determine user quality, use that to inform clustering, then use those clusters on the results page now!
