### ISSUE TITLE
Apply for Viz for Social Good

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1171]
I spoke with Chloe Tseng today--the founder of Viz for Social Good. She reached out about collaboration opportunities between Project Sidewalk and her organization, which provides collaboration opportunities primarily for non-profits to visualize data that they are collecting in unique ways.

https://www.vizforsocialgood.com/launch-a-project

Ideally, we could fill this out by the end of the first week of November, 2017 :)

**Comment by misaugstad** [comment]
@jonfroehlich do you still see a use for a collaboration like this? Should we be pursuing this?

**Comment by jonfroehlich** [comment]
We can close this.
