### ISSUE TITLE
GIS Day Notes

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1182]
There are only a few notes from the 1.5 hour mapathon during GIS day today, 11/15/17:

* Most people said that the tool was intuitive, clear, and easy to use (although they were all tech savvy, I believe)
* 8 people attended, auditing ~6 miles (very rough estimate)
* ~half of them had attended one of the sessions last year, and already had an account.

A few small issues:
* The rare issue #847 came up once (this seems to happen very very rarely, and we haven't found a reliable way to reproduce it)
* There was one instance of missing GSV imagery (so the pano looked all black), which was paired with a broken GSV arrow link that just sent the user back to the pano they were just at. So the experience was that their pano was all black, they would try to step forward (there was only one possible direction to go), and it would land them back at the same position. They quickly refreshed the page to deal with it, without my prompting. I am pretty sure that both of those issues are GSV issues, not something on our end, and it seems that this was an unlucky coincidence where both bugs appeared at the same time!
* ~2 people asked about how to label curb ramps where there is only one curb ramp at a corner (for 2 crosswalks).
* ~2 people (that we saw) were not placing any no sidewalk labels until prompted.

@maddalihanumateja add in anything that I may have missed!

**Comment by jonfroehlich** [comment]
> ~2 people asked about how to label curb ramps where there is only one curb ramp at a corner (for 2 crosswalks).

So, you mean the case where a curb ramp is placed diagonally on a corner and intended to be used for both crosswalk directions? (I think we cover this in our ground truth codebook).

> ~2 people (that we saw) were not placing any no sidewalk labels until prompted.
Whatever happened to this redesign to push this label type to the top-level? Didn't @johannkm work on this?

**Comment by maddalihanumateja** [comment]
> the case where a curb ramp is placed diagonally on a corner and intended to be used for both crosswalk directions? (I think we cover this in our ground truth codebook).

Yup, the very same. I think it shouldn't be an issue when we have a public version of the codebook (assuming we can detect when users are confused and prompt them to look at the codebook) 

> Whatever happened to this redesign to push this label type to the top-level? Didn't @johannkm work on this?

[Bringing the no sidewalk label outside the "other" menu](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/772) seems to have stalled on a label color decision.

**Comment by misaugstad** [comment]
I believe we either opened issues for things or addressed concerns here using the labeling guide!
