### ISSUE TITLE
Admin page stats dashboard needs to be consistent

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1183]
Noticed that the table shows 0 users for the day but 11 labels placed. This is due to users only placing labels in the tutorial. The Today and Yesterday column  should be updated to have same format as Overall column. 

![image](https://user-images.githubusercontent.com/3580069/33283965-7743f6ac-d37b-11e7-944d-c2328b1ee4ac.png)

**Comment by tongning** [comment]
In my local testing, for Registered and Anonymous, the Today counter did not increment even after completing a mission beyond the tutorial. For turkers the counter did increment, but only after completing a task beyond the tutorial. Haven't tested with the Researcher role yet.

**Comment by misaugstad** [comment]
@tongning when you completed a mission, did you also complete an entire task? Or was the mission shorter than a full "street edge"? Because that code only checks for completed audit tasks, not for missions.

**Comment by tongning** [comment]
Ah yes, I completed what the user sees as a mission. That might have been
less than a full street edge.

**Comment by misaugstad** [comment]
At some point I updated the today/yesterday columns to have the same format as the overall column, done!
