### ISSUE TITLE
Results Choropleth: Three Key Improvements

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1184]
I realize that the Results Choropleth was thrown together quickly just to present some tangible, easy-to-understand visualization of the data that we are collecting. However, we need to make three key improvements:

1. As noted [here](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/909), the load time is ridiculous--now up to almost 1 minute.

2. The "sidewalk problems per mile" calculation needs to handle the missing sidewalk label differently. Two options: (1) we completely remove missing sidewalks from this visualization (easiest)--this includes the choropleth coloring calculating as well as the mouseover tabulation; (2) we come up with a new algorithm like just counting one missing sidewalk per street segment--this seems simple and appropriate.

3. We need to shift the visualization from showing raw labels to showing issues (i.e., post-processed labels that have been clustered), which is what Mikey has been working on.

**Comment by misaugstad** [comment]
After I finish #1242 @aileenzeng can take a look at what the loading time is like, and see what other improvements can be made.

**Comment by jonfroehlich** [comment]
This also relates to recent work by @tongning (AccessScore) and @manaswis (AccessVisDC) -- though the current version of the results choropleth is more closely related to AccessVisDC. Ideally, I think, it would be best if the results chropleth was simply @manaswis's AccessVisDC tool (or some version of it) that also allowed people to:
- quickly view and assess city neighborhood accessibility
- determine where we may need more help and select a new neighborhood for work
- review and validate labels/clusters.

Having a nice interactive vis like this would enable us to restructure how we advertise Project Sidewalk--our hook becomes this vis, which demonstrates clear value, and then people (hopefully) will contribute because they understand the ROI and they want the vis to be accurate.

**Comment by misaugstad** [comment]
Yeah I agree. We have the basis for much better visualizations, so it would be best to replace the current viz with one of those, instead of pouring dev time into small improvements to what we have.

**Comment by misaugstad** [comment]
PR #1321 makes significant improvements here. We now use clustered attributes instead of raw labels, and the load time is closer to 5 seconds (still not fast enough though). Still more improvements to make, so leaving this open.

**Comment by misaugstad** [comment]
The only unresolved piece of this issue is changing how we calculate "missing sidewalks per mile". This is captured in #1163 so I'm going to close out this issue.
