### ISSUE TITLE
Missing turker interaction data 

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1186]
@johannkm had reported that the audit_task_interaction was missing data for some turkers on the mturk database dump he was provided. We need to ascertain the reason for this @johannkm could you provide some more context for this

**Comment by jonfroehlich** [comment]
Yes, @johannkm can you expand, in detail, on what you discovered and why you think data is missing.

**Comment by johannkm** [comment]
I don't think we're missing data in the production database, just that the turker dump I have is not the same as what @misaugstad used to generate the precision/recall labels. I'm messaging him to figure out the discrepancy. 

To demonstrate, this is the first row of the turker precision/recall table:
```yaml
condition.id: 70
worker1: A3PPRVK6XK6GP5
```

But this query returns no results:
```sql
SELECT *
FROM sidewalk_turker.sidewalk.amt_assignment
WHERE turker_id='A3PPRVK6XK6GP5' AND condition_id=70
```

Out of 275 unique `(condition.id, worker1)` pairs from the precision/recall table, only 71 had entries in `amt_assignment`.

**Comment by misaugstad** [comment]
I just ran this on my own dump, and that query does return data for me.

I am creating a dump of what I have to give to Johann for now.

@maddalihanumateja could you check that the above query yields 3 rows on the server? (turker one)

**Comment by maddalihanumateja** [comment]
@misaugstad and @johannkm . I got 3 records when I ran that query directly on the mturk database.
![image](https://user-images.githubusercontent.com/3580069/33572579-4fe9cace-d901-11e7-9e1b-632c88cfb9e0.png)

**Comment by misaugstad** [comment]
perfect, seems it is just hit dump, sending him the new one then

**Comment by johannkm** [comment]
Got the new dump, and it works.
