### ISSUE TITLE
I want to jump to a new *neighborhood*. This is not currently possible

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1188]
As we get closer to 100%, I find myself wanting to jump to a new *neighborhood* that is close to completion. This is not currently possible in the auditing interface. You have to back out to the front page and manually select something. 

In addition, the neighborhood I'm currently auditing is 100% complete (I know it is, because I finished it!); however, when the message came up to continue in neighborhood or go to a new one, I selected the former (continue in neighborhood) because I just wanted to complete the street I was on. But now I don't have an easy way to go to a new one.

**Comment by misaugstad** [comment]
As @jonfroehlich mentioned on Slack, it could be added as an option in the 'Jump' button.

**Comment by jonfroehlich** [comment]
> As @jonfroehlich mentioned on Slack, it could be added as an option in the 'Jump' button.

Right. This is what I meant in my original issue. :) Jump -> jump button.

**Comment by misaugstad** [comment]
closing via #1786
