### ISSUE TITLE
Add audited distance to today/yesterday table on admin page

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1189]
The coverage stats chart has total distance audited by each user type, but the today/yesterday table only has the label counts and audit counts. We should just add a row at the bottom, just like the audit counts one, that has the total distance in miles.

Distance audited is the metric that we really want to know; we often will find the average distance of a street edge, then use that to estimate the distance audited on a day using the number of streets audited. Wouldn't it be better to just have the metric we want to have right there? :)

**Comment by kumararoosh** [comment]
![image](https://user-images.githubusercontent.com/24703104/80891497-3bc63b80-8c79-11ea-96e3-048744b8b49b.png)

**Comment by kumararoosh** [comment]
new admin table

**Comment by misaugstad** [comment]
Looks good! Did you test that it works for today and yesterday?

**Comment by kumararoosh** [comment]
Yes it was tested now and back when i botched the branch creation and based it off of master

**Comment by misaugstad** [comment]
closing via #2089
