### ISSUE TITLE
Need to be able to remotely logout users

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1192]
This would be useful when we need turkers to only work for a fixed amount of time, a fixed number of missions, or if we detect below-par quality of work. We could display a popup that shows a message from the admin indicating why they've been logged out.

**Comment by misaugstad** [comment]
Oops, it seems that I duplicated this issue just 3 days later somehow, #1197 

Keeping the other one because it has a thread.
