### ISSUE TITLE
Admin dashboard user page should have a default value for the current region

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1193]
@manaswi had found that truncating the user_current_region_table when trying to assign users new neighborhoods caused a runtime error when trying to display user dashboards.

> onError Happened
> Execution exception[[NoSuchElementException: None.get]]

The reason for this is that the dashboard displays the current neighborhood on the dashboard and truncating the table that holds this information cause a get error. This is just an error that affects displaying the page and can be resolved by having a default 'currently not assigned' string for the neighborhood.

**Comment by misaugstad** [comment]
Looks like whoever wrote this didn't use Scala the way they were supposed to :smirk: I'll do a quick fix for this.

**Comment by misaugstad** [comment]
Right, and this isn't the user dashboard, it is when you look at a specific user through the admin dashboard, just to clarify. The public-facing user dashboard works fine.

**Comment by manaswis** [comment]
Closed via #1195 and #1204
