### ISSUE TITLE
Self-Rate Confidence in Label

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1196]
For deployment into next city, perhaps pop-up rating dialog box could include some self-assessment of confidence in the label (like that this is actually a problem...)

I've mentioned this before but can't find an actual Issue for it...

**Comment by jonfroehlich** [comment]
This is also something that @aileenzeng could do... (if we decide to prioritize it)

**Comment by misaugstad** [comment]
@jonfroehlich do you think this is something that would be useful for our upcoming deployment? we could probably find someone with cycles to implement this

**Comment by jonfroehlich** [comment]
Ugh, I don't know. I think the pop-up interface is already getting so busy and if we add this, I think we'd have to do a complete redesign. Also, now that we have validation missions, perhaps this becomes less important? I'd still like to keep this ticket open but I think we could take off the NextCity tag (and shift it to generation 3 discussions).

**Comment by misaugstad** [comment]
I totally agree with all of that.

**Comment by misaugstad** [comment]
I think you're right that we don't need this given the validation interface.
