### ISSUE TITLE
Unable to reach 100% completion of DC

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1200]
We have been stuck at 1075.1 of the 1081.1 miles of DC completed, and haven't been able to go any higher.

I have been investigating this, and I believe the issue to be that we have some number of entries in the `street_edge` table that are _not_ marked as deleted, even though the only entry in the `region` table they are connected to _is_ marked as deleted. This makes it so that when we do our aggregate computation (sum length of all non-deleted street edges), the streets are included, but when we actually assign streets, there is no neighborhood that these streets are in, so they never get assigned.

Thus, the problem seems to be that the actual distance in DC is _not_ 1081.1 miles, it is actually less! I am going to figure out which streets these are, try marking them as deleted, and see if that fixes the problem completely.

**Comment by jonfroehlich** [comment]
Thanks @misaugstad, that would be great!

**Comment by misaugstad** [comment]
Here are the before pictures:
![before-landing](https://user-images.githubusercontent.com/6518824/34049326-fd1f2fc8-e184-11e7-8512-a5e297d44c10.png)
![before-admin](https://user-images.githubusercontent.com/6518824/34049329-ff1bc6ce-e184-11e7-97e3-3388ddce0008.png)

On the admin page, you can see that there are 81 street edges that we haven't been able to complete. In fact, only 77 of those have the problem I described above, another 4 are just missing any entry at all in the `street_edge_region` table.

I am going to post the query in this issue thread, since I can't really use the query directly in the evolutions file. I could use it for the "ups" portion of it, but there is no way to programmatically figure out which entries I modified, so the actual evolutions file just has the list of street edges that I found using this query. Aaaand here is the query, for the sake of record keeping:
```
SELECT DISTINCT(street_edge.street_edge_id)
FROM street_edge
LEFT JOIN street_edge_region
ON street_edge.street_edge_id = street_edge_region.street_edge_id
LEFT JOIN region
ON street_edge_region.region_id = region.region_id
LEFT JOIN
(
  SELECT street_edge_region.street_edge_id, region.region_id
  FROM region
  INNER JOIN street_edge_region
  ON region.region_id = street_edge_region.region_id
  INNER JOIN street_edge
  ON street_edge_region.street_edge_id = street_edge.street_edge_id
  WHERE region.deleted = FALSE
    AND street_edge.deleted = FALSE
) "r"
ON street_edge.street_edge_id = "r".street_edge_id
WHERE street_edge.deleted = FALSE
  AND (region.deleted = TRUE OR street_edge_region.region_id IS NULL)
  AND "r".region_id IS NULL;
```

And here is what the landing page and admin dashboard look like now!
![after-landing](https://user-images.githubusercontent.com/6518824/34049512-a9dd5f46-e185-11e7-873e-226876c1879a.png)
![after-admin](https://user-images.githubusercontent.com/6518824/34049513-a9e6d774-e185-11e7-86d5-3db33c708618.png)

**Comment by misaugstad** [comment]
We are now able to reach 100% completion :)
