### ISSUE TITLE
Write Up Documentation On How to Deploy to Production

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1202]
@manaswis needs to write-up comprehensive documentation on how to deploy our code to production so that others (starting with @misaugstad) can do this. Ideally, she would do this soon (while in India).

**Comment by misaugstad** [comment]
The deploy instructions are located [here](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Deploying-code-to-the-server).
