### ISSUE TITLE
Need better syncing between Mturk HITs and Turker session management on PS website

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1203]
Rather than putting the onus on the Turkers to to complete missions before expiration time we need to have code in place that enforces this automatically. We need to use HIT specific metadata (pay, duration) to better manage Turker sessions on the PS website. For example: Session duration should be restricted by the specific HIT type that was taken up by the Turker. 
1. There needs to be better synchronization between the HITs we post on MTurk in the future and turker accounts on our website. If the HIT duration is 2 hours then the turker could be shown a popup displaying time available to work on the HIT and auto-logged out of the account when a session timer runs out. 
2. The conditions for mission approval should be made more visible to the turkers so they don't have a chance to skip reading them (probably have an "I have read the conditions and agree" kind of checkbox or a "This HIT will expire in x time and the countdown will be visible here:" message). 
3. The resume HIT could be used to extend the amount of time available to work on the HIT. Sessions that are associated with these kind of HITs should not reset the session expiration counter.

**Comment by misaugstad** [comment]
Not sure how this slipped through and wasn't included on my list of must-haves for future deployments, but this one is really important. It makes things much clearer for turkers, it will drastically decrease the confusion and miscommunication between turkers and researchers. This will also significantly decrease the amount of time researchers have to spend monitoring turkers to make sure they aren't working past their allotted time, and we won't have to respond to a bunch of queries related to this :)

**Comment by misaugstad** [comment]
closing via #1360
