### ISSUE TITLE
Admin Dashboard Now Times Out Probably Due to Long Queries

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1205]
With @tongning's new turk dashboard code, the admin dashboard (analytics tab) on production no longer fully loads. The console shows proxy error but I would guess that the load just times out. See screenshot:

![image](https://user-images.githubusercontent.com/1621749/34416911-a48d7c9a-ebaa-11e7-9f90-0418f574a1df.png)

**Comment by misaugstad** [comment]
Fixed this by taking out the `audit_task_interaction` queries!
