### ISSUE TITLE
Finish implementing priority-based routing on front-end

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1207]
As we noted in PR #1206 routing along least-audited streets is not fully implemented on the front-end. It is only treated as a binary right now (audited or not audited). The logic that we want to use is that a user is auditing one of the least-audited streets in that neighborhood.

Since we are also switching over to using priority values instead of number of audits, we won't actually be implementing the above, but we will implement an analog using priority. I see us doing the following:

1. Discretize the priority range into a few bins (somewhere in the range of 2 to 10)
2. Implement the analog to auditing "least audited" streets, i.e., a user is always routed down a street in the highest priority range (across that neighborhood)

When picking the number of bins for the priority range:
* A _greater_ number of bins will lead to the highest priority streets being audited _faster_, but will lead users to jump _more_.
* A _fewer_ number of bins will lead to the highest priority streets being audited _slower_, but will lead users to jump _less_.

**Comment by misaugstad** [comment]
I think this is going to be my next task. As of the merging of PR #1206, the description above holds, except that if there are multiple street edges connected to the current street edge, the one with highest priority is chosen. I am now going to implement exactly what I mentioned above (quoted below):

>1. Discretize the priority range into a few bins (somewhere in the range of 2 to 10)
>2. Implement the analog to auditing "least audited" streets, i.e., a user is always routed down a street in the highest priority range (across that neighborhood)

**Comment by manaswis** [comment]
Closed via #1212 and #1218
