### ISSUE TITLE
Unwanted Selection

### ISSUE THREAD

**Issue by myjeeed** [ProjectSidewalk/SidewalkWebpage#121]
Sometimes when you click to drag, you suddenly select the whole GSV interface (or just parts of it like the screenshot below) and it's a little bit distracting!
![screen shot 2016-06-14 at 1 03 56 am](https://cloud.githubusercontent.com/assets/9346800/16031690/19a833fc-31cc-11e6-8a16-8efadaec23f0.png)

**Comment by myjeeed** [comment]
Or sometimes like this the UI buttons get selected.

![screen shot 2016-06-14 at 1 09 06 am](https://cloud.githubusercontent.com/assets/9346800/16031734/a406d04e-31cc-11e6-97a1-15aef058b8db.png)

**Comment by kotarohara** [comment]
Thanks!

**Comment by jonfroehlich** [comment]
@kotarohara: any idea why this is happening?

@myjeeed: why are you dragging in the first place? I don't think there are any interactions that require dragging...

**Comment by myjeeed** [comment]
I meant click and dragging to pan in the street view

**Comment by jonfroehlich** [comment]
Ah, interesting. I've never had this happen to me in all my years using this interface (at least I don't remember it happening). I could definitely see this as a confusing problem for an ordinary user. Can you explain how/when this occurred?
