### ISSUE TITLE
Add priority functions for user experience and labeling frequency

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1211]
Once the new priority-based routing system is merged, we need to add a few more priority functions. In particular, we are going to start off with total distance that each user has audited, as well as their labeling frequency (labels per distance). More details forthcoming.

This will guide the next round of turkers to audit streets that have been audited by users that we suspect may be poor labelers.

**Comment by misaugstad** [comment]
@jonfroehlich here are the different options we had discussed during our 1:1 yesterday.

We plan to split our users into two groups; those above and those below some labels/distance threshold. Now we need to decide how to treat the audits of these users when it comes to street priority. For reference, here is our current way of calculating street priority:
`priority = 1/(1 + audit_count)`

And some options for how we treat users with a low labeling frequency:
1. Treat their audits as if they never happened, i.e.,
    `priority = 1/(1 + good_user_audit_count)`
2. Discount their audits by some factor, i,e,
    `priority = 1/(1 + good_user_audit_count + 0.25*bad_user_audit_count)`

I like using the 2nd option. I think that a street that has been audited once by a "good" user should have a higher priority than a street that has been audited once by a "good" user and ten times by "bad" users. If these are truly "bad" users, we could completely ignore their audits. However, our current method of using a labels/distance threshold is a very coarse filter.

On the other hand, we do have another motivation: we want to have 100% of DC audited by at least one "good" user for when we analyze data for CSCW18. Because of that, I think that if the `good_user_audit_count = 0`, we set priority = 1, and if it is greater than 0, we should use the 2nd option.

Thoughts?

**Comment by jonfroehlich** [comment]
One clarification:

> here is our current way of calculating street priority: priority = 1/(1 + audit_count)

By "current," you mean on production right now--what we've conventionally been using this whole time?

I agree with your final conclusion: if good_user_audit_count = 0, we set priority = 1, and if it is greater than 0, we should use the 2nd option.

**Comment by misaugstad** [comment]
>By "current," you mean on production right now--what we've conventionally been using this whole time?

Basically, yes. The actual street priority code that has this isn't on production yet, but what we have on production (auditing streets with a minimum `audit_count`) works out the same way as the `1/(1 + audit_count)`

**Comment by misaugstad** [comment]
Oh, do we want to treat researchers the same way that we treat users with low labeling frequency so that we have crowd workers having audited 100% of DC? I'm not sure what the overlap is, but researchers have audited 18% of DC, so that would add a _maximum_ of 195 miles to be re-audited.

If you think this would be a good idea, but the possible additional distance to be re-audited is daunting, I can calculate what the actual overlap is with crowd workers. But I'm crossing my fingers that you don't need that info to decide :upside_down_face:

**Comment by manaswis** [comment]
Closed via #1215 and #1218
