### ISSUE TITLE
Add real-time updating of street priority

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1213]
I think that we need at least a partial update of street priority in real time. At least the portion that is based on the audit count for the street should be easy to update after someone finishes an audit. This would be very fast as well. We don't have to take into account how good we think the user is at labeling at this point, we just need the system to respond once a street has been audited.

Then we could have the entire table updated once per day at a time that isn't typically busy.

The main reason we need this is so that we don't have the same streets being done repeatedly on a single day if we have high traffic. If 5 new users come in on the same day and we don't update priority throughout the day, each user will likely be assigned to the same neighborhood, and will probably audit the same streets as well.  To make sure that consecutive users are routed along different paths, we need to be able to dynamically update the priority of the streets.

**Comment by manaswis** [comment]
Closed via #1216 and #1218
