### ISSUE TITLE
Bug in audited paths: the paths stay after the 'mission complete' pop up

### ISSUE THREAD

**Issue by myjeeed** [ProjectSidewalk/SidewalkWebpage#122]
Look at the bottom left corner:

![screen shot 2016-06-14 at 1 17 20 am](https://cloud.githubusercontent.com/assets/9346800/16031844/05bb5ac0-31ce-11e6-995d-096ac32cdfa8.png)

This is also a picture of the mission complete pop up:

![screen shot 2016-06-14 at 1 17 09 am](https://cloud.githubusercontent.com/assets/9346800/16031851/11585388-31ce-11e6-9e21-e620beb77462.png)

**Comment by kotarohara** [comment]
Ha, good catch! Not sure why it is happening all of sudden.

**Comment by jonfroehlich** [comment]
This bug still exists.

![image](https://cloud.githubusercontent.com/assets/1621749/16288099/8dd7a956-38b6-11e6-93f9-b02a52f2e821.png)
