### ISSUE TITLE
New (non functional) mini map expand/full screen button?

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1221]
I noticed this while doing some testing today... In google maps, there is an expand/full screen button on the mini map when in GSV, seen below on the bottom left:

![expand-button-gmaps](https://user-images.githubusercontent.com/6518824/37066746-d78edaa8-2174-11e8-92c2-42a45cc9afb8.png)

When you click on it, the mini map expands, like so...

![expanded](https://user-images.githubusercontent.com/6518824/37066761-e8a7f36a-2174-11e8-89a1-0a00bf6bfb1e.png)

I looked through a bunch of old screenshots from using Project Sidewalk, and I did not see the expand button on the mini map anywhere. But I just noticed the expand button is on the mini map now! Here is a screenshot from today.

![api-change](https://user-images.githubusercontent.com/6518824/37066791-024bf230-2175-11e8-803e-fa9fa33eaeb6.png)

The button doesn't do anything if you click on it. Is this a result of some google API update? Can we get rid of this little thing on the mini map..?

**Comment by misaugstad** [comment]
closing via #2179

**Comment by misaugstad** [comment]
lol the button is back, and bigger!

![Screenshot from 2021-02-25 19-06-18](https://user-images.githubusercontent.com/6518824/109249472-9d254100-779c-11eb-8400-365e3efb907a.png)

**Comment by misaugstad** [comment]
@itsyeonjoon can you post the links to any posts you made on Google forums or Stackoverflow, etc?

**Comment by misaugstad** [comment]
@itsyeonjoon did you try to use the tools in the browser's developer console to figure out info about the button at all? I just tried it out and was able to locate the button. It shows you the CSS class names so you should be able to hide the button easily enough given that info.

**Comment by misaugstad** [comment]
Oops here's a screenshot:
![Screenshot from 2021-04-17 14-24-06](https://user-images.githubusercontent.com/6518824/115127138-ffbee000-9f88-11eb-884b-f349697708be.png)

**Comment by misaugstad** [comment]
I also think I had tried something like this in the past, but maybe it will work now lol: https://developers.google.com/maps/documentation/javascript/examples/control-disableUI

**Comment by itsyeonjoon** [comment]
@misaugstad Yes, I've tried using .gm-fullscreen-control (as well as .gm-control-active) CSS class and tried to hide it using commands like 
`.gm-fullscreen-control {
    visibility: hidden;
}`
(also tried display: none; ) 
But it doesn't seem to work, at least on my local dev. I also tried using !important to see if something overrides this command, but that also doesn't seem like it is the case.

**Comment by misaugstad** [comment]
>Yes, I've tried using .gm-fullscreen-control (as well as .gm-control-active) CSS class and tried to hide it using commands like `.gm-fullscreen-control { visibility: hidden; }` (also tried `display: none;` ) But it doesn't seem to work, at least on my local dev. I also tried using !important to see if something overrides this command, but that also doesn't seem like it is the case.

Where did you add that? I just added the following to `svl-map.css` (the location where the last person fixed this issue) and it worked.
```
.gm-fullscreen-control {
    visibility: hidden;
}
```

**Comment by misaugstad** [comment]
Oh and I just tried adding `disableDefaultUI: true` to the list of `mapOptions` in `Mapservice.js` and that worked too! This is probably the better solution.

**Comment by itsyeonjoon** [comment]
Sorry for responding late. I added the code to `svl-map.css` too, but it didn't work on my computer... which is really strange. Also, I'll try the last suggestion you've made as well!
