### ISSUE TITLE
Bug: Turker is not being assigned a region in the new priority based system

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1225]
While testing for #1223 (https://github.com/ProjectSidewalk/SidewalkWebpage/pull/1224#issuecomment-371643796).,I found that the turker isn't being assigned a region. Implication for this is: if the turker returns to the site via  resume HITs, they would not continue their work in the same neighborhood.

Adding the comment from the PR here:
> There is one other issue I noticed. The turker is never assigned a region. For e.g. using the URL, the turker goes to the audit page and starts working on a neighborhood. If the page is refreshed (or say the resume HIT is used), the turker is assigned some other neighborhood. When I checked the turker user dashboard from the admin dashboard (#1220 should be fixed for registered users), it shows its unassigned. I think the system is treating the turker as an anonymous user. This probably should be solved in another PR.

**Comment by misaugstad** [comment]
Okay I just found it, looks like the `update` method is being called instead of the `save` method, so it is just finding nothing to update... Easy fix!

**Comment by manaswis** [comment]
Closed via #1226
