### ISSUE TITLE
Add smiley face or other emoticon/emoji to mission pop-up

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#123]
Add smiley face or other emoticon/emoji to help indicate that the 'nice job' comments are meant to be fun/silly. As now, they come across really serious and it's not clear what's meant by them.

In the screenshot below, for example, it's not clear that 'Couldn't have done it better myself' is said in jest. Needs a winking emoticon like ;-) to make this more clear.

![image](https://cloud.githubusercontent.com/assets/1621749/16058159/0f8c2778-324b-11e6-86fb-f2899f12206d.png)

**Comment by kotarohara** [comment]
Related to #89

**Comment by jonfroehlich** [comment]
Yes, I agree that @danZzyy could do this... and probably very quickly. Either we literally use ;-) or @danZzyy finds like 2-3 fun emojis that we randomly swap in at the end of the text statement.

**Comment by kotarohara** [comment]
Agree!

**Comment by danZzyy** [comment]
@jonfroehlich "they come across really serious"

                'Today you are Harry Potter\'s golden snitch. Your wings are made of awesome.',
                'They say unicorns don\'t exist, but hey! We found you. Keep on keepin\' on.',
                '"Uhhhhhhrr Ahhhhrrrrrrrrgggg " Translation: Awesome job! Keep going. - Chewbacca'

**Comment by jonfroehlich** [comment]
@danZzyy Some do. And given that the website does not consistently employ humor or embody a witty personality, it's a bit discordant to see this text. It needs an emoticon to help emphasize that it's playful--especially for the more ambiguous phrases.

**Comment by kotarohara** [comment]
@danZzyy completed this.

**Comment by jonfroehlich** [comment]
Screenshot?

On Mon, Jun 27, 2016 at 7:27 PM, Kotaro Hara <notifications@github.com>
wrote:

> @danZzyy <https://github.com/danZzyy> completed this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ProjectSidewalk/SidewalkWebpage/issues/123#issuecomment-228906160>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABi-9R5CHbHuzulzSpMDmbnBhZVCfDvUks5qQFxngaJpZM4I1tui>
> .
>



-- 
Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich <https://twitter.com/jonfroehlich> - Twitter
