### ISSUE TITLE
Turker confirmation code possibly not showing up?

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1231]
Got an email from a turker today saying
>I completed the tutorial and the first 500 foot section.  Then, it says to click to 'generate the completion code'... nothing happens when I click that button... I did the work in firefox... maybe it would have generated a code in chrome.

Not sure what the issue was, or if it was just some confusion. We will see if anyone else brings this up.

**Comment by maddalihanumateja** [comment]
The question then would be able if they are able to see the orange MTurk code button, at least when they reload the page.
If not, it would be more worrying. I’m assuming that they saw they are using a Turker account and not an anon/registered account since they’re seeing the completion code message.

**Comment by misaugstad** [comment]
Agreed, I wish I could have asked them for a screenshot, but they had already submitted the HIT using their turker id, so I assumed that they were trying to move on. They were definitely logged in as a turker though, all their data is there.

**Comment by misaugstad** [comment]
We had 2 or 3 more instances of turkers saying that nothing happened when they clicked the button. This is out of about 100 turkers from the past week. The ones who I was able to ask said they were using Chrome. Was not able to obtain any screenshots though, so not sure if the button is visible.

**Comment by misaugstad** [comment]
Did another entire turk deployment and did not have this problem. I'm assuming updates we've made since this time has made this more robust :)
