### ISSUE TITLE
Admin contributions tab: Other label type show type name

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1234]
It seems that in the table within the contributions tab of the admin page, the Other label type's name is not showing up. I believe the same thing is happening in the user contributions tab (at least the admin version). Not a high priority, since Other is not used often, and this seems to be the only label type where this is happening (I have seen all others in the table).

![missing_label_type](https://user-images.githubusercontent.com/6518824/37836256-6e6807c2-2e88-11e8-91dc-bacd3dceedb4.png)

**Comment by misaugstad** [comment]
Well the database is not incorrect, we just did not provide a description for Other because a description doesn't entirely make sense there. So the database allows the description column to be null, which means that the code should allow the description column to be null as well.

This means that either the code needs to be updated so that it works even when the description is null, or the code needs to be updated so that it requires the description to _not_ be null :) I will say that the former is definitely easier :wink:

**Comment by ShivenBhatt** [comment]
this was fixed in #1302.
