### ISSUE TITLE
Close a label's context menu when using label type keyboard shortcut

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1237]
This is only really a problem when you are labeling two problems/features that are close to each other, and the context menu for the first covers up the second. When using keyboard shortcuts and labeling two problems/features that are both visible in the window, we don't bother closing the context menu since placing the next label closes it for us. But when the context menu covers the thing we wanted to label, we have to deselect that label type, close the context menu, then reselect the label type (which is very frustrating!). See below for reference.

![context_menu_coverup](https://user-images.githubusercontent.com/6518824/38063973-f3258c24-32c9-11e8-9846-005963d61b80.png)

Related to issue #226

**Comment by jonfroehlich** [comment]
In those cases, I would just hit ESC key then C key.

**Comment by misaugstad** [comment]
Yeah but I get into a rhythm and I know what the next label I'm going to place is, so I'm not checking if it's covered or not before hitting the C key again. 

I mean, maybe it's only frustrating to me, but in any case I don't see why the context menu should stay open once you've selected the next type of label you're going to place.

**Comment by misaugstad** [comment]
Closing via #1335
