### ISSUE TITLE
Remaining to-dos on Labeling Guide

### ISSUE THREAD

**Issue by pujaram** [ProjectSidewalk/SidewalkWebpage#1239]
- [x] Create animated gif for how to place a label on the Introduction page (it's probably most helpful if it shows you placing a label at the base of a curb ramp and another at the base of an obstacle)
- [x] Font differentiation for captions and body text
- [x] Sidebar subtopics should be more concise (manually written, rather than automatically generated) This is because the subtopics are too long, making it difficult to read. Also, we want to keep the headings as questions to be user-friendly.
- [x] Consider making the sidebar a float, so that it's always visible on the left side regardless of scroll state.
- [x] Consider removing white space after each topic.
- [x] The Labeling Guide link should be on the header, next to 'Start Mapping' rather than at the bottom of the page.
- [x] When the subtopic links are clicked on, the display is slightly below the question rather than starting at the question. This should be fixed.

**Comment by nomichka** [comment]
I tried implementing the sidebar as a float. It's not as noticeable in still pictures, but I thought that the floating sidebar looked a bit unnatural as I was scrolling, and it doesn't seem like a step up from not having the sidebar as a float.

Here are some screenshots:
![Screenshot from 2020-07-27 15-43-04](https://user-images.githubusercontent.com/35845622/88599231-29f9f780-d020-11ea-9590-570fd02b9397.png)
![Screenshot from 2020-07-27 15-43-13](https://user-images.githubusercontent.com/35845622/88599237-2c5c5180-d020-11ea-9d53-eda33b6dd32e.png)
![Screenshot from 2020-07-27 15-43-16](https://user-images.githubusercontent.com/35845622/88599242-2e261500-d020-11ea-8ae7-590dd1887108.png)
![Screenshot from 2020-07-27 15-43-20](https://user-images.githubusercontent.com/35845622/88599251-31210580-d020-11ea-8145-8d4aa2d38e57.png)

Plus two bugs - scroll down and the sidebar gets cut off, and resizing the window width makes the text become jumbled.
![Screenshot from 2020-07-27 15-44-05](https://user-images.githubusercontent.com/35845622/88599254-33835f80-d020-11ea-899d-b34fa279bfd4.png)
![Screenshot from 2020-07-27 15-44-33](https://user-images.githubusercontent.com/35845622/88599256-34b48c80-d020-11ea-8292-ff4c58d6dc8c.png)

**Comment by misaugstad** [comment]
Hmm yeah maybe it is just harder to tell in screenshots, bc it looks fine to me (except ofc for the last two screenshots, but hopefully those could be fixed). Would it be easy to include the floating sidebar in the PR so that I could play with it too? You're probably right, but I'd like to try it out, bc I find it pretty annoying to not have the floating sidebar rn! :grin:

**Comment by nomichka** [comment]
Added! If you do prefer to have a floating sidebar, then I'll figure out how to solve the bugs.

**Comment by misaugstad** [comment]
closing via #2189
