### ISSUE TITLE
Mission Complete Pop-Up Comments

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#124]
![image](https://cloud.githubusercontent.com/assets/1621749/16058181/3707dbd0-324b-11e6-9492-ae758354dad0.png)

- I think we should highlight the current audit neighborhood on the map. You may be doing this currently but hard to tell (are you highlighting in white?). If so, I think you should flip the highlight--so that the other neighborhoods are a bit grayed out and the current neighborhood has *no* opacity layer
- To be consistent with our other progress bars, I think the Neighborhood progress bar should have a % in there.
- Change 'Neighborhood' title (above progress bar) to 'Neighborhood Progress.' Consider also changing the word 'Neighborhood' here to the actual name of the neighborhood. You currently only have it in the title for the pop-up but honestly, I miss this title
- In the following, take out the word 'neighborhood' in the last two bullets so consistent with first bullet. Will also make all of these a single line of text (doesn't look good as double lines)
![image](https://cloud.githubusercontent.com/assets/1621749/16058261/9d0cc56c-324b-11e6-9a17-305a7e4937eb.png)
- You need to remind the user what mission they just completed. You say 'Mission Completed' but you don't say what mission the user just completed...

**Comment by jonfroehlich** [comment]
Also, using 'gray' to indicated area walked, I think, is confusing and hard to see. We should use a different color. I think we should also animate in the most recent route that they just animated.

**Comment by kotarohara** [comment]
@danZzyy Can you tie this to the task you are working on right now?

**Comment by danZzyy** [comment]
- I think the neighborhood highlighting could be accomplished in css. I am wondering what Kotaro's thoughts on this are
- Percentage text an existing div, it is just hidden so that's an easy fix too
- The neighborhood is already identified in the title so I think that may be redundant. I do agree adding "Progress"  clarifies the metric
- Might removing "neighborhood" confuse the user with whether this is all their audit progress or just the neighborhood?
- Do you mean the mission distance completed as the title? Again, that information is already present under the neighborhood progress.

**Comment by kotarohara** [comment]
- **Highlighting current neighborhood.** As Jon said, it is highlighting the current neighborhood by white. Daniil, you can work on it to make it more apparent if you think it's not.
- **Percentage label in the progress bar.** Daniil, please fix.
- **Neighborhood -> Neighborhood Progress.** Please use "Neighborhood Progress"
- **Removing "neighborhood."** I agree with Daniil. We should keep "neighborhood" to distinguish the first row from the rest.
- **Show the type of the mission completed.** Yeah, we only have single type of mission (audit X mi/ft), so I don't think that's necessary now.

**Comment by jonfroehlich** [comment]
I'm fine with keeping "neighborhood" on those lines but please make the text into single lines (rather than double lines).
