### ISSUE TITLE
Add clustered "attributes" to API

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1241]
Once we finish implementing the clustering of labels into attributes on the production code (#1240), we should add API endpoint(s) that mirror (or replace) the current label API endpoints.

**Comment by jonfroehlich** [comment]
> @jonfroehlich I'm thinking that we should update the access score endpoints to use clusters instead of labels when we add the clusters to the API, yeah?
Absolutely, applications should be built around *clusters* rather than raw labels. Obviously, the cluster API should allow developers to access the underlying raw labels that comprise the cluster.

> And for now, do we just want to make the cluster API endpoints mirror what we have for labels (which is just returning all the labels within a bounding box)?
Sure, that sounds fine. Can you think of a different way of doing this? I suppose you could also have something that says: 'Give me all clusters of average severity > 3'?

> This is more of a note to myself on implementation: what happens in the edge case where someone tries to use the API endpoint at the same time that we are re-running clustering?
Let's not worry about this for now. Edge case. Unlikely to happen :)

**Comment by misaugstad** [comment]
> I suppose you could also have something that says: 'Give me all clusters of average severity > 3'?

Given the infrequency that users had rated severity in our first run of DC, I don't think it is the best idea to encourage users of the API to only look at high severity problems right now :grimacing: 

Okay here is the before/after for the API page and the results choropleth page! Let me know if there are any edits y'all would want to make right now, either to the API or to the text on the page. I've been thinking about adding documentation that says _exactly_ what the JSON will look like, so they know what to expect from their queries. But that would take up a lot of space so I haven't gone through with that.

Before
![api-page-before](https://user-images.githubusercontent.com/6518824/46369592-44d3ce80-c638-11e8-81cd-ccb0ea620363.png)

After
![api-page-after](https://user-images.githubusercontent.com/6518824/46369598-48ffec00-c638-11e8-9493-c966d5b9893a.png)


Before
![results-choropleth-before](https://user-images.githubusercontent.com/6518824/46369646-68971480-c638-11e8-9ca3-849cbbb97846.png)
![choropleth-counts-before](https://user-images.githubusercontent.com/6518824/46369650-6b920500-c638-11e8-9527-e34dd065a99d.png)

After
![results-choropleth-after](https://user-images.githubusercontent.com/6518824/46369655-6f258c00-c638-11e8-95e8-6dc1289dd776.png)
![choropleth-counts-after](https://user-images.githubusercontent.com/6518824/46369660-7056b900-c638-11e8-8b81-37905468de40.png)

**Comment by misaugstad** [comment]
Oh yeah, I've also improved the results choropleth load time from 30 seconds to 5 seconds on my local machine, so hopefully we don't run out of memory when loading it on the server now!

**Comment by misaugstad** [comment]
>Wow, that's great Mikey. We have code frozen on UMIACS, right? So will this go on on the DC deployment on cs.washington.edu?

Yep! Although the API changes are one of the few things we might want to port over to the old DC code.

**Comment by misaugstad** [comment]
>Is that actually true? Didn't @aileenzeng run some of this analysis and find that some user groups actually provided a lot of severity ratings... I searched for it and found this jonfroehlich/ProjectSidewalkCHI2019#62, which doesn't really address the severity rating frequency question...

Certain user groups, yes. I think the problem is that overall, there are ~250k labels, and only ~150k have severity ratings. So if someone is using the API and is like "I only want the highest severity problems", they are likely missing 2/5 of them.

**Comment by jonfroehlich** [comment]
Right. Fine. But I still think it's a query people would want to run... :)

Also, we lost some percentage of severity ratings because of a data logging bug, remember? :) And, in the future, people will be much more likely to rate severity given @aileenzeng's UI changes.

**Comment by misaugstad** [comment]
>But I still think it's a query people would want to run... :) Also, we lost some percentage of severity ratings because of a data logging bug, remember? :) And, in the future, people will be much more likely to rate severity given @aileenzeng's UI changes.

I agree with all of that! I think that we should make a new issue for adding something like that to the API, but I was planning on doing the more basic endpoints in this update. If you think it is important enough right now, I can certainly add the option though!

**Comment by jonfroehlich** [comment]
Yes, please. Make a new issue! Glad we are in agreement.

**Comment by misaugstad** [comment]
>Wow, that's great Mikey. We have code frozen on UMIACS, right? So will this go on on the DC deployment on cs.washington.edu?

I also want to clarify on this: We have a code freeze on the DC code, not just the UMIACS code... This code isn't immediately going into the DC code base, but I will definitely port this over to the old DC code after it is put on production and tested here.
