### ISSUE TITLE
Update onboarding to suggest 'No Sidewalk' from menu

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1249]
From #772 

When the No Sidewalk label is brought outside of the ribbon menu, the onboarding tutorial still suggests to open the Other menu and look for the No Sidewalk item. We should change it so the user just clicks the 'No Sidewalk' button.

![image](https://user-images.githubusercontent.com/25534091/41366935-82806de4-6ef2-11e8-95b8-da14bae5e88f.png)

**Comment by aileenzeng** [comment]
Here are the changes that I made:
1) Make the interface ask the user to click on the **No Sidewalk** button (rather than the **Other** button)
2) Change the text (first row in the table) from "**Click the "Other" button then the "No Sidewalk" button** (etc...)" to "Click the **No Sidewalk button** (etc...) " 

| Before | After |
|--------| ----- |
| ![image](https://user-images.githubusercontent.com/25534091/41374006-d752ced4-6f06-11e8-894c-7aa010cdcf33.png) | ![image](https://user-images.githubusercontent.com/25534091/41373812-3d6cd4a4-6f06-11e8-99ad-47a23767a97a.png) |
| ![image](https://user-images.githubusercontent.com/25534091/41374029-ec4cf422-6f06-11e8-932c-cb94e753e91e.png) | ![image](https://user-images.githubusercontent.com/25534091/41373826-490d4d16-6f06-11e8-8164-fad0f08c9d17.png) |
| ![image](https://user-images.githubusercontent.com/25534091/41374044-f48cd576-6f06-11e8-9671-c3b394ed011d.png) | ![image](https://user-images.githubusercontent.com/25534091/41373830-50299de8-6f06-11e8-98b2-8fddd9a7bd1e.png) |

**Comment by jonfroehlich** [comment]
Wow! This looks great. Did you test the heck out of it? :)

**Comment by aileenzeng** [comment]
I did some testing on it! I'm not sure what other things to look for but here's what I checked for:

- If the user tries to add a "No Sidewalk" label too far from the arrow, it'll ask the user to delete it and to add another "No Sidewalk" label
- The user can't choose labels that aren't "No Sidewalk" labels

**Comment by jonfroehlich** [comment]
Great! Then I think it's time for the pull request and @misaugstad to test. :)
