### ISSUE TITLE
Mission language

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#125]
![image](https://cloud.githubusercontent.com/assets/1621749/16058334/010d20c0-324c-11e6-8705-0a20bb8e1555.png)

Easy things to change:
- Change 'this neighborhood' to the actual name of the neighborhood.
- Have the title Mission on its own line. Then, below it, have the actual mission. The actual mission can be in large text but should not be bold
- I thought we were going to switch these to a more understandable metric rather than 4,000 feet.

Harder thing to change but still, I think, a good suggestion:
- Show the map of the neighborhood and highlight the route that they need to audit. Consider animating in the route so user can follow the trace.
- Map could also show what the user has audited so far.

**Comment by kotarohara** [comment]
Related to #112

**Comment by kotarohara** [comment]
#163

**Comment by kotarohara** [comment]
Updated the mission modal window. 

![cursor_and_project_sidewalk_-_audit](https://cloud.githubusercontent.com/assets/612263/17452111/43a8e0e2-5b3a-11e6-9ca2-9f5f6f70b9e3.png)
