### ISSUE TITLE
add NarrowSidewalk label?

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1252]
I've been looking through the descriptions submitted by users for the various label types, and I've found that 154 of the 361 (43%) descriptions given for the Other label type have the word "narrow" in them. I've found that the primary use of the Other label is to mark a narrow sidewalk. There are actually only 1417 Other labels in the system, which means that 11% of _all_ Other labels have a description with the word narrow in it! I've also verified that very few of these are from researchers :) And it is spread across a bunch of users.

Reasons to add a new label type: This is actually a super important thing to mark. We had formerly been marking it as a SurfaceProblem, but this is really not an obvious fit into that category.

Reasons _not_ to add a new label type: Maybe this problem can be solved more easily using computer vision and aerial imagery. We have talked about alternative ways of marking no sidewalk (#1129), and these might be more appropriate for narrow sidewalk as well. It also adds more complexity to the system.

@jonfroehlich any thoughts on this?

**Comment by jonfroehlich** [comment]
I like the idea but two concerns:

1. We have been (and need to continue to be) very careful to maintain a very simple UI that presents only the most important label categories--this is important both to ease training demands and simplify the user experience
2. Perhaps more importantly, assessing narrowness is very difficult using Google Street View--and one's interpretation can be skewed by the Street View car camera location and the target. For example, I'm sure we've all experienced seeing an obstacle in Project Sidewalk that appeared impassable from one panorama but fairly passable from a different panorama.

Still, something to discuss! And thanks for floating the idea!!

**Comment by jonfroehlich** [comment]
Also, @aileenzeng's new tagging system might be a reasonable compromise here?

**Comment by misaugstad** [comment]
Yeah that is a good point. Having "narrow sidewalk" as one of the tags listed for surface problems, it sort of teaches users to use the surface problem label for that type of issue.

**Comment by jonfroehlich** [comment]
I also intended to compliment you on your data-driven approach here and providing some numbers to back-up your suggestion. A really nicely written post, thanks Mikey!

**Comment by misaugstad** [comment]
I think the tagging system has been a good compromise!
