### ISSUE TITLE
Confusing: 'Jumped back to your neighborhood'

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#126]
I was just auditing Mt. Vernon Square and following the red line audit path when suddenly, I got this screen. Not sure why.

![image](https://cloud.githubusercontent.com/assets/1621749/16058540/f634777e-324c-11e6-8cb8-408017f56c63.png)

Can you change the text:

'We sent you back into the neighborhood you have been walking around...' 

to:

'Oops! Something went wrong, so we jumped you to a different location in <actual neighborhood name>. Please keep exploring and helping make this neighborhood more accessible!'

**Comment by kotarohara** [comment]
Hmm, nothing really went wrong though. You just stepped outside of the neighborhood boundary that you have been auditing. I'll think about the better way of explaining what happened.

**Comment by jonfroehlich** [comment]
So, we have mission routes that route you outside of a neighborhood? Maybe what we could do instead, if possible, is not pop up this message in those cases and instead try to route them back into the neighborhood at the next possible intersection. Do you know what I mean?

In those cases when we can't route the person back into the neighborhood easily, then the message should be:

"Yikes, our bad. We just routed you outside of <current neighborhood name>, so we had to jump you back into a different neighborhood location. Keep exploring. Keep labeling. Keep making the world more accessible!"

**Comment by kotarohara** [comment]
#141
