### ISSUE TITLE
Mission Length: Is 4,000 ft too long for a mission

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#127]
Is 4,000 ft too long for a mission? We'll have to see. :)

Do we have missions longer than 4,000 ft? If so, I think we may want a different mission strategy because it feels really nice to complete a mission and get the feedback for that (the mission complete pop-up). I worry that 4,000+ feet missions just feel too overwhelming and people will drop out without completing them. Could try to launch and see, I suppose. :)

![image](https://cloud.githubusercontent.com/assets/1621749/16058669/8f7ff890-324d-11e6-8281-0ea28b7f550d.png)

**Comment by kotarohara** [comment]
Related to #66

**Comment by jonfroehlich** [comment]
With more user testing, we'll have a better sense of whether 4,000 ft (or even 1 mile) is too long for the later missions...

**Comment by kotarohara** [comment]
This keeps coming up (e.g., #78 ), so I'll set the priority to medium.

**Comment by danZzyy** [comment]
I would rather have more shorter missions. It gives a better stopping point and a greater gratification. Also I encountered several areas where the mission points into a direction that does not have a street view link so I have to refresh the page to get placed somewhere else. I dont think the average user would be as tolerant of that.

**Comment by kotarohara** [comment]
I updated the mission length. Each neighborhood now has: 1000ft, 2000ft, 4000ft, 1mi, 1.5mi, 2mi, 2.5mi, and so on.
