### ISSUE TITLE
Add tag information to contributions tab on admin page

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1285]
I think it would be beneficial to see which tags a user selects from the admin page, since it may be able to provide more at a glance information about labels. 

Here's the current contributions tab:
![image](https://user-images.githubusercontent.com/25534091/42842823-291e923a-89c3-11e8-8e64-5bd3b01e4c2b.png)
A new column might be nice to add, but I'm not sure if it would make the current table too cluttered.

![image](https://user-images.githubusercontent.com/25534091/42842827-2b9dd64c-89c3-11e8-9ec6-5273d900178a.png)
We could also add another row to this display (from clicking view on the table above).

**Comment by jonfroehlich** [comment]
@misaugstad, why wouldn't we just have both descriptions + tags? Why eliminate descriptions?

**Comment by misaugstad** [comment]
Added in PR #1291
