### ISSUE TITLE
Severity ratings sometimes not saved

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1286]
Maybe to #1256 and #1257 

Ratings sometimes don't save when I exit out of the Context Menu too quickly (<0.5 seconds) after rating severity. When I checked the logs for these types of scenarios, I noticed that there weren't any `KeyboardShortcut_Severity_` events being recorded.

**Comment by jonfroehlich** [comment]
Reason being we fixed an interaction bug around that time that had caused data loss...

**Comment by aileenzeng** [comment]
After September 1, 1146/1152 (99.5%) had severity ratings. This covers events up until mid-December 2017.

**Comment by misaugstad** [comment]
I believe this is an instance of the problem described in #1257; I think we have a problem with lots of things not being recorded if there are too many interactions happening quickly/simultaneously.

**Comment by jonfroehlich** [comment]
So this is purely about logging the interaction and not saving the actual severity data in the database, right?

**Comment by misaugstad** [comment]
Fixed in PR #1305
