### ISSUE TITLE
Update Onboarding tutorial GIFs with tool changes

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1288]
The onboarding tutorial GIFs are now a little out of date with the recent addition of severity labels/tagging system/extended description. 

Example below:
![image](https://user-images.githubusercontent.com/25534091/43037240-61aae112-8cc0-11e8-9a1d-5a181a7ff082.png)

**Comment by jonfroehlich** [comment]
Good catch. Ideally, we would onboard tagging too once we update this. Low priority for now imo.

**Comment by misaugstad** [comment]
Related to #1263. Agreed that this is low priority right now. Once all the big changes to the site are done, this falls under the category of things that should be polished!

**Comment by misaugstad** [comment]
closing via #1493
