### ISSUE TITLE
Round About Bug

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#129]
Weird red line route direction issue with round-abouts.

![image](https://cloud.githubusercontent.com/assets/1621749/16084808/0fb7f298-32e8-11e6-9bee-c177ffcbeea6.png)

**Comment by kotarohara** [comment]
This is probably due to the OpenStreetMap data we use. I cannot programmatically fix it (need to fix the data in the database).

**Comment by jonfroehlich** [comment]
I agree that this is a low priority.

**Comment by misaugstad** [comment]
Issue #1814 would also address this issue.
