### ISSUE TITLE
Switch to HTTPS

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1292]
Google Chrome now marks our site as insecure. This was a long-planned protocol change by Google (see article [here](https://www.theverge.com/2018/7/24/17603126/google-chrome-unencrypted-not-secure)). Google now marks *all* unecrypted websites as 'not secure'

![image](https://user-images.githubusercontent.com/1621749/43169356-9088b814-8f55-11e8-9ed5-595c682ce5e4.png)

This relates to Issues https://github.com/ProjectSidewalk/SidewalkWebpage/issues/536 and https://github.com/ProjectSidewalk/SidewalkWebpage/issues/988.

**Comment by misaugstad** [comment]
For whoever does this fix, read through the thread in issue #988, which describes how the site actually works under https, browsers just aren't being sent to the secure site by default, and what we might do to fix it.

**Comment by misaugstad** [comment]
With the switch to Docker, we seem to be sent to HTTPS by default! Try going to sidewalk.cs.washington.edu and you should be automatically redirected to HTTPS! Thanks @mechanicjay :grin:
