### ISSUE TITLE
After signing in/up through navbar, menu doesn't close

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1294]
If I sign in through the navbar, it successfully signs me in but the sign-in menu stays open. This only happens to me on the audit page. Possibly related to #1026

**Comment by misaugstad** [comment]
@lstrobel I really want you to be working on #865 and #1026 but I figure that while working on #1026 you might discover what is causing this bug, so I figured I would bring it to your attention :)

**Comment by lstrobel** [comment]
@misaugstad Sweet, good to know.

**Comment by misaugstad** [comment]
closing via #1383
