### ISSUE TITLE
Update results page with new NoSidewalk icon

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1296]
![image](https://user-images.githubusercontent.com/25534091/43427696-a06bc6b8-940f-11e8-8e18-9780cd4610f6.png)

Oops, looks like this slipped by me earlier when we merged #1251. We should switch out the Missing Sidewalk icon with the new purple icon. This is on the /results endpoint.

**Comment by ShivenBhatt** [comment]
this was fixed in #1301. Closing issue now.
