### ISSUE TITLE
Colors of the "Achievement" icons

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#13]
Jon's feedback: The color in these icons are distracting. Can you reduce brightness and/or saturation a bit. I also worry about the overall design language in your design. These icons don’t seem to fit the general iconic aesthetic that you developed.

**Comment by nguyenist** [comment]
@kotarohara can you send me the file of the current icons? and some screenshots of current elements with the aesthetic you'd like to mimic for these icons? happy to work on this if you'd like.

**Comment by kotarohara** [comment]
@nguyenist Achievement icons that we are talking about here are:

![image](https://cloud.githubusercontent.com/assets/612263/14584517/a1c1e1d0-0417-11e6-84d1-146697b9ed24.png)

Icons should be in the repo under `sidewalk-webpage\public\javascripts\SVLabel\img\icons`

The thing is we don't know what information we are going to put here. We don't have examples or guidelines for designing these icons either. So I'm not sure what's the best way for working on this issue.

**Comment by nguyenist** [comment]
This relates with #18 re "We need a consistent, well-defined color palate."

**Comment by kotarohara** [comment]
This issue is no longer valid as we changed the icons. See #93
