### ISSUE TITLE
Public API: query attributes on severity rating

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1320]
As discussed in #1241 we want the public API endpoint that gives attributes to have the option to select based on severity. The simplest version would probably be to have a single severity parameter, and we only return attributes with severity greater than or equal to that severity. We could also make it more complex though, allowing someone to specify a range, or optionally include attributes with no severity rating.

**Comment by nomichka** [comment]
In addition to specifying the latlng coords, the user can specify a severity rating they want (0-5, with 0 representing null severity ratings). Without specifying the severity rating, the user gets data of all severity ratings, including null.

Before:
![Project Sidewalk Issue 1320 before](https://user-images.githubusercontent.com/35845622/61570438-65430d00-aa41-11e9-8e28-b6ce4f65905a.PNG)

After:
![Project Sidewalk Issue 1320](https://user-images.githubusercontent.com/35845622/61570339-cfa77d80-aa40-11e9-8e68-2f4db0f72614.PNG)

Any edits I should make to the ui?

**Comment by misaugstad** [comment]
Very cool!!

1. I think we probably want it so that when you pass in a severity, you get all severity greater than or equal to that severity rating.
1. The only other thing I noticed is that when you say "Optionally, you can pass a specific severity to look for", you should probably mention there that the range is 1-5 (plus 0 for nulls).
1. Maybe we should actually just let them pass in "none" or "null" for labels with no severity though?

**Comment by nomichka** [comment]
I made the returned severity be equal to the passed severity instead of greater than or equal to because it allows the user a wider range of options, but I can easily change it to greater than or equal to.

And yeah, it probably is better to let them pass in "none" or "null." I'll change it to null, since the actual api shows `"severity": null`, so it'll be consistent.

**Comment by misaugstad** [comment]
>I made the returned severity be equal to the passed severity instead of greater than or equal to because it allows the user a wider range of options, but I can easily change it to greater than or equal to.

yeah that is a decent argument. I guess I'm just assuming that people are most likely to be querying on severity so that they can get only the high severity labels.

>And yeah, it probably is better to let them pass in "none" or "null." I'll change it to null, since the actual api shows "severity": null, so it'll be consistent.

I'm actually leaning towards "none". Consistency with how things are represented on the back-end is not particularly important. What is more important here is that it seems intuitive for an end-user. And I think because the data they would be querying for is labels with no severity rating, I think "none" probably works better.

**Comment by nomichka** [comment]
>yeah that is a decent argument. I guess I'm just assuming that people are most likely to be querying on severity so that they can get only the high severity labels.

So, just to make sure, go with greater than or equal to?

**Comment by misaugstad** [comment]
ahhhhh no go with what you have now

**Comment by misaugstad** [comment]
closing via #1819
