### ISSUE TITLE
Can't correct severity ratings in tutorial.

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1332]
Discovered bug during ASSETS'18 demo session. A user mislabeled severity and then got stuck--we could no longer correct or interact with the placed label.

![image](https://user-images.githubusercontent.com/1621749/47422671-16e73300-d77b-11e8-97f4-c884782fe6ca.png)

**Comment by misaugstad** [comment]
I've been doing a lot of testing of the tutorial lately for the missions infrastructure PR in particular, and I've never come across this bug, which is why I marked it as low priority. If anyone else encounters it, please document it here!

**Comment by misaugstad** [comment]
Nobody has documented this bug over the past 4 months while we have made significant changes to the tutorial and have thus tested it thoroughly. I'm going to close this for now. If it comes up again, we can reopen.

**Comment by jonfroehlich** [comment]
How dare you! :P
