### ISSUE TITLE
Enter key interferes with label tag selection

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1334]
If I click on a label tag, and hold the enter key, the tag will start alternating between being selected/deselected. If I press the enter key briefly, whatever action I last completed with the label tag becomes undone.

Before (clicked on label tag): 
![image](https://user-images.githubusercontent.com/25534091/47621215-ddcbfd00-dab1-11e8-9217-c7619419305d.png)

After (hit enter key, then reopened context menu):
![image](https://user-images.githubusercontent.com/25534091/47621206-b412d600-dab1-11e8-8a68-45fff57a1341.png)

**Comment by misaugstad** [comment]
Fixed via #1365
