### ISSUE TITLE
Need to get Sloan Foundation listed as funder

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1337]
![image](https://user-images.githubusercontent.com/1621749/48279631-ffa87680-e405-11e8-8274-33710cd62443.png)

**Comment by jonfroehlich** [comment]
Here's the logo, which we may need to inverse (so that it's white) for the webpage:

![image](https://user-images.githubusercontent.com/1621749/48279748-5dd55980-e406-11e8-9907-fde41da002ff.png)

**Comment by maubinle** [comment]
ok, here are the inverted logos, one which is the actual transparent png, the other shows what it would look like against the footer colour (I had to slightly modify it to make it a pure white, let me know if it looks off):
![apsf_nobackground](https://user-images.githubusercontent.com/16949591/48321074-9165de80-e5d4-11e8-9087-97ee354ef9d1.png)
![apsf_wbackground](https://user-images.githubusercontent.com/16949591/48321075-96c32900-e5d4-11e8-9409-ca3174c3b86c.png)

**Comment by jonfroehlich** [comment]
Looks good!

**Comment by maubinle** [comment]
ok, here's how it looks: 
![image](https://user-images.githubusercontent.com/16949591/48535530-88893d00-e860-11e8-8ae5-b308dbcba366.png) I aligned it with the rest of the three-columned parts of the website because it looked a little odd when they were clumped together but not aligned. the icon links to https://sloan.org

**Comment by jonfroehlich** [comment]
Looks nice! Please link to https://sloan.org/fellowships/

**Comment by misaugstad** [comment]
>will open a PR once I have confirmation this looks good. also, @misaugstad, just confirming I should open a PR to 'develop', not 'master', correct?

Correct!

**Comment by misaugstad** [comment]
Closing via #1341
