### ISSUE TITLE
Get Docker working as a dev environment

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1340]
Most of the work of getting Docker set up is discussed in issue #593 and PR #1303 but those are focused on getting Docker set up for production. It will also make development much easier if we can use Docker for that as well.

As far as I know, the only remaining TODO for doing development with Docker is that we have to rebuild the container whenever we modify the code, and @aileenzeng sent an email to @mechanicjay to try and get that figured out.

@aileenzeng is there any other open TODO for development with Docker?

**Comment by aileenzeng** [comment]
I don't think so - we might want to do another round of testing (for setup) because I changed the instructions recently. The old setup instructions don't seem to work anymore for whatever reason.

**Comment by jonfroehlich** [comment]
Tagging @athersharif who might have some helpful feedback for us. See also the Discussion in https://github.com/ProjectSidewalk/SidewalkWebpage/issues/593 for context.

**Comment by athersharif** [comment]
Thanks @jonfroehlich. Will take a look at the current setup and report the findings/suggestions.

**Comment by athersharif** [comment]
@misaugstad @aileenzeng @jonfroehlich pushed https://github.com/ProjectSidewalk/SidewalkWebpage/pull/1364 to resolve this.

**Comment by misaugstad** [comment]
closing via #1364
