### ISSUE TITLE
API page demos different per-city

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1344]
On the API page we have example usages of the API shown on maps like so:

![api-page-cropped](https://user-images.githubusercontent.com/6518824/49106352-cc544d00-f237-11e8-81bb-2bcf6c8fa205.png)

The bounding box for these examples are chosen carefully to showcase different label types and access score values. The DC lat-lng bounding box obviously won't work for other cities.

Should we carefully choose this for each city and have this as one of our city-specific parameters? Or do we want to think of a way to showcase the API that is not city-dependent?

**Comment by manaswis** [comment]
Related note: What should this page show for a new city when we have no data (maybe a new issue?).

**Comment by manaswis** [comment]
Bump! This is an actual issue now. Maybe remove the bounding and the map for now? And the link for the API usage could still point to DC data?

**Comment by manaswis** [comment]
Here is the API page for reference on the Seattle site:

![image](https://user-images.githubusercontent.com/2873216/55676578-61bdb880-588c-11e9-9289-44abf200883d.png)

**Comment by misaugstad** [comment]
Hmm interesting thought. Pointing to the DC data isn't a bad quick fix. We can do that for the maps as well.

**Comment by misaugstad** [comment]
closing via #2007
