### ISSUE TITLE
Weird line break in the mission completion message

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#135]
The ;-) falls on its own line, which is weird aesthetically and a bit confusing.

![image](https://cloud.githubusercontent.com/assets/1621749/16287889/b690dda6-38b4-11e6-83b1-f24ddf1680f2.png)

And I still think the emoticons should be SVGs or images rather than the more g33ksp34k of parenthetical faces.

**Comment by kotarohara** [comment]
I don't think svg image is necessary. I agree line break is weird, but I don't really know how to fix that though. Maybe @danZzyy can research and fix this?

**Comment by danZzyy** [comment]
Kotaro, I was talking about this
https://github.com/ProjectSidewalk/SidewalkWebpage/pull/132

These are the 20 messages:
 'Couldn’t have done it better myself.',
                'Aren’t you proud of yourself? We are.',
                'WOWZA. Even the sidewalks are impressed. Keep labeling!',
                'Your auditing is out of this world.',
                'Incredible. You\'re a machine! ...no wait, I am.',
                'Gold star. You can wear it proudly on your forehead all day if you\'d like, we won\'t judge.',
                'Ooh la la! Those accessibility labels are to die for.',
                'We knew you had it in you all along. Great work!',
                'Wow you did really well. You also did good! Kind of like superman.',
                'You\'re one lightning bolt away from being a greek diety. Keep on going!',
                '"Great job. Every accomplishment starts with the decision to try." - That inspirational poster in your office',
                'The [mass x acceleration] is strong with this one. (Physics + Star Wars, get it?)',
                'Hey, check out the reflection in your computer screen. That\'s what awesome looks like.',
                'You. Are. Unstoppable. Keep it up!',
                'Today you are Harry Potter\'s golden snitch. Your wings are made of awesome.',
                'They say unicorns don\'t exist, but hey! We found you. Keep on keepin\' on.',
                '"Uhhhhhhrr Ahhhhrrrrrrrrgggg " Translation: Awesome job! Keep going. - Chewbacca',
                'You\'re seriously talented. You could go pro at this.',
                'Forget Frodo, I would have picked you to take the one ring to Mordor. Great work!',
                'You might actually be a wizard. These sidewalks are better because of you.'

I think the first is the only one that doesnt have obvious humor or a strong encouraging statement. As I took it, the emojis were to make it clear that the tone of the message was humorous and encouraging and I think only the first message has this ambiguity. So maybe not using the first message would eliminate the need for emojis and the line break weirdness
