### ISSUE TITLE
Add version number to footer

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1350]
Our deploy scripts on UMIACS servers used to add our version number to the footer:

![footer-with-version](https://user-images.githubusercontent.com/6518824/49250371-83d19680-f3d3-11e8-89c5-e19399fa192f.png)

Now that we switched to UW servers and Docker, our deploy script is not doing that anymore:

![footer-without-version](https://user-images.githubusercontent.com/6518824/49250470-bed3ca00-f3d3-11e8-8a68-099835215005.png)

We either need to update this with updated deploy scripts or by adding it to the list of steps to go through when deploying new code to the server (https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Deploying-code-to-the-server)

**Comment by jonfroehlich** [comment]
But wait, don't we have this information now baked into a table (you just added this). So, can't we just pull directly from that (e.g., getCurrentVersion() which returns a version num and timestamp).

**Comment by misaugstad** [comment]
Yes, thank you, that is the better option :sweat_smile:

**Comment by misaugstad** [comment]
closing via #1503
