### ISSUE TITLE
GSV Pane is Black

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1354]
I just logged in using my Microsoft Surface Book 2 to take a screenshot for https://github.com/ProjectSidewalk/SidewalkWebpage/issues/303 and my GSV pane is black (possibly related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/451). I walked around using the navigation arrows and the Street View images did not load.

![image](https://user-images.githubusercontent.com/1621749/49322524-1b62e200-f4c5-11e8-93ed-a9d1791395bc.png)

```
svl.panorama.getPano();
"Vdr3dMQtnteAulqqxg1MXQ"
(svl.taskContainer.getCurrentTask()).getStreetEdgeId();
26509
```

The console window doesn't show anything:

![image](https://user-images.githubusercontent.com/1621749/49322587-8a403b00-f4c5-11e8-8ff5-1d5a3c185ff6.png)

**Comment by jonfroehlich** [comment]
Update: I just tried to jump to a new part of the neighborhood and I do see that one slice of the GSV window is filled in:

![image](https://user-images.githubusercontent.com/1621749/49322673-63cecf80-f4c6-11e8-9504-2578a62bf9c5.png)

I'm gonna try to restart Chrome and see if that fixes it.

**Comment by jonfroehlich** [comment]
Just restarted Chrome and say basic problem:

![image](https://user-images.githubusercontent.com/1621749/49322697-9678c800-f4c6-11e8-9968-cb3e177d11b3.png)

It's even happening in the tutorial, so I think something is messed with my video card or something... I need to restart my computer and see if that fixes it.

![image](https://user-images.githubusercontent.com/1621749/49322707-aee8e280-f4c6-11e8-9779-e3fc0289cff7.png)

**Comment by jonfroehlich** [comment]
A computer restart seemed to fix this. Very strange.

![image](https://user-images.githubusercontent.com/1621749/49322879-a4c7e380-f4c8-11e8-9b5b-2dfe1713e391.png)

I have a suspicion that it has something to do with my video drivers because as I was using Project Sidewalk, Windows popped up a window that said I needed to restart because new video drivers were installed...

**Comment by paarig** [comment]
Came across this issue when looking through the Colonial Village neighborhood. It happens at one specific spot on a street in the neighborhood. I have included a screenshot that outlines the issue. The code I typed is:
```
svl.taskContainer.getCurrentTask().getStreetEdgeId();
1154
svl.panorama.getPano();
"U8HXrDBSa_SO7n0MXujdnw"
```
<img width="1440" alt="screen shot 2018-12-31 at 6 59 51 pm" src="https://user-images.githubusercontent.com/29468022/50570024-5c514f00-0d2e-11e9-9856-fe14aac5feb0.png">

**Comment by jonfroehlich** [comment]
@paarig, what happened after you took a step? Did it continue loading blank or black GSV screens?

Also, this may be related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/451

**Comment by paarig** [comment]
@jonfroehlich After taking a step, the map reappeared. It was only at that one specific point that the CSV pane turned black.

**Comment by jonfroehlich** [comment]
Interesting. Thanks for the additional info.

**Comment by aileenzeng** [comment]
I got this error while I was running Sidewalk locally - this is the first time that I've seen this.

![image](https://user-images.githubusercontent.com/25534091/53197719-97a22880-35cf-11e9-8b70-8623c45168bf.png)

![image](https://user-images.githubusercontent.com/25534091/53197770-baccd800-35cf-11e9-9cca-922b084fb639.png)

PanoId: _UnSpZ_1ac2yXeRTsxcEOw
Street Edge Id: 14104
