### ISSUE TITLE
Sign-In Dialog Doesn't Close

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1357]
I tried signing in during the tutorial and while the sign-in looks successful, the sign-in dialog won't close.

![image](https://user-images.githubusercontent.com/1621749/49322864-79dd8f80-f4c8-11e8-80e9-a198250bd311.png)

Possibly related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1294

**Comment by misaugstad** [comment]
This looks like a duplicate of #1294 

Let me know if there is some difference I am missing.

**Comment by jonfroehlich** [comment]
You didn't provide a screenshot :P
