### ISSUE TITLE
Landing Page choropleth color really dark

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1359]
The new version on sidewalk-test.cs shows the following choropleth:
![image](https://user-images.githubusercontent.com/2873216/49334488-22a0f300-f58c-11e8-8494-f1166fd6629c.png)

This is the original on sidewalk.cs:
![image](https://user-images.githubusercontent.com/2873216/49334487-1b79e500-f58c-11e8-9043-5211bfea6d9b.png)

The color scale increased from 10 to 11 colors. Was this intentional or a side-effect of some change?

**Comment by jonfroehlich** [comment]
Purposeful to highlight difference between completely done and 99% done—a huge distinction when trying to get people to select incomplete neighborhoods.

**Comment by manaswis** [comment]
I see, gotcha!
