### ISSUE TITLE
What Does the Gray/Blue Represent on This Map

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#136]
![image](https://cloud.githubusercontent.com/assets/1621749/16287931/ecbea296-38b4-11e6-8456-5b53a151868c.png)

I thought that, perhaps, the progress bar colors were being used on the map to indicate streets that I have walked in previous missions and streets I just completed (which is cool); however, in this map, there are gray lines. What are the gray lines for?

So, in sum, I think mapping the progress bar colors is a good idea. If we don't do that, then maybe add a legend overlay to the map?

**Comment by kotarohara** [comment]
Related to #89 . @danZzyy 's next task?

**Comment by danZzyy** [comment]
The gray lines are associated with completedTaskLayerStyle. I assume that means areas of previous missions?
