### ISSUE TITLE
Experiment with survey in middle of 2nd mission

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1362]
The survey is currently being shown after the end of the 2nds mission. As @jonfroehlich pointed out in [this comment](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1136#issuecomment-445930451) it may be better to show the survey near the beginning of the 2nd mission (maybe after 100ft). This would help get the survey to more users considering the quick dropoffs we have.

Hopefully a new undergrad will be able to implement this so that we can test it and determine if it would be an improvement we want to keep!

**Comment by maubinle** [comment]
I started playing around with this, and am thinking about how to implement the design. The survey controller is pulling from the db, which today does not get updated as the user is going through the mission but is triggered by specific actions (e.g. user completes mission). I think it would be costly and impact performance to change the db such that it is updated dynamically as the user goes through the mission. 

My suggested design instead would be:
1. If a user is doing their 2nd mission, and they have completed X feet (which we can then change to test out different distances), we should save their progress to the db once
2. Then, we can use the shouldDisplaySurvey function in the SurveyController class to trigger the survey at the right moment

Do you agree with the approach?

**Comment by misaugstad** [comment]
>The survey controller is pulling from the db, which today does not get updated as the user is going through the mission but is triggered by specific actions (e.g. user completes mission)

I don't think that is entirely correct. Although specific actions like finishing a mission does trigger DB updates, it is also updated as the user audits. We send data back to the DB periodically with the labels the user placed on their progress in their current mission, etc. But maybe you are talking about a specific table in the database or something?

**Comment by maubinle** [comment]
sorry, yes -- I'm talking specifically about the "mission" table, which is where we pull how many missions a user has completed from in the surveycontroller. We also use this db table to keep track of the most recent progress a user made in a mission, so it seems fitting in this case.

**Comment by misaugstad** [comment]
>I'm talking specifically about the "mission" table, which is where we pull how many missions a user has completed from in the surveycontroller. We also use this db table to keep track of the most recent progress a user made in a mission

Okay the progress should be updated as the user is auditing... But in any case, we know the progress in the current mission on the front-end already, don't we? So can't we just trigger it from the front-end?

**Comment by maubinle** [comment]
yeah, makes sense, I was mainly just going off what we do today. I'll see how to do that.

**Comment by maubinle** [comment]
fixed via PR 1411.
