### ISSUE TITLE
Put All This Text on One Line

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#137]
Fix 'Miles audited in this mission' and 'Neighborhood miles audited so far' so that they are rendered on one line (either edit the text to use fewer chars or increase the amount of room dedicated to their display).

![image](https://cloud.githubusercontent.com/assets/1621749/16287962/2cb6f25e-38b5-11e6-9735-277d6963e513.png)

**Comment by kotarohara** [comment]
@danZzyy Can you tie this to the issue that you are working on right now?

**Comment by kotarohara** [comment]
I think @danZzyy fixed this. Daniil, can you check and close this? Thanks.

**Comment by danZzyy** [comment]
fixed here https://github.com/ProjectSidewalk/SidewalkWebpage/pull/196
