### ISSUE TITLE
Should make the "Returning to Mission" screen more robust

### ISSUE THREAD

**Issue by lstrobel** [ProjectSidewalk/SidewalkWebpage#1371]
Right now, the "Returning to Mission" screen is a MVP from #865, as submitted in #1370. The screen could be more robust, maybe mirroring the designs presented in the #865 discussion.

**Comment by misaugstad** [comment]
@lstrobel can you add a screenshot of your design here, to the PR #1370, and to the issue #865 ?

**Comment by lstrobel** [comment]
Yes!

Here is the current screen:
![screenshot_2018-12-31 project sidewalk](https://user-images.githubusercontent.com/12887715/50569536-260ad400-0d1c-11e9-943b-c78f8980db9b.png)

**Comment by misaugstad** [comment]
Related to #2152

**Comment by misaugstad** [comment]
We've replaced the old returning to mission screens with our newer mission screen that also helps with instructing users in how to label! I think that we are at a good place with this for now?
![Screenshot from 2024-04-22 16-23-30](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/0ba6ad4e-b8ba-440e-bc0e-84b2031a30ed)
