### ISSUE TITLE
Extend to Los Alamos, NM

### ISSUE THREAD

**Issue by reidpr** [ProjectSidewalk/SidewalkWebpage#1379]
Is this the right place to ask?

Los Alamos is a unified city-county in northern New Mexico. Population roughly 20,000; [102 miles](https://www.losalamosnm.us/UserFiles/Servers/Server_6435726/File/Government/Departments/Public%20Works/Engineering%20and%20Project%20Management%20Division/IMS%202016%20Report%20Rev3%20-%20Los%20Alamos%20Co.pdf) of streets; elevation 7,000 feet; extremely well educated; quite wealthy but a significant anti-tax flavor present. Main employer (mine) is Los Alamos National Laboratory.

In additional to a personal interest in having this coverage for my town, I think there is interesting research value in understanding these types of systems in small towns. I am concerned by the increasing rural/urban divide, and I think making efforts to include more rural areas in the benefits of new technology can help.

I do not have a ton of time to implement things myself, but if I had a sense of the difficulty, I could reach out to others.

On a personal note, my 1yo son is facing some visual impairments as he ages. We don't know how severe they will be, but the majority of people with his condition end up legally blind.

**Comment by jonfroehlich** [comment]
Hi Reid,

Thanks for reaching out. This is indeed the place to have this conversation (we are github fanatics and also passionate about transparency!). 

We agree with you that small-to-medium sized towns could benefit from Project Sidewalk (and we make this argument in our recent CHI'19 paper--preprint [here](https://makeabilitylab.cs.washington.edu/media/publications/Saha_ProjectSidewalkAWebBasedCrowdsourcingToolForCollectingSidewalkAccessibilityDataAtScale_2019.pdf). Thus far, we have only deployed in DC but we are currently in the process of identifying new cities, which is driven by factors like geographic diversity, city size, and whether we have a local advocate (in this case, it would be you and hopefully others in Los Alamos). Our primary focus right now is on preparing for Newberg, OR and Seattle, WA deployments, which will also be the first test of our 2.0 codebase that @misaugstad has been leading. We should talk more about whether to add Los Alamos to the list (upside: you're there; downside: we have two west-coast cities already)--but we should chat!

Re: your son. I'm sorry to hear this. While Project Sidewalk is primarily aimed at those with mobility impairments, its data can and should benefit all of us (including those with other impairments).

PS Also just generally great to hear from you as my team has long been inspired by your work at UMN on [Cyclopath](http://cyclopath.org/)--both as a valuable resource for the Twin Cities and as a research platform.

**Comment by jonfroehlich** [comment]
I just investigated Los Alamos a bit more. Here's the Street View coverage (last drive appears to be ~2014):

![image](https://user-images.githubusercontent.com/1621749/52310006-b8734880-2956-11e9-9fe4-e8b9c9ed0e9c.png)

**Comment by reidpr** [comment]
Thanks for your kind words about Cyclopath! Indeed, I heard about this via a Google Scholar alert about the citation.

A few comments —

1. Los Alamos isn't West Coast; in fact, driving time to the Southern California coast is about the same as the Gulf Coast (13 hours). There are lots of ways to refer to our region, but "high desert southwest" is maybe the best one for this purpose.

2. Visual impairments can bring mobility impairments as well, because it's harder to get around when it's hard to see where you are going. The term of art is "orientation and mobility"; e.g., if Louie ends up needing it, he'll have formal O&M training. E.g., I understand good quality curb cuts have a different-color, different-texture panel in order to be more accessible to people with vision impairments.

Regarding the Street View data, I can enlighten a bit perhaps —

1. Anything on that map without marked streets is uninhabited mountains and canyons at various elevations from say 5,000 to 11,000 feet. This includes the center of town.

2. The un-photographed "streets" on the north and west sides are dirt roads or trails, all closed to public vehicle access.

3. The un-photographed cluster just east of the center is the horse stables; those streets are dirt without sidewalks.

4. Un-photographed streets on the south side are Los Alamos National Laboratory and owned by the federal Department of Energy. Street View probably didn't go there due to access issues and because photography on LANL property is prohibited. That said, LANL is very interested in anything that can be billed as a safety issue, so there might be an opportunity for collaboration.

5. Los Alamos is wealthy and nerdy enough that citizen-operated street photography may be feasible.

I wonder if a phone chat would be a good next step. I'll try to remember to follow up by e-mail on Monday, if not, ping me at reidpr@lanl.gov.

**Comment by jonfroehlich** [comment]
Closing in favor of https://github.com/ProjectSidewalk/SidewalkWebpage/issues/281
