### ISSUE TITLE
Route Turning Green Even Though Not Walking That Street

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#138]
I'm walking down what I thought was the route but then I noticed it wasn't; however, I am still getting credit for walking a street even though I'm no longer on it. 

![image](https://cloud.githubusercontent.com/assets/1621749/16288271/2cc056d4-38b8-11e6-91b0-b91fce6f2b32.png)

![image](https://cloud.githubusercontent.com/assets/1621749/16288300/564bc3da-38b8-11e6-83f3-bddda7d14c7a.png)

**Comment by jonfroehlich** [comment]
Now I'm at end of green route and there is no where else to go (no red route left)... I'll try following the directions on bottom-right of GSV and see what happens.

![image](https://cloud.githubusercontent.com/assets/1621749/16288326/95cf3dde-38b8-11e6-8d67-5219766583dd.png)

**Comment by jonfroehlich** [comment]
And now that I'm back on the green route, I'm actually seeing a new red route, so things look like they might be working again.

![image](https://cloud.githubusercontent.com/assets/1621749/16288391/438dec68-38b9-11e6-8363-a1eef9e831aa.png)

**Comment by kotarohara** [comment]
I don't think there is a fix to this. I'm using a distance threshold to check if the user is actually on the street. This problem happens when there is a nearby street that is parallel to each other.

**Comment by jonfroehlich** [comment]
OK :(

**Comment by kotarohara** [comment]
I'm closing this issue.
