### ISSUE TITLE
Refactoring frontend code and possibly adding in data binding framework to UI

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1380]
@DoctorWarrior provided the following suggestions and thoughts for PS after working on #1309:

> In the file, “ContextMenu.js”, there is a variable, “labelTags”, which is a little tricky. It is used like an array, as I saw some function calls like `indexOf()`, `push()` and `splices()`. However, when you print it in console, you will find it became a hashmap for some reason. My guess is it was originally created and used as an array. However, at some point someone used it like a hashmap so javascript automatically converted the type. It is VERY dangerous. I tried to find out where the “illegal” thing was done in the code base last night. Since I do not know the code base very well, I will probably take more time on this. So if either of you (or anyone on our team) has the knowledge to fix this variable, please do so (and let me know).
> 
> There are too many dependencies in our code base, thus it is very difficult to find things to start with. I would suggest re-modularizing it if possible. Of course, I understand that we might not do this right now because it is not a top priority.
> 
> Our code does not have the ability to refresh the UI automatically, so after we update the data we have to write additional code to refresh the UI. This has led to some unnecessary fragments in our code base. To fix this, I would suggest we investigate some of the available frameworks (such as KnockOut, which provides easy data binding) to improve the structure of our front-tier.
>

**Comment by jonfroehlich** [comment]
Re: ContextMenu.js. I have no idea. You should chat with @aileenzeng directly.

Re: code dependencies. I am not sufficiently familiar with the codebase so I cannot comment; however, I would not be surprised--and I think this is largely a reflection of: the codebase's age, the skillsets of those who contributed, and the lack of an overarching architectural plan from the beginning (which is, in my view, completely reasonable as PS started as a research prototype and has grown organically over time). That said, I imagine this happens with many codebases of the same age. I think @misaugstad has taken a shot at refactoring the backend in the last 6 months but the frontend may need this same kind of love (however, to take this on, would require JavaScript ninja skills and lots of expertise).

Re: refresh UI automatically. I have ~20+ years of UI development experience, and it's only recently that code binding to UI has become a reality. I think this is a crucially important feature for a UI heavy design with lots of buttons, checkboxes, and other fields--but our website has never been like this (except for the context menu and a few other screens). So, while this is a valuable suggestion and potentially something you could take on, I would want to make sure we consider this task in terms of its ROI and in the context of the 100s of other open Issues we have. :)

So, in sum, I really appreciate your suggestions--and I agree that many of them would be nice in an ideal situation (unlimited labor + unlimited personnel) but we have to take a far more pragmatic approach. The key to PS's success is in constantly being aware of problems and new feature requests, discussing them, and then prioritizing TODOs within the constraints that we have.

**Comment by misaugstad** [comment]
>Re: ContextMenu.js. I have no idea. You should chat with @aileenzeng directly.

I believe @DoctorWarrior and I chatted about this some time back and we realized that there is nothing untoward happening with the `labelTags` object.

**Comment by jonfroehlich** [comment]
Closing.
