### ISSUE TITLE
Have to ensure that users cannot validate their own labels

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1382]
The backend system has to ensure that users cannot validate their own labels. 

One challenge here, of course, is how to deal with anonymous users. We could try to provide the same assurances for anon users (based on ip or however we are tracking anonymous users). Alternatively or in addition, we could just weight anonymous validations less than from registered users.

Thoughts?

**Comment by misaugstad** [comment]
I vote for both! Anon users essentially have registered user accounts that they just don't have logins for (though when they restart their browser or whatever they get a new account). So we definitely wouldn't give them any labels created by the same account. We could also go further to other anonymous users who were using the same IP address when they first were auto-logged in.

**Comment by aileenzeng** [comment]
I'm revisiting this right now - so far I am not taking IP Address into account when choosing labels for the validation interface. Is this something that we still want? If so, should all users only receive labels that are from different IP addresses and aren't theirs? Or would this only apply to anonymous users?

**Comment by jonfroehlich** [comment]
Only apply to anon imo

**Comment by misaugstad** [comment]
>so far I am not taking IP Address into account when choosing labels for the validation interface. Is this something that we still want?

I don't think we should bother with IP addresses, since we have anon accounts set up the same way as registered user accounts, which I think gets us most of the way there. I think the way we are currently doing it is sufficient as long as we weight anon user validations slightly less.

**Comment by jonfroehlich** [comment]
Ok. Go with what Mikey said. 😂

**Comment by misaugstad** [comment]
closing via #1467
