### ISSUE TITLE
Tried to use the '-' key when filling out a description in the context menu

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1385]
I tried to use the '-' key when filling out a description in the context menu and, instead, it auto-closed the context menu. Anyone know what's up here? @misaugstad, maybe a good intern task?

![image](https://user-images.githubusercontent.com/1621749/51270629-50929900-197a-11e9-9c36-7e737f93a8aa.png)

**Comment by jonfroehlich** [comment]
Ack, and what's worse is I lost the ability to pan after hitting the '-' and so I had to reload the page! (I have since learned that I can hit the '=' key and I get control back...)

**Comment by misaugstad** [comment]
This is talked about in #678 

We haven't been able to prevent +/- from causing GSV to zoom in/out, even when typing in the feedback or context menu. We auto-close the context menu so that it doesn't look detached from the label when the "-" causes a zoom.

**Comment by jonfroehlich** [comment]
I searched for this before posting but couldn't find it. It's a hard Issue to search for imo.. I just added some additional terms to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/678 to make it more findable in the future (including words like 'minus' and 'dash' and 'plus').

**Comment by misaugstad** [comment]
Awesome, that will be very helpful! I often have trouble finding that issue as well.
