### ISSUE TITLE
Feedback survey comes up too early imo

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1386]
Looks like @maubinle's feedback survey comes up at end of first mission--I think it should be the second mission (it's too abrupt after the first one and also I don't feel like the user has enough experience at this point to answer the questions...)

![image](https://user-images.githubusercontent.com/1621749/51270796-b8e17a80-197a-11e9-8d5f-3f63ac3c7ca5.png)

**Comment by misaugstad** [comment]
I have seen the same behavior, needs to be fixed. We may need a more robust solution than we currently have. As I think it currently goes after the first mission sometimes and second mission sometimes :(

**Comment by maubinle** [comment]
Oh no!

I thought this while playing around with it but each time I tested e2e it
was consistent so I thought I was imagining things. Looks like I’ll need to
change the logic for when the survey is triggered. I’ll fix this this
weekend (hooray for the long weekend!)

**Comment by jonfroehlich** [comment]
Sounds good.

**Comment by misaugstad** [comment]
While testing PR #1360 Aileen ended getting the survey twice (once after the first mission, and again after the 2nd). I'm pretty confident that this has the same root cause as getting the survey at the wrong time. We are depending on one API call to not be completed before another, and we just can't rely on that and will have to figure out a more robust way to do it.

**Comment by maubinle** [comment]
OK! I have implemented a solution to this that also tackles #1362 , and ensures users are only ever shown the survey exactly once (to avoid the bug Aileen saw).

The implementation that I have now shows the survey **the first time a user crosses the 30% completion mark of the second mission**. 59.8% of users who complete the first mission also complete the second, which means we can capture a significantly higher proportion of users in between the 1st and 2nd missions. If we go beyond the 2nd mission, we risk not capturing the opinions of the users who are dropping off (and thus not knowing why they drop off).

If we agree on this approach above, I will do more extensive testing (on all user types, with and without the tutorial) and then open a PR.

**Comment by misaugstad** [comment]
Sounds good to me!
