### ISSUE TITLE
Add link to github project on FAQ page and footer?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#139]
I think we should add a link to this github repo in the footer:

![image](https://cloud.githubusercontent.com/assets/1621749/16288339/c0a9c22c-38b8-11e6-854a-7487488b478a.png)

We should also add a link in the FAQ page and instruct people how to file a bug in the issue tracker.

**Comment by kotarohara** [comment]
Added a link to this repo on FAQ. I don't think we should have GitHub link at the footer.
