### ISSUE TITLE
Add undo functionality / show history on validation interface

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1398]
From #1384: 

> 3) Need to allow users to go back (in case people make mistakes)
>     a) History drop-down? (See all labels they've done this mission?) (Jon's note: I didn't say 'drop-down'--basically, I was suggesting a ribbon-like interface that would continuously update and show the ~5 most recent validations--which you could return to. This has dual benefits: one, it shows the user what they just validated (confirming the validation action) and second, it could be used to go back to a previous validation and change it)
>    b) Undo functionality for labels

**Comment by jonfroehlich** [comment]
IMO, this should be a lower priority for now. Let's see--via user testing--whether users really feel like this is a necessary feature.

**Comment by jonfroehlich** [comment]
I still like the ribbon-based idea to show recent validations and allow user to change mind or update info. Could show ribbon in validation interface and also recent validations on dashboard.

**Comment by jonfroehlich** [comment]
I still think this is a reasonable idea.

We just received an email:

> I hope you are doing well. On my 2546 or 2547 label, I accidentally selected disagree when it should have been agreed. I'm not sure how to go back to the previous scene, so if there is anything that I can do on my end to fix this, please let me know. So sorry for the inconvenience.

I responded:

> This happens semi-frequently to me too (about once every ~100 validations or so, I click the wrong button).
>
> Thanks for letting us know. In the future, we'd like a way for folks to review their validations and make corrections but we have no such feature yet.

**Comment by crescendochu** [comment]
During the Oradell Mapothon today, I accidentally disagreed with a correct label and realized there is no way of going back. Maybe we should have a back button somewhere? Helping users to recover from mistakes is one of [Nielsen's Usability Heuristics](https://www.nngroup.com/articles/ten-usability-heuristics/). :)

**Comment by jonfroehlich** [comment]
I really wish we had this. Just "agreed" with a curb ramp label on a driveway in Newberg. I wrote in correct description but selected wrong button.

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/8f990b8d-5150-4f94-aa70-5cf292dcbadc)

**Comment by misaugstad** [comment]
@srihariKrishnaswamy I'm really excited to have you working on this! I think that it's best to just have the undo button go back to your most recent label. I don't think that we need to worry about anything further back than one label. This should make implementation easier, it should keep the design more simple, and I believe that it should handle the vast majority of cases.
