### ISSUE TITLE
Navbar labels not correctly formatted in Audit page

### ISSUE THREAD

**Issue by maubinle** [ProjectSidewalk/SidewalkWebpage#1409]
The header labels ought to take this "rounded button" format:
![image](https://user-images.githubusercontent.com/16949591/51808048-b963f600-2243-11e9-8fe5-d02d55e7a861.png)

However, on the Audit page, they lose their formatting:
![image](https://user-images.githubusercontent.com/16949591/51808059-dd273c00-2243-11e9-85bc-75ae6d7c87eb.png)

**Comment by misaugstad** [comment]
Also on the validation page, the `Start Validating` button is still being shown. I think that we should:
1. Fix the style of the buttons on the audit page navbar
1. Add the "Start Validating" button to the audit page navbar
1. Remove the "Start Validating" button from the validation page navbar

**Comment by misaugstad** [comment]
closing via #1498
