### ISSUE TITLE
Update Jump Message

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#141]
![image](https://cloud.githubusercontent.com/assets/1621749/16288424/b2ebfd5c-38b9-11e6-8663-4377b21c6d58.png)

Change to:

**Jumped You Back To [Insert Name of Neighborhood]**
You just stepped outside of your mission neighborhood so we auto-magically jumped you back. You have [X] miles to go before you're done with this mission, keep it up!

**Comment by kotarohara** [comment]
#126
