### ISSUE TITLE
Update audit footer url

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1410]
Screenshot of the footer on the audit page: 
![image](https://user-images.githubusercontent.com/25534091/51885218-666f6900-233f-11e9-9397-7667940715fb.png)

The hyperlink to the Makeability Lab on the audit footer still directs to the UMD site. It should probably be updated so it goes directly to `makeabilitylab.cs.washington.edu`.

**Comment by misaugstad** [comment]
fixed via #1468
