### ISSUE TITLE
Something wrong with how users access audit page admin chart

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1418]
The chart below looks really off.

1. The logging of clicking "Start Mapping" on the navbar may be broken. There has to be a nonzero number of people who have clicked on that button.
1. We are missing a _huge_ amount of the traffic to the audit page. This chart only purports to show the conversions from the landing page to the audit page, so there is going to be some discrepancy here, since users can just go directly to the audit page. But I don't think that 90% of users are doing that.
1. Although I imagine a large percentage of those users _were_ turkers who were directed straight to the audit page. However, we should be able to log this!

I propose that we:
1. Fix the logging of the navbar start mapping button
1. Start logging when a turker is directed straight to the audit page (if we aren't already doing that)
1. Add a row to the table for the turker redirect

![how-users-access-audit-chart](https://user-images.githubusercontent.com/6518824/52002119-fc0d1480-2475-11e9-8fda-ce001450e10a.png)

I think the priority on this is actually relatively high, since we want to make sure the logging is being done correctly before new public deployments are in full swing.

**Comment by andrew4699** [comment]
@misaugstad I'm making some good progress here. We're logging the button correctly but reporting it incorrectly. I've fixed that part, now I'm moving on to the Turker stuff.

Could you tell me about the Turker links and how they work/what they do?

**Comment by misaugstad** [comment]
So turkers will get linked to the website with a link that looks something like
`/?referrer=mturk&hitId=h1&workerId=worker1&assignmentId=a1`

And in the `ApplicationController.scala` file I believe we parse that query string, automatically log the turker in with their credentials, and redirect them to the /audit page. So I believe you will just have to follow the logic in the `ApplicationController.scala`'s `index` function and make sure that if/when they are successfully routed to the audit page, that gets logged somehow (and if it is, that it gets added to the table on the admin page).

**Comment by misaugstad** [comment]
closing via #1508

**Comment by misaugstad** [comment]
There seems to be an error with this chart on the test server. See images below:

![chart-fail-1](https://user-images.githubusercontent.com/6518824/53979515-f1701b80-40c2-11e9-8dbe-651c35f41a65.png)
![chart-fail-2](https://user-images.githubusercontent.com/6518824/53979517-f2a14880-40c2-11e9-8917-8446f6c8d44e.png)

**Comment by misaugstad** [comment]
@andrew4699 could you look into this?

**Comment by andrew4699** [comment]
So there's an inconsistency in URL paths between the local and test servers. I believe the double `encodeURIComponent` was required for the test server so I will add that back. However, if you go to the correct URL ([](https://sidewalk-test.cs.washington.edu/adminapi/webpageActivity/Click/module=StartExploring/location=Navbar/route%253D%252F)) it returns nothing.

Does the following query on the test server return anything?

```
SELECT *
FROM webpage_activity
WHERE (activity LIKE '%module=StartExploring%' OR activity LIKE '%module=StartMapping%')
LIMIT 10
```

**Comment by misaugstad** [comment]
closing via #1538 just tested that the fix does work on the test servers :+1:
