### ISSUE TITLE
Add in information about labeling brick in labeling guide

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1421]
https://www.mysuncoast.com/2019/01/30/community-with-disabilities-call-city-sarasota-use-different-materials-downtown/

I think we should improve the labeling guide to mark brick as a surface problem (even if just low severity unless broken brick is visible). Could be added to the cobblestone part of the labeling guide here: https://sidewalk-test.cs.washington.edu/labelingGuide/surfaceProblems. I suggest something like: "How should I label cobblestone, brick sidewalk, or other rough surfaces?" for the title.

**Comment by misaugstad** [comment]
closing via #1519
