### ISSUE TITLE
Labeling guide sub-sections need hyperlinks

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1422]
Similar to [Django docs](https://docs.djangoproject.com/en/2.1/), the [Makeability Lab FAQ](https://makeabilitylab.cs.washington.edu/faq/) and other sites, I want a mouseover permalink for each header so we can hyperlink directly to parts of the guide.

Example of what I want:
![image](https://user-images.githubusercontent.com/1621749/52008991-b1e05f00-2486-11e9-9a0a-0810d7d2290f.png)

Example of what we currently have:
![image](https://user-images.githubusercontent.com/1621749/52008936-9bd29e80-2486-11e9-87f0-a2fc26d29158.png)

**Comment by jonfroehlich** [comment]
This should be a very straightforward fix (maybe < 30 minute job). We have it implemented in the [Makeability Lab FAQ](https://makeabilitylab.cs.washington.edu/faq/). Can someone take it on? @paarig @lstrobel?

**Comment by misaugstad** [comment]
resolved via #1469
