### ISSUE TITLE
Just loaded audit page on newberg and it immediately (and loudly) cheered for me

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1425]
which was quite unsettling. we *have* to change these horrible sound effects.

![image](https://user-images.githubusercontent.com/1621749/52093939-ebda5f80-2571-11e9-9c0c-c69887b097fe.png)

**Comment by misaugstad** [comment]
The issue for the sound effect change is #331 and the cheering happening when you loaded the audit page is almost certainly b/c the parameterization code was not on the server yet :grin: if this happens again we can reopen, but for now I'm going to close it.
