### ISSUE TITLE
Change 'Start Mapping' to 'Start Exploring'? And add orange 'Start Validating' button

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1429]
Change 'Start Mapping' to 'Start Exploring' and add orange 'Start Validating' button next to it. I think 'Start Exploring' feels more intriguing and exciting.

![image](https://user-images.githubusercontent.com/1621749/52134054-95176900-25f7-11e9-9f5b-2e8276fbe033.png)

Related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1420 (but that only covers menu bar).

**Comment by misaugstad** [comment]
closing via #1448
