### ISSUE TITLE
Add 'Date Registered' and 'Last Login' Timestamps to Users Table in Admin Interface

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#143]
Add 'Date Registered' (for the timestamp when the user signed-up) and 'Last Login' Timestamps to Users Table in Admin Interface

![image](https://cloud.githubusercontent.com/assets/1621749/16289304/fe3f385c-38c1-11e6-88b4-f359cc5eef11.png)

**Comment by jonfroehlich** [comment]
Also, can you make these tables have clickable column headers that sort table by ascending/descending. Something similar to: http://lintool.github.io/scholar-scraper/index-hci.html.

Maybe a task for @danZzyy? What do you think @kotarohara?

**Comment by kotarohara** [comment]
Yeah, maybe @danZzyy can work on it. I think it's a good practice for using SQL and Scala.

**Comment by danZzyy** [comment]
I am pretty comfortable with SQL and this is pretty similar to the Scala task Kotaro showed me earlier

**Comment by jonfroehlich** [comment]
Make this table sortable as well by clicking on column header to indicate sorting feature.

**Comment by jonfroehlich** [comment]
At some point, @kotarohara and I discussed having the 'Last Login' = 'Date Registered' when the user never logged in more than once--in other words, their only login was when they registered the account. 

@danZzyy, can you update the UI so that 'Last Login' is never blank reflecting this case? It just helps with sorting the table.
