### ISSUE TITLE
Admin: clicking on an anonymous user results in IllegalFormatConversion

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1436]
Clicking on an anonymous user in the Users tab in admin interface:

![image](https://user-images.githubusercontent.com/1621749/52227864-9fd73580-2865-11e9-8861-283ec2b9c62b.png)

![image](https://user-images.githubusercontent.com/1621749/52227842-89c97500-2865-11e9-905d-8674bb676da0.png)

**Comment by misaugstad** [comment]
duplicate of #1423 

I'll add some of the info from here to make it more easily searchable.
