### ISSUE TITLE
Would smaller neighborhoods be more effective in motivating work?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1437]
As I play around with Newberg, I'm struck still by how large the neighborhoods are. I've probably completed ~8 or so missions in a single neighborhood and I haven't even reached 20% completion for the neighborhood as a whole. When I get the 'end-of-mission' screen, I feel good that I finished a mission but demotivated by how much work is left to do before I can explore a new neighborhood.

A few ways to address this:

- Break up neighborhoods into even smaller chunks (e.g., ~2-3 mile areas)
- Show what others have contributed in the neighborhood (to make the task not feel so overwhelming and to build collective action and a sense of community effort)
- Other ideas?

**Comment by misaugstad** [comment]
Interesting! I had the opposite experience. But that is likely because I was auditing a smaller neighborhood _and_ because I am thinking of it in comparison to DC where we had larger neighborhoods than this.

And related to this is that instead of showing how close you are to *personally* completing the neighborhood, we should probably be showing how the community as a whole is to completing the neighborhood (captured in #846 and #925).

**Comment by jonfroehlich** [comment]
> Interesting! I had the opposite experience. But that is likely because I was auditing a smaller neighborhood and because I am thinking of it in comparison to DC where we had larger neighborhoods than this.

I'd be curious to hear from others on this like @maubinle, @aileenzeng, and some of the new students (@andrew4699, @paarig, @lstrobel, etc.)

> And related to this is that instead of showing how close you are to personally completing the neighborhood, we should probably be showing how the community as a whole is to completing the neighborhood (captured in #846 and #925).

Yes, I think emphasizing wha the community, as a whole, has completed + your contribution to that is important. Of course, we also have to be mindful of how this may affect when we assign the same route multiple times.

**Comment by misaugstad** [comment]
Over time, we've realized that yes, smaller chunks of work is better. We've been making missions smaller. We still use full sized neighborhoods when appropriate, but I've also been erring on the side of smaller neighborhoods when possible. I don't think there is anything else actionable in this thread.
