### ISSUE TITLE
Are we logging all interactions in validation interface

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1438]
Including zooms, pans, etc.

**Comment by aileenzeng** [comment]
Here is a list of actions that we are currently tracking:
* Mouse events (down, up, click)
* Keyboard events (keydown, keyup)
* Unload (when user leaves the page)
* Keyboard shortcuts for validating labels, zooming in and out 
* PanoID changed, POV changed
* All interactions when the user clicks the feedback button

Are there more that we want?

**Comment by jonfroehlich** [comment]
Is this how we log in the normal PS labeling interface? Because I would have thought we would log semantically (e.g., Zoom In, Zoom Out, Pan Started, Pan Ended)... but if you can recover these details from your more fine-grained logging, then I think we're fine.

**Comment by misaugstad** [comment]
Awesome, so it seems like you are logging everything that we log on the audit interface (and I remember discussing this with you as you were writing the code as well). So I think we can close this issue?

**Comment by misaugstad** [comment]
Yeah ok the initial question was if we are logging everything we need to that we had logged on the audit interface and @aileenzeng confirmed that she mimicked the auditing carefully, so I'm closing this.
