### ISSUE TITLE
Jump goes 1 foot away and between same 2 points

### ISSUE THREAD

**Issue by andrew4699** [ProjectSidewalk/SidewalkWebpage#1441]
(Newberg)

When I hit jump > explore a new area, I go to a location 1 foot away from where I jumped. If I hit jump from that new location, it takes me back to my original spot. This continues between edges **959** and **830**.

**Comment by jonfroehlich** [comment]
Haven't seen this behavior since @andrew4699 posted. It's likely quite specific to that route. Closing for now.
