### ISSUE TITLE
Route started on highway

### ISSUE THREAD

**Issue by andrew4699** [ProjectSidewalk/SidewalkWebpage#1442]
(Newberg)

![chrome_2019-02-04_12-48-59](https://user-images.githubusercontent.com/7133966/52236335-71645500-287b-11e9-87c8-2ab111b1e48b.png)

I didn't catch the street edge ID but I was placed on this highway-like road for one of my routes. I found it on Google Maps: https://www.google.com/maps/@45.3119969,-122.9286086,3a,75y,272.03h,84.36t/data=!3m7!1e1!3m5!1sUQcM5R0YoKo-JB7IaBEl7Q!2e0!6s%2F%2Fgeo2.ggpht.com%2Fcbk%3Fpanoid%3DUQcM5R0YoKo-JB7IaBEl7Q%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D62.774784%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656

**Comment by misaugstad** [comment]
So the OSM road categorization isn't an exact science... And there are a couple roads that end up in our dataset that look like this. And removing this category of street would also remove some streets that should truly be included in our dataset.

My opinion is that going through to weed out the few streets like this isn't worth our time. We had some streets like this in DC too. We just placed a bunch of NoSidewalk labels and moved on :wink: 

Thoughts @jonfroehlich

**Comment by jonfroehlich** [comment]
Agree. As long as they are not too common. We should continue to keep track.
