### ISSUE TITLE
"the message port closed before a response was received" console error

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1443]
While moving my mouse around the GSV pane I am getting this error continuously. I don't know if this is causing any issues.

![js-console-error1](https://user-images.githubusercontent.com/6518824/52237239-dcaf2680-287d-11e9-920c-06e830433c97.png)

**Comment by misaugstad** [comment]
I am also seeing this on the production sidewalk site. According to this thread it seems to be just noise, but it also says how to fix it: https://github.com/mozilla/webextension-polyfill/issues/130

**Comment by misaugstad** [comment]
And this is actually happening all across the site, not just the audit page. @andrew4699 do you think there is a possibility that this could be related to the gzip compression change..? That is the only recent site-wide change I can think of.

**Comment by andrew4699** [comment]
I don’t think that gzip would be the culprit. This looks like it’s related
to a browser extension. Could you disable your extensions (or use
incognito) and try again?

**Comment by misaugstad** [comment]
Thanks, that was it! Just one of my browser extensions :+1:
