### ISSUE TITLE
update about page with new team members

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1447]
looks like we haven't updated the about page since Fall of 2017 :rofl: Others please help me edit this post with changes that need to be made:

- [ ] my name: "Michael" -> "Mikey
- [ ] my title: "Graduate Student" -> "Research Scientist" or "Project Lead" or something
- [ ] Teja: "Summer 2017 - Present" -> "Summer 2017 - Spring 2018"
- [ ] Johann and Sarah "Fall 2017 - Present" -> "Fall 2017"
- [ ] Ryan, Steven: "Summer 2017 - Present" -> "Summer 2017 - Fall 2017"
- [ ] Teja, Johann, Sarah, Steven, and Ryan moved to Alumni
- [ ] Add Andrew: "Spring 2019 - Present"
- [ ] Add Ather: "Spring 2019 - Present"
- [ ] Add Richard: "Spring 2019 - Present"
- [ ] Add Sophie: "Spring 2019 - Present"
- [ ] Add Lukas: "Spring 2019 - Present"
- [ ] Add Olga: "Spring 2019 - Present"
- [ ] Add Marianne: "Fall 2018 - Present"
- [ ] Add Puja: TODO: dates?
- [ ] Add Shiven: "Summer 2018 - Present"
- [ ] Add Paari: "Spring 2019 - Present"
- [ ] Add Esther: "Fall 2019 - Present"
- [ ] Add Galen: "Fall 2019 - Present"

We also need to ask everyone for links to the page they want linked to. And default to their github pages if they don't respond :wink:

**Comment by aileenzeng** [comment]
Add me too! 😄 

- [ ] Add Aileen: "Summer 2018 - Present"

**Comment by jonfroehlich** [comment]
Also move David Jacobs to Alumni and put his completion date as Fall 2014.

**Comment by misaugstad** [comment]
@jonfroehlich we missing any publications down there?

**Comment by jonfroehlich** [comment]
I wonder if the About Us page should just point to makeabilitylab.io/projects/projectsidewalk so that we don't have to maintain multiple pages?

**Comment by jonfroehlich** [comment]
Also, I don't typically add new students (e.g., Olga) until after they've completed their trial period.

**Comment by aileenzeng** [comment]
Should we also upload higher resolution images of the publication images? They're pretty blurry on my computer.

**Comment by misaugstad** [comment]
>I wonder if the About Us page should just point to makeabilitylab.io/projects/sidewalk so that we don't have to maintain multiple pages?

100% are there any downsides? I love this idea.

**Comment by jonfroehlich** [comment]
Maybe the call-to-action and about us sections are less clear on the makeabilitylab website but other than that, no downsides?

**Comment by misaugstad** [comment]
IMO that is worth moving to just the ML site then... We could also improve the call to action there if we wanted.

Also note that if we keep the current about page, there is a projecsidewalk.io/audit link in there that should be a relative link instead.

**Comment by misaugstad** [comment]
Oh also a bunch of the team members have links to their UMIACS ML website page, and they just get redirected to the main UW ML landing page. The links need to be fixed to go directly to the user pages on UW site.

**Comment by misaugstad** [comment]
Sometime soon I will just make the about page redirect to the Makeability lab project site.

**Comment by misaugstad** [comment]
closing via #1526
