### ISSUE TITLE
Need About Page

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#145]
Need about page, which includes:

- A quick blurb about the project and some history
- A nice grid of images of all contributors/collaborators
- A list of all academic papers
- A link to our github and a call to contribute back to the project
- A list of sponsors.

**Comment by jonfroehlich** [comment]
I think this is important before our public launch honestly, so I put as very high priority.

**Comment by kotarohara** [comment]
I don't think it deserves Priority: Very High, but I agree it is important (esp. sponsors) :) 

I'm not going to do everything on the list though. I will not do the grid of images; I'm not going to wait for people to send the images. Instead, I'll make a list of names. I think GitHub link doesn't fit here. I added that to Developer page.

**Comment by jonfroehlich** [comment]
OK, I don't think it hurts us to have the github link here as well and it's common in about pages imo.

**Comment by kotarohara** [comment]
Got the first ver done and we think it's good enough for now. I'm closing it for now.

**Comment by jonfroehlich** [comment]
Looks good to me!
