### ISSUE TITLE
'Mission Complete' screen: green route not shown if street not finished

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1450]
![image](https://user-images.githubusercontent.com/1621749/52284898-31a07a80-291a-11e9-8477-9842f411f952.png)

First time I've seen this and I've completed ~8+ missions in Newberg

Update: just finished the mission following the above and now I get a green route highlight but note that I don't see a gray route (for previous mission).

![image](https://user-images.githubusercontent.com/1621749/52285026-75937f80-291a-11e9-8179-b61cb13d1522.png)

**Comment by misaugstad** [comment]
@jonfroehlich one problem is that I believe that this treats street segments as discrete units. So it seems like you were auditing a long street that was longer than that entire first mission. I don't think this is ideal, but that is an explanation, at least :sweat_smile:

**Comment by misaugstad** [comment]
closing via #1909
