### ISSUE TITLE
Is this a 'curb ramp'?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1451]
I remember debating this with @misaugstad one time who said that these types of pedestrian walkways are *not* curb ramps because they are not ramps but I wanted to mark them as ramps (and still do) because they are accessible pedestrian infrastructure to enable people of all abilities to pass through the corner (and thus, functionally serve as ramps). Thoughts? Either way, we should probably address this in the FAQ.

![image](https://user-images.githubusercontent.com/1621749/52285121-a4115a80-291a-11e9-96fd-6247219c5ee3.png)

**Comment by misaugstad** [comment]
The "How should I label islands?" section from https://sidewalk-test.cs.washington.edu/labelingGuide/curbRamps says not to label those as curb ramps.

I agree with you now that they should be labeled as curb ramps, and we should modify the labeling guide to say so.

**Comment by misaugstad** [comment]
closing via #1519
