### ISSUE TITLE
GET panomarker assets failing on admin page

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1454]
If I open the browser console on the admin page I get the error
`GET https://sidewalk-test.cs.washington.edu/assets/javascripts/SVLabel/src/SVLabel/util/UtilitiesPanomarker.js net::ERR_ABORTED 404 (Not Found)`

![panomarker-error](https://user-images.githubusercontent.com/6518824/52298453-d41b2680-2937-11e9-84f1-a65fb25132e8.png)

Any idea what's up @aileenzeng ?

**Comment by aileenzeng** [comment]
@misaugstad I haven't been able to recreate this on my local dev environment. Is this something that you get all the time? Or is this error only on `sidewalk-test.cs.washington.edu`?

**Comment by misaugstad** [comment]
hmm, yeah I get this on my local dev environment too (both Chrome and Firefox)

**Comment by aileenzeng** [comment]
Strange, I can't seem to recreate it locally.

**Comment by misaugstad** [comment]
Do you get it on sidewalk-test.cs.washington.edu?

**Comment by aileenzeng** [comment]
I don't have access to the admin page on `sidewalk-test` :)

**Comment by misaugstad** [comment]
Ahh I found it. We are looking for `UtilitiesPanomarker.js` but the file is called `UtilitiesPanoMarker.js`. I suggest we rename the file to `UtilitiesPanomarker.js` to match `Panomarker.js` :)

**Comment by jonfroehlich** [comment]
Also, let’s give Aileen admin access on test!

**Comment by misaugstad** [comment]
closing via #1505

**Comment by misaugstad** [comment]
>Also, let’s give Aileen admin access on test!

Already done :sunglasses:

**Comment by aileenzeng** [comment]
😍
