### ISSUE TITLE
Create interface for admins to view labels by looking up label ids

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1457]
Back in July, I built an interface in the admin page that allows admins to look up labels by typing in label ids. It's currently not integrated with the main tool. I think this might be a useful addition to the admin page!

**Comment by jonfroehlich** [comment]
Definitely. You can click on the contributions page in admin and, I think, see them there?

**Comment by aileenzeng** [comment]
Yep, that's an option! I was thinking that if you wanted to do a lookup by a specific label id, then you wouldn't have to scroll back through the contributions page.

**Comment by jonfroehlich** [comment]
Definitely would be nice.

**Comment by misaugstad** [comment]
closing via #1487
