### ISSUE TITLE
add appropriate logging for tagging keyboard shortcuts

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1458]
This is mostly my bad for forgetting about this when reviewing PR #1403 

Tagging with keyboard shortcuts is currently logging the following in the `audit_task_interaction` table:
`ContextMenu_TagAdded`

I would suggest:
`KeyboardShortcut_TagAdded`

Which is more in line with how severity keyboard shortcuts are logged (`KeyboardShortcut_Severity_2`).

@lstrobel can you take this on?

**Comment by lstrobel** [comment]
Yeah sure, this seems simple enough.

**Comment by lstrobel** [comment]
@misaugstad, would you want me to completely replace the `ContextMenu_TagAdded` log entry with `KeyboardShortcut_TagAdded`, or add `KeyboardShortcut_TagAdded` as an additional log entry?

**Comment by misaugstad** [comment]
I would replace it, to be consistent with severity keyboard shortcuts.

**Comment by misaugstad** [comment]
closing via #1478
