### ISSUE TITLE
stop logging "clicks" when using keyboard shortcuts

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1459]
It seems as if, for both severity keyboard shortcuts and tagging shortcuts, we are logging `LowLevelEvent_click` incorrectly (there was no click, just a keyboard press). I don't think we are making that mistake when logging keyboard shortcuts for switching label type modes.

Whoever takes this up should check all our different keyboard shortcuts (severity, label type, tagging, zooming, navigation, panning, anything else you can think of) and make sure we are not logging clicks when we do them.

**Comment by andrew4699** [comment]
Our keyboard shortcuts trigger a click on the element to get the same behavior. The simple way to fix this would be to pass a parameter like "stopLowLevel" and our LowLevelEvent logger wouldn't log events with that parameter set. The clean way to fix this would be to refactor all the necessary code into methods so we don't have to rely on triggering clicks, we can call the methods instead. The clean way has the highest chance to cause bugs and will take substantially more work than the simple way.

**Comment by misaugstad** [comment]
Definitely go with simple fix. We aren't trying to overhaul logging right now, just fixing a few bugs :) thanks!

**Comment by misaugstad** [comment]
closing via #1492
