### ISSUE TITLE
How do we know when an anon account is a researcher?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1463]
![image](https://user-images.githubusercontent.com/1621749/52507735-447baf00-2ba7-11e9-8332-d81bf0d0e5b5.png)

**Comment by misaugstad** [comment]
I've been keeping track of that myself. but it would be best if we made sure everyone has an admin account and told them to set the role up researcher when they audit anonymously.

**Comment by misaugstad** [comment]
And to clarify, those are marked as researchers because I went to the admin page and manually changed their roles from anon to researcher. I knew they were researchers bc it was before you sent the email to Newberg folks telling them about the newberg-test server.

**Comment by misaugstad** [comment]
There is no issue to fix here, so I'm closing this thread.
