### ISSUE TITLE
Mission Participation Feedback

### ISSUE THREAD

**Issue by danZzyy** [ProjectSidewalk/SidewalkWebpage#147]
Here I will post all the things I encounter while participating in the missions, which I had not done at length previously.

**Comment by danZzyy** [comment]
1)
![image](https://cloud.githubusercontent.com/assets/13355765/16422486/88029a12-3d26-11e6-8e62-15e6973abf4b.png)
I cannot complete this mission! The map wants me to go in a direction for which there is no link!

**Comment by danZzyy** [comment]
2)
![image](https://cloud.githubusercontent.com/assets/13355765/16422821/bd6ba742-3d27-11e6-81a9-adcc96ed5891.png)
the map overlay is lingering

**Comment by danZzyy** [comment]
3)
![image](https://cloud.githubusercontent.com/assets/13355765/16423130/cf0fc0e0-3d28-11e6-80a8-7c4e2cea4267.png)
little man on the map disappears

**Comment by danZzyy** [comment]
4) at one point it just froze so I had to refresh the page

**Comment by danZzyy** [comment]
5)
![image](https://cloud.githubusercontent.com/assets/13355765/16424120/d2bf056c-3d2c-11e6-8e3d-ce7e99e8451f.png)
distance audited is in km although the missions are in miles

**Comment by danZzyy** [comment]
6)
![image](https://cloud.githubusercontent.com/assets/13355765/16425515/1df36018-3d33-11e6-90e1-7d3f3472aec5.png)
Label disappears

**Comment by kotarohara** [comment]
Can you provide more information on (4)? Also, where is (5)? For (6), how did it happen? Overall, can you provide more context on how they happened?

**Comment by kotarohara** [comment]
Also, you can use a sharp sign (#) to tie an issue back to the existing issue.

**Comment by danZzyy** [comment]
4 happened when I was trying to select a label and the page became unresponsive. 5 is in the user dashboard. 6 I was labeling and then advanced and suddenly the labels did not appear at all

**Comment by danZzyy** [comment]
7)
![image](https://cloud.githubusercontent.com/assets/13355765/16426935/1e0da6f2-3d39-11e6-9390-0c42ab97a746.png)
Completed a long mission but my progress was not recorded in the final stats

**Comment by kotarohara** [comment]
@danZzyy Can you open new issues or tie these back to existing issues?

**Comment by jonfroehlich** [comment]
I agree with @kotarohara. 

@danZzyy: It's best to follow the general rule of one issue per Issue in Github. This is also, generally, the paradigm that we have been using with the other Issues on this repo--so just try to follow those examples.

And as Kotaro said, you need to add more context and descriptions when you post Issues, so that they are easier to understand and then address, as necessary.

**Comment by kotarohara** [comment]
I'm closing this issue as I don't think there are any open problems. @danZzyy let me know if this is not the case.
