### ISSUE TITLE
Dev environment slow to update Javascript files

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1473]
With our new Docker dev environment (PR #1364), @aileenzeng reported some issues with the speed Grunt when it is run. She said that it used to take her <15 seconds to run Grunt with the old dev environment, but that it takes 45-60 seconds with the new Docker dev environment. This is a significant delay b/w making changes to Javascript code and seeing the updates on our local machines.

Hopefully @athersharif has some ideas for how to improve on that!

I will also switch over to the Docker dev environment and post about whether I am having the same issues or not.

**Comment by athersharif** [comment]
https://github.com/ProjectSidewalk/SidewalkWebpage/pull/1364#issuecomment-464227667 for reference on what the underlying issue is. will push a pr soon to fix but would need volunteers using linux, mac, and windows to test this and double check :) @misaugstad thoughts on who would wanna volunteer? :)

**Comment by misaugstad** [comment]
@aileenzeng @andrew4699 or anyone else using Docker, is this still a problem? How quickly does grunt work when editing Javascript files?

**Comment by andrew4699** [comment]
It's pretty fast. Grunt takes about 5 seconds to run.

**Comment by aileenzeng** [comment]
I’m not using Docker for my dev environment, but I can test this out later if needed!

**Comment by misaugstad** [comment]
Ahh no worries, just wanted to hear about any recent usage just in case, but no need to test again.

**Comment by misaugstad** [comment]
Copying over a comment on the PR from @mcdoerr 

>I was running into (15sec - more than a minute) load times with the occasional extremely long load time of about 3 min. I fixed this issue by allocated more CPUs and memory to the docker container, through docker desktop.
>
>The changes for the docker container were 1 CPU -> 4 CPUs and 2GB memory -> 4 GB memory, though I suspect the CPU is what made the difference, not the memory.
>
>Load times are now under 10 secs.
>
>Running on macos big sur 11.2.1, docker version 20.10.2

Closing this now, since this seems pretty well resolves :star_struck:
