### ISSUE TITLE
Parameterize import-dump database name

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1477]
I like to have a few different Project Sidewalk databases set up in my dev environment. I will have one for Newberg, one for Seattle, one with all the DC data, one with a small subset of the DC data, etc. And I give each of them a distinct name (and then just modify the `application.conf` file to use the different databases).

This was easy enough with the old dev environment b/c you had to explicitly name the database anyway.

It looks like it shouldn't be too hard to parameterize `make import-dump` from what I saw. Either by making it possible to pass a parameter to `make import-dump` or by modifying the `db/Dockerfile` or `db/import-dump-sh` file in one place?

@athersharif does this sound doable and would you be able to take it up?

**Comment by athersharif** [comment]
@misaugstad yup, should be easy to do. happy to help!

**Comment by misaugstad** [comment]
Awesome, thank you! It is just related to the dev environment, so it isn't super high priority but still would love to have in the next couple weeks!

**Comment by misaugstad** [comment]
closing via #1494
