### ISSUE TITLE
Arrow keys sometimes don't work and give an error

### ISSUE THREAD

**Issue by andrew4699** [ProjectSidewalk/SidewalkWebpage#1490]
Sometimes I get the following console error when trying to rotate/move with the arrow keys (causing the action to fail):

![chrome_2019-02-25_17-59-37](https://user-images.githubusercontent.com/7133966/53381907-322f9e00-3927-11e9-8c09-1efddf26c930.png)

This is related to #1488. The error is at the line where I added `svl.tracker.push('ContextMenu_Close');`. It's possible that since some context menu close actions now have 2 .._Close events, it's resetting the currentLabel to null twice unnecessarily.

The solution: make 'ContextMenu_Close' the only context menu close event. That is, only that event will reset the currentLabel. Additionally, make it only trigger if the context menu was actually open.

**Comment by misaugstad** [comment]
closing via #1491
