### ISSUE TITLE
Add severity rating to NoSidewalk label in onboarding tutorial?

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1497]
![image](https://user-images.githubusercontent.com/25534091/53536017-92eee000-3ab9-11e9-8540-f2510e393637.png)

Now that NoSidewalk labels have severity ratings, should we rate the severity of the label in the onboarding tutorial?

**Comment by misaugstad** [comment]
This was already added in PR #1485 

It might not be showing up on the server yet b/c we have been making changes to the Docker image and debugging stuff related to that.
