### ISSUE TITLE
Context menu design enhancement

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#15]
Jon's feedback
1. Do we need this checkbox? If so, I think we need to redesign this pop-up UI… it has three parts: rating, temporary problem checkbox, and textfield. The layout/organization feels weird. I don’t like the aesthetic.
2. I like the consistency of having the pop-up interface come up for every label type but I think ‘passable’ feels weird for the curb ramp category —instead, maybe the far left should be something like ‘perfect’ or something.
3. Change this to “Short optional description” – keep the rest.

![contextmenu](https://cloud.githubusercontent.com/assets/612263/13296673/9beabfb4-dafc-11e5-8dff-7a9a807d84ec.png)

**Comment by kotarohara** [comment]
Matt's comment: In the curb ramp popup box for problems you provide some in the description but in the missing curb ramp you don’t.

**Comment by kotarohara** [comment]
Matt's comment: Matt's comment: I think the popup boxes need an explicit close button… it’s confusing without it and then somehow I accidentally deleted the label I just created… not sure why that happened.

**Comment by nguyenist** [comment]
Possible way to redesign: 
![image](https://cloud.githubusercontent.com/assets/4484141/14731360/c2337e56-081d-11e6-9e5f-71b1f33a13dc.png)

**Comment by kotarohara** [comment]
Updated the design. Please see #80
