### ISSUE TITLE
The figure caption in the landing page needs to be shortened

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#150]
![image](https://cloud.githubusercontent.com/assets/612263/16444161/c3bcac08-3daa-11e6-8292-56fb171ebb81.png)

The figure caption for the second figure needs to be trimmed.

**Comment by kotarohara** [comment]
I think this will become obsolete once Updates to Landing Page (#256) is done.

**Comment by Soben713** [comment]
**Original text**:
- The collected data is stored on our server and used to train machine learning algorithms to automatically identify new accessibility problems.

**Alternative, shorter suggestions:**

1. We use the collected data to train machine learning algorithms automatically detect new accessibility problems.
2. We use machine learning algorithms, trained by your data, to automate the process.
3. We use machine learning algorithms, trained by your data, to automate data collection.
4. We use machine learning algorithms, trained by your data, to automate labeling.
5. We use machine learning to find accessibility problems automatically
6. Your data is used to train machine learning algorithms to find new accessibility problems automatically

Thoughts?

**Comment by Soben713** [comment]
This is how it would look like after replacing it with the 6th suggestion. We still need to shorten it.
![image](https://cloud.githubusercontent.com/assets/1576529/20231666/8e8c6860-a831-11e6-8809-f6ce86756de7.png)

**Comment by Soben713** [comment]
PR #417 uses the 6th message, it's shorter than the original one. We should come up with a better layout in the redesigned landing page to make sure this problem is completely resolved. Closing this for now.
