### ISSUE TITLE
Admin View of User Contributions: Clickable Map

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#151]
In reviewing user contributions from the admin interface (e.g., click on a user, which loads an overview page of their contributions--here's mine for example: http://sidewalk.umiacs.umd.edu/admin/user/Jon%20Froehlich), it would be nice if the label circles on the map were clickable. When clicked, we would load a 'view-only' (non-labeling) interface to look at the label in SV. As another suggestion, when you mouse over the circles, might be nice to see a lil pop-up of the label on an appropriately cropped SV image.

![image](https://cloud.githubusercontent.com/assets/1621749/16467327/db1ef134-3e14-11e6-830f-e231fae17ad2.png)

Related issue: #317

**Comment by kotarohara** [comment]
I agree this is low priority.

**Comment by jonfroehlich** [comment]
I still find myself really wanting this feature though. I want to either mouse over the dots and see a quick cropped version of the SV image with the label or to be able to click on the dots and be taken to the SV location with the current user's labels visible.

**Comment by kotarohara** [comment]
Yes, I agree. But all the admin features are low priority for me now unless I need them for writing dissertation.

**Comment by jonfroehlich** [comment]
Yep!

**Comment by jonfroehlich** [comment]
Hmm, but this feature would be really nice for qualitatively exploring user contributed labels. For example, I'm trying to figure out what this user was doing. They have a lot of gray labels and a *very* high density of labels on audited streets.

![image](https://cloud.githubusercontent.com/assets/1621749/16674578/8891fafa-4487-11e6-8ad6-dd4560e1b280.png)

**Comment by jonfroehlich** [comment]
Similarly, what was this user doing? Why do they have so many missing curb ramps in the middle of streets rather than at intersections.

![image](https://cloud.githubusercontent.com/assets/1621749/16674605/b91600c2-4487-11e6-86d3-6f52d1ff069a.png)

**Comment by jonfroehlich** [comment]
Also, this user walked five blocks but really only labeled one intersection, so we really can't count this walked route as a complete audit:

![image](https://cloud.githubusercontent.com/assets/1621749/16687723/47b48d48-44e8-11e6-83ad-1faf0bee94e3.png)

@kotarohara Do we have any idea of how common this behavior is? Or what the general quality of work we are seeing? How are we evaluating worker quality?

I think it's important that we have quality control mechanisms either by having multiple auditors per street and/or by using some sort of heuristic to filter out poor quality workers (e.g., workers that walk many blocks but apply no labels are likely not performing high-quality work). Some combination of things is probably best.

**Comment by jonfroehlich** [comment]
Here's another strange one. This user seems to be marking driveways as curb ramps:

![image](https://cloud.githubusercontent.com/assets/1621749/16687866/011f8116-44e9-11e6-9953-7729d92a77bf.png)

Now that we have active users in our system, I think it's really important that we start monitoring labeling behavior so that we can: (i) improve our tutorials to address common mistakes; (ii) add in active pop-up messages if we see systemic problems (e.g., perhaps we pop-up a dialog box if we see lots of curb ramp labels being applied at non-intersections to help user understand that driveways are not curb ramps--at least not how we define them); (iii) update our FAQ; (iv) add animated gifs or tutorial videos.

**Comment by jonfroehlich** [comment]
Just judging by this top-down map, it appears that this user did pretty well (obviously can't be sure without inspecting the labels themselves); however, strangely the user did not audit the end intersections of streets, which I've circled in red. Why might this be? Perhaps these are drop points and the user did not look around at the drop point before taking a step? Or perhaps they are end points and the user could not audit the intersection before either being auto-transported to a different location in the neighborhood or finishing a mission.

![image](https://cloud.githubusercontent.com/assets/1621749/16688015/f3c249bc-44e9-11e6-89d1-897348b70d2b.png)

**Comment by jonfroehlich** [comment]
Looks like this user didn't understand the task as it appears they went off-route (I'm guessing you only count audited streets that occurred on the directed path). Notice how this user labeled lots of stuff but only one small part is marked as an 'audited street' (in black). This user also placed lots of 'Surface Problem' labels in this area, which may be accurate but we can't tell because there is no easy way to inspect user's labels. Consequently, I'm bumping this Issue to a higher priority. 

![image](https://cloud.githubusercontent.com/assets/1621749/16695131/f538bd68-450b-11e6-856e-9913c80232bd.png)

**Comment by jonfroehlich** [comment]
@kotarohara, any thoughts on this?

**Comment by jonfroehlich** [comment]
@manaswis, with the public launch, I think it's really important that we have a better understanding of how users are performing our tasks. My idea here would really go a long way in helping us do that.

We can discuss it tomorrow but I think it might need to be the next thing in your queue (or perhaps something that @Soben713 can work on).

**Comment by manaswis** [comment]
Hmm, it certainly is important to understand both user labeling behavior or misbehavior of the mission algorithms. I will add it to the list of issues we want to discuss tomorrow.

**Comment by jonfroehlich** [comment]
Great, thanks.

**Comment by manaswis** [comment]
This will, in part, be solved with https://github.com/ProjectSidewalk/SidewalkWebpage/issues/222

**Comment by jonfroehlich** [comment]
Well, the map-based solution proposed above would be way nicer and I think more usability/helpful. But let's start with #222 and see how you do.

**Comment by jonfroehlich** [comment]
This continues to be a potentially huge issue. Yes, we appear to be getting user contributions but we have no way of evaluating the quality of that work and based on a cursory review, I'm concerned. 

![image](https://cloud.githubusercontent.com/assets/1621749/18333156/8f502374-753a-11e6-94e4-3e10500a8760.png)

This particular user was auditing for over an hour today but I'm concerned that some of that work was for nothing because they may not have understood the task. We need to pull out common mistakes and put them in the FAQ.

**Comment by Soben713** [comment]
This is resolved in PR #381.

**Comment by manaswis** [comment]
Wafflebot closed since I merged it. Reopened it till complete review is done.
