### ISSUE TITLE
Obstacle in path example is weird

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1511]
This tree doesn't even look like it's on a sidewalk (or even that a sidewalk exists in this image).

![image](https://user-images.githubusercontent.com/1621749/53781510-02037480-3ebe-11e9-95f2-31cdd358c8ab.png)

**Comment by misaugstad** [comment]
I agree, it seems like a poor angle (or just too far zoomed in). We could use a new image there.

**Comment by aileenzeng** [comment]
How about this?
![image](https://user-images.githubusercontent.com/25534091/55841450-0980f380-5ae4-11e9-841a-f08a4afcbc05.png)

**Comment by misaugstad** [comment]
That is better... but it still kinda looks like the sidewalk is just ending there anyway :sweat_smile: 

Also you want to probably put the label a bit lower on the trunk!

**Comment by aileenzeng** [comment]
Hmm good point. What about this one?

![image](https://user-images.githubusercontent.com/25534091/55841874-e6efda00-5ae5-11e9-8955-5bbf94deafb2.png)

**Comment by misaugstad** [comment]
That one looks great!

**Comment by misaugstad** [comment]
closing via #1632
