### ISSUE TITLE
If we keep hide label on left then text should be centered between left and right set of buttons

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1512]
If we keep hide label on left then text should be centered between left and right set of buttons (though I'd like to see a mock first). And, of course, we may also just want to move the 'hide label' button... 

![image](https://user-images.githubusercontent.com/1621749/53781541-21020680-3ebe-11e9-9d0b-9ea89871e47d.png)

**Comment by misaugstad** [comment]
closing via #1518
