### ISSUE TITLE
grunt not found when running npm start

### ISSUE THREAD

**Issue by AmethystGear** [ProjectSidewalk/SidewalkWebpage#1517]
I get this error when I run ```npm start``` on a newly made container:
![image](https://user-images.githubusercontent.com/21998904/53855356-1610aa00-3f82-11e9-9c0e-f78e82bd88aa.png)
running ```npm install grunt``` fixes this for the container, but if the container is deleted and a new container is made, this error pops up again. 
Found this error while testing on windows.

**Comment by lstrobel** [comment]
I had the same error. The fix posted worked for me. I do still get the warning `>> Local Npm module "grunt-contrib-jasmine" not found. Is it installed?`, but the site still works regardless.

**Comment by andrew4699** [comment]
I got the same issue on Ubuntu 16.04. The posted fix worked.

**Comment by misaugstad** [comment]
closing via #1804
