### ISSUE TITLE
Unlabeled Login

### ISSUE THREAD

**Issue by danZzyy** [ProjectSidewalk/SidewalkWebpage#152]
The login fields are labeled in the text field only and disappear when you begin to type. I think there should be labels before each text field so the user does not get confused whether they should be entering username or email.
![image](https://cloud.githubusercontent.com/assets/13355765/16499016/7b787a8a-3ecc-11e6-86d6-71547e93e864.png)

**Comment by kotarohara** [comment]
Can you make a mock up?

**Comment by kotarohara** [comment]
We'll see if it'll look good. Low priority task, so you can do it when you are done with the current task.

**Comment by jonfroehlich** [comment]
Honestly, I like it as is but I could be convinced to change it if Dan's
mockup is good. :)

On Thu, Jul 7, 2016 at 6:20 PM, Kotaro Hara <notifications@github.com>
wrote:

> We'll see if it'll look good. Low priority task, so you can do it when you
> are done with the current task.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ProjectSidewalk/SidewalkWebpage/issues/152#issuecomment-231225249>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABi-9XvzzSePsXcFfYJCnYzoPis9yFniks5qTXuhgaJpZM4JCbvX>
> .
>



-- 
Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich <https://twitter.com/jonfroehlich> - Twitter

**Comment by kotarohara** [comment]
Ok, I'm closing this. Please reopen if it needs to be discussed.

**Comment by jonfroehlich** [comment]
I agree that it can be closed. I think it's fine as is.

**Comment by Soben713** [comment]
I agree with @danZzyy and I don't think this issue should be closed. This link maybe useful to see why:
https://www.nngroup.com/articles/form-design-placeholders/

**Comment by jonfroehlich** [comment]
Ok. Reopen and mock up suggested improved interface that addresses problem; however, don't do it now as we have far more serious and important issues to address. I think Kotaro closed it because he is satisficing--something that we are constantly doing currently because we simply have so many open issues.
