### ISSUE TITLE
Migrate Newberg Audit Data from Test to Production

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1523]
A highly engaged Newberg citizen just audited an entire neighborhood in Newberg (see below). We'd like to keep this data by integrating it into the production server, but how?

![image](https://user-images.githubusercontent.com/1621749/53960711-d76f1280-409b-11e9-9024-a9946dc3572c.png)

Here are @misaugstad's thoughts:
> I think it is possible to rescue the data... We would
> - Use the test server database
> - Delete all the validations
> - Delete the credentials/accounts of the fake anonymous users from that bug I mentioned before.
> - Be sad that we have some bad data because this was a test server and not everything was legit.
> - Be sad that we have some incomplete data because we didn't have NoSidewalk severity ratings, etc for the whole life of the test server.
> - Pray that none of the things we fixed since we started the test server cause giant headaches when trying to analyze the data from Newberg a year from now.

> Another option I have been thinking about is figuring out how to move this user's data into a fresh database... I just suspect that there might be some problems with moving his credentials over, there is definitely some magic going on under the hood that I don't understand. But if I can get this to work, this might be the best solution.

**Comment by jonfroehlich** [comment]
I think the last option--that is, to only rescue this user's data (and ignore everything else)--is the best option. Can we do that? How long would that take to figure out? Also, how close are we to pushing to production and releasing Newberg more formally>

**Comment by misaugstad** [comment]
>I think the last option--that is, to only rescue this user's data (and ignore everything else)--is the best option. Can we do that? How long would that take to figure out?

I'm going to spend today on this problem, and hopefully I can just get it resolved today.

>Also, how close are we to pushing to production and releasing Newberg more formally>

Before this came up, we just needed @mechanicjay to set up the new server, we were all set to deploy.

**Comment by jonfroehlich** [comment]
Ok!

Is Jason aware that he needs to be setting up the production server? I’m not sure I’ve seen those emails...

**Comment by jonfroehlich** [comment]
Never mind, I see that email now!

**Comment by misaugstad** [comment]
>>I think the last option--that is, to only rescue this user's data (and ignore everything else)--is the best option. Can we do that? How long would that take to figure out?
>
>I'm going to spend today on this problem, and hopefully I can just get it resolved today.

I just tried creating a user in a database, then migrating that user's credentials over to a new database and was unable to do so, got some cryptic error :( Given the time-sensitive nature of this, I'm going to go with the first option, and just try to clean the old database as best I can.

**Comment by misaugstad** [comment]
Did it, Newberg server is live with the migrated data! https://sidewalk-newberg.cs.washington.edu/
