### ISSUE TITLE
Admin analytics tab: graphs don't work if no data

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1525]
The missions completed per user and labels per user graphs don't load if one of the user groups doesn't have any data to go on that graph.

![graph-fail-1](https://user-images.githubusercontent.com/6518824/53979390-86bee000-40c2-11e9-98f5-ea96b7436748.png)
![graph-fail-2](https://user-images.githubusercontent.com/6518824/53979392-87f00d00-40c2-11e9-8092-2d3a5ab4ecc3.png)

**Comment by andrew4699** [comment]
Resolved in https://github.com/ProjectSidewalk/SidewalkWebpage/pull/1628
