### ISSUE TITLE
CRLF line endings break Docker setup scripts

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1527]
For some reason, we seem to have Windows style line endings on our Docker scripts (`db/init.sh` and `db/import-dump.sh`). Our Docker container is running Linux, and the scripts fail with a cryptic error like `sh: 1: /opt/import-dump.sh: not found`.

Taken from [this Stackoverflow post](https://stackoverflow.com/a/19283453), we can fix the line endings by running
```
sed -i 's/\r//g' db/init.sh
sed -i 's/\r//g' db/import-dump.sh
```

I think we may want to add a [.gitattributes](https://help.github.com/en/articles/dealing-with-line-endings#per-repository-settings) file to set the default line endings for the repo to fix the issue.

**Comment by misaugstad** [comment]
This issue has been encountered by myself and @lstrobel and the fix worked for both of us.

**Comment by misaugstad** [comment]
And thanks @athersharif for figuring out the fix in the first place!

**Comment by athersharif** [comment]
@misaugstad love the idea of .gitattributes file. adding `sed` to each shell script execution is so aesthetically displeasing 🤣

**Comment by misaugstad** [comment]
closing via #1704

**Comment by misaugstad** [comment]
this isn't fixing things when setting up fresh systems.

**Comment by misaugstad** [comment]
This has not been a problem for awhile, so I think we're good here :crossed_fingers:
