### ISSUE TITLE
After you click on 'Validate 10 more labels', there is a noticeable delay

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1528]
After you click on 'Validate 10 more labels' on the validation mission completion screen, there is a noticeable delay. The delay itself isn't a huge problem but as soon as you click the button, the mission completion screen disappears and you can then interact with the underlying validation screen again (even though this is showing data from the previous mission). Does this make sense? If you try it out, should be more clear... I can also make a video.

**Comment by misaugstad** [comment]
Agreed, I see the same thing.

**Comment by misaugstad** [comment]
This likely has the same cause as #1415, which is that we are allowed to click the continue button before the next mission has been loaded from the server. So we can probably use the same fix, done in PR #1594, which prevents the user from clicking the continue button until we've loaded the next mission.

**Comment by misaugstad** [comment]
closing via #1610

**Comment by misaugstad** [comment]
This is actually still happening. Even though we have the continue button grayed out and the wait cursor shown, if you click the continue button, it will show you the old mission's label until the new mission finishes loading. Our previous fix seemed to only prevent users from clicking continue too early after finishing their _first_ mission, but all subsequent missions still have the bug :rofl:

**Comment by misaugstad** [comment]
closing via #1699
