### ISSUE TITLE
Update Keyboard Shortcuts in FAQ

### ISSUE THREAD

**Issue by danZzyy** [ProjectSidewalk/SidewalkWebpage#153]
![image](https://cloud.githubusercontent.com/assets/13355765/16499236/74ce8a34-3ecd-11e6-9f25-91ad1847dc65.png)

We not have the 1,2,3,4,5, enter for label rating, as well as panorama moving and rotating with arrow keys.
Also only 2 questions does not seem like much of a FAQ for now

**Comment by kotarohara** [comment]
@danZzyy 

Can you do it after you are done with your current task?
