### ISSUE TITLE
How can I tell what zoom level I'm at in validation interface?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1530]
How can I tell what zoom level I'm at in validation interface? There doesn't seem to be any way I can tell other than playing with the zoom in and out controls.

**Comment by misaugstad** [comment]
Is this something you think is worth seeing in the interface? IMO it isn't that important and is unlikely to be worth the visual clutter.

**Comment by jonfroehlich** [comment]
At the very least, the zoom in and out buttons should be *grayed* out when you are in the most zoomed in state and in the most zoomed out state. They are not currently. This should add not visual clutter and should also be easy to implement.

**Comment by misaugstad** [comment]
^^ Good idea

**Comment by jonfroehlich** [comment]
And I'm pretty sure this is how the core labeling interface works! :)

**Comment by misaugstad** [comment]
closing via #1623

**Comment by jonfroehlich** [comment]
I believe this isn't working properly. I don't think @htadeusiak realized that @aileenzeng's validation interface uses the zoom level that the labeler used for each new validation screen. Consequently, he is disabling the buttons at the wrong time for some locations (note: not for all locations because, again, it depends on what zoom level the original labeler was using, I believe--though @aileenzeng can correct me if I'm wrong).

The following video shows two instances where the zoom is clearly broken. When the location loads, the "Zoom Out" button is disabled but once I "Zoom In" once, I can then "Zoom Out" *twice*!

https://youtu.be/j7xaLI-7mwU

**Comment by aileenzeng** [comment]
Hmmm - one thing that I noticed is that it doesn't look like we're doing a check to see if we should enable/disable zoom when we initially load a new label onto the validation interface.

There's a function called `setLabel` in `Panorama.js` that might be a good place to add this check!

**Comment by jonfroehlich** [comment]
Thanks @aileenzeng.

**Comment by misaugstad** [comment]
My bad, I should have continued testing more thoroughly. Initial tests worked great for me, but clearly I missed something!

**Comment by misaugstad** [comment]
closing via #1639
