### ISSUE TITLE
Multi-user clustering failing for The Greens in Newberg

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1531]
There is a discrepancy between the /results map and the admin map. Check out the 'The Greens' neighborhood on the /results page. Note how it says 36% complete but with no labels--I thought that was weird!

![image](https://user-images.githubusercontent.com/1621749/54032868-a65c1400-4167-11e9-8547-cf72ef3e3f15.png)

So, I investigated on the admin page map and, sure enough, there are actually labels here...

![image](https://user-images.githubusercontent.com/1621749/54032935-d9060c80-4167-11e9-838a-d9c50cfae76e.png)

**Comment by misaugstad** [comment]
The reason is that the /results viz uses clusters while the admin map uses labels. The clusters are not added in real time like the labels are. I audited The Greens last night then didn't run clustering, which explains the discrepancy.

Unfortunately, right now I need to manually run clustering myself. Adding automated nightly clustering (and possibly real-time or hourly) is on the near-term TODO list #1267

**Comment by jonfroehlich** [comment]
> Unfortunately, right now I need to manually run clustering myself. Adding automated nightly clustering (and possibly real-time or hourly) is on the near-term TODO list #1267 

OK, great. I agree that this should not be manual. :)

**Comment by misaugstad** [comment]
Actually, just tried to run clustering. Single-user clustering worked. Multi-user clustering failed, but it seemed to work have failed at the end, while doing The Greens. Going to test on my local environment to see if I can reproduce.

**Comment by misaugstad** [comment]
Was not able to reproduce on my local Docker setup, things worked just fine. I asked @mechanicjay for the log file from the production server so I can investigate.

**Comment by misaugstad** [comment]
Didn't see anything related to this in the log file :( will continue investigating next week.

**Comment by misaugstad** [comment]
it seems to be working now, but I have no idea why :cry:

**Comment by jonfroehlich** [comment]
Divine intervention Mikey! Or aliens!

**Comment by misaugstad** [comment]
We've made various updates to the clustering script since this bug occurred, and I believe we've got it fixed. Not seeing this problem on the server anymore!
