### ISSUE TITLE
Possible to show the underlying point labels (clusters) on /results page?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1532]
I think it would be really cool to see the underlying label clusters on the /results page. These could just be shown similar to how they are on the admin map (drawn on top of the choropleth color).

![image](https://user-images.githubusercontent.com/1621749/54033036-1cf91180-4168-11e9-9371-4a6477520420.png)

**Comment by misaugstad** [comment]
In larger cities like DC/Seattle, there will be far too many labels/clusters for this to work. The page would likely become unresponsive, or at the very least take far too long to load (and the page already takes a bit longer than we want). I just don't see a way this ends up being added to the current viz.

Possibly if @manaswis @tongning and @richardwmcgovern make entirely new visualizations that are more performant, this could be possible. But not on the current viz.

We also discussed this idea in #1462

**Comment by jonfroehlich** [comment]
I don't think it would be that hard to make a rasterized overlay of label clusters every ~1 hr on the backend that is then displayed on the map. Bt fine.
