### ISSUE TITLE
'Are you sure you want to refresh page'?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1533]
The Newberg user mentioned accidentally hitting refresh on their keyboard (F5, I think) when trying to select a severity value instead. Though this has never happened to me before, it happened to me a few times this morning!

So, I wonder if we want to consider having a pop-up asking 'Are you sure you want to refresh' or something similar. I know some websites have warnings like: 'Are you sure you want to leave this page' when there is unsaved work.

**Comment by misaugstad** [comment]
It wasn't that they were accidentally hitting refresh, it was that they were hitting the 'back' button on their mouse. But I think the solution applies in both cases.

**Comment by misaugstad** [comment]
I think we actually don't need this anymore, since refreshing the page puts you right back where you were! :)

**Comment by jonfroehlich** [comment]
Great!
