### ISSUE TITLE
Add individual label count in user's dashboard

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#155]
In the 'General Info and Stats' section, would be nice to have both overall label count (which you have) as well as a total for each of the label types (e.g., curb ramps, sidewalks obstacles, etc.).

![image](https://cloud.githubusercontent.com/assets/1621749/16667962/ebf39aca-445c-11e6-8286-42352dfd2b19.png)

**Comment by kotarohara** [comment]
Yeah. It's not a high priority task though.

**Comment by jonfroehlich** [comment]
Would be nice to have and easy to implement imo. Just a SQL query and a bit of UI :)

How full is @danZzyy's plate? :)

**Comment by kotarohara** [comment]
I think it depends on how hard it is to redesign the Mission Complete Modal #166 . This could be challenging as it requires some d3, but I want @danZzyy to work on it before doing anything else.

**Comment by kotarohara** [comment]
Related to #12
