### ISSUE TITLE
Endless mission complete + resume mission loop

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1553]
I was auditing my first-ever mission on Seattle test server. Here are the steps that occurred:

1. Selected Bryant region to audit (region 12). Did not sign in. Did not take tutorial
2. Was auditing along when greeted by pop-up that said: "looks like you've been auditing alot, do you want to sign in." I didn't realize that I wasn't signed in, so I then chose to sign in
3. I took a few more steps and then was greeted by a mission complete screen. 
4. I clicked 'Continue' and then was immediately greeted by a 'resume mission screen'
5. Then I entered into an endless cycle of taking a step and getting a mission complete screen followed immediately by a resume mission screen.

Video here: https://youtu.be/a9nAK2Nmpaw

**Comment by misaugstad** [comment]
We haven't seen this since and we've also changed how we track missions on the front-end since then, so I'm going to close this for now.
