### ISSUE TITLE
Feedback survey is kind of abrupt

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1554]
Can the title of the survey say something like: "Please take this one-time survey about your thoughts and use of Project Sidewalk" rather than just "Feedback survey."

![image](https://user-images.githubusercontent.com/1621749/54280785-8b1d4a00-4555-11e9-8154-718df670f149.png)

**Comment by misaugstad** [comment]
Trying to keep it to one line, what about:
"Please take this one-time survey about Project Sidewalk"

**Comment by misaugstad** [comment]
closing via #1565
