### ISSUE TITLE
Newberg: completing missions in Springbrook South that are outside of the highlighted neighborhood?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1558]
I appear to be completing missions in Springbrook South that are outside of the neighborhood. See green highlights.

![image](https://user-images.githubusercontent.com/1621749/54396503-6f5a9680-4670-11e9-989a-5a74d92461cd.png)

**Comment by misaugstad** [comment]
This was originally mentioned in [this comment](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1373#issuecomment-457807579) on #1373 and seems to be specific to Springbrook South.

Based on the image @richardwmcgovern showed in that (and the following) comment, the piece of road to the west seems fine to leave in this neighborhood. The pieces just north of Springbrook South should probably be moved into the Airport neighborhood, where they are physically located.

**Comment by jonfroehlich** [comment]
No longer relevant (given that Newberg is completed) so closing.

**Comment by misaugstad** [comment]
I do still want to fix this in the database. Streets are still listed in the wrong neighborhoods for those using the API. This really shouldn't be hard to do at all, it is just so low priority that I haven't gotten around to it. But I still really want to do it.

**Comment by jonfroehlich** [comment]
It becomes less relevant over time as Newberg has already conducted their own analysis of the data we collected... just fyi.

**Comment by misaugstad** [comment]
Fair enough! :)
