### ISSUE TITLE
Consider hiding 'Retake Tutorial' menu option when taking tutorial

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#156]
When taking the tutorial, consider hiding the 'Retake Tutorial' menu option in the interface. It's a bit confusing having it there.

![image](https://cloud.githubusercontent.com/assets/1621749/16668020/44e3292a-445d-11e6-8c2e-e35d6fc028d5.png)

**Comment by kotarohara** [comment]
I don't think it's necessary.

**Comment by jonfroehlich** [comment]
I think it only makes sense to show this once you've finished the tutorial--otherwise, how can you retake something you've not done. This is needlessly confusing and an easy thing to fix... 

But I agree that it is a low priority.

**Comment by jonfroehlich** [comment]
We can quickly discuss this one as a team and then close the Issue or address it quickly.

Tagging @manaswis, @kotarohara, & @Soben713.

**Comment by kotarohara** [comment]
Actually this has been implemented. I'm closing it.
