### ISSUE TITLE
Validate bug: SVValidate.js:410 Uncaught TypeError: Cannot read property 'left' of null

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1561]
I'm trying to click the 'Unsure' button but the interface is unresponsive. Here's the console printout:

```
SVValidate.js:410 Uncaught TypeError: Cannot read property 'left' of null
    at Label.validate (SVValidate.js:410)
    at validateLabel (SVValidate.js:631)
    at HTMLButtonElement.<anonymous> (SVValidate.js:617)
    at HTMLButtonElement.dispatch (jquery-1.12.2.min.js:3)
    at HTMLButtonElement.r.handle (jquery-1.12.2.min.js:3)
```

![image](https://user-images.githubusercontent.com/1621749/54432754-57722980-46e7-11e9-9440-47c5fd0d225d.png)

I think this happened to me once before as well.

**Comment by aileenzeng** [comment]
Hmmm... this is unfortunate :( Do you remember if there was anything else that was going on? (Like things loading slowly)?

**Comment by jonfroehlich** [comment]
I'm continuing to receive this error fairly frequently so would be good to test Aileen's fix (her recent PR). It's a "silent failure" as well in that I can still click buttons but they are no longer responsive, which is a totally broken user experience.

![image](https://user-images.githubusercontent.com/1621749/54932490-24464c00-4ed8-11e9-8c9f-534dd3ecc484.png)
