### ISSUE TITLE
Constant page refresh on audit page

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1563]
We have 3 confirmed cases of this. First is from an email from a Newberg citizen:

>I clicked on the link in the blurb and when I selected “start exploring” it is just loading and flashing the green loading symbol but never loads. I’m on Google Chrome. I also tried incognito mode in case it was a cookie/cache problem and that didn’t help. Is there a better browser to use?

Then @manaswis tried to reproduce and was able to like so:

>It happens when I go to incognito mode. But it doesn't otherwise. I did a hard refresh (in normal mode) and it doesn't happen. Only in incognito mode. Not sure what that happens.

But then (from @manaswis):

>I tried loading again in incognito mode to confirm there were no errors and it didn't reload continuously! :/ 

I also encountered this bug yesterday. I was testing out the workflow for AMT and go this bug on the Newberg test server as a turker. However, if I logged out of the turker account, this wasn't a problem. And then I logged into my personal account and it wasn't a problem. I then logged back into the turker account and the bug came back!!

So it seems to me that the bug is attached to specific users..?? Which would explain the behavior I saw, and the behavior @manaswis saw (because opening incognito a 2nd time would create a new anon user account). It doesn't necessarily explain the behavior from the Newberg user who had the problem on both incognito and normal modes, unless they were unlucky and just happened to have the error for both of their accounts.

**Comment by misaugstad** [comment]
I just tried logging in again today with that same turker user, and am having the same problem. I do see an error in the console right before the page refreshes that says `Error loading Street View imagery: ZERO_RESULTS`.

**Comment by misaugstad** [comment]
Update: If I try manually selecting different neighborhoods this doesn't happen. It is only happening in the Oak Knoll neighborhood for me on the test server. I am going to try all the different neighborhoods on the test/prod servers with different accounts to try and narrow down the problem.

**Comment by misaugstad** [comment]
Visiting the same neighborhood as an anon user other registered user did not cause a problem.

I also checked the database and I don't see an audit task being created in that region for the turker user since March 8th. So we are not even getting as far as assigning a new audit task.

I asked @mechanicjay for the application.log file for the newberg test server to see if any errors are popping up on the back-end that could aid in the search.

**Comment by jonfroehlich** [comment]
This just happened to me this morning on Newberg.

1. I visited https://sidewalk-newberg.cs.washington.edu/
2. Clicked Sign In
3. Clicked Admin
4. Clicked Start Exploring
5. Unending page refresh

![IMB_ngUNxO](https://user-images.githubusercontent.com/1621749/54476366-aab4ac80-47b9-11e9-8937-08180e8d5c83.GIF)

I also closed my browser and tried again. Same problem. I opened console and this is what I saw (but the console clears on auto-refresh--I managed to stop page reload to capture this):

![image](https://user-images.githubusercontent.com/1621749/54476388-f2d3cf00-47b9-11e9-94ae-2a45ed17daff.png)

![image](https://user-images.githubusercontent.com/1621749/54476394-fd8e6400-47b9-11e9-95e1-4845f7fed810.png)

```
audit:1165 Error loading Street View imagery: ZERO_RESULTS
(anonymous) @ audit:1165
f_ @ streetview.js:35
(anonymous) @ common.js:6
c @ common.js:67
(anonymous) @ GeoPhotoService.SingleImageSearch?pb=!1m5!1sapiv3!5sUS!11m2!1m1!1b0!2m4!1m2!3d45.28561607060054!4d-122.95482406204883!2d25!3m20!1m1!3b1!2m2!1sen!2sUS!9m1!1e2!11m12!1m3!1e2!2b1!3e2!1m3!1e3!2b1!3e2!1m3!1e10!2b1!3e2!4m6!1e1!1e2!1e3!1e4!1e8!1e6&callback=_xdc_._3vxzu4:1
```

**Comment by misaugstad** [comment]
Ugh, I can consistently recreate the bug on the sidewalk-newberg-test server but haven't been able to recreate on my dev environment :sob: 

I can recreate it on sidewalk-newberg-test by going to an incognito window and trying to visit the audit page. If it doesn't work, I close the window, reopen a new incognito window and try again. It usually doesn't take too many attempts to get the bug.

Unfortunately that error in the browser console is not particularly illuminating, there are no errors in the sbt console, and I can't recreate the bug on my local dev environment!! 

This is a very very important bug that needs to be fixed and I don't have much in the way of leads right now. So if anyone can help out by trying to recreate the bug on the test server as well, and then seeing if they can recreate it on their dev environment as well, that would be super helpful. Or if anyone has any ideas for what the issue might be, I am all ears!

**Comment by jonfroehlich** [comment]
What about the server logs?

**Comment by misaugstad** [comment]
Server logs is what I meant by sbt console. I asked Jason for the logs and there is nothing in them :cry:

**Comment by misaugstad** [comment]
Update: It seems like on the Newberg-test server, this seems to be happening only with the Springbrook North neighborhood... I can reproduce right now by trying to audit the Springbrook North neighborhood (region 13 :ghost: ) with any account.

I'm going to see if I can reproduce on a different test server...

**Comment by misaugstad** [comment]
I may ask Jason for a database dump from the Newberg test server so I can try my local dev environment with the exact database.

**Comment by misaugstad** [comment]
Oh thank goodness I was able to reproduce on my local dev environment by going directly to the Springbrook North neighborhood. I guess it just wasn't being automatically assigned on my local environment because there were other neighborhoods that had a smaller percentage of them audited...

**Comment by misaugstad** [comment]
Ahh, looks like the error in the console is accurate. This is simply a street edge with no GSV imagery!

![no-imagery](https://user-images.githubusercontent.com/6518824/54569031-b1e4e180-4996-11e9-9d98-33d2e95829f6.png)

**Comment by misaugstad** [comment]
I've marked the offending street edge as deleted on the test and production servers. Solving our issue for the time being. I have opened a new issue to discuss how to prevent this from happening in the future (#1570)

**Comment by jonfroehlich** [comment]
Nicely done on tracking this down Mikey!

**Comment by misaugstad** [comment]
For anyone coming across this issue again while auditing Newberg on their local environment, run this query:

```
UPDATE street_edge SET deleted = TRUE WHERE street_edge_id IN (
    1074,1070,1532,756,25,1146,
    1071,774,763,1134,1528,473,748,278,758,24,262,762,1190,187,1367,764,769,1147,1149,746,472,1189,
    1145,757,773,1159,749,772,310,1369,745,765,1073,815,89,288,1150,1531,770,1148,775,759,279,755,
    170,195,744,309,1067,750,1072,761,1132,393,502,90,1068,22,743,760,747,771,88,615,416,1160,45,
    44,1204,276,1231,26,969,674,595,579,1414,1045,1118,556,1372,1491,1022,546,456,605,378,1032,1163,
    311,766,36,814,562,425,1257,597,776,1689,1245,188,601,20,1069,1162,555,1033,1437,1014,72,46,
    83,1246,261,1203,1626,164,55,1368,1529,1133,1422,669,194,735,1247,248,501,698,1520,1168,1161,308
);
```

And that should solve your problems :+1:
