### ISSUE TITLE
Spacebar No Longer Works in Description Textbox

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#157]
This is a new bug (I've never seen it before). I can no longer put in a space character in the description textbox when labeling a problem. See below:

![image](https://cloud.githubusercontent.com/assets/1621749/16668227/28c9881e-445e-11e6-844d-b9556be431be.png)

**Comment by danZzyy** [comment]
this is probably because I disabled space and the arrow keys when implementing arrow key moving and rotating. I wanted to prevent scrolling and didnt realize this would happen

**Comment by kotarohara** [comment]
No worries. I fixed it.
