### ISSUE TITLE
Newberg: Audit path/map shows street which does not exist in GSV

### ISSUE THREAD

**Issue by galenweld** [ProjectSidewalk/SidewalkWebpage#1575]
I started a new audit session via the "Start Exploring" button in the navbar and was dropped into an intersection. The minimap told me to proceed straight, but the GSV imagery depicted a fence and field instead of a road.
<img width="1050" alt="Screen Shot 2019-03-19 at 16 37 47" src="https://user-images.githubusercontent.com/358858/54649154-53873400-4a66-11e9-9ffd-f0c64119c629.png">

Exploring [the location](https://www.google.com/maps/@45.3220383,-122.9811365,3a,60y,95.57h,76.99t/data=!3m6!1e1!3m4!1sAg9qAbxPprduQ9-wnawqFg!2e0!7i13312!8i6656) on Google Maps, the area has been recently redeveloped. The satellite imagery is up-to-date but even the lastest GSV imagery on maps.google.com is out of date

**Comment by jonfroehlich** [comment]
Thanks Galen. Project Sidewalk serves the most recent GSV data available. Sometimes there’s differences between Google Street view and the current map data. 

Again, the appropriate action to take is to click on the jump button and select I cannot go where you want me to go

**Comment by misaugstad** [comment]
Thanks for logging this @galenweld 

Not much we can do about this. I went through all the streets where people jumped for that reason and made sure to mark as deleted any that might have caused out infinite refresh bug (#1563). Nothing left to do so I'm closing this now.

**Comment by jonfroehlich** [comment]
Maybe keep this open and rename Issue thread to something about how we can better inform users about jumping. I fear that a typical user would run into this problem, get frustrated, and drop out.
