### ISSUE TITLE
Google Analytics for Newberg, Seattle, Future Cities

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1576]
How should we handle Google Analytics for Newberg, Seattle, and future cities. Is it currently hooked up?

I just quickly looked and the settings appear to point to sidewalk.umiacs.umd.edu:

![image](https://user-images.githubusercontent.com/1621749/54702349-ecb05c00-4af3-11e9-8ff2-dbef39db4370.png)

![image](https://user-images.githubusercontent.com/1621749/54702379-f8038780-4af3-11e9-9c36-7ba8f231219e.png)

**Comment by manaswis** [comment]
We should have different IDs for the different cities. I had briefly mentioned this in one of the issues (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1559#issuecomment-473111657)

**Comment by misaugstad** [comment]
I don't know what that "default URL" param means, but it seems that all the traffic to any Project Sidewalk page contributes to these numbers, possibly including access to the website in a local dev environment... Proof of that is the 247 pageviews of the /mobileValidate endpoint.

**Comment by misaugstad** [comment]
I am creating separate tracking IDs for the different cities, and will add them to the `conf/cityparams.conf` file.

**Comment by misaugstad** [comment]
closing via #1583
