### ISSUE TITLE
Backend Request: Search by tag, label type, etc.

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1577]
We now have a label search on the backend (woohoo, thanks @aileenzeng, I believe). 

![image](https://user-images.githubusercontent.com/1621749/54702886-fc7c7000-4af4-11e9-8093-f6c9baf85ad2.png)

However, this only lets you search by label id. For talks, etc., I'd really like to search by label type, severity, and tag. For example, show me all obstacles in path tagged with vegetation. So I can find things like this (see figure) when I'm making talks or meeting with people about our project:

![image](https://user-images.githubusercontent.com/1621749/54702946-1ae26b80-4af5-11e9-929b-f71a6476ebab.png)

**Comment by jonfroehlich** [comment]
Interesting, you can sort of get this desired search behavior from this part of the admin webpage:

![image](https://user-images.githubusercontent.com/1621749/54823062-e8a34c00-4c63-11e9-937b-7ed04c4776e2.png)

**Comment by misaugstad** [comment]
Ahh yes, forgot to think about how the search feature on that table would also search through the tags!

**Comment by jonfroehlich** [comment]
This part of the admin tool is actually quite amazing. Used it to quickly build this image:

https://twitter.com/projsidewalk/status/1109074838277115904?s=21

Does the search work across all data or just that which is loaded on the client? If the latter, what’s downloaded onto the client in the admin table?

**Comment by misaugstad** [comment]
Just waht is loaded on the client. And in the admin table is just all the metadata that you can see there, for the most recent 1,000 labels.

**Comment by jonfroehlich** [comment]
Got it. Most recent 1,000 labels. Thanks.
