### ISSUE TITLE
Should 'parked car' be a tag type for 'Obstacles in path'?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1578]
In Newberg, it's quite common to find cars parked in their driveway that also impede the sidewalk. The following figure is a more innocuous example:

![image](https://user-images.githubusercontent.com/1621749/54704026-33538580-4af7-11e9-9f90-c07438116708.png)

**Comment by misaugstad** [comment]
If you click the new "parked car" tag, should we automatically mark it as temporary? :sunglasses: In fact, should we do that for "trash/recycling can" as well??

**Comment by jonfroehlich** [comment]
So, we have discussed this before on another github issue. My feeling is that it doesn't really matter if we have the tag--because the tag is semantic, we can decide post hoc whether that tag category is temporary or not. In DC, I would often mark parked cars as temporary obstacles; however, I have the feeling that it's actually a rather systemic problem in Newberg and that it likely occurs quite frequently. Same with the trash/recycling cans. Even if it is temporary (e.g., one day a week, that's still 15% of the days).

**Comment by misaugstad** [comment]
but yeah i agree with the parked car tag. I've seen those quite a bit recently.

**Comment by misaugstad** [comment]
closing via #1580
