### ISSUE TITLE
Make jumping/stuck feature more noticeable

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1579]
It is common for users to not know/remember that they can use the Jump button (see #1575). We tell them about it in the tutorial, but after a user is auditing for a bit, it is probably easy to forget about the Jump button. Also people don't read instructions :)

I think we could solve this pretty easily by changing the name of the button. Instead of "Jump" why not have the button say "Stuck?". I think if someone is stuck somewhere and are looking around the interface for a way to deal with it, this would be a useful change.

I think we could knock out 2 birds with one stone here: users also do not know/remember that they can double click if there are no arrows in the direction they are trying to go. When they click the "Stuck?" button, we could suggest double-clicking in the direction they want to go. And if that doesn't work they would be able to jump as usual.

Thoughts on this as a solution?

**Comment by jonfroehlich** [comment]
Is there something we could do in the main navigation areas (red highlights below). For example, in the heads-up directions, could we have something like 'Stuck? Click here to jump." Perhaps we could also have one of those yellow pop-up messages come up if someone returns to a location for a 2nd or 3rd time, or, perhaps stays in a location for a certain amount of time... not sure. I'm not sure those buttons on the left side of the interface area really ever attended to...

![image](https://user-images.githubusercontent.com/1621749/54756528-a9162a80-4ba5-11e9-8803-82e35c4a721e.png)

**Comment by misaugstad** [comment]
I think that that's the best look! We've added a "stuck" button that will move you forward along your route, but as you said, buttons on the left side menu might not always be at the front of one's mind. I agree that if someone ends up in the same pano 2 or 3 times, we should have one of those alerts suggesting that they use the "stuck" button!

**Comment by jonfroehlich** [comment]
Just ran into this again and came up with almost the same solution. Ha!

![image](https://user-images.githubusercontent.com/1621749/155007501-35ef3088-c507-4bf4-b9a6-16d3bdee9beb.png)

I'm really struggling to move around in Amsterdam, particularly in Nieuwe Kerk e.o., https://sidewalk-amsterdam-test.cs.washington.edu/dashboard/?regionId=8
