### ISSUE TITLE
Validation bug: validation completion screen says I validated 10 labels but I didn't

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1584]
I'm not sure what happened here (perhaps I ran out of 'surface labels' to validate?) but I only validated 6 surface labels and then the mission completion screen popped up and told me that I validated 10 (and yet, the categorical count is correct).

![image](https://user-images.githubusercontent.com/1621749/54784099-41310580-4be0-11e9-89b4-25aaa2a3a3ca.png)

**Comment by aileenzeng** [comment]
I’m guessing this might be because you had a surface problem mission that was in progress (so you only had 6 labels remaining to finish this mission). 

The UI definitely isn’t clear about that though, so I’ll work on improving it!

**Comment by jonfroehlich** [comment]
I don’t think so... but I’m not really sure what you mean. I was just doing lots of validation missions. This was maybe my 5th one in a row.

**Comment by misaugstad** [comment]
You should only be getting a mission if there are at least 10 surface problems to validate, so it seems like the mission ended prematurely...
