### ISSUE TITLE
Just Signed In and Mission Bar Wrong

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#159]
I just signed in as myself and was dropped into 'Mount Vernon Square, D.C.'; however, a few things are wrong. Full screenshot at end of post. I also included cropped parts of the interface to help highlight individual points.

![image](https://cloud.githubusercontent.com/assets/1621749/16668654/ea2f274c-445f-11e6-9fdc-e3315fa451c2.png)
First, while the label count for this neighborhood shows 195 (I think it should actually be higher, honestly), the mile walked is wrong. It shows 0.0 miles. Shouldn't this interface show you how much you've walked and labeled in the current neighborhood?

![image](https://cloud.githubusercontent.com/assets/1621749/16668748/3d752852-4460-11e6-932d-cfd8546bf5d3.png)
Second, though I have yet to take a step, the mission bar says 14%. How could I be 14% done with the current mission (which is to audit 2.5 miles), if I've yet to take a step?

Third, I thought we were not going to do missions of this length. 2.5 miles seems like a very long audit task.

![image](https://cloud.githubusercontent.com/assets/1621749/16668640/e052d944-445f-11e6-9af2-bb43ae4e9e26.png)

**Comment by jonfroehlich** [comment]
Towards the second point, I have now taken a few steps and my progress bar has jumped enormously. I'm confused. I thought the progress bar is representing 2.5 miles of work, but I've only taken 3 or 4 steps, how can I now be 23% complete?

![image](https://cloud.githubusercontent.com/assets/1621749/16669509/df2f1ec0-4463-11e6-8a0e-2dbb25015030.png)

The progress bar should correspond to the current mission. If my mission is to audit 2.5 miles, then when I start the mission, the mission bar should be at 0%, when I'm at 1 mile, the mission bar should be at 40%, when I'm at 2 miles, the mission bar should be 80%, etc.

**Comment by jonfroehlich** [comment]
Towards the first point, I just finished the mission and now the miles walked icon for the 'Current Neighborhood' shows 2.63 miles--so it jumped from 0.00 miles to 2.63 miles.

![image](https://cloud.githubusercontent.com/assets/1621749/16670050/6c7dd1b6-4466-11e6-9b8f-b7e127da7c95.png)

**Comment by kotarohara** [comment]
**First point:** It should show the distance audited so far in the neighborhood. I guess it's not getting updated when you log in... Not sure why. I'll look into it.
**Second point:** It's cumulative distance. I have not updated the message. 
**Third point:** We use shorter missions. They are broken down into 1000ft, 2000ft, 4000ft, 1mi, 1.5mi, 2mi, 2.5mi, and so on. Again, I have not updated the message so it shows the cumulative distance.

**Comment by jonfroehlich** [comment]
For the second and third point, the progress bar could show both the amount completed so far in neighborhood and the amount you're currently completing, similar to the Mission Complete progress bar:

![image](https://cloud.githubusercontent.com/assets/1621749/16673418/f9e8b484-447b-11e6-9d4f-bf1fa09c0f82.png)

Or you could just change the messages, as you suggest.

**Comment by kotarohara** [comment]
**First point:** Fixed.

**Comment by kotarohara** [comment]
Related to #163

**Comment by kotarohara** [comment]
Actually this issue had been addressed. The last issue of the three that were described in this issue (the second point) was fixed before #163 .
