### ISSUE TITLE
Questioning mission length for Seattle deployment (and beyond)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1595]
What are our current mission lengths? 500ft, 1,000ft, ???

I really like keeping mission lengths shorter rather than longer. It makes the user experience feel more alive and interesting and having shorter labeling missions then gives us more opportunities for other types of missions (like validations).

**Comment by misaugstad** [comment]
500 ft, 500 ft, 1000 ft, 1000 ft, then 1/4 mile (1320 ft) for the rest of them. This is very easy to change.

**Comment by jonfroehlich** [comment]
What do you think @misaugstad? I guess the max length (1/4 mile) isn't *that* long. I think we used to have the max length be like 1/2 mile (eek!). Based on our DC deployment, how long does 1/4 mile take?

**Comment by misaugstad** [comment]
The average user would have finished 1/4 miles in 9.5 minutes

**Comment by misaugstad** [comment]
Oh and what do I think? I don't like completing 1/4 mile missions :grin: maybe we could just max out at 1000 ft..?

**Comment by manaswis** [comment]
Yeah I like the idea of maxing out at 1000 ft. Quick short missions.

**Comment by jonfroehlich** [comment]
I also like shorter missions. Maybe we could do:

- 500
- 500
- 750
- 1000

And cap there?

**Comment by misaugstad** [comment]
closing via #1609
