### ISSUE TITLE
The design of the 5 point scale radio button in the context menu

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#16]
I think it would be helpful to have pop-up infotips for each of the these 1 through 5. Perhaps these infotips could be customized for each label type.
![radio](https://cloud.githubusercontent.com/assets/612263/13296729/f1a45f00-dafc-11e5-8dbc-c563ed64965f.png)

**Comment by jonfroehlich** [comment]
This is related to #80.

**Comment by kotarohara** [comment]
This is also related to #15

**Comment by kotarohara** [comment]
Updated the design. Please see #80
