### ISSUE TITLE
Should We Have 'Report Bugs' Link

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#160]
Should we have 'report bugs' link that brings people to this Issues tracker on github?

**Comment by kotarohara** [comment]
Hmmm, probably not. We have comments field which let's people enter bug info. I think I made it so that it keeps some context information like panorama id. Can't do certain things like copy and paste screenshot but no one's going to do that anyway.

**Comment by kotarohara** [comment]
I'm closing it now. Please reopen if you disagree.

**Comment by jonfroehlich** [comment]
V good point. I agree.
