### ISSUE TITLE
Add all recorded GSV parameters to API

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1605]
We have someone asking if we have all the GSV parameters available via the API to recreate exactly what the user saw (similar to our validation interface). We don't have that right now but it would be incredibly easy to add those parameters to our current `/v2/access/attributesWithLabels` endpoint.

@aileenzeng could you list all the parameters that are needed to recreate what the user saw? Then whoever implements this will know what parameters to add.

**Comment by aileenzeng** [comment]
Yep! I think these are all the fields we use:

* `panoId`: Panorama ID where the label was placed
* `heading`: User's heading when label was placed
* `pitch`: User's pitch when label was placed
* `zoom`: User's zoom when label was placed
* `canvasX`: Pixel coordinate (horizontal) of the original label
* `canvasY`: Pixel coordinate (vertical) of the original label
* `canvasWidth`: Width of the original GSV screen
* `canvasHeight`: Height of the original GSV screen

**Comment by misaugstad** [comment]
Ok so the code is now on all of the servers (including the old DC server). Unfortunately clustering is not working on the DC server b/c it is still using the old version of the Dockerfile. We recently updated the Dockerfile for the other servers to include some Python libraries necessary for the clustering.

@mechanicjay is going to be out of town through the 16th, but he said he would be able to update the Dockerfile when he gets back. At that point I can run clustering, and then the API will actually return some data :)

**Comment by misaugstad** [comment]
This is now working on all servers! Closing via #1612
