### ISSUE TITLE
Intro mission pop-up box text shouldn't be center-aligned

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1607]
![image](https://user-images.githubusercontent.com/2873216/55444983-f4e5ae00-556d-11e9-86d5-3515427a09fd.png)

This text should be **left-aligned.**

DC has it right

![image](https://user-images.githubusercontent.com/2873216/55575808-9c74f480-56c4-11e9-8cfe-be4480f05557.png)

**Comment by annieyx** [comment]
I was just wondering where on the website I would be able to find this pop-up? When does it pop up? Thank you!

**Comment by misaugstad** [comment]
Right after you finish the tutorial on the audit page.

**Comment by annieyx** [comment]
So I was able to change the text on the pop-up message to be left-aligned but I then realized that it made other pop-up messages left-aligned. From a design perspective, it makes sense to have all the messages consistent in text-alignment but should I continue on making only the "Let's get started!" messages left-aligned while keeping the others centered?
![image](https://user-images.githubusercontent.com/49461308/57958362-79895300-78b4-11e9-8dc8-9f81fdcf1b61.png)
![image](https://user-images.githubusercontent.com/49461308/57958383-873ed880-78b4-11e9-80ef-677700b4b299.png)
From what I've seen, these two pop-ups and the "make sure to check both sides" are all under the same css.

**Comment by jonfroehlich** [comment]
I would have to see all others (before and after) to make this determination.

**Comment by annieyx** [comment]
Before:
![image](https://user-images.githubusercontent.com/49461308/57960151-1ac7d780-78bc-11e9-8152-58ff579087f7.png)
After: 
![image](https://user-images.githubusercontent.com/49461308/57960180-3f23b400-78bc-11e9-9639-c91ab650fd8a.png)
Before:
![image](https://user-images.githubusercontent.com/49461308/57960283-bc4f2900-78bc-11e9-84e3-f5395bf3fc75.png)
After: 
![image](https://user-images.githubusercontent.com/49461308/57960286-c2dda080-78bc-11e9-906d-72902d2394a7.png)
Before: 
![image](https://user-images.githubusercontent.com/49461308/57960312-d6890700-78bc-11e9-9ba5-73f46af41133.png)
After:
![image](https://user-images.githubusercontent.com/49461308/57960314-dc7ee800-78bc-11e9-88d1-e11d5b6d7081.png)

**Comment by jonfroehlich** [comment]
I actually like the centered designs better in all cases :)

**Comment by misaugstad** [comment]
I don't really have a preference, so if @jonfroehlich thinks they look better center-aligned, we may as well leave them that way :grin: Closing this issue. Thanks for looking into it @annieyx!
