### ISSUE TITLE
Make sure first street selection is random

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1613]
I think that choosing the street to start on in each neighborhood is not actually random right now. This has some negative side-effects. One is that if we don't find GSV imagery, we get that pesky infinite refresh bug (#1563); this should be fixed due to changes we talked about in #1570, but on the off chance it happens, randomly selecting the street would prevent the infinite refresh.

The other negative side-effect is that if users start auditing a street but don't finish, the next time they come to the audit page they will be starting the same street they partially completed last time... But they will be starting from scratch :( Very bad UX.

Once we let users resume a street where they started (#72) this won't matter, but selecting streets randomly is a very fast bandage we should probably use.

**Comment by jonfroehlich** [comment]
Yes, we should definitely be selecting the initial street randomly

**Comment by misaugstad** [comment]
closing via #1615
