### ISSUE TITLE
5 miles is nearly 0% of city

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1614]
Right now on the landing page we are rounding our percent complete to the nearest whole number and then saying "that is nearly x% of the city". Well since we are rounding to the nearest whole number, that is false 50% of the time :laughing: 

It should either say "that is over x% of the city" when we are rounding down, or I guess we could always round up. If we do the former, we should probably also have a special case for 0%... as "over 0% of the city" doesn't sound great :sweat_smile: 

We have a special case for 100% complete: "We did it! Users like you have mapped all X miles of Y"

![nearly-0-percent](https://user-images.githubusercontent.com/6518824/55652272-df57ca80-579f-11e9-9775-f5811ebf471d.png)

**Comment by jonfroehlich** [comment]
Let’s just add a decimal place?

**Comment by misaugstad** [comment]
wow what a solution :open_mouth:

**Comment by misaugstad** [comment]
so wait are you saying to keep the wording "nearly X.X% of the city"? Or remove the word "nearly"?

**Comment by jonfroehlich** [comment]
Remove the word nearly. Add decimal place.

**Comment by misaugstad** [comment]
How does this look? Like the decimals for the miles or no?

![landing-page-with-decimals](https://user-images.githubusercontent.com/6518824/55655594-7a08d700-57a9-11e9-8173-855b74b894b0.png)

**Comment by jonfroehlich** [comment]
Looks great

**Comment by misaugstad** [comment]
closing via #1616
