### ISSUE TITLE
Login issue: Unable to log into any account

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1619]
I created an account a few weeks back and tried to log in but was unable to. I figured my login credentials were wrong. I created another account and was unable to log in after logging out. To test, I created another fake account on the sea-test server and the same thing happened.

![image](https://user-images.githubusercontent.com/2873216/55663337-a46e8a80-57d1-11e9-9e0e-f7b5627feca9.png)

Could others verify this?

**Comment by aileenzeng** [comment]
Hmm I was able to just log in!

**Comment by manaswis** [comment]
I get this error in the console:

![image](https://user-images.githubusercontent.com/2873216/55676043-6fba0c00-5881-11e9-9501-126d05da8e65.png)

Try creating a fake account, log out, and then log in. See if it works.

**Comment by misaugstad** [comment]
@manaswis it worked fine for me

based on the image you posted it looks like you are trying to sign in with your username instead of you email address..? Idk if that was just from your screenshot or if you were correctly using your email address other times though

**Comment by manaswis** [comment]
Ah!! Good catch @misaugstad! That solved it! lol silly me :D

**Comment by misaugstad** [comment]
Ahh thank goodness! You had me like "oh no!! :fire: :fire: :fire_engine: :fire_engine:" glad ppl can still log in :relieved:

**Comment by manaswis** [comment]
Sorry for the scare! oops!
