### ISSUE TITLE
User is not defined

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1621]
![image](https://user-images.githubusercontent.com/25534091/55672320-8e52df80-584e-11e9-89e2-9e5ab5c49907.png)

![image](https://user-images.githubusercontent.com/25534091/55672326-990d7480-584e-11e9-8a26-c8a1eddd0501.png)

I got this bug on my dev environment. I checked out the `develop` branch, pulled the most recent page, and then visited the `/validate` endpoint. I was also already signed in when I had pulled. I haven't figured out a way to reproduce it though.

**Comment by misaugstad** [comment]
@aileenzeng my best guess is that grunt hadn't finished rebuilding the SVValidate.js file..? In the recent changes to develop a new User.js file was added. So if it hadn't recreated the build file before you loaded the page, then this is the error I would expect. Do you think that is possible? Or had grunt definitely finished running?

**Comment by aileenzeng** [comment]
Hmm, that sounds very likely. I thought I had hard refreshed my page a few times and that `grunt` was running, but I think that `grunt` also sometimes acts a little wonky every now and then. I haven't been able to recreate it since, so perhaps this is a non-issue!

**Comment by misaugstad** [comment]
That seems the most likely culprit, but if anyone ever sees this again, we will reopen!
