### ISSUE TITLE
Disable keyboard shortcuts when mission screens are displayed

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1627]
You can still validate labels by using keyboard shortcuts when mission screens are up (example below). We should be disabling keyboard shortcuts when these are being displayed. (NOTE: we already have functionality for disabling keyboard shortcuts in `Keyboard.js`, we're just not actually putting it to any use 😁 )

![image](https://user-images.githubusercontent.com/25534091/55765520-0a068500-5a25-11e9-8be5-a4faec4fbe02.png)

**Comment by misaugstad** [comment]
yikes!

**Comment by misaugstad** [comment]
closing via #1631
