### ISSUE TITLE
Change mission text when a user comes back and the last saved mission is resumed

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#163]
[UPDATE (Sep 19)]: The new issue title corresponds to the [comment](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/163#issuecomment-244490905) below.

---

Original Issue Text:

I think this mission screen should be redesigned:

![image](https://cloud.githubusercontent.com/assets/1621749/16669247/72bfd3a2-4462-11e6-8225-4a1555715347.png)

At a minimum, I think we should change:
- The title: "Mission: Make... X mi of this neighborhood accessible.' The use of the word 'Make' here feels wrong since users are not actually fixing problems, they are just finding problems. I also think it would be better to use the actual neighborhood name here rather than neighborhood.
- A simple suggestion. Put Mission on it's own line. Underneath, have the sub-title "Walk X mi of <neighborhood name> and label accessibility attributes'

Ideally, we would do a more massive redesign that would completely change the look-and-feel of this interface to include a map of the current audit neighborhood and, if possible, an overview of the audit route.

**Comment by kotarohara** [comment]
- "Make... Xmi". I agree using the name of the neighborhood. I think "make" is fine, but am open to change. Do you have suggestions? Btw, again, this is cumulative distance. So it should say "Audit 1/2mi to make 2.5mi accessible" or something.
- I agree. Or rather we could get rid of "Mission:" all together.

I don't think this is a high priority though.

**Comment by jonfroehlich** [comment]
I agree that it's not a high priority. I'd want to see a mock before we really do anything too drastic.

The mission text should be updated to more accurately reflect the actual current mission, however.

**Comment by kotarohara** [comment]
Updated. Screen shot on #125

**Comment by kotarohara** [comment]
I'm moving the comment from #195 to here.

> So, I think the actual fix here for this particular thing is that the Mission Dialog when you first login and return to the mission should be different than the initial Mission Dialog--that is, the Mission Dialog should say something like "Welcome back! You have XXX feet to go to complete this mission" or something. This is also related to #163.

**Comment by misaugstad** [comment]
closing via #1370
