### ISSUE TITLE
New city links on landing pages turn blue when visited making them hard to see

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1634]
I really like @manaswi's simple but effective idea of putting links to other cities on our landing pages (though not a scalable solution, however).

![image](https://user-images.githubusercontent.com/1621749/55881968-8483f180-5b58-11e9-91eb-fcb72efa586c.png)

However, once you visit one of those links, they turn blue--which is hard to see with our changing background. So, maybe keep them yellow even if visited for now? Obviously, we also have to work on a longer-term solution.
![image](https://user-images.githubusercontent.com/1621749/55881955-7f26a700-5b58-11e9-8433-2764b942b4ba.png)

**Comment by misaugstad** [comment]
closing via #1717
