### ISSUE TITLE
Are we supposed to label surface problems, obstructions, etc. in the crosswalk?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1637]
Are we supposed to label surface problems, obstructions, etc. in the crosswalk (or if no crosswalk is painted--at least in the pedestrian pathway that connects two curb ramps)? If so, we need to add this to the labeling guide. 

I think we should. :)

**Comment by misaugstad** [comment]
Yes we should be labeling things in the crosswalk. This is mentioned in the surface problems section of the labeling guide (https://sidewalk-newberg.cs.washington.edu/labelingGuide/surfaceProblems#problems-in-a-crosswalk)

It is also indirectly mentioned in the introductory paragraph of the Obstacle section:
"Obstacles are objects that are directly on the path of a pedestrian route, thus blocking the path. The ADA (Americans with Disabilities Act) requires a "clear floor or ground space" along accessible pedestrian routes (ADA 305). This allows pedestrians, especially those using walkers or wheelchairs, to remain safely on the sidewalk or crosswalk. Moving off the path to avoid an obstacle may be impossible or may cause imbalance, tripping, or other hazards."

We can think of how to make this more clear, however.

**Comment by misaugstad** [comment]
closing via #1741
