### ISSUE TITLE
More per-user validation stats in dashboard

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1646]
In addition to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1430, I think we should add validation stats to the Users table (or maybe a new table?).

![image](https://user-images.githubusercontent.com/1621749/56244014-bad9d900-6050-11e9-9e96-4239c710348b.png)

I'd like to add the following columns:
* Num labels placed by other users and validated by this user: the raw number of labels validated (similar to label count) by this user
* Num labels placed by this user and validated by others: the number of labels that this user placed that have been validated by others (let's call this Nvalidated).
* % agreement: the number of labels placed by this user that were validated as "Agree" divided by Nvalidated
* % disagreement: the number of labels placed by this user that were validated as "Disagree" divided by Nvalidated
* % not sure: the number of labels placed by this user that were validated as "Not sure" divided by Nvalidated

**Comment by andrew4699** [comment]
![Screenshot from 2019-04-23 19-46-14](https://user-images.githubusercontent.com/7133966/56628926-8cd03800-6600-11e9-8747-a1f616623830.png)

**Comment by misaugstad** [comment]
looks good to me!

**Comment by misaugstad** [comment]
well actually, could you also add a "% agree w/ others' labels" (feel free to pick a better name). I just want to know how often they are clicking the "agree" button when validating.

**Comment by andrew4699** [comment]
![Screenshot from 2019-04-24 18-47-00](https://user-images.githubusercontent.com/7133966/56704280-5d353480-66c1-11e9-8f70-f481db5ba78f.png)

How's that? The name of the field isn't exactly attractive, but we don't have any restrictions on vertical space in that table since it wraps nicely.

**Comment by misaugstad** [comment]
Looks good enough to me, thanks!

**Comment by misaugstad** [comment]
closing via #1685
