### ISSUE TITLE
Can't Use Arrow Keys When Writing Description

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#165]
I can't use arrow keys when writing a description (e.g., to move the cursor position with keyboard). Instead, the cursor keys control panning. Can we check to see if the description textbox is in focus to fix this?

![image](https://cloud.githubusercontent.com/assets/1621749/16669737/16e2a174-4465-11e6-997e-51e69bcd16f7.png)

**Comment by kotarohara** [comment]
I fixed it when I was fixing #157
