### ISSUE TITLE
How is Today/Yesterday calculated

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1653]
How is Today/Yesterday calculated? It doesn't seem to be in the admin user's local time (e.g., Pacific time for us):

![image](https://user-images.githubusercontent.com/1621749/56334406-fce84500-614c-11e9-9f2e-2caef2ed7a1a.png)

**Comment by misaugstad** [comment]
Yeah it is probably in UTC. Hopefully not difficult to fix in the queries.

**Comment by misaugstad** [comment]
Okay actually doing this sounds a lot more complicated than it would be worth doing right now. BUT I think an easier solution would be to just convert to PST. We are going to be looking at the admin page using PST almost all of the time, so it might just be easiest to use PST in this query? Much less work than switching to the client's time zone :)

**Comment by misaugstad** [comment]
closing via #2019
