### ISSUE TITLE
Out of labels to validate screen broken

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1656]
When you run out of labels to validate, it seems that the screen there is somehow broken. See image below:

![out-of-labels](https://user-images.githubusercontent.com/6518824/56395207-869c1f00-61ee-11e9-97af-3fdcdc9209d3.png)

```
Uncaught TypeError: svv.disableKeyboard is not a function
    at ModalNoNewMission.show (SVValidate.js:1315)
    at new Main (SVValidate.js:2676)
    at validate:449
```

**Comment by misaugstad** [comment]
@timvng while you wait for me to review your recent PR, how would you like to take on this issue? It used to show up a screen saying you are out of labels to validate!

**Comment by timvng** [comment]
It's a very minor fix. Should I still make a PR for it?

**Comment by misaugstad** [comment]
Yes please!

**Comment by misaugstad** [comment]
closing via #1754
