### ISSUE TITLE
Miles Audited In This Mission and Neighborhood Miles Audited So Far

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#166]
The two metrics "Miles audited this mission" and "Neighborhood miles audited so far" should not both be 2.5 miles here, but they are... Something is wrong. The "Neighborhood miles audited so far" number should be much higher.

![image](https://cloud.githubusercontent.com/assets/1621749/16669873/99a61154-4465-11e6-91af-5c0d1d41f61a.png)

**Comment by kotarohara** [comment]
Good point. @danZzyy is working on the redesign of this modal window, so he can look into it.

**Comment by kotarohara** [comment]
This will happen in next few days; hopefully by the end of tomorrow.

**Comment by jonfroehlich** [comment]
Note: this is still broken.

![image](https://cloud.githubusercontent.com/assets/1621749/16713816/e8dd77c2-4680-11e6-8e11-b9d5ccb38e8b.png)

**Comment by jonfroehlich** [comment]
@danZzyy @kotarohara, any updates on this. I checked tonight and it appears still broken.

**Comment by danZzyy** [comment]
Sorry, I hadnt encountered this issue. Since my dev db has a lot less audit information I am usually placed in a neighborhood that did not have previously completed missions.
