### ISSUE TITLE
Add Pano ID to Ground Truth Audit Tool

### ISSUE THREAD

**Issue by galenweld** [ProjectSidewalk/SidewalkWebpage#1660]
Hi all,
Esther and I have been using the great ground truth labeling tool that @tongning developed. See #1625 for details. After discussing with @jonfroehlich we have one small feature request, if it's not difficult.

Would it be possible to display the Pnao ID somewhere in the browser window, so we can jot down any panos that potentially need further discussing?

Thanks

**Comment by tongning** [comment]
Yeah this should be an easy addition. If you need to do this urgently, you can open a console window and type `svl.panorama.getPano()` to get the current panoId.

**Comment by jonfroehlich** [comment]
In the short term, go to the regular GitHub repo for Sidewalk and search for the word ‘crazy’ in closed Issues. You’ll see the command to write in the console to determine the pano

**Comment by jonfroehlich** [comment]
Oops. What Anthony said! :)

**Comment by misaugstad** [comment]
closing via #1663
