### ISSUE TITLE
I can walk using arrow keys in validation

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1662]
We aren't supposed to be able to do that, are we?

**Comment by jonfroehlich** [comment]
I don’t think so... thoughts?

**Comment by aileenzeng** [comment]
Nope! Definitely a bug.

**Comment by jonfroehlich** [comment]
In some cases, it would be helpful to be able to walk during validation to see a label from a different perspective. But this also complicates the interface (and the cost of this outweighs the benefit I think). So, yah, let’s just fix this. :)

**Comment by aileenzeng** [comment]
There is a feature that would allow us to do this (in the admin interface, we allow users to walk around), and that would be pretty simple to implement. I guess the main downside is that we wouldn't be able to keep the label onto different panoramas.

**Comment by misaugstad** [comment]
I agree with @jonfroehlich that the cost outweighs the benefit here; we want validation to be rapid.

**Comment by htadeusiak** [comment]
I just wanted to give a quick update on this issue.

In Google Maps, the best way to disable arrow key presses from moving the position is to set ```disableDefaultUI: true```. However, I believe that this is only possible for the Maps class and not the StreetViewPanorama class. 
https://developers.google.com/maps/documentation/javascript/streetview

I tried several other ways to disable the user from moving their position in validation with no success.

I tried catching the keypresses to prevent further methods from being called by using ```e.preventDefault();```, ```return false;```, and ```e.stopPropagation();```. I tried both google and DOM event listeners (I want to look into this more as I feel like this would be the best way to prevent the user from moving).

I tried setting a restriction on the bounds of lat and lng to stop the user from moving outside the "bounds". Once again I believe 'restriction' can only be used for the Maps class. Here is a reference:
https://developers.google.com/maps/documentation/javascript/examples/control-bounds-restriction

Here are two temporary fixes: 
(1) If the user changes their position, it will take them immediately back to the correct spot. Here is an example. I know you can't tell but I press the up arrow and it takes me back, then I press the down arrow and it takes me back again. I know the label does not disappear, 
![test](https://user-images.githubusercontent.com/33988444/58767301-1fd48a00-853e-11e9-9ead-3d6907426c3d.gif)

(2) If they user leaves the correct spot, I can prompt them with a new button that saids "Take me back" and it will return them to the original label. Here is an example:
https://developers.google.com/maps/documentation/javascript/examples/control-custom

I'm not really satisfied with either of these fixes so I'm going to keep working on it. I'm also inexperienced with Google Maps API, so if I said anything that is incorrect or if you know a better way to do something, please let me know.

**Comment by misaugstad** [comment]
hmm well I think on the audit page you are only able to move once every second or so, and I think that is something we implemented ourselves. so maybe see what that code is doing to prevent us from walking for 1 second at a time?

**Comment by misaugstad** [comment]
But you forcing the user back to the original pano is a good workaround. I just really feel like it shouldn't be necessary, but it looks okay if it needs to happen!

**Comment by htadeusiak** [comment]
```/*
       Move user in specific angle relative to current view for a specific moveTime.
     */
    function timedMove(angle, moveTime){
        if (status.moving || svl.isOnboarding() || svl.popUpMessage.getStatus("isVisible")){
            svl.panorama.set("linksControl", false);
            return;
        }
        svl.contextMenu.hide();
        svl.ui.canvas.deleteIconHolder.css("visibility", "hidden");
        self._movePano(angle);
        //prevent user input of walking commands
        svl.map.timeoutWalking();
        //restore user ability to walk after param moveTime
        setTimeout(svl.map.resetWalking, moveTime);
        //additional check to hide arrows after the fact
        //pop-up may become visible during timeout period
        if (svl.popUpMessage.getStatus('isVisible')){
            svl.panorama.set('linksControl', false);//disable arrows
        }
    }
```
Is this the code you were talking about @misaugstad ?
If so it only makes the visible arrows disappear and does nothing to stop clicking the arrow key. The way to do that would be setting "keyboardShortcuts" equal to false. However, once again that only works for maps and not street view.

I'm down to maybe let someone else take a stab at this. From what I know I think our best options are listed above.

Maybe if someone figured out how to catch the key press before the API, that would be better.

**Comment by misaugstad** [comment]
>Is this the code you were talking about @misaugstad ?
>If so I think it only makes the visible arrows disappear and does nothing to stop clicking the arrow key. The way to do that would be setting "keyboardShortcuts" equal to false. However, once again that only works for maps and not street view.

Yeah I think so, and I think you are right.

>I'm down to maybe let someone else take a stab at this. From what I know I think our best options are listed above.

I think it is best for you to implement the thing where it puts the user back to the pano they are supposed to be at immediately.

**Comment by misaugstad** [comment]
closing via #1859
