### ISSUE TITLE
Hide label should not be dark gray (that's reserved for disabled)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1665]
I don't think that the hide label should be dark gray. Once you click on 'Hide', it switches to 'Show' and is drawn in dark gray, which makes it seem like the button is no longer clickable. Just keep the label the regular color.

![image](https://user-images.githubusercontent.com/1621749/56476798-358c6500-6452-11e9-8a78-5be614ca0832.png)

**Comment by htadeusiak** [comment]
Do we want to remove the darken grey or just make it match the grey when we hover over the button.

<img width="770" alt="Screen Shot 2019-04-30 at 10 07 18 AM" src="https://user-images.githubusercontent.com/33988444/56979902-c4bf0a00-6b2f-11e9-806e-9684c745470f.png">
<img width="786" alt="Screen Shot 2019-04-30 at 10 06 54 AM" src="https://user-images.githubusercontent.com/33988444/56979905-c5f03700-6b2f-11e9-9d9e-b271cb975716.png">

**Comment by misaugstad** [comment]
Remove all gray

**Comment by jonfroehlich** [comment]
It should function and look like all other buttons but just toggle state between two.

**Comment by misaugstad** [comment]
closing via #1700
