### ISSUE TITLE
Add num validations to landing page?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1666]
Should be an easy thing to implement if we decide we want to do so. Simply add "# validations" similar to "# miles covered" and "# labels." I would add four columns of stats (rather than the current three) with "# validations" in the forth column. The benefit is that it gives users a greater sense of what people are doing with Project Sidewalk (and that validations are even possible!).

![image](https://user-images.githubusercontent.com/1621749/56477250-4d66e780-6458-11e9-808c-fda582286870.png)

**Comment by misaugstad** [comment]
I like it!

**Comment by htadeusiak** [comment]
Thoughts? Do you want me to make it disappear earlier before the text gets cut off? Is font size ok?
Before:
15in full screen:
<img width="1440" alt="Screen Shot 2019-05-07 at 8 59 46 PM" src="https://user-images.githubusercontent.com/33988444/57348633-ac408800-710b-11e9-9345-fff765645422.png">
Smallest width before text disappears:
<img width="777" alt="Screen Shot 2019-05-07 at 9 03 07 PM" src="https://user-images.githubusercontent.com/33988444/57348630-a9de2e00-710b-11e9-95b4-324b9cc8d43f.png">

After:
15in full screen:
<img width="1440" alt="Screen Shot 2019-05-07 at 8 57 17 PM" src="https://user-images.githubusercontent.com/33988444/57348429-db0a2e80-710a-11e9-9a76-67acdd1be3ed.png">
Smallest width before text disappears:
<img width="769" alt="Screen Shot 2019-05-07 at 9 03 27 PM" src="https://user-images.githubusercontent.com/33988444/57348639-b06ca580-710b-11e9-82f0-826f0675e1fd.png">

**Comment by misaugstad** [comment]
closing via #1720
