### ISSUE TITLE
Admin Interface: Activities Today and Yesterday Columns Not Showing Data

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#167]
Admin Interface: Activities Today and Yesterday Columns Not Showing Data

![image](https://cloud.githubusercontent.com/assets/1621749/16670419/2682f4e6-4468-11e6-9ca7-6f5cc87857f4.png)

**Comment by kotarohara** [comment]
I have not implemented this feature yet. I'll bump up the priority to medium.

**Comment by kotarohara** [comment]
Actually not sure if this is medium priority. I'll work on it when I get a chance.

**Comment by jonfroehlich** [comment]
I agree that it's a low priority and that @danZzyy should be able to do this. :)

**Comment by jonfroehlich** [comment]
I think this is probably a good start task for @manaswis.

**Comment by manaswis** [comment]
I have pushed code. Here is the pull request: https://github.com/ProjectSidewalk/SidewalkWebpage/pull/273

**Comment by manaswis** [comment]
This has been pushed to production. Shall we close this?

**Comment by jonfroehlich** [comment]
If you're sure the code works. :)

**Comment by manaswis** [comment]
This seems to be working. Closing it :)
