### ISSUE TITLE
I've left comments in the validation missions but they're not showing up

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1672]
I've left comments in the validation missions (via the Feedback button) but they don't appear to show up on the admin side. So, the key question is: are we saving this feedback correctly or is this just an admin bug?

![image](https://user-images.githubusercontent.com/1621749/56535793-67183580-6511-11e9-97fc-cc2b85ff9e53.png)

**Comment by misaugstad** [comment]
I just checked the database and they are there. It is just missing from the admin dashboard.

**Comment by misaugstad** [comment]
This issue is just that they are stored in a different table and we haven't written the code to grab the validation missions yet.

**Comment by jonfroehlich** [comment]
Whew, ok. Should be easy to fix this then :)

**Comment by jonfroehlich** [comment]
We should fix this in case users are observing bugs and telling us about them via this interface. It should be pretty straightforward...

**Comment by misaugstad** [comment]
Agreed, will assign someone  to this or do it myself this week.

**Comment by misaugstad** [comment]
closing via #1715
