### ISSUE TITLE
Validation: when I hit 'Disagree', I occasionally want to tell you why

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1679]
When users 'Disagree', it would be useful to know why. For example, I just marked a 'Surface Problem' as a 'Disagree' because it was clearly an 'Obstacle in Path.' This is a substantially different response imo than a 'Disagree' for a label that is completely incorrectly placed. 

So, how can we capture this? For example, perhaps after you hit 'Disagree', the UI fluidly asks you for more information via a closed-form response with an 'Other' option?

For example, in the following picture, I would have selected 'Obstacle in Path' rather than 'Surface Problem.'

![image](https://user-images.githubusercontent.com/1621749/56660825-33debf00-6655-11e9-9821-f1b2e32e847d.png)

**Comment by misaugstad** [comment]
I also sometimes want to give a reason (similar to your rationale). And I suppose this wouldn't slow down someone who is validating _too_ much...

**Comment by jonfroehlich** [comment]
Especially if we keep it optional...

**Comment by misaugstad** [comment]
Ugh, even then I don't want to make disagreeing 2 clicks instead of 1.

**Comment by jonfroehlich** [comment]
See https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1729#issuecomment-507883699

**Comment by jonfroehlich** [comment]
I've just been doing this in the Feedback comment field. You can see that others have been too.

![image](https://user-images.githubusercontent.com/1621749/60973815-cd754e80-a2dd-11e9-833b-3f94b85473e3.png)

**Comment by jonfroehlich** [comment]
This is now addressed because we added an open text field at the bottom: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2100
