### ISSUE TITLE
Admin Interface: Last Login Blank For Many Users

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#169]
For some reason, the last login entry for many users on the admin interface is blank. Is this because we did not track logins previously? If not, it looks like this is fixed now, right? That is, we do record individual logins in the database.

![image](https://cloud.githubusercontent.com/assets/1621749/16670540/b2ec4504-4468-11e6-9e37-d548b15e0e6b.png)

**Comment by kotarohara** [comment]
This happens when a user Sign Up once and never Log In in again (because Log In is not recorded when they Sign Up). I update the code so when a user Sign Up it also records Log In.

**Comment by jonfroehlich** [comment]
Great. Thanks.
