### ISSUE TITLE
Labeling question on Surface problem

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1690]
How would you mark surface problem for bricked streets covering an entire pano:

![image](https://user-images.githubusercontent.com/2873216/56776160-78ff1000-677f-11e9-96bd-29965d6054a7.png)

![image](https://user-images.githubusercontent.com/2873216/56776181-9e8c1980-677f-11e9-8cfd-15df04c3c9a2.png)

![image](https://user-images.githubusercontent.com/2873216/56776185-a8158180-677f-11e9-829b-04049d5f9ae8.png)

```
svl.panorama.getPano()
"CAoSLEFGMVFpcE5HLUtzZkh6VUd2SW9TOWZaWUdSV3h4dndNa1NBcEZZWGZiVmRG"

(svl.taskContainer.getCurrentTask()).getStreetEdgeId()
3355
```

This is Pike Place market main entrance - the entire pano is covered with bricked street. How many surface issues would you apply? This is the same issue as No Sidewalk but much more localized.

**Comment by misaugstad** [comment]
Same way as with NoSidewalk. I do once every pano or so so you make a line of them. I will check later if this is in the labeling guide somewhere b/c it should be. It is for NoSidewalk but idk if it is added for surface problems.

**Comment by manaswis** [comment]
Yes for No Sidewalk one per pano makes sense. However, this one is all over one pano. So would you only have one surface problem label? That doesn't seem right.

**Comment by manaswis** [comment]
Also, looks like this pano is a user-contributed pano and thus, you can't take a step (yikes!)

![image](https://user-images.githubusercontent.com/2873216/56776588-11968f80-6782-11e9-8e32-334588df1822.png)

**Comment by manaswis** [comment]
Screen recording: https://www.dropbox.com/s/52fgzaorop1a6nf/CantWalkPano_PikePlaceMarket.mov?dl=0

**Comment by misaugstad** [comment]
I wouldnt just do 1, I would do whatever was needed to create a line of surface problems on the mini map. 

Although there is brick everywhere here, we really only need to mark surface problems on pedestrian patbs. So I imagine I would mark on each corner and also once in the middle of each crosswalk area (so I guess 8 in total?)

**Comment by misaugstad** [comment]
closing via #1741
