### ISSUE TITLE
Show positive and negative examples of problem type on mission start screens

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1695]
When validating, I'm still seeing the same sorts of labeler confusion that we saw in our CHI'19 deployment (e.g., labeling a driveway as a curb ramp, labeling an obstacle that is not actually on the sidewalk). Perhaps we could have some positive and negative examples on the validation mission start screen. Since these missions are organized around a single label type, the mission start screen could focus on positive/negative examples for that label type.

![image](https://user-images.githubusercontent.com/1621749/56912986-67f71d00-6a65-11e9-8711-be01fd3b819d.png)

**Comment by misaugstad** [comment]
Closing this issue in favor of a new one with more info and mocks #2152
