### ISSUE TITLE
Consider Being Able to Sort 'Coverage Rate Per Neighborhood Bar Graph'

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#170]
Right now, the x-axis of the bar graph is arranged in alphabetical order. Consider either allowing the user to sort by either alpha order or % complete or changing default to % complete (sort in descending order from left to right).

![image](https://cloud.githubusercontent.com/assets/1621749/16670651/35c82010-4469-11e6-847d-1dd6a5af9a3d.png)

**Comment by kotarohara** [comment]
I agree this is low-priority.

**Comment by misaugstad** [comment]
We have decided to go with giving the user the option to sort by either, see #412 and #342. Closing this, as this is part of a larger discussion going on in #342.
