### ISSUE TITLE
Improve Docker setup instructions in README

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1703]
This is more to keep track of things we should add to the README to make the Docker setup process easier (will send a PR probably later, but I want to write down some proposed changes before I forget). I'm also not using Docker stuff, so these instructions are 

* How to start a Docker container that has stopped, then run the website:
```
docker-compose build
docker exec -it projectsidewalk-web /bin/bash
#root@something: make dev
``` 

I think some other things that might be worth clarifying are which shell we are running commands from (e.g., we should be running `make dev` from the docker shell, not from the local shell). 

I'm not sure if a common troubleshooting section would be helpful? (Like some instructions about what to do if someone gets "127.0.0.0:9000 didn't send any data", then tell them what to do to get unstuck).

**Comment by misaugstad** [comment]
>I think some other things that might be worth clarifying are which shell we are running commands from

100% agree with this, needs to be clarified.

>I'm not sure if a common troubleshooting section would be helpful?

A section like this [has been started](https://github.com/ProjectSidewalk/SidewalkWebpage#debugging-notes) but should be expanded :) Alternatively we could keep the README clean and create a wiki page that has tons of troubleshooting stuff, and just link to it from the README? This would also make iterating on those instructions easier. And I kind of like the idea of the documentation being in the wiki.

>How to start a Docker container that has stopped, then run the website:

Not sure I understand those instructions that you gave... I thought you just ran `make dev` outside the container, then `npm start` inside the container..?

**Comment by misaugstad** [comment]
Oh also we should add an instruction to clone the Github repo :)

**Comment by aileenzeng** [comment]
> A section like this has been started but should be expanded :) Alternatively we could keep the README clean and create a wiki page that has tons of troubleshooting stuff, and just link to it from the README? This would also make iterating on those instructions easier. And I kind of like the idea of the documentation being in the wiki.

Oooh yes, I like this! Definitely would be nice.

> Not sure I understand those instructions that you gave... I thought you just ran `make dev` outside the container, then `npm start` inside the container..?

I think `make dev` starts the container, but for some reason wasn't opening up the Docker shell to run `npm start` in.

**Comment by misaugstad** [comment]
>I think make dev starts the container, but for some reason wasn't opening up the Docker shell to run npm start in.

Interesting... Shouldn't the solution to that be to run `make ssh target=web`?

**Comment by misaugstad** [comment]
closing via #1741
