### ISSUE TITLE
Curious what percentage of labels have severity ratings in Seattle/Newberg vs. DC

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1711]
I'm curious what percentage of labels have severity ratings in Seattle/Newberg vs. DC given @aileenzeng's new icon prompt for ratings...

**Comment by misaugstad** [comment]
Did some quick queries... Check severity for curb ramps, missing curb ramps, surface problems, and obstacles.
DC
168,730 / 209,814 = 80%
SEATTLE
36,381 / 37,560 = 97%
NEWBERG
2,627 / 2,685 = 98%

Seems like an improvement :sweat_smile:

**Comment by misaugstad** [comment]
Here are the queries... For total number of labels:
```
SELECT COUNT(*)
FROM sidewalk.label
WHERE deleted = FALSE
    AND label_type_id IN (1,2,3,4);
```

For count of labels with severity:
```
SELECT COUNT(*)
FROM sidewalk.label
INNER JOIN sidewalk.label_severity ON label.label_id = label_severity.label_id
WHERE deleted = FALSE
    AND label_type_id IN (1,2,3,4);
```

**Comment by jonfroehlich** [comment]
Wow, that is *so* awesome. Way to go @aileenzeng and team! 

That's a huge increase based on a UI fix. Woohoo!

**Comment by jonfroehlich** [comment]
Also, we can probably close this issue now... but maybe a stat to track for the Project Sidewalk 2.0 paper...

**Comment by misaugstad** [comment]
Agreed!
