### ISSUE TITLE
Admin playback tool broken

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1718]
Uncaught TypeError: self.panorama.changePanoId is not a function

Looks like changes we've made in other places in the code have not been made on the playback tool.

![playback-tool-broken](https://user-images.githubusercontent.com/6518824/57399982-498cd200-7187-11e9-8515-976462a13356.png)

**Comment by misaugstad** [comment]
I fixed a couple issues, but turns out that there are a bunch of other issues with the playback tool. I don't think this tool is important enough for me to spend more time on it right now.

**Comment by misaugstad** [comment]
Note that my current work on this is in branch 1718-admin-playback-tool-broken

**Comment by jonfroehlich** [comment]
Interesting visualization highlighting automatic geotagging of objects in GSV that reminded me a bit of our playback tool:

https://www.mdpi.com/2072-4292/10/5/661

![Uploading image.png…]()

**Comment by misaugstad** [comment]
Was this actually meant for #2362?

**Comment by jonfroehlich** [comment]
No, meant for here. I found it while investigating other work that uses Google's depth data...

**Comment by misaugstad** [comment]
Also this reminds me that I fixed this page! Closing via #2215
