### ISSUE TITLE
Instruct users to see the Google Maps pane in the first mission

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#172]
![cursor_and_project_sidewalk_-_audit](https://cloud.githubusercontent.com/assets/612263/16673858/f6482b94-447f-11e6-97dc-9b9189f00589.png)

- On this screen, also highlight the Google Maps pane so that users will notice they have to follow the red line. 
- Add a small text on the Google Maps pane saying "follow the red line."

**Comment by kotarohara** [comment]
Finished

**Comment by jonfroehlich** [comment]
Can I see a screenshot?
