### ISSUE TITLE
New 'Rapid' Validation Interface

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1726]
I wanted to create a thread specific to @aileenzeng's second validation interface work because we closed https://github.com/ProjectSidewalk/SidewalkWebpage/issues/535.

For her independent study this quarter, @aileenzeng has been tasked with creating a second validation interface approach for Project Sidewalk---one that attempts to really emphasize speed. We have been narrowing in on ideas but I felt like reviving our UIST'14 attempt (inspired by Google Picasa), which shows multiple label examples on a single page (maybe a grid of 3x3 or 2x3) and allows the user to rapidly validate them. We've discussed whether these grid cells need to host interactive GSV panes or if they can be static screenshots.

I'm also copying over @aileenzeng's old mocks, which captures some of this:

![image](https://user-images.githubusercontent.com/1621749/57927919-47e89b80-7864-11e9-81cb-03e36846c397.png)

![image](https://user-images.githubusercontent.com/1621749/57927963-5c2c9880-7864-11e9-85f6-3f31a71c9894.png)

**Comment by misaugstad** [comment]
closing this via #1840 as the rapid validation interface is now in the code base. There are various issues related to improvements on it before we make it public, however.
