### ISSUE TITLE
Instruct users to audit both sides of the street in the first mission

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#173]
![image](https://cloud.githubusercontent.com/assets/612263/16673887/46fca114-4480-11e6-8aed-f47d322d9011.png)

After this mission and when they take a step forward, show a message saying "Remember, we would like you to check both sides of the street! Please label problems like sidewalk obstacles and surface problems!"

**Comment by jonfroehlich** [comment]
How about this text instead:

"Remember, we would like you to check both sides of the street! Please label accessibility issues like sidewalk obstacles and surface problems!"
