### ISSUE TITLE
role "sidewalk" does not exist

### ISSUE THREAD

**Issue by coolcat647** [ProjectSidewalk/SidewalkWebpage#1733]
I tried to run this project locally with Ubuntu16.04 and docker but failed to launch the sidewalk database. I followed the instruction shown below 

- put two key files to root of project and sidework-seattle-dump to db folder
- changed  DATABASE_URL variable in yml file to ‘jdbc:postgresql://db:5432/sidewalk-seattle’ and change city-id variable in conf/cityparams.conf to ‘seattle-wa’
- type ‘make dev’ and the terminal showed:
![output_of_makedev](https://user-images.githubusercontent.com/30228008/58126897-a8058600-7c46-11e9-8156-1772df1daaa4.png)

- type ‘npm install grunt’
- type ‘npm start’ and the terminal show:
![output_of_npmstart1](https://user-images.githubusercontent.com/30228008/58126927-ba7fbf80-7c46-11e9-94ae-c77d48a83127.png)

- finally I turn on the browser and got:
![output_of_webbrowser](https://user-images.githubusercontent.com/30228008/58126959-d4210700-7c46-11e9-8e9d-5c71422a4255.png)

![output_of_npmstart2](https://user-images.githubusercontent.com/30228008/58126971-dc794200-7c46-11e9-8a81-df28440d58c0.png)

- type ‘make import-dump db=sidewalk-seattle’ and got:
![output_of_makeimport](https://user-images.githubusercontent.com/30228008/58126977-e1d68c80-7c46-11e9-9f63-c2f2a0894199.png)

I am new for web service development, could anyone give me a suggestion to solve the problem?

**Comment by misaugstad** [comment]
Hmm the error when trying to import the dump looks the same as #1527 which I thought I fixed :(

Try running `sed -i 's/\r//g' db/init.sh` and `sed -i 's/\r//g' db/import-dump.sh`. Then run `make import-dump db=sidewalk-seattle` again and see what you get.

**Comment by coolcat647** [comment]
Thanks! It works! 
I will close this issue
