### ISSUE TITLE
Are we only validating labels not previously validated?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1739]
In our current validation framework, are we only validating labels not previously validated? And then if all labels have one validation, we cycle through them again, etc.?

**Comment by misaugstad** [comment]
Validation is completely random (except you can't validate your own labels, or labels that you've already validated). It is best that we fix this :grin:

**Comment by misaugstad** [comment]
closing via #1742
