### ISSUE TITLE
Placed Label Icons Distorted in Microsoft Edge

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#175]
The SVGs in placed labels (see green circles) are distorted in Microsoft Edge.

![image](https://cloud.githubusercontent.com/assets/1621749/16673986/520689c0-4481-11e6-9a04-6a636e9540a4.png)

**Comment by kotarohara** [comment]
Closing because Edge user rate = 0.72%.

![cursor_and_browser___os_-_analytics](https://cloud.githubusercontent.com/assets/612263/18218863/7feaf392-7133-11e6-99df-51779ba9066b.png)

**Comment by jonfroehlich** [comment]
We need to test on Chrome, Safari, and Firefox at least then. I don't think I ever tested on IE.

**Comment by jonfroehlich** [comment]
@manaswis and @Soben713, perhaps you can think of a good cross-platform testing strategy for us before we deploy v2.
