### ISSUE TITLE
Signing in on validation page fires keyboard shortcuts

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1750]
If I go the validation page as an anon user and try to sign in, as I type my username and password it fires off the keyboard shortcuts!! hah

**Comment by misaugstad** [comment]
Oh yikes this also seems to be happening when adding feedback!!

**Comment by misaugstad** [comment]
Actually never mind on the shortcuts being pressed when adding feedback. That only happens if I click the feedback button _before_ I even click "ok" to start the mission.

**Comment by misaugstad** [comment]
Note that on the audit page this does not happen, so it might be helpful to look at how we prevent keyboard shortcuts from getting fired there!

**Comment by timvng** [comment]
Validation page doesn't load properly on localhost?

<img width="1162" alt="validationPage" src="https://user-images.githubusercontent.com/51970755/59886910-f3aa6d00-9375-11e9-86cb-e829cb040fc6.png">

**Comment by jonfroehlich** [comment]
Do you have anything to validate? Should at least show images on right.

**Comment by timvng** [comment]
That was the issue, thank you!

"That only happens if I click the feedback button before I even click "ok" to start the mission".
Should we fix that on the audit site as well?

**Comment by misaugstad** [comment]
>"That only happens if I click the feedback button before I even click "ok" to start the mission".
Should we fix that on the audit site as well?

I don't think that needs to be fixed in either place. Feel free to take a quick look at it, and if it is really easy to fix then go for it. But I don't think that bug is important at all. I don't really expect people to be clicking the feedback button before the missions even start.

**Comment by misaugstad** [comment]
I think the bug where it happens when signing in is the only important one here.

**Comment by misaugstad** [comment]
closing via #1753
