### ISSUE TITLE
Cursor Does Not Change in Microsoft Edge

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#176]
The cursor does not change to the hand when you are placing a label (the pointer finger icon) or when you are panning (full open hand then shifts to a grasp).

![image](https://cloud.githubusercontent.com/assets/1621749/16673992/7dc110e4-4481-11e6-916e-c6ab89f110ec.png)

**Comment by jonfroehlich** [comment]
Also, the inferred position of the curb ramp label on the right is way off...

**Comment by kotarohara** [comment]
I am closing this issue because Edge users consist of less than 1%. I don't think it is worth addressing. Please reopen if necessary.

![cursor_and_browser___os_-_analytics](https://cloud.githubusercontent.com/assets/612263/18218797/3b9488d4-7133-11e6-9bc1-7d461706db6e.png)
