### ISSUE TITLE
localhost:9000 not updating properly

### ISSUE THREAD

**Issue by nomichka** [ProjectSidewalk/SidewalkWebpage#1763]
A few things:

1) When writing and saving new code, localhost:9000 does not update automatically, even after manually reloading.
2) Running `make ssh target=web` results in:
```
Error: No such container: projectsidewalk-${target}
make: *** [Makefile:21: ssh] Error 1
```
3) Currently, the only way to update is running `docker exec -it projectsidewalk-web /bin/bash`, then `npm start`, and finally pressing Ctrl+D and reloading localhost:9000.

It's definitely workable, but it is more tedious than it should be. 

My OS is Windows 10 Pro.

**Comment by jonfroehlich** [comment]
Wonder if @athersharif or @aileenzeng have ideas...

**Comment by misaugstad** [comment]
@nomichka could you try reinstalling Make and trying again? It seems like if you run the commands that `make` is running, they work fine. But if you actually use `make` as an alias for those commands they fail.

**Comment by misaugstad** [comment]
We've made quite a few changes since this time and I haven't heard of anyone else running into this issue, so I'm closing for now!
