### ISSUE TITLE
validate severity ratings

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1767]
We may also want to validate severity ratings on labels, and could use a new validation mission type for that! Maybe we only assess severity on labels we have previously validated?

**Comment by jonfroehlich** [comment]
I think one potential problem with this might be when users disagree with the underlying label and so won't to validate that (and not just the severity, tag, or other attributes).

**Comment by jonfroehlich** [comment]
If we pursue this, we'd need mocks first of course...

**Comment by misaugstad** [comment]
A slightly broader issue has been created now that we've added tags to the interface as well. Closing as a duplicate of #2859
