### ISSUE TITLE
Should show total number of completed validations on sidebar

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1776]
![image](https://user-images.githubusercontent.com/1621749/60685400-b7880980-9e57-11e9-9b7f-dddc68007ca4.png)

**Comment by wilsmic2** [comment]
![image](https://user-images.githubusercontent.com/50855208/61557760-f1413e80-aa19-11e9-974b-910c6f34444a.png)

Where should I put this information in the sidebar? (Location 1, 2, 3, or 4)

**Comment by misaugstad** [comment]
I kind of think maybe we should replace the number of labels in the current mission with this number. We already have the mission complete bar. So I'm thinking replace section 1 with this?

**Comment by wilsmic2** [comment]
Sounds good! What does that little icon mean next to section 1? Should I leave that or get rid of it?

**Comment by misaugstad** [comment]
heheh I don't really know :sweat_smile: I guess you can get rid of it. Do whatever you need to make it clear that that is how many labels the user has validated, while not making it seem too busy :)

**Comment by wilsmic2** [comment]
hahaha ok I will do my best! I think I will leave it mainly because that is the same icon that is being used on the auditing page where it shows the total number of labels done by the user!

**Comment by misaugstad** [comment]
closing via #2029
