### ISSUE TITLE
Need to add PacTrans logo to landing page

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1778]
![image](https://user-images.githubusercontent.com/1621749/60729071-b659e980-9ef6-11e9-87d7-7384794d0adf.png)

Grab logo from: https://www.washington.edu/research/research-centers/pacific-northwest-transportation-consortium-pactrans/

Should go down here: 
![image](https://user-images.githubusercontent.com/1621749/60729103-c5d93280-9ef6-11e9-8311-cb41ee6947b9.png)

**Comment by misaugstad** [comment]
closing via #1808
