### ISSUE TITLE
Are we logging when Audit page and Validation page are in focus/visible?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1785]
We may want to consider logging when the Sidewalk webpage is visible _vs._ when it is minimized or hidden. Something like:

https://stackoverflow.com/a/1060034

Might be helpful in estimating when users are actively working.

**Comment by misaugstad** [comment]
Very interesting! I like the sound of that. And we are not keeping track of that right now!

**Comment by misaugstad** [comment]
closing via #2222
