### ISSUE TITLE
Change 'Audit' language...

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1793]
This came up in our HCDE user testing sessions: we should change the word 'audit' whenever possible to something else--something that does not connote taxes or other boringness.

So, for example, in this screen, perhaps we just use the word 'Explore':

![image](https://user-images.githubusercontent.com/1621749/61161724-fa7e5880-a4b9-11e9-91a1-2531f24ec7b6.png)

**Comment by misaugstad** [comment]
I wholeheartedly agree!

**Comment by misaugstad** [comment]
closing via #1981
