### ISSUE TITLE
Text runs off legend in Mission Complete

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1796]
![image](https://user-images.githubusercontent.com/1621749/61163114-0588b700-a4c1-11e9-9461-ef8459a62d29.png)

![image](https://user-images.githubusercontent.com/1621749/61163134-29e49380-a4c1-11e9-83b5-13d3bb36cde0.png)

**Comment by kumararoosh** [comment]
After Fix:
![image](https://user-images.githubusercontent.com/24703104/71301142-9d33e080-2350-11ea-879b-72b78572a1ad.png)
![image](https://user-images.githubusercontent.com/24703104/71301151-ae7ced00-2350-11ea-8ba5-42f6fe96b2ed.png)

**Comment by kumararoosh** [comment]
Changed the width of the legend to make the gap between the legend and the edge of the map even on both sides:
![image](https://user-images.githubusercontent.com/24703104/71301362-fe5cb380-2352-11ea-982e-b1557f07ad76.png)

**Comment by misaugstad** [comment]
looks good! feel free to submit a PR for it! nice work :)

**Comment by misaugstad** [comment]
closing via #1982
