### ISSUE TITLE
On load of validation screen, Agree/Disagree button defaults to gray...

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1797]
![image](https://user-images.githubusercontent.com/1621749/61163303-27cf0480-a4c2-11e9-8e44-65b7d0809789.png)

**Comment by daotyl000** [comment]
I have also seen this bug.

![Screen Shot 2019-07-12 at 4 45 56 PM](https://user-images.githubusercontent.com/28814007/61163692-9614c680-a4c4-11e9-85fe-28b81d9dc65a.png)

**Comment by misaugstad** [comment]
The way this seems to be working for me is that when I finish a validation mission and start a new one right after, the button I used for the last label in the previous mission is gray.

**Comment by misaugstad** [comment]
I think this is only happening when I use keyboard shortcuts, not when I click

**Comment by misaugstad** [comment]
I think it is also causing some problems with using keyboard shortcuts for validation, which isn't great :(

**Comment by jonfroehlich** [comment]
I noticed that too

**Comment by misaugstad** [comment]
closing via #1815
