### ISSUE TITLE
Color of the current mission status bar

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#18]
Ack, so many different colors on this website. We need a consistent, well-defined color palate. This green is weird! I don’t like it

![color](https://cloud.githubusercontent.com/assets/612263/13296832/69a476a2-dafd-11e5-8fd4-40ba1521f2be.png)

**Comment by kotarohara** [comment]
Assigned to Daniil.

**Comment by nguyenist** [comment]
Let me know if you'd like help with this or if Daniil has it covered!

**Comment by kotarohara** [comment]
@nguyenist Thanks! @danZzyy has finished this. I'm closing the issue.
