### ISSUE TITLE
Should we do 2 audit missions then 3 validations?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1801]
Should we do 2 audit missions then 3 validations?

Or 1 audit mission then 3 validations.

I lean towards 2 audit missions then 3 validations because otherwise it's hard to get in the 'labeling' flow...

Wonder too if we should give option to users of returning to exploring...

We've discussed these things before but not sure if we have an active Issue.

**Comment by misaugstad** [comment]
we have been discussing this in #1372 I'll copy your comment over there
