### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/SidewalkWebpage#1809]
The website suddenly stopped working and nothing would load. After about 2 minutes this message popped up

![Screen Shot 2019-07-16 at 12 17 50 PM](https://user-images.githubusercontent.com/28814007/61323063-ef7e3d80-a7c3-11e9-9b92-1fc3ceea8f3a.png)

**Comment by jonfroehlich** [comment]
Me too:

![image](https://user-images.githubusercontent.com/1621749/61323495-f35e8f80-a7c4-11e9-9dc7-312a3127a16a.png)

**Comment by jonfroehlich** [comment]
@mechanicjay said this:

> It's Back up.
> 
> I restarted the container, it looked like it was just spinning into oblivion chewing up all database connections.  
> 
> I didn't grab the application log as I restarted it before I read Mikey's message. 
> If it happens again, I'll do that before restarting.

**Comment by jonfroehlich** [comment]
Re-opening because this is continuing to happen. From @mechanicjay, looks like it's associated with the new SQL query that @misaugstad pushed (for validation prioritization)--this is what we suspected and relates to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1799

> Top two processes on the host right now:
> 
>   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                   
> 21611 postgres  20   0  260788  54332  45668 R  93.1  0.0   2:39.91 postgres: sidewalk_seattle sidewalk-seattle 172.68.0.2(49268) SELECT                                                                                                                      
> 26395 postgres  20   0  246808  53404  42416 R  90.1  0.0   4:29.57 postgres: sidewalk_seattle sidewalk-seattle 172.68.0.2(47360) SELECT  
> 
> They just sit there...then another...then another...
> The query that seems to be associated with these is:
> 
> FROM pg_stat_activity where state='active' and datname='sidewalk-seattle';
>   pid  |                                                    query                                                     
> -------+--------------------------------------------------------------------------------------------------------------
>  30827 | SELECT label.label_id, label_type.label_type, label.gsv_panorama_id, label_point.heading, label_point.pitch,+
>        |        label_point.zoom, label_point.canvas_x, label_point.canvas_y,                                        +
>        |        label_point.canvas_width, label_point.canvas_height                                                  +
>        | FROM label                                                                                                  +
>        | INNER JOIN label_type ON label.label_type_id = label_type.label_type_id                                     +
>        | INNER JOIN label_point ON label.label_id = label_point.label_id                                             +
>        | INNER JOIN gsv_data ON label.gsv_panorama_id = gsv_data.gsv_panorama_id                                     +
>        | INNER JOIN mission ON label.mission_id = mission.mission_id                                                 +
>        | INNER JOIN (                                                                                                +
>        |     -- This subquery gets the number of times each label has been validated.                                +
>        |     SELECT label.label_id, COUNT(label_validation_id) AS validation_count                                   +
>        |     FROM label                                                                                              +
>        |     LEFT JOIN label_validation ON label.label_id = label_validation.label_id                                +
>        |     WHERE label.deleted = FALSE                                                                             +
>        |         AND (label_validation.user_id <> $1 OR label_validation.user_id IS NULL)                            +
>        |     GROUP BY label.label_id                                                                                 +
>        | ) counts                                                                                                    +
>        |     ON label.label_id = counts.label_id                                                                     +
>        | LEFT JOIN (    
> Not sure if that helps or not.

**Comment by misaugstad** [comment]
I tentatively think this may have been solved in PR #1811 but we need more testing to be able to tell.

**Comment by mechanicjay** [comment]
I haven't seen any stuck postgress processes in the 3 hours since the container was rebuild.  Looking hopeful!

**Comment by misaugstad** [comment]
closing via #1811
