### ISSUE TITLE
Finished My First Full Neighborhood But No New Mission Loaded

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#181]
I finished my first full neighborhood and the 'Mission Complete' dialog came up (see below) but after I clicked OK, I was brought to a blank screen (screenshot 2 and 3 below)

![image](https://cloud.githubusercontent.com/assets/1621749/16674479/9234a162-4486-11e6-96e8-8e0c9077904a.png)

![image](https://cloud.githubusercontent.com/assets/1621749/16674445/4d75fc56-4486-11e6-8257-08fe4d026475.png)

![image](https://cloud.githubusercontent.com/assets/1621749/16674449/56f7afc2-4486-11e6-953b-dde9cbc10eac.png)

**Comment by jonfroehlich** [comment]
There's definitely a big problem here. I logged in this morning to see if I would be assigned a new neighborhood and, instead, I was greeted by a continuous loop of 'Mission Complete' messages. I kept clicking OK and then eventually I was dropped back into Mount Vernon Sq. but that's the neighborhood I just completed!

See video: https://youtu.be/RUHR6em9m7Y

**Comment by kotarohara** [comment]
I'm working on this. It is weird that you are dropped into Mt. Vernon and shown the same mission completion messages that you saw yesterday... The admin interface says you are assigned to `Logan Circle/Shaw (Region ID: 241)`, so I have to look into why this is happening...

**Comment by jonfroehlich** [comment]
That happened at very end of video. Did you notice that?
