### ISSUE TITLE
wrong label type in mission text

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1813]
as noted in PR #1572 the mission start text for a label type actually shows the text for the label type of the _previous_ mission!

![wrong-mission-text](https://user-images.githubusercontent.com/6518824/61495040-afa68a00-a96c-11e9-982d-abfcd4c4e6b2.png)

**Comment by misaugstad** [comment]
closing via #1835

**Comment by misaugstad** [comment]
@timvng this is broken again since adding the rapid validation interface. it is only on the dev branch right now. could you fix this again please? :sweat_smile:

**Comment by timvng** [comment]
Is this the bug you're referring to? The title above the pano remains 'Is this a Curb Ramp?' even after clicking OK.
<img width="1229" alt="Screen Shot 2019-08-13 at 4 38 03 PM" src="https://user-images.githubusercontent.com/51970755/62984904-c9ab7f00-bde9-11e9-968a-9da585e2fe87.png">

**Comment by misaugstad** [comment]
yes!

**Comment by misaugstad** [comment]
closing via #1864
