### ISSUE TITLE
Admin Interface: Select Label Types To Show on Map

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#182]
It would be interesting and useful to be able to select which label types to show in the admin interface map that visualizes all collected data. For example, if I wanted to see all missing curb ramp labels, I could deselect the other label types. As now, it's very difficult to see this information.

![image](https://cloud.githubusercontent.com/assets/1621749/16674653/4ca9b48c-4488-11e6-9bbf-22934ca1279c.png)

**Comment by Soben713** [comment]
Pull request #388 was tested and merged.

**Comment by Soben713** [comment]
@tongning Just realized the "Audited Streets" checkbox does not work. Here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/1576529/20271017/51b5f820-aa57-11e6-8ff2-a999b86b40c9.png)

**Comment by tongning** [comment]
I think this happens when you check and uncheck boxes quickly, before the previous refresh is completed. Will investigate solutions.
