### ISSUE TITLE
tutorial panos gone..??

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1820]
Did we finally lose the tutorial panos..?!?! I am getting the errors below when trying to access the tutorial on localhost, dev servers, and prod servers. Can anyone else confirm they get the same error on the dev servers/localhost?

I think it is just the tutorial panos b/c I can audit normally.

![no-more-tutorial-imagery](https://user-images.githubusercontent.com/6518824/61666266-e8f03a00-ac8b-11e9-8342-057591da8b0e.png)

Luckily I was about to review #1775!

**Comment by manaswis** [comment]
Yep! :o 

Thank you @htadeusiak for #1775!!

**Comment by misaugstad** [comment]
closing via #1775
