### ISSUE TITLE
Contradicting Labels_validated count

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/SidewalkWebpage#1822]
The Own Labels Validated count on the admin part of the website does not match up with the labels_validated count from a csv file of user data created by Mikey

Few Examples of counts on both 
![Screen Shot 2019-07-22 at 3 29 49 PM](https://user-images.githubusercontent.com/28814007/61669673-c2370100-ac95-11e9-9da3-1a92d38420de.png)
![Screen Shot 2019-07-22 at 3 30 10 PM](https://user-images.githubusercontent.com/28814007/61669674-c2370100-ac95-11e9-9448-41b34e338c5d.png)
![Screen Shot 2019-07-22 at 3 30 29 PM](https://user-images.githubusercontent.com/28814007/61669677-c2370100-ac95-11e9-87f5-eee54ae19dbf.png)
![Screen Shot 2019-07-22 at 3 30 53 PM](https://user-images.githubusercontent.com/28814007/61669678-c2370100-ac95-11e9-8e98-e4fb2f2d143c.png)

**Comment by misaugstad** [comment]
this could be a bug in either the SQL query I wrote when giving this data to @daotyl000 or in the counting of validations for the admin page.

**Comment by misaugstad** [comment]
@daotyl000 @nchowder thankfully this was a bug on the admin interface, not in the CSVs I sent y'all!

**Comment by misaugstad** [comment]
ok fixed it (won't be on the prod server for a bit though). note that even when the fix is up, the agreement percentage will probably be off slightly from what I sent you in the spreadsheets. We just aren't doing as complex of a calculation on the admin page.

closing via #1856
