### ISSUE TITLE
I got a whole bunch of labels all from the same user during a validation mission, is this expected behavior?

### ISSUE THREAD

**Issue by nchowder** [ProjectSidewalk/SidewalkWebpage#1823]
https://imgur.com/a/rLhkDMl

**Comment by misaugstad** [comment]
Hmm typically not... Although I suppose if we had validated 10 curb ramp labels from each user, then a new user came on and audited, we would then end up validating 10 of that new user's labels the next time someone validated... Maybe not ideal.

**Comment by misaugstad** [comment]
closing via #1889 

this should happen much less frequently now
