### ISSUE TITLE
Changing the order of actions (tagging and severity rating) in tutorial requires re-application

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1825]
The label rating gif shows two actions - applying the severity rating and then selecting the tag to be applied. However, both of these actions are enabled. So the user can do tagging first. However, the code still expects the user to rate first and then tag. So if the user does the reverse, it still waits for the user to apply the tags even if already applied. See screenshots below.

**Example**:
If tagged first, the system is waiting for the rating:

![image](https://user-images.githubusercontent.com/2873216/61742439-fa971780-ad47-11e9-933a-a01fc8fdccd4.png)

After rating, system waits for the tag even if previously selected:
![image](https://user-images.githubusercontent.com/2873216/61742476-0aaef700-ad48-11e9-9841-193fb509c572.png)

So you have to unselect the tag:
![image](https://user-images.githubusercontent.com/2873216/61742568-45189400-ad48-11e9-969b-5eb010d41fec.png)

and then reapply for the next step to happen:
![image](https://user-images.githubusercontent.com/2873216/61742588-52ce1980-ad48-11e9-893a-fee118870a6f.png)

**SOLUTION:**
The solution is either to do disable tagging before rating OR allow either application and let the code run regardless of the order of actions taken.

**Comment by misaugstad** [comment]
closing via #1836
