### ISSUE TITLE
show locally stored tutorial panos on admin interface

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1826]
Now that we are loading panos for the tutorial from local storage, they are not showing up when trying to view those labels on the admin page contributions tab. We should fix this :)

**Comment by misaugstad** [comment]
@hanszhang00 PRs #1775 and #1834 add the local panos to the tutorial, so that code should help you include them on the admin page as well!

**Comment by misaugstad** [comment]
@ThatOneGoat to test this, you'll need to make yourself an admin on your local dev environment. You can do this by changing the entry for your account in the `user_role` table. You can figure out which `user_id` is yours by looking at the `sidewalk_user` table, and you can figure out which role is the Admin role by looking at the `role` table.

Once you make your account an admin account, you will be able to visit the admin page via the navbar (it is in the drop down menu). Then in the 'Contributions' tab, you can see labels that have been placed recently. If you place some labels from the tutorial, you will notice that when you try to view the GSV imagery for them on the admin page, it is blank. This is what you're trying to fix!

We are no longer fetching that imagery from google maps, we instead have the panos stored in our repo and are using those during the tutorial. We just need to grab those panos again on the admin page.

**Comment by ThatOneGoat** [comment]
Quick clarification, is the panorama ID from the label metadata used in AdminPanorama the same as the one passed to Panorama and PanoramaContainer? Can I get information regarding whether or not the label was from the tutorial from it?

**Comment by misaugstad** [comment]
@ThatOneGoat can you point me to exact lines of code here?

**Comment by ThatOneGoat** [comment]
Yeah, in PanoramaContainer.js, I saw this code:
![Screen Shot 2020-01-11 at 12 36 39 AM](https://user-images.githubusercontent.com/37346427/72201578-75451380-340a-11ea-87e7-98d6965a081d.png)
and I noticed it takes a parameter of panoramaId, so I was wndering if there was a way to get the same panoramaId and use it in AdminPanorama.js.

**Comment by misaugstad** [comment]
>and I noticed it takes a parameter of panoramaId, so I was wndering if there was a way to get the same panoramaId and use it in AdminPanorama.js.

Interesting, I don't fully remember how all these files interact. But I just opened up Admin.Panorama.js and I saw a `panoId` variable that should be the same thing.

**Comment by ThatOneGoat** [comment]
Got it. What is the panoramaId usually represented as? Is it a string or its own object? From what I've tested so far the panoId used in the regular Panorama and the AdminPanorama seem different as they log completely different things when I print them to console

**Comment by misaugstad** [comment]
the pano id should be a string. what else are you seeing?

**Comment by ThatOneGoat** [comment]
When I logged the regular Panorama Id I got a string that said tutorial for a tutorial which made sense. I did the same for the Admin Pano and I got a number. I'll do it again to and put steps on how I did it to see if I'm doing something wrong

**Comment by misaugstad** [comment]
The one that is called tutorial is the one that we have saved locally, so it should look different. It normally looks like a string that contains both letters and numbers.

**Comment by ThatOneGoat** [comment]
Ah, got it. I've still been unable to see my recent contributions from the tutorial in the Contributions tab, however. I should be seeing it as the first few entries, right?

**Comment by misaugstad** [comment]
Interesting, just checked and they aren't showing up for me either. I'll take a closer look now.

**Comment by misaugstad** [comment]
Okay yep! Looks like we needed to add a fake entry to the `gsv_data` table after swapping in our locally stored tutorial panos for all the queries to work as usual. So add a file called `73.sql` to the `conf/evolutions/default` directory, and the file should look like this:
```
# --- !Ups
INSERT INTO gsv_data VALUES ( 'tutorial', 13312, 6656, 512, 512, '2014-05', 1, '', FALSE, now() );

# --- !Downs
DELETE FROM gsv_data WHERE gsv_panorama_id = 'tutorial';

```

Then you should be able to see those entries!

**Comment by ThatOneGoat** [comment]
Sounds good. Just a question, though. I get why we might want to collect data from tutorials like user stats etc but why do we need to show contributions from tutorial page in the contribution tab? Isn’t that a little redundant?

**Comment by misaugstad** [comment]
Fair point. I don't think being able to see the tutorial labels in this particular place is all that important by itself. Though I do use it to see how far someone got through the tutorial in certain cases. Being able to view the labels from the tutorial on the panos somewhere else also makes me feel more confident that we are recording the data correctly. We will also likely want to visualize the labels on the tutorial panos somewhere else in the future, and if you figure out how to do it here, we can just copy that in the future :)

**Comment by ThatOneGoat** [comment]
Ok, that makes sense.

**Comment by ThatOneGoat** [comment]
For the labels in the AdminPanoramas, should I be able to interact with them (is hovering over them supposed to show anything, etc.)

**Comment by misaugstad** [comment]
nah I don't think that's important

**Comment by misaugstad** [comment]
closing via #1999
