### ISSUE TITLE
Repeat Validation Mission

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/SidewalkWebpage#1827]
I was just assigned a surface problem validation mission that I had just done a few hours ago. It was the exact same labels in the exact same order

**Comment by misaugstad** [comment]
That is very very odd.. Interested to see if it happens again.

**Comment by misaugstad** [comment]
I'm making some change now to prevent repeated validations. But this exact situation hasn't happened in years so I'm going to close it!
