### ISSUE TITLE
Do we need DC street data in all of our city deployments now that we load tutorial panos locally?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1830]
Do we need DC street data in all of our city deployments now that we load tutorial panos locally (from https://github.com/ProjectSidewalk/SidewalkWebpage/issues/681)?

**Comment by misaugstad** [comment]
Yeah we do, the labels will still have a lat-lng in DC etc, etc. Storing the panos locally doesn't change that much of the underlying code to make it so that we don't need the data associated with this street in DC.
