### ISSUE TITLE
API - add format that can be read by ArcGIS

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1832]
Turns out that you need an expensive extension to read GeoJSON into Arc... We should provide an alternative format for downloading the data so it can be read in Arc.

**Comment by kumararoosh** [comment]
Will create an API using the shapefiles format

**Comment by kumararoosh** [comment]
Looks like there is no legacy support for gt-shapefile, so we have to upgrade all of the geotools libraries to 20.3

**Comment by misaugstad** [comment]
Oh weird. How do you know?

**Comment by misaugstad** [comment]
I worry that upgrading the other geotools libraries could be impossible, because it might require updating various other libraries as well

**Comment by kumararoosh** [comment]
I was able to update all the other libraries to the 23.0 version, and tested all of the api calls. They all function the same as before updating the libraries

**Comment by kumararoosh** [comment]
Also, the server that had gt-shapefile legacy builds was supposed to be on boundlessgeo, but boundlessgeo was bought by another company, and that new company did not retain support for legacy builds
