### ISSUE TITLE
Washington DC link on the landing page no longer links to the proper place

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1837]
![image](https://user-images.githubusercontent.com/1621749/62152179-dfcc2200-b2b6-11e9-938e-d14bf40a9fdd.png)

It's linking to sidewalk.cs.washington.edu vs. sidewalk-dc.cs.washington.edu (or whatever is appropriate).

**Comment by misaugstad** [comment]
closing via #1865
