### ISSUE TITLE
Own mission completed green line glitch around the map in labeling mission completed

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/SidewalkWebpage#1839]
In the map view after completing a labeling mission, there were two green lines in my map that are always in the same position in my window (not actually aligned or attached to any street). when I zoom in and out, the two lines stay the same size and proportional distance from each other. If I pan, the green lines will stay in place but will scale to remain the same distance in the window. This is kinda a bad description but the problem is evident in the video.

Video:
https://youtu.be/fXOuk3IDXFo

**Comment by misaugstad** [comment]
Would be curious to see if you ever see it happen again or if anyone else sees this bug!

**Comment by daotyl000** [comment]
This has repeatedly happened to me. Here is a video from doing it in Newburg.

Video:  https://youtu.be/8MckAnH9ZHw

**Comment by misaugstad** [comment]
closing via #1909
