### ISSUE TITLE
Admin Interface: Label Type does not show up for Other?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1844]
See screenshot. I think this would be good for Mikey 2 as he did some admin stuff already. Should be easy fix.

To replicate: click on an 'Other' label in the map and get the pop-up. Note how the Label Type is missing for Other.

![image](https://user-images.githubusercontent.com/1621749/62323583-784fd700-b45c-11e9-8fc8-69cd0db4eefa.png)

Here's what it should look like--here, label type has 'Surface Problem'

![image](https://user-images.githubusercontent.com/1621749/62323672-aaf9cf80-b45c-11e9-9cfa-74344c50a009.png)

**Comment by misaugstad** [comment]
Ahh! This was fixed elsewhere on the admin interface in #1302 but it looks like we've missed this location!

**Comment by misaugstad** [comment]
closing via #1961
