### ISSUE TITLE
Rapid Validation Critique

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1845]
@misaugstad asked me to review the recently pushed Rapid Validation interface (https://sidewalk-sea-test.cs.washington.edu/rapidValidate) that @aileenzeng led. Here are my initial thoughts/immediate impressions.

![image](https://user-images.githubusercontent.com/1621749/62324981-86532700-b45f-11e9-9566-60d153582ec4.png)

1. First impression: the interface is overwhelming and visually cluttered. Thoughts: perhaps overlay the agree (checkmark), disagree (X), and ? (not sure) buttons? I would also experiment with only showing them on mouseover (but again, pop-up on top of interface just like Marianne's mobile validation UI). Also, the black line of 2019 Google, Terms of Use, Report a Problem is super annoying. I suggest we hide that and then just put it all on the bottom of the interface. I may also remove the 'Skip' and 'Feedback' buttons because they add to visual clutter (but perhaps we do the other things first and see how it goes).

2. On the right pane, I would put titles of "Correct Missing Curb Ramp Examples" and "Incorrect Missing Curb Ramp Examples" (I would do this for normal validation interface too).

3. How do we zoom in to a pane? I tried mousewheel on a select pane (aka cell) but it didn't work.

4. Because we instantly load a new label as soon as user selects Agree, Disagree, Not Sure, I find myself just focused on one cell at a time thereby making this approach very similar to the regular validation interface (just harder because I'm looking at a tiny window, doh). I wonder if we could experiment with having the user select a response (Agree, Disagree, Not Sure) and having the response overlaid on cell (e.g., a giant green checkmark for Agree) and then when they get done with all nine cells, we reload all cells? Currently, I'm suspicious that we will really see any efficiency gain from this 'rapid validation' interface--what do you think @misaugstad?

5. Do we need a skip option in the buttons themselves? So we would have four buttons?

6. The number of validations to complete per mission should be different here--and should be a divisible by 9. So, maybe 18 or 27?

7. We need the mouseover label support for this interface (so you can mouseover and hide label and also see metadata)

8. Bug, sometimes I would get the same label to validate loaded dynamically in a cell (i.e., after selecting a response in a cell, it loads a new label but that label is already loaded in another cell). So, for example, see the first two cells below.

![image](https://user-images.githubusercontent.com/1621749/62325599-dda5c700-b460-11e9-925d-22004a1686f2.png)

**Comment by misaugstad** [comment]
>I find myself just focused on one cell at a time thereby making this approach very similar to the regular validation interface (just harder because I'm looking at a tiny window, doh).... Currently, I'm suspicious that we will really see any efficiency gain from this 'rapid validation' interface--what do you think @misaugstad?

That is exactly how I felt. It just felt like a worse version of the current validation interface and I don't see how this could be better right now :cry:

**Comment by jonfroehlich** [comment]
I'd like to see some of my ideas implemented. And then make a decision about whether to keep pursuing it. HCI research is all about making these interactive prototypes, using them, iterating, and seeing what works and what doesn't. A failure here is also a success in that we learn this approach is just not a good idea... but again, not ready to conclude that until my suggestions are incorporated.

**Comment by jonfroehlich** [comment]
We are closing rapid validation related Issues right now. This was a great experimental prototype but the idea didn't pan out.
