### ISSUE TITLE
Labeling buttons stay highlighted after clicking them in Firefox

### ISSUE THREAD

**Issue by nchowder** [ProjectSidewalk/SidewalkWebpage#1846]
See this image:
![image](https://user-images.githubusercontent.com/17211794/62401452-182e6300-b538-11e9-83b1-c5a7485122ab.png)
After I click Curb Ramp, No Curb Ramp, etc., the label stays highlighted, even after I place the label on the canvas. I'm using Firefox on Linux.

**Comment by misaugstad** [comment]
@nchowder have you been able to reproduce this? Are you able to reproduce this on other browsers as well?

**Comment by misaugstad** [comment]
I was able to reproduce this on Firefox on Linux, but not on Chrome. All I had to do was hover over the label type icon and it would remain highlighted.

**Comment by nchowder** [comment]
It also happens in Firefox on Windows.

**Comment by misaugstad** [comment]
closing via #1996
