### ISSUE TITLE
Love the 'Can I Select A Neighborhood to Audit Video' - A Suggestion

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#185]
I love the 'Can I select a neighborhood to audit video' on the FAQ page. Nice job! I hope we can use this strategy for other things in the future!

![image](https://cloud.githubusercontent.com/assets/1621749/16710088/1f2f7090-45f1-11e6-958a-634732f1c483.png)

A few suggestions:

- Can we increase the default size of the video. It's so small, I can't view it easily without going fullscreen. Ideally, our videos on the FAQ page would be formatted so you can just click play and can understand them.
- Less importantly, I wonder if this video is a good candidate to be an animated gif rather than a video. Maybe. Maybe not. Again, gif would have to be larger
- Finally, I think we should host all of our videos on YouTube rather than directly on the site and then just embed them. Thoughts?

**Comment by kotarohara** [comment]
Probably not gif; I don't know how to control play/stop. I'll adjust size.

YouTube: we could. Pro is we don't have to have huge binary file in our
repo and free view counter. Con is we have even more things/accounts to
manage. I think we can decide if we start having more videos.

**Comment by jonfroehlich** [comment]
Sure. I understand re: gif. It may still make sense in some cases. I've seen it increasingly used on lots of websites to demonstrate 'how tos'--you can even split a video into two gifts side-by-side with captions.

I want to make a very simple 30 - 45 sec video overview of how to use Project Sidewalk. Will have to wait until after NSF deadline, however. :(

**Comment by kotarohara** [comment]
I think hosting the videos on YouTube is another issue, so I moved it to the new issue ( #201 ). I'm closing this one.
