### ISSUE TITLE
add zoom functionality to rapid validation

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1850]
Suggested in #1845

**Comment by jonfroehlich** [comment]
We only want to invest time in this after we try to address 1 and 4 in the list in https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1845. Because if we can't address 1 and 4, then I think we end up declaring the rapid validation interface a 'no go'

**Comment by jonfroehlich** [comment]
We have tabled rapid validation for now...
