### ISSUE TITLE
NoSidewalk Validation example description wording

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/SidewalkWebpage#1857]
The way the no sidewalk example description for these two seem off. the "is has" seems like the "is" is unneccessary.

![Screen Shot 2019-08-08 at 3 52 26 PM](https://user-images.githubusercontent.com/28814007/62742806-e6644300-b9f4-11e9-9185-fd5e5fd9da91.png)
![Screen Shot 2019-08-08 at 3 52 31 PM](https://user-images.githubusercontent.com/28814007/62742807-e6644300-b9f4-11e9-9c50-4969570a03c9.png)

**Comment by leonli33** [comment]
Fixed the grammar mistakes in the "No Sidewalk" sample descriptions described above. Changed descriptions can be seen below:
<img width="362" alt="2020-01-02" src="https://user-images.githubusercontent.com/31671708/71702112-78912d00-2d82-11ea-826d-42b22101e445.png">
<img width="351" alt="2020-01-02 (1)" src="https://user-images.githubusercontent.com/31671708/71702120-7e870e00-2d82-11ea-8cc9-288775e7a69b.png">

**Comment by misaugstad** [comment]
look good! can you create a PR for the fix?

**Comment by misaugstad** [comment]
closing via #1987
