### ISSUE TITLE
Consider Adding Examples of Ratings 1, 2, 3, 4, 5 of Each Label Type to FAQ

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#186]
Consider Adding Examples of Ratings 1, 2, 3, 4, 5 of Each Label Type to FAQ.

This would also be--hopefully--in the updated '?' design in the actual interface.

**Comment by jonfroehlich** [comment]
This is related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/79. Once https://github.com/ProjectSidewalk/SidewalkWebpage/issues/79 is complete, would be very easy to add this to the FAQ.

We should monitor FAQ website traffic to see how frequently visited it is. My guess is, traffic will be quite low to this compared to actual audit pages.

**Comment by kotarohara** [comment]
@Soben713 , please copy the examples on the "Explain this!" modal windows to the FAQ page.

**Comment by Soben713** [comment]
@kotarohara Will do.
