### ISSUE TITLE
Labels not appearing on the mini-map

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/SidewalkWebpage#1860]
There were some regions of my pano where I would place a label and it would not appear on my mini-map. Although I did not show it in the video, I tested out different label types afterward. I found that label type had no effect on the issue, just the location of the label. This is the first time I've experienced this and I have not seen it on any other panos in this mission.

Video:
https://youtu.be/xxFsuB25CBI

**Comment by jonfroehlich** [comment]
Interesting! We rely on the 3-D depth data to convert placed labels to lat,long. I wonder what the 3D data looks like here

**Comment by misaugstad** [comment]
I think @jonfroehlich is on the right track. This looks like an image with the depth data, which we unfortunately cannot fix.

**Comment by misaugstad** [comment]
duplicate of #1160
