### ISSUE TITLE
validate directly from admin contributions tab

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1861]
as discussed in #1166 we would like to be able to validate a label directly from the admin contributions tab. When we click on the label and the pano with the label shows up, we should have agree/disagree/not sure buttons there.

**Comment by jonfroehlich** [comment]
And a feedback textfield box

**Comment by misaugstad** [comment]
I'm actually not 100% sure when this was implemented, but it's already happened! We have shared code between this and other admin pages, so it probably was added as a byproduct of adding it to the /admin/user endpoint or something!
