### ISSUE TITLE
Sometimes first two labels in a validation mission are the same

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1869]
Sometimes first two labels in a validation mission are the same. See: https://youtu.be/0ojd5IRuMVc?t=60. I'm using the new 6.5.5 version that was just deployed today.

(if you don't start at 60s, you'll note that the surface problem validation set of 10 didn't start with a redundant label; however, I believe I did experience this before with this label type just didn't capture it on video).

**Comment by jonfroehlich** [comment]
I am consistently getting this for all label types in Newberg. Haven't tested in Seattle (I assume same problem there).

**Comment by misaugstad** [comment]
hmm very odd!

**Comment by misaugstad** [comment]
will look into it this week!

**Comment by misaugstad** [comment]
closing via #1870
