### ISSUE TITLE
5280ft should be 1mile

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#187]
I just got a mission that said audit 5280ft, but this should be 1mi instead.

![image](https://cloud.githubusercontent.com/assets/1621749/16713723/8891890a-467e-11e6-89b6-6ed7bcd25674.png)

(Sorry, I didn't get a screenshot of the mission pop-up)

**Comment by kotarohara** [comment]
This became no longer a problem as I updating #125
