### ISSUE TITLE
Skip & Feedback button not working

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/SidewalkWebpage#1871]
Nothing happens what I try to press the skip button

When I press the feedback button, it pulls up the box but I an unable to interact with it (unable to type of press the button) but I can still move the pano around behind the box. I am also unable to press any other buttons (agree, disagree, not sure, zoom) so I am essentially stuck on that validation

Video: https://youtu.be/gzfmYrJJVIU

**Comment by misaugstad** [comment]
yep this is happening for me too, only on validation.

**Comment by misaugstad** [comment]
closing via #1872
