### ISSUE TITLE
Repeating Labels when skipping on validations

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/SidewalkWebpage#1874]
I had skipped this label at the beginning of the mission. Then it appeared at the very end. I kept trying to skip this but I was unable to get another label. I tried replicating this with the same and different label types but I was unable to replicate it.

Video: https://youtu.be/esKyF-N9390

**Comment by daotyl000** [comment]
This has occurred to me again. Both times it was with the surface problem label

Video: https://www.youtube.com/watch?v=7FwAhulVD5M

**Comment by misaugstad** [comment]
Ok I think this might be solved by adding a bit more randomness into the label selection process. I will make a PR for this soon.

**Comment by misaugstad** [comment]
To explain a bit more: I think what's happening is that we have some priority ordering for the labels that need to be validated, and it splits the labels up into a few categories. We give all the labels in a certain category (say, from users who have had less than 10 of their labels validated) before we give any labels from another category. We randomize the ordering of the labels within each category.

But if there is only one label left in the highest priority category... Then when you skip and ask for a new label, that one label will always be the first one chosen. If we randomize not just within-category, but also across category, it should prevent the determinism that leads to the same label getting selected over and over again.

It should also reduce how much #1823 happens, where we would get a validation mission with labels all from the same user.

Note that with the current setup, only making that change would still result in a 1 in 5 chance that we get the same label after skipping. So I also need to add in something that prevents the exact same label from possibly coming up again right after.

**Comment by misaugstad** [comment]
closing via #1889

**Comment by jonfroehlich** [comment]
> So I also need to add in something that prevents the exact same label from possibly coming up again right after.

Did you also address this?

**Comment by jonfroehlich** [comment]
And thanks to @daotyl000 for filing this Issue!

**Comment by misaugstad** [comment]
Yep! Sorry I just didn't go into great detail on it. I just passed the label id of the label being skipped to the back end so we could make sure we didn't give it again.
