### ISSUE TITLE
Repeated Auditing Mission

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/SidewalkWebpage#1875]
I had just finished an auditing mission and when I went to the next one, it routed me through the exact same route.

**Comment by jonfroehlich** [comment]
Uh oh! Were you signed in?

**Comment by jonfroehlich** [comment]
Hmm. I have never seen this. Are you sure same route and not just some overlap?

**Comment by misaugstad** [comment]
This has not been reported 11 months, and we have made this code less buggy in other ways in recent months, so I think it is unlikely that this bug still exists, so I'm going to close this for now. We can always reopen if it happens again.
