### ISSUE TITLE
Mobile feedback button is sometime partially hidden

### ISSUE THREAD

**Issue by htadeusiak** [ProjectSidewalk/SidewalkWebpage#1879]
The feedback box has some problems. I can at least see the feedback button now for all label types. However, it is still partially cut off for surface problem label type. 

I think the best way to fix this for all phone sizes is to make it is possible to scroll on that page.

This is an old image before I changed the spacing, but you can see how it cuts off the "Feedback" button at the bottom. It still does this for surface problems because it has the longest description text.
![63982059-4db26780-ca76-11e9-9511-c187b2c34015](https://user-images.githubusercontent.com/33988444/64049606-3765e380-cb2a-11e9-87d0-9e8a07c8b8d7.png)

**Comment by misaugstad** [comment]
closing via #2165
