### ISSUE TITLE
Add zoom feature to mobile validation

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1883]
Ideally with a pinch zoom, which is what people typically expect on mobile.

**Comment by jonfroehlich** [comment]
I personally feel--and am curious what others think--that without zooming here, mobile validation is hard to use (particularly for 'surface problems' but I also feel the desire to zoom in on many other label categories).

Indeed, I'm not sure we should deploy and advertise mobile support until we have this feature integrated.

**Comment by timvng** [comment]
Agree! I'm currently focusing on implementing this.

**Comment by jonfroehlich** [comment]
Awesome. Good to hear @timvng.

**Comment by misaugstad** [comment]
closing via #1893
