### ISSUE TITLE
Audit missions are continuing even after reaching 100%

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1885]
I decided to try and finish the George Fox neighborhood in Newberg this weekend (as a break from paper writing). Once I reached 100% on the mission screen, I was expecting to be done--however, I have gotten ~3-4 missions since initially reaching 100% completion. I decided to start recording a video of my experience:

https://youtu.be/-FeMxvQmytI

**Comment by misaugstad** [comment]
closing via #1909
