### ISSUE TITLE
After completing a neighborhood, PS hangs

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1886]
I just completed George Fox neighborhood in Newberg. Once I did, the mission complete screen hangs with a 'busy cursor' over the 'Audit Another Neighborhood' button and the button never turns blue (always stays gray).

![image](https://user-images.githubusercontent.com/1621749/64128535-d299cb80-cd6b-11e9-9c2d-484009ba94f3.png)

**Comment by misaugstad** [comment]
closing via #1909
