### ISSUE TITLE
Admin Interface: I added a comment via the Feedback button yesterday, but not showing in admin interface

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#189]
Admin Interface: I added a comment via the Feedback button yesterday, but not showing in admin interface.

![image](https://cloud.githubusercontent.com/assets/1621749/16713843/69dd92ee-4681-11e6-9c8c-50aebc3236b0.png)

**Comment by jonfroehlich** [comment]
Also not showing in the direct url admin interface for the user (in this case, jonfroehlich):

![image](https://cloud.githubusercontent.com/assets/1621749/16751182/74f7820a-47a5-11e6-8c10-30f8b41069ae.png)

@kotarohara, is this a UI problem or are we not saving feedback from users correctly in the database?

**Comment by kotarohara** [comment]
I think there is an issue with comment feature.

**Comment by jonfroehlich** [comment]
So that means that the comments are *not* being saved? (Hence, all of my time spent typing in comments was for naught?).

This also affects our ability to analyze user comments. :(
