### ISSUE TITLE
Auditing Routing through non-road

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/SidewalkWebpage#1890]
I am not sure if this is a google map issue but it looks like either the flight of stairs on the left is being called a road, or that it things there is a road connecting the current road and where it wants me to go but it is just grass and dumpsters

![Screen Shot 2019-09-03 at 1 52 25 PM](https://user-images.githubusercontent.com/28814007/64207872-5b8b3280-ce52-11e9-8d8f-1555c154913f.png)

**Comment by misaugstad** [comment]
This seems like an error in how OSM has classified that route. I know that @nchowder had found some problems with the OSM road network and had talked about figuring out the process for making those fixes. Did that ever happen?

Figuring out the process for making edits to the OSM road network and writing a short guide for it on our wiki is something very useful, and we could point others to it in the future when they come across stuff like this :)

**Comment by nchowder** [comment]
I never did figure out how to make changes to the OSM road network. I think [this page](https://wiki.openstreetmap.org/wiki/Contribute_map_data) might be helpful.

**Comment by misaugstad** [comment]
closing because I have created an issue specifically for fixing OSM errors (#1896)
