### ISSUE TITLE
double tap zoom on mobile breaks validation

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1894]
At least on Safari, I am able to double tap two things to try and zoom in: the info bar at the top and the label itself. When tapping on the info bar, the zoom is sort of minor, but you still can't see the validation buttons at that point. And if you double tap on the label, you zoom in very far.

If you double tap on the label again, it will zoom you back out. But if you pan at all, the label disappears and you are no longer able to zoom back out or do anything really.

What it looks like before zooming:
![IMG_4103](https://user-images.githubusercontent.com/6518824/64286469-63aaa700-cf12-11e9-936c-b77d8066611c.PNG)

After zooming on the info bar:
![IMG_4104](https://user-images.githubusercontent.com/6518824/64286483-6a391e80-cf12-11e9-8ca0-3f6a7430b4f4.PNG)

After zooming on the label:
![IMG_4105](https://user-images.githubusercontent.com/6518824/64286500-74f3b380-cf12-11e9-968f-d01347efbaca.PNG)

After zooming on the label then panning:
![IMG_4106](https://user-images.githubusercontent.com/6518824/64286510-7cb35800-cf12-11e9-987e-cc7f2d062048.PNG)

Given that I cannot zoom in by double tapping the actual panorama, there must be a way to prevent double tap from zooming on the remaining parts of the interface.

Also note that this is pretty much unrelated to the current zoom PR #1893 because that uses the GSV zooming mechanism, which totally different from this.

**Comment by ThatOneGoat** [comment]
Ok, I'm not quite sure how you were able to do the double tap zoom by tapping on the label itself (mine doesn't do anything when I test on safari on my IPhone) but I get a similar issue when I double tap on the validation buttons where the zoom is huge and you can no longer see the panomarker. 

I'll just aim to find a way to disable double-tap zoom in general

**Comment by misaugstad** [comment]
closing via #2034
