### ISSUE TITLE
make Project Sidewalk business cards

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1897]
quote from someone from newberg commenting on our advertising:

>I would strongly suggest that you make it a policy to print out business cards with the Project Sidewalk logo, the city logo (whatever city), BIG PRINT URL, and contact information for questions—for every city you introduce Project Sidewalk in. People just do not remember URLs—ever—and so having it on a piece of paper will provide both a reminder of the address and a physical reminder to keep this on the to do list. You might even consider a short online version to get emailed en masse (but only with the blessing of the city, and only to those who have expressed/should have an interest in the project). I cannot emphasize enough in this short space how important it is to get this information in front of people when they sit down at their computers (or enter it into their phones).

@manaswis comment from #1887 

>I have long considered printing out customized business cards with Project Sidewalk logo behind it and we have such pretty graphics to do that! Example: https://www.moo.com/us/ - they have REALLY awesome designs!

**Comment by jonfroehlich** [comment]
And @gari01234 has also been working on this.

In fact, @gari01234, it would be awesome to have you check-in all of the amazing logo and graphic work to: https://github.com/ProjectSidewalk/Branding.

I'm closing this Issue for now as it belongs in https://github.com/ProjectSidewalk/Branding. If we want, we could duplicate it there.
