### ISSUE TITLE
have project sidewalk QR codes for physical media

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1898]
from #1887 

>Another idea is to have **QR codes on flyers and other physical media.** It's easy to scan. However, that would also mean that they would do it on the phone and we don't support auditing on the phone yet. But if we can find a way to use it to have them save the address or bookmark or something --- we could point them to mobile landing webpage with different city addresses, something like this:
>
>![image](https://user-images.githubusercontent.com/2873216/64199619-946ddc00-ce3f-11e9-8e3b-cd55a64a30f2.png)
>The last sentence was supposed to be Validating Existing Labels -- but the language is not important.
>
>Language, ordering etc can change but this is to give a general idea.
>(Didn't have a proper sheet of paper :P)

**Comment by jonfroehlich** [comment]
I think @gari01234 was making similar QR codes? If so, we should get them committed to https://github.com/ProjectSidewalk/Branding (@gari01234, feel free to commit them directly or send them to me and I can do it).

This Issue now belongs in https://github.com/ProjectSidewalk/Branding so closing it here.

**Comment by jonfroehlich** [comment]
A quick example from @gari01234:

![image](https://user-images.githubusercontent.com/1621749/94144530-19021280-fe26-11ea-8067-8a87409ad468.png)

**Comment by gari01234** [comment]
I just add the files here: https://github.com/ProjectSidewalk/Branding/tree/master/CitySpecific/CDMX

So far I have only made graphics with QR code for CDMX, next week I can maybe make another one for another city with a different theme.

**Comment by jonfroehlich** [comment]
This is amazing. So, these QR codes go directly to CDMX?

**Comment by gari01234** [comment]
Yes. Next week I can probably do the QR codes for the other cities :) 
I am using this page to generate the QR codes: http://goqr.me/de/ then I adjust the colors in Photoshop.
