### ISSUE TITLE
Total Distance Audited in Km on Dashboard

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#190]
In the dashboard for users, the total distance audited is in km; however, other parts are in miles. So, let's put miles as the main metric (and km in parenthesis).

![image](https://cloud.githubusercontent.com/assets/1621749/16751316/62bbc654-47a6-11e6-8f20-b8b07305b75c.png)

**Comment by kotarohara** [comment]
I feel like there was a same issue somewhere.
