### ISSUE TITLE
Mobile validation: Font style on the text on completion screen

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1902]
![image](https://user-images.githubusercontent.com/2873216/64734214-12169500-d49b-11e9-88d9-a855877a6c5d.png)

Agree, Disagree, Not sure looks different. Zoom-in its looks more filled in. However, the page crashes if zoom in too much (#1903).

**Comment by misaugstad** [comment]
@MattJ12 there are instructions for testing on mobile [here](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Process-for-contributing-new-code#testing-your-contribution).

**Comment by misaugstad** [comment]
This looks like it has actually been resolved somehow! Tested on 3 different phones and the font seems to be looking fine!
