### ISSUE TITLE
Mobile: Validation completion page crashes on zooming in

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1903]
Landing Page's zoomed in state that doesn't crash:
![image](https://user-images.githubusercontent.com/2873216/64734368-599d2100-d49b-11e9-80aa-b0c8b06c6b92.png)

This level of zooming crashes it. I was zooming to figure out #1902 issue.

**Comment by misaugstad** [comment]
Even just preventing zooming is an okay solution for this one. Figuring out why it is crashing and preventing it would be better, but I'm not sure users need to be able to zoom here.

**Comment by jstadeusiak** [comment]
Been experimenting around with this error and was not able to replicate it until now. From what I understand the series of errors that may potentially cause the crash do not occur when on the mobile validation page, seems like the errors/crash actually occur while validating. I created the error by zooming in and out on the validation pages, and eventually it replicated itself a couple times. I was able to continue validating through the mission, but when the validation completion page displayed the crash/errors prevented me from continuing. 
I've attached the docker log for it below as well as the console for chrome dev tools. 
![image](https://user-images.githubusercontent.com/64165755/86283023-1d0af500-bb95-11ea-87df-b20fc54ca56f.png)
![image](https://user-images.githubusercontent.com/64165755/86283204-69563500-bb95-11ea-8c99-116d783b141d.png)

**Comment by misaugstad** [comment]
oo so the page is actually crashing when you get this error?

**Comment by jstadeusiak** [comment]
Not really, this error is logged while going through validations and I can continue to validate until I complete the mission. 
![image](https://user-images.githubusercontent.com/64165755/86284063-006fbc80-bb97-11ea-9783-bdd6811451bb.png)
When I reach this completion page its here where the page becomes completely unresponsive

**Comment by misaugstad** [comment]
@jstadeusiak do you only get this when zooming in and out? What if you just pan around a bunch? The error being logged doesn't _look_ related to the zooming. But it definitely could be. But just to rule out other possibilities, can you try some normal validating and seeing if the error shows up? And a ton of panning to see if it shows up/

**Comment by jstadeusiak** [comment]
Update: This error was being triggered after switching mobile devices in chromes dev tools without refreshing the page.  The completion page is generally unresponsive to any sort of interaction other than the button to continue validating. Occasionally zooming in will work, but will not cause any sort of crash. I believe this issue can be closed.

**Comment by misaugstad** [comment]
Agreed. We talked about this during the weekly meeting yesterday and a few of us tested the live site and didn't come across this issue.
