### ISSUE TITLE
Mobile Validation: Need visual confirmation of which button was just pressed

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1905]
For mobile validation, need visual confirmation of which button was just pressed. Maybe a quick animation (see below) or at least change the button color for a second on touch-lift?

![MobileValidationFeedbackToUserOnButtonPress](https://user-images.githubusercontent.com/1621749/64738886-60309600-d4a5-11e9-8d6d-5853e62974df.gif)

Note: as the animation is occurring, should be loading next image or something (not shown in mock).

**Comment by misaugstad** [comment]
closing via #2048
