### ISSUE TITLE
track validation users on admin page

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1906]
We just launched mobile support yesterday (woohoo!) and we've seemingly got some new users. Because mobile is (currently) always anonymous, they should show up as anonymous--which I thought we disambiguate by IP address? However, we only have 1 anonymous user from yesterday and one for today. So, maybe this disambiguation is broken... or am I missing something?

![image](https://user-images.githubusercontent.com/1621749/64789044-851a1d00-d528-11e9-90a1-d43caa490cbb.png)

**Comment by misaugstad** [comment]
closing via #1920
