### ISSUE TITLE
Prevent laptop users from going to mobile validation page

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1917]
It doesn't look great
![mobile-validate-laptop](https://user-images.githubusercontent.com/6518824/66157102-eb4e0900-e5d7-11e9-825b-3593158a7e84.png)

**Comment by kumararoosh** [comment]
I'm not sure on how to completely prevent laptop users from going to the mobile site, however, my current solution simply redirects any laptop users to the validate page. A full prevention would require combining both the mobile and the laptop validation pages or redirecting before the mobile validation page even loads.

**Comment by misaugstad** [comment]
So I know that on the backend we can redirect users to a different page before the page loads. You should be able to see this in any of the files in the app/controllers directory if you search for "Redirect". I think the question is how to know whether the request is mobile from the backend instead of the frontend!

**Comment by misaugstad** [comment]
closing via #1988
