### ISSUE TITLE
For labelmap, add in validation support

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1930]
For labelmap, be able to validate labels on pop-up.

Also, for the map itself, be able to selectively filter labels shown so that you can choose from:
- All labels with at least one positive validation
- All labels with at least one negative validation
- All labels with at least one unsure
- All labels

Something like that?

Builds on: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1166

**Comment by misaugstad** [comment]
closing via #1938
