### ISSUE TITLE
Be able to minimize legend in /labelmap

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1931]
The legend is huge and can get in the way--let's have a lil minimize function that allows us to minize it in bottom left

![image](https://user-images.githubusercontent.com/1621749/67336694-a6343d00-f4da-11e9-9805-7e1be6c99750.png)

Something like this comment box in Fusion 360:

![image](https://user-images.githubusercontent.com/1621749/67336806-d1b72780-f4da-11e9-80dd-174b76b80aac.png)

![image](https://user-images.githubusercontent.com/1621749/67336828-d8459f00-f4da-11e9-96df-8849a7094893.png)

**Comment by misaugstad** [comment]
Okay here's a look at where I'm at with minimizing the legend right now. I should make the button look more attractive. Any other suggestions?

![legend-minimize-1](https://user-images.githubusercontent.com/6518824/68325731-dc4af280-007e-11ea-9f15-7a39563f22e4.gif)

**Comment by jonfroehlich** [comment]
Looks good to me! Though the gif is super low-res so can't really see the iconography you're using.

**Comment by misaugstad** [comment]
Okay I copied the button from elsewhere on the site (closing the sign-in modal), so here's what it looks like now.
![legend-minimize-1](https://user-images.githubusercontent.com/6518824/68326589-95f69300-0080-11ea-9719-944ed521a0c8.png)
![legend-minimize-2](https://user-images.githubusercontent.com/6518824/68326501-68a9e500-0080-11ea-83b5-f4e02eb9e483.png)

**Comment by misaugstad** [comment]
I don't like the mapbox logo down there. I could try to see if I could move it to the bottom right

**Comment by misaugstad** [comment]
Ok I think this looks pretty good

![legend-minimize-3](https://user-images.githubusercontent.com/6518824/68328391-0a7f0100-0084-11ea-8c68-61ec44e67c25.png)
![legend-minimize-4](https://user-images.githubusercontent.com/6518824/68328393-0bb02e00-0084-11ea-8de1-d10dd757a865.png)

**Comment by misaugstad** [comment]
closing via #1953
