### ISSUE TITLE
Change city titles to white hyperlinks (rather than yellow)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1949]
Yellow is hard to see:

![image](https://user-images.githubusercontent.com/1621749/68253150-144d2980-ffdc-11e9-8f39-3070c58bf7c4.png)

![image](https://user-images.githubusercontent.com/1621749/68253132-08616780-ffdc-11e9-8b5a-3b5f532f63bf.png)

**Comment by misaugstad** [comment]
closing via #1955
