### ISSUE TITLE
Labelmap pop-up: Label type appears blank for "Other" label type

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1960]
As another suggestion, the title header of the pop-up could have the Label Type displayed- its more visible. Currently, the title "label" doesn't serve any purpose.
![labelmap_popup](https://user-images.githubusercontent.com/2873216/68446926-05f53e00-0193-11ea-8172-6684c24f5fbf.png)

**Comment by misaugstad** [comment]
closing via #1961
