### ISSUE TITLE
I've started 'twice' in Columbus on test server and get DC as first mission

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1964]
And both times, I got thrown here to start, which was confusing because the 'uh oh, you're quite far away from the audit route' pops up. Can we take the tutorial mission out of regular missions now? 

![image](https://user-images.githubusercontent.com/1621749/68789226-e7ab9a00-05f9-11ea-8dfa-8127fc266ff3.png)

**Comment by misaugstad** [comment]
closing via #1970
