### ISSUE TITLE
Remove Maryland from 'Designed and Operated By...' footer

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1965]
Now that we no longer have anyone on the team from Maryland (@tongning graduated), we should remove Maryland from the footer.

https://github.com/ProjectSidewalk/SidewalkWebpage/search?q=operated+by+the&unscoped_q=operated+by+the

![image](https://user-images.githubusercontent.com/1621749/68789041-75d35080-05f9-11ea-8b6f-4ac489ae7e04.png)

**Comment by misaugstad** [comment]
closing via #1966
