### ISSUE TITLE
Ratings Not Being Saved Bug

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#197]
I've never seen this before but it looks like my severity ratings are suddenly not being saved--I can't tell if this is a backend problem (e.g., the ratings actually are not being saved) or a UI problem (the ratings are being saved but not shown correctly).

I took a video: https://youtu.be/AjdtlMcmjn0 (still uploading, hopefully will be done soon).

Oh and I opened the console in Chrome and there was nothing in there...

**Comment by kotarohara** [comment]
I have no clue why it is happening. I'll look into it when I start coding again.

**Comment by kotarohara** [comment]
Fixed

**Comment by jonfroehlich** [comment]
What was the issue?

**Comment by kotarohara** [comment]
The keyboard shortcuts were not implemented correctly.
