### ISSUE TITLE
neighborhood complete incorrect in columbus

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1973]
I'm getting the neighborhood complete message in Columbus even though we've only finished 2% of downtown.

![neighborhood-complete-columbus](https://user-images.githubusercontent.com/6518824/69386985-2f28ca80-0c79-11ea-9495-2c9cffd48a05.png)

**Comment by jonfroehlich** [comment]
Yikes!

**Comment by misaugstad** [comment]
Okay I figured out the issue! I ran my script that checks for streets that have no imagery last week, and I marked those streets as deleted in the database. But I was actually in the middle of auditing one of those streets, so when I tried to audit again this is the error that showed up! Fixed the issue so I'm not getting this error anymore.

**Comment by jonfroehlich** [comment]
So this was just on your localhost?

**Comment by misaugstad** [comment]
No this was on the test server.

**Comment by misaugstad** [comment]
I just had to mark the street as `deleted = FALSE`, load the audit page and jump to a new street, then mark the street as `deleted = TRUE` again.
