### ISSUE TITLE
After finishing three validation missions on Columbus, interface hung on 'start an exploration mission'

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1977]
![image](https://user-images.githubusercontent.com/1621749/69746376-febdb200-10f8-11ea-8e1a-3003f62da82c.png)

Also, I thought the new code recently pushed no longer forced a mission path but rather enabled users to choose either to continue validating or to start exploring...

**Comment by misaugstad** [comment]
I didn't realize the webhook for Columbus wasn't set up yet when I pushed out the new version last night, so Columbus still has the old version right now. Emailing Jason about it now. Not sure why we are hanging here though... Might be an edge case since we don't have very many labels to validate...

**Comment by misaugstad** [comment]
Actually not emailing Jason, just making a small edit to the README to trigger the webhook. I needed to test the webhook anyway, so this is a good chance to do so.

**Comment by jonfroehlich** [comment]
Hasn't happened again to me and now I see that the new mission select code is there (and working from my testing)...

**Comment by jonfroehlich** [comment]
Hmm, now it's hanging after completing an initial set of 10 validations. If I had to guess, it's because there are no more validations available.

![image](https://user-images.githubusercontent.com/1621749/69812026-41889400-11a4-11ea-9667-d123740fe993.png)

**Comment by misaugstad** [comment]
closing via #1980
