### ISSUE TITLE
Anyway to Quickly Tell What Version Deployed to Production Server

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#202]
Is there any easy way to tell what version of Project Sidewalk is deployed on production server?

For example, maybe the footer on the landing page has a last updated date or a version number or something.

Obviously, this is a low priority but I'd like to know what "version" I am using when I'm testing the site.

**Comment by jonfroehlich** [comment]
I'm guessing the site has not been updated because the mission dialog is still broken (e.g., miles audited in this mission = neighborhood miles audited so far--but this is wrong):

![image](https://cloud.githubusercontent.com/assets/1621749/17464612/c2fcb3f6-5cb0-11e6-9ffa-540a168b337d.png)

**Comment by jonfroehlich** [comment]
I still think this would be useful to me. I can see that you haven't pushed some new changes yet (e.g., the Likert scale bar is still the old one) but I can't tell if you fixed the comment uploading and the keyboard rating thing.

Can you just add a deployment timestamp (date & time) to footer:

![image](https://cloud.githubusercontent.com/assets/1621749/17855879/e22bd38a-6848-11e6-9a34-d1c601ed5958.png)

**Comment by kotarohara** [comment]
Ok. Done. 

![cursor_and_project_sidewalk_-_audit](https://cloud.githubusercontent.com/assets/612263/17863383/793f2baa-6867-11e6-9bba-9be390a5feac.png)
