### ISSUE TITLE
Add Liga Peatonal Logo to Mexico City

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2022]
Add the Liga Peatonal logo to http://sidewalk-cdmx.cs.washington.edu. Need to figure out where. 

![Logo LP](https://user-images.githubusercontent.com/1621749/74764096-e52e9100-5235-11ea-860c-1d8c2eabac39.png)

We could have something like this except for "collaborators" or "brought to you by":

![image](https://user-images.githubusercontent.com/1621749/74764197-26bf3c00-5236-11ea-8806-7ca80141d2df.png)

In fact, here's a quick sketch/mockup. 
![image](https://user-images.githubusercontent.com/1621749/74764378-70a82200-5236-11ea-86bb-bd83c222a482.png)

[BroughtToYouBySection.pptx](https://github.com/ProjectSidewalk/SidewalkWebpage/files/4220880/BroughtToYouBySection.pptx)

**Comment by gari01234** [comment]
![grafik](https://user-images.githubusercontent.com/50057640/74834837-7ed06e00-531c-11ea-977b-e17e667d7972.png)
:grin::grin: Looks great!

**Comment by misaugstad** [comment]
closing via #2033
