### ISSUE TITLE
Deploy and Run in Microsoft Azure

### ISSUE THREAD

**Issue by mohammadshaeri** [ProjectSidewalk/SidewalkWebpage#2028]
Has anyone experience of running the project in Microsoft Azure?
I created the image with Azure DevOps and made container instances. then it's created but is in waiting status and is not running.
thank you in advance

**Comment by misaugstad** [comment]
I don't believe I've heard of anyone attempting to set this up using Azure.

**Comment by misaugstad** [comment]
Screenshots and such might be useful! It may not necessarily be an issue related to running in Azure

**Comment by jonfroehlich** [comment]
Closing because OP never responded.
