### ISSUE TITLE
Street Segment Not Marked as Walked Even Thought it Was Walked

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#203]
About ~1 month ago, I audited this street segment. I just logged in today to test out the system a bit and I was routed along a long street that I thought was familiar--I checked the dashboard and, in fact, it's a street that I already audited but was not marked as walked. You can tell this because you can see labels that I applied but the street is does not have the gray line.

Here's the dashboard view with a red outline on the segment that I am currently walking.
![image](https://cloud.githubusercontent.com/assets/1621749/17464436/92e56572-5cac-11e6-897d-fb311444bde0.png)

Here's a screenshot of the GSV audit view:
![image](https://cloud.githubusercontent.com/assets/1621749/17464444/b2e48aec-5cac-11e6-903a-eb063abaef77.png)

(Those labels shown in the top-down map are labels I applied during this audit--I have seen no labels from my previous audit).

**Comment by jonfroehlich** [comment]
You can tell that this route is a super long street segment so maybe that has something to do with it?

**Comment by jonfroehlich** [comment]
OK, it looks like it shows up as audited in the mission complete dialog:

![image](https://cloud.githubusercontent.com/assets/1621749/17464502/456018d6-5cae-11e6-9b1d-0c4e19639fb2.png)

But I just reloaded the dashboard and that segment still shows as incomplete:

![image](https://cloud.githubusercontent.com/assets/1621749/17464507/622729a0-5cae-11e6-905c-d59c22b69862.png)

Which means I can never finish this neighborhood. I'm going to use the dashboard to select a new audit neighborhood until this bug is fixed.

I think this bug is worth investigating to see what the cause is--hopefully this is just an isolated incident but if it is more pervasive it would prevent others from completing neighborhoods as well.

**Comment by jonfroehlich** [comment]
@kotarohara, any updates on this?

**Comment by kotarohara** [comment]
No, I have not looked into this yet. I will look into this this weekend.
