### ISSUE TITLE
Changes in .html files not being displayed locally

### ISSUE THREAD

**Issue by leonli33** [ProjectSidewalk/SidewalkWebpage#2030]
When making edits to .html files, the changes made are not recognized on the local host web page. However, the changes are recognized for both Scala and JS files. Therefore, to see a change in a .html file, an edit to a JS or Scala file is required.

In the terminal, I get this message when I edit a .html file, specifically the index.scala.html file located in the 'app/views' directory:
![image](https://user-images.githubusercontent.com/31671708/76130888-3920d000-5fc1-11ea-84e3-14aa72ac0b1a.png)

However, when reloading the page in my local environment, the edit I made cannot be seen.

In order to see my change to the .html file, I have to edit a JS file. Doing so gives me this message in the terminal:
![image](https://user-images.githubusercontent.com/31671708/76131027-ba786280-5fc1-11ea-9e55-2d176f9c269f.png)

After this message. I can reload the page and all changes can be seen. Does anyone know why this is happening?

**Comment by misaugstad** [comment]
Never seen/heard of this before!

>In order to see my change to the .html file, I have to edit a JS file.

Does changing a non-html Scala file also cause the page to update?

Could you also note your OS?

**Comment by jonfroehlich** [comment]
I haven't seen this either. Closing for now unless @leonli33 wants to provide more details (happy to hear more and try to address!).
