### ISSUE TITLE
No mini map in tutorial

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2049]
One user came across a bug where there was no mini map in the tutorial! I've never seen this before and haven't been able to reproduce. Documenting it here in case it ever pops up again.

![no-mini-map-tutorial](https://user-images.githubusercontent.com/6518824/77951540-1495dc00-727f-11ea-834b-752d42a173c1.png)

**Comment by jonfroehlich** [comment]
Curious what browser they were using. I've never seen this either. Closing until we see it again (to keep our Issues manageable).
