### ISSUE TITLE
Translate results page and user dashboard

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2052]
Both these pages have very little text and are prominently featured on the navbar, so it is definitely worth the effort to add translations for them.

Also when I update the text for these, I should fix the two places where I accidentally wrote "validir" instead of "validar".

**Comment by gari01234** [comment]
https://docs.google.com/document/d/1nkBRJ2BDk6M6scgm596d6BeEYqHXb3VQeFgTMOOB-6o/edit?usp=sharing

**Comment by misaugstad** [comment]
closing via #2082
