### ISSUE TITLE
Pages loading without translations

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2054]
Rarely the audit (and maybe validation) page(s) can load without loading most of the translations. The translations that are in the HTML are there, but the ones that are inserted via JavaScript are not there. Example below.

![unnamed](https://user-images.githubusercontent.com/6518824/78398021-2fca5980-75a7-11ea-8311-4d9dff0c4bc2.png)

The code I wrote is supposed to wait for the translations to load before fully loading the webpage, so I need to take a closer look and see if I did something wrong.

**Comment by jonfroehlich** [comment]
I'm curious if we'll see this again with additional deployments in other languages. Something for @maartensukel and team to watch out for.

**Comment by misaugstad** [comment]
Just noting that I haven't seen this in a very long time. I'll consider closing this at some point soon!

**Comment by misaugstad** [comment]
I've made some changes over the past few months to when we set up translations, and I believe that this race condition should no longer be an issue!
