### ISSUE TITLE
Are the non-slick DAO implementations necessary?

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2064]
Do some investigating to see whether the non-slick DAO implementations are needed in the project.

**Comment by ThatOneGoat** [comment]
Ok, so it seems that the PasswordInfoDAO (the non-slick version) and the AuthTokenDAOImpl I wrote both aren't necessary, they're just remnants of some base silhouette project. However, the UserDAOImpl is a little different since the actual class itself doesn't use slick but the companion object does use slick.

I think we have two options: We can remove the PasswordInfoDAO and AuthTokenDAOImpl cause they are unneeded and we can keep the UserDAOImpl as is with the UserDAOSlick, or remove the PasswordInfoDAO, AuthTokenDAOImpl, and UserDAOImpl, and move the companion object in USerDAOImpl to UserDAOSlick.

**Comment by misaugstad** [comment]
I think that trying to move the companion object over would be good. Hopefully it will either be pretty easy, or you'll realize quickly that there was a good reason for it to be in USerDAOImpl instead!

**Comment by misaugstad** [comment]
closing via #2077
