### ISSUE TITLE
Make LabelMap's existence more obvious and accessible to users.

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2069]
As @gari01234 points out, we have this nice LabelMap feature but it's not highlighted or accessible from our landing page or top-level menu. I think this is because LabelMap fails on large datasets like Seattle but I think it would be nice to include it for smaller cities like Newberg, CDMX, etc.

![image](https://user-images.githubusercontent.com/1621749/80282348-cdf0a180-86c5-11ea-82f0-a350eb9d698e.png)

**Comment by misaugstad** [comment]
That's correct that we haven't highlighted it because it won't work on larger datasets. But that's a good point. Very little reason not to include it for smaller cities/datasets. My only concern is it being confusing for users in cities where we end up expanding and the dataset becomes too large. Then if we remove the link to this map it might be confusing.

**Comment by jonfroehlich** [comment]
Let’s just cross that bridge when we come to it? And release it for now?

**Comment by misaugstad** [comment]
I agree.

**Comment by misaugstad** [comment]
Do you like the name "Label Map"? Or would you want the link to it to say something different?

**Comment by jonfroehlich** [comment]
I like Label Map. Maybe ask the team to see if they have better ideas?

**Comment by misaugstad** [comment]
@jonfroehlich any qualms here? Some of them (particularly the audit page) look a bit busy. I think it's probably fine though.

![labelmap-navbar-landing](https://user-images.githubusercontent.com/6518824/80433879-19b16f80-88ad-11ea-837a-9b7e73eceb9d.png)
![labelmap-navbar-audit](https://user-images.githubusercontent.com/6518824/80433883-1b7b3300-88ad-11ea-8f44-15338c26a759.png)
![labelmap-navbar-validate](https://user-images.githubusercontent.com/6518824/80433885-1cac6000-88ad-11ea-869d-5d4fb576bbc7.png)

**Comment by jonfroehlich** [comment]
Good for now. In future, maybe See Results can be a drop down

**Comment by misaugstad** [comment]
closing via #2076
