### ISSUE TITLE
'Accessible' Social Distancing Sidewalk Width Map

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#2070]
Recently, an interactive map came out showing sidewalk width safe for social distancing: https://www.sidewalkwidths.nyc/

It would be interesting to add Project Sidewalk data to the mix to make an accessible version of it: https://twitter.com/manaswisaha/status/1254076027094982656
New Yorker article talks about things like obstacles creating issues and we have that data and more!

Now, [Toronto](https://sharedstreets.github.io/sidewalkwidths-toronto) is also in the mix with more cities to come: https://twitter.com/emilyeros/status/1253842592481107970?s=21

This would be great undergrad project!

NYC Code: https://github.com/meliharvey/sidewalkwidths-nyc

**Comment by jonfroehlich** [comment]
An interesting idea but beyond the scope of our current work. Closing for now.
