### ISSUE TITLE
Navbar collapses incorrectly

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2081]
Navbar is collapsing incorrectly (especially on the admin pages)

Here is what it looks like on the develop branch (incorrect):
![Screen Shot 2020-04-28 at 12 30 29 AM](https://user-images.githubusercontent.com/37346427/80547278-abcc7d00-896c-11ea-8acc-d6e3071684c8.png)

Here's what it looks like on the admin page on develop (incorrect):
![Screen Shot 2020-04-28 at 12 34 44 AM](https://user-images.githubusercontent.com/37346427/80547299-b555e500-896c-11ea-9f9e-59d0c87a5a8b.png)

Here's what it looks like on the current deployed Project Sidewalk website (correct):
![Screen Shot 2020-04-28 at 12 30 36 AM](https://user-images.githubusercontent.com/37346427/80547333-c43c9780-896c-11ea-8d22-3ed795f07cff.png)

**Comment by ThatOneGoat** [comment]
I forgot to mention that these are all screenshots taken at full screen (so the first image I showed was incorrect since it shouldn't be collapsed during full screen)

**Comment by misaugstad** [comment]
@ThatOneGoat what is the resolution of the screen you're using? The landing page looks fine for me when full screen.

I was actually able to reproduce the problem on the admin page on the production servers too. Not at full screen, but when I decrease the width a bit I can get that bug.

**Comment by ThatOneGoat** [comment]
1440 x 900

This was happening for me on the landing page in the develop branch. Master (and production) is currently working fine for me as well

**Comment by ThatOneGoat** [comment]
Wait actually that's strange. It's back to being normal again for the landing page... 

But the admin page is still a little wonky regardless for me like you said

**Comment by misaugstad** [comment]
closing via #2184
