### ISSUE TITLE
API Page Optional Parameters Formatting

### ISSUE THREAD

**Issue by MattJ12** [ProjectSidewalk/SidewalkWebpage#2084]
On the API page for each accessibility format type there is an optional parameters section.  For the severity parameter, you can only pass an integer so it should just say `severity=[int]`, not `severity=[int|string]`.  Also, for the filetype parameter there should be square brackets around what parameter types you can pass like this: `filetype=[string]`.  The filetype parameter used to be like this: `filetype=csv|geojson` but I think it makes more sense based on how the `severity` parameter is specified to just do `filetype=[string]` to convey the type, not content, of the parameter.  Also, for the Access Attributes API in the paragraph describing optional parameters there should be a space before the start of the third sentence.

**Comment by misaugstad** [comment]
Ahh, when we were talking earler, I forgot that you can pass in "none" for the severity parameter to get labels that have no severity rating. So `severity=[int|string]` still makes sense. But you're right that switching to `filetype=[string]` should happen. Also yes the typo should be fixed :)

**Comment by misaugstad** [comment]
closing via #2141
