### ISSUE TITLE
Add lucha libre mask version of logo to CDMX server

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2086]
![ProjectSidewalk_cdmx 2](https://user-images.githubusercontent.com/6518824/80768693-ec103480-8aff-11ea-8c72-d1c47fff14fd.jpg)

**Comment by misaugstad** [comment]
Now that we are setting up a server in SPGG, include it for that city as well. You can see how we have different images for different servers by looking at the skyline on the landing page.

**Comment by misaugstad** [comment]
@MattJ12 can you edit the image to be the same as the normal logo, just with the lucha libre mask?

So make the background transparent, remove the link and the additional logos, and crop so that there's no extra border anywhere. I would also say to compress to make the file size smaller, even if we lose some resolution. We want the landing page to load as quickly as possible. It could still be a slightly higher res than the current one, but right now the file size is 20x bigger.

You may find it easier to just copy the mask onto the old logo as well.

**Comment by MattJ12** [comment]
> @MattJ12 can you edit the image to be the same as the normal logo, just with the lucha libre mask?
> 
> So make the background transparent, remove the link and the additional logos, and crop so that there's no extra border anywhere. I would also say to compress to make the file size smaller, even if we lose some resolution. We want the landing page to load as quickly as possible. It could still be a slightly higher res than the current one, but right now the file size is 20x bigger.
> 
> You may find it easier to just copy the mask onto the old logo as well.

Just updated.

**Comment by misaugstad** [comment]
closing via #2121
