### ISSUE TITLE
Audit Mission Complete Screen Mission Labels

### ISSUE THREAD

**Issue by MattJ12** [ProjectSidewalk/SidewalkWebpage#2088]
For auditing, on the mission complete screen under mission labels section it says `mission.ramp` and I think it is supposed to say `Missing Curb Ramp`.

**Comment by misaugstad** [comment]
Nice find, thanks @MattJ12 !

**Comment by misaugstad** [comment]
Whoops sorry @rpechuk ! Looks like I forgot I had created this issue and documented it again in #2112 and then fixed it in #2125 ! I'll assign you a new task :grin:
