### ISSUE TITLE
Slow Compile Times

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2099]
One thing I (and a few other researchers like @kumararoosh ) have noticed is that the compile-time (for both `npm start` and when the sbt catches a file change while the server is up) upon running for the project is quite long (around the order of 2-5 minutes for one scala file). Some investigation may be needed to see why cpu usage isn't as optimized, etc.

**Comment by kumararoosh** [comment]
One solution is to give docker access to all of the cores in your system, which decreases the compile time significantly (takes 10 seconds instead of a minute).

**Comment by misaugstad** [comment]
According to [this stackoverflow post](https://stackoverflow.com/questions/37871540/how-many-cpus-does-a-docker-container-use), the number of CPUs is not limited by default on Linux at least. But if you're using Windows/Mac then you should check the Docker settings in the GUI to see if any CPU limits are being set.

**Comment by ThatOneGoat** [comment]
For Mac users, you can get a massive speed up in compile time by adding the :delegated flag to docker-compose.yml, as stated by PR #1474 .
Here is the docker documentation on how it works, but what it basically does is it just gives the docker container a mor authoritative view of the file system in mac: https://docs.docker.com/docker-for-mac/osxfs-caching/ 
With that being said, it may be worthwhile to see if there are similar performance tuning flags for Windows or Linux

**Comment by kumararoosh** [comment]
In order to give more resources to docker on Windows:
1. Enable use of Hyper-V on Windows [(follow this tutorial)](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v)
2. Open the docker dashboard, and click the settings gear on the top right
a. If the settings is disabled, sign in to docker
3. Go to resources &rarr; advanced.
4. Slide the CPU bar all the way to the right.
a. This will increase the speed of compile times. Docker will only use all cores during compile, so there is no need to worry about the performance of other programs.

**Comment by misaugstad** [comment]
Awesome, thanks @kumararoosh ! Could you add this to the Docker troubleshooting wiki as well?

**Comment by misaugstad** [comment]
And what kind of speedup did you see from this?

**Comment by kumararoosh** [comment]
I saw a change from about 5 min to less than 30 seconds

**Comment by misaugstad** [comment]
incredible!! great work figuring this out. would love to hear from other Windows users if this helps them as well

**Comment by jonfroehlich** [comment]
Looks like @kumararoosh just added this to the [wiki](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Docker-Troubleshooting#slow-compile-time-on-windows). Closing for now.

(And I plan to try it as well!)

**Comment by ThatOneGoat** [comment]
Just a note, HyperV only works for those with Windows Pro. Otherwise you will have to use WSL2.

**Comment by jonfroehlich** [comment]
@ThatOneGoat: you should update the wiki to convey this info.
