### ISSUE TITLE
Current Mission progress bar goes down as the user steps backward

### ISSUE THREAD

**Issue by Soben713** [ProjectSidewalk/SidewalkWebpage#211]
I'm not sure how I ended up here, but as you can see in the first picture, the caption states that I should walk straight. But after I do, mission's progress bar resets to 4% (second picture).

I guess this happened because I didn't complete some parts of the route and came back to the starting point. It is probably not a bug, but still I think it is a usability problem and there should be a way to inform the user that s/he is in the wrong place.

<img width="1076" alt="screenshot 2016-08-13 18 37 22" src="https://cloud.githubusercontent.com/assets/1576529/17650938/b5018286-6228-11e6-8591-ed0177ebf8b3.png">
<img width="1041" alt="screenshot 2016-08-13 18 37 34" src="https://cloud.githubusercontent.com/assets/1576529/17650939/b7ccc0b6-6228-11e6-8226-2fc7ab9fe387.png">

**Comment by jonfroehlich** [comment]
@kotarohara, do you know what's going on here? This definitely seems like a bug. The progress bar should only update when the user is progressing along the red path, right?

@Soben713: I've never seen this problem before and I've completed ~50 missions :). So, can you provide a bit more detail on what you were doing when this happened?

**Comment by kotarohara** [comment]
Ok, yeah. It didn't happen before, but I see it is happening now. I suppose the progress bar is using the current position of the user instead of the furthest point that the user have traveled to.

**Comment by jonfroehlich** [comment]
@kotarohara, OK. Yah, let's fix that.

@Soben713. Nice find! Thank you very much for contributing this.
