### ISSUE TITLE
Example image popups in wrong location on validation

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2115]
Here is what it looks like for me:
![example-location-off-1](https://user-images.githubusercontent.com/6518824/82609830-222a5c80-9b72-11ea-863f-07b03a953cb4.png)
![example-location-off-2](https://user-images.githubusercontent.com/6518824/82609916-5140ce00-9b72-11ea-86c8-b118976dedcc.png)
![example-location-off-3](https://user-images.githubusercontent.com/6518824/82609919-5271fb00-9b72-11ea-9b3c-7e4b51ce21fb.png)
![example-location-off-4](https://user-images.githubusercontent.com/6518824/82609922-53a32800-9b72-11ea-9809-649b9f84580f.png)

**Comment by rpechuk** [comment]
![image](https://user-images.githubusercontent.com/39865166/85779750-c6a33f80-b6d8-11ea-86d5-fd8c5d9d30a3.png)
![image](https://user-images.githubusercontent.com/39865166/85779868-e3d80e00-b6d8-11ea-852d-ed36846832f6.png)
![image](https://user-images.githubusercontent.com/39865166/85779903-ed617600-b6d8-11ea-829d-f5bc408fbbeb.png)
![image](https://user-images.githubusercontent.com/39865166/85779924-f2262a00-b6d8-11ea-915a-ae57dde5cea4.png)
Updated UI pictures^^^

**Comment by misaugstad** [comment]
closing via #2151
