### ISSUE TITLE
Zooming in/out distorts the placement of the arrows in tutorials 

### ISSUE THREAD

**Issue by Soben713** [ProjectSidewalk/SidewalkWebpage#212]
There are some problems with the placement of the arrows to which the user should add a label in the tutorial. This specially happens when you zoom in/out

<img width="812" alt="screenshot 2016-08-13 18 19 02" src="https://cloud.githubusercontent.com/assets/1576529/17651075/824a0ca6-622c-11e6-8537-a1244eb58c3a.png">
<img width="834" alt="screenshot 2016-08-13 18 19 14" src="https://cloud.githubusercontent.com/assets/1576529/17651076/86058898-622c-11e6-9881-9d4792e66f6c.png">

.

**Comment by jonfroehlich** [comment]
Interesting. I'd not seen this before. I suppose it's related to Zoom In/Zoom Out as you say. I think the easiest fix would be to disable Zoom In/Zoom Out during the tutorial.

**Comment by jonfroehlich** [comment]
@kotarohara, can you please respond about this issue and your perceived severity of the problem. @Soben713 seems to indicate that this only happens when you zoom in and out in the tutorial.

**Comment by kotarohara** [comment]
Yeah, I figured the arrows in the tutorial does not take into account of zooming. I think we can just disable zooming.

**Comment by jonfroehlich** [comment]
@kotarohara, great, I agree!
