### ISSUE TITLE
Ignore validations from users manually marked as "low quality"

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2128]
There are some turkers who intentially audit/validate in bad faith, who add junk data into the system. For such users, I set the `high_quality_manual` column in the `user_stat` table to false. We are correctly ignoring their audits when running clustering & such, but we are not ignoring their validations right now.

Places I can think of where we should ignore their validations:
1. Prioritization of validations; a label with a junk validation should still be validated
1. /labelmap popups; we list validation counts, and we shouldn't include the junk ones
1. Stats for users on the admin page; junk validations are typically 100% agree which inflates these stats

This is just what I could think of off the top of my head. When making these updates, one should look through the code to see if validations are used anywhere else and address that as well.

**Comment by misaugstad** [comment]
Updating this to say that we want to ignore from all low quality users, not just the ones manually marked as low quality. We're going to be updating the heuristic for "low quality" data to be based on accuracy, so I feel better about excluding the data from all low quality users now.

**Comment by jonfroehlich** [comment]
Just bumping this now that you've done: https://github.com/ProjectSidewalk/SidewalkWebpage/pull/3024

Seems like they are related?

**Comment by misaugstad** [comment]
Nice find! I had lost track of this issue. It's actually a duplicate of #2755 which is better written, so let's keep that one.

There are two bullet points in #3013 that have yet to be implemented, and they each have their own ticket. #2755 is one of them!
