### ISSUE TITLE
Bug In Using Keyboard For Labeling

### ISSUE THREAD

**Issue by Soben713** [ProjectSidewalk/SidewalkWebpage#213]
When using keyboard numbers to specify a label's significance (passable/not passable) the corresponding radio-button gets selected but it is not saved. I'm using Chrome v52.

**Comment by jonfroehlich** [comment]
This is a duplicate of https://github.com/ProjectSidewalk/SidewalkWebpage/issues/197.

I believe it was fixed. I'll let @kotarohara comment and close if it is.

**Comment by jonfroehlich** [comment]
@kotarohara, is this now fixed?

**Comment by kotarohara** [comment]
Yes, this is fixed.
