### ISSUE TITLE
For quality analysis, update validation queuing algorithm to prioritize users with low numbers of validations received

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2139]
According to my estimates, 194 of 627 users have not yet received 10 validations of their labels. We've discussed the validation queuing algorithm at length in the past but I can't remember how it works :) In short, I recommend that we modify the queuing algorithm to prioritize users with < 20 validations (or some threshold like that). This will help with quality analysis.

```
178/898 users (19.8%) never completed even one mission. Removing them from analysis.
194/627 users (30.9%) have not received the min num of validations of 10. Removing them from analysis.
We filtered out 525/898 users (58.46%)
373 total users remain across the 4 cities
```

**UPDATE:** OK, this isn't as bad as I thought because 151 of these 194 (78%) never even supplied 10 labels—so they wouldn't be able to reach the min num of validation threshold (there aren't even 10 labels to validate!). But still, this means that 41 users have yet to receive the minimum number of validations... not sure how many of these are 'no sidewalk.'

```
178/898 users (19.8%) never completed even one mission. Removing them from analysis.
151/627 users (24.1%) have not provided the minimum number of labels of 10. Removing them from analysis.
41/428 users (9.6%) have not received the min num of validations of 10. Removing them from analysis.
We filtered out 525/898 users (58.46%)
373 total users remain across the 4 cities
```

**Comment by misaugstad** [comment]
@jonfroehlich could you check how many that would be if you remove no sidewalk from the label count? Because we are basically doing this already. We are priotiziting users who have less than 10 labels validated (per label type). See PR #1787

**Comment by misaugstad** [comment]
ahh although also in that analysis, I filter out users who are manually marked as "low quality" whereas the prioritzation algorithm does not do that filtering right now. The issue for doing that is #2128

**Comment by misaugstad** [comment]
This was already implemented at the time that it was written :ok_hand:
