### ISSUE TITLE
UI Bug in Path Rendered in Google Minimap upon Returning to Mission through Choropleth

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2142]
When returning to a mission you were already in via the choropleth, sometimes, the path (line) that is rendered in the Google minimap of where you have audited/need to go is fully red even when you have already explored part of that mission.

Currently, I can't figure out how to reproduce the issue, so any evidence/repro steps are needed.

**Comment by misaugstad** [comment]
So the line was red, but were you placed in the middle of the street? Or were you placed back at the beginning of the street?

**Comment by ThatOneGoat** [comment]
In the middle of the street. It's like I had traversed through part of the mission, but instead of the path I already had audited through being green, it was still red.

**Comment by misaugstad** [comment]
Do you remember what happened when you took a step forward? Did the part you had already audited turn green? Did the mission completion jump up a significant amount? Were there labels on the mini map from your previous session or were they missing?

**Comment by ThatOneGoat** [comment]
Yeah, it returned to green. None of those other things happened.

**Comment by ThatOneGoat** [comment]
I managed to repro it again. I visited a mission I already completed part of, left to do some validation, then came back and the path I had already audited was still red in the minimap:
![Screen Shot 2020-06-26 at 1 53 00 PM](https://user-images.githubusercontent.com/37346427/85900341-84e7c700-b7b4-11ea-81d2-e7cd0bd9337f.png)

**Comment by misaugstad** [comment]
closing via #2174
