### ISSUE TITLE
Remove trash from parenthetical about temporary

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2145]
I agree with this user who suggests taking trash out as an example as a temporary obstacle:
![image](https://user-images.githubusercontent.com/1621749/85605330-e833f680-b606-11ea-9132-478989dd525e.png)

This is what they're referring to:
![image](https://user-images.githubusercontent.com/1621749/85605076-bb7fdf00-b606-11ea-8e53-da6dfb9ee7ed.png)

**Comment by misaugstad** [comment]
closing via #2146
