### ISSUE TITLE
Problems with logging in the tutorial

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2150]
This started out just as an issue for duplicate logging in the tutorial, but now I'm just going to include all the logging problems I find.

UPDATE: Okay, actually below when I say things are being logged "2 times" what I actually mean is "2^(n+1) times", where n is the number of times you placed a label in the incorrect location. And the tagging being logged 20 times is more like 10*2^(n+1) times. If you place a label in the wrong spot more than 8 times or so, you start to see a performance hit. By the time I placed 15 or so incorrect labels, I was getting a 10 second delay for any action I performed during the tutorial.

- [x] For any transition, `Onboarding_Transition` is being logged twice. Only needs to happen once.
- [x] When adding the wrong tag, `Onboarding_Transition` is logged anywhere from 16 to 22 times with the note "onboardingTransition:redo-tag-attribute-\*". This only needs to happen once (any time someone adds a new tag). This is probably happening n times per tag or something.
- [x] Similar to the previous point, No Sidewalk label requires two tags. After you place the first one `Onboarding_Transition` is logged over 20 times with the note "onboardingTransition:tag-attribute-6".
- [x] In the above two situations where the tag stuff is being labeled a bunch of times, the `ContextMenu_Close` action is also being logged once for every two `Onboarding_Transition` actions. I'm not sure if this is happening anywhere else, but it is happening when adding/removing tags at least. Most of the time this shouldn't be logged at all because the context menu remains open after adding a tag. I know that when you add the correct tag (and remove all incorrect tags) the context menu automatically closes for you. So it might have something to do with this.
- [x] ~When we log the action `KeyboardShortcut_TagAdded` we include the note "tagId:\*,tagName:\*", but when we log the action `ContextMenu_TagAdded` (the click version of that) our note includes the audit task ID "tagId:\*,tagName:\*,auditTaskId:\*". We don't need to log the audit task ID at all, there is already a column for that.~ -- I'm realizing now that the `auditTaskId` note doesn't matter in the tutorial, but it does matter outside the tutorial, since you can go back to an old label and edit it. So the note should be kept the same.
- [x] For most situations, if you do something wrong, you go to a "redo-X" state, and that is logged. But for some reason, placing a label in the wrong location is handled by a different function in Onboarding.js instead of having its own state. This also means that it isn't being logged as such. You can tell that an error was made because the "onboardingTransition:select-label-type-\*" note gets logged extra times. But it should really have its own state like the rest of the mistakes.

The original text of the issue:
>I'm trying to get together data from the tutorial logs and I'm seeing that every Onboarding_Transition action is being logged twice. And even worse, if you choose the wrong tag, the action is being logged 16 or more times. My guess is something like it's logging it 4 times per tag for some reason.

**Comment by misaugstad** [comment]
I also think that ContextMenu_Close is erroneously being logged a bunch of times when applying the wrong tag. I'll keep updating this issue with issues I find with the tutorial logging.

**Comment by misaugstad** [comment]
Wow this is worse than I could have imagined! Things are getting logged 2^(n+1) times, where n is the number of times you placed the label in the wrong spot before getting it right. That's for something like rating severity. Tags are being logged more like 10*2^(n+1) times.

**Comment by jonfroehlich** [comment]
😲🥺😩

**Comment by misaugstad** [comment]
@rpechuk note that I don't expect you to fix all of these issues in a single PR. If you are able to fix any such issue, please make a PR just for that fix, and we can work on this incrementally :) We can split into multiple issues too once we have more info on what's going wrong.

**Comment by rpechuk** [comment]
Hey just looking through this issue as I think I missed it when it was assigned and was working on different issues. I was wondering what out of the mentioned issues has been fixed (if anything) and what still needs fixing. I was also wondering where in the code we are calling functions to log "Onboarding_Transition" because I can't seem to find it and the deeper I go the more confused I get. Just so you know this is the issue I will be working on as i'm at a bit of a roadblock on the async PR and noticed this one is much older.

**Comment by misaugstad** [comment]
>Hey just looking through this issue as I think I missed it when it was assigned and was working on different issues. I was wondering what out of the mentioned issues has been fixed (if anything) and what still needs fixing

As far as I remember, none of the above have been fixed. I believe I assigned this to you because you had done a lot of work with the logging over the summer, so you had a better idea of what you were doing with it than most :wink: aaand then I pulled you onto the leaderboard issue because that was more pressing at the time.

I think the idea behind this issue is just to see if you can figure out what is going on with any of these logging issues. And if you figure one out, make a PR fixing that one, and then see if you can find another. I wouldn't try to fix all the bugs in one PR, and we may not be able to fix all of the bugs in a reasonable amount of time. But it's worth seeing what you can figure out, especially the ones that start to balloon the number of interactions being logged.

>I was also wondering where in the code we are calling functions to log "Onboarding_Transition" because I can't seem to find it and the deeper I go the more confused I get.

If you just search through the code base for "Onboarding_Transition" (it's ctrl-shift-f in intellij idea), you should find numerous references to it in `OnboardingStates.js`. They are all inside a "transition" function that is called whenever the onboarding transitions into that state. You can see the various places it gets called by looking for `state.transition` in `Onboarding.js`.

**Comment by rpechuk** [comment]
Sounds good i'll look into it! This is the issue i'm going to focus on the this week (then finals next week) and as much as I can between travelling for winter break.

**Comment by rpechuk** [comment]
In commit #2482 I fix the issue with logging `Onboarding_Transition` 2^(n+1)/ 10*2^(n+1) times in each transition
