### ISSUE TITLE
Update Mission Screens to make them more informative/educational, fun, and gamified :)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2152]
Our mission screens are a key opportunity to help motivate users but also to help them learn about sidewalk accessibility and correct/incorrect labeling behavior. I don't think we take advantage. 

For example, here's a current validation screen:
![image](https://user-images.githubusercontent.com/1621749/85859934-cbb4cd00-b772-11ea-8ea5-755ca21f7033.png)

And here's a quick mockup of a version aimed towards better informing our users:
![image](https://user-images.githubusercontent.com/1621749/85859973-dec79d00-b772-11ea-9f6a-6e05731a76d3.png)

There are lots of potential ways of doing this. For example, an alternative would be to randomly pick one *incorrect* example to show users for the target label type each time the mission screen is shown. This incorrect example would be curated from a small list of prepared images based on our [CHI2019 paper](https://makeabilitylab.cs.washington.edu/media/publications/Saha_ProjectSidewalkAWebBasedCrowdsourcingToolForCollectingSidewalkAccessibilityDataAtScale_CHI2019.pdf): 

![image](https://user-images.githubusercontent.com/1621749/85860170-3403ae80-b773-11ea-9c74-5a076b30f837.png)

And we'd explain that these are common user errors that we need to correct.

**Comment by misaugstad** [comment]
Here are some related issues... #1695 #1798 #234 #1838 #94 #1323

**Comment by jonfroehlich** [comment]
The next step would be to generate some mock ups and solicit feedback from the team. So, if someone wants to gain some user Interface design experience, This would be a great opportunity

**Comment by NityaVenkat** [comment]
Hi 

in case no one is currently working on this, i would like to volunteer

**Comment by jonfroehlich** [comment]
Sure. That would be great. Please use the tool first to get a sense of it and then post some rapid mocks for feedback!

Remember, we are trying to keep the user experience fun and supportive and gamelike!

**Comment by misaugstad** [comment]
@NityaVenkat yep the help on this would be greatly appreciated!! Also please check out the other issues I linked to above to get an idea of some of the things we might want to have included on these screens.

**Comment by NityaVenkat** [comment]
Trying to get some background here, so will the users be doing this on their mobiles since i saw posts that talks about maps and routes walked. Or is this just going to be informational guide screens? 

I did see the link to this application somewhere, but i'm unable to locate it now. Can someone just post the link to the current version here.

**Comment by jonfroehlich** [comment]
The application is [here](https://sidewalk-sea.cs.washington.edu/) and is only for desktops/laptops (one small part is available on mobile). Please spend some time using the app (~maybe 3 auditing missions and 3 validation missions) and let us know if you have any more questions. Best way to explain Project Sidewalk is to use Project Sidewalk :) And you'll need in-depth understanding if you're going to be able to design new UX :)

**Comment by jonfroehlich** [comment]
I started collecting images that we could use to point out common "correct" and "incorrect" labeling activity:

- [Surface Problems](https://docs.google.com/presentation/d/1QfTEOF0sJXyaB_yvfy9oI1POOQrgysMaHcYaZsKgf7s/edit#slide=id.g9a614cbb06_1_0)
- [Obstacles](https://docs.google.com/presentation/d/1E8f_dqIIhjPCGI9z69FCxguwgtRcH92Y77-mV1xduOs/edit#slide=id.g9a569457c5_0_122)
- [Curb Ramps](https://docs.google.com/presentation/d/1HDIw0Nzy72s0HdIn4AMsZcIgE3C3YjemrJeCZkFDHxQ/edit#slide=id.g9a59c21d14_0_72)
- [Missing Curb Ramps](https://docs.google.com/presentation/d/1_INkXmBoafq7rHtUmDaR5n9TSrBA62g69WWfOVZWYWA/edit#slide=id.g9a639fa2a5_0_210)
- [No Sidewalks](https://docs.google.com/presentation/d/15TOCN0L09Yxcn8taUs92fMIqNxB9LDXvhB6A_56uKys/edit#slide=id.g9a65bc8ac2_0_117)

**Comment by jonfroehlich** [comment]
Here's an updated example mission screen. Is it glanceable enough? What do you think @gari01234? 

![image](https://user-images.githubusercontent.com/1621749/94021982-771cf000-fd69-11ea-85c7-45e6f041624d.png)

**Comment by gari01234** [comment]
> Here's an updated example mission screen. Is it glanceable enough? What do you think @gari01234?

looks great! Do you think it looks even glanceabler if you write the word "correct" in green and the word "incorrect" in red?

**Comment by jonfroehlich** [comment]
Good idea. I'll try that. Let's keep collecting correct/incorrect examples [in these slide decks](https://docs.google.com/presentation/d/1QfTEOF0sJXyaB_yvfy9oI1POOQrgysMaHcYaZsKgf7s/edit#slide=id.p) so we have good content for the mission screens.

**Comment by jonfroehlich** [comment]
Note that in addition to making these screens more educational, I also think they should be more fun and game'y, incorporating game design aspects like we are doing for the mission sidebar (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2260#issuecomment-705545794), user dashboard (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2281), and leaderboard (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2177).

So, for example, at the mission screens, we'll want to emphasize:
- how close they are to their next achievement related to that mission
- possibly their current rank (or some other aspect of leaderboard)
- overall stats
- and then some educational component

**Comment by jonfroehlich** [comment]
Just playing around with very early ideas here.

Original:
![image](https://user-images.githubusercontent.com/1621749/95656188-71d9d800-0ac1-11eb-85d4-12ff16f36ddf.png)

Very rapid draft of update:
![image](https://user-images.githubusercontent.com/1621749/95656204-86b66b80-0ac1-11eb-80a8-b1420d1e12fc.png)

Or something like this (a bit too busy):
![image](https://user-images.githubusercontent.com/1621749/95656217-9afa6880-0ac1-11eb-9c34-d964dbb1eb49.png)

**Comment by gari01234** [comment]
> 
> 
> Good idea. I'll try that. Let's keep collecting correct/incorrect examples [in these slide decks](https://docs.google.com/presentation/d/1QfTEOF0sJXyaB_yvfy9oI1POOQrgysMaHcYaZsKgf7s/edit#slide=id.p) so we have good content for the mission screens.

I updated all the slide decks. I will continue, from time to time, to upload more images. But I guess/hope we have enough for now ;)

**Comment by jonfroehlich** [comment]
I just reviewed the slide decks. They look great. I agree that we have enough for now.

**Comment by katrimana** [comment]
Hi all, I have made mockups for the validation mission start and end screens.

**Validation mission start screen:** 
- Focus on educating users the common mistakes in labels (inspired by how they are being presented in hackathons)
- The screen will only show 1 common error at a time so screen will not feel cluttered and user can at least get 1 takeaway
- Sequence of displaying the error can be either 1) showing the most common problem first or 2) random so user can learn a new thing each time (as suggested by Mikey)
- This layout can work for a variety of errors - see full range here: 
https://www.figma.com/file/m8eLiFP824qZ49QMJB8Hq1/Proj-Sidewalk-mission-screens?node-id=0%3A1

![image](https://user-images.githubusercontent.com/35394380/153472907-08092f3a-3e27-47bf-8ad3-ad88ea2d0415.png)
![image](https://user-images.githubusercontent.com/35394380/153473522-f8c90d33-2590-47f5-9a0c-f7929304e9fe.png)

- Also considered matching the pop up screen border color with the label color

![image](https://user-images.githubusercontent.com/35394380/153472940-dc07380b-a7a7-4e82-9b64-770e972784db.png)



**Validation mission end screen:**
- Make it more delightful with a gif (this gif is royalty free, or I can try to make something similar)
- Show how many more labels they have got to reach next level
- Taken out the summary stats of their labels in the mission (are those important?)

![Mission end](https://user-images.githubusercontent.com/35394380/153473224-e06dc853-a0f7-4736-bdcd-ca9b46351734.gif)

**Comment by jonfroehlich** [comment]
The team distilled mission start screens into three core principles:
> (1) **user direction** (e.g., giving a mission objective); (2) **user engagement** (e.g., making them feel excited, interested, engaged, empowered that they are helping change urban accessibility, etc.); (3) and **user education** (e.g., helping them learn more about urban design and improving their labeling/validating)

I think the mission completion screens are similar but maybe with additional focus on making people feel satisfied/gratified with the work that they're doing, helping show them a review of what they just accomplished, and highlighting how close they are to both personal (badges) and community (neighborhood completion) objectives.

**Comment by katrimana** [comment]
As discussed, for the mission start screens we'll have correct examples (in illustrations) and wrong examples (in images), and these will be displayed to the user on random. 
Figma link: https://www.figma.com/file/WIta6wAMpsnw9mAgKexlpk/Proj-Sidewalk-mission-screens?node-id=532%3A796

1. Layout for correct example screen (illustration)
- Will create versions for other label types once illustrations are finalized by David
![image](https://user-images.githubusercontent.com/35394380/173094802-29bfef8a-0d55-49c4-b7ca-33ac561b732a.png)

2. Layout for wrong examples (images)
- Would like to have feedback on the images chosen and the copy describing the images. 
- There are other backup images in the Figma file.
![image](https://user-images.githubusercontent.com/35394380/173095013-5e94379b-0db5-445d-a1f7-1c33358d9d50.png)
![image](https://user-images.githubusercontent.com/35394380/173095035-c0d34fa2-f8e9-4091-94f1-f20aef21e1c1.png)
![image](https://user-images.githubusercontent.com/35394380/173095060-c0f49eae-48a1-47cd-a5f2-2f50ee930f85.png)
![image](https://user-images.githubusercontent.com/35394380/173095091-0a544a38-01e3-44dd-bd3b-80db212afe70.png)
![image](https://user-images.githubusercontent.com/35394380/173095124-683e1eb7-5f59-4cef-95f2-aa03e975f1e6.png)
![image](https://user-images.githubusercontent.com/35394380/173095156-b4001883-d66b-4dac-a149-36bf193ad79c.png)
![image](https://user-images.githubusercontent.com/35394380/173095199-35f3f3d1-800b-4d6e-b041-91767ded9d6a.png)
![image](https://user-images.githubusercontent.com/35394380/173095223-b54cc7c9-64c7-42e1-a8b8-cfe04c3c37f5.png)
![image](https://user-images.githubusercontent.com/35394380/173095273-7e3e1496-a32f-4c64-8097-9b0140164db4.png)
![image](https://user-images.githubusercontent.com/35394380/173095302-a2c0be81-2ed0-4aef-a708-987cf4ddc5f7.png)
![image](https://user-images.githubusercontent.com/35394380/173095337-947bc891-7de7-43f8-bb14-c4bc10e1c444.png)

**Comment by jonfroehlich** [comment]
Overall, looks great!

There are a few images that are either incorrect or could be improved. For example, in the following case, this is actually a correct label because there is a height difference between the dirveweay and sidewalk and a curb ramp _is_ needed.

![image](https://user-images.githubusercontent.com/1621749/173109727-ec7d494b-9fff-4df6-85d7-f82407482516.png)

My other suggestion is that the pop-up that says "Wrong Label / Mark Disagree" is a wonderful area to catch the eye but I think we underutilize it. Rather than just saying "Wrong Label / Mark Disagree", I wonder if we could also have a bit of text about _why_ it's wrong. For example, "Driveways are not curb ramps" and then on the left sidebar we repeat this but more expansively and with greater detail.

Finally, when we show Daniel's illustrations, let's be sure to put the labels in appropriate spot. They should be more like this (and you'll have to move the wheelchair and person to accommodate)

![image](https://user-images.githubusercontent.com/1621749/173110588-012a427e-1adc-4f05-8149-c8ed993829d4.png)

**Comment by hoominchu** [comment]
We started working on the implementation of these screens. Attaching a short video of the work in progress.

https://user-images.githubusercontent.com/8168506/200907226-f12b8815-aa5c-47b4-9618-02acaaedde95.mov
