### ISSUE TITLE
Bug in New Mission Complete Dialog

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#217]
It shows that I audited 2.5 miles in this mission but have only completed 0.5 miles in the neighborhood. How is this possible? Shouldn't audited in this neighborhod always be >= to miles audited in the mission?

Could it be that this is a simple problem with function call mismatch--perhaps the function for calculating how many miles completed in this mission is being called to calculate the neighborhood part.

![image](https://cloud.githubusercontent.com/assets/1621749/17856551/161bf942-684c-11e6-84b5-2aeb642eba9a.png)

**Comment by kotarohara** [comment]
Yeah, I found that the two numbers are flipped in Daniil's code when calling a method. I fixed it on the weekend.

**Comment by jonfroehlich** [comment]
Great, we can close this now then, right? Or have you not tested it yet?

**Comment by kotarohara** [comment]
Yes, I'm closing this.
