### ISSUE TITLE
No audio in Safari

### ISSUE THREAD

**Issue by shokiami** [ProjectSidewalk/SidewalkWebpage#2176]
When a label is placed during auditing, a sound should play. This works for browsers such as Chrome and Firefox but is not working in Safari. Specifically, `audios[name].play();` in AudioEffect.js is an unsupported operation.

**Comment by misaugstad** [comment]
Do other sounds play on Safari? Or is placing a label the only one that doesn't work?

**Comment by shokiami** [comment]
@misaugstad That seems to be the only time a sound is ever played so I am not sure. The only reference I was able to find was `svl.audioEffect.play('drip');` in Canvas.js which is called when you place a label.

**Comment by misaugstad** [comment]
There is definitely a mission complete sound though

**Comment by shokiami** [comment]
@misaugstad Sorry you are right! Completely missed that! I just tested it out and the mission complete sound works for both Chrome and Firefox but not for Safari.

**Comment by misaugstad** [comment]
closing via #2202
