### ISSUE TITLE
Add badge system (gamification)

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2178]
The concept originally came up in #1315 and #73

There used to be a skeleton of a badge system implemented that was never shown to users, but I finally deleted that code maybe a year ago (the mission infrastructure changed too much to where it was no longer useful to keep around).

Some ideas @jonfroehlich has given for what could be tracked with badges
* number of miles walked (e.g., first 0.5 mile, first 1 mile, 2 miles, 5 miles, 10 miles)
* number of labels of different types (with different tiers and badges for reaching, say, 100, 200, 500, etc.)
* number of neighborhoods completed
* completing first audit mission ever
* completing first validation mission ever

Some examples of other websites and their system of badges
* https://questagame.com/university-bioquest
* [Sidewalk Gamification.pdf](https://github.com/ProjectSidewalk/SidewalkWebpage/files/3458336/Sidewalk.Gamification.pdf) (courtesy of @htadeusiak)
* https://edu.decidim.org/gamification/badges?locale=en (and the Github issue about the design of the badges [here](https://github.com/decidim/decidim/issues/3209))
* Apple Watch also has a interesting set of rewards/badges for their health tracking stuff

And an example of how we could tie this system in with social media:
![image](https://user-images.githubusercontent.com/1621749/56708469-95447380-66d1-11e9-85c5-7d18ac637830.png)

**Comment by jonfroehlich** [comment]
Also, @bridgetsheff was working on this originally. I'll ping her to see if she has any mocks or initial badge assets to send us.

**Comment by jonfroehlich** [comment]
Here is Google's "CrowdSource" game with badge implementation: https://youtu.be/WmzwfFWEodw

**Comment by misaugstad** [comment]
closing via #2297
