### ISSUE TITLE
Label image and severity image do not render in Safari

### ISSUE THREAD

**Issue by shokiami** [ProjectSidewalk/SidewalkWebpage#2188]
In Safari, the label image and severity image do not render. In the screenshot below, there should be a curb ramp icon in the label and a smiley face next to "somewhat passable."

<img width="1027" alt="87477043-48053800-c5dc-11ea-88bd-c0c89a0fd647" src="https://user-images.githubusercontent.com/43970567/88129395-de150180-cb8c-11ea-8b60-0b64f27253d6.png">

**Comment by jonfroehlich** [comment]
For some reason, I remember @shokiami making progress on this. But perhaps I'm wrong?

**Comment by misaugstad** [comment]
He did fix a similar issue, #1783 but I think he had a hard time figuring out this one.

**Comment by jonfroehlich** [comment]
Gotcha. Good work @shokiami on #1783. Perhaps you could tell us what challenges you encountered so we could use that knowledge for future work on this Issue.

**Comment by shokiami** [comment]
@jonfroehlich Yeah definitely. If I recall correctly, the challenge I was running into was that Safari had an issue with setting image paths (`imageObj.src = imagePath;` in Point.js and `severityImage.src = severityImagePath;` in Label.js).

**Comment by misaugstad** [comment]
This no longer seems to be an issue!
