### ISSUE TITLE
Hit enter to close the context menu

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#219]
Hitting enter should close the context menu. See #80 for the related conversation.

![image](https://cloud.githubusercontent.com/assets/612263/17863986/151a4738-686a-11e6-8cd2-39cc1fd5afbe.png)

**Comment by jonfroehlich** [comment]
Can you please fix this one? I keep trying to hit enter to close the dialog and it hurts my brain that it doesn't work. :)

**Comment by jonfroehlich** [comment]
@manaswis, perhaps this could be your first frontend task? Otherwise, @kotarohara, can you please do this. It would be super fast and easy... and now users are requesting it.

![image](https://cloud.githubusercontent.com/assets/1621749/18222341/cdf8594c-7162-11e6-9e1c-3ea1f29b8808.png)

**Comment by manaswis** [comment]
I could do it but I won't be able to do it in the next 3 days. If its immediately needed, then @kotarohara would be the best person to do this. Otherwise, I will do it after I return.

**Comment by jonfroehlich** [comment]
Oops, I thought I had assigned @Soben713 to this last week but I must not have clicked the 'Comment' button so it was lost in a tab somewhere. @Soben713, I think this should be an easy place to start with some frontend dev.

**Comment by Soben713** [comment]
@jonfroehlich Will do.

**Comment by Soben713** [comment]
Has anybody fixed this issue? Because the enter key already works for me.

**Comment by jonfroehlich** [comment]
It does _not_ work when the description textbox has focus, which is, imo when you _really_ want the enter key to work because both of your hands are on the keyboard.

![image](https://cloud.githubusercontent.com/assets/1621749/18563317/39bfdc80-7b55-11e6-87d2-d4cb737ddb88.png)

**Comment by kotarohara** [comment]
The context menu does not close when you are on focus on the text field. It has been set so that typing text would not accidentally control other parts of the interface (e.g., changing the mode). So what you have to do is (i) find the part that says something like `event.preventDefault`, (ii) before that line check if the typed key is enter (or esc), and (iii) if it is enter/esc, close the window, otherwise follow what we are doing now.

**Comment by Soben713** [comment]
@kotarohara @jonfroehlich Ok, got it.

**Comment by Soben713** [comment]
Was fixed in #330.
