### ISSUE TITLE
Add a default PR (and issue) template

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2190]
I really want to add a default PR template that can serve both as a checklist of things to check for before submitting a PR, and as a way to improve documentation in the PR. I looked into this a bit a few weeks ago and found that it was more complicated than just setting something up on the Github website, so I didn't go through with it then. But I'd really like to now.

@shokiami would you be able figure out how to set up a PR template (ideally an issue template as well)? You can just add a super super basic stand in one; I will write the whole thing after you get it set up, I just would appreciate the help in getting it set up in the first place!

**Comment by jonfroehlich** [comment]
@misaugstad shouldn't this be closed. Seems like there are templates both for Issues and PRs now...

**Comment by misaugstad** [comment]
Ahh yes I had not tried to make a new PR to test that it works since the most recent merge into master. Just checked and it's working, so yeah I'll close it. Good catch.
