### ISSUE TITLE
Consider removing 'points into traffic' tag for curb ramps

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2203]
I have found this to be the most confusing tag for our users (mostly anecdotal). I get asked what this tag means more than any other when doing mapathons and such.

Also anecdotally, when reviewing work from turkers, this seems to be the tag that is applied most haphazardly. We have them use it in the tutorial, so they probably think it is important to use that tag, most people just have no idea when they're supposed to use it. And I assume that since turkers are worried about doing something wrong and having their work rejected, they will often add the tag on every label, or seemingly at random.

I have also found that when I explain the tag to people, it can take quite a long time to explain. I think that to truly explain what we want from this tag in the tool, we need to show them an image (maybe a gif) that shows both the flow of traffic and where the pedestrian path is located that the curb ramp is for... I just haven't found a way to describe this idea in a concise enough way that is at all suitable for Project Sidewalk.

Maybe we just take it out of the tutorial, and it becomes a mostly unused tag, but we still have the option to add it?

Although the issue of a curb ramp pointing you into cross traffic is a real issue, I don't see how we get data on this that isn't total garbage. And while we collect this garbage data, we are confusing our users by not describing it fully :sweat_smile:

**Comment by misaugstad** [comment]
@jonfroehlich are you opposed to removing the points into traffic tag?

**Comment by jonfroehlich** [comment]
Let’s discuss in future. I’d prefer to keep it tbh. But am open to dropping. 

Bigger issue to me is adding the tags for Mexico that Edgar suggested or at least discussing these (and possibly consolidating)

**Comment by misaugstad** [comment]
@jonfroehlich do you have any qualms about dropping it from the tutorial? Or do you want to keep it in there for now as well?

**Comment by jonfroehlich** [comment]
No qualms

**Comment by misaugstad** [comment]
closing via #2220
