### ISSUE TITLE
When You Place a New Label, the Rating Looks Like It's Already Filled Out

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#221]
When you place a new label, the rating looks like it's already filled out (to the rating that was last used). Screenshot below.
![image](https://cloud.githubusercontent.com/assets/1621749/17864432/13126536-686c-11e6-9ce4-04a593840d3f.png)

Movie here: https://youtu.be/gVl6WsROTuA

**Comment by kotarohara** [comment]
I noticed earlier and fixed it already.
