### ISSUE TITLE
Rename "Occlusion" to "Can't see the sidewalk" in labeling guide

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2212]
The word occlusion is just what we use on the back end and in papers when we can describe what we mean by it. Anything user facing should use the phrase "Can't see the sidewalk".

**Comment by jonfroehlich** [comment]
Is @jacknussbaum actively working on this one? Otherwise, I could get to it relatively quickly. Lmk.

**Comment by misaugstad** [comment]
Saving this for @jacknussbaum who is starting next week.

**Comment by misaugstad** [comment]
Since it is a perfect warm up task and is not super high priority.

**Comment by jacknussbaum** [comment]
I was wondering about maybe using slightly more formal language on this change? What about something like "Sidewalk Not Visible"?

**Comment by jacknussbaum** [comment]
'Can't see the sidewalk' felt a little colloquial. This may bring more clarity? Not a big deal, but lmk what you think @misaugstad @jonfroehlich thanks!

**Comment by jacknussbaum** [comment]
I realize there may be other instances of "Can't see the sidewalk" that are user-facing already actually

**Comment by jonfroehlich** [comment]
Thanks for thinking of this Jack. However, we want informal, easy to understand language. So, I think "Can't see sidewalk" or "Can't see the sidewalk" is fine!
