### ISSUE TITLE
Table That Shows Most Recent Labels, Severity Ranking, Descriptions

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#222]
Is there currently a way to review the labels, severity, and descriptions left in the pop-up label dialog in the admin interface?

![image](https://cloud.githubusercontent.com/assets/1621749/17864881/dc4f878e-686d-11e6-920f-e5f5cc072f59.png)

If not, could we add something for this? Two quick ideas:

- A table that just shows the most recent labels, severity ranking, and descriptions entered into our system. Table should also have timestamp of the label and user who entered it. Each row is a label.
- Same as above but for each user's admin interface that shows their most recent labels, severity ranking, descriptions, etc. Again, each row is a label.

**Comment by jonfroehlich** [comment]
This should be a fairly easy task for one of the new Project Sidewalk RAs.

**Comment by manaswis** [comment]
Submitted pull request https://github.com/ProjectSidewalk/SidewalkWebpage/pull/290

**Comment by manaswis** [comment]
Updated with user tables and pagination --> pull request https://github.com/ProjectSidewalk/SidewalkWebpage/pull/294

**Comment by jonfroehlich** [comment]
Can you also add in a boolean column for Temporary:

![image](https://cloud.githubusercontent.com/assets/1621749/18225556/c4cce27e-71c2-11e6-9e3a-c8b358271384.png)

**Comment by manaswis** [comment]
Done! Pull request --> https://github.com/ProjectSidewalk/SidewalkWebpage/pull/311

**Comment by manaswis** [comment]
This has been merged into the master branch. Closing it.

**Comment by jonfroehlich** [comment]
@manaswis, we discussed in person but it's not in this ticket--perhaps it's in another Issue--but the idea was to make another column that is a url that, when clicked, takes you to the location in GSV for that label. We could implement this in two stages:

1. Stage 1 - Easy: When you click on URL, you're taken to the location of the label and you are looking in the same direction as that label; however, the labels from that user are not actually visible.

2. Stage 2 - Harder: When you click on the URL, you're taken to the location of the label but you can see all the labels from that user in the GSV scene--the label that corresponds to the one you clicked in the URL is highlighted in some way.

**Comment by manaswis** [comment]
Yes, I remember. I am going to open a new issue for this.
