### ISSUE TITLE
Terms and conditions isn't showing up

### ISSUE THREAD

**Issue by rpechuk** [ProjectSidewalk/SidewalkWebpage#2226]
When clicking this link:
![image](https://user-images.githubusercontent.com/39865166/92660668-bfd7a200-f2af-11ea-9c40-fdd2374efe5f.png)
![image](https://user-images.githubusercontent.com/39865166/92660691-c9f9a080-f2af-11ea-99bf-7bbee24353bb.png)
You get this as the result:
![image](https://user-images.githubusercontent.com/39865166/92660655-b2bab300-f2af-11ea-9d49-82ee5170fff5.png)

**Comment by misaugstad** [comment]
Yikes. Okay, looks like it is only happening during the sign up process (both the /signUp endpoint and through the navbar). The link in the footer is working fine though.

**Comment by misaugstad** [comment]
closing via #2235
