### ISSUE TITLE
When you click on a new city name, default action should be to take you to landing page (not audit page) for that city

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2227]
@gari01234 suggested that when you click on another city name on the landing page that we should simply load that city's landing page (rather than the audit page, as we do now). The reason why we loaded the audit page was that we were worried people would not be able to differentiate between one city's landing page and another... (so, we were trying to address the problem of: "Wait, which city have I loaded now?" and "Did my click actually do anything").

To help combat that problem—and I'm not sure it is actually a problem—we could put the current city's name in bold on landing page like this:

![image](https://user-images.githubusercontent.com/1621749/92667086-d554c800-f2bf-11ea-8d77-72b773795e44.png)

![image](https://user-images.githubusercontent.com/1621749/92667160-08975700-f2c0-11ea-9905-c00cbc158f58.png)

I also think we may want to consider adding in some % complete stats up here so that users don't need to scroll down to see this information.

**Comment by jonfroehlich** [comment]
I guess one downside of putting the prefix of "city name, let's create a path for everyone" is that it feels like a call-to-action specific just to those people who live in that city but our users can come from anywhere to help... Hmm. 

@misaugstad, thoughts on this?

**Comment by misaugstad** [comment]
I agree that it feels weirdly like it is specific to those living in that city. I didn't really like that method of differentiating anyway... I think there has got to be a better way to clearly distinguish which city you're in. The "Start Exploring ___" button almost does it for me, but I agree that there should be something more prominent.

I almost want to put something in the navbar near the sidewalk logo, but I REALLY don't think we should be adding anything we don't have to to the navbar. I don't have any great ideas off the top of my head for how to add an identifier that looks really clean. Would love more ideas.

**Comment by jonfroehlich** [comment]
Let's have you merge https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2255 and see what we think after that point. It might be that the "Start Exploring ____" is sufficient.

**Comment by misaugstad** [comment]
closing via #2255
