### ISSUE TITLE
Mission Structure

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#223]
I'm confused about the length of missions. Can you specify what the mission lengths are as you progress through a neighborhood. I've completed ~6 missions I think in Congress Heights and I'm still being assigned 1/2 mile missions. Is this right? What's the correct mission length behavior?

![image](https://cloud.githubusercontent.com/assets/1621749/17865164/2813079e-686f-11e6-8abf-e54c9968d5bb.png)

**Comment by kotarohara** [comment]
This is same as #239. I'm closing this.
