### ISSUE TITLE
GSV view located in the U. S. when exploring Mexico cities

### ISSUE THREAD

**Issue by gari01234** [ProjectSidewalk/SidewalkWebpage#2231]
when I want to start exploring,  SPGG and CDMX, it first takes me to a GSV view located in the United States. It is always the same GSV view where it places me at the beginning. 

see video: https://youtu.be/uasdxzI819U

**Comment by jonfroehlich** [comment]
Interesting. And when I’ve validated, I’ve also seen some scenes from the US. This explains it. Thanks for finding this Gari

**Comment by misaugstad** [comment]
Yeah that is the street that the tutorial is on, just with some newer images. This happens all the time (and I think is causing some other problems too). Been trying off and on to figure this out for awhile, but I think it's pretty important to get this figured out soon.

**Comment by jonfroehlich** [comment]
Just happened to me. I finished part of the assigned route in Del Valle and then interface jumped me here (back to DC)

![image](https://user-images.githubusercontent.com/1621749/93532564-27b46b00-f8f6-11ea-87fe-5e2632bdc324.png)

**Comment by jonfroehlich** [comment]
And actually, I'm seeing quite a few DC images in SPGG validations right now.

@misaugstad, can you run a quick query on San Pedro to see how many labels have lat, long outside of Mexico?

I wonder how much labor we are wasting both in auditing Washington DC and in validating Washington DC labels on our other city servers.

**Comment by misaugstad** [comment]
Looks like there are 202 non-tutorial labels outside of Mexico on the SPGG server, which is close to 2% of the labels. I don't want to be wasting that much effort, so this should be resolved quickly. The one upside is that we now have a street that a ton of different people have all audited, which can be useful for other reasons :grin:

**Comment by jonfroehlich** [comment]
Thanks for conducting this analysis Mikey.

I thought the same thing in terms of using that data for other reasons (exploring false negatives, etc.)... but I know when I was sent to DC during an audit mission, I didn't audit it in the same way as I knew it was out-of-bounds.

**Comment by misaugstad** [comment]
reopening bc I'm not sure that this will fix the issue in all situations yet.
