### ISSUE TITLE
SPGG Expansion into Del Valle

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2232]
Now that the first neighborhood in SPGG is almost complete (see below), after speaking with SPGG, @gari01234 says that neighborhood '5' below should be next. He also said this is a higher priority than adding Mexico-specific tags atm. (As an aside, these neighborhoods area really huge @misaugstad. I was going to recommend that perhaps we unlock more than one... but given their size, maybe not?)

![image](https://user-images.githubusercontent.com/1621749/93212594-a3a48c80-f717-11ea-8257-b9806755ac90.png)

![image](https://user-images.githubusercontent.com/1621749/93212649-b4ed9900-f717-11ea-861c-b1736749c43a.png)

**Comment by misaugstad** [comment]
I think one at a time is good. I expect to be able to get this done tomorrow. In the future, adding new neighborhoods should only take me a few minutes :+1:

**Comment by jonfroehlich** [comment]
Woohoo! Looking forward.

**Comment by misaugstad** [comment]
closing via #2234
