### ISSUE TITLE
Compress skyline images

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2237]
As mentioned in #2204 we want to compress the skyline images on the landing page as best we can, to improve the slow loading times. @jonfroehlich offered to do a lossless compression using Photoshop.

And here are the versions at the level of compression we are using on the landing page:
https://github.com/ProjectSidewalk/SidewalkWebpage/blob/master/public/assets/columbus-oh/skyline.png
https://github.com/ProjectSidewalk/SidewalkWebpage/blob/master/public/assets/spgg/skyline.png
https://github.com/ProjectSidewalk/SidewalkWebpage/blob/master/public/assets/seattle-wa/skyline.png
https://github.com/ProjectSidewalk/SidewalkWebpage/blob/master/public/assets/washington-dc/skyline.png
https://github.com/ProjectSidewalk/SidewalkWebpage/blob/master/public/assets/generic_cloud_overlay.png

@jstadeusiak I forgot to verify that you put the originals into the assets folder in the PR as requested [in this comment](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2204#pullrequestreview-472902153) Can you add the non-compressed versions in this thread?

**Comment by jonfroehlich** [comment]
Just to be clear, where can I get the non-compressed versions? (Didn't totally understand your request to @jstadeusiak).

Once I get the non-compressed versions, I'll use Photoshop to create lossless compressed PNGs.

**Comment by jstadeusiak** [comment]
Here are the non-compressed versions @jonfroehlich 
Skyline/Cityscape:
![skylineFinal](https://user-images.githubusercontent.com/64165755/93625859-76fea800-f997-11ea-8677-5328865297d8.jpg)

Skyline/Cityscape Mexico:
![skylineFinalMexico](https://user-images.githubusercontent.com/64165755/93626832-e0cb8180-f998-11ea-8da3-17068486ebb0.png)


Seattle:
![skyline](https://user-images.githubusercontent.com/64165755/93626576-774b7300-f998-11ea-9603-e2fd48ae35cc.png)

**Comment by jstadeusiak** [comment]
@misaugstad Did you want me to make a folder in assets with all the non-compressed versions?

**Comment by misaugstad** [comment]
It's all good, I don't think you need to continue working on this issue. Jon and I will do the additional compression and I'll add them to the repo myself. Thanks for all the hard work on the skyline issue! They are looking great :)

**Comment by jonfroehlich** [comment]
Are we sure that adding GitHub retains the original images when uploading to a GitHub thread and doesn't try to compress them? (I can't imagine that GitHub expects us to exchange high-quality files by embedded them in GitHub Issue posts...)

**Comment by jonfroehlich** [comment]
The Seattle image, in particular, already looks compressed and pixelated...

**Comment by misaugstad** [comment]
Yeah they are not being compressed when uploaded to a github thread. I have no idea if the original image added to the repo was compressed from whatever Bridgett originally sent. But here is the entire history of the skyline that I've been able to find from digging through our issues and pull requests.

The last version of the design that was uploaded to the Seattle skyline thread #1678 (316 kb)
![image](https://user-images.githubusercontent.com/1621749/56315690-38631f00-610d-11e9-919f-5a7c02b2f11a.png)

The first version that was in PR #1678 It looks like the above, but it has the clouds/bubbles added, and the background is now transparent. I couldn't find any discussion of making those changes on Github or in my email (382 kb).
![skyline-old2](https://user-images.githubusercontent.com/6518824/93929098-2f965580-fcd0-11ea-9bb6-d7ce96b61d52.png)

The first version that actually made it onto the website (the final version in PR #1678). I think it is the same as the one above, except that its dimensions resemble the DC skyline better. I also don't know where the discussion about this change happened (959 kb).
![first-seattle-skyline](https://user-images.githubusercontent.com/6518824/93928483-41c3c400-fccf-11ea-84c5-0a8cad8c761e.png)

And the version that is on the website right now. I believe @jstadeusiak just removed some of the vertical space from the image that was there before (940 kb).
![skyline-current](https://user-images.githubusercontent.com/6518824/93929465-bfd49a80-fcd0-11ea-8fd2-93092d941dca.png)

**Comment by jonfroehlich** [comment]
Thanks @misaugstad. I just used the versions that @jstadeusiak posted [here](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2237#issuecomment-694989595). Let me know if I should also use some of what you posted above.

I used Adobe Photoshop 2020 to create compressed (lossless) PNGs—but this didn't dramatically cut down the file sizes (and, in some cases, the file sizes increased). So, I've also included JPG versions but these lack transparency, obviously.

https://www.dropbox.com/sh/pvnp9ogkdlo6vuw/AADFB0MpyWLahYjIRwQruXOMa?dl=0

**Comment by misaugstad** [comment]
Thanks @jonfroehlich I think what we need is for someone to do a lossy compression that keeps them as PNGs, and really just need to trial and error see how compressed we can get each one without a noticeable difference in quality when looking at the landing page.

**Comment by misaugstad** [comment]
And ofc we should keep the originals either in this repo or in the [branding repo](https://github.com/ProjectSidewalk/Branding).
