### ISSUE TITLE
Add in pop-up hovers to tags?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2241]
In https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2240, @gari01234 suggested adding pop-up hovers to tags:

![imagen](https://user-images.githubusercontent.com/50057640/93570322-1ff6d400-f993-11ea-9d93-06e4e15e4ed5.png)

I think some of these pop-hovers would be easy to make—others, like the "no alternative route" are actually harder to show in a single pop-up and requires probably an animated gif and textual descriptions.

**Comment by jonfroehlich** [comment]
Over Slack, Gari indicated that he could take the lead on this one so assigning him for now. @gari01234, if that doesn't work for you, no worries: feel free to unassign yourself.

To help with this Issue, we are trying to create a comprehensive set of examples here (however, the examples need to be improved so that they are organized around tags):

- [Surface Problems](https://docs.google.com/presentation/d/1QfTEOF0sJXyaB_yvfy9oI1POOQrgysMaHcYaZsKgf7s/edit#slide=id.g9a614cbb06_1_0)
- [Obstacles](https://docs.google.com/presentation/d/1E8f_dqIIhjPCGI9z69FCxguwgtRcH92Y77-mV1xduOs/edit#slide=id.g9a569457c5_0_122)
- [Curb Ramps](https://docs.google.com/presentation/d/1HDIw0Nzy72s0HdIn4AMsZcIgE3C3YjemrJeCZkFDHxQ/edit#slide=id.g9a59c21d14_0_72)
- [Missing Curb Ramps](https://docs.google.com/presentation/d/1_INkXmBoafq7rHtUmDaR5n9TSrBA62g69WWfOVZWYWA/edit#slide=id.g9a639fa2a5_0_210)
- [No Sidewalks](https://docs.google.com/presentation/d/15TOCN0L09Yxcn8taUs92fMIqNxB9LDXvhB6A_56uKys/edit#slide=id.g9a65bc8ac2_0_117)

**Comment by gari01234** [comment]
I am making a selection of images for each one of the tags. [Link](https://docs.google.com/spreadsheets/d/1iRr4G3JZ5v05HRzz09Dc1GWjSNBdxUjnr-UW1jphJZo/edit?usp=sharing)

I suppose it is convenient that the images correspond to the countries (Mx, US). So I will also make a selection of images for US. 
Next step will be to generate texts describing the images.

**Comment by gari01234** [comment]
@misaugstad 
going back to this issue, here are the images for each of the labels:
I'm missing a couple

**Curb ramp/ rampa peatonal**
[muy angosta](https://user-images.githubusercontent.com/50057640/96350992-faa3d580-10b8-11eb-9bdd-3bfa27648241.png)
[orientada al tráfico](https://user-images.githubusercontent.com/50057640/96351578-984cd400-10bc-11eb-8043-d78f51db9d1c.png)
pavimento de advertencia táctil ausente
[empinada (mucha pendiente)](https://user-images.githubusercontent.com/50057640/96351726-a7805180-10bd-11eb-9910-454accfa8029.png)
[área de aproximación insuficiente](https://user-images.githubusercontent.com/50057640/96351071-638b4d80-10b9-11eb-80f1-a49d07b55fb1.png)
[con desnivel](https://user-images.githubusercontent.com/50057640/96351606-dcd86f80-10bc-11eb-8114-f5725784abec.png)

**Missing Curb Ramps/ Rampa peatonal ausente**
[hay una ruta alternativa segura para cruzar](https://user-images.githubusercontent.com/50057640/101777931-73d90b00-3af3-11eb-8bbf-90134c7a7b89.png)
[no hay una ruta alternativa para cruzar](https://user-images.githubusercontent.com/50057640/95466661-dccdc680-097c-11eb-91cd-48f59f7aa274.png)

**Obstacles in Path/ Obstáculo**
[poste](https://user-images.githubusercontent.com/50057640/93486081-107c7a00-f904-11ea-8ff7-fa1be53c7fa4.png)
[árbol](https://user-images.githubusercontent.com/50057640/93485609-87654300-f903-11ea-9558-2a64c9d0c2f4.png)
[vegetación](https://user-images.githubusercontent.com/50057640/101779678-e0550980-3af5-11eb-82da-bea5c22826e8.png)
[basurero](https://user-images.githubusercontent.com/50057640/101779877-185c4c80-3af6-11eb-9cf0-9c9565c5de18.png)
[auto estacionado](https://user-images.githubusercontent.com/50057640/93489160-774f6280-f907-11ea-8fd6-e322664a4f74.png)
[obra en construcción ](https://user-images.githubusercontent.com/50057640/96352271-50c94680-10c2-11eb-87e0-a0b8a95ebff5.png)
[señalamiento](https://user-images.githubusercontent.com/50057640/93485170-11f97280-f903-11ea-9f0a-f158f2811801.png)
entrada a cochera
[escalones](https://user-images.githubusercontent.com/50057640/93769604-55155780-fc1b-11ea-9883-333e5d8f394d.JPG)
[comercio ambulante](https://user-images.githubusercontent.com/50057640/101783031-0c728980-3afa-11eb-8808-32ea2fd87da1.png)
[desnivel](https://user-images.githubusercontent.com/50057640/101783160-3461ed00-3afa-11eb-9cd4-a5e8dfc6a033.png)

**Surface problem/ problema en superficie**
[textura irregular](https://user-images.githubusercontent.com/50057640/93770944-27311280-fc1d-11ea-8b97-124e0cea7060.JPG)
[dispareja](https://user-images.githubusercontent.com/50057640/101783379-7e4ad300-3afa-11eb-803b-b491ac38399c.png)
[grietas](https://user-images.githubusercontent.com/50057640/93493366-1f672a80-f90c-11ea-9893-61d0ce70d508.png)
[hierba](https://user-images.githubusercontent.com/50057640/93494379-41ad7800-f90d-11ea-8b21-008023ffa13c.png)
[muy angosta](https://user-images.githubusercontent.com/50057640/83888886-bbe53280-a74a-11ea-8f3d-8935426721ce.JPG)
[rota](https://user-images.githubusercontent.com/50057640/93492029-a7e4cb80-f90a-11ea-959a-2a1da309f53e.png)

**No sidewalk/ No hay banqueta**
termina abruptamente
la calle tiene una banqueta
la calle no tiene banquetas
camino de tierra
plataforma única
