### ISSUE TITLE
How are the city's ordered on landing page?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2242]
Now that we have deployed into so many cities, I think there are two issues to address with the landing page:

1. How is the list of cities ordered? Because we might get click-traffic effects based on order, perhaps they should be ordered based on incompleteness? I wonder too if we should just take out Washington DC at this point
2. Aesthetically, the list wraps leaving a 'Orphan' city at the bottom (just one city name), this looks bad to me.

![image](https://user-images.githubusercontent.com/1621749/93598697-ea8dbe80-f971-11ea-8101-2a959fdb73f6.png)

**Comment by gari01234** [comment]
> Aesthetically, the list wraps leaving a 'Orphan' city at the bottom (just one city name), this looks bad to me.

On my screen I see two at the end. 

![imagen](https://user-images.githubusercontent.com/50057640/93615648-f4e0a480-f9d3-11ea-9e62-7517c672f9b2.png)

**Comment by jonfroehlich** [comment]
Ha, different issue in Spanish! I think the "Creemos un camino para todas las personas" should be two lines rather than four. :)

**Comment by misaugstad** [comment]
It looks like they are just in the order that they are in in this first list in the cityparams.conf file: https://github.com/ProjectSidewalk/SidewalkWebpage/blob/master/conf/cityparams.conf#L6

Those can be moved around very easily. @jonfroehlich do you have an ordering preference?

**Comment by jonfroehlich** [comment]
Not really. I suggest either dynamically listing them based on which city needs the most work or listing them in alpha order. Thoughts?

**Comment by misaugstad** [comment]
if by "dynamically" you mean that it should be able to reorder itself automatically, I think that that sounds like too much work. But I do think that removing DC and ordering by how much work remains / our desire to complete them is something that I can just maintain as we go by manually reordering that list in the config file. The ordering won't change that frequently, and it's so simple for me to update manually.

**Comment by jonfroehlich** [comment]
Sounds good
