### ISSUE TITLE
Display images, in "explore" section, of the most common mistakes in labeling

### ISSUE THREAD

**Issue by gari01234** [ProjectSidewalk/SidewalkWebpage#2244]
Is it possible to identify some of the most common mistakes people are making when labeling? 
I ask this because, from time to time, when I am "exploring" in PS a survey appears. Perhaps images can be shared, from time to time, showing common errors in labeling.

This with the purpose of improving validation accuracies of active users, see: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2240#issue-703944118

![imagen](https://user-images.githubusercontent.com/50057640/93617859-cfa16580-f9d6-11ea-9833-5126ac0ed0c1.png)

**Comment by misaugstad** [comment]
Related to #270 #503 #1253 #1368 and #1446

**Comment by jonfroehlich** [comment]
I really like this idea. We'll obviously want to implement this in a way that doesn't _annoy_ the user with lots of pop ups... but generally, I think this is a good idea.

**Comment by gari01234** [comment]
Maybe we can show this kind of images depending on the user's accuracy score? The higher the accuracy, the fewer the images.

**Comment by jonfroehlich** [comment]
Nice idea. Thanks @gari01234.

**Comment by gari01234** [comment]
![Entradas-a-cocheras_Gif](https://user-images.githubusercontent.com/50057640/98360609-67f8b580-202a-11eb-968f-246e7731bbab.gif)

First mockup...Text translation: remember driveways should not be labeled as curb ramps

**Comment by gari01234** [comment]
@misaugstad @jonfroehlich 
I am back with this issue. A couple of weeks ago I sent an [email](https://us2.campaign-archive.com/?e=__test_email__&u=88665598b686adc686aec96da&id=eb71cf8470) , to SPGG users, with images of common mistakes that are being made when tagging. Maybe these images can be shown, as a pop-up, in the "explore" interface. 

1- Remember that entrances to driveways and parking lots are NOT curb ramps and should NOT be labeled as "Curb Ramp"
1- Recuerda que las entradas a las cocheras y a los estacionamientos NO son rampas peatonales y NO deben etiquetarse como "Rampa peatonal"
![01](https://user-images.githubusercontent.com/50057640/101789551-bacdfd00-3b01-11eb-89a1-1d06c7704ad9.jpg)

2- Poles, trees, signs, vegetation, parked cars...are NOT considered obstacles on the sidewalk when there is at least 1.20 meters of free space to circulate.
2- Los postes, árboles, señalamientos, vegetación, autos estacionados...NO se consideran obstáculos en la banqueta cuando al lado hay mínimo 1.20 metros de espacio libre para circular
![03](https://user-images.githubusercontent.com/50057640/101789674-e05b0680-3b01-11eb-9003-497f102b317e.jpg)
![06](https://user-images.githubusercontent.com/50057640/101789679-e0f39d00-3b01-11eb-9613-69be387dba8c.jpg)

3- It is necessary to place the labels in the center of the surface problems.
3- Es necesario posicionar las etiquetas en el centro de los problemas en la superficie
![04](https://user-images.githubusercontent.com/50057640/101789816-041e4c80-3b02-11eb-8fea-950b1d441fb2.jpg)
![05](https://user-images.githubusercontent.com/50057640/101789818-04b6e300-3b02-11eb-9d2f-13435a23846f.jpg)

4- It is necessary to place the labels in the center of the curb ramps
4- Es necesario posicionar las etiquetas en el centro de las rampas peatonales
![12](https://user-images.githubusercontent.com/50057640/101793262-e3f08c80-3b05-11eb-9d4f-cf6b5b8fbe98.jpg)
![11](https://user-images.githubusercontent.com/50057640/101793264-e4892300-3b05-11eb-99bb-001d40b8ddc1.jpg)

5- The obstacle labels must be positioned at the base of the obstacle
5- Las etiquetas de los obstáculos, que encuentres en las banquetas, deben posicionarse en la base del obstáculo
![09](https://user-images.githubusercontent.com/50057640/101792245-c66ef300-3b04-11eb-8083-61e54329dd54.jpg)
![10](https://user-images.githubusercontent.com/50057640/101792252-c7a02000-3b04-11eb-9a2f-aeb4375e2e66.jpg)

6- Only problems found on sidewalks should be labeled. Problems outside the sidewalk should NOT be labeled
6- Solo se deben etiquetar los problemas que se encuentran en las banquetas. Los problemas fuera de las banquetas NO deben de etiquetarse
![07](https://user-images.githubusercontent.com/50057640/101789955-316afa80-3b02-11eb-88c8-fe75acb01029.jpg)

**Comment by jonfroehlich** [comment]
I just want to bump this Issue and any others that relate to improving the *quality* of data being collected in Project Sidewalk. Arguably, nothing is more important to work on atm (other than performance issues and bugs, of course).

This also relates to:

- https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2407
- https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2288#issuecomment-706670837

Thanks @gari01234 for pinging me about this again.

**Comment by misaugstad** [comment]
I would say that this has been sufficiently addressed through the new mission start tutorial screens for the Explore page!
