### ISSUE TITLE
Remove embedded video from landing page

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2247]
Given that we'd like to add a few more things to the landing page (like the [leaderboard](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2177)), I think we may want to consider removing some elements. 

One element that sticks out to me as unnecessary is the video (third "module" down from top), which appears to only have 74 views ([link](https://www.youtube.com/watch?v=wAdGXqRunQs&feature=emb_logo)). We could move this video somewhere else, of course.

Current landing page:
![screencapture-sidewalk-sea-cs-washington-edu-2020-09-18-09_40_21](https://user-images.githubusercontent.com/1621749/93623688-f2f6f100-f993-11ea-86bd-39b53b334299.png)

With video module removed:
![screencapture-sidewalk-sea-cs-washington-edu-2020-09-18-09_40_21 - Cropped with no video](https://user-images.githubusercontent.com/1621749/93623991-71539300-f994-11ea-9558-271cfbe8dfb3.png)

**Comment by jonfroehlich** [comment]
What do you think @misaugstad. As I said the embedded video only has 74 views, so I'd prefer to focus content on the interactive map, the progress, the upcoming leaderboard feature, etc.

**Comment by misaugstad** [comment]
100% Given 74 views, I'm all for removing it.

**Comment by jonfroehlich** [comment]
Made me sad though :(

I'll take this on and PR it today probably. Again, will make room for the leaderboard stuff.
