### ISSUE TITLE
Pittsburgh is showing as a city on landing page (wow!) but it's not loading correctly (boo!)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2248]
![image](https://user-images.githubusercontent.com/1621749/93624736-a9a7a100-f995-11ea-9157-8447968d8359.png)

![image](https://user-images.githubusercontent.com/1621749/93624692-98f72b00-f995-11ea-9776-ac35dd972186.png)

**Comment by misaugstad** [comment]
Right, I didn't fully catch that we are ready to deploy to production in Pittsburgh. I will get on that ASAP.
