### ISSUE TITLE
Onboarding tutorial gets stuck after panning too much

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#225]
The tutorial gets stuck after the user pans and doesn’t mark the yellow arrow in the tutorial. And since the yellow arrow doesn’t have a label on it, it’s a bit confusing. The info box (that gives step-by-step instruction to the user) is still visible. So a next button on the info boxes would be useful. That would help bring the user back to the point where (s)he left off, else it’s confusing for a first-time user to find his next step. I had to restart the tutorial again.

**Comment by jonfroehlich** [comment]
I don't actually understand this. Can you either make a movie or attach a series of screenshots. 

We often make lil videos to record bugs. See, for example:
- https://www.youtube.com/watch?v=gVl6WsROTuA
- https://www.youtube.com/watch?v=RUHR6em9m7Y

**Comment by manaswis** [comment]
Okay, I will do that.

**Comment by manaswis** [comment]
I couldn't recreate that situation again. Closing this issue for now. If I am able to recreate it again, I will reopen it.
