### ISSUE TITLE
Avoid having text rendered in an image

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2253]
Occasionally, we have text rendered in an image—which both decreases accessibility and makes translation harder. We should remove the static (rendered) text and replace by html text.

![image](https://user-images.githubusercontent.com/1621749/94013705-4b950800-fd5f-11ea-9041-650b7423dbb0.png)

See: https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Translating-Text-On-Images-With-Photoshop-Guide

**Comment by jacknussbaum** [comment]
Ready to submit a PR for this issue, just need a few translations!

Specifically, for the text that was previously rendered in an image, circled below:
![image](https://user-images.githubusercontent.com/71039842/98083352-0fa99400-1e2f-11eb-8a1f-954ae8eec830.png)

The sentences needing to be translated:
-"Curb ramps help wheelchair users get on and off the sidewalks"
-"Wheelchair users can't navigate sidewalks when curb ramps are missing"
-"Obstacles block the paths of wheelchair users"
-"Sidewalks with surface problems may not be navigable"

**Comment by misaugstad** [comment]
You can find the translations in #2050 my bad on not linking to that issue here

**Comment by jacknussbaum** [comment]
Awesome, thank you. Just added those translations.
