### ISSUE TITLE
LabelMap Pop-Up "Do you want to explore this area..." is Annoying

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2256]
When you mouseover a neighborhood in LabelMap, a pop-up keeps occurring "Do you want to explore this area..." I suggest we either get rid of this popup or only show this pop-up if you click on the choropleth (in an area, obviously, where your mouse is not directly over a label). The latter is preferred.

I would fix this one myself but I think we're currently waiting on @MattJ12 and @misaugstad's work in refactoring the choropleth code and I don't want to break it.

![image](https://user-images.githubusercontent.com/1621749/94142653-7ba5df00-fe23-11ea-820b-d0b2e8c58201.png)

**Comment by misaugstad** [comment]
@MattJ12 and I actually talked about this popup last week. I forget if he is removing the popup, or is instead reusing the popups from the landing page choropleth so that it actually give you any information... In any case I agree that we should come back to this after that code is merged.

**Comment by jonfroehlich** [comment]
Thanks, yes. The popup kept coming up for me this morning when I just wanted to click on the labels, so I found it distracting and annoying (this is specific to LabelMap).

**Comment by MattJ12** [comment]
@misaugstad @jonfroehlich Mikey is correct, the branch I'm finishing up changes the labelmap mouseover popup to be the same as that of the landing page choropleth.  As far as changing the popup to only happen on click for the label map, this could easily be done by passing in boolean parameters to the `Choropleth.js` file through a params object which changes the popup functionality based on which choropleth/map is being created.

**Comment by misaugstad** [comment]
This has been fixed!
