### ISSUE TITLE
Move /Instructions to SidewalkWebpage Wiki or README.md?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2258]
Why do we have a separate repo for [Instructions](https://github.com/ProjectSidewalk/Instructions)? Maybe best to move this content over to SidewalkWebpage (both the README.md or the Wiki, where it makes sense?). Also, is this Instructions repo still maintained? I followed the Instructions in our SidewalkWebpage/README.md for Docker setup and it worked great.

![image](https://user-images.githubusercontent.com/1621749/94151292-1526be00-fe2f-11ea-8fc9-7e9b1462b13e.png)

**Comment by misaugstad** [comment]
The Instructions repo is no longer relevant. That's for the old dev env setup. I've left it around for posterity and in case the Docker setup ended up having too many problems and we needed to go back. We've been using Docker long enough and it's gotten smooth enough that I wouldn't feel terrible about removing the repo. At the very least we could put something at the top of the Instructions README stating that these instructions are no longer valid.

**Comment by jonfroehlich** [comment]
Done. We can also delete in future.

![image](https://user-images.githubusercontent.com/1621749/94192362-b465a880-fe63-11ea-98bf-ad4628da8ea3.png)
