### ISSUE TITLE
Do we have the Project Sidewalk labeling icons anywhere?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2259]
Do we have these icons anywhere? I believe the circles are drawn as SVGs and then we overlay logos, however, at some point I recall that @aileenzeng had made some versions in PowerPoint that we could use to overlay on images for documentation and talk purposes. @aileenzeng, do you remember what I'm talking about? If not, I'll make some for us.

![image](https://user-images.githubusercontent.com/1621749/94165030-9df92600-fe3e-11ea-88eb-c98ffefa5fec.png)

**Comment by jonfroehlich** [comment]
I see that all of the icons are stored in `\SidewalkWebpage\public\javascripts\SVLabel\img\icons\Sidewalk` and that we have rasterized images of the icons—but they are very small and intended for the Google Maps minimap (e.g., `GMapsStamp_CurbRamp.png`)

![image](https://user-images.githubusercontent.com/1621749/94165569-37283c80-fe3f-11ea-9730-db151fa0fef9.png)

**Comment by misaugstad** [comment]
I just searched through all the places where I can remember there being images in our repo and couldn't find anything higher res.

**Comment by jonfroehlich** [comment]
Yah, I think I recall that @aileenzeng had some somewhere just for work on our CHI2019 paper...

**Comment by aileenzeng** [comment]
Yep, I vaguely remember using some SVGs -- I'll see if I can dig them out!

**Comment by misaugstad** [comment]
We've sent multiple emails back and forth, and it doesn't look like we're going to be able to find these SVGs :sweat:
