### ISSUE TITLE
Create custom sidebar to clean up Github wiki

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2261]
#### Brief description of issue/feature
As seen below, our Wiki has become a bit cluttered and hard to navigate with 16 pages.

![Screenshot from 2020-09-24 13-33-27](https://user-images.githubusercontent.com/6518824/94197426-a1a2a200-fe6a-11ea-9679-b8e6cb5d2509.png)

As you can see on the bottom right there, we can make a custom sidebar for our wiki, which could clean things up considerably.

#### Design ideas & mockups
Here are some examples of wikis with sidebars. Some are better than others ofc.
[d3](https://github.com/d3/d3/wiki)
![Screenshot from 2020-09-24 13-54-54](https://user-images.githubusercontent.com/6518824/94199374-91d88d00-fe6d-11ea-8011-e478a212f398.png)

[hysterix](https://github.com/Netflix/Hystrix/wiki)
![Screenshot from 2020-09-24 13-55-18](https://user-images.githubusercontent.com/6518824/94199413-a026a900-fe6d-11ea-983e-9ab3c62a6678.png)

[mcMMO](https://github.com/mcMMO-Dev/mcMMO/wiki)
![Screenshot from 2020-09-24 13-55-53](https://user-images.githubusercontent.com/6518824/94199463-b5033c80-fe6d-11ea-92b0-f0e7a350d180.png)

#### Potential solution(s)
We could look at how some of these are made. There is also a tool that can help design a wiki sidebar (that I haven't looks much into) called [github-sidebar-wiki](https://github.com/adriantanasa/github-wiki-sidebar/wiki).

**Comment by misaugstad** [comment]
@cyrusnaficy could you look into this a bit? Not sure if there are other nice solutions outside of the one that I linked to. And we do sometimes sense people to our wiki to get to know the project, and I'd like for this to be nicely organized, with stuff for programmers in a separate place!

**Comment by misaugstad** [comment]
Our sidebar is looking much more clean now, thanks @cyrusnaficy !!

![Screenshot from 2024-09-10 11-04-30](https://github.com/user-attachments/assets/b181acd5-f1b4-4572-abee-001152e6857c)

**Comment by jonfroehlich** [comment]
Great job team!
