### ISSUE TITLE
Somehow I've labeled way outside of the SPGG neighborhood boundaries

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2267]
On SPGG, I was looking at my user dashboard and noticed that I've contributed labels quite a bit outside of the neighborhood boundaries. See southeastern corner.

![image](https://user-images.githubusercontent.com/1621749/94275216-89c72e80-fefb-11ea-877d-49340e4c1f82.png)

Any thoughts on this @misaugstad?

**Comment by misaugstad** [comment]
@jonfroehlich you and I had started auditing before SPGG asked us to restrict to just a single neighborhood (now two neighborhoods). So we each contributed data outside the currently available neighborhoods, which is what we're seeing here.

**Comment by jonfroehlich** [comment]
Gotcha. Thanks Mikey. 🙏🏻
