### ISSUE TITLE
Parameterize MissionTable.getDistanceAudited(userId) to return either miles or kilometers depending on locale

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2269]
I want an easy way to list total distance audited for users on their user dashboard but using the correct measurement system (either imperial or metric).

So, two quick questions:
1. Is there a way to determine which locale the user is in and what we should use for the distance measurement system
2. Secondly, can (or should) we parameterize `MissionTable.getDistanceAudited(userId)` to something like `MissionTable.getDistanceAudited(userId: UUID, returnInMetric: Boolean = false)`. Currently, the function returns in imperial (so setting the default returnInMetric to false would maintain backward compatibility with other method callers)

**Comment by misaugstad** [comment]
I explained in-depth how to know when something needs to be converted [here](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2280#issuecomment-700282974). And we should not parameterize `MissionTable.getDistanceAudited(userId)` given that it is in a model file, and so I don't think it should know or care about the user's locale. I think it is best to do the conversion in a controller/view Scala file, or in the JavaScript.
