### ISSUE TITLE
Why do we have both public/css and public/stylesheets?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2270]
For code cleanliness and organization, seems like we should have only either `public/css` or `public/stylesheets`? Also, I noticed that we have fonts and images within `public/stylesheets`, which seems to not follow standard web dev organization (and also doesn't fit within the definition of "stylesheet").

![image](https://user-images.githubusercontent.com/1621749/94294690-087c9580-ff15-11ea-9966-9d6bcacb460b.png)

**Comment by jonfroehlich** [comment]
Relatedly, we also have `public/assets` and `public/images`—both which have images in them. I'm working on a new feature that has new assets (new icons) but I don't know where to put them given that we seem to place visual assets in both places. So, I'd appreciate some guidance here.

And then, more longterm, I think we need to refactor this a bit to cleanup where we put images, etc. so they are all in the same place (but organized into proper sub-folders, of course).

**Comment by misaugstad** [comment]
Not to mention `public/javascripts/SVLabe/img`, `public/javascripts/SVLabe/css`, `public/javascripts/SVLabe/audio`, `public/javascripts/SVValidate/img`, `public/javascripts/SVValidate/css`...

The organization was determined before I got here, and I was like "I really don't know what is standard" so I haven't bothered refactoring. I would very much welcome a refactoring though

**Comment by jonfroehlich** [comment]
Great, I think you and I can work on this in the future. Low'ish priority for now.
