### ISSUE TITLE
In the new CSS grid on landing page with stats, why do we have an href to validate?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2271]
@jstadeusiak did a great job on the new landing page background image design. One question I had, however, was why we have `a href`s in the code below. This is in `index.scala.html`

![image](https://user-images.githubusercontent.com/1621749/94295249-cdc72d00-ff15-11ea-8eb2-74aaede920fc.png)

@jstadeusiak, would you mind answering that question?

**Comment by misaugstad** [comment]
Oh that was actually always there... Though I think in the past it used to work lol. I forgot to test that it still worked after @jstadeusiak made that PR. But yeah if you clicked on the number of labels validated, it would bring you to the validation page.

**Comment by jonfroehlich** [comment]
I don’t think it currently works. At least it didn’t work in my local dev environment IIRC. 

I also don’t think we need it,and I don’t think the user expects it to be clickable

**Comment by misaugstad** [comment]
Yeah definitely not necessary. And definitely doesn't work rn.

**Comment by jstadeusiak** [comment]
Yeah, was already there when I began working on it, I left it alone.  Seems like a super easy fix if its just pulling it out I can go ahead and do that. Sound good?

**Comment by jonfroehlich** [comment]
Yep sounds good to me too
