### ISSUE TITLE
Update queries to use 'US/Pacific' instead of 'PST'

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2272]
##### Brief description of issue/feature
We convert a few timezones in SQL queries from UTC to PST, but that's only correct from November to March. But during daylight savings time, we should be using PDT. So right now those times are off by an hour.

##### Expected behavior
My clock shows Fri Sep 25 1:20 PM. When running queries to get the current time and converting it to our local time, we want to see "2020-09-25 13:20".

##### Current behavior
If I run what we have now, `SELECT now() AT TIME ZONE 'PST'`, I get "2020-09-25 12:20" (one hour off). If I sub in "PDT" for "PST", I get the correct time.

##### Potential solution(s)
If we use `SELECT now() AT TIME ZONE 'US/Pacific'`, we will get the correct time the whole year.

**Comment by jonfroehlich** [comment]
I think we should also have a global or some other parameter/configure setting for setting the default backend time zone which we then consult to create these queries appropriately

**Comment by misaugstad** [comment]
@johnsonkuang you can just start with changing them to US/Pacific. We can worry about parameterizing later on.
