### ISSUE TITLE
Weekly leaderboard show only show on leaderboard.scala.html and landing page if conditions met

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2276]
The weekly leaderboard should only show up on leaderboard.scala.html (or whatever it's called) and the landing page if certain conditions are met. I think those conditions are something like we need at least ~3-5 active users that week in order to show it.

Related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2177

**Comment by misaugstad** [comment]
closing via #2306
