### ISSUE TITLE
Consolidate page load animations?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2278]
We currently have three different "page load" animations but stored in multiple places. We should have one page load animation and, if possible, have it stored in one location:

**miscAjaxLoader.gif**
![AjaxLoader](https://user-images.githubusercontent.com/1621749/94352548-30eeb780-001b-11eb-8a68-9b2b8596bdba.gif)
`SidewalkWebpage\public\javascripts\SVLabel\img\miscAjaxLoader.gif`

**loader.gif**
![loader](https://user-images.githubusercontent.com/1621749/94352551-3d731000-001b-11eb-8ae7-89a52d10c138.gif)
`\SidewalkWebpage\public\images\loader.gif`

**page-load.gif**
![page-load](https://user-images.githubusercontent.com/1621749/94352555-57acee00-001b-11eb-8e84-984214f7ef3a.gif)
`SidewalkWebpage\public\assets\page-load.gif`

I also propose that we have something a bit more fun and thematic related to Project Sidewalk. Possibly like this (7.2KB):

![ProjectSidewalk_Loading_Animation_Attempt2](https://user-images.githubusercontent.com/1621749/94352568-8d51d700-001b-11eb-92d5-a1fefd087527.gif)

Here's the smaller version (3.5KB):
![ProjectSidewalk_Loading_Animation_Attempt2_Resized](https://user-images.githubusercontent.com/1621749/94352569-92af2180-001b-11eb-9e0a-4b0a967a1b9f.gif)

**Comment by misaugstad** [comment]
Oh this is great. I love the idea of having our own loading animation!

**Comment by jonfroehlich** [comment]
This relates to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/689.

**Comment by jonfroehlich** [comment]
I updated this animation slightly (to make the wheels turn), integrated it into the webpage, and opened a [PR ](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2299).

![ProjectSidewalk_Loading_WheelAnimation3_WithSidewalk_w100](https://user-images.githubusercontent.com/1621749/95028676-ce1ea100-0656-11eb-8193-8930e3934d78.gif)
