### ISSUE TITLE
Tutorial: Learning to walk not very clear

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#228]
**UPDATE: Mar 22**

> Based on recent discussions with Jon:
> We should probably let the user take a step, move to the next location and then let the user mark the curb ramp. 
> 
> Then, we can connect it with the issue of previously applied labels not visible.
> 

OLD Issue Statement:
Learning how to walk wasn’t very clear in the tutorial. The small circle marked ‘here’ is almost covered by the info box. But the actual way of walking straight is clicking one of the arrows that show up (part of the StreetView interface).

![learning_to_walk](https://cloud.githubusercontent.com/assets/2873216/17868293/499edc00-687c-11e6-90ac-0f2db2f2ed1d.png)

**Comment by jonfroehlich** [comment]
What do you mean by the small circle marked clear?

Also, you can double click on a distant part of a road to move in that direction in the GSV interface. Was that not clear from the tutorial?

Finally, after you're done with the tutorial but while completing your very first mission, you should have received some more pop-up instructions guiding you on what to do. Did you receive those instructions?

**Comment by manaswis** [comment]
Re: What do you mean by the small circle marked clear?
When I took the tutorial for the first time, the "double click here" circle was partly hidden under the instruction box. That's what I was referring to in this issue.

Re: Also, you can double click on a distant part of a road to move in that direction in the GSV interface. Was that not clear from the tutorial?
I retook the tutorial and then I saw the mouse image with the 'double click here' text. It wasn't clear the first time.

Re: pop-up instructions
After finishing tutorial and during the first mission, I got instructions on clicking missing curb ramp label but not others.

**Comment by jonfroehlich** [comment]
Maybe we should do a few more pop-up instructions during the first mission then. @manaswis, what instructions do you think we should provide?

**Comment by manaswis** [comment]
This issue can be closed. The addition pop-up instructions is being discussed in other issues. In particular to this one, the walking straight instruction can be more explicit in the first mission by showing an instruction to the user after he/she takes his first few steps saying something like: "Do you know you can double click the road to move ahead? Why don't you give it a try?"

**Comment by jonfroehlich** [comment]
I like this. Good idea. Two separate things:

1. Do we want to pop this up even if the user is already double clicking to walk?

2. Once the pop-up has occurred, do we want to actively monitor to see if they actually do it and then intervene again if they don't?

**Comment by manaswis** [comment]
Closed via #696
