### ISSUE TITLE
Possibly remove old test code

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2283]
I believe that @kotarohara wrote tests for the backend in the tests dir and the front end in public/javascripts/SVLabel/spec. By the time I started (3 years ago) the tests were not being used or updated as code as changed/added. This has continued for another 3 yeras, and now the tests are completely out of date to the point of being pretty much meaningless IMO. I think that we may as well just delete the current suite of tests. It's just clutter in the code that sbt complains about sometimes and you sometimes accidentally open a test file when searching for something in your IDE.

If we ever have the bandwidth to write tests again, we should probably start from scratch with a fresh test suite #1086

Thoughts @jonfroehlich ?

**Comment by jonfroehlich** [comment]
I agree!

**Comment by misaugstad** [comment]
Just realized that the app/assets/ directory that just holds favicon.png can be deleted when the tests are deleted. It's also located in public/images/ and any uses of it outside of the tests use the one in public/images.
