### ISSUE TITLE
Improve function header comments in UserProfileController.scala

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2284]
In reviewing the code for `UserProfileController.scala`, I noticed that there are a number of methods without comments. The class itself is also poorly commented/described. I think this would be a fast task for @misaugstad that would really improve code approachability. As a relative newcomer to the code, it's not always clear to me how the backend is architected, how the pieces fit together, and where methods should exist. As one example, I added the method `getDistanceAudited(user.get.userId)` to the MissionTable which returns the full distance a user has audited (and sits alongside the method `getMetersAuditedInCurrentMission` but the suggestion was to move this to `UserProfileController.scala` (which I'm now doing but again, without good class definitions, it's hard to know where things should live).

![image](https://user-images.githubusercontent.com/1621749/94558577-e33d9f00-0214-11eb-8ff8-9baf065be5b0.png)

**Comment by misaugstad** [comment]
I agree that the methods should have associated comments. Though part of the confusion is definitely misreading my suggestion that you _call_ the `getDistanceAudited` method from `UserProfileController.scala`, not that you move it there. You had the correct organization, where you put the `getDistanceAudited` function (which accesses the database) in a "model" file.

**Comment by jonfroehlich** [comment]
Sure. Thanks. In addition to methods, all classes should have some comments describing them. :)
