### ISSUE TITLE
Gallery load makes too many API calls

### ISSUE THREAD

**Issue by kumararoosh** [ProjectSidewalk/SidewalkWebpage#2287]
##### Brief description of issue/feature
The current implementation of the Sidewalk Gallery results in thousands of calls to the Google Maps API, costing about $7 per page refresh.

##### Expected behavior
Since only 10 images are shown at a time, a google maps API call should only occur for the images being shown to the user.

**Comment by ThatOneGoat** [comment]
A quick fix has been pushed. Waiting to hear back from Mikey about whether it worked or not.

**Comment by ThatOneGoat** [comment]
This appears to be resolved. Closing to keep tasks clean
