### ISSUE TITLE
Labels disappear from the interface after moving

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#229]
During onboarding, after we pan the whole intersection, coming back to the first view that we had labeled, all the labels that we marked weren’t visible on the interface. The text says we marked it but the interface doesn’t show it has. 

Similarly on the usual audit screen, after zooming in, all the labels for the ramps disappear from the screen even when they are visible in the walk screen.

<img width="1280" alt="screen shot 2016-08-22 at 11 50 59 am" src="https://cloud.githubusercontent.com/assets/2873216/17868484/06b318d8-687d-11e6-8d52-d343634f07ab.png">

**Comment by jonfroehlich** [comment]
Sounds like there are two problems. Can you clearly document them both via video please?

Jon

**Comment by manaswis** [comment]
This is the video where you can't see the labels: https://drive.google.com/file/d/0B9l0KlVSh-2RWjBkVWZhYkF2Rzg/view

Here are some screenshots where:

Image 1: First, I wasn't able to see the labels on the GSV screen
<img width="1280" alt="screen shot 2016-08-22 at 4 47 16 pm" src="https://cloud.githubusercontent.com/assets/2873216/17871553/12590fe6-688a-11e6-81be-5ad056a483cb.png">
<img width="1280" alt="screen shot 2016-08-22 at 4 47 22 pm" src="https://cloud.githubusercontent.com/assets/2873216/17871551/12561750-688a-11e6-8a55-3e575a7429ff.png">

Image 2: Then, after zooming in I was able to see them (which didn't work in the video).
<img width="1280" alt="screen shot 2016-08-22 at 4 47 34 pm" src="https://cloud.githubusercontent.com/assets/2873216/17871552/125637ee-688a-11e6-82be-9315dd191c16.png">

**Comment by jonfroehlich** [comment]
Yah, not sure what is going on here. Notice also that the green/red line in the top-down map is not shown. Perhaps @kotarohara can shed some light on what's happening. 

Thanks for taking this video and expanding a bit on the problem.

**Comment by jonfroehlich** [comment]
A few things:

- Is this only during onboarding?
- You do realize that we can never show you previously placed labels from a different GSV location than the one you placed them... and though you said you returned to the same place, it's possible that you return to a nearby GSV location

**Comment by kotarohara** [comment]
Is this a still valid issue?

**Comment by manaswis** [comment]
No, this can be closed. The issue of labels not being visible on the GSV screen has been discussed and clarified in the meetings.

**Comment by jonfroehlich** [comment]
We need to figure out a way to address this however, even if just in the FAQ
