### ISSUE TITLE
Sidewalk Gallery: Create query to grab assorted images for initial load of Sidewalk Gallery landing page

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2293]
Currently, our landing page for Sidewalk Gallery is very sparse. 

Our plan is to load a variety of recent labels based on type, severity, and possibly even tag, about 21 or 30 for the initial load.

**Comment by jonfroehlich** [comment]
And the 21 or 30 was not chosen arbitrarily: it's based on the fact that we're currently rendering three images to a row. If we change this to, say 4, then the number of images we show on initial low should be evenly divisible by four. :)
