### ISSUE TITLE
Sidewalk Gallery: Implement Sidewalk Gallery sidebar for filtering/selection

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2295]
Currently, the design of the Sidewalk Gallery page is bare and tacky.

Here is Jon's proposed mock of the Sidewalk Gallery UI which we are aiming for:
![image](https://user-images.githubusercontent.com/37346427/94974967-0b532980-04c5-11eb-9899-84bfe5f23cbb.png)

**Comment by jonfroehlich** [comment]
A couple of quick comments about my mock:

- Not sure yet on whether we want to say "Show" or "Filter" and whether all of those checkboxes, etc. should be filled in on initial load (they probably should be, right?). 
- For Tags, I was expecting this to be dynamic based on what label types are current selected
- I wonder if we should somehow indicate the number of things we have for each type—for example, Tree would be Tree (192) and Vegetation (341) where those parantheticals represent the number of times those tags have been used in our database. Similarly, we could have that for the label types too: Curb Ramp (4,012), Missing Curb Ramp (1,321), etc. (but this additional info risks overwhelming the user, so maybe just display it in a tooltip or mousehover)
- It seems like we may want to try 4 or 5 images to a row (as a maximum depending on user browser's width size)

And one primary objective of our user experience is speed and interactivity: we want to allow users to quickly browse, search through, and filter sidewalk images/labels quickly.

**Comment by jonfroehlich** [comment]
In terms of the sidebar, I wouldn't reinvent the wheel here. Use a standard CSS template/approach for this. Google around and make a well-informed choice.

One question is whether it "floats" so that it's always viewable regardless of scrolling in the main pane. I say yes. :)

**Comment by jonfroehlich** [comment]
Since you asked, here's the raw mock file.

[SidewalkGallery.pptx](https://github.com/ProjectSidewalk/SidewalkWebpage/files/5344423/SidewalkGallery.pptx)

**Comment by kumararoosh** [comment]
![sidewalk-page-ideation](https://user-images.githubusercontent.com/24703104/95542358-69db4480-09aa-11eb-9bcf-43e2b3e8b879.png)

Here is the mock that @ThatOneGoat and I created after some talking. Note that the show dropdown should be before the sort by dropdown.

Here is the full PowerPoint with all of our steps of ideation:
[SidewalkGallery.pptx](https://github.com/ProjectSidewalk/SidewalkWebpage/files/5352465/SidewalkGallery.pptx)

**Comment by jonfroehlich** [comment]
Looks great to me. Go team!

A few comments:
- Add slightly more vertical space (margin-top) with the Sort By, Show, and Filter By headers and the sub-header Tags
- Not sure what the 'Other Filters / Map' is but my guess is it's not for the MVP?
- We'll have to decide what we want for the Show widget. A drop-down menu is simple and easy to use but requires a click to see the interactive elements, so makes it slightly more difficult to easily browse and explore different label types.
- When 'Assorted' is selected in the Show drop down, there will be lots more 'tags' than you're currently showing in your mock. How to handle that?
- In our notes doc, I talked about somehow highlighting how many of each thing we have but your mock doesn't incorporate that idea. For example, in GitHub, I can see how many current Issues and PRs we have: 
![image](https://user-images.githubusercontent.com/1621749/95581429-e3485680-09ed-11eb-84b5-a02312b6127e.png). I think we need something similarly for Label Types, Tags, and maybe even severity (which will be harder given how its currently visualized but maybe you do it via a tooltip?)

**Comment by kumararoosh** [comment]
![image](https://user-images.githubusercontent.com/24703104/95938875-a71b4a00-0d8f-11eb-8f06-f67bba1fe9af.png)
This is what we have right now as shown in the mock, we still have to makes changes to the card generation in order to minimize the chance of having such a large space on the side

**Comment by jonfroehlich** [comment]
Nice progress. Is this a live shot? I would make the side bar on the left narrower so you have more room for content on the right. Again, take a look at similar "gallery" like applications. The sidebar tends to be ~200-250 pixels. For example:

![image](https://user-images.githubusercontent.com/1621749/95988735-2fc0d700-0dde-11eb-850d-c5a66aea0b4d.png)

Many of my other comments/feedback in this Issue thread still apply but I'm guessing you're still working on them.

Awesome to see the progress here and I can't wait to use it!
