### ISSUE TITLE
Mission complete dialog box shows up after retaking the onboarding tutorial 

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#230]
After completing onboarding tutorial and pressing ‘OK’ (in the image), I am brought back to the same interface (see image 2). Only after clicking the walk straight arrow, the mission complete sound and box shows up, and then the next mission is shown (image 2).

![f1](https://cloud.githubusercontent.com/assets/2873216/17868624/9ae6589e-687d-11e6-8dba-c75fadd37292.png) Image 1: After onboarding completion screen. Ignore the red circle (that was to show the spelling mistake and I didn't have another image of this screen).

![after_onboarding](https://cloud.githubusercontent.com/assets/2873216/17868718/0a26a6be-687e-11e6-8357-fc532d3db2a6.png) Image 2: Back to the same interface

**Comment by jonfroehlich** [comment]
Hmm, this definitely doesn't seem right. @kotarohara, can you investigate?

**Comment by kotarohara** [comment]
@manaswis I don't really understand the problem but it sounds like a problem :) What is happening?

**Comment by jonfroehlich** [comment]
Also, @manaswis, did add in an Issue to fix the 'a head' -> 'ahead' -- if not, can you do that. It's an easy fix and should be completed.

**Comment by kotarohara** [comment]
I fixed the typo! Thanks @manaswis

**Comment by manaswis** [comment]
@kotarohara This was a singular instance. It happened the first time I took the tutorial. I will try to recreate it later today. 

So the problem was when I clicked the OK button (Image 1), the mission complete animation (w/ cheering audio) didn't show up immediately. When I walked straight on the next screen (image 2), it showed up. It didn't happen the next time I took the tutorial.

**Comment by jonfroehlich** [comment]
@manaswis, is it possible you walked in some strange direction during the tutorial?

**Comment by jonfroehlich** [comment]
@manaswis, can you please investigate this more closely. The tutorial is crucial to Project Sidewalk but we're having trouble recreating this issue.

**Comment by manaswis** [comment]
Yes, I am on it.

**Comment by manaswis** [comment]
Here is the video: https://youtu.be/D4KBhnOpBx0?t=2m13s

Its set to start at 2.13s. Notice how in the bottom right corner, the box appears. I continue with the tutorial following the instructions on the top left corner. Skipping those to 2.39s. - https://youtu.be/D4KBhnOpBx0?t=2m39s
You can see when press that bottom-right box, then the mission animation shows up.

**Comment by jonfroehlich** [comment]
Right, to be clear, Manaswi found two problems. One at 2.13s and another at 2.39s in the video links above.
