### ISSUE TITLE
Sidewalk gallery: how to support validations in Sidewalk Gallery

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2303]
Need to think about and mock some designs for allowing users to quickly validate labels in Sidewalk Gallery. @aileenzeng had an original implementation of this. @ThatOneGoat or @kumararoosh, can you copy some screenshots of that implementation below.

We discussed various ways to do this in our meeting: 
- Via mouseover (user mouses over the card and we show agree, disagree, unsure; upside of this solution is it's super convenient and visible. Downside is that it's perhaps too salient and disruptive?)
- Via expansion. User clicks on card and we show an expanded version of the card or a pop-up

**Comment by misaugstad** [comment]
And for the back end, validations need to be tied to a "mission" right now. The easiest thing to do (which is what we did for validations through Label Map) is to just make a new mission type, and when a user does their first validation through Gallery, make a new mission of that type for them. Then all their future Gallery validations can be tied to that one mission you created.
