### ISSUE TITLE
Switch leaderboard data to async call and add back to landing page

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2307]
The leaderboard data is currently being fetched in the template scala, which means that it needs to have fully loaded before the page loads. On our largest cities (Seattle) this will take upwards of 3 seconds, too long to wait to load the landing page. We need to switch this to an async ajax call in the JavaScript instead, so that the page can load before the leaderboard tables are filled in.

I think that essentially what this will look like is that you will add a new endpoint to get the leaderboard data. The endpoint will basically call the `UserStatTable.getLeaderboardStats()` function, convert the data into JSON, and send it. You'll call this endpoint from JavaScript (either a script directly in `leaderboard.scala.html` or in a newly created file) and then fill in the table elements from the JavaScript code, using the results of the ajax call.

**Comment by misaugstad** [comment]
@jonfroehlich for a short time we had the leaderboard on the landing page, but it made the page take too long to load. Do we still want to include this in the landing page? We can make the call to get the leaderboard data async so that it doesn't impact initial page load. I figure that I should either assign this to an intern or close the ticket!

**Comment by jonfroehlich** [comment]
I think rather than having on landing page, we could consider having it as its own item on the menubar.
