### ISSUE TITLE
Panning and zooming in and out creates distorted images

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#231]
![distorted1](https://cloud.githubusercontent.com/assets/2873216/17868854/a161ec96-687e-11e6-82d6-f0d0bb1bfb89.png)
![distorted2](https://cloud.githubusercontent.com/assets/2873216/17868855/a1669ef8-687e-11e6-90fb-702ad3ad1251.png)

**Comment by jonfroehlich** [comment]
This is an artifact of Google Street View and will not be fixed.
