### ISSUE TITLE
Bug: Date registered later than date last logged in?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2311]
On the SPGG server, we have a user with a date registered as Sept 14, 2020 but last login as Sept 10, 2020. How is that possible?

![image](https://user-images.githubusercontent.com/1621749/95928948-8c3cdb80-0d77-11eb-98aa-1d4109d5f48b.png)

**Comment by misaugstad** [comment]
Yeah it looks like the registered/login dates are messed up on the admin page. I think our query is just messed up right now.
