### ISSUE TITLE
Make first mission even shorter!

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2324]
Previously, we discussed making the first mission shorter: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/841 —from 1,000 ft (which took 16.9 minutes, on average, to complete) to 500 ft (~8.45 minutes). And we did this.

I think we should consider making the first mission even shorter—something like 250 or 300 ft. From [Wikipedia](https://en.wikipedia.org/wiki/City_block#:~:text=The%20standard%20block%20in%20Manhattan,adopted%20by%20other%20US%20cities.):

> The standard block in Manhattan is about 264 by 900 feet (80 m × 274 m). In Chicago, a typical city block is 330 by 660 feet (100 m × 200 m), meaning that 16 east-west blocks or 8 north-south blocks measure one mile, which has been adopted by other US cities.

The key is in allowing a user to feel successful and enabling them to have a relatively "quick" win. As now, with a 5-minute tutorial + a 500 ft first mission, that's almost a 14 minute ask. We could cut this down to 10-minutes by shortening that first mission. I also think we should continue to think of ways of limiting the introductory tutorial.

**Comment by misaugstad** [comment]
Yeah I think that making the first mission shorter had bigger downsides before we implemented resuming an audit in the middle of a street. Now that we have that, we really aren't wasting any data, and we should be able to arbitrarily mess with mission lengths. And changing the lengths should be quite easy tbh.

I think the first time we make this change, I'll probably want to do it so I can carefully look around to see if we are making assumptions about the mission lengths anywhere. But theoretically it should be a very quick update.

**Comment by jonfroehlich** [comment]
Great! We may want the first **two** missions to be 250ft and then possibly graduate to 500ft. Not sure if we'll ever want 1,000ft since 17 minutes is a huge ask. Thoughts?

**Comment by misaugstad** [comment]
Yeah I think that makes sense. We can just keep making the missions shorter :) it's probably more fun for users. We should think about how this effects the proportion of validations we get to the total number of labels. If we are low on labels but have plenty of validations, then we may want to consider reducing the number of validations in a mission. Or decreasing the number of validation missions before we send users back to exploring. Or if we are low on validations, then just decreasing explore missions lengths is perfect.

**Comment by jonfroehlich** [comment]
After doing the mapathon today, I really think shorter missions are better... 0.5 miles is just too far I think (ever). So, we should keep things shorter. Curious what @kumararoosh thinks now that he's on the leaderboard!
