### ISSUE TITLE
Map avatar view indicator on sidebar

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2329]
In exploring Bing's GSV competitor (called "Streetside"), I discovered that there mini-map view (top-down map) showing what the avatar is looking at in 3D space is quite elegantly designed:

![image](https://user-images.githubusercontent.com/1621749/96875316-ef8bd500-142b-11eb-95bb-1f364dc7ea76.png)

See video https://youtu.be/glwmXFiLGRM

Indeed, in [some previous incarnations](https://makeabilitylab.cs.washington.edu/media/publications/Hara_ImprovingPublicTransitAccessibilityForBlindRidersByCrowdsourcingBusStopLandmarkLocationsWithGoogleStreetViewAnExtendedAnalysis_2015.pdf), we used to do two things: first, we would show you a field-of-view indicator (similar to Bing Maps design above); second, we would "gray out" parts of the minimap until you looked at them:

![image](https://user-images.githubusercontent.com/1621749/96874971-90c65b80-142b-11eb-8f5a-afc5f05a8f39.png)

This "grayed out" until you "explore" or "look at" the area was inspired by real-time strategy games like Warcraft or Command and Conquer, which have "unexplored" areas of your map in black until you send units to look at them:

![image](https://user-images.githubusercontent.com/1621749/96874710-4c3ac000-142b-11eb-9056-81392ee49a05.png)

**Comment by misaugstad** [comment]
I believe that this will actually be resolved as a subset of #1316 which @shokiami is taking on, so I'm going to assign this one to you too.

**Comment by misaugstad** [comment]
closing via #2860
