### ISSUE TITLE
Transition from old mission to new mission is a bit confusing

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#233]
There are two issues with the transition text from old to new mission:

1) Next mission’s instruction text (shown below) looks extremely similar to the old mission text if the audit is being done in the same neighborhood. (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/234)
<img width="1280" alt="screen shot 2016-08-22 at 11 41 51 am" src="https://cloud.githubusercontent.com/assets/2873216/17869079/9a1710e6-687f-11e6-9489-620b44787c59.png"> 

2) The next interface screen shows 100% done when the new missions starts. But once I start walking straight, it resets to 0.

<img width="1280" alt="screen shot 2016-08-22 at 11 42 04 am" src="https://cloud.githubusercontent.com/assets/2873216/17869077/9a0cf322-687f-11e6-8840-07bb43e638db.png">

**Comment by jonfroehlich** [comment]
I agree that the next mission screen could really be improved (indeed, here's one suggestion on that: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/94; I had also previously suggested that the Mission Complete dialog and the Next Mission dialog should be combined in someway).

I think the key point you make here is that the mission screen seems so similar to the last mission screen that it's not clear to the user that they are on the next mission. This is a problem and probably should be fixed (though no one else has pointed it out...). Pinging @kotarohara to bring him in on the discussion.

The easiest fix I can think of is to just continue incrementing missions and showing the counter somehow. So, we should say something like 'Mission 5' or 'Mission 6' when they are on that mission for the given neighborhood (or maybe 'Your 5th Mission: XXXX' or 'Your 6th Mission: YYYY.' Still, this is an imperfect solution as the user will have to remember that this number has been incremented.

Thoughts?

**Comment by kotarohara** [comment]
For the same reason as #234 , I'm removing this from public deployment. 

@manaswis What's the difference between #234? If they are the same issue, you should not create a new issue. Instead, use comment to append your thoughts on the related issue.

**Comment by jonfroehlich** [comment]
@kotarohara: Can't we just do what I said for the easy fix? This would take < 1 hour to implement imo. 

> The easiest fix I can think of is to just continue incrementing missions and showing the counter somehow. So, we should say something like 'Mission 5' or 'Mission 6' when they are on that mission for the given neighborhood (or maybe 'Your 5th Mission: XXXX' or 'Your 6th Mission: YYYY.' Still, this is an imperfect solution as the user will have to remember that this number has been incremented.

The problem is that right now the same mission screens keep coming up and it's not possible to tell them apart from previous missions so the user starts to think something is broken. There is no indication by the UI that this is a *new* mission and that they are exploring new parts of the assigned neighborhood.

**Comment by manaswis** [comment]
@kotarohara In this issue, I was talking about the whole transition as a complete unit, which includes the last image. When the next mission starts, in the last image, the mission is shown as complete (100% in the progress bar). When you start walking, then the mission progress bar goes back to 0%. So that might be confusing.

I added https://github.com/ProjectSidewalk/SidewalkWebpage/issues/234 coz the mission text seemed like a different issue. I think the last image also can be an issue, but I leave it upto you to decide if another issue is needed for that. :)

**Comment by jonfroehlich** [comment]
@kotarohara, @manaswis's right, when we display the new mission dialog, the underlying progress bar should reset to 0%. Currently, it does not do that.

![image](https://cloud.githubusercontent.com/assets/1621749/17898549/2a90b432-6926-11e6-8bfa-d4e8ceaedb3a.png)

**Comment by manaswis** [comment]
Clarified the text of the issue.
Issue 1 is covered by #234 and Issue 2 has been taken care of. 

This issue can be closed now.

**Comment by jonfroehlich** [comment]
I don't think this can be closed as there is information in this Issue not captured in #234.

**Comment by kotarohara** [comment]
@manaswis , please work on this.

**Comment by manaswis** [comment]
Have added the missing information from this issue to #234. Closing this issue now.
