### ISSUE TITLE
Small text error on user dashboard

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2335]
Seen below, the message for earning all mission badges is messed up and says that you've earned all labeling badges. This is only messed up on the English version.

**Comment by jonfroehlich** [comment]
Good catch! I’m not seeing a screenshot to go along with this...

**Comment by jonfroehlich** [comment]
Here's the screenshot to go along with this. The text for missions incorrectly states: "Congratulations, you've earned all labeling badges." but should state: "Congratulations, you've earned all mission badges."

![image](https://user-images.githubusercontent.com/1621749/97080828-250efa80-15b3-11eb-8740-e4b8bb4e857e.png)
