### ISSUE TITLE
Sidewalk Gallery: Implement a Modal Overlay to show more card information

### ISSUE THREAD

**Issue by kumararoosh** [ProjectSidewalk/SidewalkWebpage#2336]
##### Brief description of issue/feature
Add a sidebar that allows for more info to be seen once an image is selected, and allow the user to perform validation on the sidebar

**Comment by kumararoosh** [comment]
Here are two different mocks for how we could implement it:
![SidewalkGallery](https://user-images.githubusercontent.com/24703104/97068830-ef9ce980-157f-11eb-8843-1a2e1d313522.png)
![SidewalkGallery_2](https://user-images.githubusercontent.com/24703104/97068832-f4619d80-157f-11eb-95f4-5bcee15e8356.png)

**Comment by jonfroehlich** [comment]
How about a mock with the enlargement shown in the center of the screen (or centered on the main content div) and then with arrows to go back and forth to quickly navigate between the thumbnails?

**Comment by ThatOneGoat** [comment]
Something like these?
This one just has the card expand out, shifting the other cards around it outwards (takes up the space of 6 unexpanded cards, so we'll have to figure out where the cards go to).
![image](https://user-images.githubusercontent.com/37346427/97135315-2a805800-170d-11eb-9379-6b014a478dc1.png)

The other way Is just having the card popup as a separate modal kind of like on the admin page:
![image](https://user-images.githubusercontent.com/37346427/97135394-5996c980-170d-11eb-8f33-014f8263ecae.png)
(Also, note I forgot to fill in a row in the pic)

**Comment by jonfroehlich** [comment]
I like the second one personally. It’s what I was envisioning. What do you think is better of the options so far? And why?

**Comment by ThatOneGoat** [comment]
I don't mind the 2nd one either, but I personally like either of the two mocks Aroosh put up earlier more. Firstly, it's based on Google Images (so it's already tried and true), and it feels like the whole screen is being used effectively. I also feel like it's important we allow the users to still interact with the gallery (like select a different card rather than having to use arrows) even after a card is selected. The modal version creates a level of separation between gallery view and card view that could be a little unintuitive.

**Comment by jonfroehlich** [comment]
I just re-used Google Image search and I agree with you @ThatOneGoat. Let's try to mimic that behavior! Wo0t! Let's go with something from here: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2336#issuecomment-715730981

I think the specific design of that "more info" card needs to be iterated upon but we can discuss that as you begin working on the layout and overall functionality.

**Comment by misaugstad** [comment]
closing via #2570
