### ISSUE TITLE
Maybe have an uplift or height difference tag?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2339]
In response to this screenshot:
![image](https://user-images.githubusercontent.com/1621749/97108573-ba7dbd80-168b-11eb-85c7-a046be7c964f.png)

We may want to have an "uplift" or "height difference" tag for surface problem? See this [categorization scheme by Seattle DOT](https://sdotblog.seattle.gov/2017/08/28/seattle-sidewalk-survey-update/):

![image](https://user-images.githubusercontent.com/1621749/97108563-a89c1a80-168b-11eb-8eb1-f56988e3a575.png)

**Comment by misaugstad** [comment]
Yeah I think that right now we are using the obstacle in path "large step" tag if it is really bad. But I think "uneven" is good for surface problems. I think one issue is that when we changed it from "uneven" to "uneven/slanted" it doesn't really read as "uneven or slanted", it kind of reads as just "slanted"... I have been thinking about this lately and wondering if we want to rename to "uneven or slanted".

**Comment by gari01234** [comment]
In the Spanish version we are using "desnivel"
![imagen](https://user-images.githubusercontent.com/50057640/97308349-1188bb80-1861-11eb-8371-f0686fbfc9dc.png)

**Comment by misaugstad** [comment]
Yeah and I think the Spanish translation is better than the English one :) We could even consider changing "large step" to "height difference" or "height change"... "change in height"

**Comment by misaugstad** [comment]
@jonfroehlich do you have further thoughts on this? We were aiming to have "large step" cover this situation. Do you think a name change is appropriate?

**Comment by jonfroehlich** [comment]
I wouldn’t categorize that example screenshot as a step (I often associated “step” as something designed rather than something that occurs as degradation as weathering, etc)

**Comment by misaugstad** [comment]
Right. So what are your thoughts on the suggested name changes of "height difference", "height change", or  "change in height"?

**Comment by jonfroehlich** [comment]
Yah, maybe "height difference" and then "slanted" is its own thing?

**Comment by misaugstad** [comment]
@jonfroehlich Great, so do you feel like "height difference" works well as an obstacle tag? Or should it be a surface problem tag? I lean towards obstacle? But the line is sort of blurry for something like this

**Comment by misaugstad** [comment]
@jacknussbaum when we decide on the final text, note that you'll want to change the name using an evolutions file. You can start by looking at old PRs that modify the tags, and you can ask around about evolutions files (I know that @ThatOneGoat and @shokiami have used them in the past).

**Comment by jonfroehlich** [comment]
@misaugstad and I just talked about this and decided on putting "height difference" for both obstacle and surface problem label types—a decision that we will no doubt regret in a year. Hahah!

**Comment by jacknussbaum** [comment]
@misaugstad could I get the translation for "height difference" por favor?

**Comment by misaugstad** [comment]
@jacknussbaum the Spanish translations is staying the same with "desnivel". "large step" for obstacles should be changed to "height difference" as well.
