### ISSUE TITLE
Next mission text needs more clarity

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#234]
The next mission text sometimes looks very similar to the old ones (maybe coz of the old missions being in the same neighborhood), which might be confusing.

Modifying the text by one connecting to the old mission and then the new mission text would help. E.g. "Brilliant! You covered x miles in your last mission in X neighborhood." Then the new mission text..

<img width="1280" alt="screen shot 2016-08-22 at 11 41 51 am" src="https://cloud.githubusercontent.com/assets/2873216/17869297/ad978db6-6880-11e6-8298-ef6c40285f59.png">

**Comment by jonfroehlich** [comment]
This is related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/233 and https://github.com/ProjectSidewalk/SidewalkWebpage/issues/94

**Comment by kotarohara** [comment]
@manaswis Can you mock them up?

@jonfroehlich I don't think this will go to public deployment. I'm removing this from the milestone.

**Comment by kotarohara** [comment]
@manaswis Please work on this. Let me know if you need help.

**Comment by manaswis** [comment]
Consolidating information for this issue from #233 here:

Jon's suggestion:

> I agree that the next mission screen could really be improved (indeed, here's one suggestion on that: #94; I had also previously suggested that the Mission Complete dialog and the Next Mission dialog should be combined in someway).
> 
> I think the key point you make here is that the mission screen seems so similar to the last mission screen that it's not clear to the user that they are on the next mission. This is a problem and probably should be fixed (though no one else has pointed it out...). Pinging @kotarohara to bring him in on the discussion.
> 
> The easiest fix I can think of is to just continue incrementing missions and showing the counter somehow. So, we should say something like 'Mission 5' or 'Mission 6' when they are on that mission for the given neighborhood (or maybe 'Your 5th Mission: XXXX' or 'Your 6th Mission: YYYY.' Still, this is an imperfect solution as the user will have to remember that this number has been incremented.

**Comment by misaugstad** [comment]
closing in favor of newer issues on the same topic like #1323 #1798 and #2152
