### ISSUE TITLE
Remove rapid validation interface code?

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2356]
We have a prototype for a "rapid validation interface", that didn't pan out. See critique/discussion in #1845 

I don't really see that interface becoming useful, so I would ideally like to remove the associated code (I'm on a bit of a code cleaning kick right now). What are your thoughts @jonfroehlich ? Are you good with nixing it, or do you want to keep the code around for awhile?

**Comment by jonfroehlich** [comment]
Absolutely, we should remove it. I also think it felt a bit kludgey in terms of its integration... but that could 100% be my naivete. However, if we want another validation mission type in the future, may want to consider architecturally what's cleanest.

Also, I feel like Sidewalk Gallery could become another incarnation of the "rapid validation interface"... even though that's not it's primary goal.
