### ISSUE TITLE
Red route in the top-down map  should load a little before reaching the intersection

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#236]
Top-down map doesn’t show the complete path when close to the intersection while the progress bar shows the mission is half done. Top-down map path ends at the intersection. It loads the route at the intersection. It should load a little before the intersection when the intersection is visible in the top-down map. 

Not loading before gives the feedback to the user that his mission is near complete, while the progress bar says something else.

<img width="1280" alt="screen shot 2016-08-22 at 11 47 29 am" src="https://cloud.githubusercontent.com/assets/2873216/17869678/5aa02f80-6882-11e6-9f37-1404afedfc56.png">

**Comment by misaugstad** [comment]
I don't remember when this was implemented, but it happened! We now load the next street a decent amount of time before the intersection :ok_hand:
