### ISSUE TITLE
Sidewalk gallery: filtering examples

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2360]
On Sparkfun's sidebar, it's an exclusive 'AND.' As you select more things, you drill down. Their 'star rating' interface also provides an additional example of how to potentially handle our severity filtering. Here's an [example query with LEDs](https://www.sparkfun.com/search/results?term=leds). Note that it shows which options you are selected at the top too.

![image](https://user-images.githubusercontent.com/1621749/98876795-dfb44f00-2433-11eb-93b6-e4a3c85953d2.png)

Amazon's website also uses checkboxes and has a similar 'star rating' design:

![image](https://user-images.githubusercontent.com/1621749/98877368-2eaeb400-2435-11eb-908e-062283dc00fb.png)

**Comment by ThatOneGoat** [comment]
![image](https://user-images.githubusercontent.com/37346427/98877504-80efd500-2435-11eb-8b75-21f630cf8caa.png)
https://www.gettyimages.com/photos/cats?family=creative&license=rf&phrase=cats&sort=mostpopular#license

**Comment by jonfroehlich** [comment]
With @isavin12's assistance, I think we're pretty good here. We can continue to look for design inspiration from other sites that allow complex querying/filtering on left sidebar (target.com is another one, for example).

One nice thing about target.com is the "Sort by" dropdown in top-right. We can similarly allow for sorting based on 'Severity, label age, and validation accuracy."

![image](https://user-images.githubusercontent.com/1621749/123462223-e0eb5400-d59e-11eb-9783-5d1841a89928.png)
