### ISSUE TITLE
Are contributions still being saved?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2368]
@Gari01234 just DM'd me this morning and shared a screenshot showing that no contributions are being shown on the backend for SPGG. Is this a problem with actual data getting uploaded or simply a bug in the backend admin tool in showing us the data?

![image](https://user-images.githubusercontent.com/1621749/99302319-10193600-2804-11eb-98d2-2e415e500347.png)

**Comment by misaugstad** [comment]
@gari01234 do you know that someone was contributing during those two days? I just tested out adding some labels right now and it showed up on there. And I'm looking through the logs from this weekend and I'm not seeing much. Are you sure it wasn't just that no one contributed data for two days? Or do you know of someone contributing?

**Comment by gari01234** [comment]
@misaugstad  This is the first time I see that there are no contributions in two days, but it may be possible, of course. 
Next time I will first review the table of contributions before jumping to assumptions. Sorry about that!

**Comment by misaugstad** [comment]
No worries! Keep looking out :)
