### ISSUE TITLE
Is there press outside of DC we can put on the landing page?

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2373]
The landing page only has press from DC right now. I feel like I remember there being some press from other cities we've deployed in as well. We should include those, and we can make the press specific to each city.

**Comment by misaugstad** [comment]
Here's what it looks like now:
![Screenshot from 2020-11-17 00-51-29](https://user-images.githubusercontent.com/6518824/99368250-c108ea80-286f-11eb-8bb2-cd85120cd667.png)

**Comment by jonfroehlich** [comment]
We do have press from other cities now (like Amsterdam). Should we eliminate this block all together or keep it updated with new press for each city?

**Comment by misaugstad** [comment]
Great question 😅 I personally don't want to deal with the upkeep of the "Press" or the "What people are saying" sections. But I have a hard time describing how much we lose by removing either or both of them.

**Comment by jonfroehlich** [comment]
Oh, good point about 'what people are saying'

![image](https://user-images.githubusercontent.com/1621749/163624860-336da968-b11b-4dcb-a8ad-ccc39f35656a.png)

Honestly, for now, I feel like commenting them out. What do you think?

**Comment by misaugstad** [comment]
I'd agree with that. I'd probably prefer to straight up delete the code though since it's so easy to find the code again if we just search for the PR where they are removed.

**Comment by misaugstad** [comment]
When doing this, make sure to search for any CSS and images that is are only used for these specific HTML elements and delete those! We want to keep the code base as clean as possible :)
