### ISSUE TITLE
Make small improvements to admin playback tool

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2381]
I recently fixed up the admin playback tool (shown below). A couple of easy to implement features that I think would make the tool much easier to use:

1. Show a play button instead of automatically playing when the page loads
1. There are a couple parameters I've set in the JavaScript that I'm logging to the console, but we don't have a way to change them unless you're on a local dev environment. We should be able to input those parameters in the webpage. The parameters include playback speed, how long of a pause in interactions to skip over, and how much time to collapse one of those long lapses into. We can also display total watch time.
1. Add a "replay" button. I think this should only be added if it is trivially easy, since we can always just refresh the page to replay.
1. A pause (or even rewind) button would really nice, but is probably harder to implement and therefore not worth it. While I'm implementing the above, if I realize that those features aren't that hard, I might go ahead and implement.

![Screenshot from 2020-11-19 15-12-55](https://user-images.githubusercontent.com/6518824/99735639-d05b8400-2a79-11eb-85c8-56a1c2e78450.png)

**Comment by misaugstad** [comment]
@uditpatwal you can find this tool by going to the admin page, going to the contributions tab, clicking on 'View', and then clicking on the task ID. It will do this replay of the audit of the street where that label was placed.

**Comment by uditpatwal** [comment]
@misaugstad Does something like this look good? Ill change the button names once I figure out a good short name for them. The pause button would be the play button to start it and if we implement pausing, it would do that too.
![Admin Task Page Mockup](https://user-images.githubusercontent.com/34140897/101701776-9d3f5b80-3a4d-11eb-98b2-027a73fadbfa.jpg)

**Comment by misaugstad** [comment]
yeah I think that looks fine, thanks @uditpatwal you can also use the 'refresh' icon we use for the Jump button on the audit page for the replay but I'd think
