### ISSUE TITLE
Reduce vertical size of footer

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2384]
The green portion of the footer just takes up a bit more space than it needs to. We could just decrease the space on the bottom so that there is as much empty space below the text as there is above the text.

![Screenshot from 2020-11-20 14-42-40](https://user-images.githubusercontent.com/6518824/99856876-ccde0080-2b3e-11eb-9269-64d1251c45b4.png)

**Comment by mcdoerr** [comment]
Reduced size footer image, before image is in the thread above:
<img width="1412" alt="Screen Shot 2021-02-01 at 12 44 50 PM" src="https://user-images.githubusercontent.com/45296521/106516003-b388f700-6493-11eb-8930-ce681a91922f.png">

Fix size of footer by reducing min height and setting both top and bottom paddings to 50px. 
Previously, only the top padding was 50px. 
This makes the top and bottom space the same even when the screen size is different.

**Comment by misaugstad** [comment]
Okay yep, that looks nice!
