### ISSUE TITLE
Mission Length

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#239]
I've been at 1/2 mile audit length for a long time in this neighborhood. Is that the max audit length now? What's the mission-by-mission breakdown?

![image](https://cloud.githubusercontent.com/assets/1621749/17915163/564cd6c8-6976-11e6-9194-709203fe90e3.png)

Pinging @kotarohara

**Comment by kotarohara** [comment]
For each neighborhood, we have 1000ft, 2000ft, 4000ft, 1mi, 1.5mi, 2.0mi, ... missions, and 100% Coverage Missions at the end.

**Comment by misaugstad** [comment]
The question in the initial comment has been answered, and improvements are being discussed in #1130, so I am closing this issue now. 😄

**Comment by jonfroehlich** [comment]
And I'm not sure that answer was accurate because I don't think I ever did a 1.5 mile or 2.0 mile mission. Unless his description was cumulative, which seems weird.

**Comment by misaugstad** [comment]
Ahh, and you did ask such a question in #880 😉 It is, in fact, cumulative! How intuitive!
