### ISSUE TITLE
Sidewalk Gallery: Redesign Cards

### ISSUE THREAD

**Issue by kumararoosh** [ProjectSidewalk/SidewalkWebpage#2392]
Redesigned the cards to accommodate for validation and better space use

![image](https://user-images.githubusercontent.com/24703104/99930978-c5b61e80-2d07-11eb-8854-d74bb30a59a1.png)

**Comment by misaugstad** [comment]
I would decrease the height of the buttons by maybe a third. Also reorder them so that they are in the same order as on the validation page (Agree, Disagree, Not sure).
