### ISSUE TITLE
I Can't Walk Straight Due to Construction... What Do I Do and How Does This Affect My Ability to Complete a Neighborhood?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#240]
I can't walk straight due to construction, what do I do? I suppose this means that I will never be able to finish auditing this neighborhood?

![image](https://cloud.githubusercontent.com/assets/1621749/17915190/9e6985fa-6976-11e6-85da-c72607d76508.png)

**Comment by jonfroehlich** [comment]
I ended up doing this. Do we then mark that segment as untraversable so that the user can still get credit for finishing the neighborhood?

![image](https://cloud.githubusercontent.com/assets/1621749/17915215/d5a778ec-6976-11e6-911e-39975e9ef463.png)

**Comment by jonfroehlich** [comment]
Another weird occurrence. I am routed along a path that is disconnected from my current street.

![image](https://cloud.githubusercontent.com/assets/1621749/17915383/1499fdd0-6978-11e6-8280-04101683bd04.png)

**Comment by kotarohara** [comment]
Yes, you get credit if you select "I cannot go to the direction..." before you jump. 

> Another weird occurrence. I am routed along a path that is disconnected from my current street.

That's weird. I originally though that the program mistakenly evaluated that the two streets segments shown on the Google Maps are connected. This could be the case as the program uses a short distance threshold (don't quite remember the value) to assess whether two street segments are connected or not. But by looking at the Google Maps again, I think the two streets are too far away to each other...

I don't think that happens a lot, so I don't think it's a super high priority issue. But it should be looked into.

**Comment by jonfroehlich** [comment]
Let me push the "another weird occurrence" to a separate Issue and close this one out.
