### ISSUE TITLE
Choose location for loading GIF on audit/validation pages

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2403]
@jonfroehlich made this amazing loading GIF that we use while we wait for the page to load. But I would like to start using it in other places when things take a bit of time to load and the user could use that feedback. I think that overlaying the GIF over GSV is a bit much and could be disorienting. And a 'wait' cursor is decent, but it is also easy for that to get overridden when their mouse then hovers over a button that specifies a different cursor in its CSS.

I'm thinking that we could do something like picking a standard location (top right corner near the zoom buttons..?) where we show the loading GIF whenever we start doing something that could take awhile.

Something like this:
![Screenshot from 2020-12-07 18-45-30](https://user-images.githubusercontent.com/6518824/101431804-743b9100-38bc-11eb-8a74-00777f8706b7.png)

**Comment by misaugstad** [comment]
@jonfroehlich how do you feel about this idea? Or do you think it doesn't feel like standard practice and we should use a different method of showing that the user is waiting for something to load?

**Comment by jonfroehlich** [comment]
I don’t love it tbh. This is most similar to the UI paradigm of having a “loading” or “processing” part of a status bar in a desktop application (status bars tend to be at a UI window’s bottom).

But given that we don’t have said status bar and the current placement feels arbitrary paired with the fact that it’s unclear how often and when we would need this, I think it’s a low priority and needs further discussion if we do ultimately want something like this

**Comment by misaugstad** [comment]
I think that's fair, especially the arbitrary nature of the location, and yeah I agree that it feels like a loading icon in a status bar that we don't have.

Some evidence supporting the case that we need something like it, is that we discussed needing more 'loading' feedback in #1792

I also wonder if we underestimate the need for it since we are typically using good internet connections.

**Comment by misaugstad** [comment]
Thinking back on this, and Jon is right that this is an outdated UI paradigm that doesn't even really fit with the interfaces that we have, so I'm going to close this. #1792 is the issue to look at instead.
