### ISSUE TITLE
Jump Button Does Not Work

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#241]
The jump button is not working for me. See video:
https://youtu.be/VCyjtXCR7cs

This is likely related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/240. Perhaps I have fully completed this neighborhood except for unwalkable areas? Here's a map of my current completion of Congress Heights:

![image](https://cloud.githubusercontent.com/assets/1621749/17915494/f9806f10-6978-11e6-9b31-01751727d729.png)

**Comment by jonfroehlich** [comment]
Yah, I think I had completed the neighborhood but there were untraversable areas so this is a weird edge case. I ended up going into my dashboard and selecting a different neighborhood to audit and then coming back to Congress Heights. As soon as I started in Congress Heights, I was presented with a 'Mission Complete' dialog:

![image](https://cloud.githubusercontent.com/assets/1621749/17939457/bbbf8eba-69f8-11e6-8d35-b1b38d6260d6.png)

Hmm. OK, I clicked Continue and was then given a new Mission dialog (which was a bit messed up, I didn't get a screenshot) but still in Congress Heights.

![image](https://cloud.githubusercontent.com/assets/1621749/17939503/f457696e-69f8-11e6-836e-e3b8ada115cc.png)

**Comment by jonfroehlich** [comment]
This is still a problem. When I click OK in the Jump Button dialog, nothing happens (no matter what radio button I select). @kotarohara, what's going on here?

See errors in console:
![image](https://cloud.githubusercontent.com/assets/1621749/17953121/af49e6f8-6a3e-11e6-8063-1b77008a2875.png)

**Comment by jonfroehlich** [comment]
@kotarohara, did you ever investigate this?

**Comment by jonfroehlich** [comment]
Just received an email from a user:

> I'm not able to finish segments of missions (I can get near to the end of the red line, but then I can't go forward anymore (using the arrow on the screen, my arrow keys on my keyboard or double-clicking on the ground) and get a new piece of green red line to follow. You can see where I got stuck in the attached screenshot. I also can't get out of it by using the "jump" button because when I click "OK" in the jump dialogue box, it doesn't do anything. I have to reload the page to be able to audit (for a bit) again.

<img width="1081" alt="screen shot 2016-09-03 at 1 04 13 pm 1" src="https://cloud.githubusercontent.com/assets/1621749/18226679/35f68ac6-71dd-11e6-9489-4337d414563c.png">

This has got to be related to the problem of finishing a neighborhood. We simply did not test this condition enough and I have yet to see a successful case where you complete a neighborhood and then are correctly assigned and can start auditing in a new neighborhood.

@manaswis and @Soben713, you have to help us test completing neighborhoods. 

@kotarohara, can you please investigate this bug? It would also be very helpful if you could write some test code or a special interface that allows us to test what happens when you get close to clearing/finishing an entire neighborhood, since it's very time consuming to get to this point (Again, I've done it twice and both times, Project Sidewalk failed).

**Comment by kotarohara** [comment]
Yes, actually this was what I was working on a couple of days back. I'll get back to this tonight.

**Comment by jonfroehlich** [comment]
Another user reported this problem. We really must fix this.

![image](https://cloud.githubusercontent.com/assets/1621749/18258046/5a06ca5a-739c-11e6-9388-70e178f34561.png)

**Comment by kotarohara** [comment]
Merged #312 , so this should have been fixed. I'm closing it.
