### ISSUE TITLE
Sidewalk Gallery: Text for when there are no labels satisfying query 

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2419]
Aroosh and I were thinking it would be good to have some text show up when no labels satisfying a query are available (for example, for my database, I don't have any "Problem" labels).

An example string we came up with was:
“We found no labels that match your query"

Any other ideas to approach this issue welcome.

**Comment by misaugstad** [comment]
First, the "Problem" type is only used for the clustered attributes. It basically treats surface problems, obstacles, and missing curb ramps as the same label type for clustering. So you'll only see it used in the `user_attribute` and `global_attribute` tables.

That being said, we should still deal with the case where there are no labels matching a filter. I think that something along the lines you suggested works. We can also just use it as a call to action to add labels. Presumably if we don't have any labels for a given query, it probably means that we need to collect more data, so we can direct them to the audit page.

**Comment by ThatOneGoat** [comment]
Gotcha, I'll remove "Problem" as a selectable type.
I'll also add an additional link to the audit page.

**Comment by ThatOneGoat** [comment]
Would a good text example be something like 
"We found no labels that match your query. You can contribute to gathering more data here"
where the "here" is linked to the audit page?

**Comment by misaugstad** [comment]
I'd aim for something less technical than 'query', and I think we can go shorter/simpler. Something like "No matches. Start exploring to contribute more data!", where "Start exploring" is hyperlinked.

**Comment by ThatOneGoat** [comment]
Sounds good
