### ISSUE TITLE
Just an FYI: I Received Credit for Auditing a Juxtaposed Neighborhood When I Started In a New Neighborhood

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#242]
I just selected a new neighborhood that was next to my old audit neighborhood and I received credit for the shared streets between the two neighborhoods. So, this is the initial screen shown to me when I started. This is not a bug but I am just logging this behavior here.

![image](https://cloud.githubusercontent.com/assets/1621749/17915808/ad5e719c-697b-11e6-9ab8-05d39bbaa0ac.png)

@kotarohara, I'm sure you are aware of this, no?

**Comment by kotarohara** [comment]
Yes, I am aware of this. I agree, I don't think this is a problem.

Can I close this? I don't think it's a good idea to keep non-issues in open...

**Comment by jonfroehlich** [comment]
Sure. Close it. I just wanted to make sure we were on same page.
