### ISSUE TITLE
Sidewalk Gallery: Null severities for labels 

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2420]
For certain label types (like Occlusion), there are many labels that just don't have a severity (for example, for Occlusion, we just don't give the option to give a severity, hence the null severity). 

My first thought is to just to handle these as edge cases and just not show the "filter by severity option" as well as slightly alter how the cards look. 

Thoughts?

**Comment by misaugstad** [comment]
I think that for occlusion, yeah we can just not show a severity option. In general, I think that null severity labels should be shown, just with some text indicating that no severity was provided. I would also think that an option users should have the option to filter for labels with null severity, but not worth rearranging the interface to include in MVP.
