### ISSUE TITLE
Sidewalk Gallery: Clarifying functionality for how severity works

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2421]
In meetings, we discussed how the current look of the severity filter may be ambiguous and confusing in terms of functionality. One thing that was brought up was how the circular look of the severity buttons look like radio buttons (rather than how they should function as checkboxes). 

What I feel is a simple but clear improvement of the severity filter is to just make the severity icons look more square (we keep the rounded corners to match the cards - a softer look in general):
![newseveritylook](https://user-images.githubusercontent.com/37346427/103182546-e884a700-4860-11eb-9f3a-cb22010183e6.PNG)

**Comment by misaugstad** [comment]
Yeah I think that helps a lot
