### ISSUE TITLE
Sidewalk Gallery: Translations

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2422]
Thread for internationalizing text on Gallery page. Since the English text is still in question right now, I'll update with text to be translated soon.

**Comment by misaugstad** [comment]
@ThatOneGoat @kumararoosh is there still text to be translated? what's the status of this right now?

**Comment by ThatOneGoat** [comment]
I believe the strings we need to be translated are:
"Show"
"Filter by"

For there isn't much text until we have expandable cards.

Also, just to confirm, we have the strings "Severity" and "Tags" already translated, right?

**Comment by misaugstad** [comment]
>Also, just to confirm, we have the strings "Severity" and "Tags" already translated, right?

Correct.

Great, I'll get those translations to y'all soon. As y'all come back to Gallery, I think that this and #2459 should be the highest priority tasks.

**Comment by misaugstad** [comment]
gallery: galería
show: mostrar
filter by: filtrar por

**Comment by ThatOneGoat** [comment]
Ah, I just realized there might be one more string to translate:
"No matches. Start exploring to contribute more data!", which appears when no there are no labels satisfying a certain query. The "Start exploring" is linked to the audit page, so that might need to be taken into consideration with the translation.
Thanks!

**Comment by ThatOneGoat** [comment]
Oh also, the strings "Severity" and "Tags" apparently. These words don't have translations on their own

**Comment by ThatOneGoat** [comment]
Also a UI comment, some longer translations sometimes mess with how the tag select icons look, as below:
![image](https://user-images.githubusercontent.com/37346427/112114442-4fbaaa80-8b75-11eb-9cb0-33693b357666.png)

I'll create a separate issue for this and link it later.

**Comment by misaugstad** [comment]
all -> todos
none -> ninguna (or ninguno if you're referring to something masculine), but both etiquitas and calificación are feminine)
not applicable -> no aplicable

for "Can't See Sidewalk" I would honestly switch the English translation to "Can't See the Sidewalk" and use that translation we have on-hand.

**Comment by ThatOneGoat** [comment]
Great, thanks!

Is there anything on the bigger string ("No matches. Start exploring to contribute more data!")?

Also, I decided to keep the english as "Can't See Sidewalk" and use the spanish translation we have on-hand for "Can't See the Sidewalk" for cleanliness on the English side.

**Comment by misaugstad** [comment]
Right, let's go with "No hay resultados. Comienza a explorar para aportar más datos" and you can underline "Comienza a explorar".

**Comment by ThatOneGoat** [comment]
Should we keep the exclamation marks for

> Right, let's go with "No hay resultados. Comienza a explorar para aportar más datos" and you can underline "Comienza a explorar"

Should we keep the exclamation marks?

**Comment by misaugstad** [comment]
Right, didn't notice the exclamation:
No hay resultados. ¡Comienza a explorar para aportar más datos!

**Comment by misaugstad** [comment]
Start the hyperlink at the "C"
