### ISSUE TITLE
Mission Complete Progress Bar 1 Pixel for 'Previous Mission' Even Though None Completed

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#244]
We are drawing one pixel of a blue progress bar on the first mission in a neighborhood (indicating % complete during previous missions) but the % should be zero, so the blue bar should be zero pixels.

![image](https://cloud.githubusercontent.com/assets/1621749/17931114/b361c70e-69d7-11e6-8330-d6e5912b359f.png)

Zoomed in:
![image](https://cloud.githubusercontent.com/assets/1621749/17931141/da8ddcdc-69d7-11e6-8d71-8956346b5396.png)

**Comment by misaugstad** [comment]
@hanszhang00 can you verify that this is actually still happening, and then fix it if it is? :)

**Comment by misaugstad** [comment]
closing via #1772
