### ISSUE TITLE
Sidewalk Gallery: Querying by severity/tag is inconsistent

### ISSUE THREAD

**Issue by michaelduan8** [ProjectSidewalk/SidewalkWebpage#2445]
There's a very weird edge case I found where I will initially load on the "All" page, switch to "Other" label type, then click next page to see that there seems to not be enough valid labels in the database to fulfill an entire second page. However, I go back to the "All" page, then back to the "Other" page and click next page again only to see that the page is full. 

This leads me to believe there's a bug in the `getLabelsBySeverityAndTag()` method in `LabelTable.scala`. Another possibility is the way we are keeping track of already loaded label ids is faulty. Either way, it's not a hugely noticeable bug, but it should be fixed for consistency.

**Comment by ThatOneGoat** [comment]
This query is pretty prominent on prod. Not so much on the label types with a bunch of labels, but definitely on those with way less like "Other." For example, on Seattle, I can get to page 3 on the "Other" page before we supposedly can't load anymore. Switching back to the "All" tab and then back to "Other" lets me go all the way to page 4 however.

**Comment by ThatOneGoat** [comment]
So I can no longer repro this with the databases I currently have. I will investigate this with a smaller database. In the meantime, @kumararoosh could you try to repro this? Thanks
