### ISSUE TITLE
Sidewalk Gallery: v1.1 Features/Fixes

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2449]
Thread to compile all the goals we want to finish with the release of v1.1 for Sidewalk Gallery.

**Comment by ThatOneGoat** [comment]
One thing for sure is translations. 
I'll start adding English text to Issue #2422 and we can do all the translating there before incorporating it into the codebase.

**Comment by ThatOneGoat** [comment]
Linking to Jon's notes on Beta release
Issue #2450

**Comment by ThatOneGoat** [comment]
One thing I think would be very helpful is expandable cards. The biggest thing is they will allow us to show more information about labels that we couldn't do before with the small cards.

**Comment by ThatOneGoat** [comment]
We should also start allowing users to make more complex queries on more specific relations. 

Jon's example here is a good example: Issue #2447

**Comment by misaugstad** [comment]
Replaced with a Github Project: https://github.com/ProjectSidewalk/SidewalkWebpage/projects/2
