### ISSUE TITLE
Typo in Mission -- Easy Fix

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#245]
"Make the 100% of this..." -> "Make 100% of this..."

![image](https://cloud.githubusercontent.com/assets/1621749/17939525/06ad5402-69f9-11e6-9357-dd5650e9c7f0.png)

**Comment by jonfroehlich** [comment]
@kotarohara, can you please fix this. It's easy!

**Comment by kotarohara** [comment]
Fixed
