### ISSUE TITLE
Check nightly/weekly for expired imagery

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2458]
We could add some code that checks old imagery to see if it has expired. There is an endpoint that we can use to check for the existence of imagery that is free to use, so we don't have to worry about cost here. We have a `last_viewed` column in the database for each pano, and we could use that to only check for imagery that hasn't been checked in X amount of time. Then we would update the `last_viewed` and `expired` columns for all the panos we check that night. I might also just limit it to a few hundred panos per night or something just so that we don't accidentally try to check 50k panos across all our servers one night.

I see no reason not to just run this every night, since most nights it just won't need to check anything (once we've checked all the data we haven't checked yet).

Some benefits:
* It can make loading of the validation page and Gallery marginally faster in some cases, since those pages do this check as well, and they will be less likely to hit expired imagery, which requires them to continue searching for non-expired panos
* We will actually have information on how much of our imagery has expired, which is something that stakeholders often ask about.
* And once we have this information, we will more easily be able to figure out where there is new imagery, which can inform what areas we might want to have users re-explore (#1165)

This also shouldn't be too hard to implement. We have other scripts that run nightly, so we can copy that bit of code. And we have validation and gallery that already do these API calls, so it's easy to copy those as well.

I imagine the query to figure out which panos we should check would look something like this (excluding time zone stuff for concision):
```
SELECT gsv_panorama_id
FROM gsv_data
WHERE expired = FALSE
    AND last_viewed::date > now()::date - interval '6 months'
ORDER BY last_viewed
LIMIT 500
```

There is the question of how frequently we should be checking the imagery? I was thinking like every year? Maybe every 6 months? Really, we should see how long it takes to do this check and how much network traffic it uses, and that should determine how frequently we do this.

**Comment by jonfroehlich** [comment]
Sounds great to me!

**Comment by misaugstad** [comment]
As @mcdoerr pointed out in #2488, it's possible for a pano to be marked as "expired" when it actually is not. I assume that it's because there was some network problem at the time that we wanted to check for the imagery. Given that, I think that we should probably also check imagery that has already been marked as expired just to make sure that it actually has expired. This should be done much less frequently than checking if imagery that we thought existed has expired though!

**Comment by misaugstad** [comment]
@akliamrous here's a bit more info to help you get started!

1.  You will most likely want to start by just making the functions you need to check labels for imagery, and just have an endpoint you can call that will do that. I would just work on pretty much all of the functionality _except_ for making it run automatically every night. You can always add that piece at the end, and it will be easier to test along the way if it isn't trying to run at a specific time.
2. You'll be able to find the way we use the free API to check for imagery by looking at the code for the `/label/labelsByType` endpoint. I believe that it leads to a `panoExists()` function somewhere in the back-end code that you'll want to either use or base your code off of.
3. For some example code on how to make something run automatically at a specific time, I'd check out something like PR #1730. Specifically, the changes/additions to `Global.scala` and `UserStatActor.scala`. There have probably been some changes since that PR, so also look at the most recent version of that code, but looking at that PR shows which lines specifically need to be added to make something like that work.

**Comment by misaugstad** [comment]
As part of dealing with #956 I am making it so that we record some data about every pano that a user visits, instead of only the ones where labels have been placed. However, when checking for expired imagery, only the panos that have labels on them matter. So we should make sure to filter down to just that set when implementing this!

**Comment by misaugstad** [comment]
>it's possible for a pano to be marked as "expired" when it actually is not. I assume that it's because there was some network problem at the time that we wanted to check for the imagery. Given that, I think that we should probably also check imagery that has already been marked as expired just to make sure that it actually has expired. This should be done much less frequently than checking if imagery that we thought existed has expired though!

I agree with all of this, but it's also important that we check the error message that we get when requesting imagery. We should be able to differentiate between network errors and errors because the image doesn't exist anymore.
