### ISSUE TITLE
Sidewalk Gallery: prioritize validated labels

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2459]
Our system can collect some poor quality data, which is why we have the validation pipeline. However, we are not currently taking validations into account in Sidewalk Gallery.

While one could argue that we want Sidewalk Gallery to show both low- and high-quality labels to get additional validations, Sidewalk Gallery isn't really a primary channel for this. Instead, it's a *gallery* to highlight examples of labels, tags, and severities.

Thus, we should deprioritize showing labels on Gallery that have negative validation scores.

We should somehow deprioritize showing labels that we know (or suspect) are of poor quality. Some options for how this might look:
* Filtering out labels that have more disagree than agree validations
* Showing those labels with more disagree validations _after_ the labels that don't
* On the flip side, maybe we show labels that have more agree validations _first_! Could even show all validated, then all without validations, then all that have disagree validations
* We could filter out or deprioritize labels from users that have been marked as "low quality". Maybe it's all of their labels, or maybe it's all of them except for the ones that other have agreed with through the validation interface.

So there are quite a few options here, but this seems like a high priority task for Gallery 1.1 :ok_hand:

**Comment by jonfroehlich** [comment]
Thanks @misaugstad. I agree that this is critical.

I believe we were using a quality score before (Mikey, what was the equation for this? Something like `score = num positive validations - num negative validations - 0.2 * unsures`). The 0.2 is a weight factor that can change.

**Comment by misaugstad** [comment]
I think that we had talked about something like that, but I think we ultimately went with a more simple: it's correct of there are more agree than disagree, and it's incorrect if more disagree than agree, and it's treat it as unvalidated if they are even (and we ignore unsure). That's at least what we do when computing a user's accuracy score right now, I believe.

**Comment by jonfroehlich** [comment]
Gotcha. Fine with keeping it simple and only moving towards complexity as necessary

**Comment by jonfroehlich** [comment]
I think at some point we may want to also consider being able to filter and sort by agreement scores (because this, in itself, is interesting).

**Comment by misaugstad** [comment]
>I think at some point we may want to also consider being able to filter and sort by agreement scores (because this, in itself, is interesting).

Some of that mentioned in #2358
