### ISSUE TITLE
Typo in Onboarding Tutorial - Easy Fix

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#246]
![onboarding_bug_takingastep_red](https://cloud.githubusercontent.com/assets/2873216/17941696/7980df7c-6a02-11e6-8e57-f60e8fae2369.jpg)

**Comment by jonfroehlich** [comment]
Thanks!

@manaswis, can you start using github's organizational features to tag your posts.

**Comment by manaswis** [comment]
Sure!
