### ISSUE TITLE
Add support for organizations

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2466]
Copying over some text @jonfroehlich posted in #2338 

>I know from talking to partners that they want leaderboards not just for individuals but for organizations. This is particularly important as we begin partnering with schools and other community organizations.
>
>In those cases, I don't think "choosing a shared goal" is important. Instead, I think it's important to:
>
>* Allow users to quickly and simply type in or otherwise select their organization
>* See their organization's performance on the leaderboard. At a minimum, this can be just like the individual leaderboard but the left column has organization rather than an individual's username
>I consider these things more important than specific "mapathon" support because these features are more broadly applicable. In addition, if we started with the above, I imagine it could be extended to have specific mapathon support with goal settings.

I think that #2338 got a bit messy and confusing because it is ostensibly about shared goal support for mapathons, while Jon was arguing that having leaderboards for organizations is more important. So I created a new issue for this. And I think that you should take over this issue instead @shokiami (sorry for pulling you in a bunch of directions!). I think that Jon is right that organization affiliation is more important to our users right now than shared mapathon goals, especially as we are being used in more and more schools.

Here's how I'd see this being implemented right now:
1. On the user dashboard, we include a section for joining an organization.
    1. There would be a drop down menu with orgs that exist in our system
    2. I think we should say something like "If your organization isn't listed and you want to see a leaderboard for your organization/team, then please email blah@blah.blah with your username, city, team name, and a list of usernames of users in your org (if applicable)". @jonfroehlich I know that you were suggesting just including a text box that we can do string matching on, but I think that that has its own set of complications, and there probably won't be a _ton_ of organizations, so I think it might be easiest for orgs to be added through me.
2. Add a table to the database for organizations. And either add a table to join users with orgs, or maybe you could just add a column to one of the existing table for users. This is how we'll keep track of organization affiliation.
3. Add a section to the admin dashboard that allows admins to add orgs and to add members to the orgs. This one could probably be done in a future PR, since I should be able to do anything I need to with a direct query to the database.
4. A third leaderboard could be added to the leaderboard page that is just for your organization. And if you aren't in an org yet, it could have the exact same drop down and such for joining an org instead of the leaderboard.

I think that with that implementation, the dev time won't be overly burdensome, while having a solid implementation that we can build on in the future.

**Comment by shokiami** [comment]
@misaugstad @jonfroehlich 

Here is currently what everything looks like. Is there anything I should change before I submit the PR?

Dashboard:
<img width="1252" alt="dashboard_en" src="https://user-images.githubusercontent.com/43970567/116488922-78a31f00-a848-11eb-8f93-ff269682bb1b.png">
<img width="1253" alt="no_org_en" src="https://user-images.githubusercontent.com/43970567/116488925-7a6ce280-a848-11eb-9fbc-76e6ce0cb42b.png">

Leaderboard:
<img width="1100" alt="leaderboard_en" src="https://user-images.githubusercontent.com/43970567/116488937-7fca2d00-a848-11eb-8896-d3c5e6208378.png">
<img width="1203" alt="no_org_leaderboard_en" src="https://user-images.githubusercontent.com/43970567/116488940-80fb5a00-a848-11eb-82dd-d6c1430155e9.png">

Spanish Version:
<img width="1221" alt="dashboard_es" src="https://user-images.githubusercontent.com/43970567/116488948-8658a480-a848-11eb-9c50-4c53d63e366b.png">
<img width="1247" alt="no_org_es" src="https://user-images.githubusercontent.com/43970567/116488950-8789d180-a848-11eb-9095-ec47b34e80ad.png">
<img width="1220" alt="leaderboard_es" src="https://user-images.githubusercontent.com/43970567/116488951-88226800-a848-11eb-9126-532736ec535e.png">
<img width="1226" alt="no_org_leaderboard_es" src="https://user-images.githubusercontent.com/43970567/116488954-89539500-a848-11eb-9f83-72474790a2f7.png">

**Comment by misaugstad** [comment]
I'll have more time to give feedback tomorrow, but what does the leaderboard page look like when there is a weekly leaderboard as well?

**Comment by shokiami** [comment]
Sorry, my weekly leaderboard is empty, but here is what it looks like.

Wider view:
<img width="1327" alt="leaderboard_weekly_wide" src="https://user-images.githubusercontent.com/43970567/116490123-768e8f80-a84b-11eb-8411-2373559ba8ba.png">

Narrower view:
<img width="771" alt="leaderboard_weekly_narrow" src="https://user-images.githubusercontent.com/43970567/116490125-78585300-a84b-11eb-9c18-66195604ec41.png">

**Comment by misaugstad** [comment]
1. I would change "Organization Leaderboard" to "Minecraft Gang Leaderboard".
2. Maybe "Top 10 contributors to Minecraft Gang" -> "Top 10 overall contributors to Minecraft Gang"?
3. On the user dashboard, maybe in a tooltip? Or maybe the text should always be there... Or it's only there if you are currently not in an org? idk. Anyway I'm looking for some text like "If you'd like to create an organization, please email sidewalk@cs.uw.edu and include your organization name and description.". I'm not super attached to the text tbh, but we should add something like that, even if it isn't super prominent.

Otherwise, I think it looks pretty good! We might want to mess with the button and how we display the org name on the user dashboard at some point, but I think it looks good enough for an MVP :) Great work!

**Comment by jonfroehlich** [comment]
@shokiami and I had a great end-of-quarter chat. When I envisioned an organization leaderboard, I wasn't thinking about showing a leaderboard within a group (competition within a group) but rather across-group competition. That is, we would show a table of leaders grouped by organization. So, with the current groups you have in your mocks, you would have an "Organization Leaderboard":

| # | Group | Labels | Missions | Distance | Accuracy |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 1. | Liga Peatonal | 2021 | 121 | 55.5 km | 89.1% |
| 2. | Minecraft Gang  | 1785| 84 | 45.5 km | 89.1% |
| 3. | Project Sidewalk (Seattle)  | 1452 | 50 | 25.5 km | 89.1% |
