### ISSUE TITLE
Sidewalk Gallery: Make it easier to see what "cards" you've already validated

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2476]
As you're weaving through the cards in Sidewalk Gallery (and agreeing/disagreeing, etc.), it would be nice to show the user what cards they've already responded to by changing giving some visual indicator. I suggest putting an icon indicator (maybe colored circle with icon) in upper-right hand corner of the card—such as a "green check" for "agree" and "red x" for "disagree". Could also consider changing the outline of the validated card to green for agree, red for disagree, and yellow for unsure.

Ideally, this would be sync'd so that these validation icons would show up based on your previous validation history (e.g., if you've validated a particular label in the past—either with LabelMap, validation tool, or sidewalk gallery—then it would show the appropriate icon indicating your validation).

**Comment by misaugstad** [comment]
I worry a little bit about turning Gallery into more of a validation interface than it should be. I'd hope that the need for this would become less relevant after we begin prioritizing labels that don't have disagrees already in Gallery, and maybe we should reevaluate at that point?

In any case, it would still be helpful to show that something has been validated in the past using the method that we already do (where the agree/disagree button remains visually selected after you click). If we could have that show up after refreshing the page, and have it include validations through our other interfaces, that would still be helpful.

**Comment by jonfroehlich** [comment]
Definitely. We need to keep discussing this. Multiple things going on.

First, at a minimum, we should provide better feedback about the cards validated during *that* user's session.

Second, I was suggesting that this validation history be sync'd (so you see your own validation feedback from past sessions and other validation interfaces shown in that indicator)

Third, there are other considerations like: what is the validation history like for that card (not just from you but other users) and, in addition, is there a way to prioritize, filter, sort cards based on their validation history in gallery.

And yes, I agree that this is intermixing multiple potential facets of Sidewalk Gallery--not just allowing the users to select, filter, and search for labeled problems but also to consider the overall quality of our data (by better surfacing validation histories) and to actually partake in improving data quality.

I would argue that all of these things are important to Project Sidewalk and Gallery too...

**Comment by misaugstad** [comment]
Also mentioned in #2450 

>Once you've validated a card, maybe change the outline of that card to the validation color to both confirm that it's been validated and also show, glanceably, from the gallery view (yes, I know you can mouseover the cards to get visual confirmation but my comment is in addition to this)

**Comment by kumararoosh** [comment]
![image](https://user-images.githubusercontent.com/24703104/116767590-fc464280-a9e5-11eb-98d2-6d4579bba8a4.png)
This is the proposed solution for making the validations more easily seen. When the button is pressed, the background color of the card changes to the corresponding choice. In contrast to the white background, these colors pop.

**Comment by misaugstad** [comment]
I kinda like it! I think it would make me motivated to validate all the labels on the page, too :eyes:

**Comment by isavin12** [comment]
@kumararoosh can we make validated cards look like this? I'm not 100% sure about using orange for disagree, but it fits the Project Sidewalk style guide. Open to exploring other colors if it creates confusion. 

![Card Validation](https://user-images.githubusercontent.com/56325998/120953092-2d124980-c701-11eb-9be7-b2c20ce43943.JPG)
![Card Validation 2](https://user-images.githubusercontent.com/56325998/120953098-2edc0d00-c701-11eb-868b-a8a895d8d734.JPG)

**Comment by misaugstad** [comment]
closing via #2596
