### ISSUE TITLE
Congress Heights Strangeness Continues

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#249]
I just logged in tonight and was dropped back into Congress Heights. I was directed down a street, which I audited, but when I hit the end of the street segment, there was no more red route and thus, nothing more for me to accomplish.

![image](https://cloud.githubusercontent.com/assets/1621749/17953079/34103762-6a3e-11e6-85ff-69789ce4bcb8.png)

This could be because I think I've already completed 100% of Congress Heights...

**Comment by kotarohara** [comment]
This is the continuation of #241

**Comment by kotarohara** [comment]
This should be fixed as I have merged #312 (I haven't pushed it to the server though). I'm closing it.
