### ISSUE TITLE
Consider Having a Button That Allows User to Jump to a Different Neighborhood

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#250]
Currently, it's quite hidden that, as a user, you actually have some control over which neighborhoods you audit--this is because we drop users into neighborhoods that have the _fewest_ street segments audited. However, users can actually select new neighborhoods to audit in the dashboard.

I was thinking it might also be nice to have a simple button that allows the user to jump to a new neighborhood that is in the most need of auditing (or towards the top of the list) .

**Comment by misaugstad** [comment]
There are a few more options now for allowing the user to jump to a new neighborhood.
