### ISSUE TITLE
Start auditing a street from a label on /labelMap

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2502]
##### Brief description of problem/feature
We could let users looking at Label Map to start auditing a specific street from that interface (originally proposed by Jon on Slack). Since they can now see which labels have expired imagery (PR #2488), they should be able to manually choose to re-audit streets where the imagery has expired!

##### Design ideas & mockups
Maybe where we have the error that says "We use the Google Maps API to show the sidewalk images and sometimes Google removes these images so we can no longer access them. Sorry about that.", we could suggest that they explore the street again with the updated GSV imagery!

**Comment by jonfroehlich** [comment]
What will this UI look like? If I click a label, will it have a button that lets me start auditing there?

Or can I actually mouse over a street and click on that to start auditing there...

**Comment by misaugstad** [comment]
As of right now, I think that the plan is to have a button available when you click on a label to let you audit that street, and it should drop you right at the place where the place where that label was placed.

But I am now remembering that there is an issue with letting someone start auditing in the middle of a street. If they are placed in the middle of the street, the front-end just treats it as though they audited from an endpoint of the street up to that point. So if they pop in in the middle of a street and finish auditing the second half of the street, this would be treated by our system as a fully audited street :'(

Maybe for now we make the button just say "Explore this street" or something, and make them start from the endpoint of the street?

What we ultimately want is to [make metadata editable](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2575) so that they don't even have to go to the street and audit themselves if they see an error. But for now maybe we just bring them to the street endpoint?

**Comment by jonfroehlich** [comment]
I agree that we could put users at the start of that street and have UI that says "Explore this street." 

But I don't actually see the [make metadata editable](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2575) as a replacement to this feature.

My use case actually stems from Oradell. There are some streets that are marked as "audited" but seem to have a lack of labels (inconsistent with nearby areas):

![image](https://user-images.githubusercontent.com/1621749/188648653-e4e0ba4a-dce7-4318-8087-7054b592b05a.png)

I would like to select these streets (via a mouseover popup or something similar) and click "audit." While we could use a nearby label for this, that assumes that a label exists—which may not always be the case. You know?

**Comment by misaugstad** [comment]
>But I don't actually see the https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2575 as a replacement to this feature.

Ahh, see I was talking about someone looking at label map, seeing a label that they think is incorrect, and wanting to fix it. Right now they can't, but we are least giving them the opportunity to reaudit the street.

I didn't realize that you were specifically interested in auditing a street based on the street segment. But now that you've described why, that makes a ton of sense.

And when I made the comment about making data editable, I am also forgetting the original use case that brought up this issue: you're looking at labels on LabelMap and then you find a street where all the imagery is expired and you want to re-audit that street.

**Comment by jonfroehlich** [comment]
Gotcha. Should we create a new issue then for 'Start Auditing from a Street' or should we fold it into this Issue?

**Comment by misaugstad** [comment]
Let's fold it into this one since I'm going to be the one to finish it off.

**Comment by misaugstad** [comment]
closing via #3021
