### ISSUE TITLE
Make filter options clearer in Gallery

### ISSUE THREAD

**Issue by michaelduan8** [ProjectSidewalk/SidewalkWebpage#2512]
We want to make sure it is easily determinable whether a filter option has been selected or not.

**Comment by misaugstad** [comment]
@jonfroehlich originally mentioned in #2450 with this text and image:

>We've talked about this before but it's still not super clear to me which filter options are selected and which are not. Maybe something simple like bolded outlines around selected options. But we should also consider totally different approaches (based on design research).

![image](https://user-images.githubusercontent.com/1621749/105903715-19c5d380-5fd5-11eb-8346-3f8d9ff69462.png)

**Comment by misaugstad** [comment]
I believe that this has been addressed aside from #2601 so I'm closing this one!
