### ISSUE TITLE
Updating the credentials for database tools in README.md 

### ISSUE THREAD

**Issue by itsyeonjoon** [ProjectSidewalk/SidewalkWebpage#2517]
It seems like the credentials listed under Programming environment's database tools section in `README.md` need an update. 

At the moment, the credentials for connecting to the database is shown like this: 

![dbcredentials](https://user-images.githubusercontent.com/41148074/112397739-ea270500-8cbf-11eb-8023-5165ebdefa9f.jpg)

We found out that these credentials don't apply for some people. For example, for some people, the "user" was "postgres", not "sidewalk". Since people can find information on what their User, Password, and Database are in `docker-compose.yml`, it might be a good idea to mention about this in the credentials.

**Comment by misaugstad** [comment]
Thanks @itsyeonjoon ! I think that even for users where "sidewalk" will work as the user, "postgres" should work as well, so we should just switch the documentation to say postgres instead!
