### ISSUE TITLE
You've got quite far away from the audit route

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#252]
"Uh-oh, you've got quite far away from the audit route. Click here to jump back."

should be:

"Uh-oh, you're quite far away from the audit route. Click here to jump back."

![image](https://cloud.githubusercontent.com/assets/1621749/17953326/9429ac4e-6a40-11e6-9824-851a29145b7e.png)

**Comment by kotarohara** [comment]
This has been already fixed locally.
