### ISSUE TITLE
Talked to Yu Huang this morning, she recommended nominating Project Sidewalk for Digital Public Goods

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2525]
I spoke with [Yu Huang](http://www-personal.umich.edu/~yhhy/) this morning and she recommended nominating Project Sidewalk for [Digital Public Goods](https://digitalpublicgoods.net/standard/). Here's the nomination form [here](https://docs.google.com/forms/d/e/1FAIpQLSdGzlBiecPBlVvJXmcMKXF3zdxASY8vGnrdnNNwp7fVKb169A/viewform).

She also suggested https://ovio.org/projects.

**Comment by misaugstad** [comment]
Love it!!

**Comment by misaugstad** [comment]
I've made it partway through this process, and they will reach out for more information. I made it to the point where it says
>In order to be a full Digital Public Good, projects must demonstrate an adherence to privacy and other applicable international and domestic laws, standards and best practices, and do no harm. We therefore require the next section be completed by someone who is authorized to make assertions on behalf of the project. 
>
>If you have this authority please carry on to the next section. If you do not have this information please submit the nomination and we will follow-up with the project to collect additional information.

I'm not sure that I'm the person to be answering all of those questions, so I submitted the project as a "candidate" for now :ok_hand:

**Comment by misaugstad** [comment]
Okay, our application is being considered! You can see us listed [here](https://digitalpublicgoods.net/registry/)! Nothing left for us to do on this front now, so I'm going to close this issue. I'll come back and update it when we ultimately hear back from them.

**Comment by misaugstad** [comment]
Oops, dropped the ball on this one. If we still wanted to do this, we need to fill out the full form.
