### ISSUE TITLE
Current Neighborhood Not Properly Highlighted In Mission Complete Dialog

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#253]
Looks like there is a small bug in the drawing of the neighborhood highlight here as the bottom part of my current neighborhood didn't make it in the mask (circled in red in second image to make it more clear).

![image](https://cloud.githubusercontent.com/assets/1621749/17953371/ddf7b960-6a40-11e6-90b8-657fa9727a5f.png)

![image](https://cloud.githubusercontent.com/assets/1621749/17953379/eb949ac0-6a40-11e6-9723-62def151a452.png)

**Comment by kotarohara** [comment]
No that looks like a correct boundary data. You can see each neighborhood boundary in the demo or the admin interface.

![image](https://cloud.githubusercontent.com/assets/612263/18155835/43d02a58-6fdf-11e6-896f-380a9e23f689.png)

**Comment by jonfroehlich** [comment]
Ok, great. Let's close this issue. Thanks!
