### ISSUE TITLE
Long usernames get cut off on mobile

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2536]
##### Brief description of problem/feature
Users with long (or even medium length) usernames have their name cut off on the mobile validation page when they sign in. See example below where we only get through maybe 10 characters.

![long-username-issue](https://user-images.githubusercontent.com/6518824/115132023-77086a00-9fb1-11eb-8704-1d64ddff8e12.PNG)

##### System info (OS, browser, city, and local/prod/test)
Mobile Safari on all servers.

##### Potential solution(s)
We should be able to just have the button width scaled dynamically with the length of the username. Should be an easy fix.

**Comment by misaugstad** [comment]
@jiamae this uses the mobile site! You can do some easy testing with the browser console, which can emulate different types of phones (at least in Chrome). But ultimately you should test on your own phone as well! Instructions for how to do that are [here](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Process-for-contributing-new-code#testing-your-contribution)!

**Comment by jiamae** [comment]
Does anyone have a preference of how much padding we want for usernames when on the mobile validation page?
![2](https://user-images.githubusercontent.com/56496451/142708174-07c3044d-8c5a-4222-b233-76573d62e761.PNG)
![1](https://user-images.githubusercontent.com/56496451/142708177-1d6fd758-976e-41b2-8fc5-228aba235824.PNG)

**Comment by misaugstad** [comment]
I like the amount of padding in the 2nd image!
