### ISSUE TITLE
Should Vegetation Be Marked as a Temporary Problem?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#254]
I've been marking vegetation as a temporary problem (because I imagine it often fixes itself in the winter months) but perhaps I shouldn't be doing this. Do we have any info on this in the FAQ or in the label type help?

![image](https://cloud.githubusercontent.com/assets/1621749/17953405/1d27fe1a-6a41-11e6-9646-d9db9b779f02.png)

**Comment by Soben713** [comment]
One of our severity examples is about over-grown vegetation, but we don't say anything about whether it is a temporary problem or not.
![image](https://cloud.githubusercontent.com/assets/1576529/20274958/9a0d36c6-aa64-11e6-8bde-30b8825cb2c4.png)

I will update it both in the FAQ and the label type help.

**Comment by Soben713** [comment]
@jonfroehlich Correct. We can't generally say that vegetation must be marked as temporary because some would disappear in winters and some would not.

What I did was just to explain that if it is something that would be fixed in winters you should mark it as temporary. Here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/1576529/20279369/516bf42c-aa76-11e6-8b67-454a1d4fd40e.png)

**Comment by jonfroehlich** [comment]
I don't think we should say this. It's speculative. How would the user know if it would be fixed in the winter? And how could someone evaluate whether the underlying sidewalk isn't all broken up and degraded as a result of the overgrowth? Finally, don't say things like 'must' when talking to users--it's too heavy handed--instead, say things like 'should.'

**Comment by Soben713** [comment]
Yeah, I agree that it's speculative. Do you have any other suggestions? I don't know what to do.

**Comment by Soben713** [comment]
After talking to Jon, we decided to move this to v3.

**Comment by misaugstad** [comment]
I would think to label overgrown vegetation as temporary in just about any situation. My thought is that people (govt workers) do typically go around and cut overgrown vegetation relatively frequently. Maybe I am overestimating that frequency, but I get the sense that plants are always growing and being trimmed back, so this branch will probably be cut after a relatively short period of time. Let me know if I am way off base, though :)

**Comment by jonfroehlich** [comment]
I think you're overestimating the frequency with which vegetation gets properly trimmed (at least in DC summers where all vegetation grows exponentially it seems). I use sidewalks with strollers a ton and I'm often pushed off sidewalks into semi-dangerous situations because of thick brush that grows into sidewalk impeding the path.

**Comment by misaugstad** [comment]
We did end up going into some of the nuance of this in the labeling guide:
![Screenshot from 2021-04-21 13-42-27](https://user-images.githubusercontent.com/6518824/115618355-6ef94480-a2a7-11eb-8fac-b8dca4daeed8.png)
