### ISSUE TITLE
Finished Audit Route in the Mission Complete Dialog is not shown on the map

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#255]
This neighborhood is very long and, consequently, the code that we use to center the neighborhood in the Mission Complete screen means that some routes will not be shown (without panning/zooming). For example, in the screenshot below, my audit route is not shown by default. I had to pan manually to see what I had audited (second image).

![image](https://cloud.githubusercontent.com/assets/1621749/17953478/b052c634-6a41-11e6-8dc8-a0332de3079a.png)

![image](https://cloud.githubusercontent.com/assets/1621749/17953481/b7e6ac8a-6a41-11e6-862c-13d52148db82.png)

**Comment by misaugstad** [comment]
This zoom has been fixed :ok_hand:
