### ISSUE TITLE
The word 'tag' shows up on sidewalk gallery filter buttons

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2554]
Should be a quick fix.

![image](https://user-images.githubusercontent.com/1621749/117497927-f42e5b80-af2d-11eb-93db-6f14f8029bcd.png)

**Comment by jonfroehlich** [comment]
I've seen it multiple times on multiple computers (seems to show up everytime I try to demo) :-D

**Comment by jonfroehlich** [comment]
Still happening for me:

![image](https://user-images.githubusercontent.com/1621749/122295620-4a3bda80-ceae-11eb-9866-c6365e44a294.png)

**Comment by misaugstad** [comment]
Yeah if it isn't fixed in this current version, I'll make that top priority to do that bug fix tomorrow

**Comment by jonfroehlich** [comment]
I refreshed and it worked again... so unfortunately it's an inconsistent bug as you pointed out previously

**Comment by jonfroehlich** [comment]
But it has been happening quite consistently to me as I've been using Gallery more to write this paper:

![image](https://user-images.githubusercontent.com/1621749/122398901-31bfd480-cf2f-11eb-8e9b-9f84857f4ea0.png)

**Comment by jonfroehlich** [comment]
@misaugstad this continues to happen even with the new UI. It's quite a frequent problem.

![image](https://user-images.githubusercontent.com/1621749/122564776-998f2180-cffa-11eb-8b88-8264daefc7f7.png)
