### ISSUE TITLE
Project Sidewalk on Makeability Lab webpage throwing server error 500

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2562]
![image](https://user-images.githubusercontent.com/1621749/118897226-b252cd00-b8be-11eb-92a1-47bf02f0555f.png)

https://makeabilitylab.cs.washington.edu/projects/sidewalk/

**Comment by misaugstad** [comment]
Although we link to it from Project Sidewalk, it's a Makeability Lab website issue, so I [moved it there](https://github.com/makeabilitylab/makeabilitylabwebsite/issues/948).
