### ISSUE TITLE
Error message when setting up dev env database with postgres 12

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2568]
##### Brief description of problem/feature
@akliamrous just set up their dev environment, and they are the first new intern to be onboarded since upgrading to postgres 12. It seems like the `pg_restore` command might be trying to create the "public" schema in the newer versions when it wasn't before. As a result, we're seeing the following error:
```
pg_restore: error: could not execute query: ERROR:  schema "public" already exists
...
pg_restore: warning: errors ignored on restore: 1
```

It's not a huge issue, since the error just gets ignored and everything continues as normal. But I think that we could probably remove the line that creates the "public" schema to get rid of this error message.

**Comment by jonfroehlich** [comment]
Also received this error. And the answer doesn't exist in the dev environment [Troubleshooting wiki](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Docker-Troubleshooting). :)

![image](https://user-images.githubusercontent.com/1621749/132930832-6d179946-b561-4aa8-9e30-bfe87ed3c705.png)

**Comment by misaugstad** [comment]
This is no longer an issue since we reworked our databases into a single database with multiple schemas.
