### ISSUE TITLE
Upload data on mission complete

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#257]
I know that we intermittently upload data (rather than immediately after a label is placed). I want to make sure that we are uploading data as soon as a mission is completed (regardless of where we are in the action queue).

**Comment by jonfroehlich** [comment]
@kotarohara, can you please respond to this? Do we upload data when a mission is complete.

I know that we currently do not upload data on every mouse click/movement but instead batch the data into an upload/action queue but I want to know if we have different trigger events (like finishing a mission) where we do actually upload the data. Please respond.

**Comment by kotarohara** [comment]
No, we don't. We upload data when a task is completed as well as
periodically.

**Comment by jonfroehlich** [comment]
So, isn't a task is complete when a mission is complete... so don't you mean Yes?

**Comment by kotarohara** [comment]
No, task complete means completing a street edge. Not necessarily a
mission. Mission can be completed in the mid-street.

**Comment by jonfroehlich** [comment]
Well then, don't you think we should upload data when a mission completes--since this is often the time when I close my browser window?

In other words, can you address the higher level point about saving data rather than just the lower level points.

**Comment by kotarohara** [comment]
Sure, we can do that. But this is a lower priority work as it also submits data at tab closing/transition.

**Comment by jonfroehlich** [comment]
Ah, yes, that seems most important.

I do think saving at mission completion would be another nice check point. We can mark as low priority and discuss.

**Comment by kotarohara** [comment]
I updated this so that when a user completes a mission label data gets submitted.
