### ISSUE TITLE
Need "Data Dump" for PacTrans Reporting

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2571]
I am writing our ["Final Report" ](http://depts.washington.edu/pactrans/research/reporting/) for PacTrans funding, which is due **June 15, 2021.** As part of this, they require us to submit our "final research dataset." This is described in the [PacTrans PI Handbook](http://depts.washington.edu/pactrans/wp-content/uploads/2020/04/2020.4.29-PI-Handbook-v1.0.pdf). I've copy/pasted the relevant parts for us:

> ## Data Management
> As a recipient of a federal grant, PacTrans is required to make, to the extent feasible, all final digitally formatted scientific data resulting from our funded projects publicly accessible for search, retrieval, and analysis barring certain restrictions such as individual privacy, confidentiality, etc. More details about PI submission of this data and our storage procedure can be found in the Final Report & Data Reporting: Expectation & Process section below.
> For more information, as well as links to documentation and templates, please see the Data Management page on our website here: http://depts.washington.edu/pactrans/research/data-management/
> 
> ## Submitting Final Dataset
> As summarized in the Data Management section above, all PIs are required to submit their final research dataset, along with corresponding metadata, to PacTrans at the end of their project to be made publicly available unless documented restrictions make dissemination imposible. Whether or not the data set will be made public, PIs are required to submit a metadata worksheet for that final research dataset. This dataset and metadata must be submitted to PacTrans by no later than 30 days after PacTrans approves the PIs final technical report. Once the dataset and metadata are received, PacTrans staff will create a profile for that data on the PacTrans collection of the Harvard Dataverse. The Dataverse will generate a unique permalink URL for each publication, which will not change, even if new versions of the document are uploaded. The permalink will be linked to the final technical report and vice versa. The dataset and metadata will also be stored locally and the Dataverse profile will be linked in the project profile on the PacTrans website.

@misaugstad, what would be the best way to do this? I'm thinking of some sort of per-city dump that we zip up? Would be nice if we had this automated on the API. Like, you point to a specific /api/url (perhaps with a token that we give you) and then you receive a tarball (or some sort of data dump) in return. As now, looks like we have a "We are working on this":

![image](https://user-images.githubusercontent.com/1621749/121407320-05df9600-c914-11eb-963c-6e841645275c.png)

**Comment by misaugstad** [comment]
What data do we need to provide, exactly? Is it just the stuff we currently have from the API, but all together in one place? Or is it like "give us everything that isn't PII"?

**Comment by jonfroehlich** [comment]
I think it's focused on the labeling metadata. I would say either:

- Raw labeling data (e.g., label type, severity, comments, tags, validation data, etc.)
- Clustered versions

We could do this either as XML or JSON (preferred) or probably just a simple SQL dump (in the worst case).

And it needs to be like a zipped archive, I think.

**Comment by misaugstad** [comment]
Here is a zip file with the clustered attributes for each city! Let me know if you need anything else!
[Sidewalk-Accessibility-Attributes.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/6650848/Sidewalk-Accessibility-Attributes.zip)

**Comment by misaugstad** [comment]
Linked above, you can find the data worksheet that we have to fill out at the link below by clicking on "PacTrans project final dataset metadata worksheet."

http://depts.washington.edu/pactrans/research/data-management/
