### ISSUE TITLE
Sidewalk Gallery: What do gray labels mean?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2573]
Just loaded Sidewalk Gallery (no filters selected, etc.) and had an occurrence of a "gray" label but there is no way to determine what this gray label means (no description of gray label, no legend, no mouseover support). So I can't respond to the question of "Agree", "Disagree", or "Unsure"

![image](https://user-images.githubusercontent.com/1621749/122121896-fe6f2f80-cde0-11eb-9b7b-24bfb8994250.png)

![image](https://user-images.githubusercontent.com/1621749/122122024-2363a280-cde1-11eb-9934-29297af79935.png)

**Comment by jonfroehlich** [comment]
I would argue that this is a problem across all label types since there is no legend or way to determine what a label type means. So, for example, what does the purple label or green label here mean?

![image](https://user-images.githubusercontent.com/1621749/122122193-54dc6e00-cde1-11eb-8566-2b9c4944042e.png)

**Comment by misaugstad** [comment]
closing via #2570
