### ISSUE TITLE
Sidewalk Gallery: Add in panorama image timestamp to each card

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2574]
As we have in the auditing and validation views, I think it would be useful and interesting to show the image date on each Sidewalk Gallery card. We could show it as an overlay as we do here:

![image](https://user-images.githubusercontent.com/1621749/122131671-611af800-cdee-11eb-8607-c59d6980d54e.png)

**Comment by ThatOneGoat** [comment]
Resolved by 2587

**Comment by misaugstad** [comment]
closing via #2596
