### ISSUE TITLE
Add validation in Gallery expanded modal

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2578]
##### Brief description of problem/feature
We are missing validation in the Gallery expanded modal. @kumararoosh should be working on this soon so that we can have it before our ASSETS poster!

![Screenshot from 2021-06-16 15-25-27](https://user-images.githubusercontent.com/6518824/122302601-2b8e1180-ceb7-11eb-870f-129e6da04b36.png)

**Comment by jonfroehlich** [comment]
Woohoo! Great job on this @kumararoosh!
