### ISSUE TITLE
Should we divide the large neighborhoods (e.g., Georgetown) into smaller neighborhoods?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#258]
It's a bit overwhelming to try and audit Georgetown with the way that our missions are currently structured. I have to audit 12 miles to complete Georgetown--that's huge compared to many neighborhoods. Just a discussion point for now but something to come back to for future releases.

![image](https://cloud.githubusercontent.com/assets/1621749/17991546/a5b06098-6b0d-11e6-822e-d75932617114.png)

**Comment by misaugstad** [comment]
Dividing neighborhoods into smaller segments is definitely something we are doing in our current deployments (something that @richardwmcgovern has been a huge help with!).
