### ISSUE TITLE
Multiple labels on expanded modal in Gallery

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2580]
##### Brief description of problem/feature
With the redesign of Gallery, I am sometimes seeing multiple labels (of different label types) showing up on the same image. This is only happening in the expanded section, not the smaller cards.

![Screenshot from 2021-06-16 13-02-24](https://user-images.githubusercontent.com/6518824/122302965-b111c180-ceb7-11eb-9b58-43a30923d4a2.png)

**Comment by misaugstad** [comment]
And another example
![Screenshot from 2021-06-16 12-57-06](https://user-images.githubusercontent.com/6518824/122303052-cc7ccc80-ceb7-11eb-8886-fbe25d8bca66.png)

**Comment by jonfroehlich** [comment]
I'm seeing this too!

![image](https://user-images.githubusercontent.com/1621749/122487267-b7736c80-cf8f-11eb-97c6-d5ec85e1b01f.png)
