### ISSUE TITLE
Fix remaining comments from Gallery PR

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2582]
##### Brief description of problem/feature
We merged PR #2570 a bit early so that we could take screenshots and try it out on production. Which means that there are still some comments from PR reviews that haven't been addressed yet. Going to try and list them here:
- [x] Remove `grid-area` CSS attributes [link](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2570#discussion_r647058796)
- [x] Update some comments [link](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2570#discussion_r647064966)
- [x] Add +n visual when there are more tags than we can display on the small card [link](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2570#discussion_r647068705)
- [x] Clean up the code that is copied into `Gallery.Panorama.js` (and can you rename it `GalleryPanorama.js`) [link](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2570#discussion_r647070808)
- [x] There are some constants that should be created/used [link](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2570#discussion_r653052931)
- [x] Fix the cursors (1-3 in [this comment](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2570#pullrequestreview-677999108))
- [x] ~Remove the movement capability in GSV (5 in [this comment]~(https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2570#pullrequestreview-677999108)) <- We decided that movement in GSV is fine
- [x] ~Fix the card being covered up by the footer (7 in [this comment](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2570#pullrequestreview-677999108))~ <- This has been replaced by issue #2616

**Comment by jonfroehlich** [comment]
Is this checklist up-to-date now that @ThatOneGoat and you made some changes for ASSETS poster deadline?

Also, I think moving in GSV is fine. I don't think we necessarily have to disable it.

**Comment by misaugstad** [comment]
Thanks for looping back to this. We created an issue for one of those tasks so I crossed it off. I finished one of the other ones earlier, and I crossed out the movement in GSV one since that one is fine as-is.

**Comment by ThatOneGoat** [comment]
> * Fix the cursors (1-3 in [this comment](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2570#pullrequestreview-677999108))

In agreement with bullet point 3, for now I'll keep the gallery tags on the cards and modal as `cursor: default`. If/when we implement interactability with the tags, we can switch the pointer type then.
