### ISSUE TITLE
Sidewalk Gallery: Quick crit of new interface

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2587]
First of all team, congrats on rolling out a new version. AWESOME! It's a joy to work with such a talented team. 

I just wanted to provide a few notes of feedback while it's fresh. I've been steadily using the old UI the past few days, so the jump to the new UI is a bit dramatic. But, in general, despite my crit below, I do believe we are moving in the right direction.

Here's the old UI:
![image](https://user-images.githubusercontent.com/1621749/122485031-d4f20780-cf8a-11eb-90b7-9ccf6bf7bd31.png)

Here's the new UI:
![image](https://user-images.githubusercontent.com/1621749/122485053-dfac9c80-cf8a-11eb-98b5-1ad8021c2c27.png)

But some issues with new UI:
- Overall, I think the new UI has a lot of visual distractions overlaid on each image card, which interferes with a visual scan of the images. The old UI seemed to really emphasize the **imagery** as a first class object and the metadata as secondary. The new UI intermixes them and, I think, overly highlights the metadata. I think we might be able to find a nice compromise. But for now, this is my primacy concern. The gallery view now is just too busy--it's taking away from the core ROI of the gallery, which is the images!
- What happens when there are lots of tags (2+) applied to a label, which, in my experience was quite common. How does the new UI handle this? Do we show multiple rows of tags on the overlay?
- The severity and tags overlay look interactive (they have the _affordance_ of interactivity), even though they are not. This is a problem but will perhaps be a future strength once we make these editable (see Issue https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2575) but for now, it's confusing.

Some more detailed UI feedback:

1. Too much white space between sidebar and gallery view. Old UI did not have this problem (even at different windows sizes; and I've tried both on my laptop and external monitor)

![image](https://user-images.githubusercontent.com/1621749/122485428-bb04f480-cf8b-11eb-9598-7ea37ee1e5b0.png)

2. I love having both the lil label circles and the label type name in the top-left corner of each card, however, it's very hard to read the text based on some backgrounds. I used a dark red rectangle on two examples (but there are even worst examples that I did not screenshot but saw when I first loaded the UI). Lots of potential strategies here (like adding a subtle dark gradient behind the white text, which is what we do on the [Makeability Lab website](https://makeabilitylab.cs.washington.edu/) for the text on top of the banners or adding a black outline around the white text),

![image](https://user-images.githubusercontent.com/1621749/122485612-38c90000-cf8c-11eb-86c0-acb9fc7b42c6.png)

3. I'm not sure I agree that we need to always have the 'Agree, Disagree, and Not Sure' buttons showing. It's also not clear that they are interactive or what they are, exactly. (To solve the interactivity problem, I think each lil button should change its background to a light green, light red, and light yellow when the mouse moves over them). The buttons are also far smaller than our previous UI, which makes them harder to click on. Given that to provide feedback on correctness, you have to, by definition, move your mouse over the target card (to provide feedback), I still think hiding these buttons except on mouseover is the right way to go.

![image](https://user-images.githubusercontent.com/1621749/122485869-c7d61800-cf8c-11eb-99b8-0699abe17a69.png)

4. We use a different visual language for selecting severity. On the regular gallery cards, we show a "selection" via a solid white fill. On the expanded card, it's a black fill. Need consistency here. I say black for both?

![image](https://user-images.githubusercontent.com/1621749/122487052-269c9100-cf8f-11eb-8094-6fa612bbe959.png)

5. The numbers in the severity circles are not perfectly vertically aligned. They are too far down. Maybe off by 1 or 2 pixels. Also, it looks like we are using two different font sizes. Notice how the number 1 and 2 is smaller than 3, 4, 5. So, that could be one source of the vertical alignment problem.

![image](https://user-images.githubusercontent.com/1621749/122487128-5a77b680-cf8f-11eb-9079-65f29eb3108c.png)

It looks worse when you shrink your window and it becomes more noticeable.
![image](https://user-images.githubusercontent.com/1621749/122487625-8cd5e380-cf90-11eb-8d48-5aa15d89ef1a.png)

6. When you click on a card to expand it, the underlying card that you clicked on can disappear because the grid gets reorganized and the selected card gets hidden (need to scroll to it). Instead, after you click on a card, the clicked on card should be like centered next to the expanded card. Then, if you click on the left/right arrows, the underlying card on gallery view should come into view too (and also have a lil highlight like an outline or something).

As now, watch what happens when I click on the tree picture (2nd row, 1st image).

![image](https://user-images.githubusercontent.com/1621749/122490080-f86e7f80-cf95-11eb-8f01-fbcf8fedda79.png)

Now it's gone! 

![image](https://user-images.githubusercontent.com/1621749/122490136-22c03d00-cf96-11eb-839c-eceef008888f.png)

This is confusing. Instead, when going from nothing expanded to showing the clicked on expanded card, the just clicked on image should be scrolled to be row 1, col 1 or row 2 col 2 as the default

7. The Severity overlay visually conflicts with the large bolded Google text on bottom-left corner of card:
![image](https://user-images.githubusercontent.com/1621749/122565051-e246da80-cffa-11eb-8ccd-dadb50d4f739.png)

Can we move the Google text to top-right of card? Otherwise, we'll have to move up the severity text a few pixels so it doesn't overlap.

8. The filter bar on the left side should be set as a float with an absolute y position so it stays in place even when user scrolls. As now, when I open an expanded card, the filter bar can go away.

![image](https://user-images.githubusercontent.com/1621749/122566359-52a22b80-cffc-11eb-9453-1cc6a6494f47.png)

Happy to discuss my comments below but wanted to brain dump first impressions.

I so appreciate everything you've done on this thus far @kumararoosh and @isavin12. And it's really only through some use like I'm doing now that I can provide a detailed crit like this. So, glad we pushed it!

**Comment by misaugstad** [comment]
>The old UI seemed to really emphasize the imagery as a first class object and the metadata as secondary. The new UI intermixes them and, I think, overly highlights the metadata. I think we might be able to find a nice compromise. But for now, this is my primacy concern. The gallery view now is just too busy--it's taking away from the core ROI of the gallery, which is the images!

Honestly, a very basic slight improvement we could do is just to decrease text size and the size of the severity rating circles. Just to make a higher percentage of the area be the actual image.

>What happens when there are lots of tags (2+) applied to a label, which, in my experience was quite common. How does the new UI handle this? Do we show multiple rows of tags on the overlay?

We go into more detail in #2588 

>The severity and tags overlay look interactive (they have the affordance of interactivity), even though they are not. This is a problem but will perhaps be a future strength once we make these editable (see Issue #2575) but for now, it's confusing

Agreed, excited to make these editable :) I imagine us adding an "X" to the tags so that you can delete them, and a "+" at the end of the list so you can add new ones!

>Too much white space between sidebar and gallery view. Old UI did not have this problem (even at different windows sizes; and I've tried both on my laptop and external monitor)

You are so right about this!

**Comment by jonfroehlich** [comment]
A simple fix, which I'm doing right now in dev console for screenshotting, is to change the `grid-template-columns: 1fr 3fr;` to  `grid-template-columns: 0.75fr 1fr;` but not sure how that will scale at diff window sizes.

![image](https://user-images.githubusercontent.com/1621749/122488974-7ed59200-cf93-11eb-95cc-39201ef38a64.png)

**Comment by isavin12** [comment]
For the card design, I think we should revise it to the following, which addresses the above comments. I will post mocks tomorrow:

- Label Type (without the icon on the left, confusing to have two icons per card). I'll play with the text color for legibility.
- Severity: Just a number, no circles for now. (e.g 4/5). Keep circles on Modal.
- Tags: 10pt maximum font size. Add +n if there are multiple tags that don't fit
- Agree/Disagree Buttons: Only on mouseover. Minimum 36px button height (or maybe these are just on the modal).

Also posting my previous mockups for reference. If we can get closer to these in terms of proportions and sizing that would be great. Some notable things that were not implemented:

- When opening the modal, all cards except the selected card should have a 50% transparent white mask over them
- Right under GSV in the modal there should be a timestamp for the GSV image date and date the tag was created. 
- The modal should have large Agree/Disagree Buttons (maybe we have these buttons just on the modal and not on the cards?)
- Text size should match the specs. Or at least look close in proportion. (I will revise tags and severity to be even smaller on the cards)
- +n is missing from tags on cards. 

![Card Design Spec-01](https://user-images.githubusercontent.com/56325998/122491359-ae3acd80-cf98-11eb-9a97-210b77a09634.jpg)
![Card Design Spec-02](https://user-images.githubusercontent.com/56325998/122491364-af6bfa80-cf98-11eb-8f24-6587235e02f3.jpg)

**Comment by misaugstad** [comment]
>The modal should have large Agree/Disagree Buttons (maybe we have these buttons just on the modal and not on the cards?)

As much as I want this, changing it seems like too much engineering work for this weekend on top of everything else, and I don't think it is the worst thing in the world. Would still love to see mocks with it, but maybe also a mock without it?

**Comment by isavin12** [comment]
Here's some updated UI Mocks per the above comments. I prefer the light color scheme with one line of tags. 
Notable Changes:

- All metadata moved to bottom of card
- Severity visualization is simplified
- Tag size Reduced
- Agree/Disagree buttons only on mouseover
- Verified cards change color and outline
- Modal incorporates image time stamp, label time stamp, and increased size for GSV. Verification buttons on card only.

![New Cards without Sidebar – 8](https://user-images.githubusercontent.com/56325998/122583489-242d4c00-d00e-11eb-8348-908645861e21.png)
![New Cards with Sidebar – 2](https://user-images.githubusercontent.com/56325998/122583488-22fc1f00-d00e-11eb-8fa8-81e633dc2563.png)

**Comment by jonfroehlich** [comment]
I like it! I agree that lighter is better. I think that the using a dark fill on the tags gives them too much prominence. How about simply using outlined rounded rectangles

![image](https://user-images.githubusercontent.com/1621749/122584183-e846b680-d00e-11eb-9daa-94e6d088aa6a.png)

On the expanded card, since we will want to make these editable, I think we should show:

- All the tags for that label type even if not selected (then user can select if they want to edit)
- The severity info needs to be more self-explanatory (maybe we use the frowny faces as the labeling interface does)
- The tag and image timestamps are not super clear.

**Comment by isavin12** [comment]
Design Specs incorporating above changes:

![Card Specs](https://user-images.githubusercontent.com/56325998/122588058-7c1a8180-d013-11eb-9789-ad5510fbbc77.JPG)
![Modal Specs](https://user-images.githubusercontent.com/56325998/122588062-7cb31800-d013-11eb-8f00-5a6c97a2ffcf.png)

**Comment by manaswis** [comment]
Just poppin in to say, I so LOVE this! ❤️  
Especially, lovin' the progression of the UI design improvements and attention to detail!

Amazing job @isavin12 (and @jonfroehlich of course) :D!!

**Comment by jonfroehlich** [comment]
So, I think we can go with the designs in https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2587#issuecomment-864136015.

My understanding is that @kumararoosh's summer internship has now started so this will have to be mostly handled by @ThatOneGoat and @misaugstad. Try your best to work to @isavin12's awesome spec.

Let's start with this and then we can loop back to addressing other concerns. Sound good?

**Comment by misaugstad** [comment]
This sounds good.

One thing we'll want to think about is what it eventually looks like when we add an outline or something to cards when a label has been validated. Right now we have basically the color of "agree" just for a selected card. Not necessary to deal with immediately though.

**Comment by jonfroehlich** [comment]
I didn't think @isavin12 "selected state" mockup was just for the selected card but rather when a card had been validated (which I believe he was called the "selected state"). So, you could have all 9 images with different colored outlines (green, red, yellow) depending on whether and how they've been validated.

**Comment by misaugstad** [comment]
yep I realized that and I was in the middle of writing a comment to say so! thank you!

**Comment by ThatOneGoat** [comment]
As an update, here is what the current UI looks like (with no expanded cards):
![image](https://user-images.githubusercontent.com/37346427/122656549-6939a700-d110-11eb-82fc-3cd500b71ef7.png)
Here is an example with some cards validated:
![image](https://user-images.githubusercontent.com/37346427/122656571-925a3780-d110-11eb-9398-94055f6a9f7d.png)
Here is an example with a card with extra tags that can't be shown (+n):
![image](https://user-images.githubusercontent.com/37346427/122656577-aef66f80-d110-11eb-9822-b28587e5a5fb.png)

Currently, I'm working on updating the actual expanded modal, but I want to get these screenshots out for feedback (also I've pushed the code, so those with the dev env can give it a look on their own local machines - definitely could use any help finding bugs!). 

As for the work on the expanded modal, the big thing I want to do is implement an autoscrolling feature so that any clicked card is centered on the left (is actually visible) when it is selected/expanded.

**Comment by jonfroehlich** [comment]
This looks really good. Super clean and to @isavin12's amazing spec.

Can't wait to see the expanded card. I had some ideas about the "autoscrolling" feature and just creating a better interactive linked connection between gallery cards and expanded cards here: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2589#issuecomment-864120423 (which includes a bonus video of Michael Jordan and Google Image Search's interaction).

**Comment by ThatOneGoat** [comment]
Yup, just finished the autoscrolling feature (at least an initial version of it) and pushed it to remote (on my branch, 2587_New_Gallery_Interface). I decided to instead go with Ilia's mocks where the nonselected cards (when in modal mode) are semitransparent while the selected card is fully opaque. However, this is probably a discussion to be continued in the actual thread you put down, so I'll update with some screenshots there.

**Comment by jonfroehlich** [comment]
Makes sense. I think as long as the semi-transparent overlay does not make it too difficult to see the underlying card, we should be good. Thanks for all your awesome work on this @ThatOneGoat!

**Comment by isavin12** [comment]
Great Job guys, here's some feedback from testing the live version at https://sidewalk-newberg-test.cs.washington.edu/gallery

Card Edits (refer to specs):

- "Label Type" text (Curb Ramp, etc.) should be BOLD
- "Severity" and "Tags" title text should be regular with a weight of 400
- Text within tags should be BOLD
- Let's give the tags just a bit more padding around the text
- All text and stroke/fills should be dark blue (#2d2a3f) not black

Modal Edits:

- On my big screen, the text at the bottom isn't aligned with the edges of the image. Looks fine once I minimize the window. (see first screenshot)
- "Label Type" text (Curb Ramp, etc.) should be BOLD
- Can we move GSV down to give the "Label Type" text more whitespace/breathing room?
- Titles (Severity, Tags, Temporary, Description) should be BOLD
- Severity numbers replaced with smileys
- A little more padding around text within tags. Text within tags should be BOLD
- All text and stroke/fills should be dark blue (#2d2a3f) not black. Exception is the data for "temporary" and "description", which should be Grey (#888787)
- Change "Labeled" and "Image Date" text to 400 weight (regular)

Usability:

- When I click on a card, I see multiple tags in GSV. Can we change it to just be the tag in the card (see second screenshot)
- When I pan around in GSV, I lose my place. Can we make clicking the card return you to the original position?
- Running into overlay issues once I reach the footer (see third screenshot).
- Would it make sense to make the scroll infinite? Or is having pages like we do currently better?


![Text not aligned](https://user-images.githubusercontent.com/56325998/122831382-acc21b80-d29e-11eb-985e-1239da351622.JPG)

![Multiple Tags](https://user-images.githubusercontent.com/56325998/122831396-b0ee3900-d29e-11eb-8114-2487aeeea796.JPG)

![Overlay issues](https://user-images.githubusercontent.com/56325998/122831404-b3509300-d29e-11eb-812c-fbf6fbc82468.JPG)

**Comment by misaugstad** [comment]
Love it, thank you @isavin12 !

@ThatOneGoat Try to get as much of the visual stuff as possible done by, say 10 pm along with a PR. That should give me about enough time to put that code on production before I head to bed. Which will mean that @jonfroehlich will have the most recent stuff if he wants to take a look in the morning.

I think that all of the stuff that @isavin12 listed under "Card Edits" and "Modal Edits" should be done (and should hopefully be easy). I would just skip the issue of the bottom of the modal not lining up with the bottom of the page. That sounds more difficult and is less important than the other things right now.

I would suggest removing a bit of the space between the severity circles and the word "Tags" on the small cards, which will give a tiny bit more room to add actual tag names! Especially important for Spanish language version.

I haven't checked this, but when we filter for specific tag(s), are those being brought to the front of the list on the small cards? If not, we should also implement that ASAP so when you filter you actually see the right tags being shown on each card.

If you get through all of _that_, then I would think it's time to move on to bugs like multiple labels on an image and closing the modal when the filter is changed!

**Comment by ThatOneGoat** [comment]
> * "Label Type" text (Curb Ramp, etc.) should be BOLD

Unfortunately, it seems like CSS caps the max font-weight at 900. As a result, making the label type text even "bolder" doesn't look that different (for example, I switched to use font-weight: 900 and font-weight: bolder; there's a very very slight difference). Unless I'm misinterpreting what you're suggesting, maybe we use a thicker font?

**Comment by isavin12** [comment]
I think having bold at 700 is fine. We just need to make sure everything that I've labeled "bold" is at 700 and everything else is "regular" at 400. 

Would using `font-family` instead of `font-weight` help? For instance use `font-family 'Raleway Bold' ` and then for regular use `font-family 'Raleway Regular' `  ? I'm not sure if those are defined by you or by the system. If they're defined by you, just ignore my question.

**Comment by ThatOneGoat** [comment]
> I think having bold at 700 is fine. We just need to make sure everything that I've labeled "bold" is at 700 and everything else is "regular" at 400.
> 
> Would using `font-family` instead of `font-weight` help? For instance use `font-family 'Raleway Bold' ` and then for regular use `font-family 'Raleway Regular' ` ? I'm not sure if those are defined by you or by the system. If they're defined by you, just ignore my question.

Ah gotcha. I switched to using font-family: 'Raleway Bold'. Here's there result:
![image](https://user-images.githubusercontent.com/37346427/122848701-f6226300-d2be-11eb-9537-b1d9b205770d.png)

Here's just using font-family Raleway-Regular with bold font-weight:
![image](https://user-images.githubusercontent.com/37346427/122848782-12be9b00-d2bf-11eb-90b8-58262af2344e.png)

Thoughts?

**Comment by isavin12** [comment]
The first one, using `font-family: Raleway-Bold` looks perfect! I was designing using font-family, so if we can assign font-families to all text, that would be ideal. Thanks!

**Comment by ThatOneGoat** [comment]
> * Severity numbers replaced with smileys

Personally, I feel this would make the severity rating kind of confusing. Note that, even though we use smileys on the audit page (when placing labels), to me, they are a supplement to the number severities underneath, which provides an understandable severity scale (1 - 5).  I feel like if we just use smileys on the expanded modal, it might get a little ambiguous.

Though, maybe I missed your justification somewhere, @isavin12?

Also, @misaugstad @jonfroehlich @kumararoosh , any thought?
