### ISSUE TITLE
Sidewalk Gallery: New UI, tag selected but not shown in card

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2588]
I think this has to do with the fact that the new UI only shows one or two tags per card at a time (which is broken imo, we need to show all applied tags for each card like the old UI). 

But one confusing effect of this is that when I go to the filter sidebar on the left and select something, the resulting cards look like they do not match the selected filter!

![image](https://user-images.githubusercontent.com/1621749/122486288-9c9ff880-cf8d-11eb-8ef2-60694e511efc.png)

I think the fix should be that we need to show all applied tags on every card, so we need to redesign how we show tag overlays.

**Comment by misaugstad** [comment]
As mentioned in #2582, the intended functionality at this point is supposed to be if there are too many tags to fit on the card on that one line, we show something like "+n" after the last one they see, presumably with a tooltip showing the tags that aren't shown on the card..? We should show all the tags on the expanded card though.

That's a good point though, that if we filter by a specific tag, that tag should probably be brought to the front of the list so it's actually being shown!

**Comment by misaugstad** [comment]
@jonfroehlich also mentioned on a video call that it we might want to make the tag size conditional. where we aim to do it in one line, if there are too many tags, we decrease the text size and split it across 2 lines that take up about the same space. and if it takes more than 2 lines, we do the "+n" approach. I'd be interested to see what that looks like.

I'm still personally okay with showing only one line of tags (with the +n) in the thumbnail sized images. Though of course we should show all the tags on the full sized images.

**Comment by isavin12** [comment]
Here's two ways of doing it. I prefer 1 line, as long as all applied tags are visible in the modal. Same mocks as posted in #2587 

![Tag UI Options](https://user-images.githubusercontent.com/56325998/122582188-b59bbe80-d00c-11eb-9ee7-a7358ff75a6d.JPG)

**Comment by ThatOneGoat** [comment]
Resolved by PR 2587

**Comment by misaugstad** [comment]
closing via #2596
