### ISSUE TITLE
Sidewalk Gallery: Showing Agree, Disagree, Not Sure Feedback for Cards

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2591]
I recall that @isavin12's mockups outlined the gallery cards in green, red, and yellow to show which cards the user has already validated. However, as now, they just show gray.

![image](https://user-images.githubusercontent.com/1621749/122563847-8d569480-cff9-11eb-8665-fe1f8b9ac31c.png)

@isavin12 can you copy/paste that mockup in this thread?

Also, I think it's important that, if the user is logged in, when we show labels that the user has previously validated (not just in that user session), that we show them as validated in the gallery (using the same indicators).

**Comment by ThatOneGoat** [comment]
Resolved by 2587. I'm not 100% sure if we are maintaining validations across sessions, but I think we do? I need to confirm (if not, I'll make a seperate functionality issue for that)

**Comment by jonfroehlich** [comment]
The key is that if the user is logged in, that you will have to download the validation data from the server from that user and appropriately render the validation info on the cards.

**Comment by misaugstad** [comment]
closing via #2596 

made a new issue for showing older validations: #2603
