### ISSUE TITLE
TaskModel is Not Defined

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#260]
I tried to do my nightly testing of Project Sidewalk. After I logged in and clicked participate, I was greeted by a blank audit screen. The Javascript console says: "276:710 Uncaught ReferenceError: TaskModel is not defined"

![image](https://cloud.githubusercontent.com/assets/1621749/18024268/c2c7dc30-6bd3-11e6-995f-80a3452bf0d2.png)

**Comment by kotarohara** [comment]
Hmmm, could this be because of cache?

**Comment by jonfroehlich** [comment]
Seems to be working now but let me test a bit more.

**Comment by jonfroehlich** [comment]
Closing as I cannot replicate problem. Maybe it was due to cache?
