### ISSUE TITLE
Gallery expanded view should close when changing filter

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2606]
##### Brief description of problem/feature
When you are looking at the expanded view of a card in Gallery and then you change the filtering options, the expanded view stays open. This is a problem because usually you are adding a filter that would remove the card you're looking at from the list! An example of this looking bad is below.

Click on a card...
![Screenshot from 2021-06-22 14-44-03](https://user-images.githubusercontent.com/6518824/123004089-02fb9100-d369-11eb-8f27-f6f74c8b12c7.png)

Then filter for a totally different label type and the old label is still shown...
![Screenshot from 2021-06-22 14-44-18](https://user-images.githubusercontent.com/6518824/123004095-055deb00-d369-11eb-8959-df53fb7ec60d.png)

##### Expected behavior
We would expect the expanded view to close when changing the filter.

**Comment by misaugstad** [comment]
This issue was accidentally created, but since we don't have the ability to delete issues right now, I just edited the content with an issue that we were going to file anyway!
