### ISSUE TITLE
Labels spilling outside GSV image in Gallery

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2608]
##### Brief description of problem/feature
I've started to occasionally see the issue below, where on the small cards in Gallery, a label that is near the edge of the image can spill over on the the white space outside the image.

![Screenshot from 2021-06-22 16-40-24](https://user-images.githubusercontent.com/6518824/123026778-9648bc80-d391-11eb-9daa-73875a98912a.png)

##### Expected behavior
I think that we would expect the label to just be cut off at the edge? Another option is trying to center the label in each image.

**Comment by jonfroehlich** [comment]
Just came across this too! 

![image](https://user-images.githubusercontent.com/1621749/127210211-a255b778-743b-445f-a817-b019e106194f.png)

**Comment by misaugstad** [comment]
Posting about this now so I don't lose track of these screenshots: I've just fixed this as a part of removing the old Tohme code (#956). The labels were both in slightly the wrong position (off by approx the label's radius in both directions) while also spilling over the edge. We don't have anything spilling over the top because we have that thin bar at the top of the Explore page that says "Explain this!" that prevents users from placing labels on that edge.
Before
![Screenshot from 2023-03-08 11-42-33](https://user-images.githubusercontent.com/6518824/223827318-3d6b5b4b-f2ea-4337-bedb-7f535480ddcb.png)

After
![Screenshot from 2023-03-08 11-40-24](https://user-images.githubusercontent.com/6518824/223827296-097cb0d5-31aa-4b05-bc34-3f684ee81373.png)

**Comment by jonfroehlich** [comment]
Wooohooo! Go @misaugstad go!!! 👏
