### ISSUE TITLE
Curb Ramp and Missing Curb Ramp on this Screen Should be Plural

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#261]
![image](https://cloud.githubusercontent.com/assets/1621749/18024288/174f5814-6bd4-11e6-9a88-fc0312a8381d.png)

**Comment by manaswis** [comment]
Fixed it here: PR https://github.com/ProjectSidewalk/SidewalkWebpage/pull/325
