### ISSUE TITLE
What should it look like if we can't even show one tag in Gallery?

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2612]
##### Brief description of problem/feature
How should the tag section look if the only tags we've got are too long to fit on the small card? Right now it just says "+1" which looks a bit silly.

![Screenshot from 2021-06-22 20-41-46](https://user-images.githubusercontent.com/6518824/123032232-7964b700-d39a-11eb-9c61-4e27a65ff043.png)

**Comment by jonfroehlich** [comment]
Can we use the ellipses? That is, just show the first N chars of the tag then ellipses.
