### ISSUE TITLE
Sidewalk gallery: clicking on and mousing over the +1, +2, +N stuff doesn't do anything

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2614]
When I moused over or clicked on the +1 tag, I expected to see a lil hover with the full tag information for the label.

![image](https://user-images.githubusercontent.com/1621749/123146692-09464780-d413-11eb-9f3b-7b0d0567475e.png)

I could imagine doing two things:

- On mouse over, show a lil hover popup of all tags
- On click, open expanded card

**Comment by ThatOneGoat** [comment]
Here is a very simple mock design I whipped up for the tooltip:
![Uploading tooltip for gallery.png…]()

**Comment by misaugstad** [comment]
Right, I also feel like it might look better as just a white background with black text? I realize that that doesn't fit the look of the tags elsewhere, but the black background definitely looks off to me, and I'm not sure I see how to make it work.

Well, one idea, and this might be the right look anyway given the weird spacing, is to set a max width that is a lot wider, and let there be multiple tags on each row (similar to how we have it on the expanded view).

**Comment by jonfroehlich** [comment]
Thanks @ThatOneGoat for mocking up some ideas. I agree with @misaugstad that we need a pop-up with a white background.

Perhaps you can sort of copy this mock?

![image](https://user-images.githubusercontent.com/1621749/126161987-8af30478-c564-450d-81be-eb5a28a1c72c.png)

From here: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/456#issuecomment-870758413

**Comment by isavin12** [comment]
I would think that the +1 would just open up the expanded card, but I see how that could be frustrating for someone skimming through. @ThatOneGoat you have the right idea, here's a mock of what I think Jon is talking about. Two options: One is just a popup, the other is a popup with a white mask on hover. All tags should be the same height and font size though.

![Popup](https://user-images.githubusercontent.com/56325998/126936819-edfd4a32-31ba-4394-8dff-382c5c937575.JPG)

**Comment by misaugstad** [comment]
I think that the first one looks good!

@ThatOneGoat as far as implementation goes, you are probably looking for something like a bootstrap popover.

**Comment by ThatOneGoat** [comment]
> I think that the first one looks good!
> 
> @ThatOneGoat as far as implementation goes, you are probably looking for something like a bootstrap popover.

Yeah, I've been using just tooltip for now, but I'll see how popover goes
