### ISSUE TITLE
Prevent Sidebar/Expanded Modal from Overlapping with Footer.

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2616]
Currently, it is possible to scroll all the way to the bottom such that the sidebar (and expanded modal when a card is selected) overlaps with the footer. This is not ideal.

The proposed solution is to make the sidebars/expanded modal "sticky" up to the point when they make contact with the top of the footer.

Here are "before" pictures of the issue:
Sidebar overlapping:
![image](https://user-images.githubusercontent.com/37346427/123206246-3543e600-d470-11eb-899e-31f180636027.png)

Expanded Modal (and sidebar) overlapping:
![image](https://user-images.githubusercontent.com/37346427/123206286-47258900-d470-11eb-873d-fce8ffd3f7e2.png)

**Comment by jonfroehlich** [comment]
To me, this is really about how the modal interferes with the prev/next buttons, which is a problem. Maybe an easy fix is to give the `< [1] >` a white background and a higher z-axis value so it's out infront of the modal?
