### ISSUE TITLE
Sidewalk Gallery: should we include Other?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2617]
I'm not sure we should include Other. If the team thinks that the 'Other' label type is important, perhaps we do not include it when 'All' is selected and only show 'Other' when that label type is selected in the drop down.

It's just not always clear why someone labeled something as Other unless they say so...

![image](https://user-images.githubusercontent.com/1621749/123325947-80e8a500-d4ed-11eb-8795-692948a52844.png)

**Comment by misaugstad** [comment]
I agree that we should take it out of the "All" category. Or at the very least, we shouldn't be bringing _so many_ Other labels to the first page in the "All" category. I think that we are trying to get `n` labels of each label type on the initial page load, and at the very least, Other should be reduced in frequency.

**Comment by jonfroehlich** [comment]
OK, I say we take it out of the 'All' category then :)
