### ISSUE TITLE
Escape on the 'Explain This' Window Should Close Window

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#262]
I should be able to hit escape to close this window:

![image](https://cloud.githubusercontent.com/assets/1621749/18027157/e5b5957e-6c29-11e6-9044-06ea396a6354.png)

**Comment by kotarohara** [comment]
@Soben713 You want to do this? We can work on it on Mon together.

**Comment by Soben713** [comment]
@kotarohara Will do. :)
