### ISSUE TITLE
Should This Be Marked as an Obstacle or Surface Problem?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#263]
When auditing, I occasionally run into sidewalk problems that could legitimately labeled with different label types. For example, in this case, I feel like the grass could be labeled either as a surface problem or a sidewalk obstacle. It feels more like a surface problem, however, so I went with that.

The key point here, however, is that when evaluating accuracy, we may need to take these sort of ambiguities into account. Thoughts from @manaswis, @Soben713, @kotarohara ?

![image](https://cloud.githubusercontent.com/assets/1621749/18029220/18446caa-6c60-11e6-8cac-ff62e52239cd.png)

Zoomed in:
![image](https://cloud.githubusercontent.com/assets/1621749/18029223/4c341664-6c60-11e6-899e-ef3c73791b54.png)

**Comment by manaswis** [comment]
Clear definitions would be needed to resolve ambiguities during analysis. E.g. Surface problem could only include issues inherently *internal* to the surface e.g. grass, protruding surface etc. While obstacles could be something *external* to the surface e.g. things placed on the sidewalk

That's an example definition. But my point is defining each clearly with a distinguishing feature.

**Comment by jonfroehlich** [comment]
I agree with you @manaswis but the larger point is that we should not be penalizing or otherwise marking a user's label incorrect in these edge cases as either a surface problem or sidewalk obstacle is sort of legitimate.

**Comment by kotarohara** [comment]
I guess in this case it's pretty clear that this is a surface problem. But I agree more ambiguous cases could pop up. In CHI2013 we turned categories of labels into binary labels of Accessible vs. Not Accessible for the same reason.

**Comment by jonfroehlich** [comment]
Yep, I remember that.

We can discuss this today a bit and then likely close the Issue because the solution is likely on the analysis side rather than on the front end UI side.

**Comment by kotarohara** [comment]
Can I close this?

**Comment by jonfroehlich** [comment]
Yes
