### ISSUE TITLE
Some tags are just too long in Spanish

### ISSUE THREAD

**Issue by ThatOneGoat** [ProjectSidewalk/SidewalkWebpage#2636]
Some of the tags in Spanish are very long, such that they leak out of the sidebar as so:
![image](https://user-images.githubusercontent.com/37346427/127115793-fdd1aab3-4634-40e3-84c9-cb36b6d0007a.png)

**Comment by jonfroehlich** [comment]
Good catch. Can we auto-truncate with ellipsis:

https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

And then have mouseover support for fullname?

**Comment by rpechuk** [comment]
Made some changes, here is what the tags look like without hovering over them:
![image](https://user-images.githubusercontent.com/39865166/127573984-132848a5-050f-433b-b63e-069f9137eaa3.png)
and here is what they look like while hovering over them:
![image](https://user-images.githubusercontent.com/39865166/127574029-e85c3dca-79e2-412f-a019-8bef4fd249dc.png)
Next commit will contain these changes if you want to mess around with them, feel free to give me feedback and i'll implement asap @jonfroehlich @misaugstad @ThatOneGoat !

**Comment by rpechuk** [comment]
I forgot to mention the issue in the commit message and have no other code to commit so see this branch: 
#2636-truncate-spanish-tags-gallery

**Comment by jonfroehlich** [comment]
Looks reasonable to me. Nice work @rpechuk!
