### ISSUE TITLE
Redesign smiley severity scale to start at a neutral face

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2640]
##### Brief description of problem/feature
In #2601 we discussed the possibility of changing the smiley faces associated with the severity rating scale to start at a neutral face instead of a happy face, because a low severity problem isn't a good thing.

A counterpoint that hasn't been mentioned yet is the fact that we are labeling both problems _and features_. A severity 1 curb ramp is a very positive thing, so it makes sense for the curb ramp rating scale to begin with a full smile. Do we want it to be different for problems vs features? If so, we would need to figure out what to do about the severity filter in the left sidebar in Gallery. Or since there are more problem label types than features label types, maybe we are happy with switching them all over to starting at a neutral face?

If we decide to make a change, the changes should show up on /audit, /validate, and /gallery.

**Comment by jonfroehlich** [comment]
This is really important now because our filter bar seems to indicate that a problem of '1' or '2' deserves a happy face. This is not appropriate. We should not signal content with a sidewalk problem rated as a '1' or a '2'—it's still a problem.

![image](https://user-images.githubusercontent.com/1621749/128017688-001f0c4f-452c-4b04-ab68-5ece7ea511e1.png)

In terms of a counterpoint of having a '1' for a curb ramp. Fair enough, but I still think having a neutral face for that is better than having happy faces for the problems. I'd rather switch to neutral faces ASAP and worry about the potential inconsistency with curb ramps later (and if we add crosswalks, that "positive feature" will also have same issue as curb ramps).

**Comment by ThatOneGoat** [comment]
Still applicable, though this is more of a design question.

**Comment by jonfroehlich** [comment]
@Luciozzz This is another icon design task that is pretty important.

I agree with @misaugstad that for **accessibility features** like curb ramps, pedestrian signals, and crosswalks, we could use the same or similar icon design:

![image](https://user-images.githubusercontent.com/1621749/140611859-a3e7dd74-1fa2-4410-bd4a-a880b5cef9b3.png)

But for **accessibility problems** like surface problems, no sidewalk, obstacles in path, better to start with neutral and get worse (just used MS Paint here to demonstrate starting with neutral at 1):

![image](https://user-images.githubusercontent.com/1621749/140611900-9481ddf3-d0f5-45be-98ff-3f00cf87a5c5.png)

**Comment by Luciozzz** [comment]
I redesigned the happiest and the saddest faces in order to differentiate more with the 2nd happiest and 2nd saddest faces. And I added a very sad face and an extremely sad face. Hope this works!
![image](https://user-images.githubusercontent.com/18668038/141053864-8274d858-8251-4883-a64a-eb1c1ad7361f.png)
@jonfroehlich

**Comment by jonfroehlich** [comment]
Nice! I'm not an emoji expert but these are certainly an improvement over what we have now!

Can you make individual versions (.svg and .png) that are well-cropped at the edges and equal sizes?

Let's name them.

```
smile0.png
smile1.png
neutral.png
frown1.png
frown2.png
frown3.png
frown4.png
```

Or something like that. @misaugstad can comment on naming scheme.

**Comment by Luciozzz** [comment]
I suggest we name those faces like this:
![image](https://user-images.githubusercontent.com/18668038/141165987-09476e3b-e109-464c-898e-483829836fac.png)
A larger number means a higher emotion intensity.

Here is a zip of all the named & cropped icons in PNG and SVG:
[Smiley.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/7514895/Smiley.zip)

**Comment by katrimana** [comment]
[smileys_new.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/10045653/smileys_new.zip)

**Comment by hoominchu** [comment]
Attaching some screenshots of the work in progress:
<img width="765" alt="Screenshot 2022-12-18 at 1 10 18 AM" src="https://user-images.githubusercontent.com/8168506/208290166-ca7c7203-a3d9-439d-a941-c097061fef52.png">
<img width="626" alt="Screenshot 2022-12-18 at 1 09 51 AM" src="https://user-images.githubusercontent.com/8168506/208290170-adf62646-95d6-4103-8f4a-edc8dfdfbf5e.png">
<img width="625" alt="Screenshot 2022-12-18 at 1 09 42 AM" src="https://user-images.githubusercontent.com/8168506/208290172-474fe0ec-eb0f-4f81-874d-6f054ce028a8.png">
<img width="799" alt="Screenshot 2022-12-18 at 1 06 57 AM" src="https://user-images.githubusercontent.com/8168506/208290175-0219c6a9-6eb8-4029-ab98-7e348f11add2.png">
<img width="804" alt="Screenshot 2022-12-18 at 1 06 12 AM" src="https://user-images.githubusercontent.com/8168506/208290178-bc876bcc-a29d-457f-afeb-198768d785f4.png">
<img width="801" alt="Screenshot 2022-12-18 at 1 05 47 AM" src="https://user-images.githubusercontent.com/8168506/208290179-208f0eef-a403-4066-8ef2-04027d8a5f4f.png">
<img width="802" alt="Screenshot 2022-12-18 at 1 03 49 AM" src="https://user-images.githubusercontent.com/8168506/208290180-11b0751a-e36c-4fdd-811e-c1430d7005dd.png">

**Comment by jonfroehlich** [comment]
Love it @hoominchu!

I wonder if we might want to switch to a yellow-to-red gradient (using Project Sidewalk colors) where yellow is for Severity 1 and red is for Severity 2 (and we avoid green at all as green is, perhaps, an overly positive signifier.

See colors here: https://github.com/ProjectSidewalk/Design

Maybe extract five discrete levels from the gradient? This tool might help. https://www.colorhexa.com/fbd78b-to-eb734d
<img width="935" alt="image" src="https://user-images.githubusercontent.com/1621749/208312216-ed2fd533-8dff-4268-86e1-34159508f049.png">

**Comment by hoominchu** [comment]
That sounds good!

I tried it out quickly—adding some screenshots/recordings here for reference. @jonfroehlich pointed out that there is discordance between the smiley colors and the 'disagree' and 'not sure' buttons. We are planning to experiment with the saturation/luminance to avoid the same. 


https://user-images.githubusercontent.com/8168506/208314523-62a7b203-1975-4667-a3d0-7eca84ba5bae.mov

![image](https://user-images.githubusercontent.com/8168506/208314528-2d0c294e-4cfc-4c46-a0c6-ce9b3298d6aa.png)

**Comment by hoominchu** [comment]
I experimented with saturation and luminance a bit and here is a resulting version. That's the darkest I could make the colors while keeping the contrast between the the color of the facial features and the background reasonable. Let me know what you think!

https://user-images.githubusercontent.com/8168506/208323926-87f81012-42ee-4cef-8782-7598d5932b9a.mov

<img width="1440" alt="Screenshot 2022-12-18 at 3 00 54 PM" src="https://user-images.githubusercontent.com/8168506/208323927-8316a81c-7bf5-4fa0-96b7-10d7ec4ff5fc.png">
<img width="1440" alt="Screenshot 2022-12-18 at 3 00 47 PM" src="https://user-images.githubusercontent.com/8168506/208323929-056b6d51-2f7d-4c26-aed8-998dd0f8cc94.png">

**Comment by jonfroehlich** [comment]
I think this is great but I'd like to see Severity 1 be more yellow so that there is more visual distinction across the five levels. Let's aim for Severity 1 as yellow, Severity 3 as orange, and Severity 5 as red.

But this is better than having all green I think. Great job!

**Comment by hoominchu** [comment]
That makes sense! I have updated the colors and you can see them here.
Gradient used: https://www.colorhexa.com/f4db48-to-e85f2b.

<img width="1440" alt="Screenshot 2022-12-20 at 10 21 39 AM" src="https://user-images.githubusercontent.com/8168506/208739220-6ae0fa2f-1af5-4d0e-bf83-88444da2fc7c.png">


https://user-images.githubusercontent.com/8168506/208739296-95343dff-c0ad-4a6a-b034-15014b3e8020.mov

**Comment by jonfroehlich** [comment]
This is perfect. Wow! Let's ship it!

**Comment by hoominchu** [comment]
Great! We need to decide one more thing. Which one of these do you think works better for the explore page context menu?

The hover color is constantly light yellow in this one.
https://user-images.githubusercontent.com/8168506/208760676-bbe1441b-19c3-4d57-8b1b-f3ed23317cfe.mov


Hover color matches the selected color in this one.
https://user-images.githubusercontent.com/8168506/208760774-238df1cd-b5f8-4955-bfd1-8d2f294dcdba.mov

**Comment by jonfroehlich** [comment]
I can’t get videos to load but I’m mobile. I would prefer second option (though saying that without seeing videos)

Generally your hover color is slightly different but visually distinct from selected fill color. I typically do this by playing with opacity.

**Comment by hoominchu** [comment]
Sounds good. Here is how it looks with the opacity adjustments.


https://user-images.githubusercontent.com/8168506/208768736-86b657b4-e4db-4435-a73a-d52d04803327.mov

**Comment by jonfroehlich** [comment]
Thanks @hoominchu!
