### ISSUE TITLE
Sidewalk Gallery: Filter circles are too large

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2648]
The filter circles on the left sidebar look disproportionately large compared to the rest of the sidebar elements.

It looks like the width of each circle is 40px. It should be more like 30px.

## Old
Here's 40px (what it currently is):

```
.gallery-severity {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 50px;
}

.gallery-severity-image {
    cursor: pointer;
    background-color: white;
    width: 40px;
}
```

![image](https://user-images.githubusercontent.com/1621749/128018921-1d32f9cf-739c-4e29-98c8-426b4894a22a.png)

## Suggested fix
Here's new suggested code with 40px for `gallery-severity` and 30px for `gallery-severity-image`:

![image](https://user-images.githubusercontent.com/1621749/128018863-98028306-6d16-456b-93af-20fe20515ee5.png)

```
.gallery-severity {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 40px;
}

.gallery-severity-image {
    cursor: pointer;
    background-color: white;
    width: 30px;
}
```

**Comment by misaugstad** [comment]
Can do! Thanks for just going in and messing with the CSS yourself to make this trivially easy for me :)

**Comment by jonfroehlich** [comment]
I'm a hax0r at heart!
