### ISSUE TITLE
Sidewalk Gallery: need tool tips over severity circles

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2650]
When you mouse over the severity circles, there should be a tooltip that pops up and explains: "least severe" ... "most severe" using the same language as the audit interface.

![image](https://user-images.githubusercontent.com/1621749/128019937-9a15fde7-95da-47e0-b04e-4893d9968694.png)

**Comment by misaugstad** [comment]
closing via #2656
