### ISSUE TITLE
Add fields Total Distance Audited and Time Spent in the Interface in User Table in admin interface

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#266]
How about total miles/km audited and total time spent in the interface? Again, could be a nice, easy task for @manaswis to gain some understanding of database, writing queries, and building out the admin interface more.

![image](https://cloud.githubusercontent.com/assets/1621749/18029576/a3c0c02c-6c69-11e6-9994-59ce80b14fc1.png)

**Comment by kotarohara** [comment]
Total miles/km, I agree. Total time on in the labeling interface is not always useful. For example I keep the window open and that counts as time present in the interface.

**Comment by jonfroehlich** [comment]
Well, let's just add time and see if it is a useful metric.

We could also refine the Time Spent metric in the future to be have a 'timeout' -- that is substract all time after a certain threshold of no interaction.

**Comment by jonfroehlich** [comment]
We could possibly also add number of steps--where a step is one move forward or backward in the interface.

It would be really nice to get a sense of miles walked/user since this is the metric we highlight on the frontpage. It's hard to know how distributed it is.

**Comment by misaugstad** [comment]
Time spent auditing requires looking at the `audit_task_interaction` table, which takes too much time to be used on the full user table. We could consider including it on the admin user dashboard (`/admin/user/<user_id>`) which is also where we have distance audited!
