### ISSUE TITLE
Release more neighborhoods in Azcapotzalco?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2665]
I received this note from @gari01234 today:

> We are going to start collaborating with the ITESM university to continue mapping CDMX. They are interested in mapping Azcapotzalco at first. Can you enable all the polygons of Azcapotzalco?

@misaugstad, how hard would this be?

I see Azcapotzalco is at about 37% right now

![image](https://user-images.githubusercontent.com/1621749/129205850-9ef95cd9-23be-4ace-824b-b472891527c4.png)

![image](https://user-images.githubusercontent.com/1621749/129205913-31a6352c-6641-48f0-b034-0d5033d7d12a.png)

**Comment by misaugstad** [comment]
Done!
