### ISSUE TITLE
Consider adding Cities to dropdown?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2678]
![image](https://user-images.githubusercontent.com/1621749/132075879-676a6ac3-3d74-461e-8d14-bf9c53f515b4.png)

Just like Data, we have could Cities with a dropdown selection for the various cities.

**Comment by misaugstad** [comment]
Love it! How would you feel about decreasing the size of the navbar in all dimensions a little bit? Like bringing the font down by one size, decreasing the horizontal and vertical whitespace accordingly, which would probably slightly decrease the height of the navbar.

The buttons just seem pretty large to me with a lot of whitespace, and we continually have issues of wanting to add more buttons and then the navbar getting too crowded :upside_down_face:

**Comment by jonfroehlich** [comment]
Sure. Worth a try at least.

**Comment by jonfroehlich** [comment]
Might be nice to also have a frontpage module that allows you to select different cities like this. Perhaps you could mouse over the pins and get info on the city and data collected thus far and could select it to audit (which would bring you to audit page rather than landing page of that city or something)

![image](https://user-images.githubusercontent.com/1621749/133615528-5a0b07a7-42ad-40e8-a657-4b8300f505a7.png)

Made with [Google MyMap](https://www.google.com/maps/d/u/0/edit?hl=en&mid=1yy-zQx_oXElkkEpcFrFxaGSb3ETqglMr&ll=32.96102092485025%2C-95.79660414531367&z=5)s (for a talk but useful here too).

**Comment by misaugstad** [comment]
@ishaanp9 when you're adding this, note that we have some code somewhere (I think it's just CSS?) that sets the width of the browser at which we switch from the full navbar to a "hamburger menu" style navbar. You'll want to adjust this value by an appropriate amount given the new item in the navbar.

**Comment by jonfroehlich** [comment]
Let's get this done for when we ship the new UI and launch Amsterdam. It's pretty important that we make it easier to choose cities.

Should also consider just showing a random list of 3-5 cities on the landing page under the button (to ensure that list doesn't get too long)

![image](https://user-images.githubusercontent.com/1621749/149022506-636da26b-78d5-46d4-b99e-dfc786a3eff2.png)

**Comment by misaugstad** [comment]
>Should also consider just showing a random list of 3-5 cities on the landing page under the button (to ensure that list doesn't get too long)

That's fair. Added a screenshot below where it splits onto 2 lines. @ishaanp9 this should be pretty easy to implement right in `app/views/index.scala.html`. It will be easiest to test if you set your `city-id` to "pittsburgh-pa" in your `docker-compose.yml` file. The reason is that we are only trying to show 5 of the cities right now, so if you pick one of the 5 we're trying to show, then it only shows the 4 _other_ cities. Since we are not showing Pittsburgh on the landing page, all 5 cities are shown on the landing page for Pittsburgh.

![Screenshot from 2022-01-14 18-12-48](https://user-images.githubusercontent.com/6518824/149605098-38ea63d3-ff04-4c3e-a158-7d375c4c5e64.png)

**Comment by jonfroehlich** [comment]
I think it's important that this gets released with our new UI push as we will have two more cities added: Pittsburgh and Amsterdam. It seems like a relatively straight forward addition. Add in Cities as a top-level menu header with an alphabetized list of cities (or maybe also categorized by country?).

**Comment by misaugstad** [comment]
@sidlak-c137 in the interest of time, I am going to work on this task this week. Your additions to the config files are going to be really helpful for this! I just know how much fiddling is going to need to be done with the navbar, so I want to make sure to get my hands on it ASAP.
