### ISSUE TITLE
Redesign labeling icons?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2684]
We are likely to add crosswalk and possibly even pedestrian signal label types. We'd need to generate icons for these buttons. In doing so, this may give us an opportunity to redesign *all* of our label types and color schemes. This may be possible because of talented folks like @isavin12 that we've added to our team.

![image](https://user-images.githubusercontent.com/1621749/135718620-817282a0-2fcd-40b5-9e91-10fd2be7e4c4.png)

![image](https://user-images.githubusercontent.com/1621749/135718612-c9c402ce-4829-4337-bcdb-d1fcf60e11cd.png)

**Comment by Luciozzz** [comment]
I've worked on a new set of icon designs and here they are:
![image](https://user-images.githubusercontent.com/18668038/139961786-67811ab3-dea1-43ad-9573-cc67c7682b98.png)
This is a mockup with a more spacious button layout and new button shapes:
![image](https://user-images.githubusercontent.com/18668038/139961868-695f767c-4afe-429c-a785-bdd3b5eac137.png)
Would love even more feedback! @jonfroehlich @isavin12 Once we've OK'ed the design, I'll go ahead and apply them to the labels, the popup labeling window, and the mission start screen (shown below):
![image](https://user-images.githubusercontent.com/18668038/139962334-97280276-264d-45d9-929c-3f80045e3842.png)
![image](https://user-images.githubusercontent.com/18668038/139962201-4393fde1-8529-4eef-a2cd-7711b36addf0.png)

**Comment by jonfroehlich** [comment]
Wow, what great progress @Luciozzz. I think this new set is cleaner and each icon is more distinguishable from others in the set!

A few comments.

1. I think the "No Sidewalk" icon could again include the wheelchair user as you had before. So, something like the following but without the pedestrian light:
![image](https://user-images.githubusercontent.com/1621749/139963051-dd2d4c17-b194-411b-8fdc-9d15d5ae9a02.png)

2. I wonder if there is a way we could make the obstacle icon clear that it's not just about labeling fire hydrants or poles but labeling those things when they impede someone with a wheelchair (e.g., no space on sidewalk to go around). This relates to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2685.

3. I think we should try to make an ADA compliant ramp for the "curb ramp" icon. My concern is that the current icon doesn't really look like a modern curb ramp, just a "slant" down. To do this, you might need a slightly different view perspective that allows you to see the ramp.

Here are some pictures of ADA-compliant ramps:

![image](https://user-images.githubusercontent.com/1621749/139963192-f717fb93-1fda-4c66-87b2-3ac4bc60318f.png)

[Source](https://www.sehinc.com/news/ada-transition-plans-may-be-required-receive-federal-funding-transportation-projects)

And sketches and more info that you could use as design inspiration:

![image](https://user-images.githubusercontent.com/1621749/139963286-98720c40-81b4-4a5e-bd92-e2a4d274b1b2.png)

[Source](https://www.ada.gov/pcatoolkit/chap6toolkit.htm)

![image](https://user-images.githubusercontent.com/1621749/139963359-cd4c6f1b-394a-4291-bda8-2a0685444e0c.png)

[Source](https://dot.ca.gov/-/media/dot-media/programs/civil-rights/documents/permanent-pedestrian-facilities-ada-compliance-handbook-a11y.pdf)

See also:
- https://www.roads.maryland.gov/ohd/adafinal.pdf
- https://www.dot.state.pa.us/public/Bureaus/design/ADA/PocketGuide.pdf
- https://www.access-board.gov/ada/guides/chapter-4-ramps-and-curb-ramps/

**Comment by misaugstad** [comment]
I came here to say basically the same things as @jonfroehlich which is a good sign 😉 
1. We should probably make the ramp appear ADA accessible if possible
2. The surface problem icon is really just not clear to me. A cracked sidewalk might be relatively simple while getting the point across?
3. For the no sidewalk icon... I don't love it. I don't hate it. I'm not sure that I would want the wheelchair user added to the icon 😂 I might like it enough as-is
4. Jon makes a good point about it being too easy for someone to fall into just thinking about obstacles and poles / fire hydrants. Maybe there is a type of obstacle that we could put that isn't just your standard pole or fire hydrant that would get ppl thinking about what it means for there to be an obstacle, without needing to make the icon too noisy? My first thought is a parked bicycle on the sidewalk, but that's a noisy object to add on it's own!

**Comment by isavin12** [comment]
@Luciozzz great work! It's a step in the right direction. Could we possibly try a hyper-simplified version of these label types? I still feel like these are a little too detailed. 

Could we also see what they look like without color? Just thinking back to Jon's comments about how the color starts to lose meaning once we have more than like 3. I've been looking at Google's icons for MEET and MAPS for inspiration:

![image](https://user-images.githubusercontent.com/56325998/140015173-7ad0a6af-9975-4aae-9148-641309f25236.png)
![image](https://user-images.githubusercontent.com/56325998/140015215-1d796804-4742-4f52-a45f-fb6f3e374cc6.png)

**Comment by jonfroehlich** [comment]
In conversations with Barbara Minsker at SMU, she suggested using the language: "Curb Ramp Needed" rather than "Curb Ramp Missing" (and, similarly, "Pedestrian Signal Needed" and "Crosswalk Needed"). I like this language because it signals to users that they are, in some ways, voting a preference and acting a bit like community urban planners.

Additionally, a key challenge with bringing in more labeling buttons is the complexity of the task. I was thinking that perhaps there is a UX way of solving this that would also let us have both the "Needed" buttons for curb ramps, pedestrian signals, and crosswalks. So, in total, we would have:

1. Curb Ramp
2. Curb Ramp Needed
3. Crosswalk
4. Crosswalk Needed
5. Pedestrian Signal
6. Pedestrian Signal Needed
7. Surface Problem
8. Obstacle in Path
9. Sidewalk Needed
10. Other

There might be a few ways of reducing these. For example, we make "Curb Ramp" and "Curb Ramp Needed" one button or icon and when you mouse over it, it animates into two buttons where you can make your selection. Alternatively, you click on the "Curb Ramp" button and when you drop it in place, the first thing you select is whether it's missing or there. In either case, we would have:

1. Curb Ramp + Curb Ramp Needed (as one button)
2. Crosswalk + Crosswalk Needed (as one button)
3. Pedestrian Signal + Pedestrian Signal Needed (as one button)
4. Sidewalk Problem (and could animate out to 'Surface Problem' or 'Obstacle in Path')
5. Sidewalk Needed
6. Other

Thoughts?

**Comment by Luciozzz** [comment]
I like the new naming pattern. I think it's clearer and also easier for us to develop icons. The current newest version of icon design is down below:
<img width="646" alt="square" src="https://user-images.githubusercontent.com/18668038/141514019-3e28f9ba-74f9-408c-b680-14352aea4343.png">
And here is a mockup:
![image](https://user-images.githubusercontent.com/18668038/141514639-3a0d73d2-752f-4b7d-95ab-caa37b5caa49.png)

**Comment by Luciozzz** [comment]
Also, I think it's helpful to reduce the number of icons by doing this:
![hover](https://user-images.githubusercontent.com/18668038/141518402-2dbebf41-c950-48d6-a296-9e4ca45ec2a3.gif)

Will think about the new naming and have a mockup ready soon.

**Comment by jonfroehlich** [comment]
Yes! This (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2684#issuecomment-967334923) is what I was thinking about... though we might have to implement this slightly differently to:
- Use a different primary icon that indicates it might expand into curb ramp / curb ramp needed (as now, you double up on the 'curb ramp' label for both the unexpanded icon and then reuse it for the 'curb ramp' icon
- Minimize screen real-estate. Your idea will use lots of vertical space (essentially doubles the vertical need of button length due to where the pop-ups are placed)

**Comment by jonfroehlich** [comment]
I was thinking about this more this morning and I'm still wrestling with people's ability to discern when a crosswalk or pedestrian signal is needed. I could see folks reliably marking their existence (when they exist) but being able to think through when a crosswalk or signal is needed, or not, feels like a transit planning task that is more advanced than what we currently ask of folks in Project Sidewalk. 

I think that some of our users—who are particularly diligent or skilled or come from a background in urban planning or walkability audits—could do this without a problem but could the "general" user?

**Comment by misaugstad** [comment]
>I think that some of our users—who are particularly diligent or skilled or come from a background in urban planning or walkability audits—could do this without a problem but could the "general" user?

That is really my main concern here. Given the mistakes being made with the more simple label types and our discussions about more training for those, I don't see how your average user would have the knowledge to label the absence of signals without dedicated training.

**Comment by jonfroehlich** [comment]
Yah, I was thinking that we could keep "Missing Curb Ramp" (or rename it to "Curb Ramp Needed") but for pedestrian signal and crosswalk, perhaps we return to only labeling the existence of those and not asking our users to provide judgments about where they are necessary (if they don't exist).

**Comment by Luciozzz** [comment]
> I was thinking that we could keep "Missing Curb Ramp" (or rename it to "Curb Ramp Needed") but for pedestrian signal and crosswalk, perhaps we return to only labeling the existence of those and not asking our users to provide judgments about where they are necessary (if they don't exist).

Returning to only labeling the existence would reduce the total number of icons to 8: 
![image](https://user-images.githubusercontent.com/18668038/142485877-07bbf426-a537-4605-b276-2ae30f7da382.png)

If we only have 8 icons in total, I'd suggest we cancel the hover interaction (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2684#issuecomment-967334923) and put those 8 icons straight out to get rid of additional steps. Instead, we could group them with tags, e.g. something like this: 
![image](https://user-images.githubusercontent.com/18668038/142495768-53af724c-322a-418d-8be4-a13ab047a443.png)
I moved the zoom in/out to the left to save some space at the top. I've also adjusted the icon colors and provided several versions.

**Comment by jonfroehlich** [comment]
Hi @Luciozzz. I agree!

What's the difference between #1 and #2 above and #3 and #4 above?

I quite like the circular buttons: they feel nice and clean. Will people know they are clickable?

I think the "Curb Ramp Needed" icon still needs work. The newest icon makes it seem like the curb ramp is **not** needed rather than it's missing. 
![image](https://user-images.githubusercontent.com/1621749/142498530-addbfa01-a61f-4efb-a411-2a4c6f8c0d1c.png)

Maybe you need to go back to something like the following but using an arrow to point out the lack of ramp?
![image](https://user-images.githubusercontent.com/1621749/142498720-3be0b427-d852-4e20-8bbb-a07676cc0b96.png)

Also, we need to see what these look like when placed on an image. Before, we changed the outline and fill colors. It looks like from your one example that we'd only use outline color (and keep fill color as white or gray)?
![image](https://user-images.githubusercontent.com/1621749/142498895-e9017506-d14d-4f1e-b8cf-75e6df2d0f2a.png)

**Comment by misaugstad** [comment]
@jonfroehlich are we planning on keeping the "can't see sidewalk" label type? If so, we'd need a new icon for that as well and would need to decide where that icon will go.

**Comment by jonfroehlich** [comment]
Yes, I think that continues to be important, don't you?

**Comment by misaugstad** [comment]
Yeah I just wasn't sure because that label type hasn't been mentioned at all yet. It also theoretically has a good use (showing where a physical audit would be useful), but we haven't really done anything with that label type yet.

**Comment by Luciozzz** [comment]
I came up with some new designs for curb ramps and other. Here is a comparison between the old ones and the new ones:
![image](https://user-images.githubusercontent.com/18668038/144307201-f92cba93-0206-4614-af30-9eb65a6c3bce.png)

**Comment by Luciozzz** [comment]
About the "other" icon - I think it's actually helpful to use a simple version (the + sign or ... sign). I understand it's gonna look great if we can come up with a general graphic that can represent the "other" category in context; however, the reality is it doesn’t matter because our users will decide. All we need to do is to create a symbol, label it so that our users can proceed to recognize and use the symbol. It will then become popularized in the system.

**Comment by Luciozzz** [comment]
The same thing goes to the obstacle icon - I'm afraid that if we use a pole in the middle of the street, users will perhaps mis-mark pedestrian signal poles and road signs. Using something that can represent a general idea and is not misleading could be better (like the rock).

**Comment by yeisenberg** [comment]
Neat stuff! i like 1 for curb ramp, and missing curb ramp and then the 3 dots for other. For the curb ramp ones, i wonder if they could look more like a corner? the part on the left looks like a mid-block crossing. Like if you made the bottom left part as more of a corner?  Great stuff! Yochai

**Comment by yeisenberg** [comment]
I found the Rock a bit hard to understand/immediately get. What do you think about a fire hydrant? or if its a pole, someone indicating a narrower width?

**Comment by Luciozzz** [comment]
Here are some modifications: 
![image](https://user-images.githubusercontent.com/18668038/144329120-35d9923f-480e-4db0-9e6f-a55d82be12b0.png)

About the "obstacle" icon - the current one that we are using right now is the fire hydrant, but we talked about that and thought users would probably label fire hydrants only and ignore other ones. That's why I came up with a more general rock icon. I made a pole icon with arrows for us to compare, but I still think rocks are better.
![image](https://user-images.githubusercontent.com/18668038/144331359-2feed926-464e-49b2-ab87-d0bb291288dd.png)

**Comment by jonfroehlich** [comment]
Wow, great work @Luciozzz. 

1. Could you try a curb ramp design where the corner is even more salient? Maybe placing the curb ramp on the corner itself?
![image](https://user-images.githubusercontent.com/1621749/144332776-99b27905-2a04-4b9c-b081-b44ec814fbb4.png)

2. Thanks for making those other obstacle in path icons. I think of all of them you've come up with, I prefer the fire hydrant but I also wonder if there is a way to indicate that the there is no room to go around the hydrant, sort of like you have with 
![image](https://user-images.githubusercontent.com/1621749/144332853-37cd6d8c-49fb-45a3-b6ff-9103b3f1cbb1.png)

3. I think this "missing curb ramp" design is *SUPER* creative (nice job!) but I wonder how well it scales down given the nuance of the dotted lines (and whether it would be easily understood). 
![image](https://user-images.githubusercontent.com/1621749/144332931-979b801e-41b1-40bf-837e-21415dc1eab7.png)

Thus, I probably like this one best (but I'd like to see it with a corner): 
![image](https://user-images.githubusercontent.com/1621749/144332959-614c6d37-605b-44ef-84d7-a8326e1791fd.png)

**Comment by Luciozzz** [comment]
After all the iterations, here is the latest version of the icons:
![image](https://user-images.githubusercontent.com/18668038/145615556-dce9a9b6-ab99-4666-a97c-efde3e063c38.png)

Here is a mockup of the current mission screen with the new icons:
![image](https://user-images.githubusercontent.com/18668038/145615640-82683d5a-14e2-4833-b0b5-a778a8951cac.png)

And here is a mockup of the redesigned mission screen with the new icons:
![image](https://user-images.githubusercontent.com/18668038/145615805-560a6293-e14d-4e87-bae3-4e452010445d.png)

**Comment by jonfroehlich** [comment]
This is amazing. Way to go @Luciozzz!

In our PS meeting, we talked about:

1. Making sure that placed labels are small (if possible, making them the same size as we currently have). To enable this, maybe custom make smaller versions of the icons (e.g., the small version of "Obstacle in Path" is just the fire hydrant, "Surface Problem" is just a crack, etc.)

2. Whether or not we can and should push a full UI redesign at this point or just add in the labeling icon top bar (for now) and continue working on the UI redesign in a separate ticket.

**Comment by jonfroehlich** [comment]
@misaugstad, you and I need to talk about implementation timeline on this as we Amsterdam is expecting this by the end of January (so you might have to do some frontend work!) :)

**Comment by misaugstad** [comment]
Since I'll be out for at least a week in January, I should start working on this next week. I'll start working towards the mock that uses our current interface with just the new icons for now.

How close are we to having the icons finalized with the correct size and everything? I can start working on this without the final design for the icons, but I'll need them somewhat soon I'd think.

**Comment by jonfroehlich** [comment]
> Since I'll be out for at least a week in January, I should start working on this next week. I'll start working towards the mock that uses our current interface with just the new icons for now.

Was thinking the same thing.

> How close are we to having the icons finalized with the correct size and everything? I can start working on this without the final design for the icons, but I'll need them somewhat soon I'd think.

You should coordinate with @Luciozzz directly on this. We should get all icon related design work committed to the Design repo as well: https://github.com/ProjectSidewalk/Design

**Comment by misaugstad** [comment]
@Luciozzz sorry that we missed this earlier, but we also need to work on the design of the subcategory menu when someone clicks on the "other" section. Right now it brings up a dropdown with the "other" and "can't see the sidewalk" label types, shown below. Which also reveals that we need a "can't see the sidewalk" icon!

![Screenshot from 2022-01-31 15-25-10](https://user-images.githubusercontent.com/6518824/151889664-50fc192a-abd1-4e4e-83c5-32f86ae0bc9c.png)

@Luciozzz if you don't have time to work on this design (this week or at all), just let us know!
