### ISSUE TITLE
Real-time priority routing to re-audit street segments audited by low-quality users

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2698]
With some of the labeling inaccuracies we've seen in the Chicago pilot, we need to update our routing priority algorithm—that is, re-auditing streets audited by low-quality users (see leaderboard screenshot below). @misaugstad and I've talked about this ad nauseum but I could not find a good existing ticket for it.

Currently we allocate re-audits based on a rough heuristic formula that accounts for labeling frequency (e.g., minimum num of labels over X meters). But I think we can do much better.

At a minimum, our route assignment algorithm needs to take into account "poorly" audited streets—the most straightforward way of doing this is simply to re-audit any street that was audited by a low-accuracy user (as calculated by validations). We could also use some of the other heuristics we've used in the past for classifying 'good' vs. 'bad' labelers.

![image](https://user-images.githubusercontent.com/1621749/138346788-7d31d776-28d9-44f0-80b1-c40dab52298e.png)

**Comment by jonfroehlich** [comment]
Great discussion @misaugstad!

I tend towards "Below labeling frequency threshold OR accuracy below 60%"

If you send me some `.csv` files with columns for user, labeling frequency, and accuracy, I'd be happy to do some analysis to see how different "low quality" metrics might affect re-audits.

**Comment by jonfroehlich** [comment]
There is also the notion of poor quality users as well as "poor quality" audited street segments (that is, prioritizing re-audits for street segments with label data that has negative validations). This relates to: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2508

**Comment by jonfroehlich** [comment]
This is also related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2108

**Comment by misaugstad** [comment]
Took a quick look at the data... Out of the total number of users with 50 or more labels validated (of which there are 462), here are the fraction of users who are below various possible accuracy thresholds.

40%: 0.4% (2 users)
50%: 1.9% (9 users)
60%: 3.5% (16 users)
70%: 8.4% (39 users)
80%: 25.8% (119 users)

Given those results, I feel pretty happy with the suggested 60% threshold. Filtering out data from the bottom ~5% of users feels reasonable to me. I'd be down to move it up to 65% too :)

**Comment by jonfroehlich** [comment]
Thanks for this analysis. Did this calculation include the labeling heuristic as well of 3.75 labels per 100 meters, since that's the full formula we are using as described in your PR (https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2724)
