### ISSUE TITLE
Add validation info to API

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2699]
While related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1668, this feature request is different: it would be good to include validation information in our API (at least for the `Access Attributes` API and maybe for the `Streets` version too--harder for neighborhood because it's so much to aggregate).

Given that our API serves aggregations rather than raw labels—even 'Access Attributes' serves clusters, we need a way of providing validation info. IMO, we simply provide the sum of `agrees`, `disagrees`, and `unsures` for that cluster.

Notably: Lisa needs this info for some of our work together, so would be good to get this into the next release.

**Comment by misaugstad** [comment]
I think that I'm going to refrain from adding validation to the streets API. It's unclear to me how someone should interpret the sum of the validation counts there. I think that the only thing it could tell you is that you shouldn't have confidence in the accessibility score for a street that has labels with a lot of downvotes... But we should just be refraining from including labels with a bunch of downvotes in the API in the first place, so I don't see the use of including the validation counts for a street.
