### ISSUE TITLE
We need more options for "Jump"

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#27]
Jon's comment: Actually, neither of these options apply. We need a third option: “I cannot go the direction that you want me to walk…” (or something like that) Perhaps we also add in a write-in blank here…. So a 4th option

![jumpoptions](https://cloud.githubusercontent.com/assets/612263/13297356/f3cfe8fa-daff-11e5-89fa-16d4517023cb.png)

**Comment by nguyenist** [comment]
@kotarohara I didn't even know this feature existed! How do you "jump"?

**Comment by kotarohara** [comment]
Doesn't selecting the option and clicking ok takes you somewhere else?

**Comment by nguyenist** [comment]
Oh I mean -- what do you click to get that window to pop up with the options in the first place? Is it the "explore" button?

**Comment by kotarohara** [comment]
Ohhhhh! I see :) There is a button on the left. You see the "Jump" button under the "Sound" and above "Feedback"?

**Comment by kotarohara** [comment]
Changed the language. I'm closing this.

**Comment by jonfroehlich** [comment]
What's the new language? What are the new options? Can you show me a screenshot?
