### ISSUE TITLE
Add image date, labeling dates, and validation info to API

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2729]
From our Chicago partners meeting--with Regional Transportation Authority (RTA), Chicago Metropolitan Agency for Planning (CMAP), and  Metropolitan Planning Council--they asked us to include in our API, for each label/cluster:
- Image date
- Label date
- Validation info

We already have a ticket for validation info [here](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1668) but need to add in other parts. Given that we serve clusters in our API, we'll need a way to include this information.

My feeling is that for each cluster, we include the list of labels that compose that cluster and then include relevant metadata.

To make it so you only need to analyze the cluster, we could have cluster-level details like: `agree_validation_count`, `disagree_validation_count`, `unsure_validation_count`--which sum the underlying cluster data as well as things like `average_image_age`, `average_label_date_age`

**Comment by misaugstad** [comment]
In the comment above, we are linked to #1668 which deals with being able to query for only validated labels. The issue for simply adding validation info to the API is #2699.
