### ISSUE TITLE
Should probably only show Team Leaderboard if there is something to show

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2733]
Screenshot from Seattle site:

![image](https://user-images.githubusercontent.com/1621749/142664748-0bf2e7e3-4963-4ebc-9e29-4a36c03d34a0.png)

**Comment by misaugstad** [comment]
My only counter to that is that showing a blank teams leaderboard indicates to people that they _could_ be on a team that is on the teams leaderboard... So in some ways this feels like our best advertisement of teams right now on the site. It could be done better of course :)

**Comment by jonfroehlich** [comment]
Agree with your counterpoint but also since you can't yet sign up yourself for a team... I think it just adds clutter. But small issue, I suppose.

**Comment by ArjunNarendra** [comment]
Screenshot from San Pedro Garza García, MX before fix:
<img width="1264" alt="Team_Leaderboard_Before" src="https://user-images.githubusercontent.com/29639493/145118133-efdf17ae-de52-4759-8450-044696284182.png">
Screenshot from San Pedro Garza García, MX after fix:
<img width="1268" alt="Team_Leaderboard_After" src="https://user-images.githubusercontent.com/29639493/145118170-b28927be-de1f-443e-a72d-8e75034b9b66.png">
