### ISSUE TITLE
Share a specific label type, filter selection, etc. in Sidewalk Gallery

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2746]
I want to be able to share links like "here are all the garbage can labels in Seattle" or "here are all surface problem labels with severity 5"

Probably easiest (best?) to implement this with a [query string](https://en.wikipedia.org/wiki/Query_string). So:

`https://sidewalk-sea.cs.washington.edu/gallery?label_type=obstacle&tags=trash`

and

`https://sidewalk-sea.cs.washington.edu/gallery?label_type=surface_problem&severity=5`

Would be nice for things like this [Tweet](https://twitter.com/projsidewalk/status/1471989942591000581?s=20):
![image](https://user-images.githubusercontent.com/1621749/146620287-cbe0d43e-278e-42c5-9d20-95a2911293a3.png)

Also relates to: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2405

**Comment by jonfroehlich** [comment]
Coming back here to say that I think this is really quite important.

**Comment by misaugstad** [comment]
Once @sidlak-c137 has finished #2633, the back-end work related to building the URL will be finished. So we would be able to share the query string after #2633 is finished. The last piece would just be adding it somewhere in the UI. Maybe it could be as simple as a typical "share" icon next to the word "Show" in the sidebar (with a tooltip explaining what you're sharing).

**Comment by misaugstad** [comment]
Just a reminder for us for the future: @sidlak-c137 got part of this working. When changing cities, the label type is retained, but the severity and tags are not. The reason for this was that the severity and tags are added to the page dynamically, whereas the initial call to load the webpage already included a parameter for the label type. It will take a heavier lift of modifying JavaScript code to accommodate setting the severity and tag info in the initial page load.
