### ISSUE TITLE
Need to mark Sierra and Amy as researchers

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2749]
Need to mark Sierra (sberqu2) and Amy (hofstraa) as researchers in Chicago

**Comment by misaugstad** [comment]
Can do! But a reminder that you can do that on the admin interface as well. Not sure if you were just recording this as a TODO or if you thought that I needed to run a query on the database to do it.

**Comment by misaugstad** [comment]
Done!

**Comment by jonfroehlich** [comment]
Oops, yes, I thought we had to do that on the SQL backend... thanks!
