### ISSUE TITLE
Jumped within neighborhood right before new mission starts

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#275]
This might be confusing for the user if (s)he finds this message immediately after (s)he gets his/her new task, which is what happened with me:

<img width="1280" alt="screen shot 2016-08-31 at 1 41 50 am" src="https://cloud.githubusercontent.com/assets/2873216/18117371/4b406154-6f1c-11e6-823d-6fbf5ae1be92.png">

**Comment by jonfroehlich** [comment]
This has happened to me before, though infrequently.

Thanks for reporting it!
