### ISSUE TITLE
Add logos for Amsterdam

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2752]
##### Brief description of problem/feature
I think we'll want to add logos for the City of Amsterdam, Amsterdam Intelligence, and World Enabled to our site. Not sure if these are all going in the Collaborators section or if we are finding a new solution given the number of logos we are starting to rack up ;)

Here are the City of Amsterdam and Amsterdam Intelligence logos. We're just waiting on the World Enabled one.

City of Amsterdam
![GASD_E_sponsor_pms](https://user-images.githubusercontent.com/6518824/147298569-ebd8df27-9791-4169-8ae6-afe6f0187f7e.png)

Amsterdam Intelligence
![ai logo_white](https://user-images.githubusercontent.com/6518824/147298571-70b87bfa-12f3-4469-a671-c9e4a83c3ae4.png)

**Comment by jonfroehlich** [comment]
Here are two World Enabled logos I have:

Full color (but lower res):

![image](https://user-images.githubusercontent.com/1621749/147694210-4e56355e-b93d-4599-bfdb-16ee23256e7c.png)

From https://worldenabled.org/

Blue monochrome:
![image](https://user-images.githubusercontent.com/1621749/147694262-0e3406c4-a539-4475-9b18-e36ab5d4938b.png)

From: https://www.guidestar.org/profile/51-0538978

**Comment by jonfroehlich** [comment]
OK, Victor got back to us. They prefer that we use the color one. So, we're good to push forward on this now!

**Comment by misaugstad** [comment]
@jonfroehlich should these 3 logos be present in every city (like Liga Peatonal) or just in Amsterdam (like OpenColumbus)? And should we start by just adding the logos to the Collaborators list and make all the logos a bit smaller to see how it looks?

**Comment by jonfroehlich** [comment]
World Enabled and Amsterdam logos should only be on the Amsterdam page (for now).

But I could also imagine having a Collaborators/Partners list, as you suggest, with all collaborators listed (and logos from OpenColumbus, Liga, Amsterdam, etc.)

We should also add in the CREATE logo as they've now provided matching funds for our work.
