### ISSUE TITLE
Stuck inside a building in Amsterdam?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2765]
According to @maartensukel, when they were testing the newly launched Amsterdam site, they got stuck inside a building. And they couldn't determine how to get out (e.g., to hit the 'Stuck' button).

This might be related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/668

**Comment by misaugstad** [comment]
Hopefully we can get another example of this happening where we can get some more info. I tried to look through some logs (rewatched the few audits that have been done) and wasn't able to find anything. This also is an argument for #1579! We should be able to prompt ppl who seem like they might be stuck somewhere to press the stuck button.

**Comment by misaugstad** [comment]
The same issue is documented in #3065 with some more information than we have in this ticket.
