### ISSUE TITLE
Oradell, NJ boundary data

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2779]
I found this [Bergen County ArcGIS parcel viewer](http://bcgisweb.co.bergen.nj.us/parcelviewer/) on the [Bergen County, NJ government website](https://www.co.bergen.nj.us/planning-engineering-regional-planning-transportationgeographic-information-system-gis). 

Bergen County is quite large. The blue highlighted city below is Oradell, NJ (Oradell is a "cross-like" shape):

![image](https://user-images.githubusercontent.com/1621749/154984756-b24b5269-b804-40c1-9200-2b75686d8b51.png)

Here's the full county:
![image](https://user-images.githubusercontent.com/1621749/154984939-31d3374a-081d-4bd1-8b75-91382da4cbb8.png)

There is also contact info on the website:
>Geographic Information System (GIS) is widely used in various County departments. Among others, the Department of Planning & Engineering maintain and regularly update a county-wide property parcel layer. The data can be downloaded at the [NJ Geographic Information Network](https://njgin.state.nj.us/NJ_NJGINExplorer/IW.jsp?DLayer=Parcels%20by%20County/Muni) website.  Should you have questions regarding the data, please contact us via phone (201) 336-6446 or email [gis@co.bergen.nj.us.](mailto:gis@co.bergen.nj.us.)

The link above to the NJ Geographic Information Network is broken but I found this: https://njgin.nj.gov/#!/ through which I found [Parcels and MOD-IV of Bergen County (shp file)](https://njogis-newjersey.opendata.arcgis.com/documents/newjersey::parcels-and-mod-iv-of-bergen-county-nj-shp-download/about)

There is a download link on [that page](https://njogis-newjersey.opendata.arcgis.com/documents/newjersey::parcels-and-mod-iv-of-bergen-county-nj-shp-download/about) to download `parcels_shp_dbf_Bergen.zip`, which contains all of the boundary data for Bergen County. I'm hoping @misaugstad can use this to grab Oradell, NJ boundaries and maybe to split Oradell into five parts: North, East, West, South, and Central (but doing such a split is contingent on how big Oradell is).

![image](https://user-images.githubusercontent.com/1621749/154985661-73b5d62b-ee2f-4ba3-97ee-426f48cca2d6.png)

**Comment by jonfroehlich** [comment]
Here's an example split of Oradell into five parts (if we need to do this).

![image](https://user-images.githubusercontent.com/1621749/154989502-bf404acd-c945-4d9c-b9a9-fae701edebcc.png)

**Comment by misaugstad** [comment]
The parcels dataset you linked to doesn't have the simple municipality boundaries, just the parcels of land (pic below). I'm scanning through the open data website now to see if I can just find the municipalities.
![Screenshot from 2022-02-21 16-21-47](https://user-images.githubusercontent.com/6518824/155041641-68091b04-1b4b-49f5-aa9f-009fcc4f740c.png)

**Comment by misaugstad** [comment]
Well I finally figured out how to [add arcgis mapserver layers](https://www.cadlinecommunity.co.uk/hc/en-us/articles/360009761197-QGIS-Adding-ArcGIS-Map-Server-Layers) and then save those features locally :upside_down_face: So I ended up using [this server](https://maps.nj.gov/arcgis/rest/services/Framework/Government_Boundaries/MapServer). We are all set on Oradell boundary data!

**Comment by jonfroehlich** [comment]
Nice, great job @misaugstad!
