### ISSUE TITLE
Now That We Are Public... Need Production and Test Server?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#278]
Now that we've launched publicly (yay!!!), we probably need to follow good web design practice and have a production server and a test server. My concern is that we accidentally checkin code that adds a new feature or fixes a bug, but really introduces a new problem.

Thoughts on this?

**Comment by manaswis** [comment]
Yes, this will definitely be useful. The current way of testing on local is good but testing on production database would be more useful than the stagnant db on our local system.

So the test server should allow us to switch between production db and test server db (for not messing up the actual production data if the feature/bug fix involves inserting new data e.g. fake accounts).

**Comment by manaswis** [comment]
Closing this. We have a dev server now :)

**Comment by jonfroehlich** [comment]
Hahah. That we do.
