### ISSUE TITLE
Admin access to Amsterdam collaborators

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2780]
Maarten and Claudia

**Comment by misaugstad** [comment]
I don't think that either of them have created registered accounts on the site yet. But when they do, either of us can update that through the "User" tab in the admin interface.

**Comment by jonfroehlich** [comment]
@misaugstad, this is now resolved, right?

**Comment by misaugstad** [comment]
I've now done this for the prod servers as well! Resolved.
