### ISSUE TITLE
Clicking on neighborhood hyperlink on auditing sidebar results in `Page not found` bug

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2783]
![image](https://user-images.githubusercontent.com/1621749/155007791-4c79e8cf-b9fd-4d5b-8c3a-6564dddeae3c.png)

To reproduce:
![image](https://user-images.githubusercontent.com/1621749/155007969-bcd3fb88-1e38-4ca2-bf93-db92b31ae0c2.png)

**Comment by misaugstad** [comment]
Note that I'm pretty sure it's supposed to zoom you to the specified neighborhood on your user dashboard!
