### ISSUE TITLE
Why have paint fading and paint not fading for crosswalk tags?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2790]
I think we only need "paint fading." I find it confusing to have both. What are your thoughts @misaugstad? And what was the original reason for having both?

![image](https://user-images.githubusercontent.com/1621749/155544652-353e3ae9-afd1-4a29-81af-5575edd1b356.png)

**Comment by misaugstad** [comment]
It was meant to mirror the "alternate route present" and "alternate route not present" for missing curb ramps. Honestly not 100% sure what the rationale was for either :upside_down_face: Maybe I was anticipating users adding crosswalk labels when there is no paint at all? Not sure. I can move to just "paint fading".

**Comment by jonfroehlich** [comment]
Thanks. I agree to remove `paint not fading` and to keep `paint fading`.
