### ISSUE TITLE
Dev Environment doesn't work on Apple M1 Chips

### ISSUE THREAD

**Issue by rpechuk** [ProjectSidewalk/SidewalkWebpage#2798]
### Brief description of problem/feature
Compiling and other docker related tasks don't work on any new mac computers that have an apple chip. This(to the best of our current knowledge) is a docker issue and the only way to fix it at the moment is either waiting for a docker update that fixes the issue or updating the container (see https://betterprogramming.pub/macbook-m1-breaks-docker-development-14566ab6fa2e#:~:text=Docker%20Is%20Not%20Supported%20on,and%20will%20be%20solved%20soon.).
### System info (OS, browser, city, and local/prod/test)
I'm experiencing this issue on a 14-inch 2021 MacBook Pro with a M1 Pro Apple chip running macOS Monterey.
### Current behavior (add screenshots if applicable; check terminal & browser console for errors)
Example of getting stuck compiling:
![image](https://user-images.githubusercontent.com/39865166/156293836-44847f3f-046d-43ac-8c5f-2a7a13a6d6f1.png)

**Comment by jonfroehlich** [comment]
Ugh, so sad! I'm hoping to get an M2 when they come out but will not do so if we can't get our dev setup working on them...

**Comment by misaugstad** [comment]
@rpechuk I think I remember you getting further than this point at some point since you posted this. How far have you gotten? And were there any fixes you made to get further?

**Comment by jonfroehlich** [comment]
I'm experiencing similar behavior on MacBook Pro M1 as well.
<img width="224" alt="image" src="https://user-images.githubusercontent.com/1621749/187567509-4d526d96-a055-4a94-a628-99c69cf49ddb.png">

Seems to be stuck here after running `npm start`:

```
Done.
Running "watch" task
Waiting...
[info] Loading project definition from /opt/project
```

**Comment by hoominchu** [comment]
I spent some time figuring out the installation issue on M2. Here is a summary of the same. 


Link: https://stackoverflow.com/questions/72273216/error-building-custom-docker-image-with-postgres-and-security-updates-configur
(SUCCESS) When installation was getting stuck at task 5/7. This helped get past this issue. This is a different issue than the one mentioned earlier in the thread.

------------------

Link: https://stackoverflow.com/questions/67684430/apple-siliconm1-11-4-get-a-java-error-jdk16
Some users mentioned having issues with openjdk-8. Although our error is not exactly the same as theirs, I tried changing the jdk version to 11 but didn't help.


After doing the steps above, I tried running npm start and 'sbt' independently (with -debug and -verbose options) to narrow down the scope of error, I noticed strange behavior—the program got stuck at different points each time I ran it. 

A couple of times it reached the following stage (as mentioned in the README)
"[info] Loading project definition from /opt/project"

And one time it reached the following stage (as mentioned in the README)
"[info] Set current project to sidewalk-webpage (in build file:/opt/)"

But never reached the following stage (as mentioned in the README)
"[success] Total time: 78 s, completed Dec 20, 2018 8:06:19 AM"


However, it did say the following some times.
"[info] Done updating."

------------------


Link: https://stackoverflow.com/questions/70765522/docker-amd64-warning-on-apple-m1-computer
Talks about Docker + qemu problem as it's known. Suggests using --platform linux/amd64. Says running Intel based images on Apple Silicon should be regarded as 'best effort' only. 

^ I haven't tried this suggestion yet. Will try it and update here.


------------------

Related discussion:

Link: https://pythonspeed.com/articles/docker-build-problems-mac/
Why docker fails on new macs. This talks specifically about the issues with Python based installations. There are no direct solutions for us but there are general ideas we can explore. (EXPLORE)

**Comment by misaugstad** [comment]
Thank you for documenting all of this!!

**Comment by jonfroehlich** [comment]
OK, it looks like the amazing @hoominchu solved this in branch https://github.com/ProjectSidewalk/SidewalkWebpage/tree/2798-apple-silicon. 

I was able to successfully build and run the code on an Apple M1 Max! 🎉🙌🏽🎊🎈

<img width="881" alt="image" src="https://user-images.githubusercontent.com/1621749/209817267-d9af860a-0083-435f-b1a2-e8f4b3fb4cd8.png">

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/1621749/209817243-79e54ed5-0047-471d-8749-5e3c8f740297.png">
