### ISSUE TITLE
Cannot proceed in the onboarding tutorial after the 3rd corner of the intersection

### ISSUE THREAD

**Issue by mattm401** [ProjectSidewalk/SidewalkWebpage#280]
Last night I was re-doing the tutorial section of Sidewalk and during the third intersection (post-labeling the two intersections as "curb ramps", submitting the severity forms, etc.) the tutorial stopped working; it would not advance past the "label curb ramps" and arrows that were up. I would delete the curb ramps icons and re-apply them in slightly different locations, but no luck getting the tutorial to advance. Seems like a relatively minor issue, however, I refreshed the page and could not repeat the issue; something to keep an eye on if you receive similar reports.

Sorry, no screenshots, but I was using Windows 7 on a Chrome Browser for what it's worth.

**Comment by jonfroehlich** [comment]
Looks like another person experienced this according to feedback left on site. No way to figure out how common this is because it's very likely that only a small percentage would every report an issue:

![image](https://cloud.githubusercontent.com/assets/1621749/18150894/724ba686-6fb8-11e6-9927-3821a460f044.png)

**Comment by jonfroehlich** [comment]
Another one related to the tutorial, though seemingly a different problem:

![image](https://cloud.githubusercontent.com/assets/1621749/18150910/8ba93d28-6fb8-11e6-997d-63e183800881.png)

**Comment by kotarohara** [comment]
I think this is important. The problem is, though, I tried the onboarding multiple times today and haven't succeeded in reproducing the bug for a single time...

**Comment by manaswis** [comment]
I spoke with Lee. He also mentioned the tutorial getting stuck. Also related problem in the tutorial - https://github.com/ProjectSidewalk/SidewalkWebpage/issues/268

Lee's suggestion was that there might be some code in the rendering part that creates an exception and stops the execution. That exception, whatever that is, is infrequent. Hence, doesn't show up every time.

**Comment by kotarohara** [comment]
Ok, fixed. One event listener that was listening to clicking target feature was unintentionally unbinded. Pushed the change to the server.

**Comment by jonfroehlich** [comment]
Sweet! Great find @kotarohara. I wonder why it was working some of the time... thoughts?

**Comment by kotarohara** [comment]
For the event lister to be unbinded, a certain condition had to be met. So if you did not hit that condition you should have been able to go through the onboarding tutorial.
