### ISSUE TITLE
Project Sidewalk Amsterdam *TEST* is showing up in Google

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2806]
As Maarten pointed out via email today:

> I noticed the test website is what shows up on google if you look for project sidewalk amsterdam.
> https://www.google.com/search?q=project+sidewalk+amsterdam
>
> Maybe add no scrape to robots.txt?
> Discovered because a local newspaper used in their online version, asked them to change it.

I verified this myself. It is the top result unfortunately :(

![image](https://user-images.githubusercontent.com/1621749/157448373-ee5bf415-c72b-48e3-a7ee-2b1378cbfe45.png)

We should also examine whether this happens on other city servers.

**Comment by misaugstad** [comment]
We are discussing solutions on [this thread](https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1000#issue-1163930384) for the Makeability Lab website, as we are having the same issue there.

**Comment by misaugstad** [comment]
This seems to be fixed now! Seems as though one of our interventions worked (eventually)!
