### ISSUE TITLE
New label icons need to have white/black outlines?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2807]
I noticed that sometimes it's hard for my eye to find the labeling icons in the validation interface, especially the more muted green for the curb ramp icon.

I then realized that we no longer have black/white outlines around the labeling icons (like we used to with the old labels):

![image](https://user-images.githubusercontent.com/1621749/157517916-50183ad3-f054-4194-9024-a25d7be2ced3.png)

# Old Labels
White outlines:
![image](https://user-images.githubusercontent.com/1621749/157518031-9104e94e-c751-42c2-9ac2-f99ab256af61.png)

Black outlines:
![image](https://user-images.githubusercontent.com/1621749/157518111-c717a7be-a619-49e8-8fc0-dbaec52d1f67.png)

# Suggestion
We could have a two-color outline: black (1 pt) then white (1 pt), which would work across background types (that's how mouse cursor icons work). Alternatively, we could have adaptive outlines based on background image (but this is more complicated and probably not worth the effort).

**Comment by misaugstad** [comment]
@jonfroehlich are you suggesting that we edit the icon images to have those outlines? Or to add them in the JS/CSS? I'm assuming you mean the former, but I just want to be sure before I start messing with them ;)

**Comment by bnelson05** [comment]
Here's what the different line widths I experimented with look like @jonfroehlich :

0.3:
![2807LW0 3](https://user-images.githubusercontent.com/69987726/176959584-2b228502-7f20-4730-b5c5-07167d4e994f.JPG)

0.5:
![2807LW0 5](https://user-images.githubusercontent.com/69987726/176959587-e7a9b189-2080-4669-a5a1-2b5c050ab073.JPG)

0.7:
![2807LW0 7](https://user-images.githubusercontent.com/69987726/176959588-f6297caf-beac-4817-a800-f76c6532c643.JPG)

1:
![2807LW1](https://user-images.githubusercontent.com/69987726/176959591-e1bdbba6-e586-439d-a55a-bdcb8f8b1e86.JPG)

**Comment by misaugstad** [comment]
Let's go with 0.5 for now. I can actually see the contrast without it feeling like it's taking up too much space!

**Comment by jonfroehlich** [comment]
Yah, I like 0.5 too! Thanks team!
