### ISSUE TITLE
Missing arrow to navigate in the street view

### ISSUE THREAD

**Issue by claudiasofiapinhao** [ProjectSidewalk/SidewalkWebpage#2810]
It is happening a lot that we need to go straight ahead to complete a mission and there is no arrow to pursue that path. Is it possible to correct this behaviour? 

![WhatsApp Image 2022-03-10 at 12 23 01](https://user-images.githubusercontent.com/100705238/157655931-1ae19d42-75be-4db3-930e-9aef95bfa8b7.jpeg)

**Comment by jonfroehlich** [comment]
Yes, this is a frequent problem in Amsterdam for some reason. We're not sure why! And thanks so much for submitting this ticket.

However, we have a fix! For now, you can click the "stuck button", which I've highlighted.

![image](https://user-images.githubusercontent.com/1621749/157670443-792c833d-a478-4907-9bd2-6d978297797d.png)

You can also see us talking about other solutions in this thread:
https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2781

I'm gonna close this thread in favor of that one.

**Comment by jonfroehlich** [comment]
Closing in favor of https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2781
