### ISSUE TITLE
Looks like "No Sidewalk" labels are back in primary validation pipeline?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2819]
On the test server in Oradell:

![image](https://user-images.githubusercontent.com/1621749/158839773-7bda4255-857b-4dd6-b80e-d4cba27af487.png)

![image](https://user-images.githubusercontent.com/1621749/158839862-9b239792-0d9f-4ce4-80f3-ce7a9a266a4e.png)

**Comment by misaugstad** [comment]
The No Sidewalk labels are completely excluded from the validation interface, they are simply deprioritized. You only get No Sidewalk validation missions once you've validated all the other labels (well, if you have fewer than 10 labels of any other label type to validate).

You were really just validating my data in Oradell, and about a third of the data are no sidewalk labels. So I guess I'm not surprised that you got to those :)

![mikey-labels](https://user-images.githubusercontent.com/6518824/158914571-3df9dc11-b0ae-4e6f-8b5a-1840579bd0eb.png)
