### ISSUE TITLE
What's the difference between 'en' and 'en-US'?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2823]
![image](https://user-images.githubusercontent.com/1621749/159090615-135df201-0661-4f77-a0a2-8f31b61b4656.png)

**Comment by misaugstad** [comment]
As of right now, it's mostly just the measurement system. So en-US uses miles/feet, and en uses km/meters.

**Comment by jonfroehlich** [comment]
Oh, neat!
