### ISSUE TITLE
Add smooth panning when clicking on navigation messages

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2825]
##### Brief description of problem/feature
When you click on the navigation messages, we will now pan you to the correct direction, or move you forward if you are already facing the right way. @jonfroehlich brought up that the panning to the correct direction is very abrupt, and that it would be best to have a smooth pan.

##### Potential solution(s)
It doesn't look like there is any way to do this automagically using the API, so we'll have to implement it ourselves. We should be able to call setPOV function some number of times at a small increment to make it look smooth.

**Comment by jonfroehlich** [comment]
I just tested this on the Oradell test server and it worked *almost* perfectly but sometimes, unfortunately, didn't work at all. See video. In the following video, I show some positive examples but then a unresponsive example. I click "turn left" and it changes my angle 90 degrees but really I needed more... and then I get "stuck."

https://user-images.githubusercontent.com/1621749/161384817-ec3a5b9b-c14e-4c81-bcdd-dbbeda7b1fe6.mp4
