### ISSUE TITLE
Feedback from Liga Peatonal about La Piedad launch and new Spanish Translations

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2826]
They wrote up a [Google Doc](https://docs.google.com/document/d/1lk2Y-7IMiVnAT-5v1nkDJVMIFWOhcActXnpoC0Gunos/edit#heading=h.fivto3g0070e) with great feedback. Just dumping it here rather than splitting into individual issues for now.

**Comment by misaugstad** [comment]
Adding a list for myself here. I've separated out the other tasks into their respective issues. These are mostly going to be related to the tags. Similar to #2856 for Amsterdam.
NOTE: this list hasn't been finished yet. had to run so I'm posting what I've got so far.

- [ ] Add tag "waterlogged" / "encharcada" for curb ramps -- @jonfroehlich do you think we should add this everywhere?
- [ ] Add tag "manhole without a cover" / "registro sin tapa" to Mexico only
- [ ] Update translation "comercio ambulante" -> "comercio"
- [ ] Update translation "dispareja" -> "dispareja/inclinada"
- [ ] Replace the tooltip image for the points into traffic tag. Aldo sent us a better one :)
    ![points-into-traffic](https://user-images.githubusercontent.com/6518824/163486247-e3a99a63-8167-4188-a1fa-326ab603bbbd.png)

**Comment by jonfroehlich** [comment]
I also just came across a waterlogged curb ramp in Chicago (in Harvey) in case it's useful for the tooltip:
![image](https://user-images.githubusercontent.com/1621749/163578327-af8bcc25-d8e0-47d5-8ef5-d684430db903.png)

![image](https://user-images.githubusercontent.com/1621749/163578412-cb3e49af-44ac-4ea3-b06e-b546bb532a70.png)

![image](https://user-images.githubusercontent.com/1621749/163578428-f28ca5ec-fd06-4080-a23b-a141462ebcc3.png)

I wonder if we should say something like "water puddle" or "water accumulation." Not sure what the best tag is. Obviously, anything that is "waterlogged" would be (somewhat temporary) just like "parked car" (but that temporary nature can be inferred).

**Comment by misaugstad** [comment]
>I wonder if we should say something like "water puddle" or "water accumulation." Not sure what the best tag is

Maybe just "water" or "pooled water"?

I've also finished going through and making the list in my comment above, and I added a few comments to the google doc with questions (some for @jonfroehlich and some for Aldo). Let me know if you disagree with anything above!

**Comment by jonfroehlich** [comment]
I like pooled water!
