### ISSUE TITLE
Labeling guide expanding sidebar is broken

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2830]
##### Brief description of problem/feature
In the labeling guide, clicking the '+' in the sidebar is not expanding it. I think that I accidentally broke that CSS at some point recently :)

**Comment by misaugstad** [comment]
I think it was probably PR #2792 because that's when I added the list of cities to the navbar, and the error message in the console that I see at /labelingGuide references the list of cities in the dropdown.

**Comment by hawksFTW** [comment]
The + sidebar is expanding in Mikey's local environment but not in my environment or in the test servers. In browser this error comes up:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/69694786/176034543-40abe324-2747-4088-8d48-d5392a0b1bfa.png">

Something may be preventing the code in sidebarSubtopics.js from running. I'm looking into that now.
