### ISSUE TITLE
Show both audited streets (completed) and yet-to-be audited streets

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2832]
Currently, LabelMap shows you all completed audited streets but not which streets are allocated but not yet completed.

It would be useful to visualize both by default, so you can get a better sense of all that remains in particular neighborhoods (e.g., which streets are left yet to be completed)

![image](https://user-images.githubusercontent.com/1621749/159369635-4f799605-2f9c-4e90-870d-3f6c72fcdc1b.png)

**Comment by misaugstad** [comment]
closing in favor of #2873 which is a duplicate but has more added context
