### ISSUE TITLE
Explain why we cannot show a feature labeled in one panorama from other panoramas in FAQ

### ISSUE THREAD

**Issue by Soben713** [ProjectSidewalk/SidewalkWebpage#284]
Originally issued by @EdigaHe here: #267 

After I added some labels in the Street View window, the labels appear for a while but after I switch back from other places they disappear. I understand that the mini map at the right bottom corner shows all added labels but I prefer that the Street View window also remember all added labels.

@jonfroehlich's comment:

> Hi @EdigaHe, thanks for your comments. Generally, we reserve github tickets for actual bug reporting and issue tracking rather than discussion points... but thank you for posting your feedback.
> @kotarohara, @manaswis, @Soben713: this is the second time that a beta tester has reported confusion over point 2 above. We do cover it a bit in the onboard tutorial (but it's very subtle). I think we should at the very least add this to the FAQ about why we can't do this (though I agree that it would be nice).

**Comment by manaswis** [comment]
Adding Lee's comment too (just for the record)

Lee: It would also be useful if labels would propagate between images, so that I could see what I'd already labeled while moving ahead and avoid repeated or missed labels.

**Comment by jonfroehlich** [comment]
Thanks @manaswis. Yes, we get it. This would have been a core part of our design if it wasn't impossible. :) 

@kotarohara, do you have any videos of trying to get this feature to work back in the day?

**Comment by manaswis** [comment]
Based on our discussion in the meeting, we can't add this feature so we need to some way of circumventing it.

Solution: Add pop-up help messages in the first mission telling user that they can view their labels in the top-down map.

TODO: come up with appropriate message

**Comment by jonfroehlich** [comment]
@manaswis. After thinking about this more, I also think we could have a nice animated gif to the FAQ that simply shows someone labeling and then walking a bit and then turning around and showing that the labels aren't there--maybe also then walking back to the original location and showing that they are, actually, still there... and maybe pointing out the use of the top-down map.

**Comment by kotarohara** [comment]
@jonfroehlich No, I can't find the video.

**Comment by jonfroehlich** [comment]
@kotarohara, OK. I think we should just do the FAQ fix as I suggested.

**Comment by misaugstad** [comment]
This is referenced in the FAQ, though I don't know which PR added this.
