### ISSUE TITLE
Gray out severity levels for unsupported label types

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2840]
Now that we've removed severity ratings from some label types, we need to decide how to show (or hide) this info in other visualizations like Sidewalk Gallery. 

For example, here's Pedestrian Signal before our recent [change](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/2838):
![image](https://user-images.githubusercontent.com/1621749/159978722-059df33c-3c90-434a-9894-5acbe5fb3da6.png)

And here's what it looks like after:
![image](https://user-images.githubusercontent.com/1621749/159978800-e7839a8a-9563-4def-a46c-43bee0dca685.png)

I think I might argue, however, that for visual consistency with other gallery cards, we shouldn't make the severity ratings fully invisible but rather "disabled" by graying them out.

![image](https://user-images.githubusercontent.com/1621749/159978975-7411a005-121f-4ac1-9450-c6508b551f40.png)

**Comment by misaugstad** [comment]
In addition to graying out, we could have a tooltip for them explaining that those label types don't use severity ratings.

**Comment by jonfroehlich** [comment]
Agree!
