### ISSUE TITLE
Add Crosswalk and Pedestrian Signal to Interactive Tutorial?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2846]
Now that we have Crosswalk and Pedestrian Signal label types, we should discuss adding them to the interactive tutorial. Interestingly (and thankfully), these things **do** show up in our tutorial scenes!

![image](https://user-images.githubusercontent.com/1621749/161430704-3c53c0e4-ae81-4793-967c-e93b4107d9a1.png)

![image](https://user-images.githubusercontent.com/1621749/161430765-11fb780b-603a-43e0-a589-5de4b137c493.png)

![image](https://user-images.githubusercontent.com/1621749/161430787-56ef80d0-3390-491a-8fca-aff1b82d19dc.png)

![image](https://user-images.githubusercontent.com/1621749/161430811-7ea69577-3d26-4356-8876-05e9c59d9be7.png)

![image](https://user-images.githubusercontent.com/1621749/161430896-ecd5a898-7855-48ae-9c87-395a2a954c83.png)

![image](https://user-images.githubusercontent.com/1621749/161430923-78f32f77-1306-43af-a6dd-9b5f10609329.png)

Here's the annotated deck. I may have missed some things.
[ProjectSidewalk_Tutorial_PedestrianAndCrosswalksAnnotated.pptx](https://github.com/ProjectSidewalk/SidewalkWebpage/files/8404643/ProjectSidewalk_Tutorial_PedestrianAndCrosswalksAnnotated.pptx)

**Comment by misaugstad** [comment]
Some notes from a 1:1 meeting with @jonfroehlich:
* Start with user panned to the left a bit more so that they can't see the signal on the right and we don't have to deal with it :wink: 
* On the corner with 2 ramps, we'll probably let them know that they should label everything, but that we're going to label those 2 ramps and the pedestrian signal (and maybe even that following crosswalk?) for them to speed things up.
* The flow in the beginning is probably...
    1. Label first curb ramp
    2. Label first crosswalk
    3. Pan
    4. Zoom
    5. Label second curb ramp
    6. Label first missing curb ramp
    7. Label first pedestrian signal
    8. Zoom out
* The last curb ramp that they label is probably important to have them continue to label because it's not on a corner
* Outside of what we've generally landed on here, I'm going to play test a little bit to figure out what works to label or skip. It might be hard to tell what the flow is going to be like without actually putting some of those steps in. For example, should we have them label the second crosswalk..?

**Comment by misaugstad** [comment]
@jonfroehlich @devonsnyder @yeisenberg I have finished a draft of the text in the tutorial that includes crosswalks and pedestrian signals! I removed a few of the curb ramp labels in the middle, and excluded some of the pedestrian signal and crosswalk labels as well to speed things up a bit. The tutorial is still longer than it used to be.

I'm hoping for some input on the text! We can continue to iterate once it's live, but I'd like to at least have one round of text revisions before I send the text off to translators and get the first draft up on our test servers. Below I'm including anything that changed in a significant way. I'm including the text below the images in case you want to copy/paste for editing.

![Screenshot from 2023-08-31 17-24-49](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/a10af0ed-f9f4-45d1-a6a1-98bb86246f14)
>Now let's label the painted crosswalk. \<span class="bold">Click the "Crosswalk" button\</span>.

![Screenshot from 2023-08-31 17-24-55](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/112a7177-e287-4cf0-bfb3-4626ef48c5e2)
>Great! Now \<span class="bold">click beneath the flashing yellow arrow\</span> to label the crosswalk.

![Screenshot from 2023-08-31 17-25-15](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/9e9efe7c-42c9-46a8-ad5d-dd496a3dc243)
>Now you can rate the quality of the crosswalk where 1 is passable and 5 is not passable for a wheelchair user. Because the surface is smooth and the paint isn't fading, \<span class="bold">let’s rate it as 1, passable.\</span>

![Screenshot from 2023-08-31 17-25-23](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/7922bd6d-96f1-4773-b537-c787da7a33b2)
>Uh-oh, you should rate this crosswalk as 1, passable. The surface looks smooth and the paint isn't fading. \<span class="bold">Let’s click "1" to set its quality.\</span>

![Screenshot from 2023-08-31 17-25-41](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/5b98bc7d-7c5f-4e9a-abdb-51be82bc8e16)
>On the pole you can see a light telling pedestrians that they can cross the street. \<span class="bold">Click the "Pedestrian" Signal button\</span> to label it.

![Screenshot from 2023-08-31 17-25-50](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/6ec0949a-2659-471b-a0ff-fd8bb7f399f7)
>Now let's label it by \<span class="bold">clicking beneath the flashing yellow arrow\</span>. You can see the light higher up on the pole, but we ask you to add your label at the bottom of the pole because it gives us a more accurate location.

![Screenshot from 2023-08-31 17-26-21](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/7fde8d85-18cf-4060-a581-c645f878406f)
>Oops! Your label is too far away. For tall objects like poles, we ask you to add labels at the base of the pole. This gives us more accurate location info! \<span class="bold">Hover over the label and click the delete icon\</span>.

![Screenshot from 2023-08-31 17-26-34](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/78e08f3b-583c-4094-9bf4-ffb4b8dc43f0)
>There seems to be a painted crosswalk here as well. First, \<span class="bold">click on the "Crosswalk" button\</span>.

![Screenshot from 2023-08-31 17-26-42](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/1e830ef4-f2e0-43c8-a602-134578574e03)
>Let's label it by placing your label near the center of the crosswalk. \<span class="bold">Click below the flashing arrow\</span> to add your label.

![Screenshot from 2023-08-31 17-26-56](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/bd76553c-3ddf-455b-9c1c-ba4709005eae)
>Oops! Your label is too far away. Try adding your label at the center of the crosswalk. \<span class="bold">Hover over the label and click the delete icon\</span>.

![Screenshot from 2023-08-31 17-27-16](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/860526e8-ffd8-4816-860c-3e25911287f4)
>To help speed things up, we are labeling these two curb ramps, this crosswalk, and this pedestrian signal for you. In the future, you should label all of these yourself!

![Screenshot from 2023-08-31 17-27-33](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/a8274e98-d8c5-4115-8b49-af8d810a1ab9)
>We shouldn't forget the pedestrian signal! \<span class="bold">Click the "Pedestrian Signal" button\</span> to label it.

![Screenshot from 2023-08-31 17-27-41](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/f19c0b0f-2f8d-49eb-9872-6dbd29722ba8)
>\<span class="bold">Click at the base of the pole\</span> to label this pedestrian signal.

![Screenshot from 2023-08-31 17-28-07](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/226ba049-cb53-403b-bcfa-2c1dd8b391bf)
>Now you can look for more issues at this location. In this case, notice how there is a crosswalk with pedestrian signals but \<span class="bold">no curb ramps\</span> at either end.

![Screenshot from 2023-08-31 17-28-21](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/2c550060-15fb-4282-9d8f-a92deaeece49)
>In the future, you will need to add all of these labels yourself. But we want to get you started on actual missions, so let’s \<span class="bold">finish this tutorial!\</span>

**Comment by jonfroehlich** [comment]
This looks so awesome (and I can tell how much diligence and work it took!).

I think we should try to have **bolded** words in each popup, so just double check that you have that (seems to be missing on a few).

For this one (and one more instance), let's bold "your label is too far away":
<img width="755" alt="image" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/5c0968a0-b214-4c89-8b77-7b55f79e163d">

But overall, I think this is really close to shippable and then once on test, we can do another round of feedback?

**Comment by devonsnyder** [comment]
Great job Mikey and team! My only feedback would be to adjust the language
of "wheelchair user" if possible to something like "assistive device user"
or "someone using an assistive device". Or that could be introduced later
once when we've added some language about assistive devices to the labeling
guide on the site. I know that makes it a bit more clunky, but it would
help make sure raters are also considering how crosswalk conditions impact
folks who are using walkers and canes.

On Thu, Aug 31, 2023 at 7:58 PM Jon Froehlich ***@***.***>
wrote:

> This looks so awesome (and I can tell how much diligence and work it
> took!).
>
> I think we should try to have *bolded* words in each popup, so just
> double check that you have that (seems to be missing on a few).
>
> For this one (and one more instance), let's bold "your label is too far
> away":
> [image: image]
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1621749%2F264823432-5c0968a0-b214-4c89-8b77-7b55f79e163d.png&data=05%7C01%7Cdsnyde8%40groute.uic.edu%7Cfab89bde3e46458a0f3308dbaa8680b0%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C638291266887704804%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o3%2BO6X0kfPAiv4KuImLTc%2FRsRGRCqtC9MtjgYQXRyNk%3D&reserved=0>
>
> But overall, I think this is really close to shippable and then once on
> test, we can do another round of feedback?
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProjectSidewalk%2FSidewalkWebpage%2Fissues%2F2846%23issuecomment-1701965599&data=05%7C01%7Cdsnyde8%40groute.uic.edu%7Cfab89bde3e46458a0f3308dbaa8680b0%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C638291266887704804%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r%2FE%2B8UI58QV4wcr8q4dynIsLiCJKpKEqOfaZ8n%2FarRQ%3D&reserved=0>,
> or unsubscribe
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA5OCRMYLNCN6MCNLY4NUNK3XYEXJ3ANCNFSM5SNG25WQ&data=05%7C01%7Cdsnyde8%40groute.uic.edu%7Cfab89bde3e46458a0f3308dbaa8680b0%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C638291266887704804%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Bj3R6Z3v2BpZo%2BzlJxaHVdtl6WcKiXOYXWkIxJ9iidI%3D&reserved=0>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
Devon Snyder *(she/her/they/them)*
Project Coordinator
Department of Disability and Human Development
UIC College of Applied Health Sciences
UIC, Master of Urban Planning & Policy '22
***@***.*** | 425-443-0301

**Comment by jonfroehlich** [comment]
Great point @devonsnyder. I think this brings up a larger issues about how we frame the problem of sidewalk accessibility labeling: is it generally for anyone who might benefit from an accessible and safe sidewalk (children, people who are blind or low vision, wheelchair users, others who use an assistive aid) or is it specifically for wheelchair users.

I think we've been shifting to the former but haven't yet really made this specific in our UI and framing to the user.

**Comment by yeisenberg** [comment]
Great work Mikey, looks awesome. some quick feedback:
Agree with the discussion for making it as a larger user group of people with disabilities vs. wheelchair users only
For the ped signal, is there a pop-up with how to fill it out? I know I’m annoying about this, but would still like to advocate for there being a scale on this and having a tag for it having an audio signal (I know I need to get you supporting material for that). I think it is important for blind/low vision group…

**Comment by jonfroehlich** [comment]
> Agree with the discussion for making it as a larger user group of people with disabilities vs. wheelchair users only

Sure, I agree too. But it's not clear how to operationalize this. And it seems like an issue that pervades beyond just the tutorial to nearly all aspects of the tool.

Re: pedestrian labeling
I think that makes sense but I also think that labeling things like audio signal is towards one of the most difficult things we have in Project Sidewalk (and is also fairly US centric). Not saying we shouldn't add it but just pointing to how important it will be to create good training materials

Finally, given the divergence of discussion here, I might offer that we should figure out: (1) what needs to be done right now to ship the new tutorial; (2) what things we know we want to do longer term.

**Comment by misaugstad** [comment]
>I think we should try to have bolded words in each popup, so just double check that you have that (seems to be missing on a few).

Can do!

>For this one (and one more instance), let's bold "your label is too far away":

Sounds good!

>For the ped signal, is there a pop-up with how to fill it out? I know I’m annoying about this, but would still like to advocate for there being a scale on this and having a tag for it having an audio signal (I know I need to get you supporting material for that). I think it is important for blind/low vision group…

As of now, none of our tags would apply to these pedestrian signals, so I skipped that part and am just closing the context menu and pushing them forward after they label the signal. I figured that if we add tags that would apply, we would update the tutorial at that time!

>adjust the language of "wheelchair user" if possible to something like "assistive device user" or "someone using an assistive device".

I had just copied over language from another part of the tutorial :grin: The tutorial may be the best time to introduce this term to users, so maybe it's worth putting it in with a tooltip now since I'm already working on the tutorial?

**Comment by yeisenberg** [comment]
Got you, thanks for the explanation for that Ped signal Mikey and sounds good to move forwward to complete the task and than adjust once we have more info. I'll follow-up with more info - re possible ways to easily code audible signal precense...thanks
