### ISSUE TITLE
On LabelMap, the "Curb Ramp" checkbox doesn't work

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2854]
If you try to uncheck the Curb Ramp label type, the map still shows them. Looks like there is an error thrown in console. Should be easy to test. This is in Oradell.

![image](https://user-images.githubusercontent.com/1621749/161752866-856b0c0d-ac81-44d1-aea1-0adb1e78f818.png)

```
Uncaught TypeError: Cannot read properties of undefined (reading 'CurbRamp')
    at toggleLayers (MapUtilities.js:26:48)
    at HTMLInputElement.onclick (labelMap:366:232)
```

**Comment by misaugstad** [comment]
Oh no, I forgot to do one last sweep to check all of the buttons! Should be an easy fix.

**Comment by jonfroehlich** [comment]
Great. Thanks. We've already had nice feedback from the Amsterdam team about how valuable the new functionality of seeing validated/unvalidated labels is (and the correctness judgments) but things don't work as you'd expect since that curb ramp checkbox is broken.
