### ISSUE TITLE
Update tags for Amsterdam

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2856]
##### Brief description of problem/feature
Here's the current list of changes we want to make to the tags for Amsterdam in particular. @jonfroehlich please comment if I missed something or if anything new comes up!
- [x] Remove 'points into traffic’ tag from curb ramps
- [x] Remove ‘brick’ tag from surface problem
- [x] Remove ‘brick’ tag from crosswalks
- [x] Add ’no pedestrian priority’ tag under crosswalks
- [x] Remove 'missing friction strip' (soon to be known as 'missing tactile warning')
- [x] Add 'tactile warning' (instead of 'missing tactile warning')

Then change this everywhere:
- [x] Change ’missing friction strip’ to ’tactile warning’.

**Comment by jonfroehlich** [comment]
I think switching 'missing friction strip' to 'missing tactile warning' might be good for all US cities.

And then, for Amsterdam, they want us to invert this. That is, only mark 'tactile warning' when one exists (and the default is that it does not).

![image](https://user-images.githubusercontent.com/1621749/164086113-ada8efd4-5f81-4afb-831b-d346388fc9ea.png)
