### ISSUE TITLE
Validate specifics of ratings

### ISSUE THREAD

**Issue by yeisenberg** [ProjectSidewalk/SidewalkWebpage#2859]
##### Brief description of problem/feature
Wondering if possible to set up validation for specific aspects of labels? like validating tags separately and validating the scores, where you could provide your own score to compare with? So the validation mission would have a very specific purpose.

**Comment by jonfroehlich** [comment]
This has long-been discussed.

I think there are two related issues here:
- First, making it more clear on the *current* validation flow **what** you are supposed to be validating. Is it *just* the label type? Or the combination of label type + tags + severity? This is a common question that we receive. If you look at the validation UI question, it says: "Is this a curb ramp" or "Is this a surface problem", which is supposed to indicate to the user to validate things on the label level (and not necessarily severity + tags) but this is ambiguous.
- Second, how to validate tags and severity ratings. We talk more about this here (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2575) 

See also Issues tagged with quality-control (https://github.com/ProjectSidewalk/SidewalkWebpage/labels/quality-control) or validation (https://github.com/ProjectSidewalk/SidewalkWebpage/labels/Validation).

**Comment by yeisenberg** [comment]
Got it, thanks for sharing these previous discussions. I could see it being something ADA coordinators may want. For instance, to prioritize improvements, they'd likely want the severity to be validated.

**Comment by misaugstad** [comment]
Latest designs are here: https://www.figma.com/file/6pnEQVzUHOTFPPUwaZu9xI/Project-Sidewalk?type=design&node-id=0%3A1&mode=design&t=FK6b9KPiRGd2DoKN-1

Going to get started on the back end work for this!
