### ISSUE TITLE
Change message when user steps outside an assigned neighborhood and is jumped to a new location

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#286]
Currently, the tone is bit harsh and puts the blame on the user for stepping out.

<img width="1280" alt="jumping_neighborhood" src="https://cloud.githubusercontent.com/assets/2873216/18189539/c908a0c4-7089-11e6-91d8-0ed7e0ea5aa6.png">

TODO: Come up with several messages that we can show.

**Comment by kotarohara** [comment]
@manaswis Do you want to work on it?

**Comment by manaswis** [comment]
Sure

**Comment by manaswis** [comment]
Closing this issue as its no longer applicable due to the new jump implementation.
