### ISSUE TITLE
The NSF funding info is incomplete in "We are proudly funded by..."

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2861]
![image](https://user-images.githubusercontent.com/1621749/163579131-2d077aff-211a-481a-9a67-6f76009da253.png)

Two things related to the NSF listing:

- The number is not centered below the NSF logo
- We need to have two numbers and both should be hyperlinked: [#1302338](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1302338) and [#2125087](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2125087)

Also relates to: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2732

**Comment by MohitSoni11** [comment]
Previous: Award #1302338
New: Award #1302338 and #2125087

Please add Spanish translations with the PR.

**Comment by MohitSoni11** [comment]
Previous: Award #1302338
New: Award #1302338
 and #2125087

Can I please have the translations into Spanish for the new text?
