### ISSUE TITLE
incorrect % of Chicago mapped

### ISSUE THREAD

**Issue by yeisenberg** [ProjectSidewalk/SidewalkWebpage#2863]
The Chicago deployment landing page says 30% of Chicago has been mapped, but it is much lower. Am thinking this is related to how much we've opened up right? Is there a way to revise this percentage so people who visit the site don't get the wrong idea? Like call it % of sidewalks opened in Chicago area? or recalculate based on total miles of road?
Thanks,
Yochai

**Comment by jonfroehlich** [comment]
This calculation is based simply on the number of auditable roads available in the neighborhoods that are currently open in Project Sidewalk.

Agree that this metric is strange for when we do selective roll outs as we do in Chicago

**Comment by misaugstad** [comment]
Maybe we could add a config that for whether or not the entirety of a city has been opened up. Then we can display "X% of \<city\>" if it's all revealed, or "X% of target area in \<city\>" if not.

**Comment by yeisenberg** [comment]
I like that approach! and way of specifying the % based on target area

**Comment by misaugstad** [comment]
@palbirmin I imagine that you'd be adding this to the `conf/cityparams.conf` file. The list of cities that have the entire city rolled out:
- DC
- Newberg
- SPGG
- Oradell

Those that are only partially opened up:
- Seattle
- Columbus
- Pittsburgh
- CDMX
- La Piedad
- Chicago
- Amsterdam
- "Validation Study"

**Comment by palbirmin** [comment]
I have added a config for whether or not a city has been opened. 
Currently, I am unsure about the appropriate message to display.  Should I use the phrase "target area in <city> mapped", shorten it or change the phrasing? 

![image](https://user-images.githubusercontent.com/95188914/168702845-b90a6d7c-1996-4b69-ac41-4e66308d1777.png)
![image](https://user-images.githubusercontent.com/95188914/168703486-2489c175-3149-4260-81b8-7f5e78b79bab.png)
