### ISSUE TITLE
Something strange going on with neighborhood completion rate and segments marked audited

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2872]
Last night during the mapathon, the Girl Scouts decided to create their own final challenge for the last hour: completely mapping Central Oradell. We, ostensibly, completed that challenge—and the neighborhood choropleth shows 100%:
![image](https://user-images.githubusercontent.com/1621749/164896376-665a1c6d-f316-4cdb-b938-7e4f65839e72.png)

However, when you actually look at the LabelMap, you see many streets that were not marked as audited. Here's the current LabelMap followed by a version I made that highlights all unaudited streets in red (focusing solely on Central Oradell):

![image](https://user-images.githubusercontent.com/1621749/164896423-9b7a07ef-3423-445b-965b-298ba6dd8516.png)

![image](https://user-images.githubusercontent.com/1621749/164896603-08a4af75-f67c-4a05-bed6-f5b667ae4cb2.png)

So, a few things could be going on:
* One, some of those streets were simply never included—they got excluded when we created the underlying dataset for Oradell when pulling from OSM
* Two, there is a bug in LabelMap showing us what street segments have been audited or not
* Other things?

But this seems like a high priority thing to examine. It's really important that we audit all available roadway that could potentially have sidewalks.

Also, I checked, and that Highway 80 is actually Oradell Ave and has sidewalks on both sides. It should be audited—[see link](https://www.google.com/maps/@40.9544447,-74.0325146,3a,75y,99.94h,76.33t/data=!3m10!1e1!3m8!1sGJ3TEqgHhtm8VYHsLXy64A!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DGJ3TEqgHhtm8VYHsLXy64A%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D320.17358%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192!9m2!1b1!2i33).
![image](https://user-images.githubusercontent.com/1621749/164896570-de94a44e-de5e-45ba-86b9-63d5cf7a9f4f.png)

Here's the PPT file. [CentralOradell.pptx](https://github.com/ProjectSidewalk/SidewalkWebpage/files/8547364/CentralOradell.pptx)

**Comment by jonfroehlich** [comment]
Despite Central Oradell showing as 100% audited, I selected the neighborhood and started auditing this morning. Once I completed a mission, I was shown this mission complete screen which indicates that 3.1 miles are left? Something very strange is going on.

![image](https://user-images.githubusercontent.com/1621749/164909245-e842cd13-c064-46e5-b524-34f90861a30a.png)

**Comment by jonfroehlich** [comment]
Maybe what's happening is that as we gather more validations, some users are being inferred as "low quality" and their audited segments are no longer being counted. And I remember there being a difference between how the completion rate for the choropleth is counted vs. in other areas of PS.

**Comment by misaugstad** [comment]
>some users are being inferred as "low quality" and their audited segments are no longer being counted. And I remember there being a difference between how the completion rate for the choropleth is counted vs. in other areas of PS.

Yep, this seems to be exactly what's happening. For example, I found one user with 3.8 miles audited but only 3 labels added. Most of the streets you highlighted in red have been audited by that user.

![Screenshot from 2022-04-26 17-09-20](https://user-images.githubusercontent.com/6518824/165413058-c2db9f4d-ea0c-4355-a91f-7c6716e2d1fa.png)

You can find my lengthy musings on this issue in #2770

**Comment by jonfroehlich** [comment]
Wow, yikes. They must have misunderstood something. I think many of these streets are where there are no sidewalks, and they didn't realize they had to add no sidewalk labels frequently.

In fact, when I select Central Oradell and start auditing, I'm getting routed along streets, I believe, that were previously done by low-quality users. And my work **is** being counted.

![image](https://user-images.githubusercontent.com/1621749/165621573-2d00f85d-0ffc-4b71-8b16-783410e87fcb.png)

**Comment by jonfroehlich** [comment]
@misaugstad, actually, in thinking about this more, I think we should try and resolve the completion rates on the choropleth to be more accurate. I don't think Central Oradell should show with 100% completion when we have discarded low-quality users. It should actually show how much is remaining to finish it with "high-quality" users.

This will also then be easier to communicate with our city partners and other stakeholders about how much work is left.

Thoughts?

![image](https://user-images.githubusercontent.com/1621749/165756938-14639583-d9ee-4abb-a1db-59555793f375.png)

**Comment by misaugstad** [comment]
I totally agree! The main question I have is what whether or not this percentage should increase while someone who has already been marked as low quality is actively auditing in that neighborhood. If someone is marked as low quality and audits a mile, should the percentage change?

I assume for now that we just have it _not_ change. That will be confusing for those users, but right now it is confusing for *all* users anyway :upside_down_face:

**Comment by jonfroehlich** [comment]
> I assume for now that we just have it not change.

Agree.

**Comment by misaugstad** [comment]
Okay it looks like this was only _mostly_ addressed! But I missed one crucial piece! There's this extra conditional that we used to deal with rounding errors, and it looks like I missed changing our method of calculating distance in that one conditional... So neighborhood that you see that are partially audited, those percentages are correct on the maps. But some neighborhoods that say that they are completely audited actually need more work. I will fix that in the next day or two!

The top-line numbers that say miles remaining or percent of the city audited as a whole are correct though.

I was also completely convinced that we were resetting the completion percentage for neighborhoods every night after updating the `user_stat` table, but it turns out that we are not! So I will add that in as well.
