### ISSUE TITLE
Update user dashboard map to show/hide correct, incorrect, and unvalidated labels

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2875]
Since @misaugstad has added this functionality to the main LabelMap, we should also add it to the user dashboard.
![image](https://user-images.githubusercontent.com/1621749/164897398-a18847f7-607c-40cc-b7b1-1b811e591070.png)

This is also related to: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2288, which has been a long-open ticket with a "very high" priority.

**Comment by misaugstad** [comment]
closing as a duplicate of #2811
