### ISSUE TITLE
Update API instructions

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2880]
It's not clear from the API webpage if the data is already clustered or if you are getting raw labels. There was some confusion about this with Liga Peatonal.

https://sidewalk-spgg.cs.washington.edu/api

I think just generally we need to update the API page to make it more readable and understandable following best practices from other API pages.

**Comment by misaugstad** [comment]
Related to #2754. @jonfroehlich feel free to close one of them if you think that they are both covered by one of these.

**Comment by jonfroehlich** [comment]
Bwahahah. Your original post is better. Let's close this one. :)

But the nice thing is, we know there are people out there using our API! 🤘🚀🎉
