### ISSUE TITLE
New API endpoint for general PS stats

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2882]
Mikey and I just discussed a general API endpoint to get some basic stats off of each server like

```
{
  label_cnt: ####,
  users_cnt{
    num_users: ####,
    num_labelers: ####,
    num_validators: ####,
    num_registered: ###,
    num_anonymous: ###
    ...
  }
  label_cnt{
    overall: ###,
    surface_problem_cnt: ###,
    obstacles_cnt: ###
    ....
  }
  validations_cnt{
   overall: ###
   agree_cnt:###
  ...
  }
} 
```

**Comment by jonfroehlich** [comment]
@misaugstad this has become pretty important now as I write reports for PacTrans, NSF, etc. This way, I would not be bottlenecked to you doing backend SQL queries either whenever I'm preparing presentations, etc.

It would be good to have like either a REST parameter for `high_quality_only=true` or to somehow include both low and high quality results in the data dump. The latter is probably preferred.

```
{
  users_cnt{
    num_users: ####,
    num_high_quality: ####,
    num_labelers: ####,
    num_validators: ####,
    num_registered: ###,
    num_anonymous: ###
    ...
  }
  label_cnt{
    overall: ###,
    high_quality: ###, //only labels from high quality users
    surface_problem_cnt: ###,
    obstacles_cnt: ###
    ....
  }
  validations_cnt{
   overall: ###,
   high_quality: ###, // only validations from high quality users
   agree_cnt: ###
  ...
  }
} 
```

**Comment by jonfroehlich** [comment]
Thanks for adding this to your @misaugstad task board. I just came here this morning to say that I needed this feature again this morning! 🌄And I'd sure love to have it! :)

**Comment by jonfroehlich** [comment]
@misaugstad, I'm now working on an NSF report and would really benefit from this API endpoint. Can I get an estimate of when this might be done?

**Comment by misaugstad** [comment]
I would say in 1.5 to 2 weeks, but usually in that amount of time we end up finding things that are more important to put ahead of this 😁

**Comment by jonfroehlich** [comment]
Thanks Mikey. I came back here to say, I found another circumstances where we need these API call (we're preparing a talk for TRANSED and want to present current counts of things). It would just be so lovely to have this API and then I wouldn't have to rely on your backend SQL dumps to produce latest numbers.

**Comment by jonfroehlich** [comment]
@misaugstad and I are Slacking about our "reputation" system again and I'm curious how that might affect this API... and whether @misaugstad agrees with the general format...

```
{
  users_cnt{
    num_users: ####,
    num_high_quality: ####,
    num_labelers: ####,
    num_validators: ####,
    num_registered: ###,
    num_anonymous: ###
    ...
  }
  label_cnt{
    overall: ###,
    high_quality: ###, //only labels from high quality users
    surface_problem_cnt: ###,
    obstacles_cnt: ###
    ....
  }
  validations_cnt{
   overall: ###,
   high_quality: ###, // only validations from high quality users
   agree_cnt: ###
  ...
  }
} 
```

I also previously asked:
>It would be good to have like either a REST parameter for high_quality_only=true or to somehow include both low and high quality results in the data dump. The latter is probably preferred.

And I'm not actually sure what the right approach is for this.

**Comment by misaugstad** [comment]
I am down with the general format. Though at least for the purposes of programming and the readability of the results, having that REST parameter would work better IMO. We would have to duplicate possibly every single value for high/low quality, so it feels like it makes more sense to only query for one at a time.

Alternatively, keeping the variable names the same, but just separating them into two separate JSON objects:
```
{
  all_users: {
    users_cnt {
      num_users: ####,
      num_labelers: ####,
      num_validators: ####,
      num_registered: ###,
      ...
    },
    label_cnt {
      overall: ###,
      surface_problem_cnt: ###,
      ....
    },
    validations_cnt {
     overall: ###,
     agree_cnt: ###,
    ...
    }
  },
  high_quality_only: {
    users_cnt {
      num_users: ####,
      num_labelers: ####,
      num_validators: ####,
      num_registered: ###,
      ...
    },
    label_cnt {
      overall: ###,
      surface_problem_cnt: ###,
      ....
    },
    validations_cnt {
     overall: ###,
     agree_cnt: ###,
    ...
    }
  }
}
```

**Comment by jonfroehlich** [comment]
Right! I was thinking similarly. I think either solution is good (either REST or separate JSON objects). I will defer to you.

Thanks @misaugstad!

**Comment by misaugstad** [comment]
@jonfroehlich for the count of validations, do you need the actual count of the number of validations broken down by agree/disagree/notsure? Or do you just need a count of the _number of labels_ that have been validated, broken down by agree/disagree?

I assume that the latter is much more useful. Though I can still include the total validation count separate from the count of the total number of labels validated.

**Comment by misaugstad** [comment]
@jonfroehlich since I already had a giant query written that does everything described, plus some other stuff, I added some other stats :) Pasting the JSON structure I'm thinking of below. I have turkers in their own category. And I only have the total count of the number of validations (not broken down by agreement). However, I do have the _number of labels_ broken down by agreement.

```
{
    km_explored: ###.##,
    km_explored_without_overlap: ###.##,
    users_counts: {
        all_users: ####,
        labelers: ####,
        validators: ####,
        registered: ###,
        ...
    },
    labels: {
        label_count: ###,
        curb_ramp: {
            count: ###,
            count_with_severity: ###,
            severity_mean: #.#,
            severity_sd: #.#
        }
        ...
    },
    validations: {
        total_validations: ###,
        labels_validated: ###,
        labels_agreed: ###,
        labels_disagreed: ###,
        overall_accuracy: ##.##%,
        curb_ramp: {
            validated: ###,
            agreed: ###,
            disagreed: ###,
            accuracy: ##.##%
        },
        ...
    }
}
```

Let me know if there's anything you see off the top of your head that's missing or needs to change!

**Comment by jonfroehlich** [comment]
Great work @misaugstad!

1. Agree that turkers should be their own category
2. We previously had a `high_quality_only` JSON block. Can we still do this?
3. Ugh, not sure I understand your question about num of validations :( But I'm having morning brain fog 🧠🌫 before my first cup of coffee. Maybe we Slack about it?

**Comment by misaugstad** [comment]
>We previously had a `high_quality_only` JSON block. Can we still do this?

I'm adding it as a query parameter!

>Ugh, not sure I understand your question about num of validations :( ... Maybe we Slack about it?

Can do!

**Comment by misaugstad** [comment]
Discussed with Jon on Slack, and he agreed with the current approach!
