### ISSUE TITLE
Gallery logging isn't actually connected to users

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2885]
##### Brief description of problem/feature
I wanted to start using some of the logs in the `gallery_task_interaction` table, but I realized that we don't actually have these logs connected to a `user_id` in any way! There is a screenshot below of the relevant table. The `audit_task_interaction` and `validation_task_interaction` tables are connected to a user through a `mission_id` field. This doesn't make as much sense for Gallery, but we should at least be including the `user_id` in the table then if we don't add a table to keep track of separate sessions.

Similarly, when someone validates a label through Gallery, this isn't being directly tied to the logging in Gallery in any way. We should really be including the `label_id` in the `note` column in the `gallery_task_interaction` table whenever a validation happens. We should be able to back-fill in most cases, because the `gallery_task_interaction` and `label_validation` timestamps should match up.

And finally, it looks like the `pano_id` column is always null in the `gallery_task_interaction` table, which was clearly not the intention :upside_down_face:. We can at least back-fill this for the logging of someone validating a label, and that might be the only pano-specific logging that we are doing now anyway.

**Comment by misaugstad** [comment]
Oh, it also looks like we switched out logging of `Validate_MenuClick={Agree,Disagree,NotSure}` to `Validate_MenuClick{Agree,Disagree,NotSure}` (removed the `=`) at some point, but it wasn't changed in our old logs. That will be easy to update.

**Comment by misaugstad** [comment]
Oops, here's the picture! And yeah this one is my bad! I must not have noticed this lapse when reviewing the PR for Gallery from the beginning.

![Screenshot from 2022-05-09 13-42-11](https://user-images.githubusercontent.com/6518824/167512844-232e64d6-ee3a-4081-a39c-4522b0f4e6b8.png)

**Comment by jonfroehlich** [comment]
@misaugstad and I discussed this. He's going to fix it for the future (and not write SQL queries to fix it for the past logs).
