### ISSUE TITLE
Need to add crosswalks and pedestrian signals to validation missions

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2887]
This is especially important for the validation study with Devon + Yochai.

Obviously, have to get this stuff into our labeling guide as well (!). 😊

**Comment by misaugstad** [comment]
And we still keep No Sidewalk validation missions as lowest priority?

**Comment by jonfroehlich** [comment]
Hmm. What are your thoughts here... probably?

**Comment by misaugstad** [comment]
I think so... I don't see a lot of No Sidewalk labels being misplaced, so it's probably not as high value to get validations for those labels. The issue is more about not placing enough of them :stuck_out_tongue:

**Comment by jonfroehlich** [comment]
Great. Thanks. In addition to the labeling guide, we'll have to find "do" and "do not" examples for the right sidebar, so this is a bigger ticket than it may initially seem...

**Comment by misaugstad** [comment]
@jonfroehlich what text would you add to say that this is not a crosswalk?

![Screenshot from 2022-05-26 10-07-35](https://user-images.githubusercontent.com/6518824/170541916-c421a069-5905-4867-adea-e0631ba30f06.png)
