### ISSUE TITLE
Add in user info into Access Attributes API

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2889]
For our Access Attributes API, I suggested (and @misaugstad agreed) that we could add in user id info for each cluster. 
Because clusters can involve labels from multiple users, it needs to be a list. The `user_id` would be like a hash of the actual id.

For example:

```
"users":{
         "user_ids" : [user_id1, user_id2, etc.]
      }
```

We could then use a new API endpoint for users that returns information about their label count, accuracy, etc.

Full example of a label cluster JSON:
```
{
         "type":"Feature",
         "geometry":{
            "type":"Point",
            "coordinates":[
               -74.04113006591797,
               40.94673156738281
            ]
         },
         "properties":{
            "attribute_id":52534,
            "label_type":"NoCurbRamp",
            "street_edge_id":359,
            "osm_street_id":11588730,
            "neighborhood":"South Oradell",
            "severity":3,
            "is_temporary":false,
            "agree_count":1,
            "disagree_count":5,
            "notsure_count":0
         }
      },
      "users":{
         "user_ids" : [user_id1, user_id2, etc.]
      }
```

**Comment by misaugstad** [comment]
It might make more sense to just include the user_id in the /attributesWithLabels API endpoint instead of the /attributes endpoint. But yes I agree that we could include user_id and have a separate endpoint for users' accuracy and such!

**Comment by jonfroehlich** [comment]
Ack, yes, I didn't notice those two endpoints are different since of how they are folded together in the API docs.

Does `/attributesWithLabels` return raw labels and `/attributes` returns clusters?

**Comment by misaugstad** [comment]
`/attributes` returns just clusters, and `/attributesWithLabels` returns the clusters AND the accompanying labels.

**Comment by igornishka** [comment]
This would be indeed great! Both list of users in /attributes and user_id only in /attributesWithLabels, but the second one would definitely be more useful for analysis of the raw data

**Comment by misaugstad** [comment]
@zoekaputa this seems like a good next API task! I would only worry about including the `user_id` in the /attributesWithLabels endpoint, and just include it in the `properties` section where all the other metadata goes :)
