### ISSUE TITLE
Huge Landing Page Interface Icons on Page Load

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#289]
While this is a small problem, it is noticeable and does make our website feel a bit amateurish. 

Video: https://youtu.be/KHDJF2MSOlc

![image](https://cloud.githubusercontent.com/assets/1621749/18190112/1856d084-708e-11e6-9971-a654b357b8c5.png)

Is probably something that @Soben713 could solve given his background.

But perhaps the point is moot if we redesign the landing page anyway.

**Comment by Soben713** [comment]
I think this will be fixed if we add `width=200` to the html tag of the image instead of specifying it in the CSS file. I tested it and it seems to be working fine on my local server.

**Comment by jonfroehlich** [comment]
That's an easy fix but doesn't that break good HTML/css design? :)

**Comment by Soben713** [comment]
It does. However considering the main reason of this problem, which is the time it takes for the CSS files to be loaded, I can think of only two ways to fix this:

1. Specifying the width in the HTML file
2. Changing the original image size

Maybe the latter fix would be better.

**Comment by jonfroehlich** [comment]
I agree, I think we should do the latter. Hmm, it's currently an SVG but we could just make it a 200 pixel wide PNG or something. No reason that I know of to make this an SVG...

**Comment by Soben713** [comment]
There is no need to change the file type. It is possible to specify a default width for an SVG image too. Scalability of the image is the main benefit, the image will not look sharp in high resolution displays if it is not scalable.

**Comment by jonfroehlich** [comment]
OK, let's set the default width then!
