### ISSUE TITLE
No brick tag in Mexico?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2897]
@misaugstad, do you remember why there is no brick tag in Mexico:
![image](https://user-images.githubusercontent.com/1621749/168322824-84795436-2f24-4b56-a29c-582004336e45.png)

**Comment by misaugstad** [comment]
I believe that it was suggested to be quite uncommon. The Github issue is #1945 and the spreadsheet where we planned out our initial tags for Mexico is [here](https://docs.google.com/spreadsheets/d/19IAtCwQiK9ghTVkF8agEvV_5SOh6ezcYkEAG4kEtBSE/edit#gid=0).

**Comment by jonfroehlich** [comment]
Gotcha. Yes, here it's more of an adornment.

**Comment by jonfroehlich** [comment]
I don't know. I just saw some brick sidewalk in La Piedad...

![image](https://user-images.githubusercontent.com/1621749/168395019-97813b95-c282-40c4-911c-f5ab795baca4.png)

**Comment by misaugstad** [comment]
I would talk about it with folks from Liga Peatonal. I believe that they are the ones who originally said that we don't need the brick tag. And maybe that had more to do with CDMX and/or SPGG in particular, as opposed to Mexico as a whole.

**Comment by jonfroehlich** [comment]
I think we need to bring it back... here's another example:
![image](https://user-images.githubusercontent.com/1621749/168442315-22a512a6-9944-4d1e-8fc5-dce209e91a01.png)

**Comment by jonfroehlich** [comment]
Just saw that your new release didn't include the brick tag...

**Comment by misaugstad** [comment]
Yeah we didn't have that fully nailed down yet, I don't think you got a response in the #mexico channel on Slack yet.

**Comment by jonfroehlich** [comment]
Jesús said:

> En lo que a mi respecta, podría estar bien, no hay mucho, pero lo tenemos, acá se le conoce a ese material como adoquín, así también, hablando de la superficie, creo que podría ser bueno agregar una etiqueta que se llame empedrado, agrego imagen. Saludos.

Translation:

> As far as I'm concerned, it could be fine, there's not much, but we have it, here that material is known as cobblestone, also, speaking of the surface, I think it could be good to add a label called cobblestone, I add image. Greetings.

**Comment by misaugstad** [comment]
Oops, I didn't change the tag to brick/cobblestone!
