### ISSUE TITLE
Keyboard binding for selecting the problem severity in the context menu

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#29]
Jon's comment: I like being able to use the keyboard to select my label type but I want to be able to use my number keys to select 1,2,3,4,5, etc.

**Comment by kotarohara** [comment]
Assigned to Daniil

**Comment by kotarohara** [comment]
@danZzyy addressed this issue. I'm closing it.

**Comment by jonfroehlich** [comment]
Is this on sidewalk.umiacs yet? I checked and it didn't work...
