### ISSUE TITLE
Edge case: can break Explore by clicking on label and nav arrows at the same time

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2922]
##### Brief description of problem/feature
If you add a label, then pan so that the label is directly under one of the navigation arrows, then click on a point that covers both of them, you can fully break the Explore page. The interface tries to open the context menu and move at the same time, which ends up with the context being open on the wrong panorama without the label. You can't close the context menu. You can't add new labels. And there seems to be something wrong with the navigation arrows as well, and I haven't been able to get back to the pano where I placed the label to be able to close the context menu!

![Screenshot from 2022-05-26 15-19-16](https://user-images.githubusercontent.com/6518824/170589385-15e3a4ad-63bb-468a-9e0c-599573ab6b6e.png)

Not a super common bug, so it's not high priority. And refreshing the page fixes the problem.

##### Potential solution(s)
Hopefully we can just change the z-index for either the labels or the nav arrows so that one is clearly on top of the other.

**Comment by misaugstad** [comment]
Related to #1055

**Comment by jonfroehlich** [comment]
Noting here that it was brought up by the Zurich team—who said they encountered it "several time" and it's been mentioned in a few of their reports to us. :)

**Comment by misaugstad** [comment]
This has been fixed! I'm pretty sure that I fixed it while working on RouteBuilder or something, but I don't actually remember when it was fixed. I didn't realize that I had an open issue for the bug at the time!
