### ISSUE TITLE
Tutorial not allowing users to exit to exploration after completion

### ISSUE THREAD

**Issue by GPA0VERKD** [ProjectSidewalk/SidewalkWebpage#2924]
##### Brief description of problem/feature
After the tutorial is finished, the user is shown a screen that congratulates the user and lets them hit an 'ok' button to move on the exploring. However, the 'ok' button does nothing right now, so the only way a new user can move on is to refresh the page to restart the tutorial and hit 'skip tutorial' to get around it altogether.

##### Expected behavior
Hitting the 'ok' button should move the user to 'exploring' UI

##### Current behavior (add screenshots if applicable; check terminal & browser console for errors)
At the end of the tutorial, the user is stuck on this screen:
![image](https://user-images.githubusercontent.com/77756028/170785189-98df4061-74f2-4a03-a579-c2bd18c57fec.png)
With these error logs:
![image](https://user-images.githubusercontent.com/77756028/170785300-8274009b-8c91-4f35-95be-c28d43dab20a.png)
*note: the "Uncaught TypeError" error shows up once when reaching the end of tutorial screen, the again when the 'ok' button is clicked*

Error log:        
Uncaught TypeError: Cannot read properties of null (reading 'getPanoId')
    at LabelContainer.addUpdatedLabel (SVLabel.js:5053:25)
    at Tracker.refresh (SVLabel.js:1302:32)
    at Form.compileSubmissionData (SVLabel.js:3251:17)
    at Tracker.submitForm (SVLabel.js:1283:33)
    at Tracker.push (SVLabel.js:1274:18)
    at HTMLDocument.<anonymous> (SVLabel.js:1083:18)
    at HTMLDocument.dispatch (jquery-1.12.2.min.js:3:12444)
    at HTMLDocument.r.handle (jquery-1.12.2.min.js:3:9173)

**Comment by misaugstad** [comment]
Super high priority. Users need to be able to finish the tutorial!! We were going to release a new version of Sidewalk today anyway, so a fix for this needs to be included.
