### ISSUE TITLE
Updated URL for acquiring city boundaries

### ISSUE THREAD

**Issue by paulterinho** [ProjectSidewalk/SidewalkWebpage#2933]
# Brief description of problem/feature

- Clicking on city boundary link gives a 404 in the New City Setup. 
- Not a blocker. Low priority. 

# Expected behavior

- Click on link and see a website

# Current behavior (add screenshots if applicable; check terminal & browser console for errors)

- Click on link and getting a 404.

# Steps to reproduce

- Go to `https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Creating-database-for-a-new-city` 
- Click on the `https://wambachers-osm.website/boundaries/` link.
- See the 404 notification.

# Potential solution(s)
- Update the link or remove it.

**Comment by misaugstad** [comment]
Fixed! Looks like another group in Sweden was using the tool, saw that it was taken down, and made their own! You can find it here: https://osm-boundaries.com/. I've updated the link on the wiki page.
