### ISSUE TITLE
Add 'level with the sidewalk' tag for crosswalks in Amsterdam

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2935]
##### Brief description of problem/feature
We need to add this tag in Amsterdam, ideally before Monday morning, since they will be running a training on that day.

**Comment by jonfroehlich** [comment]
Is this on production yet? Doesn't look like it.

![image](https://user-images.githubusercontent.com/1621749/173595941-59cae761-e9ce-477a-9ad2-b9a775f6460a.png)
