### ISSUE TITLE
Label Types in Project Sidewalk: Crosswalks, Pedestrian Signals, and Beyond

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#295]
From user feedback:

![image](https://cloud.githubusercontent.com/assets/1621749/18222269/51d0f272-7160-11e6-942e-fa34b6817e4e.png)

Could have:
- A crosswalk label for crosswalks
- A 'missing crosswalk' label to indicate the need for a crosswalk

**Comment by kotarohara** [comment]
We had a discussion about this. I don't think it should be included as a part of the current interface, which is focused on collecting data for people with mobility impairments. 

But I agree it would be nice to collect crosswalk data along with all the other urban data.

**Comment by jonfroehlich** [comment]
I agree with you. What should we do with feature requests like this? Close them out or keep them open so that we remember them...

**Comment by misaugstad** [comment]
Just putting in my 2 cents as I come across this: I would think this is more easily solved using CV and satellite imagery, and isn't a great fit for our tool.

**Comment by jonfroehlich** [comment]
Why not a fit for our tool?

**Comment by misaugstad** [comment]
Just because it seems like a CV application that wouldn't need much user input. I suppose I may have been taking a slightly more narrow view of the project than I should have. We could easily have a sub-part of Project Sidewalk that does this analysis of satellite imagery and have user validation missions that are used to train the models that identify the crosswalks.

**Comment by jonfroehlich** [comment]
So, I would still advocate trying to include a crosswalk label. In my discussions with DOTs (including DDOT), crosswalks are always mentioned as important assets that need to be tracked and monitored because they wear out due to weathering (i.e., the paint fades away).

Roberto Manduchi and colleagues have done quite a bit of work on using Computer Vision to automatically recognize crosswalks; however, they've found that simply relying on satellite imagery is insufficient due to occlusion from shadows and trees (try this out yourself--load up downtown Washington DC and there are a surprising number of sidewalk features obscured by such things). So, at ASSETS'15, they demonstrated a technique of combining satellite imagery + GSV in their computer vision pipeline:

Dragan Ahmetovic, Roberto Manduchi, James M. Coughlan, and Sergio Mascetti. 2015. Zebra Crossing Spotter: Automatic Population of Spatial Databases for Increased Safety of Blind Travelers. In Proceedings of the 17th International ACM SIGACCESS Conference on Computers & Accessibility (ASSETS '15). ACM, New York, NY, USA, 251-258. DOI: https://doi.org/10.1145/2700648.2809847

There appears to be more recent work on this (haven't read it yet) by other research groups, including:

Koester, D., Lunt, B., & Stiefelhagen, R. (2016, July). Zebra crossing detection from aerial imagery across countries. In International Conference on Computers Helping People with Special Needs (pp. 27-34). Springer, Cham.

Berriel, Rodrigo F., et al. "Deep Learning-Based Large-Scale Automatic Satellite Crosswalk Classification." IEEE Geoscience and Remote Sensing Letters 14.9 (2017): 1513-1517.

Ahmetovic, D., Manduchi, R., Coughlan, J. M., & Mascetti, S. (2017). Mind your crossings: Mining GIS imagery for crosswalk localization. ACM Transactions on Accessible Computing (TACCESS), 9(4), 11.

Berriel, R. F., Rossi, F. S., de Souza, A. F., & Oliveira-Santos, T. (2017). Automatic large-scale data acquisition via crowdsourcing for crosswalk classification: A deep learning approach. Computers & Graphics, 68, 32-42.

**Comment by jonfroehlich** [comment]
I came here to say that I still think we should consider adding a crosswalk label button (maybe as one of the drop down 'Other' options). :)

**Comment by jonfroehlich** [comment]
Ha, was just going to add a new Issue about adding a Crosswalk Label type but then found this. I've been in discussions with some public health researchers interested in exploring pedestrian injuries and fatalities at intersections and one key thing that's helpful here is knowing whether there is a painted crosswalk.

Pinging @misaugstad so he sees this.

**Comment by jonfroehlich** [comment]
And like all other label types, users could rate severity and provide specific tags. Here are some examples:

![image](https://user-images.githubusercontent.com/1621749/96932348-9778c100-1473-11eb-8bf3-a93c9ca91e2d.png)

**Comment by jonfroehlich** [comment]
Coming back to this again, from Shiloh Deitz's work at Univ. of Oregon (she also cites Lobben and Perdue in coming up with this list but I couldn't find underlying reference).

These are accessibility barriers or facilitators that we may want to consider adding either as label types or as tags in future (some we can grab from available data sources, like speed limits):
![image](https://user-images.githubusercontent.com/1621749/107127849-c9b8fd80-686d-11eb-89a7-bdf905ab2ab6.png)

**Comment by jonfroehlich** [comment]
This is the type of categories the Urban Accessibility team in Amsterdam is thinking about and examining:

![image](https://user-images.githubusercontent.com/1621749/124026458-90149a80-d9a6-11eb-934e-8fcf3521b7aa.png)

**Comment by jonfroehlich** [comment]
In Dr. Eisenberg's audit study, they also assessed pedestrian signals and crosswalks. I've attached their codebook, which may help inform our buttons + tags: [AuditTool.xlsx](https://github.com/ProjectSidewalk/SidewalkWebpage/files/7269816/AuditTool.xlsx)

**Comment by jonfroehlich** [comment]
For Professor Quistberg's work in Colombia, they are examining:

![image](https://user-images.githubusercontent.com/1621749/146981373-84ecac53-0131-4b4f-b140-6e9f21b213d7.png)

**Comment by jonfroehlich** [comment]
We now have crosswalks and pedestrian signals! Closing this for now :)
