### ISSUE TITLE
Show /validate label metadata by default in Amsterdam

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2958]
##### Brief description of problem/feature
Folks in Amsterdam have been requesting that the label metadata (severity and tags) that show up on hover just be shown by default without needing to hover. I still don't think that this is the right move for the Validate page in general, but folks in Amsterdam are working with a specific use case where it makes sense. I don't think that it would be too difficult to add in some custom code to make it shown by default in Amsterdam only.

**Comment by misaugstad** [comment]
@jonfroehlich should I turn this into a ticket where the goal is to make it configurable by city, for situations like Amsterdam where we know that users will be highly trained and will want this info? Or should I just add the 'wontfix' tag and close it for now?

**Comment by jonfroehlich** [comment]
I think 'wontfix' for now. I'll do one better and do it for you :)
