### ISSUE TITLE
I Think There Are Likely Bugs Associated With Finishing a Neighborhood

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#296]
I have successfully completed two neighborhoods. In both cases, there were bugs that prevented me from going on the next mission. Now, we are receiving some feedback from users that this is the case.

I would like @manaswis  and @Soben713 to try and complete one neighborhood for testing. As the near the completion of the neighborhood, please start screen recording so we can capture what happens.

We should also discuss a better testing protocol for testing the completion of a neighborhood and the assignment/beginning of a new one.

**Comment by jonfroehlich** [comment]
@Soben713 just ran through a neighborhood quickly (Columbia Heights) on his localhost so he wouldn't have to label anything and could just test what happens when you fully complete the neighborhood.

The video is here:
https://www.youtube.com/watch?v=f95NXOU3dMg

Real action starts here:
https://youtu.be/f95NXOU3dMg?t=2m16s

Some weird things going on:

1. Notice how in this mission complete screen, it says that he has 0.1 miles left to complete the neighborhood
![image](https://cloud.githubusercontent.com/assets/1621749/18227406/2716c584-71f1-11e6-87c0-d12a551c07f9.png)

2. Then he correctly gets the last mission screen, which says audit 100% of a neighborhood:
![image](https://cloud.githubusercontent.com/assets/1621749/18227408/402bf850-71f1-11e6-9753-33d04d043977.png)

3. Then he gets a 'Jumped back to Columbia Heights' pop-up window but notice that it says that he has 2.20 miles to go, when the mission screen said 0.1 miles. This is a bug. @Soben713 and @kotarohara, we need to carefully track this as well since this problem doesn't have its own Issue. We could open one...
![image](https://cloud.githubusercontent.com/assets/1621749/18227412/5d0cbaf4-71f1-11e6-971e-d271ad4066b6.png)

4. Finally, he finishes around: https://youtu.be/f95NXOU3dMg?t=2m46s. By finishes, I mean he gets to 100%... but notice how nothing happens. The mission doesn't end. He is not assigned a new neighborhood. Nothing. And then when he jumps around, he keeps getting the applause (another bug).

![image](https://cloud.githubusercontent.com/assets/1621749/18227417/825c04b8-71f1-11e6-9e91-7833163c0faa.png)

@kotarohara, when you explore #241 tonight, hopefully you can also investigate and fix this bug.

**Comment by kotarohara** [comment]
I guess this is fixed in the PR #312 ?

**Comment by jonfroehlich** [comment]
Will need to be tested and verified by @manaswis and @Soben713 before we close this.

**Comment by jonfroehlich** [comment]
Looks like another user just finished a neighborhood and likely ran into the new neighborhood bug (so they probably couldn't do any further audits for us).

![image](https://cloud.githubusercontent.com/assets/1621749/18388620/4f882192-7670-11e6-9adb-b0f79c057ab1.png)

**Comment by manaswis** [comment]
Yeah, looks good to me.

**Comment by kotarohara** [comment]
Sorry, I clarify. Can I merge this to the `master` or should I merge it to a staging branch (which will be merged later).

**Comment by Soben713** [comment]
I haven't completely tested it yet, but in my opinion you can merge it for now as long as we're not deploying it before public deployment 2.

**Comment by kotarohara** [comment]
I'm merging this into `master`.
