### ISSUE TITLE
Dissenting validations column computation incorrect?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2965]
I'm looking over the "Dissenting Validations Given" column in our new Users API for Oradell ([link](https://sidewalk-oradell.cs.washington.edu/v2/userStats?filetype=csv)), and I think a discovered an error in the calculation.

It looks like folks have a very high rate of dissenting validations. For example, user e86fdc72-c79d-4cdc-b5b2-8ef4859141d2 gave 2186 validations and 1847 of which were supposedly dissenting. Similarly, user 2d7e45f5-3656-4aae-9a09-14addfa80d22 gave 1320 validations with 1086 dissenting. This seems really high. Can you double check that this calculation is correct?

**Comment by misaugstad** [comment]
Oops! It looks like the order of the columns just got messed up! The column names say validations given -> dissenting -> agree -> disagree -> notsure, but the data is ordered as validations given -> agree -> disagree -> notsure -> dissenting

So the second user actually has 1320 validations given, 1086 _agree_ validations, and only 92 dissenting validations. This will be a real quick fix!

**Comment by jonfroehlich** [comment]
Do I earn the "nice diligent" eye 👀 award?!?! 🏆

**Comment by jonfroehlich** [comment]
And thank you for fixing this so quickly! 🙏
