### ISSUE TITLE
Show user "high quality" status on admin dashboard

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2966]
##### Brief description of problem/feature
We have heuristics to determine whether a user is producing high quality data. This is stored in the `high_quality` column of the `user_stat` table. And it's a really important piece of information! Unfortunately, we are not including it anywhere in the admin interface for us to check!

I propose adding to the dashboard for each user (at `/admin/user/<username>`) along with their accuracy rating. We could add it to that table on the Users tab of the full admin dashboard, but that table is already overflowing.

**Comment by jonfroehlich** [comment]
Yes, the Users tab is overflowing... but given that it is and has a scrollbar, I think adding it there is the priority and easiest. I'm also fine with putting it in the dashboard for each user (at `/admin/user/<username>`) but, imo, that's secondary.
