### ISSUE TITLE
Using 'Severity 5' crosswalk label to mean "No Crosswalk"

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2973]
This was bound to happen. Just noting this here so we can discuss how to handle it. When we first talked about adding the crosswalk labels, we discussed having both a "Crosswalk" and "No crosswalk" label but then settled on just having the former (for simplicity) but some users are feeling compelled to mark both...

![image](https://user-images.githubusercontent.com/1621749/180321778-fa6b906f-7433-40c2-994d-d38a6d2876eb.png)

**Comment by misaugstad** [comment]
closing this as part of #2976
