### ISSUE TITLE
Forgot your password: EmailException: Sending the email to the following server failed : smtp-relay.sendinblue.com:587

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2975]
We use a service called sendinblue.com for email, and previously had problems with it https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2817 (due to inactivity of our account).

It looks like this might be happening again. We received an email:

> When she used the current username and password, she still couldn't sign in. When she tried to use "Forgot your password", she got email exception:

```
onError Happened
Execution exception[[EmailException: Sending the email to the following server failed : [smtp-relay.sendinblue.com:587](http://smtp-relay.sendinblue.com:587/)]]
```

**Comment by misaugstad** [comment]
Interesting... Just tried to send a password reset email, and it worked just fine! It looks like this might have been a temporary issue?

For what it's worth, the person that emailed followed up to say that they had been using the wrong email to sign in. Though using the wrong email address doesn't bring up this error message anyway...

Maybe this is an issue that we leave open and continue to monitor.

**Comment by misaugstad** [comment]
As of right now it seems to be working on the test servers, but not the prod servers?? I'm checking the configs right now to see if I can figure out why...

**Comment by misaugstad** [comment]
The configs in our code seem to be set correctly, and I don't see any discernable difference between how we configure the test vs prod servers in the Gitlab repo that would explain this difference. I just emailed UW CS support about it.

**Comment by misaugstad** [comment]
@mechanicjay has fixed this!

I sent him these two error messages I saw in the logs:
>javax.mail.MessagingException: Could not convert socket to TLS
>javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

He responded with
> wonder if the base image is out of date on prod -- if there were some security update that's missing, that could result in cipher errors

He tried updating the base image and responded with this:
>That was, in fact the issue.  After pulling the updated base image and rebuilding the sidewalk image, I was able to successfully send myself a reset email from sidewalk seattle. ... Further, I've updated the build process to check for an updated base image every time it builds, so we shouldn't run into this type of disparity between environments in the future.

Problem resolved, thank you @mechanicjay!
