### ISSUE TITLE
Make Nice Table of Contents with Anchors for FAQ

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#298]
We should have a Table of Contents at top of [FAQ page](http://sidewalk.umiacs.umd.edu/faq) (something like this http://www.cs.umd.edu/~jonf/advising.html).

We could also improve the aesthetic a bit and move the hosting of the videos to YouTube (see Issue https://github.com/ProjectSidewalk/SidewalkWebpage/issues/201)

**Comment by Soben713** [comment]
There are multiple issues here. I'm going to close this and create two separate ones:

1. Adding table of contents
2. Improving the aesthetic

Moving the videos to youtube is already in another issue (#201) as mentioned in the issue, so I'm not creating another one for that.
