### ISSUE TITLE
On leaderboard, have "Want to improve your accuracy?"

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2989]
On the leaderboard page, have something like "Want to improve your accuracy, read our labeling guide or view your recent incorrect labels on your dashboard" with links for each

**Comment by misaugstad** [comment]
Maybe we randomly show either that or what we show right now below the leaderboard?
<img width="639" alt="Screen Shot 2022-08-19 at 12 45 39 PM" src="https://user-images.githubusercontent.com/6518824/185695842-6b218c4a-efbb-45a0-9345-9585a00511a5.png">

**Comment by jonfroehlich** [comment]
I think the "Join an organization" stuff is less of a priority currently, especially since we don't allow self-signups yet

**Comment by misaugstad** [comment]
Sounds good, we can just replace it with that for now :)

**Comment by misaugstad** [comment]
@lindseyehrlich here's your first task! Some notes:
* The leaderboard can be found at /leaderboard
* The text should say "Want to improve your accuracy? Read our labeling guide and view your recent incorrect labels on your dashboard."
* "labeling guide" should link to /labelingGuide
* "your dashboard" should link to /dashboard

Hopefully the way that translations work is relatively intuitive. But if something isn't working how you'd expect, message on the interns channel on Slack!
