### ISSUE TITLE
Each 'Anonymous' User Should Get Their Own Anonymous Identifier

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#299]
Currently, it looks like all anonymous users are grouped together--at least, this is how it looks from the admin interface:

![image](https://cloud.githubusercontent.com/assets/1621749/18232720/03ae72b4-72a4-11e6-8d6b-e42285622efb.png)

If this is indeed the case, I think it should be changed so that every new anonymous user is assigned a new anonymous identifier (e.g., anonymous + random character set). This way we can still:
- Track that individual anonymous user in terms of session length, label types, quality of work, etc.
- Count the number of anonymous users we've had (yes, this is approximate because an anonymous user could come back to the system and get a new anonymous id

These things are important for the research paper that we are trying to write.

@kotarohara, can you comment on the way that anonymous users are handled on the backend and whether it's currently possible to disambiguate every anonymous contributor that we've had so far?

**Comment by kotarohara** [comment]
Users' tasks are tied to their IP address, so I don't think it is necessary to create user id for each new users (and I think it would be even harmful if we create a user for every session).

**Comment by kotarohara** [comment]
To be more specific, that's right that every anonymous contribution is tied to the `anonymous` user, but every task contributed are also tied to IP address, which allows us to (sort of) distinguish who contributed what.

**Comment by jonfroehlich** [comment]
> To be more specific, that's right that every anonymous contribution is tied to the anonymous user, but every task contributed are also tied to IP address, which allows us to (sort of) distinguish who contributed what.

Good, this is, to me, what matters! We will want to analyze individual user behavior as much as possible for our research and to help improve our systems.

**Comment by jonfroehlich** [comment]
And maybe the Admin Interface can possibly breakdown behaviors a bit more based on ip as well... we can discuss.

**Comment by manaswis** [comment]
Edge case: If the user moves from the last place he labeled as an anonymous user. E.g. when I moved from my home to university. So, some double counting for each user will occur, which I guess is expected with IP address.

**Comment by jonfroehlich** [comment]
@kotarohara, why do you think it's harmful if we create a user for every session? Harmful to who?

**Comment by kotarohara** [comment]
Harmful to us, in a sense that we are inserting unnecessary user id/username records to our database.

**Comment by jonfroehlich** [comment]
But only if they click participate, right?

**Comment by kotarohara** [comment]
Yes.

**Comment by jonfroehlich** [comment]
OK, one thing to think about is separating out anonymous in the Admin Interface based on ip address now _(e.g., _ so we have better understandings of time spent on page, # of audits per person, etc.) and___ also trying to present a different representation of 'user' on frontpage since alot of people seem to be auditing anonymously, our user counts are actually higher than what we present.

**Comment by kotarohara** [comment]
Ok. @manaswis , can you open two issues, reference this issue (#299), and close this issue?

1. Top page contributor counter should be increased by the number of anonymous user's IP addresses. This seems like a task for @Soben713 as he is already working on the top page redesign. 
2. (If this is not included in your admin update issue) update the admin interface so that it shows user activities per anonymous user IP address.

**Comment by manaswis** [comment]
Just saw this comment. Yeah sure. Will do.

**Comment by kotarohara** [comment]
@manaswis , can you open the two issues as described above and reference this issue (#299) from them?

**Comment by manaswis** [comment]
Made two issues that address the above two feature requests: #322 and #323. Referenced them in each for more information.

Should I close this?

**Comment by kotarohara** [comment]
Great! Thank you @manaswis . I've closed the issue. We can continue the discussion in #322 and #323 .
