### ISSUE TITLE
Update labeling guide to emphasize to label every curb ramp (not just deficient curb ramps)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2992]
During our Oradell mapathon, someone suggested that they were only labeling curb ramps that were deficient rather than all curb ramps.

They suggested updating our labeling guide. I did double check the labeling guide, and I agree that we could open with "Label every curb ramp regardless of whether there are problems"

![image](https://user-images.githubusercontent.com/1621749/185265718-fc9240c0-2b05-460b-8938-a0c07df5e02a.png)

**Comment by misaugstad** [comment]
@tanayaxsharma can you add that as a sentence at the end of that intro section that ends with "or vice versa (ADA)"?
