### ISSUE TITLE
Description in the Feedback window should be updated

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#30]
Jon's comment: I think the feedback box should be about anything not just the streets/sidewalks at the current location.

![feedback](https://cloud.githubusercontent.com/assets/612263/13297567/f7242718-db00-11e5-9319-b92ec2ad7599.png)

**Comment by kotarohara** [comment]
It now says: "Any thoughts? Found something confusing? Spotted a bug? Send us comments!"

**Comment by jonfroehlich** [comment]
Sounds great. Thanks Kotaro!
