### ISSUE TITLE
Remove labels validated as "incorrect" from our API

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3003]
##### Brief description of problem/feature
A cursory look at our code just now indicates that we probably are not filtering out labels from high quality users where their labels are marked as incorrect from other users' validations.

I think that when we started out, I vaguely remember us discussing that it was something that we would want to do in the future, but we wanted to see how the data looked in production after a bit... And then we forgot to make a Github issue for this...

This should be a quick fix that we can implement now! If we want to be more careful about removing labels, we could consider only excluding labels if they have at least two validations saying that the label is incorrect? No matter what, we would only remove ones where it's marked as incorrect via majority vote.

Related to #1668, though this one is much more simple and should be done ASAP.

##### Potential solution(s)
I think that this is as simple as adding the following filtering line to `getUserLabelsToCluster()` in `UserClusteringSessionTable.scala`:
```
if _lab.correct.isEmpty || _lab.correct === true
```

Or in the case where we require at least two negative validations...
```
if _lab.correct.isEmpty || (_lab.correct === true && _lab.disagreeCount > 1)
```

**Comment by jonfroehlich** [comment]
Great memory and diligence Mikey. Can you help me understand what you mean by these two sentences?

> If we want to be more careful about removing labels, we could consider only excluding labels if they have at least two validations saying that the label is incorrect? No matter what, we would only remove ones where it's marked as incorrect via majority vote.

I do think we should be "more careful" in respecting high quality user labels (yes, everyone makes mistakes but high quality users are, I think, less likely to make a mistake than a low quality or average quality validator).

**Comment by misaugstad** [comment]
So we are already fully excluding labels from users marked as "low quality". And the easiest thing I was suggesting we do, is to also exclude labels from "high quality" users if they have been validated as "incorrect" through majority vote. However, this would mean excluding labels from "high quality" users even if they've only received one "incorrect" vote and nothing else, so we could consider giving the benefit of the doubt and requiring at least two "incorrect" votes in addition to there being more incorrect than correct votes.

**Comment by jonfroehlich** [comment]
Yah, at risk of overcomplicating our algorithm here and special casing "high quality" users, I agree that we should require at least two "incorrect" votes.

Longer term, we may want to do something more sophisticated that is a weighted vote system based on a user's quality
