### ISSUE TITLE
Create a Table of Contents for the FAQ Page

### ISSUE THREAD

**Issue by Soben713** [ProjectSidewalk/SidewalkWebpage#301]
Originally in #298, by @jonfroehlich:

> We should have a Table of Contents at top of FAQ page (something like this http://www.cs.umd.edu/~jonf/advising.html).

**Comment by jonfroehlich** [comment]
Can I see a screenshot of the new page?

**Comment by Soben713** [comment]
Sure.

![image](https://cloud.githubusercontent.com/assets/1576529/18254809/ade28d6c-736f-11e6-866b-4d75c1e6fcb8.png)

**Comment by jonfroehlich** [comment]
We will probably want to organize these into topics/categories at some point (just like http://www.cs.umd.edu/~jonf/advising.html). Should probably create a new ticket for this.

**Comment by Soben713** [comment]
@jonfroehlich I agree. That makes it much easier to find a question, specially if there are too many.
