### ISSUE TITLE
Make sure that manually "excluded" data is excluded everywhere

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3013]
##### Brief description of problem/feature
I added a column to the `user_stat` table awhile back called `exclude_manual`, which is meant to be one level more extreme than just marking users as `low_quality=TRUE`. This is meant for users who have done some auditing in bad faith (there was once a user that just put 100 curb ramp labels on a single pano) and other small edge cases where we really don't want to see a user's data in our system. Here's how I'm thinking the differentiation should look, including which have been implemented thus far:
Low quality
- [x] Labels deprioritized for validation
- [x] **Only labels validated as "correct" show up in Gallery** -- right now they are being completely excluded
- [x] **Only labels validated as "correct" show up in the API** -- right now they are being completely excluded
- [x] Labels hidden by default on LabelMap
- [ ] Their validations are deprioritized when determining label correctness (covered in #2755)
- [ ] Their validations are deprioritized for showing on other users' recent mistakes list (covered in #3001)
- [x] User still shows up on leaderboard

Excluded
- [x] **Labels never included in validation**
- [x] **Labels never included in Gallery**
- [x] No labels show up in the API
- [x] **Labels never included on LabelMap**
- [x] **Their validations are not used when determining label correctness**
- [x] **Their validations are not shown on other users' recent mistakes list**
- [x] User is not shown on leaderboard

I really want to go through all of the points marked in bold ASAP. Those are all going to be pretty straightforward to update, and each update should either improve the quality of data we show or reduce unnecessary validation work for our users.

The two points that are more complicated to implement already have associated tickets that we can loop back to later!

**Comment by jonfroehlich** [comment]
Can we centralize this via utility functions so that we have one and only one place to make these queries (which will make our system both easier to use and easier to update in the future).

**Comment by misaugstad** [comment]
Very interesting... Not exactly, but I think that we can get A LOT closer to this than where we're at right now. Since you can compose queries using Slick, we should be able to create a subquery that is used in most places. There will be gaps, because some locations we want to remove data and some we want to simply deprioritize. And there are other edge cases where we need to use plain SQL instead of Slick. And we need to keep most of this in SQL/Slick for the sake of performance (and not running out of memory by loading all our data in Scala).

But overall, this is a great point. These changes are being made in enough places that we should definitely be consolidating. We've done something similar elsewhere, where we've made a specific subquery for all of the labels, excluding deleted and tutorial labels, and we use that almost everywhere. We should be able to do something similar here!
