### ISSUE TITLE
When you vote on LabelMap, the underlying table should update in real-time

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3017]
When you vote Agree, Disagree, Unsure on LabelMap, the underlying modal table that counts these should update in realtime. This also helps provide useful feedback to the user that their vote was counted.

https://user-images.githubusercontent.com/1621749/187799412-7ca04aa5-a2d2-40b1-99eb-f7b972911722.mp4

**Comment by misaugstad** [comment]
What should we do for users whose validations we are ignoring?

**Comment by misaugstad** [comment]
>What should we do for users whose validations we are ignoring?

This isn't something that's super common right now, so we can ignore it right now. It might become an issue later though

**Comment by dylanbun** [comment]
@misaugstad just read through the comments, are we just taking validations from any user (including those we are ignoring?)

**Comment by misaugstad** [comment]
Yep!
