### ISSUE TITLE
Prioritize validations of recently added labels (to help fill in leaderboard)

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3018]
##### Brief description of problem/feature
We have our weekly leaderboard, which is really nice for mapathons! But we don't explicitly prioritize recently added labels on Validate, which means that the accuracy section of the weekly leaderboard is often barren! Below is a screenshot @jonfroehlich sent from our current mapathon in Amsterdam.

![image](https://user-images.githubusercontent.com/6518824/187958055-f10aecc3-9adf-48ed-9da9-b17bb5b78181.png)

##### Potential solution(s)
I think that we could add at least a small weight towards recent labels in our prioritization! Since this is pretty explicitly for the leaderboard I think we can just it binary: slightly increase probability of showing a label if it would count towards the weekly leaderboard.

Getting recent labels validated during mapathons should also help with rapid feedback on your auditing that shows up on your user dashboard!

**Comment by jonfroehlich** [comment]
Ah yes, that second point is crucial and perhaps more of a reason than any to do this:
> Getting recent labels validated during mapathons should also help with rapid feedback on your auditing that shows up on your user dashboard!

**Comment by misaugstad** [comment]
Okay, switching this to just checking if the label was added in the last week for performance reasons! The gymnastics we do with timezones and such to make sure the stats reset at midnight Pacific slow the validation query down by about 17% (90 ms). If we just do the simple check for the label being added in the past week, it's slowed down by only 4% (20 ms). Seems worth the speedup IMO.
