### ISSUE TITLE
Improve FAQ Page's Aesthetic

### ISSUE THREAD

**Issue by Soben713** [ProjectSidewalk/SidewalkWebpage#302]
Originally in #298:

> ... We could also improve the aesthetic a bit ...

**Comment by jonfroehlich** [comment]
Can I see a screenshot?

**Comment by Soben713** [comment]
This is not fixed yet.

**Comment by Soben713** [comment]
Miss-clicked the close button.

@jonfroehlich Can I close this issue now?

**Comment by jonfroehlich** [comment]
Looks good!
