### ISSUE TITLE
Close context menu in tutorial when label needs to be deleted

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3027]
![image](https://user-images.githubusercontent.com/1621749/190514751-6964a85a-c761-470d-a727-7cc7f33ea24b.png)

**Comment by jonfroehlich** [comment]
I was also slightly confused by the instruction because when I first received it, there were two X's (one on the pop-up dialog and the other on the label itself):

![image](https://user-images.githubusercontent.com/1621749/190514870-f2661983-1306-48c6-b4cd-6ac6ea3b659d.png)

**Comment by misaugstad** [comment]
>I always label curb ramps at the bottom-middle... but tutorial doesn't seem to like this

As of #3210 this is now fixed. For some reason the ideal location for most of the labels was set above the thing being labeled. I slightly adjusted them to be more in line with what we'd expect, so this now works.
![Screenshot from 2023-04-19 13-12-10](https://user-images.githubusercontent.com/6518824/233189593-c082a35d-5e09-407d-a78f-a02a04f6229a.png)

>I was also slightly confused by the instruction because when I first received it, there were two X's (one on the pop-up dialog and the other on the label itself):

I think that we should probably automatically close the context menu if the label is in the wrong place and we want the user to remove it. This deals with there being two X's, plus we just don't need to show this extra stuff on the screen when we want them to delete it anyway. Going to change the title for the issue to go after this.

**Comment by misaugstad** [comment]
Maybe we even prevent the context menu from opening at all in this case?

**Comment by jonfroehlich** [comment]
This seems right to me:

> I think that we should probably automatically close the context menu if the label is in the wrong place and we want the user to remove it. This deals with there being two X's, plus we just don't need to show this extra stuff on the screen when we want them to delete it anyway. Going to change the title for the issue to go after this.
