### ISSUE TITLE
Possible to make the navigation message + arrow flash here?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3028]
Typically, when we offer an instruction like this in the tutorial we either use a flashing yellow/white arrow or we flash the UI element itself. We do neither here but I think we should.

1. Can we flash the navigation arrow? If not, can we put a flashing pointing arrow to it
2. Can we flash the "Go straight" UI element?

![image](https://user-images.githubusercontent.com/1621749/190515469-44c847a9-bf35-4b43-b106-685049f81121.png)

**Comment by misaugstad** [comment]
Yep, we should be able to flash both! The arrow will probably need to be done in a different way than the other elements on the page. For all the others I think that we are changing the background color. We'd have to do something slightly different bc I think that these are part of an svg that's drawn on the screen. Shouldn't be too bad though.

**Comment by misaugstad** [comment]
For whoever works on this, I recommend going into the browser dev tools to mess around with the arrow manually. Then you can implement that in code. The rest of the code that flashes, it's referred to as "blinking" throughout the code.
