### ISSUE TITLE
Support Ctrl-A in Description Textbox in Pop-up Severity Rating Dialog Box

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#304]
Low priority but since we don't (yet) support auto-complete in the description textbox, would be nice to support ctrl-a so user could quickly copy text to be used in future description textboxes.

![image](https://cloud.githubusercontent.com/assets/1621749/18255034/e1716420-7372-11e6-90df-7e790a013242.png)

**Comment by jonfroehlich** [comment]
This is based on a suggestion from a user. Full thread here:

![image](https://cloud.githubusercontent.com/assets/1621749/18255263/e7672b3c-7375-11e6-89f9-950062efe704.png)

The response:
![image](https://cloud.githubusercontent.com/assets/1621749/18255266/f4997d82-7375-11e6-8591-6aee58ca36c6.png)

**Comment by jonfroehlich** [comment]
@sagec108: can you please support ctrl-a in the description box (to select all text). This should be an easy task for you. Let me know if you don't understand the request.

**Comment by sagec108** [comment]
I will look into it after I fix the admin playback page. Thanks!
