### ISSUE TITLE
Get PanoId and LabelId from Sidewalk Gallery

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3044]
From https://github.com/ProjectSidewalk/SidewalkWebpage/issues/248, I know how to get the panoId from the audit and validation page:

**audit page:**
pano_id: `svl.panorama.getPano();`
street_edge_id: `(svl.taskContainer.getCurrentTask()).getStreetEdgeId();`

**validate page:**
pano_id: `svv.panorama.getPanoId();`

But how can I get the PanoId and LabelId from Sidewalk Gallery? Perhaps this is related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/340 where we want some of this info in a pop-up dialog; however, I've never seen Sidewalk Gallery mentioned here. 

I use Sidewalk Gallery more than any other tool for working on the Labeling Guide and providing examples of tags, etc.

**Comment by misaugstad** [comment]
>Get PanoId and LabelId from Sidewalk Gallery

As of right now, you can use the browser console by just inspecting the GSV image. The image HTML element has an ID that looks like `id="label_id_123"`. And the image src has the `pano_id` in it.

>Perhaps this is related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/340 where we want some of this info in a pop-up dialog; however, I've never seen Sidewalk Gallery mentioned here.

Not sure why it's never mentioned in the ticket, but we are adding this to Gallery as well! Explore, Validate and Gallery should all have this info, and I want to include `label_id` in the Validate and Gallery versions. So you shouldn't have to use the browser console for much longer!

**Comment by misaugstad** [comment]
Oops, forgot to send the screenshot I took that shows what I'm referring to in the console!

![gallery-browser-console](https://user-images.githubusercontent.com/6518824/194907526-41c72fb2-9170-46fa-9132-ad59da9ea222.png)

**Comment by misaugstad** [comment]
Closing via #3050
