### ISSUE TITLE
Rename /audit to /explore

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3045]
Since renaming the Audit page to the Explore page awhile back, we've changed the naming basically everywhere except for the URL! We should probably change the URL too :) But of course /audit should continue to redirect to /explore for the forseeable future.

**Comment by jonfroehlich** [comment]
This is probably done automatically by the Scala template you're using on this page but make sure the title is updated too:
![image](https://user-images.githubusercontent.com/1621749/195341611-bd1f23fc-cde6-428e-8314-6661201a9af3.png)
