### ISSUE TITLE
Remove Pedestrian Signal severity histogram from Admin page

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3057]
##### Brief description of problem/feature
We added a histogram for severity ratings in Pedestrian Signal labels, but we removed severity from that label type shortly after. We just need to remove that histogram from the admin page now too!

![Screenshot from 2022-10-21 11-53-06](https://user-images.githubusercontent.com/6518824/197269103-56d9d0e3-bc9d-4e6c-9c3e-db8f421cebb3.png)

**Comment by sneh721** [comment]
I have removed the histogram, and the relevant statistics (average and standard deviation) for Pedestrian Signal labels from the admin page. There was another table called "Validations Per Label Type" which had some some statistics for Pedestrian signals which I removed as well. Let me know if I should put any of this code back. 

Before: 
<img width="792" alt="image" src="https://user-images.githubusercontent.com/84554565/219541776-1ad795e9-edc9-4677-a8ab-4620c17a5180.png">
<img width="988" alt="image" src="https://user-images.githubusercontent.com/84554565/219545409-d9324f64-164f-4d02-b683-5e88ccf4f607.png">

After: 
<img width="804" alt="image" src="https://user-images.githubusercontent.com/84554565/219559655-c517aa80-7606-4244-baa8-9b1efd89e52f.png">
<img width="989" alt="image" src="https://user-images.githubusercontent.com/84554565/219544042-2580a14c-82af-4570-b600-07993ffa70dd.png">

Can I make a pull request?

**Comment by misaugstad** [comment]
You should keep the Pedestrian Signal line in the "Validations Per Label Type" chart. We didn't remove the Pedestrian Signal label completely, only the severity rating for it.

Could you also increase the size of the severity histograms? Now that we don't need a 4th one on a line, we should be able to make them bigger again!

**Comment by sneh721** [comment]
Thanks for the feedback! I have put back the Pedestrian Signal line in the "Validations Per Label Type" chart. 
<img width="988" alt="image" src="https://user-images.githubusercontent.com/84554565/221086463-779a3382-5e46-4bac-938c-76a83970f913.png">

I have also increased the size of histograms:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/84554565/221087045-1c0263f2-fe37-422b-ac38-b77aab2701e6.png">

**Comment by misaugstad** [comment]
It looks like we may as well make these a bit larger! I don't think that we are worried about taking up too much vertical real estate on the admin page, so feel free to make them take the same width as the text!

**Comment by misaugstad** [comment]
Then feel free to make a PR!
