### ISSUE TITLE
Lots of auditing happening outside the Harvey boundary in Chicago

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3063]
![image](https://user-images.githubusercontent.com/1621749/199771900-109ac07b-7e82-44c4-b001-bafb3ad5b31f.png)

https://sidewalk-chicago.cs.washington.edu/labelMap

**Comment by misaugstad** [comment]
@jonfroehlich that's part of the Hazel Crest neighborhood, which we temporarily turned off about a week ago. But turning off those neighborhoods doesn't hide the data from LabelMap. So those labels shouldn't be a problem unless you're seeing labels that were added less than a week ago!

**Comment by jonfroehlich** [comment]
Ah, gotcha. Thanks for clarifying!
