### ISSUE TITLE
Maybe more positive framing than "compete against teammates"

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3064]
Perhaps we switch this to "Join an organization and work together as a team to map and assess sidewalks" or something

![image](https://user-images.githubusercontent.com/1621749/200030754-bb052c8d-c5e1-4edd-ab87-785fbcb21fd6.png)

**Comment by misaugstad** [comment]
In a new issue (#3138) @sneh721 asked
>I wanted to know what the relevant Spanish translation for this text would be. For reference, the original Spanish text is "Únete a una organización para competir contra tus compañeros!"

@sneh721 You can use Google Translate for now (for both Spanish and Dutch)! I collect all those translations that we make using Google Translate, and then I will send a big list of things to translate to our partners occasionally!

**Comment by misaugstad** [comment]
Oh, and I'll add instructions for this to the [process for contributing code wiki page](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Process-for-contributing-new-code) for the future!

**Comment by sneh721** [comment]
Thanks. These are the changes in English, and the corresponding changes have also been made in Dutch and Spanish. Can I make a pull request?
Before:
![Before](https://user-images.githubusercontent.com/84554565/219268902-8f24dcb6-aa57-4901-8105-cabe8db7203a.png)
After:
![After](https://user-images.githubusercontent.com/84554565/219269555-95fab233-5c9d-4e65-a760-59deb89f423d.png)

**Comment by misaugstad** [comment]
Yep, go for it!
