### ISSUE TITLE
Bug: accuracy in the `user_stat` table is `null` when accuracy is 0% or 100%

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3069]
##### Brief description of problem/feature
Not totally sure why it's happening yet, but I noticed during the recent Chicago mapathon that users with 100% or 0% accuracy actually have their accuracy listed as `NULL` in the `user_stat` table! Hoping it's an easy fix!

**Comment by jonfroehlich** [comment]
Interesting! I wonder why this is... 

Great catch @misaugstad. Looking forward to hearing about what you find out!
