### ISSUE TITLE
Store Sound/Mute Option in User Profile

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#307]
![image](https://cloud.githubusercontent.com/assets/1621749/18258040/23c685ca-739c-11e6-8e22-3f9c87ac18fe.png)

**Comment by kotarohara** [comment]
The comment says:

> Can the sound feature be included in the dashboard/profile also? I don't want to hear the sounds, but every time I reload the page or come back to the website, I have to click the sound button. It'd be better if it could remember that I don't want any sounds.

An easy way to achieve this would be to store the setting in a cookie or browser storage (which is wrapped by `TemporaryStorage.js`) and reloaded on the browser refresh. I think this is a low priority work though.

**Comment by jonfroehlich** [comment]
I agree that it's a low priority but could be a nice entry point for @Soben713 to start contributing to the code.

**So two possible solutions:**
1. Store in cookie or browser storage (lightweight solution) -- this would also, I believe, work even if you are anonymous and never sign in
2. Store in backend per user (heavyweight solution) -- this would only work if user creates account and signs in

**Comment by Soben713** [comment]
I added it to Public Deployment v2 and will look into it.

**Comment by jonfroehlich** [comment]
@Soben713, I would prioritize the Other issue that I assigned you in the Issue tracker first.
