### ISSUE TITLE
Keyboard shortcuts have been enabled on the audit page

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3073]
##### Brief description of problem/feature
WASD keyboard shortcuts have somehow been enabled on the Explore page... This is a huge problem, because we use S as a shortcut for Surface Problems and W as a shortcut for Crosswalks! When I try to add a surface problem label, I get moved backwards! Furthermore, if you open the context menu and then add the label on a different pano, it breaks the tool and you need to refresh the page...

This should likely just be a fix in a config, shouldn't be difficult!

**Comment by jonfroehlich** [comment]
Ha, interesting. Looks like WASD is enabled in Google Street View now by default (and I think WASD is the common keyboard commands for navigation in first-person shooters). ⌨

Should def be fixed!
