### ISSUE TITLE
Region ID not shown on GSV info popup on Explore

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3087]
##### Brief description of problem/feature
As seen below, we aren't showing the Region ID on the Explore page in the popup on the GSV info button.
![Screenshot from 2022-12-02 15-51-49](https://user-images.githubusercontent.com/6518824/205410545-eed41d2e-14bf-43b0-9319-e7d72a15df3c.png)

##### Potential solution(s)
I think this is because we are using `svl.taskContainer.getCurrentTask().getRegionId()` instead of `svl.neighborhoodContainer.getCurrentNeighborhood().getProperty('regionId')`. Should be an easy fix!

**Comment by kevinjtwu** [comment]
Fixed
![image](https://user-images.githubusercontent.com/106000281/216452832-c1549647-6bbb-4ea4-b153-cb887cbf0e50.png)
