### ISSUE TITLE
Signaling in UI that comments are actually seen

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3096]
It would be nice to signal in some way that your comments can be viewed by the original labeler on their dashboad. At the minimum, just small text (or maybe a pop-up) that says that... This would both hopefully motivate people to fill this out and to further surface how the comments will be used.

![image](https://user-images.githubusercontent.com/1621749/207096917-e08304ef-6334-44fe-8f2e-b08a06d48b91.png)

**Comment by misaugstad** [comment]
I like the idea of showing a popup the first time that a user tries to submit a Disagree validation without a comment!

**Comment by dylanbun** [comment]
@misaugstad @jonfroehlich in terms of sequence, how would we want this to flow?

1. User selects disagree without comment -> popup -> next validation
or
2. User selects disagree without comment -> popup -> still on same validation -> regardless of what happens, next validation

**Comment by jonfroehlich** [comment]
So, I was thinking something very lightweight that indicates that comments are viewed on the dashboard. Maybe it's a small font text beneath the text field with a hyperlink to the user's own dashboard?

I think the more important ticket for this is here: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/3113
