### ISSUE TITLE
Show mission screens after 'mission complete' screens in validations

### ISSUE THREAD

**Issue by hoominchu** [ProjectSidewalk/SidewalkWebpage#3107]
##### Brief description of problem/feature
When a user selects 'Validate more labels' after completing a validate mission, they are directly taken to the next validate mission. 

##### Expected behavior
The users should be shown the mission screens (tutorial) for the next mission **if** it is a different one.

##### Current behavior (add screenshots if applicable; check terminal & browser console for errors)
After clicking on the 'Validate more labels' button below the user is directly taken to the next mission.
![image](https://user-images.githubusercontent.com/8168506/211452693-f44577c3-3be5-46ad-a8b8-285777a2bf78.png)

##### Steps to reproduce
1. Start and complete a validate mission.
2. Click on the 'Validate more labels' button. 
3. See that the mission screen (tutorial) is not

**Comment by jonfroehlich** [comment]
This "Validation Mission Screen" itself also needs a full redesign so that might also impact the flow of this and how we design the "start" screen of the next validation mission..

![image](https://user-images.githubusercontent.com/1621749/214349448-0439d983-b8b9-4adb-8ef4-0a124b4afa6a.png)

**Comment by jonfroehlich** [comment]
Hey @misaugstad and @hoominchu, if it's not too much trouble. I think a quick fix for this would be what @hoominchu recommends: if the next mission is a different label type, we should show the new "tutorial" start mission screen for that label type.

We can and should, of course, also consider how to make the 'Mission Complete' screen better. 

I know Liga is planning on doing some more validations of their labels soon, so might be worth prioritizing this fix if it is not too much trouble.

**Comment by hoominchu** [comment]
Sure thing. I'll try to fix it this week.

**Comment by jonfroehlich** [comment]
Just wanted to float this to the top of the queue as currently the user is only given the valuable "mission start" screen only the first time they start validations...
