### ISSUE TITLE
Add Mandarin translations

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3123]
##### Brief description of problem/feature
Our partners in Taiwan have just provided us with Mandarin translations for our interface. It's time to add them in and see how the interface looks!

**Comment by jonfroehlich** [comment]
And here's the translation file:

[Translation (Traditional Chinese, Taiwan).zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/10678934/Translation.Traditional.Chinese.Taiwan.zip)

Inside this zip, you'll find:
![image](https://user-images.githubusercontent.com/1621749/217352220-066aad68-5e06-4232-a8be-ff7ab9413f7b.png)

**Comment by jonfroehlich** [comment]
Here's the updated translation file with `messages.en` translated (they had previously missed this file before).

[Project Sidewalk Translation (Traditional Chinese, Taiwan).zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/10808303/Project.Sidewalk.Translation.Traditional.Chinese.Taiwan.zip)
