### ISSUE TITLE
Validate mission start screens messed up when there are no labels to validate

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3126]
##### Brief description of problem/feature
We used to have a screen that was shown on Validate immediately upon loading the page if there were no labels available to validate that would direct them to the Explore page to collect more data. This only really happens when a server is very new and not much data has been collected. With the new mission screens, we forgot to check for this edge case, so [in Taipei](https://sidewalk-taipei-test.cs.washington.edu/validate) we just see this:

![Screenshot from 2023-02-07 18-08-33](https://user-images.githubusercontent.com/6518824/217410823-c4d83ce2-8254-45a4-b4f6-9c708be56724.png)

This page is still available on mobile though!

**Comment by jonfroehlich** [comment]
Can confirm that our system crashes on this. In preparation for our Auckland phone call, I was doing validations--and it looks like I ran out of labels to validate! 😂

![image](https://user-images.githubusercontent.com/1621749/222261958-ccdba10e-7505-4595-a19c-ac7b268175c1.png)

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'remove')
    at SVValidate.js:2488:49
    at streetview.js:65:132
    at streetview.js:97:267
```

Then I tried it in a new window and got this:
![image](https://user-images.githubusercontent.com/1621749/222262521-fe65275e-7025-4d87-b397-5bef5ca4e63f.png)

@misaugstad and I think this might be because I validated all labels in Auckland and there is nothing left

**Comment by misaugstad** [comment]
We didn't remove the code for this, we just broke it somehow :grin: I think it has to do with how we used to use the same HTML elements for the mission start screen and the screen where we say that there are no more missions left. So we were just editing the text on that screen.

Now what we probably need to do is when there are no labels to validate is to hide our usual mission screen, and show the old one instead (with the correct text). You can see a pic below of what it looked like at one point in time:
![image](https://user-images.githubusercontent.com/25534091/53224677-71f63d00-362a-11e9-8c2d-090db6312442.png)

Given that very few users will ever see this screen, I'm find with using the ugly version that we have ;) Most of the code for it is in `ModalNoNewMission.js`!

**Comment by misaugstad** [comment]
And you should be able to temporarily edit the back-end code to return no labels to the front-end to test this temporarily!

We should make sure that this works when there are no labels to start, _and_ if you finish one mission and aren't able to do another one after it because we're out of labels!

**Comment by jonfroehlich** [comment]
On the new Keelung server, I was able to get past the initial mission screen but then the validation UI loaded and looks like this:

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/b43ce8d0-bb92-4a20-993e-d47d6522fbee)

**Comment by kevinjtwu** [comment]
I think I've replicated the issue by editing the backend to return a null JsValue
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/106000281/41b1fe51-dc9e-4525-a4d1-3eb68629451a)

**Comment by kevinjtwu** [comment]
What should we do on mobile? The no new missions screen asks the user to explore, but we can't explore on mobile. 
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/106000281/995571bd-be70-484a-bef8-3fff1b18b32a)

**Comment by kevinjtwu** [comment]
> What should we do on mobile? The no new missions screen asks the user to explore, but we can't explore on mobile. ![image](https://user-images.githubusercontent.com/106000281/269772316-995571bd-be70-484a-bef8-3fff1b18b32a.png)

Currently, clicking on 'Start Exploring' redirects the user to the Seattle server to validate labels.

**Comment by misaugstad** [comment]
It looks like at the bottom of `ModealNoNewMission.js` the test for that was set with this line
```
uiModalMission.closeButton.html(i18next.t('mission-complete.no-new-mission-button') + ` Seattle, WA`);
```
