### ISSUE TITLE
Spanish Translation for text

### ISSUE THREAD

**Issue by sneh721** [ProjectSidewalk/SidewalkWebpage#3138]
##### Brief description of problem/feature
I have changed the text "Join an organization to compete against your teammates!" to "Join an organization to and work together as a team to map and assess sidewalks!"

I wanted to know what the relevant Spanish translation for this text would be. For reference, the original Spanish text is "Únete a una organización para competir contra tus compañeros!"

**Comment by misaugstad** [comment]
@sneh721 For questions about a specific issue, you can just add comments on that issue thread! Just moved your comments over to the initial thread: #3064
