### ISSUE TITLE
Jumped dialog message shown immediately after a new mission is assigned

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#314]
From PR #312:

**Issue**: After completing the old mission (or neighborhood), and moving on to a new one, the jump dialog message immediately shows up after we dismiss the new mission text. See example below.

Old neighborhood: Deanwood
Newly assigned neighborhood: Mount Pleasant. 

After the old mission is complete, here are the series of screenshots:
<img width="1223" alt="mission_complete" src="https://cloud.githubusercontent.com/assets/2873216/18300179/defd42ea-7494-11e6-86e9-b78818b695a3.png">

The newly assigned neighborhood is Mount Pleasant. Missed taking the screenshot of the new mission text. After I click OK on the mission text pop up, the following screen is shown.

<img width="1229" alt="jumped to deanwood" src="https://cloud.githubusercontent.com/assets/2873216/18300177/defb9a44-7494-11e6-9e36-73bb90073645.png">
The pop up dialog box shows message about jumping out of old [here, Deanwood] neighborhood immediately after I was assigned a new neighborhood.
**This is a bug.** 

This bug occurs even between two missions (old and new) in the same neighborhood i.e. when moving from old mission to new mission, the jumping out of neighborhood is displayed after the new mission was assigned (#275).

This doesn't happen everytime but it does occur sporadically.

**Comment by kotarohara** [comment]
@manaswis Can you provide more detail to this issue?

**Comment by manaswis** [comment]
Updated the issue description.

**Comment by kotarohara** [comment]
Thanks.
