### ISSUE TITLE
Consider routing users down both directions of a street

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3140]
Based on Yochai's Slack post, we may want to consider _not_ marking a street segment complete until it's been audited in both directions (either by same user or other users).

For small, narrow streets like we find in residential neighborhoods, it's relatively easy to audit both sides of the road (especially with proper training); however, it still requires diligence to remember to look backwards once every few "moves" forward to check for problems that are visible in only one direction.

For larger streets, it's sometimes difficult to see the other side of the road. Here, hopefully we would already route people down both sides of the street (assuming we have the OSM dataset + GSV imagery capture). But even then, we could route them in both directions for each side of the street.

Thoughts?

**Comment by jonfroehlich** [comment]
Ha, we already have this here: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2108

**Comment by misaugstad** [comment]
Moved your comments over to #2108 !
