### ISSUE TITLE
Adding accuracy in admin dashboard view of a user

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3143]
Would it be possible to show more accuracy related stats for a user in the admin dashboard view of them. Mostly curious about overall accuracy (based on validations) but would love this split by label types too.

![image](https://user-images.githubusercontent.com/1621749/220417865-b8f9a03d-d883-4b8c-9a52-2b9b3ec316ee.png)

Would also be useful to show recent examples of incorrect labels with the image (like we have in the regular dashboard view).

**Comment by misaugstad** [comment]
Closing in favor of #3070!
