### ISSUE TITLE
Missing OSM street geometry in Seattle

### ISSUE THREAD

**Issue by crescendochu** [ProjectSidewalk/SidewalkWebpage#3144]
##### Brief description of problem/feature
I found some discrepancies between the dataset retrieved from our /v2/access/score/streets API call and the street geometries obtained from OSM using OSMnx for Seattle. Looks like those way_types outside primary, secondary, tertiary and residential aren’t being captures in our database. (Screenshot below, left is OSMnx and right is our database)
![missing-osm-gepmetry](https://user-images.githubusercontent.com/60413478/220758773-e40f1464-f0d2-4ae1-9175-53985a0b541e.jpg)

**Comment by jonfroehlich** [comment]
Yes, we do filter down to specific `way_types` but one that you've identified that we might clearly want to add is `living_street`; there could also be others.

@misaugstad, as we setup new cities, we should revisit the list of which way_types we incorporate by default...

**Comment by misaugstad** [comment]
Yes, awhile back I went through the different street types and added in 'unclassified', 'pedestrian', and 'living_street' in our newer cities. Unfortunately I didn't record exactly when I started doing that :disappointed: But it won't be too difficult to figure out.

The issue for adding these missing streets is #2547 so I'm closing this as a duplicate :ok_hand:
