### ISSUE TITLE
Getting validated labels in gallery even with "validationOptions=unvalidated" option

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3149]
![image](https://user-images.githubusercontent.com/1621749/221329026-c069afdd-4b9f-4c28-a99d-8781ebd484c0.png)

Try to recreate here: https://sidewalk-chicago.cs.washington.edu/gallery?labelType=NoCurbRamp&validationOptions=unvalidated

**Comment by misaugstad** [comment]
Ahh, I see. That's because "unvalidated" actually means either "no validations" or "the same number of agree and disagree validations". Need to discuss options for how to resolve that discrepancy!

**Comment by jonfroehlich** [comment]
Hmm, maybe we add a fourth option just above "unvalidated" to be "unsure." And that's both the (1) labels that have just unsures; and (2) labels that have same number of agree and disagree validations.

Then we reserved unvalidated for truly those labels without validations. Thoughts?

**Comment by misaugstad** [comment]
I like it!

**Comment by misaugstad** [comment]
Closing via #3220
