### ISSUE TITLE
Top nav bar redesign

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3152]
Once in a while, we have to rethink the top nav bar as we add in new tools/functionality. With RouteBuilder, I think we should again revisit this. 

Here's what I would propose:
![image](https://user-images.githubusercontent.com/1621749/221361885-e5d84a9a-b2b0-4c9d-88e4-3445ff4cdd66.png)

Should become:

Explore | Validate | How to Label | Tools | API | City | User | Language

Then within Tools, we have RouteBuilder, LabelMap, Gallery, Results Map, and Leaderboard

We save space by transforming "Start Exploring" -> "Explore" and "Start Validating" -> "Validate". We could also add in our lil explore icon and validation icons there (e.g., the spyglass icon, which we all seem to like).

Update: adding word 'navbar' here to make this ticket easier to find.

**Comment by misaugstad** [comment]
I like it! Thoughts on switching Tools and API around so that all the drop down menus are together on the right-hand side? So it would look like:
Explore | Validate | How to Label | API | Tools | City | User | Language

**Comment by misaugstad** [comment]
Oh I actually might like tools next to the User dropdown? Since we also want people to be using the User Dashboard! Alternatively, API could just be in the Tools menu.
