### ISSUE TITLE
Remove 'missing crosswalk' from 'other' label type

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3158]
From Slack:

> The Other label type doesn't have any specific use. It is really just there in case a user sees something that they think should be documented that doesn't have a label type, hence the name "Other". We do have two tags for it: 'no bus stop access' and  **'missing crosswalk'** (which we should probably remove now that we have a Crosswalk label)

**Comment by misaugstad** [comment]
I believe that if we just add it as an "excluded" tag to the `cityparams.conf` file for every city, that should hide it from the UI without deleting any old data! Pretty easy :)
