### ISSUE TITLE
Label context menu disconnected when placing first label

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3166]
##### Brief description of problem/feature
I've been noticing lately that the context menu is sometimes placed too high above the label, such that it is disconnected from the actual label icon! I just tried to test it out now, and it looks like it's happening on the first label that I place when I load the page -- same happens if I open the menu for a previously placed label instead of adding a new one. After that, the context menu seems to be in the correct place.

Not sure if it's an issue when we put the context menu below the label, it's a little harder to tell if that's incorrect with a quick eyeball test.

https://user-images.githubusercontent.com/6518824/223880024-bcda63c9-3eb2-45be-abdf-bbb5f0c85dc1.mp4

**Comment by jonfroehlich** [comment]
Strange. Thanks for flagging.
