### ISSUE TITLE
Incorrect links in navbar

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3169]
##### Brief description of problem/feature
Lately, I've seen maybe 2-3 times, that the link in my navbar will all be set to the same thing. Each time I can remember, it was to the /audit/street URL. It looks like every link in my navbar is being set to that URL. But when I refresh the page, the links are set correctly again... I haven't found a way to reproduce it yet. You can see in these images that I'm hovering over different buttons in the navbar, but in the bottom-right, you can see the URL for every button is set to "/audit/street/9578".
<img width="1273" alt="Screenshot 2023-03-13 at 11 03 04 AM" src="https://user-images.githubusercontent.com/6518824/224796989-63c49f70-9928-4629-a5cd-9503cbfeb642.png">
<img width="921" alt="Screenshot 2023-03-13 at 11 03 36 AM" src="https://user-images.githubusercontent.com/6518824/224797010-f92635cf-b2bd-404e-8269-9f6c3482cce8.png">

##### System info (OS, browser, city, and local/prod/test)
I've seen it in Chrome on both Linux and Mac. Definitely on prod, but I believe others as well.

**Comment by misaugstad** [comment]
Just figured out what's going wrong here! The following line in `Admin.Panorama.js` is the troublemaker:
```
$("a").attr("href", "/audit/street/" + self.label['streetEdgeId']);
```

This code is used when we try to show a popup for a label in LabelMap or any of the Admin pages. If there is no GSV imagery available, we are setting _every_ link on the page to bring you to audit that street! Let's make it so that we are only modifying the "Explore the street" link ;)

**Comment by justyeethan** [comment]
Is there a route or example that I can reproduce the issue? It seems like all the links are working for me, but I used my personal account for testing the commit.
![Screenshot 2023-04-19 at 9 23 01 AM](https://user-images.githubusercontent.com/61468547/233138774-5b29e5ec-e475-4439-9897-b52b8e8d6b6b.png)

**Comment by misaugstad** [comment]
The easiest way to test is to go to `/labelMap`, then click on a label to bring up the popup, but you'll need to look at a label with no GSV imagery (the label will be sorta grayed out). When that popup shows up, the links are changed.

I think I gave you a database dump for Seattle, which means that there is a TON of data, and LabelMap takes forever to load. So you should probably just add a query parameter to look at a specific neighborhood to make testing easier: `/labelMap?regions=5`

**Comment by justyeethan** [comment]
Alright, just tested to see if everything worked, and it does:

After clicking a label to bring up the popup, it keeps all the links intact:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61468547/233202095-6066a934-3049-436e-abab-76aaf2a337a8.png">

The "Explore the Street" also functions as it normally would
<img width="997" alt="image" src="https://user-images.githubusercontent.com/61468547/233202310-6ee7bb5f-0d24-44e0-9a34-af81717fc778.png">

**Comment by misaugstad** [comment]
Great! And just to confirm, were you able to replicate the issue on the develop branch?

**Comment by justyeethan** [comment]
Yes!
