### ISSUE TITLE
Visualize more route info in the minimap

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3170]
I'm moving part of https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2108 here as https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2108 started to branch into two separate issues.

In https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2108#issuecomment-1435703678, I wrote:

> It would also be helpful to know if, on our backend, we have routes for both sides of the street (in each direction). For example, in this case, the street is quite wide and it's hard to see the left side but auditing the right side is just fine. As a labeler, I'm wondering if I need to strain to look at the other side or if I will also be routed down the other lane in the opposite direction (e.g., if that route data exists).
>
> A possible solution is to show some indication on the minimap of all routes in our database (e.g., in light gray):
![image](https://user-images.githubusercontent.com/1621749/219875165-776f5d0d-0278-4e8d-b453-1fd60ac54a9e.png)

Then in https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2108#issuecomment-1444511734, I wrote:
> This came up again today. I think at the very least we can draw all potential routes on the minimap (say, in gray) so that (at least well-trained) auditors know if there are bidrectional routes on each side of the street available.
>
> So something like this (very drafty mockup but you get the idea):
![image](https://user-images.githubusercontent.com/1621749/221294930-05e04c89-0611-47e8-b1d6-39eaf8687c32.png)
>
> The original:
![image](https://user-images.githubusercontent.com/1621749/221295013-c24f183b-97bc-493c-9a1d-7e1033e3db9c.png)
>
> From this Slack conversation:
![image](https://user-images.githubusercontent.com/1621749/221295091-2ed9612f-de4e-4b71-b6c8-f5988912f802.png)

**Comment by jonfroehlich** [comment]
This also came up a few times recently with Devon who most recently wrote on Slack:

> So, just started another auditing route and came across the same issue I was having with the first route I audited in DuPage County. When I selected the route from the route builder it showed a single line to select, but here it is orienting me to the right of the street center line, making it difficult to see the other side of the street. When I come across a midblock intersection, I should be able to navigate over to capture the midblock intersection on the other side of the street and I guess I will just move down the side I wasn't able to see very well to make sure I didn't miss anything. Any other recommendations when this happens? I know I used the street center line shapefile and made sure it was the same coordinate system as PS/Google Maps

![image](https://user-images.githubusercontent.com/1621749/225067042-7357e2e3-d89d-44ef-812a-9fb8713b27b4.png)

I still think my idea of visualizing available routes in the minimap would help with this. In my mock below, I added gray visualizations of route availability (but also agree that more could be done to make this clear)...

![image](https://user-images.githubusercontent.com/1621749/225067319-c5de21e3-5ace-4550-924d-70b23b57bab9.png)

**Comment by misaugstad** [comment]
Yep I agree that showing all the routes on the mini map would help with this confusion!

What Devon and I have been dealing with lately is an issue where OSM does not have the road split into two separate segments, but GSV does have imagery on each side of the street. In this case, the ideal would be to have users go down the street twice, looking at one side of the street each time (we talk about something like that in #2108). It's possible that we could determine which roads are 4 lane roads, tell users to look at a specific side of the street, and then try to push them towards that side of the street in the background if GSV has imagery on both sides... Nontrivial engineering-wise, there is a lot we would have to figure out, but I think it's possible.

Starting with showing the streets on the mini map would be great though! Though it isn't necessary for the validation study, since Devon is picking the routes through RouteBuilder where they can see all possible streets.

**Comment by jonfroehlich** [comment]
Great, I think we are aligned... except for:

> It's possible that we could determine which roads are 4 lane roads, tell users to look at a specific side of the street, and then try to push them towards that side of the street in the background if GSV has imagery on both sides

You mentioned engineering limitations, I worry more user confusion. :) I just don't see this as a worthy trajectory for us: a lot of work for little payoff. 

I think the message should just be: do the best you can no matter what street you are on in auditing both sides of the road. (But I could be wrong!)

**Comment by jonfroehlich** [comment]
This is a good example video that helps really highlight the problem. I don't know if I'm supposed to try and look at the other side of the street here (which is very far away).

https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/330d88c6-5997-4149-8e59-eef4cafa3ae4
