### ISSUE TITLE
Record some pano metadata in a new table

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3171]
##### Brief description of problem/feature
We have some data that is about the panorama that is stored in the `label` table, namely: `panorama_lat`, `panorama_lng`, `photographer_heading`, and `photographer_pitch`. These are still stored in the `label` table instead of the `gsv_data` table because they will sometimes change over time (we aren't totally sure why), so it made sense to just record the new value whenever we add a new label there. In addition, we were only recording entries in the `gsv_data` table when users added a label to a pano, so we weren't missing out on any data.

But as a part of #956 we are now adding entries to the `gsv_data` table for any pano that a user visits, even if they didn't place a label. Since the metadata above is only stored when a label is added, we won't have it for images with no labels. This is especially problematic to the lat/lng of the pano, which I'd consider to be incredibly important!

##### Potential solution(s)
There are three different ways we might deal with this data, given that it changes (slightly) over time:
1. Add it to the `gsv_data` table, using the values that we find when we visit the pano for the first time. This is the easiest and fastest.
2. Add it to the `gsv_data` table, updating the values whenever they change. This is relatively easy, though it does add more database operations to an already very database-heavy process.
3. Create a new table where we record this data so that we can keep a full history of what the metadata looked like over time. This makes some queries more difficult to code, though it's not prohibitive!

Given that we almost never use this data, and the fact that the metadata we're talking about changes by such small amounts, I lean towards options 1 or 2.

And my best guess is that the metadata changes because Google is making corrections, which leads me to choosing option 2.

**Comment by jonfroehlich** [comment]
Thanks Mikey. I'm fine with you recommendation of 2. Couldn't we also use our logging table to log when we notice that they change (so at least we have a record?)

**Comment by misaugstad** [comment]
>I'm fine with you recommendation of 2

Sounds good, let's go with that!

>Couldn't we also use our logging table to log when we notice that they change (so at least we have a record?)

Yeah I think that's fair and easy enough to add as well! We'll probably just record that data in our logs whenever we run into it, not necessarily worrying about if it's changed or not. But we will then be able to see if it's changed over time through database queries :+1:

**Comment by misaugstad** [comment]
To summarize:
1. Move the `panorama_lat`, `panorama_lng`, `photographer_heading`, and `photographer_pitch` columns to the `gsv_data` table.
2. Update those values whenever we return to that pano again (if they change).
3. Whenever we enter a pano, log those values in the `audit_task_interaction` table.
