### ISSUE TITLE
Gallery/Validate icon outlines are square in Safari

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3176]
##### Brief description of problem/feature
The Gallery label icon outlines in desktop Safari are square instead of circular 🥴 Not great! Let's fix up that CSS, huh?
<img width="1429" alt="Screenshot 2023-03-17 at 6 04 04 PM" src="https://user-images.githubusercontent.com/6518824/226075073-4e418087-f844-433c-bdf5-4f68d24cac51.png">

##### System info (OS, browser, city, and local/prod/test)
MacOS Safari, prod and test. Not an issue in Chrome or Firefox. Also not an issue on mobile Safari.

**Comment by misaugstad** [comment]
@justyeethan I'd prioritize this over #2677!

**Comment by misaugstad** [comment]
@justyeethan and I actually are not seeing this anymore :joy: @dylanbun @jonfroehlich @hoominchu I know all of you have Macs, could you check the Validate and Gallery pages to see if you see this issue??

**Comment by dylanbun** [comment]
@misaugstad Yup got it to appear. See attached. Safari Version: Version 16.3 (18614.4.6.1.6), macOS: 13.2.1 (22D68)
<img width="1120" alt="Screenshot 2023-05-18 at 12 29 09 PM" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/56641275/4ea37e98-0b60-4cbc-9185-530d050e87cf">
<img width="721" alt="Screenshot 2023-05-18 at 12 29 14 PM" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/56641275/340af818-b9ad-4cc1-b6c1-53d33be4d94c">

**Comment by misaugstad** [comment]
Okay thank you!

And it looks fine for me, Safari version 16.4 (18615.1.26.11.22), macOS 13.3 (22E252)!

Just checked the [release notes for Safari 16.4](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes#CSS). Under the CSS section, I see:
>Added support for outline following the curve of border-radius

That REALLY sounds like what's going on here :joy: @dylanbun when you get a chance, could you update Safari and see if that fixes it? If so, we can really confirm that it's just that Safari finally added support :)

**Comment by misaugstad** [comment]
@dylanbun has confirmed that the browser update solved it.
