### ISSUE TITLE
Can't complete tutorial due to pop-ups

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3187]
The training popup is conflicting with the user's ability to interact with the actual PS UI in the tutorial.

This happened to nearly every single student at Denny Middle School, which I thought was due to their laptop setup. But we just received an individual report that this is also happening "in the wild." So, this needs to get fixed...

>Good morning!
I'm going through your awesome tutorial here https://sidewalk-chicago.cs.washington.edu/audit .
I'm using a macbook pro, chrome.
I'm unable to move the training window in order to rate the quality of a curb access on the third example (double curb).
Here's what I mean (if I want to give this a 1 or 2 rating, I can't...at least I can't figure out how to because I'm unable to move either window):

![image](https://user-images.githubusercontent.com/1621749/227784370-1b65e131-83ec-4e14-bb6d-604fad2dbce7.png)

**Comment by misaugstad** [comment]
We have one report where we were able to get their computer specs:
>Browser: Firefox 111.0 (64-bit).
>Screen resolution: 1920x1080.
>Laptop: ROG Zephyrus G14 GA401QM_GA401QM.

I believe that we can reproduce the issue on most resolutions, actually! Though it will be a lot more common on lower res screens. We wanted to make the area where you can add the label relatively large to make it easy on users, but that also means less possible real estate for the info windows to never block important UI elements!

**Comment by misaugstad** [comment]
Great idea, I'll get to work!
