### ISSUE TITLE
As a Potentially Motivating Feature... Show Map and Completion Rates of DC Neighborhoods on Frontpage

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#319]
As a potentially motivating feature... show map and completion rates of DC neighborhoods on frontpage and allow users to select neighborhoods that they think need help.

(This is complementary to our automatic assignment method, which would still work when users just click participate--which will likely be the far more common case).

**Comment by misaugstad** [comment]
This is covered again in issue #697 and resolved in PR #692
