### ISSUE TITLE
Requesting for dataset dump

### ISSUE THREAD

**Issue by lisamalani** [ProjectSidewalk/SidewalkWebpage#3196]
##### Brief description of the problem/feature

How can I access the already annotated dataset?
I am working on a classification model that will automate the process of classifying the street views based on the four classes that Project Sidewalk is currently annotating their dataset on, i.e., missing sidewalks, curbs, obstacles, and surface problems. I have been using the Project Sidewalk API to download the raw csv for different cities they have already mapped (Seattle, Newberg, Oradell, etc.), which will be the label output and GSV API to download the street view images that will be used as input to the model. However, I am facing challenges getting the Project Sidewalk csv for different cities. For e.g., for Oradell, I got only 99 data points, but on the website result map, it looks like there are significantly more points.

##### Potential solution(s)

Is there a way I can access the dataset dump for all the cities that have been covered so far?

**Comment by misaugstad** [comment]
Hi @lisamalani would you be able to add the URLs you're using to get data from the APIs here? You should be able to get all of the data from the API. If you send the URLs you used, I can either direct you to a different API or we will know which ones need to be fixed!

**Comment by lisamalani** [comment]
Sure! Here it is:

```
extension_lookup = {
    "seattle": "sea",
    "pittsburgh": "pittsburgh",
    "columbus": "columbus",
    "oradell": "oradell",
    "newberg": "newberg",
    "mexico": "cdmx",
    "mex_uni": "cdmx",
}

base_uri = f"https://sidewalk-{extension_lookup[city_name]}.cs.washington.edu/"
```

**Comment by lisamalani** [comment]
Hi @misaugstad Did you figure out why I might be getting fewer data points? Or if there is a faster way to access the dataset dump? Thanks!

**Comment by lisamalani** [comment]
Lol! I work at odd hours of the night, so that might be it. I will try again. Thanks!

**Comment by lisamalani** [comment]
Tried again, and it worked! Thanks!
