### ISSUE TITLE
FAQ ToC is empty

### ISSUE THREAD

**Issue by Soben713** [ProjectSidewalk/SidewalkWebpage#320]
The table of contents panel in FAQ page is currently empty (as shown in the screenshot). Note that it is supposed to be dynamically filled with a JS file that should be in `sidewalk.umiacs.umd.edu/assets/javascripts/FAQ/build/FAQ.js`. Since the source JS file is accessible from [http://sidewalk.umiacs.umd.edu/assets/javascripts/FAQ/src/tableOfContents.js](http://sidewalk.umiacs.umd.edu/assets/javascripts/FAQ/src/tableOfContents.js) I suspect this is a deployment issue and will be resolved if the JS files are concatenated on the server.

![image](https://cloud.githubusercontent.com/assets/1576529/18424910/50de002a-7882-11e6-9859-9b4352cd8f91.png)

**Comment by Soben713** [comment]
Assigning it to @kotarohara since I do not have access to the server right now.

**Comment by kotarohara** [comment]
Fixed.
