### ISSUE TITLE
Add tag for utility panel / manhole cover

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3205]
##### Brief description of problem/feature
Recently we've been trying to label utility access panels / manhole covers as low severity surface because they can be bumpy, and they can become slippery when wet. Given how common of an occurrence these are, we should add a tag for it if we want people to label them.

One thing we need to think about is what name we give to the tag. There are different terms for a manhole cover. And I'm not sure that everyone will understand what a 'utility panel' or 'utility access panel' means.

Here are some pics of what we've been labeling:
![Screenshot from 2023-04-13 10-44-48](https://user-images.githubusercontent.com/6518824/231842381-1ae5c421-f802-4483-bba4-5f3e0ce2cb59.png)
![unnamed](https://user-images.githubusercontent.com/6518824/231842397-140eb238-15d4-4886-8537-957548d33890.png)

**Comment by jonfroehlich** [comment]
Good idea. I like 'utility panel' — seems generic enough!

**Comment by misaugstad** [comment]
Let's add this in every city for now

**Comment by misaugstad** [comment]
Closing via #3218
