### ISSUE TITLE
Request for German language

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3219]
From our Zurich partners:

> We have started the recruitment phase for data collection. The majority of our participants are/will be German speaking. Is it possible to add German to the language list of the Project Sidewalk tool? 😬 As of May, I will have a research assistant who can help translate if needed.

**Comment by misaugstad** [comment]
Here are the translations to incorporate
[projectsidewalkzurichtranslatedfiles.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/11627937/projectsidewalkzurichtranslatedfiles.zip)

**Comment by jonfroehlich** [comment]
Here's the messages file.

[messages_translated.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/11676898/messages_translated.zip)
