### ISSUE TITLE
Show anonymous contributors count on the landing page 

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#322]
Parent Issue: #299 

To better track the number of users interacting with the website, the above issue talks about tracking anonymous users. It would be a cool measure to show on the landing page; we show the 'total #contributing users' instead of just showing the total of #registered users.

Related issue: #323. Using the API that will be written in #323.

**Comment by jonfroehlich** [comment]
@manaswis, isn't this done now and can be closed?

**Comment by manaswis** [comment]
Yes, this is done. Was just waiting for a confirmation before closing. This works. Closing it.
