### ISSUE TITLE
Show user activities per anonymous user IP address in the admin interface

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#323]
Parent Issue: #299 

Currently, the interface just shows the activities of registered users. Add a table that shows the activities by the anonymous users (based on their IP address).

For the individual anonymous user, the table should show in terms of session length (time spent on page), label types, quality of work, # of audits per person etc.

TODO: Figure out what the table should contain.

**Comment by manaswis** [comment]
This is included in the latest version. Enhancements to the table have their own issues. Closing this issue.

**Comment by manaswis** [comment]
Point that came up while working on #364 and discovering the bug #403 is that how do we count the number of anonymous users (also, displayed on the landing page): 
- should it just be users who visited the site, or 
- should it be users who have *at least completed one task* (current way of doing it) or 
- should it be contributing users i.e. users who have *at least added a label*

What do you think should be the right way to do it?

**Comment by jonfroehlich** [comment]
Didn't we already discuss this and decide on the second bullet? I still think this is the right approach. I'm not sure we can trust users who only came into the system and provided a few labels but did not finish their first mission (or 'road segment'--whichever it is).

One other thing: how many users have completed one task but not added a label?

**Comment by jonfroehlich** [comment]
Update, since @misaugstad just referenced this in https://github.com/ProjectSidewalk/SidewalkWebpage/issues/342. Task here is/was defined as completely at least one street segment (@manaswis could correct me if I'm wrong).

**Comment by misaugstad** [comment]
@jonfroehlich Having worked with the code yesterday, I can confirm that this is the case.

**Comment by jonfroehlich** [comment]
And kudos @misaugstad for sleuthing all the way back through closed issues. Ah, what fun it is to join a giant, multi-year project! :)
