### ISSUE TITLE
Add widget to download data on API page

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3237]
For each subsection of the API page (Access Attributes, AccessScore: Streets, and AccessScore: Neighborhoods), it might be useful to have an interactive widget to support downloading all data for that city.

I propose a dropdown menu to support filetype (csv, shapefil, geojson) and then a download button next to it.

This could be helpful for our non-technical advocates to download data to then transmit to their city government or analyst colleagues.

**Comment by misaugstad** [comment]
Agreed, also related to #2754 amd #3236
