### ISSUE TITLE
Show speed limit somewhere on Explore/Validate page

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3249]
##### Brief description of problem/feature
Google has a [speed limit API](https://developers.google.com/maps/documentation/roads/speed-limits) that we can request using lat/lngs. This could be nice to add, maybe in the top-right corner? We initially thought of this as useful when determining whether or not to include Missing Curb Ramp labels. We could include it on the Validate page as well, specifically when looking at Missing Curb Ramp labels.

I could also see this being useful in the context of crosswalks or pedestrian signals in the future if we start labeling their absence!

Looking at the API, they have a parameter that we can use to get the response in either MPH or KPH!

**Comment by jonfroehlich** [comment]
Thanks for this idea Mikey! Would this work internationally? Looks like it may cost per API call?

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/0b4128d4-e273-4baf-802c-f0d54af88781)

**Comment by misaugstad** [comment]
Unclear whether we should constantly be requesting, or trying to check all of the streets at once and saving it, or requesting at streets as we get to them, and then saving it at that time. Not sure what the cost of the API would end up being right now.

**Comment by jonfroehlich** [comment]
> check all of the streets at once and saving it

I'm all for this!

Great re: coverage.

**Comment by jonfroehlich** [comment]
I like this. And sounds good to me. I've traveled to many countries across the world (5 of 7 continents) and speed limit signs are reasonably similar. 

I think white rounded rectangle with the following format would work well:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/db181b32-6baf-4379-8044-380b977a72bb)

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/5f59a21d-3be5-4c99-9c10-b798784a0543)

**Comment by misaugstad** [comment]
OOPS so sorry @justyeethan it looks like we are not actually allowed to use Google's Roads API (and therefore speed limits API).  We would need some sort of "asset tracking" contract with Google [link](https://developers.google.com/maps/asset-tracking-plan).

>On June 3, 2019, a new Asset Tracking plan was launched on Google Maps Platform. This plan is only available for customers with large fleets (thousands of assets) and a specific use case. ... Notice: The Speed Limit service is available to all customers with an [Asset Tracking](https://cloud.google.com/maps-platform/asset-tracking) license

The documentation doesn't make it clear enough that you can _only_ use the API if you are part of an asset tracking license, but that is indeed the case.

I am looking into alternative data sources.

**Comment by misaugstad** [comment]
@justyeethan can you try out this website to see if we can get the info we need from it? It's called [HERE](https://www.here.com/get-started/pricing). It looks like we'd want the "Map Attributes API". It sounds like you can create a free account and get 2.5k free monthly requests without providing payment info. But lmk if there's an issue there!

If that doesn't work, then we can just plan to include whatever data we can get from OSM when creating new databases. Mostly likely the way we'll do that is:
1. You can submit a PR with the speed limit UI, but we just hide the speed limit part of the UI if we don't have speed limits available. You'll add a column to the database that will be null everywhere; we can just put in a few dummy numbers for testing.
2. The next time I create a database for a new server, I'll save the speed limit data and update the documentation for the future.
3. Once I've done it once for a new city, I'll set up a process to fill in the data for previous cities.

**Comment by jsomeara** [comment]
@misaugstad I'm currently experimenting with using OSM's overpass API to get speed limit info through the `maxspeed` tag.

I was thinking of making a request on every street view "movement" to fetch the speed limit at the current coordinate point, then displaying it. I realize that this might be too request heavy or slow. What do you think?

**Comment by misaugstad** [comment]
I think it's worth a shot! One thing you could also try to reduce the number of requests is to try to request using the osm_way_id of the street that the user is on. If we get a response for it, we can use that speed limit for the entire street that the user is on. But I wouldn't worry about making that improvement until we have it working by requesting at every point.

I don't think that you should need to make a new endpoint in Project Sidewalk, though. You should be able to just query the Overpass API using JavaScript, right?

**Comment by jsomeara** [comment]
> I don't think that you should need to make a new endpoint in Project Sidewalk, though. You should be able to just query the Overpass API using JavaScript, right?

I was worried I might run into CORS issues but upon further inspection, it seems to be okay :)

**Comment by misaugstad** [comment]
Oh and you may find some HTML/styling for the speed limit signs in #3300! I ended up taking the speed limit stuff out of this PR, so you won't see it in the Files Changed tab, but you should be able to find the code in the commit history.

**Comment by jsomeara** [comment]
Made a PR: #3611
