### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3251]
Our collaborators in Zurich just created German translations for us.

[projectsidewalkzurichtranslatedfiles.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/11625955/projectsidewalkzurichtranslatedfiles.zip)

**Comment by misaugstad** [comment]
Closing as duplicate

**Comment by misaugstad** [comment]
Duplicate of #3219 that is!
