### ISSUE TITLE
Add basic moderation for validation comments

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3252]
##### Brief description of problem/feature
I lost track of the comment, but I think I saw one along the lines of "what the hell was this person thinking?". Given that we now show validation comments on LabelMap and (more importantly) User Dashboards, at some point it would be good to add in some really basic moderation filters for the text that we show to users.

I've seen some weird, incoherent expletives thrown at us through the feedback form or survey, which is fine. But I'd rather not have our users dealing with that!

That being said, I think that so few people look at the validation comments right now, that it doesn't really matter yet. But I'm logging it now for the future!

##### Potential solution(s)
Even just a filter that checks for some key words/phrases and flags them as comments not to show would be good.

Maybe even a little flag icon next to comments so that users can mark them as inappropriate.

I also look through most comments every month or so, so if we just have a flag in the database for comments not to show, I can mark those when I see them.

**Comment by yeisenberg** [comment]
Nice! what do you think of the standardized text + dropdowns for the comments? would that help with this issue too?

**Comment by jonfroehlich** [comment]
I think Dropdowns (or other closed-form selections) are a good approach to this problem. I believe we have this idea somewhere else as a ticket (yes, it's here: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/3113)

**Comment by misaugstad** [comment]
Are we then talking about removing the free form text box for comments entirely?

**Comment by jonfroehlich** [comment]
Yes, I think so. We can have an 'Other'. But can keep this closed form. And closed form data is far easier to analyze. We can take the common mistake analyses that we've now done multiple times (from Project Sidewalk CHI'19 to Chu's more recent work).

Note that I am generally not a fan of "Dropdown" UIs as I would prefer something that has higher visibility (e.g., such that all possible selections are shown at once).

**Comment by yeisenberg** [comment]
Got you, interesting. Also this is the link to the language we used in my class: https://docs.google.com/document/d/1pxpuDLuidE4aponNKh89OksSqwilA7fxttC2tx4AMF8/edit?usp=sharing

Perhaps it can be used to just show the feedback for the label that was used?

**Comment by misaugstad** [comment]
Cool, I'll close this in favor of #3113 then. We can also have the Other include an open-ended description that we don't show to other users if we want. We can just keep that data internally in case it's helpful for figuring out new options to add!
