### ISSUE TITLE
Expanding to new city: Teaneck, NJ

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3254]
We are working with our Oradell team on expanding into nearby Teaneck, NJ. In the fall, we plan to work with a local high school team for auditing. So, we should:

* Figure out the boundary data for Teaneck (where did we get it for Oradell, do you remember?)
* Decide how/if to split it up. I found this ward and election [district map here](https://www.teanecknj.gov/media/Residents/Maps/Teaneck%20Election%20District%20Map%209-9-20.pdf). This would work well but it's a PDF (note, we don't need the parcel data, just the geographic breakdown of districts/wards)

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/27f021a5-f3cc-4e74-b263-62c1156f7226)

I also found a [GIS parcel viewer of Bergen County](https://www.co.bergen.nj.us/planning-engineering-regional-planning-transportationgeographic-information-system-gis) but this doesn't seem to have exactly what we need.

Thoughts @misaugstad?

**Comment by jonfroehlich** [comment]
Somewhat relatedly, the Oradell folks are also interested in us mapping the sidewalks on all of the county roads in Bergen County.

> This [list of county roads](https://en.wikipedia.org/wiki/List_of_county_routes_in_Bergen_County,_New_Jersey) in Bergen County is useful. Hopefully, we can extract those roads from OpenStreetMaps for our tool.

**Comment by jonfroehlich** [comment]
Here's the CADD data file for Teaneck sent to us from a teanecknj.gov employee who said:

> NAD 83 coordinate system was used for this map. This map can easily be used as a base map for ARCGIS.

[Teaneck Overall Map (all sheets).zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/12072853/Teaneck.Overall.Map.all.sheets.zip)

**Comment by jonfroehlich** [comment]
OK, the Teaneck folks just emailed to say the want to host a mapathon on August 14th... is this doable? It strikes me as challenging given all that we have going on (but perhaps possible if the boundary data and backend setup isn't too difficult).

@misaugstad, have you had a chance to check the CADD file for Teaneck?

**Comment by yeisenberg** [comment]
Can ask Devon tomorrow. She may be able to lead that. is this for training the future trainers of other raters?

**Comment by jonfroehlich** [comment]
I converted the .dwg file to ArcGIS shape files using https://www.gisconvert.com/ (I also tried https://mygeodata.cloud/conversion but our file size of 7MB exceeded the free conversion threshold). 

The tool outputted three layers: lines, points, and polygons, which I then visualized in QGIS. To me, these do not look like neighborhood boundaries:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/2ac1bc09-feda-4ab4-bd28-2879b8fdf282)

Here's just the polygons and line layers—looks more like commercial/residential real-estate plots vs. neighborhood boundaries 
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/88b435ff-5faf-49e9-9766-6cd2d78cfe84)

So, I don't think the data is what we want.

Here's the converted DWG to shape files.
[teaneck_converted_dwg_to_shapefiles.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/12234442/teaneck_converted_dwg_to_shapefiles.zip)

**Comment by jonfroehlich** [comment]
Teaneck folks got back to us with a new dataset (this time as a .shp file) but it's still not exactly what we want.

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/70379a9b-3e7c-4c57-a71b-a5a35763b3d0)

Here's the data file:
[Teaneck_Parcel_2023.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/12240771/Teaneck_Parcel_2023.zip)

I emailed Teaneck back and they said we will have to go through Bergen County. I asked for a contact there.

**Comment by jonfroehlich** [comment]
A Teaneck city official just sent us to this site (https://www.teanecknj.gov/teaneck-maps) but it only has PDFs:

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/bbd5c2af-c13d-43db-9dd4-dc874f041d85)

**Comment by jonfroehlich** [comment]
Just asked said Teaneck official for more computer-readable formats like ArcGIS shape files or GeoJSON....

Essentially, we want a shape file of all the Teaneck districts in this PDF: https://www.teanecknj.gov/media/Residents/Maps/Teaneck-Polling%20locations%202022.pdf

**Comment by misaugstad** [comment]
It sounds like our current contact doesn't have anything like this, and is directing us to the county. Note that in the worst case, I can try to hand draw the district boundaries in QGIS using the PDF map as a reference.

**Comment by jonfroehlich** [comment]
Yah, I was thinking similarly given that we did something like that in Oradell.

Could you use the GIS data that we received to get the Teaneck outer boundary and then hand slice in the "district" boundaries (more or less).

**Comment by misaugstad** [comment]
I don't specifically remember if the data on the boundary of the city was provided an easily accessible, but I assume that it was. There is also probably an OSM dataset with the city boundary data, though it may be outdated. I've used [this site](https://osm-boundaries.com/) in the past to get the boundary of the city.

**Comment by jonfroehlich** [comment]
How easy would it be to just extract the boundary data from this? https://github.com/ProjectSidewalk/SidewalkWebpage/issues/3254#issuecomment-1662259185

**Comment by jonfroehlich** [comment]
Update. With the help of the Teaneck MIS Technical Assistant, I think we have what we want from: https://njogis-newjersey.opendata.arcgis.com/datasets/764362ac87254d77b976a080f926a6fe_0/explore?filters=eyJNVU5fTkFNRSI6WyJUZWFuZWNrIFRvd25zaGlwIl19

Screenshot below:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/d56c88c4-9922-41ea-8554-cc618a68cc2f)

Now we just need to have names for them (as naming them D12, D18, etc. doesn't seem very user friendly)

**Comment by jonfroehlich** [comment]
OK, I was able to load [this data](https://njogis-newjersey.opendata.arcgis.com/datasets/764362ac87254d77b976a080f926a6fe_0/explore?filters=eyJNVU5fTkFNRSI6WyJUZWFuZWNrIFRvd25zaGlwIl19) into QGIS and confirm it's what we want.
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/0a2994d1-3cf8-4c51-9484-9829c2b76f79)

Here's boundary data in GeoJSON for the Teaneck election districts (compressed in zip format):
[Teaneck Only - Election_Districts_for_New_Jersey.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/12285275/Teaneck.Only.-.Election_Districts_for_New_Jersey.zip)

Here's all of the election districts in New Jersey (also GeoJSON but compressed with 7-zip format to get under 25MB):
[Election_Districts_for_New_Jersey Full.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/12285279/Election_Districts_for_New_Jersey.Full.zip)

You can get the original files, including ArcGIS shape files, from:
https://njogis-newjersey.opendata.arcgis.com/datasets/764362ac87254d77b976a080f926a6fe_0/explore?filters=eyJNVU5fTkFNRSI6WyJUZWFuZWNrIFRvd25zaGlwIl19

**Comment by misaugstad** [comment]
Thank you!!

**Comment by misaugstad** [comment]
closing via #3367
