### ISSUE TITLE
Need prettier CSS for mission screens outside of English language

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3257]
##### Brief description of problem/feature
The CSS looks a little bit rough in languages that are more verbose than English for our new mission start screens. And they are so pretty, I want them to be pretty in other languages! There are two examples below, but it's consistent across Spanish, Dutch, and German, and for all the different label types on both Validate and Explore.
![Screenshot from 2023-06-14 14-15-27](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/3c5160d5-7559-4d0d-a92f-c36fac56c214)
![Screenshot from 2023-06-14 14-15-33](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/eb98c071-522e-4957-9f5f-5b583eb16a49)
![Screenshot from 2023-06-14 14-15-47](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/8270b65e-d976-4b9e-87df-7e9b0cdc94f2)

**Comment by hoominchu** [comment]
Just saw this issue. I am not sure what approach is being explored currently but we can have a function that adjusts the font size to fit it on the label by checking if the 'container' element has a scroll (horizontal and vertical) and if yes, reduce the font size by 0.05px (or some other small value). Repeat until there is no scroll or we hit a minimum font value.

I can help provide more details if needed.

**Comment by jonfroehlich** [comment]
I don't think we should change the font size necessarily. To me, it's purely about spacing. See the screenshots above.

**Comment by hoominchu** [comment]
Ah okay. We can add a 'locale' class to the mission screens div (maybe we do this already) and then have CSS with more specific selectors to handle those cases.
