### ISSUE TITLE
Tracking API Usage

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#329]
Are we tracking API usage? If not, we should.

What metrics do we have (or should we have, if we haven't implemented yet).

Which API calls are being made. Which data is being used, etc.

**Comment by kotarohara** [comment]
It does track API usage. If @manaswis and @Soben713 want to check them out, they should see the `webpage_activity` table `activity` column. It stores the HTTP request (i.e., something like `GET /v1/access/score/neighborhoods?lat1=38.761&lng1=-77.262&lat2=39.060&lng2=-76.830`, so they can filter rows by `GET /v1/access/...`.
