### ISSUE TITLE
Having default Achievements feels weird.

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#33]
Matt's comment: Why do I have two achievements already?

**Comment by kotarohara** [comment]
Good point. I may change the term "Achievements" if that helps.

**Comment by kotarohara** [comment]
This is no longer valid. We don't have the default achievements on the status pane anymore.

**Comment by jonfroehlich** [comment]
I think it might be nice to have a leaderboard, however, possibly only accessible via the dashboard. Maybe an intern task?
