### ISSUE TITLE
Keelung and New Taipei Centered on Taipei rather than Keelung and New Taipei

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3302]
I imagine the `city_center` lat,lng or some other config property is set incorrectly for Keelung.

Here's route builder, where Taipei is clearly loaded.
https://sidewalk-keelung.cs.washington.edu/routeBuilder

<img width="1493" alt="image" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/ba1d6b07-04f3-41fe-87e0-6cf47dbf8a92">

Also affects the landing page (again, it's centered on Taipei rather than Keelung)
<img width="1509" alt="image" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/b8f47436-a2a1-4bd5-a37d-aaa82000dac8">

**Comment by jonfroehlich** [comment]
I just checked, this also affects New Taipei.

**Comment by misaugstad** [comment]
closing via #3308
