### ISSUE TITLE
The pano date is stuck on July 2023

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3304]
The pano date in lower-left corner is incorrectly showing July 2023.

Here's Seattle:
<img width="917" alt="image" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/932b48d2-82f8-4ea6-a7b7-87d7af5676b8">

Here's Oradell:
<img width="801" alt="image" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/8d2d4334-632b-44b3-93df-083713d6182d">

**Comment by jonfroehlich** [comment]
Interestingly, when trying to verify that the GSV was in fact not from July 2023, I found that the image from Oradell was from June 2018 but that there is a newer GSV image from Dec 2022 and that problem is now fixed :)

<img width="1344" alt="image" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/51a3386a-9842-4563-9297-957f80936432">

<img width="1498" alt="image" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/66e1fc32-81eb-4316-8d51-eb686b5a8834">

**Comment by misaugstad** [comment]
Note that this is an issue only on the Validate page. The dates look correct on the Explore and Gallery pages.

**Comment by jonfroehlich** [comment]
Nice. Thanks for checking this Mikey!
