### ISSUE TITLE
Zooming bug in validation UI

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3309]
I've replicated this multiple times. Attaching but one example.

Here's the problem: when you load a validation, we show you the exact view that the labeler used (including pan position, zoom position, etc.). If you're not at the max zoom, we let the validator zoom in. But our tracking of the zoom level appears broken. For example, you can zoom in two times but then the interface only lets you zoom out once. See video (again, I replicated this multiple times).

https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/a2d1c594-b48f-429c-b44a-cddfc60e71de

**Comment by misaugstad** [comment]
It's possible that this issue has to do with rounding. I remember there being some issues in the past with this. I even remember Safari doing rounding differently from Chrome/Firefox/Edge which caused some issues with zoom.

**Comment by misaugstad** [comment]
^^ Jon is using Chrome
