### ISSUE TITLE
Expanded cards in Gallery UI are sometimes unresponsive

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3314]
Problem: when expanding gallery UI cards, you should be able to select agree, disagree, and unsure buttons (that pop-up on hover). You should also be able to select the thumbs up or down. However, in many instances, you somehow cannot do this. See video. 

I can easily replicate it but it doesn't always happen. So, I imagine you could replicate this if you tried on say ~10 cards. I'm using Chrome. Haven't tried other browsers.

https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/78f25d59-81a3-4577-98ad-ff397da72169

**Comment by misaugstad** [comment]
I was able to reproduce this. It feels like a possible race condition where we are trying to attach the event listeners before the HTML elements have been created..? But I thought that the expanded view wasn't removed, we just changed the data in the different fields, so I'm not so sure about the race condition idea. Needs more investigating! No errors in console.

**Comment by misaugstad** [comment]
Still running into that issue again today!

**Comment by misaugstad** [comment]
I usually only get like 1-3 validations in on the expanded view before it stops working there.

**Comment by misaugstad** [comment]
You should start with the public facing user dashboard as a base, then add in some features to the admin version on top of it (not important that it's super pretty). Features from Admin version of the user dashboard that should be kept:
1. The table showing general info and stats (but if any of those things are duplicated somewhere else on the public facing version, they can be removed from this table)
2. The "Mark Work Quality by Date" section
3. The Completed Missions section
4. The Feedback section

Note that we can just remove the Labels and Audited streets section.

**Comment by misaugstad** [comment]
And for any sections you delete, if those API endpoints aren't being used anywhere, delete all associated code! We don't want code that doesn't do anything hanging around!

**Comment by misaugstad** [comment]
Sorry I just posted these on the wrong issue!! Deleting and pasting in the right one

**Comment by cyrusnaficy** [comment]
> I usually only get like 1-3 validations in on the expanded view before it stops working there.

One thing I notice is if it doesn't work on thumbs up, you can click thumbs down and that works. Then after clicking thumbs down, clicking thumbs up works again...vice versa. 

Still trying to fix this, will provide updates.

**Comment by misaugstad** [comment]
Ohhh okay! That's why it seems like it happens only _most_ of the time! Makes it sound like the issue should be easier to fix, since it just sounds like a clear issue with the logic in the code :)
