### ISSUE TITLE
Recenter New Taipei on Banqiao Area

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3329]
The Taiwan team wants to launch Aug 3 but asked for New Taipei to be centered not on Old Taipei (as it is) but rather the Banqiao region.

> One thing to point out, for New Taipei City, the map still centers on Taipei City. Could you have the default to center on the Banqiao area, where the two initial villages (Zhongshan and Longan) are located

**Comment by misaugstad** [comment]
Done! I sent the screenshot and link to Frank, and will make any quick adjustments before their mapathon as needed.
![Screenshot from 2023-08-01 10-10-06](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/5c1572f8-5392-4d9f-8707-e62957574b4f)
