### ISSUE TITLE
Centering for Oradell is now off

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3331]
On load:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/5cba989f-c129-40e5-81c6-75aafc710714)

You have to manually move map south to find Oradell:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/4c7529c8-f2fd-4b4f-a14d-2c293beaa6b7)

**Comment by jonfroehlich** [comment]
Also affects LabelMap:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/d0ac7bca-7a5e-458b-b6dc-029daf17224a)

**Comment by misaugstad** [comment]
A small copy/paste issue from #3320 that I didn't catch, this has been fixed! Let me check the other maps real quick.

**Comment by misaugstad** [comment]
Had to fix a couple things in La Piedad and Auckland, I believe that everything is looking good now!

**Comment by jonfroehlich** [comment]
Thank you Mikey!
