### ISSUE TITLE
Label showing up in upper-left of GSV view

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3336]
See video.

https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/ce128315-9bf4-4ef8-ac12-5dae56938393

Dev console (but pretty sure those things are unrelated):
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/ddf0e675-f0f6-4626-8edb-41e3ccfb7da1)

**Comment by misaugstad** [comment]
OMG you're right how did I not notice that...

**Comment by jonfroehlich** [comment]
It's not always happening though...

**Comment by jonfroehlich** [comment]
I see it always happening now. And I think I know why. When you _pan_ away from a label, it shows up in the upper-left corner.

https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/e4c511a9-c2c4-44e9-9b83-366913df9655
