### ISSUE TITLE
Jon and Mikey on leaderboard in Keelung

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3338]
Typically, the research team does not show up on the leaderboard. Maybe we missed a flag for keelung?

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/979b3e2d-74d6-4080-b256-35a3cbec3af5)

**Comment by jonfroehlich** [comment]
Also, New Taipei

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/1f2162ca-cf57-4df2-98a9-fde75b1c47e5)

**Comment by misaugstad** [comment]
The thing I forgot to do was to mark us as "Owners"! This has been fixed!
![Screenshot from 2023-08-03 11-37-20](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/734b30b3-df43-4691-8015-5fd972273261)
