### ISSUE TITLE
Need People Nudge logo on Taiwan webpage

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3340]
Seems like we should replace Liga Peatonal on Taiwan sites, no?

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/7172f3b3-f660-4e59-adc6-e28c237db677)

**Comment by jonfroehlich** [comment]
Just got this from Tsung-Lun:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/46fb7dcc-33b0-4af4-b140-d6a06ca16b56)

I asked them for a higher-resolution version and a url we could hyperlink the logo to.

**Comment by jonfroehlich** [comment]
Here's a higher resolution one:

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/c417a4da-2796-4b31-a028-22c957be9489)

**Comment by 1kechen** [comment]
Is there a URL to hyperlink to?

**Comment by jonfroehlich** [comment]
This is what our Taiwenese partners said:
> We currently don’t have a website, the following link is to the Facebook fan page:https://www.facebook.com/peoplenudge?mibextid=LQQJ4d
