### ISSUE TITLE
On custom route, if you keep auditing after you reach end, you'll get a strange error

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3341]
I discovered this today on a custom route. I was trying to go back on my route to double check something and the system glitched hard: kinda fun to watch. It will be about 90% into the video here: https://youtu.be/oONCCEaH4lM

I don't know if it has to do with being on a custom route...

**Comment by misaugstad** [comment]
Very very strange... Not sure if this has to do with the custom route or not.

**Comment by misaugstad** [comment]
Okay I think that it does have to do with custom routes. I was able to reproduce the issue.
