### ISSUE TITLE
GSV controls act weird when going back to an already completed route

### ISSUE THREAD

**Issue by crescendochu** [ProjectSidewalk/SidewalkWebpage#3355]
See video. Happened to myself and the intervention group. This happens when you've reached the end of a route, tried to go back to see missed anythings, then the gsv controls would freeze, the bottom right corner button and zoom in/ out buttons would also freeze.

https://github.com/ProjectSidewalk/SidewalkWebpage/assets/60413478/2d6f7e46-7c8f-420a-8f4b-d70fb187e753

**Comment by misaugstad** [comment]
closing as duplicate of #3341
