### ISSUE TITLE
Can we make the interim mission complete screen different from the final one?

### ISSUE THREAD

**Issue by crescendochu** [ProjectSidewalk/SidewalkWebpage#3356]
These two screens look too similar, both participants were confused with this. 
Was wondering if we can change the interim mission complete buttons from **keep exploring/ start validating** to **continue**? And also take out the two buttons for the route completion screen?

<img width="813" alt="image" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/60413478/3f1a57ff-06a8-46ea-ac27-34227e930022">

<img width="841" alt="image" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/60413478/83ec4cc3-7c66-4489-8c2d-429a11279ad2">

**Comment by jonfroehlich** [comment]
I brought this concern up over Slack when I was pilot testing the routes. I agree that it's a problem.
