### ISSUE TITLE
City names and translations

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3377]
Received an email from Frank that said:

> I've noticed the city names in the intro window stay in English even after the language selection has been set to other languages (for example Chinese). Could you guys fix that so that the city name also convert?  Example screenshot below showing "New Taipei" (in English).

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/cbee2d7d-059a-4000-934d-105ab07cbb42)

In the same email, he also asked us to make another city-name related fix:

> Also each city area that we have opened in Taiwan (Taipei, New Taipei, and Keelung), for those cities to be correctly referred to in Chinese, after each city name, the Chinese word for "City" (市) has to be inserted, otherwise it's not a proper name. Could this be handled in the code just like the other translations terms?

**Comment by misaugstad** [comment]
Just recording that I'm getting Chinese names for US states [here](https://www.julianne-studio.com/%E7%BE%8E%E5%9C%8B%E5%B7%9E%E5%90%8D%E8%8B%B1%E6%96%87%E7%B8%AE%E5%AF%AB%E5%8F%8A%E4%B8%AD%E8%8B%B1%E6%96%87%E5%85%A8%E7%A8%B1-%E7%BE%8E%E5%9C%8B%E7%95%99%E5%AD%B8%E4%BB%A3%E8%BE%A6/#:~:text=%E7%BE%8E%E5%9C%8B%E5%90%84%E5%B7%9E%E7%9A%84%E9%83%B5%E6%94%BF%E7%B8%AE%E5%AF%AB%EF%BC%8C%E8%8B%B1%E3%80%81%E4%B8%AD%E6%96%87%E5%85%A8%E7%A8%B1%E4%BB%A5%E5%8F%8A%E9%A6%96%E5%BA%9C%EF%BC%8C%E6%8C%89%E8%8B%B1%E6%96%87%E7%B8%AE%E5%AF%AB%E6%8E%92%E5%88%97%EF%BC%9A%20%E7%BE%8E%E5%9C%8B%E5%B7%9E%E5%90%8D%E8%8B%B1%E6%96%87%E9%83%B5%E6%94%BF%E7%B8%AE%E5%AF%AB%EF%BC%8C%E4%B8%AD%E8%8B%B1%E6%96%87%E5%85%A8%E7%A8%B1%E4%BB%A5%E5%8F%8A%E9%A6%96%E5%BA%9C%E5%90%8D%E7%A8%B1%EF%BC%8C%E6%8C%89%E8%8B%B1%E6%96%87%E7%B8%AE%E5%AF%AB%E9%A0%86%E5%BA%8F%E6%8E%92%E5%88%97%20%E2%80%93,%E8%B3%87%E6%96%99%E4%BE%86%E6%BA%90%20%E2%80%93%20%E7%B6%AD%E5%9F%BA%E7%99%BE%E7%A7%91).
