### ISSUE TITLE
Walla Walla, WA and College Place, WA ArcGis Shapefiles

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3382]
For our forthcoming deployment in Walla Walla, WA and College Place, WA, here are some relevant shapefiles.

From Email:

> I received some shapefiles from our contact Tim. The zipped folder has two layers - one being the outline of the Walla Walla and College Place region (WWV_ProjectSidewalk_noNHs) and the other layer having neighborhood boundaries (WWV_ProjectSidewalk_NHs). This second layer has the names of all the neighborhoods. Please let me know if more information is needed!

[WWV_ProjectSidewalk_layers.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/12541140/WWV_ProjectSidewalk_layers.zip)

**Comment by misaugstad** [comment]
Just tested out the shapefiles and they look great! Not creating the database quite yet, but the neighborhood boundaries are exactly what we need!

**Comment by jonfroehlich** [comment]
Some awesome ugrad students have been building a GSV availability analysis tool that helps analyze and calculate GSV availability in an area and the capture dates. We just used Walla Walla, WA as a test site and found out the following:

Across ~27,700 GSV images in Walla Walla, WA, the average capture date was 2021 (max: 2023; min: 2008) and standard deviation was 3.3 years. Here's a histogram of capture dates.

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/e0af88fd-f5b1-41d1-b013-a4c7a9ee86f5)

And here's a spatial visualization where the yellow corresponds to more recent (2023) and the blue is less recent (~2012 and before).

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/c27b88bd-5d8b-48a7-a4b8-87f0ec3708eb)

**Comment by jonfroehlich** [comment]
The students continue to work on this and provided some improved visualizations

This is using a grid-based approach:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/718a7be3-384a-451e-8542-400f24df1446)

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/80c4c947-5e4c-4906-8983-aef3034c5dab)

This is using a road-network approach:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/00a3d7d6-a23e-490c-b1b7-2030dfd4c232)

**Comment by yeisenberg** [comment]
Very cool!!

--
Yochai Eisenberg, PhD
***@***.******@***.***>
312-413-9410
Schedule an appointment via Calendly<https://calendly.com/yochaie/45min>

**Comment by misaugstad** [comment]
Closing via #3393 

Configs are set up, just waiting for the server to be spun up by CSE Support!
