### ISSUE TITLE
Admin Interface: Make End-User Comments Table Same Format As Recent Label Table

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#339]
In other words, allow user to sort, show # of entries, go to next page of table, search, etc.

![image](https://cloud.githubusercontent.com/assets/1621749/19281597/ee005fae-8fb8-11e6-9193-191ef4ba9501.png)

**Comment by manaswis** [comment]
Completed this in PR https://github.com/ProjectSidewalk/SidewalkWebpage/pull/338.
