### ISSUE TITLE
APIs not dealing with neighborhoods with commas in CSV format

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3390]
##### Brief description of problem/feature
@devonsnyder brought to my attention that the data looked messed up in CSV format for some data she was getting from our API (pic below). The reason is that the neighborhood is called "Little Italy, UIC"; there is a comma in the field for a CSV (comma-separated value) file.

![Screenshot from 2023-09-26 16-32-05](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/f6f132ea-00bd-4eab-9c45-58f2a80a3580)

##### Steps to reproduce
Here's the API call that @devonsnyder used:
https://sidewalk-chicago.cs.washington.edu/v2/access/attributes?lat1=41.863085&lng1=-87.661878&lat2=41.874468&lng2=-87.646729&filetype=csv

##### Potential solution(s)
I believe that the standard when your data could contain a comma is to surround it in double quotes. From what I can tell, the only data in our APIs that could have commas are the "Neighborhood Name" columns in `/v2/access/attributes`, `/v2/access/attributesWithLabels`, and `/v2/access/score/neighborhoods`. Should be pretty easy to update!

**Comment by davphan** [comment]
While looking into this, it seems like `/v2/access/score/neighborhoods` is having an issue where the "coordinates" field somehow has a newline or something throwing off the csv file:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/77756028/8beb1dba-d1ed-44d1-92e9-52e05e3e9dd4)
Can I make a new issue on this?

**Comment by misaugstad** [comment]
@davphan is this after fixing the current issue you're still seeing this? If not, fix this issue first, and then make a new issue if it's still happening! This seems like the kind of thing that could be caused by the first issue!

**Comment by davphan** [comment]
I reverted my changes and tried it and that issue still persists, so I figure it's something else? Would you rather I make a new issue for it or get it figured out in this same PR?

**Comment by misaugstad** [comment]
Oh if it's happening without the changes you made to the code (or the database), then yes, make a new issue and work on that one next please!! If they are both easy/related changes, then I don't have an issue with them sharing a PR. Just depends on what makes sense / is easiest for you!
