### ISSUE TITLE
Add organization as a column in the Admin Users tab

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3398]
##### Brief description of problem/feature
I'd like to add "organization" or "org" as a column in the "Users" tab on the Admin page. I think that we can likely remove a column or two from here that we aren't really using to help make room? We alraedy need to scroll horizontally, so I'd love to remove some rarely-used columns if possible. Here are some of the columns I think are candidates for removal. @jonfroehlich I'd like to hear if there are any in the list that you do/don't want to keep!

1. login count
1. audit count (somewhat redundant given that we have label count)
1. mission count (somewhat redudant given that we have both label count and validation count)
1. "% Own Labels Notsure" and "% Own Labels Disagree" (having only "% Own Labels Agree" is probably sufficient here, and it's also what we're already doing for their own validations)

And then here's a screenshot of the columns for context (had to scroll, but to the left are username, user ID, email, and role.
<img width="973" alt="Screenshot 2023-10-05 at 12 08 06 PM" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/c0e57f83-4a70-43ff-9e41-61ef2a763598">

Aaand maybe we have the same sort of drop-down menu system as we do for user roles so that we can set users' orgs for them!

**Comment by jonfroehlich** [comment]
Sure.

I agree with everything but would like to keep login count.
