### ISSUE TITLE
Cannot seem to skip tutorial

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3399]
On walla.projectsidewalk.org, I was just testing the new city site. I am logged in. Two problems:

1. When I click the 'skip' button, it just reloads the tutorial screen
2. The tutorial screen asks me to login but I am logged in

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/f1e48a67-e9c8-412e-b48f-af260b88ff6e)

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/aa4fc0a6-1f17-4482-a4d7-1e8859dbc2bd)

**Comment by hoominchu** [comment]
I was able to reproduce this issue. Both completing the tutorial and skipping it end up in a circular loop. My console log is attached below.

<img width="719" alt="Screenshot 2023-10-06 at 1 22 30 PM" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/8168506/86bcc436-d3da-4fbb-b569-c9ae75b63961">

**Comment by jonfroehlich** [comment]
Thanks @hoominchu. How about on other city servers?

**Comment by hoominchu** [comment]
It is working fine on Seattle server.

**Comment by devonsnyder** [comment]
Morning all, checking in to see how this is going. Appreciate it being classified as a priority!

**Comment by misaugstad** [comment]
Hi @devonsnyder I'm out of town and have been with family the past few days, but I am tackling this this afternoon! Should push a fix to production either today or Thursday!

**Comment by misaugstad** [comment]
This has been fixed! The issue had to do with filtering down to just one neighborhood... I did one of the steps in the wrong order 🙈 I just needed to add an entry for the tutorial street to the `street_edge_priority` table. It's all fixed on test and prod now, no code needed!

**Comment by devonsnyder** [comment]
Amazing! Thanks, Mikey and team! I'll share the site with our Walla Walla contact.

**Comment by jonfroehlich** [comment]
@hoominchu said he was experiencing this on his local dev with Pittsburgh city boundaries... he can pipe in with specifics.
