### ISSUE TITLE
Cannot "validate more labels"

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3401]
When I click on "validate more labels", nothing happens and the console prints an error.

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/dd7126d9-2d02-437c-a50f-6ed2b5f2f44e)

**Comment by hoominchu** [comment]
I am able to replicate this along with the console message.

**Comment by hoominchu** [comment]
And interestingly, the mission start screens are neither shown in the beginning nor after clicking on Validate More Labels.

**Comment by jonfroehlich** [comment]
Just had this again in production but I assume because this code fix isn't on prod yet

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/285becc2-5f62-465a-8f28-6a5c5b42be1e)
