### ISSUE TITLE
Labeling guide links point to different places

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3420]
We've found that some cities want to point folks to their own custom labeling guide (for example, in Taipei, New Tapei, and Keelung). 

However, in our html, we have multiple places that point to this labeling guide and they appear to be hard coded rather than, say, referencing a labeling guide location variable. And, currently, these different links take you to different places.

If you click on "How to label", you go here: https://sidewalk-taipei.cs.washington.edu/assets/documents/labeling-guide-Taiwan.pdf

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/784cd22e-a257-4b8b-aef0-2f676e5b3a78)

If you click on labeling guide in the leaderboard, however, you go just to the English html page. This should be fixed.
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/7c50dfc6-f58a-4d54-bff9-38e60d47242a)

**Comment by misaugstad** [comment]
Given that we are hoping to move over to a more easily updated labeling guide in Google Docs (#3282), I think that we should avoid the overhead of storing this in a variable, and just check if there are any other places that link to the labeling guide and update those for now!

**Comment by misaugstad** [comment]
Closing via #3449
