### ISSUE TITLE
Start recording dates and pano IDs for older panos when users visit them

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3423]
##### Brief description of problem/feature
We've talked about wanting to explore changes in GSV imagery over time, though the Google API to look at past pano IDs at a location is a paid API that's prohibitively expensive to run on an entire city just to get those IDs. However, when users visit a pano in PS, they are already using that API, so we have access to that data! In the response object, there is a "time" attribute that holds the pano IDs and timestamps for all the all the available GSV panos at that location. Here's an example call you can use in the browser console:
```
svl.streetViewService.getPanorama(
    { pano: 'NXyzHZcbw8ldr3B0Shye7g' },
    function(data, status) { console.log(data.time); });
```

And the output looks like this:
<img width="393" alt="Screenshot 2023-11-13 at 11 33 58 AM" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/90b6775a-3080-48f2-80b8-caa9a2cc3cf1">

Note that the data is only accurate up to the month. So it will always say the first of the month.

##### Potential solution(s)
Every time a user visits a pano, we could just save this data in case we ever want to use it. Since we won't actually be using the data in core PS, I'd suggest that we make a new table to hold the data.

**Comment by jonfroehlich** [comment]
Great idea. Oh how I wish we had thought of this in ~2017

**Comment by jonfroehlich** [comment]
We are saving not just the historic panoid here but also the timestamp, right?

**Comment by misaugstad** [comment]
Yep!
