### ISSUE TITLE
Add last label timestamp to overallStats API?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3430]
Mikey and I were talking about how to quickly assess how active a server is:
* Easiest: just add in a `last_label_timestamp` to the [overallStats API](https://sidewalk-oradell.cs.washington.edu/v2/overallStats)
* Slightly better: add in average date of last 100 labels to the overallStats API

**Comment by misaugstad** [comment]
Yeah I like average date of last 100 labels! I'd be okay with naming the field something vague like "recent_activity" or "recent_activity_date", or we could be really specific with "avg_timestamp_last_100_labels".

**Comment by jonfroehlich** [comment]
👍🏽 Did you mean to close this?

**Comment by misaugstad** [comment]
Nope! I think that every once in awhile Github decides that "ctrl-enter" means closing the issue?! Thank you for noticing!

**Comment by jonfroehlich** [comment]
Can we get this one prioritized @misaugstad?

**Comment by misaugstad** [comment]
Yep! @davphan you down to take a break from what you're currently working on for this?

**Comment by davphan** [comment]
Yup! I'll start working on this one now then :)

**Comment by jonfroehlich** [comment]
I would say all labels (verified or not) but exclude tutorial labels
