### ISSUE TITLE
Add in street address / search support to RouteBuilder

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3432]
From Yochai's feedback session, folks will likely want to enter a street address, a transit stop, or even POIs (a school) and then have RouteBuilder mark that and center/zoom around that location.

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/b2f140c1-1ca5-4db0-97c5-5ca4ef1e63e3)

**Comment by misaugstad** [comment]
We should do this for LabelMap and User Dashboard map as well!

**Comment by misaugstad** [comment]
@srihariKrishnaswamy we haven't added address search to any of our maps on the website, so you should start by doing some research into what are options are and their cost. I imagine that the two most likely options for us would be using either Google or Mapbox, but I haven't really looked into it myself!
