### ISSUE TITLE
Long Gallery tags aren't truncated on the first card of the page

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3464]
##### Brief description of problem/feature
There are tags with long names (like "not enough landing space") that need to be truncated. Or they are truncated because there are multiple tags that won't all fit on one line. We have code that checks available width and truncates automatically... But it looks like that code isn't being run or isn't working on the first card of the page.
<img width="1425" alt="Screenshot 2024-01-26 at 4 45 16 PM" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/f31a1983-d50d-4e70-8dcf-17c6ffa446e6">
<img width="1425" alt="Screenshot 2024-01-26 at 4 45 09 PM" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/5f3c76e1-36cf-4a06-93e3-500ad213955f">
<img width="1425" alt="Screenshot 2024-01-26 at 4 44 26 PM" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/f87fd3c5-5fa5-4f86-b93d-ee3d0f98160e">
<img width="1425" alt="Screenshot 2024-01-26 at 4 44 20 PM" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/efe8fd8e-97f8-4c47-ab5e-4bf0822f83d4">

##### System info (OS, browser, city, and local/prod/test)
I've seen this on Chrome on Mac and Linux. I would expect it to happen anywhere though.

**Comment by jsomeara** [comment]
Perhaps the truncate code might not run unless there's more than 1 tag (like in the 3rd card in your first example image) and those tags cannot fit. For one long tag though, I think JS might not even be necessary to truncate it. Gonna make a PR that fixes this with CSS.
