### ISSUE TITLE
Add an endpoint to view a label: /admin/label/<label-id>

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3469]
##### Brief description of problem/feature
As requested by @crescendochu! 

We essentially want something like the Admin's Label Search tab, except you can put the `label_id` into the URL, allowing us to link directly to the label instead of loading up the admin page and searching for it.

**Comment by jonfroehlich** [comment]
It would help us make hyperlinks to our data. Ideally, this would open up the that same Admin label pop-up (or similar).
