### ISSUE TITLE
Reviewing v7.18.0 with Mikey; Explore-street-link broken in LabelMap

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3473]
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/e1a3c056-02ae-4433-94bc-323bae825581)

**Comment by misaugstad** [comment]
@jonfroehlich this isn't happening for me. Can you test it one more time? I'm pretty sure that this was another error that was a result of caching. Going to close unless you can reproduce it!
