### ISSUE TITLE
Open Columbus icon hyperlink no longer active

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3475]
If you click on the Open Columbus link, you get a meetup page that is no longer found. Do they have another website we could use?

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/8a83fe62-e940-49d0-ac91-f09235b86920)

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/d90a524f-1459-42a5-a517-04a01b441814)

**Comment by misaugstad** [comment]
Here's the response on Slack
>decided to pause the group as we were getting stretched a little too thin over the last 8 months. We are not sure what the future of this group will look like but for now we are not actively meeting.

Seems like we should just remove the hyperlink for now, then. Very sad :/

I don't think that we're working with any other groups in Columbus... Should we remove this from the city dropdown list in the navbar?

**Comment by jonfroehlich** [comment]
Let's remove the hyperlink and but keep the icon and keep the city listing. Thanks Mikey!

**Comment by nehaa2426** [comment]
the logo itself is not on the website anymore, is this resolved?

**Comment by misaugstad** [comment]
As of now it only shows up on the Columbus version of the website! You can manually make your landing page show the Columbus version by changing the `SIDEWALK_CITY_ID` in your docker-compose.yml and then rerunning `make dev` and `npm start`! But pages other than the landing page are unlikely to work, so I would switch it back to the correct one if you are trying to test any other parts of the site!
