### ISSUE TITLE
Include timestamp whenever we save temp files for our API

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3479]
##### Brief description of problem/feature
We are doing this correctly for our GeoJSON APIs, and @SanyamSavla is working on an update for our CSV APIs that will do the same thing. But I have noticed that at least for our Shapefile API, the file names are generic: "labels.dbf", "attributes.zip". We should add timestamps to these so that multiple API requests can happen at the same time without stepping on one another.

@SanyamSavla you are already making changes to the Shapefiles API to batch them, maybe you could roll this in with that change? Or tackle it once you're done with the changes you're making, either way!

**Comment by SanyamSavla** [comment]
Okay, let me have a look over this and I will update you accordingly!

**Comment by SanyamSavla** [comment]
I have linked it with PR #3462 and committed changes to add timestamp for shapefiles! 

@misaugstad Can you please review if that file opens up correctly on the GIS software.

**Comment by misaugstad** [comment]
Closing via #3516
