### ISSUE TITLE
Denison, Texas Boundary Data

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3484]
I think we can get Dension, Texas boundary data here: https://www.cityofdenison.com/planning/page/zoning-map. Click on "Interactive Map", which takes you [to this link](https://denison.maps.arcgis.com/apps/webappviewer/index.html?id=bc2d6a3793cd4defa7d00b3867aa0f26). Then turn on/off layers with the "Layer List" and you can control what to show: zoning, streets, boundaries, etc. Hopefully we can download this locally. Another possibility is: https://www.cityofdenison.com/planning/page/city-maps

The following is from: https://www.cityofdenison.com/planning/page/zoning-map

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/08b007b3-6658-4411-b1fa-1ed0a136038f)

This is the Denison ISD layer:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/d76488a9-bb3e-45e2-ba97-f205f0e16ce8)

This is the elementary school attendance zones:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/2b7178d9-fa8c-48d9-b243-521de3ed384b)

This is the Denison wards:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/7c3c35d6-c1a1-4409-aa7f-42fbe23984d7)

City council boundaries:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/f55beb08-c1f9-49f1-8484-6f51f4eb15f5)

**Comment by misaugstad** [comment]
Just got en email from our contacts in Denison:
>I apologize for my delayed response. It has come to our attention that the public works department is pursuing a sidewalk and alley assessment and analysis. They have hired a 3rd party to do this. We will not be moving forward with this. I appreciate the communication and willingness to facilitate this work.
