### ISSUE TITLE
For admins, show other users who validated on validate page?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3496]
This was requested by Zurich team.

Could do this on the admin interface or directly in the validate flow (e.g., check if an admin or research team member, then show user and some metadata). Could be something to consider for the validation UI redesigns.

> About the validation: until now Annina and I have each validated a part of the Zurich labels - about 3000 and 2000 respectively - with some overlap. Also, a few ZuriACT participants validated some labels. Ideally, we would want each label validated by at least two 'experts' (which includes for example me and Annina) and for this, we will have more experts validating soon. So, we were thinking, it would be helpful if we could see when validating a label if this label was validated by an expert by showing the user IDs of the experts. Do you have a better idea of how to do this? We would be happy to hear your suggestion!

**Comment by misaugstad** [comment]
The current plan is that this would be another option in the drop-down menu when clicking on your username (right below "Admin"). We would probably call it "Admin Validate" and the url "/admin/validate". We could entirely reuse the current Validate page code, and just have some conditionals in to decide whether to show certain UI elements.
