### ISSUE TITLE
Dumping all crops into the same dir seems potentially messy and inefficient

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3502]
Related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/3468

With @hoominchu's auto-cropping code, should we avoid dumping all crops from all cities into the same directory? Some filesystems have small limits (e.g., 65k files per dir). Moreover, it takes a long time to open large dirs. I might suggest organizing them by city and then label type (so, we would have a `Zurich, Switzerland` dir and then dirs like `curb ramps`, `missing curb ramps`, etc.)

**Comment by misaugstad** [comment]
Sounds like our filesystem if zfs, which has a max number of files per dir of 281,474,976,710,656. So running into that limit won't be an issue. Though we could always group them into sub directories if we find that easier.

**Comment by jonfroehlich** [comment]
I think we should clean this up a bit. If I use WinSCP or another UI tool to try and load those dirs, it can take a very long time.

Perhaps you can address this when we work on https://github.com/ProjectSidewalk/SidewalkWebpage/issues/3506. 

Also, these files are marked as "temp"--shouldn't that also be addressed? Maybe that's another existing Issue that should be linked.

**Comment by misaugstad** [comment]
>Also, these files are marked as "temp"--shouldn't that also be addressed? Maybe that's another existing Issue that should be linked.

Yes, that will be fixed as part of #3468!

Hoping to tackle all three of these issues in the next week or so!
