### ISSUE TITLE
Some crops still have GSV street name overlays?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3503]
In rapidly reviewing a subset of our crops, I observed that some still have the streetview text overlay:

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/cf216d23-4bb7-433c-8102-f9df122423ea)

This is `crop_temp_pittsburgh-pa_12692bf9-35f2-4a9a-8051-c31df62388a7_392_NoCurbRamp.jpg.png`

**Comment by jonfroehlich** [comment]
Another example:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/37ae71e7-7473-417b-8dee-66819f2e9235)

`crop_temp_pittsburgh-pa_12692bf9-35f2-4a9a-8051-c31df62388a7_338_Crosswalk.jpg.png`

**Comment by misaugstad** [comment]
Looks like this was at least started, but we never actually merged this code in... https://github.com/ProjectSidewalk/SidewalkWebpage/compare/develop...save-crops

@hoominchu were we at a place where this was ready to go? Did I say I was going to test it or something and then dropped the ball?

**Comment by hoominchu** [comment]
yes, the code to fix is ready in branch: https://github.com/ProjectSidewalk/SidewalkWebpage/tree/save-crops

and right, it needs to be tested and released.

**Comment by jonfroehlich** [comment]
Glad I decided to actually look at how well the crops were working? :)
