### ISSUE TITLE
Admin Interface: I Want Better Metrics and More Information

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#351]
Things like:
- Histogram of time spent using Project Sidewalk with median and average marked. Also, perhaps include a table that also includes this info but differentiates between signed in and anonymous users
- Histogram of number of labels per mission with median and average marked. Again, would like summary table comparing signed in and anonymous users
- Histogram of number of audits per person with median and average marked. Again, would like summary table comparing signed in and anonymous users
- Histogram of number of logins per registered user with median and average marked

These are things that we will be reporting in our publications so I'd like the dashboard to start showing them. Who wants to take this one? @Soben713 or @manaswis?

**Comment by manaswis** [comment]
I can do it.


Best Regards,
Manaswi Saha
Ph.D. Student
Department of Computer Science
University of Maryland, College Park
http://cs.umd.edu/~manaswi/
Twitter - @manaswisaha <https://twitter.com/manaswisaha>

**Comment by Soben713** [comment]
I can also manage to do it if it is not part of the Public Deployment v2.

**Comment by jonfroehlich** [comment]
I think we should also brainstorm other relevant metrics.

This seems increasingly related to @Soben713's interest in assessing crowd worker behavior, so perhaps a good place for him to start; however, I'm happy with either of you doing it. You guys can discuss and decide. Then please change the 'Assignee' in github.

**Comment by jonfroehlich** [comment]
It looks like this thread died as no one took on the assignment. I still consider this Issue very important and relevant to @Soben713's quality control work; however, given that he is leaving the team, perhaps we should assign it to someone else.

**Comment by manaswis** [comment]
I am happy to take it on. It would be important for the CSCW paper. However, @Soben713: since its closely related to your work, if you'd like to do this before you leave, then let me know. Either way is fine with me.

**Comment by jonfroehlich** [comment]
I don't think @Soben713 will have time to do this honestly. He has like one week left in the group. I'm leaning towards assigning this to a new ugrad researcher who will likely join our team next week.

**Comment by misaugstad** [comment]
I had previously split the multiple ideas given into separate issues, but forgot to close this. Closing it now.
