### ISSUE TITLE
Consider updating "Pooled Water" to "Pooled Water/Debris"

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3518]
It's often the case that leaves or other debris are at the bottom of the curb ramp but we have no current good way to mark

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/2df913bb-8b55-4e5a-8eb1-3099201abf14)

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/15a5f99e-8357-41cc-8231-6ec913cf9baa)

**Comment by misaugstad** [comment]
Great idea!
