### ISSUE TITLE
Setup St. Louis Missouri

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3522]
We are working with a new organization in St. Louis, Missouri to map and assess sidewalks in specific wards.

Here is all the ward data: [wards_2020.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/14702651/wards_2020.zip)

Here's just ward 3, which is the initial focal point:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/9d88513a-589d-4050-ae84-38512016a2bf)

[Ward3.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/14702865/Ward3.zip)

**Comment by misaugstad** [comment]
This has now been set up! https://sidewalk-st-louis.cs.washington.edu/
