### ISSUE TITLE
Admin Interface: Add 'Last Audit' Timestamp to Anonymous Users Table

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#353]
Add 'Last Completed Audit' and/or 'Last Label' timestamp column to Anonymous Users table.

**Comment by manaswis** [comment]
Resolved in PR #406. Also takes care of issue #365.

Screenshot:
<img width="1280" alt="screen shot 2016-11-11 at 2 44 57 pm" src="https://cloud.githubusercontent.com/assets/2873216/20228124/cd092786-a81d-11e6-8f6b-e7673d0661d8.png">
