### ISSUE TITLE
New Validate should have default reasons for being unsure

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3581]
##### Brief description of problem/feature
When validating disagree, I've added 3 potential reasons to disagree, plus the text box. Right now I only have a text box for Unsure, but there are some common reasons to be unsure, and we could make things more smooth by having options there. Some options that may apply to all label types:
* Image is blurry / label is too far away (could also prompt them to zoom here if they aren't fully zoomed in)
* Need another angle for context

But there could also be label type-specific reasons:
* Obstacle: can't tell if there is enough space to get around object
* Missing Curb Ramp: can't tell if pedestrians should be able to cross here (might be a busy road)

I haven't spent time thinking through a big list of options here, but we should work on compiling a list of 3 for each label type!

**Comment by jonfroehlich** [comment]
Yes. Great idea.

**Comment by jonfroehlich** [comment]
* Can't tell if it's narrow or width of sidewalk
* Can't tell if a missing curb ramp is required here
