### ISSUE TITLE
Validate: label can be hidden behind mini map when loading label

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3582]
##### Brief description of problem/feature
Since adding a minimap to all versions of Validate (PR #3576), we now have an issue where the label can be hidden behind the mini map immediately when we show it to them. This is because we try to pan the user to the view that the labeler had when they added it, expecting it to give better context than just centering the label. But that's not going to fly if the label is just completely hidden!

##### Potential solution(s)
The easiest thing would be to have the label show up above the minimap no matter what... This looks funky.
![Screenshot from 2024-06-28 19-16-59](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/cff11bdc-aa69-4f7c-b84a-c2a6bf3c3b73)

Next could be to mess with the opacity of the minimap if the label is underneath it. Better... Still kinda weird? Idk I think I need to look at it again with fresh eyes later. Could also just fully hide the minimap if the label is behind it.
![Screenshot from 2024-06-28 19-18-18](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/e5e1a49c-d915-4886-96e1-42a735d90d5b)

Another option is to detect if the label is going to show up under the minimap, and auto-pan the GSV so that the label doesn't start behind the minimap. The only downside to this one (aside from code complexity) is that users can still pan so that the label ends up behind the minimap on their own. Though this method could be combined with another method so that the label remains visible if the user pans to make it under the minimap.

**Comment by jonfroehlich** [comment]
If label starts behind mini-map, just move minimal to bottom left rather
than the default of bottom-right?

**Comment by misaugstad** [comment]
>If label starts behind mini-map, just move minimap to bottom left rather than the default of bottom-right?

Right, I forgot that I was going to mention that that was another option... I'm not a fan of it. Might be a little weird to have the map jumping around. And more importantly, what do we do with the zoom buttons that are next to it? Then those will just be floating unless we move those too.

**Comment by misaugstad** [comment]
Since we are removing the minimap (#3593), this issue will no longer be relevant.
