### ISSUE TITLE
Add in a open text field for new validate interface

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3595]
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/f27b634d-b773-4fbc-b42c-cc3bd95a6706)

I wanted to write in that this area of sidewalk was uneven/slanted due to the driveway but there is no open text field to write this info... did we talk about putting an open text field in Project Sidewalk? I think we should...

**Comment by misaugstad** [comment]
Yeah I think it makes sense to do this. Maybe it's phrased as "add comment"?
