### ISSUE TITLE
The mouse travel on the new validate UI is intense

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3596]
If I agree with everything shown (across multiple screens particularly), I have a significant amount of mouse travel. I have to click "yes" than move the mouse a large number of pixels to the "submit" button and then move back up to the "yes, no, unsure" area for the next image—and back and forth. This is too much effort.

Could we have the "Submit" button be triggered by hitting 's'? 

Or could we redesign the UI somehow to also have the submit button at the top of the UI...

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/b3f55a42-c822-4766-819c-4ba4126c9554)

**Comment by misaugstad** [comment]
>Could we have the "Submit" button be triggered by hitting 's'?

100%! It totally slipped my mind, adding an 's' shortcut for 'submit' was something I was planning to do!
