### ISSUE TITLE
"View in Street View" didn't bring me to the proper pano

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3607]
I love the "View in Street View" option that we have; however, I ran into a problem with it this morning.

In Gallery, I was viewing this image:
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/ed81b1c5-8db6-48c5-94ef-035fa5e38059">

Then I clicked on "[View in Street View](https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=49.22357547384986%2C-122.98417246854102&heading=100.06115868735137&pitch=-8.92242188029158)"
<img width="1065" alt="image" src="https://github.com/user-attachments/assets/68de3619-9780-4bea-97cb-23ee8ec27935">

But if you click on that link, you get the following with a message "No street view imagery available here":
<img width="955" alt="image" src="https://github.com/user-attachments/assets/9e05eb3c-cf87-4f2b-984d-6eec79058f8d">

From looking at the image and street intersections, I was able to derive the actual location, which is ([Google Maps Link](https://www.google.com/maps/@49.2235755,-122.9841725,3a,75y,101.15h,68.16t/data=!3m7!1e1!3m5!1s-5CroQWZ8xZZl-NGKuIPxQ!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3D-5CroQWZ8xZZl-NGKuIPxQ%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D146.56241%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192?coh=205409&entry=ttu)):
<img width="1404" alt="image" src="https://github.com/user-attachments/assets/c4a96114-8597-497c-9bf6-e18231177755">

Any ideas why this might have happened @misaugstad? Is this just a one-off problem or did GSV maybe change their API a bit? Or why can't we access the exact pano? It seems like it does indeed exist [here](https://www.google.com/maps/@49.2235755,-122.9841725,3a,75y,101.15h,68.16t/data=!3m7!1e1!3m5!1s-5CroQWZ8xZZl-NGKuIPxQ!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3D-5CroQWZ8xZZl-NGKuIPxQ%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D146.56241%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192?coh=205409&entry=ttu).

**Comment by misaugstad** [comment]
Oh that's really weird, I'm not sure what's going on! I just tried this out and managed to reproduce a few times. At least with the ones that I was able to do, the images were at approximately the same location, just from a different period in time. Though from your example it looks like it might be a totally different location.

**Comment by jsomeara** [comment]
It works when setting the `pano` parameter to the pano id instead of specifying the viewpoint coordinate.

Example:

https://www.google.com/maps/@?api=1&map_action=pano&heading=100.06115868735137&pitch=-8.92242188029158&pano=-5CroQWZ8xZZl-NGKuIPxQ

Are there any downsides of switching to `pano` instead of `viewpoint`?

**Comment by misaugstad** [comment]
>It works when setting the pano parameter to the pano id instead of specifying the viewpoint coordinate ... Are there any downsides of switching to pano instead of viewpoint? (If not, I can make a PR with the fix)

No idea why we wouldn't have been using the pano ID already, so we would definitely welcome a PR!

**Comment by jsomeara** [comment]
Made a PR: https://github.com/ProjectSidewalk/SidewalkWebpage/pull/3608
