### ISSUE TITLE
Add left/right keyboard shortcuts to Gallery expanded view

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3612]
##### Brief description of problem/feature
When the expanded view is open, I think that we should have the following keyboard shortcuts at a minimum:
* Validate agree: A and Y
* Validate disagree: D and N
* Validate unsure: U
* Go to previous label: left arrow key
* Go to next label: right arrow key

**Comment by jonfroehlich** [comment]
Yes! :)

**Comment by jsomeara** [comment]
Hi! I was gonna give this shot until I realized I don't have any labels to validate in my DB. Does anyone know if there's a way to add/simulate labels in a dev environment with a DB that has its PII scrubbed?

**Comment by misaugstad** [comment]
>It seems my labels are showing up in the gallery of the dev environment but for some reason the validate page doesn't load anything. I get this error in the console:

I think that you probably just need to add even more labels for Validate to work! And you also need to add labels with a different account than the account you use to validate the labels. I think that you can see your own labels in Gallery, but not Validate

**Comment by jsomeara** [comment]
> I think that you probably just need to add even more labels for Validate to work! And you also need to add labels with a different account than the account you use to validate the labels. I think that you can see your own labels in Gallery, but not Validate

Good to know if I ever need to work on the validate page! My apologies for clogging up this thread a bit earlier.


---

Made a PR for the keyboard shortcuts: #3613
