### ISSUE TITLE
Short Gallery tags aren't displayed correctly

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3636]
##### Brief description of problem/feature
Boxes holding tag names are taking up the full length of the card even if they are short names.

@jsomeara it looks like neither of us tested #3634 with short tags :facepalm: 
![Screenshot from 2024-08-28 12-37-42](https://github.com/user-attachments/assets/e8b343c5-3b02-408b-8776-0fe87aa532f5)

##### System info (OS, browser, city, and local/prod/test)
Local/test

**Comment by jsomeara** [comment]
Sorry about that!

**Comment by jsomeara** [comment]
Made a PR
