### ISSUE TITLE
Admin Interface: Activities Table Not Accounting for New Way of Calculating Who a User Is

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#364]
This table appears out of sync with how we are calculating users on the landing page now. Should be consistent:

![image](https://cloud.githubusercontent.com/assets/1621749/19572722/791a675a-96d1-11e6-8072-e6cefecbfc36.png)

**Comment by jonfroehlich** [comment]
In fact, might be nice to have:

Total Users
  Registered Users
  Anonymous Users

**Comment by manaswis** [comment]
Is this format okay?

<img width="394" alt="screen shot 2016-11-11 at 3 12 55 pm" src="https://cloud.githubusercontent.com/assets/2873216/20228881/60052c58-a821-11e6-9ff1-e586709ddd75.png">

**Comment by jonfroehlich** [comment]
No :) I'll come talk to you.

**Comment by manaswis** [comment]
How is this?

<img width="424" alt="screen shot 2016-11-11 at 3 55 48 pm" src="https://cloud.githubusercontent.com/assets/2873216/20229974/609b50c4-a827-11e6-8b11-7248c09f9813.png">

OR, making the numbers center aligned:

<img width="414" alt="screen shot 2016-11-11 at 4 01 59 pm" src="https://cloud.githubusercontent.com/assets/2873216/20230118/432fd19e-a828-11e6-871d-f1f4f41235fe.png">

**Comment by jonfroehlich** [comment]
Looks good! Definitely do not center align the numbers. Number needs to be left-aligned to properly compare them across categories.

Can you split up labels by label type in this chart as well using a similar visual design?

**Comment by manaswis** [comment]
Sure, I can.

**Comment by manaswis** [comment]
Updated table looks like this:

<img width="513" alt="screen shot 2016-11-11 at 5 57 29 pm" src="https://cloud.githubusercontent.com/assets/2873216/20232731/640409fc-a838-11e6-92bc-ade2bc886c83.png">

Is this good?

**Comment by jonfroehlich** [comment]
It's great. Can you bold audits row to be consistent.

**Comment by Soben713** [comment]
Maybe if you align them to the left with a fixed margin that would look more structured? I quickly edited it in Photoshop:

![image](https://cloud.githubusercontent.com/assets/1576529/20234163/d7994960-a845-11e6-950c-598300a6d8dc.png)

**Comment by manaswis** [comment]
Yes, that's a great idea. I have updated the table:

<img width="512" alt="screen shot 2016-11-11 at 11 34 28 pm" src="https://cloud.githubusercontent.com/assets/2873216/20235712/a78e45be-a867-11e6-9975-0a2d6ca90bf6.png">

**Comment by Soben713** [comment]
Cool.
