### ISSUE TITLE
Admin Interface: User Table Should Show Last Login for Anonymous

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#365]
As discussed with @manaswis, the User Table should show "last login" for anonymous, which corresponds to the most recent anonymous visitor who labeled at least one thing.

Alternatively, could combine this table with the anonymous user table and make them one thing.

**Comment by manaswis** [comment]
Is resolved with PR #406. Combined this information in the anonymous users table. Screenshot:

<img width="1280" alt="screen shot 2016-11-11 at 2 44 57 pm" src="https://cloud.githubusercontent.com/assets/2873216/20228049/7b5c390a-a81d-11e6-8bd5-7071f3590c44.png">

Closing this one. If any problems are seen, will update #353 (keeping that open till its reviewed).
