### ISSUE TITLE
Remove "cannot go in the direction you want me to walk" option from Jump button

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3676]
##### Brief description of problem/feature
For the past few months, I've been periodically looking at streets where users have been skipping the street because they clicked the jump button and said that they couldn't walk in that direction, hoping to remove any streets that we don't actually have imagery for. But what I've found is that in almost all cases, users _could_ have successfully made it down the street if they clicked the "Stuck" button instead; the issue is just that GSV doesn't have a direct link between two panos for some reason. This means that people are skipping streets that they could normally be auditing, and I'm wasting my time looking at those! 

At this point, I think that we should just remove that option from the Jump button. We can change the dialog to instead just tell users that if it seems like they can't move forward, that they should click the "Stuck" button. And the modal just becomes essentially a "confirm you want to jump" dialog. That way users can still choose to jump to a new part of the neighborhood if they want, but we get to move users towards the Stuck button if the issues is that they're stuck.

Let's also move the Stuck button above the Jump button!

![Screenshot from 2024-10-01 11-06-00](https://github.com/user-attachments/assets/38b87722-74e3-4710-8cdd-1ed553b6a063)

A quick draft of some text / list of changes:
1. "Jump to another location because:" -> "If it looks like you can't move forward, please click the "Stuck" button instead"
1. "I want to explore another area!" -> "I just want to explore another area!"
2. Remove the "I cannot go the direction you want me to walk." button
3. Center the now lone button
4. Rework the logging that should probably be changed because there are no longer multiple options

There's plenty that we _should_ do to redesign this ugly dialog that will look even worse after these changes, but it's not used super frequently, and that's outside the scope of this change that should be pretty quick!

**Comment by jonfroehlich** [comment]
Sounds good!

**Comment by misaugstad** [comment]
@aslassi777 here's your next task!

**Comment by aslassi777** [comment]
thanks! checking it out

**Comment by misaugstad** [comment]
Wait, I was being silly! We should just skip the first "page" of the modal and skip to showing the second page where you decide whether to jump to a new area in the neighborhood vs outside the neighborhood:
![Screenshot from 2024-10-02 12-40-59](https://github.com/user-attachments/assets/ff0f3a6f-af27-4fde-9461-489e54dc83c9)

Updated list of changes:
1. "Go to a new location or a new neighborhood?" -> "If it looks like you can't move forward, please click the "Stuck" button instead"
2. Entirely remove the first page of options
3. Rework the logging that should probably be changed because there are no longer multiple options
4. Probably there are more structural changes to make than just logging since we are simplifying things by having it only be one page. Note that this code is probably pretty gross, and it's worth putting in a little bit of time to clean it up and simplify it!

**Comment by aslassi777** [comment]
sounds good, I will take a look at this today and through the weekend probably
