### ISSUE TITLE
Confirm that Project Sidewalk Data (the Database) is Properly Backed Up

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#369]
I want to confirm that the Project Sidewalk data (the database) is properly backed up and at what frequency. I then want this information fully documented in our documentation.

**Comment by jonfroehlich** [comment]
@Soben713, can you email staff and ask about this and then add this to our project documentation.

**Comment by Soben713** [comment]
@jonfroehlich Just did.

Also, these scripts may be useful:
https://wiki.postgresql.org/wiki/Automated_Backup_on_Linux

**Comment by jonfroehlich** [comment]
Thanks for emailing staff. My understanding is that all of our UMIACS servers are backed up but good to get more details and to document these details in our own documentation.

**Comment by Soben713** [comment]
The database is backed up every day at 5am. It is documented [here](https://docs.google.com/document/d/1bXflDqd-hpFUdcrJUJzJh3CibgDJr_UGjAgxJz4OymU/edit#). I also added the link to the main readme file.

**Comment by Soben713** [comment]
In case my explanation was not clear, the link is also added to the main page of the GitHub repository. Screenshot:

![image](https://cloud.githubusercontent.com/assets/1576529/20231295/a28d50de-a82e-11e6-8707-9fd42336557e.png)

**Comment by jonfroehlich** [comment]
OK, good. Thanks.
