### ISSUE TITLE
Check if we log the clicks for 'Explain this' button

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#372]
Check if we log the clicks for 'Explain this' button. If we don't add this to our logger.

**Comment by Soben713** [comment]
We don't. This is the current events in the database:

1. ViewControl_MouseUp
2. RemoveLabel
3. ModalSkip_ClickJump
4. ModeSwitch_Walk
5. ViewControl_DoubleClick
6. ModeSwitch_NoCurbRamp
7. KeyUp
8. KeyDown
9. Redo_AddLabel
10. ModalSkip_ClickRadio
11. Click_ModeSwitch_SurfaceProblem
12. Click_Redo
13. ContextMenu_RadioChange
14. TaskEnd
15. ModalSkip_ClickOK
16. PopUpMessage_ClickOk
17. RefreshTracker
18. TaskStart
19. Click_ZoomOut
20. Click_Subcategory_Other
21. ContextMenu_CloseButtonClick
22. ContextMenu_TextBoxBlur
23. Onboarding_End
24. ContextMenu_OKButtonClick
25. TaskSubmit
26. WalkTowards
27. ModalSkip_ClickCancel
28. ContextMenu_TextBoxFocus
29. ModeSwitch_CurbRamp
30. Onboarding_Start
31. ModeSwitch_Occlusion
32. Click_OpenSkipWindow
33. Click_Subcategory_NoSidewalk
34. Redo_RemoveLabel
35. Click_ModeSwitch_NoCurbRamp
36. LabelingCanvas_MouseUp
37. ModeSwitch_Other
38. Onboarding_Transition
39. ModeSwitch_Obstacle
40. ModalComment_ClickOK
41. Click_Undo
42. Undo_RemoveLabel
43. ViewControl_MouseDown
44. Click_ModeSwitch_Obstacle
45. Click_ZoomIn
46. Click_Subcategory_Occlusion
47. TaskSkip
48. ContextMenu_CheckboxChange
49. Undo_AddLabel
50. LabelingCanvas_FinishLabeling
51. ModeSwitch_NoSidewalk
52. Click_ModeSwitch_Other
53. ModeSwitch_SurfaceProblem
54. LabelingCanvas_MouseDown
55. MissionComplete
56. ModalComment_ClickCancel
57. Click_LabelDelete
58. Click_ModeSwitch_Walk
59. Click_ModeSwitch_CurbRamp
60. LabelingCanvas_MouseOut
61. Unload
62. ModalComment_ClickFeedback

**Comment by jonfroehlich** [comment]
I just updated @manaswis original comment to be more descriptive and gave the action item to Soheil.

**Comment by Soben713** [comment]
I'll maintain the whole list of events that should be added to the logger in issue #389. Closing this.
