### ISSUE TITLE
About Page Personnel

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#376]
For the About page personnel, we need to add:
- Manaswi
- Ladan
- Soheil
- Anthony

Change the following to ending Fall 2016:
- Daniil Z.
- Possibly Stephanie Nguyen (need to ask her if she still wants to be involved @nguyenist)

**Comment by nguyenist** [comment]
Thanks @jonfroehlich! Pending the priorities, I'm interested and would like to see if it makes sense for me to help out this semester. Want to do whatever is most helpful / realistic for the team. 

- I'm still DC based / working full time in case that's still something to consider for your teams' needs. 
- If there are components on the priority list that could be scoped to UX + UI research / design / front-end changes, I'd love to chat about how best to be involved / meet those goals.  
- Happy to hop on a call sometime. Let me know what works.

**Comment by jonfroehlich** [comment]
@nguyenist, thanks Stephanie. We are still a massively resource-constrained team so any of your talents/time that you'd like to share with us would be helpful. :) You can see UI/UX related Issues here: https://github.com/ProjectSidewalk/SidewalkWebpage/issues?q=is%3Aopen+is%3Aissue+label%3A%22UI+Design%22. Not sure how easy any of these would be for you to contribute to.

Incidentally, @manaswis's primary research focus is on building a suite of Access Score visualization prototypes. Would likely be good to get your feedback on that.

**Comment by tongning** [comment]
Here is the updated page, and the [diff](https://github.com/ProjectSidewalk/SidewalkWebpage/commit/10f2db8113cc80b769bed4038863b5222068d734). It would be great if everyone could review it (for both style and content) before I submit the pull request.
![about-updated](https://cloud.githubusercontent.com/assets/7234278/20040122/b08e3756-a41f-11e6-8d58-c9929aa3037a.PNG)

**Comment by jonfroehlich** [comment]
Looks good.

Quick things.
- Is 'Alumni' an H2? It should be a sub-header under Team Members
- Let's try and add semester prefixes whenever possible (to be consistent)
- Spring 2012 for me and Kotaro
- Fall 2013 for David Jacobs
- Fall 2016 for Manaswi and Soheil
- Summer 2015 for Ladan
- Remove 'Project Lead' from Kotaro

**Comment by tongning** [comment]
Updated. Team Members was an h2, so Alumni is an h3 now.
![about-2](https://cloud.githubusercontent.com/assets/7234278/20040812/31deb18a-a42c-11e6-88ce-0f32ef5448aa.PNG)

**Comment by jonfroehlich** [comment]
Jin should be Spring 2013 to Fall 2014

I think the Sponsors should also be left aligned rather than center aligned... but can't be sure without seeing it.

**Comment by tongning** [comment]
Updated:
![about-3](https://cloud.githubusercontent.com/assets/7234278/20069427/837e8a4c-a4ea-11e6-9a1c-b3118886d6da.PNG)

**Comment by jonfroehlich** [comment]
Perfect. This is ready to ship now.
