### ISSUE TITLE
Pixelated GSV images introduced with #3626

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3762]
I just started using PS for the first time after #3626 and I noticed (to me), a big problem. The GSV window in PS is now pixelated regardless of browser window size or laptop screen size.

Take a look at what is now the PS view:
![image](https://github.com/user-attachments/assets/7e95148f-e587-466d-b5f3-b097baea6ac6)

vs. [the actual GSV view](https://www.google.com/maps/@40.9010019,-74.0158767,3a,90y,267.73h,74.17t/data=!3m7!1e1!3m5!1sfCssctMO3cN2xzWNm4satA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D15.832267447624915%26panoid%3DfCssctMO3cN2xzWNm4satA%26yaw%3D267.72825078956896!7i16384!8i8192?entry=ttu&g_ep=EgoyMDI0MTIwMy4wIKXMDSoASAFQAw%3D%3D):
![image](https://github.com/user-attachments/assets/4620f903-0cbc-4172-a69d-f66360982e25)

Notice how pixelated the road name and stop sign are. Something is happening with @jsomeara's code where it's not properly scaling the GSV window and, instead, is just doing a pixelated zoom. It makes everything on my monitor look grainy.

OK, here's zoomed in side-by-side comparison with PS on the left and GSV on the right. You should open the image in a new tab (or download it to zoom in and see details).

![image](https://github.com/user-attachments/assets/f0ad40a3-3151-4b0c-98c9-4e9658c527a3)

To me, this impacts not just the experience of PS auto-scaling on a large monitor 27" but also the experience when I'm using my MacBook Pro laptop (ordinary window size). The quality of the GSV imagery is reduced. Something is happening here.

Here's the location from above. Note: this is quite evident across two cities I tried and every pano I loaded.

```
City: Teaneck, NJ
Latitude: 40.90100188483349°
Longitude: -74.01587667926636°
Panorama ID: fCssctMO3cN2xzWNm4satA
Street ID: 1401
Region ID: 14
GSV URL: https://www.google.com/maps/@?api=1&map_action=pano&pano=fCssctMO3cN2xzWNm4satA&heading=267.2087500000017&pitch=-16.959999999999884
```

**Comment by misaugstad** [comment]
And another problem, when I tried to look at this street directly using https://sidewalk-teaneck.cs.washington.edu/audit/street/1401, it's using auto-zoom! :joy:

**Comment by misaugstad** [comment]
Reverted in #3763 

Grainy vs clear:
![Screenshot from 2024-12-04 14-04-31](https://github.com/user-attachments/assets/debc47dc-8c23-4944-b5c2-e5d30731b459)
![Screenshot from 2024-12-04 14-04-37](https://github.com/user-attachments/assets/efddb51d-4238-45c5-a95d-47b74dca34c5)
