### ISSUE TITLE
Admin Interface: Playback Labels Don't Look Correctly Placed

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#385]
Not sure if this is just the user I am watching or if our math is wrong is placing the labels on the GSV view (see screenshot; note how the green labels seem to be above the actual curb ramp locations).

![image](https://cloud.githubusercontent.com/assets/1621749/19838412/13700474-9ea5-11e6-842e-1628ed01f088.png)

**Comment by Soben713** [comment]
I've also noticed it. Will look into it.

**Comment by Soben713** [comment]
Pull request #416 fixes this.
