### ISSUE TITLE
Admin Interface: The Avatar Dot Disappears in Soheil's Task Playback Tool

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#390]
I didn't have a chance to take a screenshot or movie recording but I've found that--quite frequently--the avatar dot disappears in @Soben713's new task playback tool. @Soben713, have you seen this?

**Comment by Soben713** [comment]
Yes, I've seen it many times as well. Will look into it.

**Comment by misaugstad** [comment]
I've done a rework of this page in the past and don't remember seeing it since then. Plus no one really uses this page, though I wish I remembered to use it more! Will reopen or create a new ticket if I ever see something like that again.
