### ISSUE TITLE
Login Timestamp Strangeness

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#393]
Note how the grantdmckenzie user has labels timestamped from 10/31/2016 but has only logged in once, which was on 10/28/2016. Is this a case where perhaps he kept the window/tab open in his browser?

![image](https://cloud.githubusercontent.com/assets/1621749/19899923/2f57f108-a038-11e6-9213-d4cbe9e187d4.png)

**Comment by misaugstad** [comment]
This is almost certainly a case of the user leaving the tab open in their browser for a few days. Do you want anything to be done about this, or should I close this issue?

**Comment by misaugstad** [comment]
I'm going to close this for now. It was more of a question that has been answered, and less of a bug. Feel free to reopen if something should be done about it.
