### ISSUE TITLE
Admin Interface: Label Info Dialog Box GSV Blank

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#394]
Sometimes the GSV pane pane is blank in this pop-up window--I can't tell if there was a load error or if the panorama no longer exists or what. Is there anyway to surface more info to the admin user?

![image](https://cloud.githubusercontent.com/assets/1621749/19903211/2e4a3a26-a044-11e6-8df9-2f2fc0478e41.png)

**Comment by Soben713** [comment]
Will look into it.

**Comment by misaugstad** [comment]
This has been fixed!
