### ISSUE TITLE
Avoid triggering admin map refresh when checkboxes are clicked

### ISSUE THREAD

**Issue by tongning** [ProjectSidewalk/SidewalkWebpage#395]
Currently all markers are on a single layer, so when the user selects or deselects a marker type the entire layer needs to be removed and redrawn. It would be preferable to separate the marker types onto different layers so that marker types can be shown or hidden without a map refresh.

**Comment by jonfroehlich** [comment]
Yes! :)

**Comment by manaswis** [comment]
This is resolved in the issue #506 and PR #526. Closing this.
