### ISSUE TITLE
Audit tasks completed by anonymous users are erroneously marked as incomplete

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#403]
The database table `audit_task` that maintains the list of tasks audited by all users has a column 'completed' that indicates if the street segment has been audited. Currently, even if you complete an audit of a street, they are not being marked as 'complete' in the table.

This also affects the calculation of number of contributing/visiting anonymous users, which we probably should discuss. Adding a comment in the respective issue thread #323.

Following is a screenshot of the database table:

<img width="1043" alt="anon_user_task_complete_error" src="https://cloud.githubusercontent.com/assets/2873216/20196661/afa4e6b2-a769-11e6-9b3f-7389a7fcc721.png">

**Comment by jonfroehlich** [comment]
I don't understand your comment. The first paragraph, in particular, doesn't make sense to me. Are you stating that the 'completed' field in the database is not being set correctly for anonymous users but works for signed-in users?

**Comment by manaswis** [comment]
Yes, that's what I meant.

**Comment by jonfroehlich** [comment]
OK, yes, please investigate why this is and its implications on our analysis, etc.

**Comment by jonfroehlich** [comment]
Also, please set up a milestone for this (either v2 or v3 depending on severity).

**Comment by manaswis** [comment]
Since this bug will affect the way we do data analysis, I have added a note to the [developer notes stored in the wiki](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Developer-notes).

**Comment by jonfroehlich** [comment]
Your explanation in the wiki makes it seem like there is a difference here between v1 and v2 but I didn't think there was a difference, just that nobody noticed this problem before.

![image](https://cloud.githubusercontent.com/assets/1621749/20901335/0cea676c-bb00-11e6-958d-a00659efe3b5.png)

**Comment by manaswis** [comment]
Yes, there isn't a difference. That's why I clubbed both releases together. I could remove v1 if that will make it more clear.
