### ISSUE TITLE
Change jumping mechanism in the system

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#408]
Frequent jumps while auditing is annoying and many users (>4/10 434 students) in our usability studies have that pointed out. Jumps usually occur when the routing algorithm places the user either near the boundary of a neighborhood or when all connected routes around the user's current location are audited and (s)he is moved to a new location. This becomes even more frequent when you are nearing neighborhood completion. This dramatically reduces user experience esp for users who actively contribute.

Based on today's discussion in the meeting, here is the **solution**:

**Idea**: Not to automatically jump the user but give the user an option to label the intersection before instructing the user to jump.

**Steps**:
1: Determine the jump location

> **TODO**: Implement the required mechanism

2: At the jump location, give the user a message (bottom right corner of the GSV screen) telling the user to finish labeling this location and then click on that message to jump 

> **TODO**:  brainstorm the message text

3: If the user moves far from the jump location after labeling, then show the modal message that “we are jumping you to a new location” 

> **TODO**:  
(1) Implement the required mechanism to track user's actions at the jump location, and
(2) brainstorm this jump message text - #286

This will also resolve issues #275, #314 and #286.

**Comment by jonfroehlich** [comment]
Nice post. We already brainstormed the pop-up text and I think Soheil copied it into his localhost. We just have to figure out if we can shorten it and, if not, how to adapt the CSS so that the pop up grows vertically and not horizontally.

**Comment by Soben713** [comment]
I just typed it in the inspector to see how it looks and unfortunately did not copy it elsewhere.

**Comment by jonfroehlich** [comment]
@manaswis, I just thought of this on my bike to work this morning: I think we should *log* when we show this message to the user, when it starts to blink, and when the user actually clicks on it. I want to study whether users click on the message almost immediately or whether they do what we actually want, which is to audit that remaining area and then jump. 

I feel like our solution is somewhat confusing/ambiguous now as we never tell the user when they are really supposed to jump. We leave it up to them, which feels wrong to me.

**Comment by manaswis** [comment]
Yes, we should do that. The blink part might be a bit trickier since that's controlled by the JS timer but its doable. We need to add a few other listeners to specifically track the blinking during the jump.

**Comment by manaswis** [comment]
One idea is: To inform them as an instruction/information beforehand that there would be situations where they might have to jump because streets around them would already have been audited and they will have to be moved to an unaudited area of the neighborhood. This would let at least tell them, in advance, why the jumps are happening and why they have to perform the jumps.

When this information is given to the user needs to be thought about. Eg. we could show them in the beginning e.g. during the first few steps even though its already a bit heavy on instructions. 
OR
just before the first jump for that user -- this would actually be more useful and contextual.

**Comment by jonfroehlich** [comment]
I don't think we need to clarify *why* they need to jump. To me, this is not the confusing part. The confusing part is that its ambiguous when they are actually supposed to choose to jump.
