### ISSUE TITLE
Admin Interface: Coverage Rate per Neighborhood Graph

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#412]
![image](https://cloud.githubusercontent.com/assets/1621749/20248653/8da89172-a9b6-11e6-9a87-041653643e6c.png)

A few things:
- Graph should switch x and y axes. Y-axis should be neighborhood names and x-axis should be completion rates. This would make the neighorhood names far more readable
- Graph should be sortable by percentage complete and by neighborhood name (currently defaults to latter). This should be interactive.
- The y-axis title (currently 'neighborhood coverage rate (%)') should be outside of y-axis to the left of the axis labels rather than inside the graph where it could collide with data

**Comment by misaugstad** [comment]
This was covered again in issue #342 and then resolved in PR #692
