### ISSUE TITLE
Admin Interface: Pop-Up Label Examiner Window

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#415]
The pop-up label examiner window, which comes up when you click on a label in the Admin Interface map, has incorrectly placed labels. The math looks off. For example, in the screenshot below, the orange label should be where my mouse cursor is and not on the fence. This is related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/385 and I'm guessing the same placement function (underlying math) is used for both.

![image](https://cloud.githubusercontent.com/assets/1621749/20281807/f43f9632-aa7f-11e6-9c43-69cf761fbd2d.png)

Would be great to get @kotarohara's help on this because I'm guessing this is something that wouldn't take him too long to fix, since he implemented the label placement code originally.

**Comment by kotarohara** [comment]
This is probably due to using different projection mode used in `Admin.Panorama.js`. I sent the PR. @Soben713 , can you check if the change fixes the problem?

**Comment by Soben713** [comment]
@kotarohara Interesting. I quickly tested it on my localhost and it certainly improves it. But It doesn't completely resolve it.

This is the test:

Original labels:
![image](https://cloud.githubusercontent.com/assets/1576529/20292155/41652e3e-aab9-11e6-9c31-4d5cf3275824.png)

Without your changes
![image](https://cloud.githubusercontent.com/assets/1576529/20292120/ffc0f878-aab8-11e6-9f68-5af86c83c28f.png)

After your changes:
![image](https://cloud.githubusercontent.com/assets/1576529/20292071/be623194-aab8-11e6-9531-9856085a549a.png)

**Comment by Soben713** [comment]
Changed the aspect ratio of the panorama holder and it solves the problem. Here is the result:
![image](https://cloud.githubusercontent.com/assets/1576529/20292696/c697bbf4-aabd-11e6-8a43-2b1e97db8dcc.png)

**Comment by Soben713** [comment]
The pull request was merged. Closing this.

**Comment by jonfroehlich** [comment]
@Soben713, aha, I see that you did indeed test this. Nice job!
