### ISSUE TITLE
The cursor for panning Street View

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#42]
When the mouse cursor is in the Street View pane while in the Walk mode, the cursor should be a hand icon instead of an arrow icon.

**Comment by nguyenist** [comment]
seems to be working 4/9

**Comment by nguyenist** [comment]
will check tutorial

**Comment by nguyenist** [comment]
I may have figured it out.

in `Map.js` line 674:
Change
```
            setViewControlLayerCursor('default');
```
To
```
            setViewControlLayerCursor('OpenHand');
```

**Comment by nguyenist** [comment]
@kotarohara does changing the default to OpenHand make undesired effects elsewhere? What is your intention for when the cursor should be a pointer vs. open hand?

**Comment by kotarohara** [comment]
@nguyenist Thanks for the update. The cursor icon should be OpenHand only if the mouse is on the Street View pane while you are in the walking mode.

**Comment by nguyenist** [comment]
Hey @kotarohara I have been looking at this issue for awhile. Not quite sure I can replicate the problem. Can you tell me where the cursor is a default where it should be openhand?  See screenshot.
![screen shot 2016-04-17 at 2 01 46 pm](https://cloud.githubusercontent.com/assets/4484141/14588977/1b76bf0e-04a5-11e6-9d0f-496119dd05e4.png)

**Comment by jonfroehlich** [comment]
I think it might be a Mac vs. Windows thing. Looks like your screenshot is from a Mac, did you try with Windows?

Also, we should test with Chrome and Firefox (or other popular browsers--maybe Safari on a Mac).

**Comment by nguyenist** [comment]
@jonfroehlich This was with Mac on Chrome. I can try Mac on Firefox / Safari. I don't have a windows device.

**Comment by jonfroehlich** [comment]
I have Windows and I have experienced this problem.

**Comment by kotarohara** [comment]
This is most likely happening only during onboarding. 

@nguyenist , I think you are right about the `setViewControlLayerCursor('OpenHand')` vs `setViewControlLayerCursor('default')` . Something is not going right in that function during the onboarding and it's not properly changing the mouse cursor. I checked out `steph-version` and tried the onboarding but the problem is still there. Could you look into this when you get a chance?

Note, to work on the onboarding tutorial, log out and go to the page as an anonymous user. Also, your may need to call `svl.storage.clear()` to clear the cache which might remember you finished the onboarding.

**Comment by nguyenist** [comment]
@kotarohara Yes I did notice the cursor is `default` during onboarding. Just checked and this behavior happens on Chrome + Firefox + Safari.

The photo I attached was showing the `OpenHand` after onboarding. Will look into the `svl.storage.clear()` tomorrow after work!

**Comment by kotarohara** [comment]
@nguyenist Awesome! Thanks :)

**Comment by nguyenist** [comment]
What is the function that is called when you are onboarding with the tutorial? Is it the same function that is being called when you have already completed onboarding and are just "auditing" in general?

**Comment by nguyenist** [comment]
There seems to be 2 different .js files being loaded. Tested
![image](https://cloud.githubusercontent.com/assets/4484141/14693497/7a1420e4-072d-11e6-89f5-1c1141defae0.png)
with "true" and "null" and it seems like different files or functions being pulled. If I knew the functions / files you are using for when you haven't onboarded vs you have, then I can try to figure out the code that is calling the default cursor.

**Comment by kotarohara** [comment]
I thought I fixed this and closed this issue... Maybe there was a duplicate. I'm closing it now.
