### ISSUE TITLE
Street View image not available for some old tasks/labels

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#423]
The Street View image becomes black for old labels/tasks. 
Check this for an example: http://sidewalk.umiacs.umd.edu/admin/task/1501

<img width="757" alt="screen shot 2016-11-15 at 7 44 54 pm" src="https://cloud.githubusercontent.com/assets/2873216/20330339/1a393324-ab6c-11e6-8bf4-90cbab966079.png">

Is the image being invalidated by Google?

**Comment by jonfroehlich** [comment]
I believe this is a known problem (and one of the reasons why I wanted to download the panoramas or, at least, a rectangular boundary area around every label). @Soben713, didn't you already mark this as an Issue or did we simply discuss it?

**Comment by misaugstad** [comment]
This is covered by issue #539 and a pano scraper has been set up, with the code in [this repo](https://github.com/ProjectSidewalk/sidewalk-panorama-tools), so I'm closing this issue.
