### ISSUE TITLE
GSV Updates from Google: Check all Sidewalk calculations work properly

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#424]
Google just pushed their changes to their APIs. We are now receiving new images with enhanced features (e.g. streets labeled with street names, walking through the streets is way smoother etc.)

We need to make sure that the changes haven't broken any of the calculations we make in our system.

Things to check (not exhaustive - will keep updating it):
- label placement calculations
- it looks like the arrow placement in the tutorial is broken
- touchscreen support.

[Add more...]

**Comment by jonfroehlich** [comment]
I just checked on my mobile phone and one cool thing is that the motion sensor in the phone now can control your view (this is neat). Downside is that the GSV pane frequently goes all black. So we should definitely test if touchscreen support is broken.

**Comment by jonfroehlich** [comment]
It looks like placed labels in the GSV pane do not 'stick' to their position as well with the new GSV API. See video: https://youtu.be/ll_OFFjxHo0

I'm going to open up a new Issue for this.

**Comment by kotarohara** [comment]
@manaswi, I actually tried to find the Google's notes about the update to the Google Maps API. I cannot find it. Can you share the link?

**Comment by manaswis** [comment]
Recent release v2.1 resolves these issues.
