### ISSUE TITLE
The Tip Box Key Press Recommendation is a Bit Ambigious

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#428]
We need to say 'You can also press the *O* key...' without the word key, this tip box is confusing. I think the key icon itself should also look more like a key. Something more like: 
![image](https://cloud.githubusercontent.com/assets/1621749/20345480/5f9cb8d8-abc5-11e6-9a1a-15b51f4ea5c9.png) or 
![image](https://cloud.githubusercontent.com/assets/1621749/20345496/69ada6ac-abc5-11e6-9e7b-609caab78fff.png)

![image](https://cloud.githubusercontent.com/assets/1621749/20345517/7ba27a72-abc5-11e6-891b-728799cb3fd1.png)

**Comment by jonfroehlich** [comment]
Even the github tip box shows better key icons (that indicate a keyboard key):

![image](https://cloud.githubusercontent.com/assets/1621749/20351196/d53e7102-abdf-11e6-8c34-e1dca1ec15d2.png)

**Comment by Soben713** [comment]
Yeah, I like Github's keyboard buttons. I'll do something similar.

**Comment by Soben713** [comment]
Also, do you mean we should remove the second part that explains what happens if you press that key?

**Comment by jonfroehlich** [comment]
I don't know what you mean by "Also, do you mean we should remove the second part that explains what happens if you press that key?" so I don't think so.

**Comment by Soben713** [comment]
So, how about this?
![image](https://cloud.githubusercontent.com/assets/1576529/20365590/6caa952c-ac15-11e6-9b89-29e2166df5a6.png)

 The bounding box is now a square and it has a bottom shadow.

**Comment by jonfroehlich** [comment]
We need to say:

"You can also press the *C* key for selecting the "Curb Ramp" label."

**Comment by Soben713** [comment]
@jonfroehlich Right. Updated the pull request.
