### ISSUE TITLE
GIS Day Usability Observations

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#430]
**Tutorial Problems**
About half of the room (maybe ~15 users) failed to get through the tutorial for a mixture of the following reasons:

- The most common problem was that users did not understand which direction to pan when they saw the animated hand. Most users intuitively panned in the direction of the hand movement and not counter to the hand movement. (#437)
- Another very common problem (perhaps even more common now that I think about it) is that the tutorial arrows were almost always drawn in the wrong place. Not sure if this is related to the GSV API being updated. https://github.com/ProjectSidewalk/SidewalkWebpage/issues/424 -- FIXED (v2.1 release)
- One person used Internet Explorer and things looked very broken. Perhaps we need to warn users to switch to a different browser. (#545) -- FIXED (v3.1.2 release)

**Observations During Labeling**
- I had a number of questions about 'should I label this?'

- I noticed one user didn't realize he needed to label an entire intersection and, instead, just labeled the curb ramps in his current view

- One user kept clicking on the pop-up turn-by-turn directions. I think it would be great to make this clickable and it would automatically orient you in the direction that you need to go or, if it's pointing straight ahead, would move you in that direction. Just a thought.

**Comment by manaswis** [comment]
Also, to add, the labels added by people might not be good. So for analysis, we might have to ignore labels submitted today (Nov 16, 2016).

**Comment by jonfroehlich** [comment]
@manaswis, but that's always the case. We have no reason to believe that the people from today are any better or worse than a normal online user.

**Comment by manaswis** [comment]
That's true. This comment was based on a comment you made in one of our meetings today that we might have to ignore the labels from today (probably, it would also because of the new version of GSV that was used in the first half). I will update the comment to add that fact. I logged it here so that we can refer to it when we do the actual analysis.

**Comment by jonfroehlich** [comment]
Yep, my comment was more with regards to the GSV API switch than with the users. :)

**Comment by manaswis** [comment]
Updated the comment. Thanks for pointing that out. I missed the crucial part of the message :)

**Comment by misaugstad** [comment]
All 3 of those issues have been addressed! The first one by restricting panning to only one direction.
