### ISSUE TITLE
Admin Interface: Timestamps in Recent Labels Table in Local Timezone?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#433]
It looks like the timezone is wrong for the timestamps in the Recent Labels table. I'm not sure if all timestamps are stored as UTC in the database and then translated into the admin user's home timezone when presented, but there is some sort of error here. Note that it shows 11/16 at 5:33PM but it's not even 2PM here yet!

![image](https://cloud.githubusercontent.com/assets/1621749/20361049/20a59c32-ac04-11e6-9979-09a24cca2307.png)

**Comment by manaswis** [comment]
Not sure, why this is problem happened on this day. I tried again by adding labels. They have the correct timestamp.

![screen shot 2016-11-18 at 6 01 53 pm](https://cloud.githubusercontent.com/assets/2873216/20450382/16de8806-adbe-11e6-8154-d062bd596f86.png)

I'll look into the timestamps of those labels in the database next.

**Comment by misaugstad** [comment]
This issue has come up again just now. It is only happening for a single user. The timestamps for their labels and their audit task interactions are not in UTC (they are 13 hours ahead, I believe), but the task_start and task_end are correct. The difference between those two groups is that the former has the timestamp created on the front-end, while the latter is created on the backend right before making the update.

Do we have any ideas for why this might happen to a single user?

**Comment by misaugstad** [comment]
@lstrobel seems to be having the issue of timestamps being recorded in local time on his machine right now! Perfect time to investigate why and/or try to fix it to ensure it is put into UTC!

**Comment by misaugstad** [comment]
Awesome, thanks y'all!

**Comment by misaugstad** [comment]
closing via #1389
