### ISSUE TITLE
Tutorial: Improve instructions for panning

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#437]
From my GIS day observations, a very critical thing emerged: roughly half of the users I observed (~8 people) could not figure out what the panning animation meant in the tutorial and started to pan in the wrong direction. Rather than panning to the left (as the animation suggests), they panned in the direction of the hand movement (so, they panned to the right). This is a significant problem!

Two things that I think we should do to fix this:

- Have an arrow on the left side of the GSV pane that says something like "Pan this way" or "Pan to the left" or "Pan to the left by clicking-and-dragging the interface"

- If the user pans in the wrong direction, we should stop them (after some degrees of panning in the wrong direction) and put up a notification that tells them to pan in the other direction and/or gives them a button to click on to reset their view to the correct orientation

**Comment by jonfroehlich** [comment]
An update on this. Over Thanksgiving, I had one family member try our interface. She is a science graduate student. Though not in CS, she is fairly technical. She was also confused by the panning animation and could not finish the tutorial. Indeed, she ended up turning the wrong way and labeling features and getting more and more confused until she wanted to quit. She was quite frustrated.

**Comment by manaswis** [comment]
Updating this point with Jon's recent comments:

1) a check to make sure the user is panning in right direction
2) in addition to hand animation, display an arrow (possibly with text) that shows which direction to pan. arrow could animate

This is inline with Jon's original issue post.

**Comment by manaswis** [comment]
More details from Issue #531:

>Jon: In our user testing, I observed a very common problem: users would misperceive the panning hand animation to mean that they should pan to the right ---> rather than the appropriate pan to the left <---. We need to do two things: (i) add an additional arrow that tells the user where to pan (not sure on language here)--see drafty mockup below; (ii) if they start panning the wrong way, pop up a more salient and helpful message that helps them correct this action; (iii) if they continue panning the wrong way, auto-pan the right way all the way to appropriate spot. We could also consider a different animation than the hand thing since that seems confusing.
>![image](https://cloud.githubusercontent.com/assets/1621749/24000061/8cdf9788-0a30-11e7-95db-a56b36dc7474.png)

>Manaswi: Existing issue #437. The problem with panning is the users have to pan the opposite direction to the way they want to go. E.g. to see the next intersection in the tutorial, they have to drag to the right to move left, which is why they get confused. So adding an arrow saying "Pan" might not help. We could add to the instruction text that "Drag to the right to move left" or something like that and show the arrow in the direction of the drag (and inside the arrow, add the appropriate text like you showed).

**Comment by manaswis** [comment]
# Mocks
In the mocks, the instruction text has a word in orange. That's the word I want feedback on. We have considered panned (personally don't prefer), dragged, looked, went and moved.

This is what I found for the word 'pan':
![image](https://user-images.githubusercontent.com/2873216/26854364-d9c79dfe-4ae3-11e7-9305-4275471f7353.png)

Source: Visual Thesaurus.

## **1**
![image](https://user-images.githubusercontent.com/2873216/26854145-e32ac32c-4ae2-11e7-8a8f-d4d107799970.png)

## **2**
![image](https://user-images.githubusercontent.com/2873216/26854427-1e0e9f3a-4ae4-11e7-92e3-3ef4471506ae.png)
Used a different type of arrow that has a little "motion" in its design.

## **3**
![image](https://user-images.githubusercontent.com/2873216/26854451-34ac9c10-4ae4-11e7-9824-622cc8c86fda.png)
Text within the arrow

## **4**
![image](https://user-images.githubusercontent.com/2873216/26854459-3e982c80-4ae4-11e7-82ba-453d08abe1d5.png)
Text below the arrow. Least preferred.

@everyone: Which mock do you like the most?

**Comment by misaugstad** [comment]
For context, the current instruction before this says "Let's adjust the view to look at another corner of the intersection on the left. **Grab and drag the Street View image**."

When they pan the wrong way, why not just say
"Oops! Try dragging in the other direction" or
"Oops! Try dragging the other way" or 
"Oops! Try dragging the opposite direction"

I'm not sure that we need to explicitly tell them that they panned/went/looked/turned the wrong way; is it not clear enough to give them an instruction, then when they try to do it backwards, saying "oops! try doing it the other way"?

Side note: In the instruction before this, do we need to say "Let's adjust the view to look at another corner of the intersection..."? Can we cut it down to "Let's look at another corner of the intersection..."?

**Comment by misaugstad** [comment]
Also not sure how important it is that we use the words "Street View image" when we originally tell them to click and drag.

**Comment by jonfroehlich** [comment]
> Also not sure how important it is that we use the words "Street View image" when we originally tell them to click and drag.

What would we say instead?

**Comment by jonfroehlich** [comment]
I like @misaugstad comment here https://github.com/ProjectSidewalk/SidewalkWebpage/issues/437#issuecomment-306639290. I think that makes sense. We immediately pop-up a message that says:

> "Oops! Try dragging the other way"

I also think having the arrow is still helpful, perhaps with overlaid text that says "Look this direction" or "Pan this way."

**Comment by manaswis** [comment]
Updated mock:

![image](https://user-images.githubusercontent.com/2873216/26858231-07b6264e-4afe-11e7-8014-6216f9fa3682.png)

>Side note: In the instruction before this, do we need to say "Let's adjust the view to look at another corner of the intersection..."? Can we cut it down to "Let's look at another corner of the intersection..."?

@misaugstad I think "Adjust the view" was used to train the users that the screen can be panned.

**Comment by jonfroehlich** [comment]
We mocked this up in my office (note that the arrow could also animate a bit by fading in some N pixels from the left border and then animating to the left to the position captured in the mock)

![image](https://user-images.githubusercontent.com/1621749/27244072-eff70cbe-52b2-11e7-9a96-8064bbfb732e.png)

**Comment by manaswis** [comment]
Closed via #696 and #701.
