### ISSUE TITLE
Tutorial Redesign: Discussion Thread for Ideas

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#439]
During v2 testing, we found multiple problems with the onboarding tutorial, of which few parts would require a redesign. Some of them that we found are listed here:

- Direction of panning wasn't clear to many users -- needs to be made more clear of which direction to pan
- The "you have already labeled this corner so you do not need to label it again" does not clearly onboard people that their labels will disappear. This is too subtle, especially since the step that they take is so small
- The arrow placements were incorrect -- needs to be fixed (and I believe we don't count a placed label unless it is within a certain distance of an arrow, which can make things really confusing when the arrows don't line up)
![image](https://cloud.githubusercontent.com/assets/1621749/20373677/5762893c-ac41-11e6-87f3-7836d7a0f503.png)
- Learning to walk isn't great -- needs to be redesigned

Some of my personal thoughts:
- We could decrease the number of curb ramps to mark -- we currently have 4 curb ramps being marked. I understand the point is to teach them to *completely* label an intersection, but when the user is doing the tutorial (I feel they might get the idea that we are teaching them "how to label" and  they have already learnt that by applying the first 3 labels). Not sure. What do you think? 

- The third corner of the intersection where two ramps need to be marked, the order in which the tutorial asks the user to do is reverse. The arrow close to the user should be labeled first. This would also solve the problem of the top-left instruction box overlaying over the label box as seen in the figure below:

![screen shot 2016-11-16 at 6 38 08 pm](https://cloud.githubusercontent.com/assets/2873216/20370995/bce80e1a-ac2f-11e6-8ce4-7c9da8587306.png)

 [Here](https://github.com/ProjectSidewalk/SidewalkWebpage/issues?q=is%3Aopen+is%3Aissue+label%3AOnBoarding) are the issues that are related to onboarding.

**Comment by jonfroehlich** [comment]
We continue to collect evidence that our initial tutorial is, unfortunately, broken for quite a few users. Here's some more:

![image](https://cloud.githubusercontent.com/assets/1621749/21075485/6fbb8800-bee1-11e6-9b18-1f5b3eba7100.png)

We really need to fix this for v3.

**Comment by manaswis** [comment]
All of these mentioned ideas have a corresponding issue. See #531. Closing this issue.
