### ISSUE TITLE
Landing Page Icons Not Scaled Correctly in Microsoft Edge

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#449]
![image](https://cloud.githubusercontent.com/assets/1621749/20577166/1c4b9444-b18f-11e6-880b-1bfea4f2707d.png)

**Comment by jonfroehlich** [comment]
Since we are not supporting Microsoft Edge currently, I won't post this as a separate Issue but currently the mouse cursor does not change correctly in Edge when you have a label selected (it just stays as a pointer).

**Comment by manaswis** [comment]
Since the landing page has been updated, this issue has become outdated.  Also, the issue mentioned in the next comment is captured in #638. Closing this.
