### ISSUE TITLE
tutorial: double click -> click on the curb ramp to label it // not sure where curb ramp is

### ISSUE THREAD

**Issue by nguyenist** [ProjectSidewalk/SidewalkWebpage#45]
![image](https://cloud.githubusercontent.com/assets/4484141/14406646/6bee6804-fe7b-11e5-86d6-63643b9ac0a9.png)

**Comment by kotarohara** [comment]
It's not really a bug as in there is no error. But it it true that we need to better navigate the user if the arrow is not visible in the current point of view. Easy solution would be that we force the point-of-view to face the target curb ramp.

**Comment by kotarohara** [comment]
I fixed this issue. Now when you hit this stage the interface should auto-focus on the target curb ramp.
