### ISSUE TITLE
GSV Pane Just Went Black

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#451]
GSV pane just went blank while auditing. 

Console says: "Failed to load resource: the server responded with a status of 500 ()"

![image](https://cloud.githubusercontent.com/assets/1621749/20583562/34695a00-b1b9-11e6-89a4-74721001dbd0.png)

Could we catch that this is happening and try to call the API again?

**Comment by manaswis** [comment]
This looks like the error we saw when pano ID was not available. Closing this.

**Comment by jonfroehlich** [comment]
@manaswis Where and how was this fixed? You said 'this looks like the error we saw when the pano ID was not available' but you didn't provide further context about how this was actually addressed...
