### ISSUE TITLE
Tutorial: Show tutorial interface immediately instead of loading GSV Interface first

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#454]
As a first-time user, after you click Participate, the GSV interface confusingly shows briefly before the tutorial. This should not happen. It's confusing and disorienting. The tutorial interface should come up immediately.

https://youtu.be/_JdAOQMM3VQ

**Comment by manaswis** [comment]
Closed via #658
