### ISSUE TITLE
Onboarding labels getting logged -- is this correct?

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#460]
Just wanted to clarify if this is the right behavior:

I was going over some of the labels added by users who contributed today and I observed the labels are from the onboarding location for all of them. For some, those are the only labels (i.e. they didn't audit further after finishing onboarding). Are we supposed to log them into the database?

User 1: 
![screen shot 2016-12-01 at 1 35 29 pm](https://cloud.githubusercontent.com/assets/2873216/20807086/84dcf8ee-b7cb-11e6-9619-249f909d09cc.png)

User 2:
![screen shot 2016-12-01 at 1 35 50 pm](https://cloud.githubusercontent.com/assets/2873216/20807088/84e78ec6-b7cb-11e6-878a-158accd22310.png)

User 3:
![screen shot 2016-12-01 at 1 36 51 pm](https://cloud.githubusercontent.com/assets/2873216/20807089/84f23da8-b7cb-11e6-88f8-a95c5cf9135c.png)

**Comment by jonfroehlich** [comment]
Absolutely. We want to be able to investigate things like: onboarding performance vs. actual performance.

I guess the question in my mind is:  why _wouldn't_ we log this? IMO, we should be logging as much as possible to better understand how users behave, how to potentially improve our system, and to enable us to answer our research questions (both current and future).

**Comment by manaswis** [comment]
Right, it makes sense. We can also track how many users move from onboarding to the actual auditing of streets with the help of these. Thanks!

**Comment by jonfroehlich** [comment]
Also, when posting screenshots of our admin data, do try to block out identities if possible (and especially emails).

**Comment by manaswis** [comment]
Sure, I'll update the above screenshots accordingly.
