### ISSUE TITLE
Add Hover Tooltips to Other Buttons that Have Keyboard Shortcuts

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#461]
You can press 'Z' to zoom but there is no hover tooltip for this for some reason.

![image](https://cloud.githubusercontent.com/assets/1621749/20810024/ec489dee-b7d5-11e6-8a06-c7b33630c3f3.png)

**Comment by jonfroehlich** [comment]
@Soben713, even though this is marked as v3, you said you would do this as v2. Do you plan to do it or not? If v3, then we obviously have to unassign you as you are leaving the team.

**Comment by Soben713** [comment]
@jonfroehlich Done.

**Comment by jonfroehlich** [comment]
Thanks! Can you push this to sidewalk-dev so we can test?

**Comment by Soben713** [comment]
@jonfroehlich Can't do it right now because it requires rebranching the hotfix first (I've been discussing the correct way to do it with Manaswi). But I'll try to finish it tonight.

**Comment by jonfroehlich** [comment]
Ok. No biggie. Thanks.

**Comment by Soben713** [comment]
The pull request for this issue and the hotfix are now merged into develop. The next deployment to the test server will contain both changes. Will have to discuss the correct way of deploying to the test server tomorrow with Manaswi.
