### ISSUE TITLE
Are We Logging When People Self-Select Their Own Audit Neighborhoods?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#464]
Are we logging when people self-select their own audit neighborhoods?

![image](https://cloud.githubusercontent.com/assets/1621749/20850969/d3345d1c-b8ab-11e6-8316-26eaf6114298.png)

This is important for our research. Can someone check please? @manaswis @kotarohara

**Comment by manaswis** [comment]
Doesn't look like we do. The code is [here](https://github.com/ProjectSidewalk/SidewalkWebpage/blob/26e99ab9b54b2febfce6e5fce719b3fe35acf346/public/javascripts/Progress/src/Progress.js). When the user clicks, no tracker code is being called. 

Correct me if I am wrong @kotarohara @Soben713.

**Comment by jonfroehlich** [comment]
We need to do this then.

**Comment by Soben713** [comment]
We currently only track interactions within an audit task. So this definitely is not stored in the `audit_task_interaction` table.

**Comment by manaswis** [comment]
This should also be in relaunch.

**Comment by jonfroehlich** [comment]
Definitely. Related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/721.

**Comment by misaugstad** [comment]
Quick question: Do we want the text boxes to be the same as in the choropleth where it says how much of the neighborhood has been audited?

**Comment by jonfroehlich** [comment]
@misaugstad: I think so yes.

**Comment by manaswis** [comment]
Closed via #742
