### ISSUE TITLE
Admin Interface: Update Activities Table for Users

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#474]
I'd like to update this table:
![image](https://cloud.githubusercontent.com/assets/1621749/21153970/bd22c738-c13a-11e6-9b4a-efab76033cd2.png)

so that we calculate users in three different ways:
- Users who completed at least 1 mission
- Users who completed at least one audit (street segment)
- Users who contributed at least one label (beyond the tutorial)

**Comment by misaugstad** [comment]
I'm guessing that this is something that we no longer think it is important to implement, so I'm going to close the ticket (@jonfroehlich can reopen if he disagrees).

Here's what it looks like now:
![Screenshot from 2024-09-27 13-49-42](https://github.com/user-attachments/assets/53048fbd-a7e4-4a23-93e9-88070b115d4e)


With this asterisk:
>For cells with the format X (Y). The "Y" is the number of users who have completed at least 1 audit task or have validated at least one label. The X is the total number of users who opened the audit or validation tool regardless of finishing a task.
