### ISSUE TITLE
Find solution for deployed code (version) verification

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#475]
Find a way in which we can find/verify the version of the code running on the server.

This issue came up while deploying the test server (see issue #471) where the distribution that got deployed (due to another issue) did not contain the new changes that were to be tested (see [comment](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/471#issuecomment-266870815) for more details).

To avoid this in the future, we need some way of verifying that the latest version (or a specific version) has been deployed.

**Comment by misaugstad** [comment]
@mechanicjay has provided me with a process for doing that.
