### ISSUE TITLE
Test Server v2 Stress Testing: Getting stuck a lot in v2 and other observations...

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#487]
I just completed a quick test of completing a neighborhood (Douglass) on the test server (which is running v2). Because I was completing a neighborhood, there were a lot of small random street segments left to be audited which meant that I had to jump around a lot. There is not much we can do about this; however, I did get to test @manaswis's new jumping code as a result. Generally, it performed well. However, I observed a few issues (which we can parse out of this Issue and make their own individual Issues in github if we so decide). The video is here: https://youtu.be/6NBHy-OKzrY

1. There were many times when I got towards the end of the street segment and the heads-up navigation told me to 'Walk Straight' but I couldn't walk straight. There were no direction arrows to click and double clicking on the GSV pane didn't work either. The only way out was to click the 'Jump' button on the sidebar. I think this will confuse the typical user and I'm worried that they would get frustrated and drop off the system. See, for example, https://youtu.be/6NBHy-OKzrY?t=4m34s

Possible fixes:

* Have a timer running. If a user is in a spot for longer than some threshold (e.g., 30 secs) without performing some action like labeling, then pop-up a dialog and ask if they are stuck and if they need to jump out of that location. Note: this doesn't really fix the problem.

* Make it so that the 'you are done auditing this area, time to jump' message comes up a bit earlier in the audit route. You could special case this for dead ends--which seem to be the problem. So, something like 'If at a dead end street, pop-up jump message earlier than normal' (i.e., using the old threshold for this)

* Make the heads-up display navigation interface clickable so if user clicks 'Walk Straight' and the user's location doesn't actually move, then we know they are stuck and can take corrective action. Note: this only fixes the problem if the user thinks to click the heads-up display.

* Oh, maybe we could sense when they double click on interface and if they don't move after that, then we know they can't move in that direction and might be stuck?

Here are some counter example to the above where things worked as designed--I was able to double click and make it to the very last bit of the route so that @manaswis's new jump message came up: https://youtu.be/6NBHy-OKzrY?t=1m21s and https://youtu.be/6NBHy-OKzrY?t=2m38s

2. The 'uh, oh' message about being far off the route shows briefly between the time you jump and land at your new location. See: https://youtu.be/6NBHy-OKzrY?t=1m30s (it happens every jump though I only provided one link).

**Comment by manaswis** [comment]
Thanks for the detailed feedback. 

> There were many times when I got towards the end of the street segment and the heads-up navigation told me to 'Walk Straight' but I couldn't walk straight. There were no direction arrows to click and double clicking on the GSV pane didn't work either. The only way out was to click the 'Jump' button on the sidebar. I think this will confuse the typical user and I'm worried that they would get frustrated and drop off the system. See, for example, https://youtu.be/6NBHy-OKzrY?t=4m34s

This is a problem for detecting and handing dead-ends. As we discussed, we'll look into it after the holidays. I have logged it here: #491

>The 'uh, oh' message about being far off the route shows briefly between the time you jump and land at your new location. See: https://youtu.be/6NBHy-OKzrY?t=1m30s (it happens every jump though I only provided one link).

This issue is logged here: #462
