### ISSUE TITLE
The purpose of the Access Score page is unclear

### ISSUE THREAD

**Issue by mattm401** [ProjectSidewalk/SidewalkWebpage#49]
The "Access Score" option is vague and unclear; it also appears that the legend isn't working.

![image](https://cloud.githubusercontent.com/assets/1121334/14474454/33d9ade6-00cb-11e6-8517-52701339d83f.png)

**Comment by kotarohara** [comment]
I agree that the Access Score is not really polished. Maybe I'll take it down for now...

**Comment by kotarohara** [comment]
I fixed the bug, but the interface still needs polishing.

**Comment by kotarohara** [comment]
Updated the demo: sidewalk.umiacs.umd.edu/demo

**Comment by jonfroehlich** [comment]
Should we change the name of 'demo' in the menu to something else--like AccessScore. 

As now, when I see demo, I thought that clicking on it would bring me to a demo of the data collection system not a demo of an API implementation.
