### ISSUE TITLE
Handling dead-ends while jumping

### ISSUE THREAD

**Issue by manaswisaha** [ProjectSidewalk/SidewalkWebpage#491]
As noted by Jon in #487 issue, the jump message is only shown when you reach the end of the route. But some places e.g. at dead-ends, the user can't walk ahead. Hence, the user never gets the jump message to transport to a different location. I am pasting Jon's comments below which includes possible fixes:

> There were many times when I got towards the end of the street segment and the heads-up navigation told me to 'Walk Straight' but I couldn't walk straight. There were no direction arrows to click and double clicking on the GSV pane didn't work either. The only way out was to click the 'Jump' button on the sidebar. I think this will confuse the typical user and I'm worried that they would get frustrated and drop off the system. See, for example, https://youtu.be/6NBHy-OKzrY?t=4m34s
Possible fixes:
> * Have a timer running. If a user is in a spot for longer than some threshold (e.g., 30 secs) without performing some action like labeling, then pop-up a dialog and ask if they are stuck and if they need to jump out of that location. Note: this doesn't really fix the problem.
> * Make it so that the 'you are done auditing this area, time to jump' message comes up a bit earlier in the audit route. You could special case this for dead ends--which seem to be the problem. So, something like 'If at a dead end street, pop-up jump message earlier than normal' (i.e., using the old threshold for this)
> * Make the heads-up display navigation interface clickable so if user clicks 'Walk Straight' and the user's location doesn't actually move, then we know they are stuck and can take corrective action. Note: this only fixes the problem if the user thinks to click the heads-up display.
> * Oh, maybe we could sense when they double click on interface and if they don't move after that, then we know they can't move in that direction and might be stuck? 

A way of finding dead-ends is if we are more cognizant of the underlying street network. TODO: Contact Kotaro to know more about the node graph that he created.

**Comment by misaugstad** [comment]
We have addressed this in a few ways recently!
1. We added a 'Stuck' button (PR #2412)
2. The heads up navigation messages are now clickable, and if it says to go straight and you can't, it automatically moves you somewhere new (PR #2821)
