### ISSUE TITLE
End of Neighborhood: length undefined error

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#492]
The error below shows up when a user completes a neighborhood. This error is very rare and only happens for specific neighborhoods. For e.g., refer the data dump in ~/git/Instructions/resources/sidewalkDumpDec20_0815PM (on my computer); it has this problem logged for Burleith neighborhood (region 224). Although, when I tried to recreate using this dump, the error didn't occur. However, the last mission's text was incorrect. So it should be related to the #480 issue. More investigation is needed.

![screen shot 2016-12-19 at 5 35 59 pm](https://cloud.githubusercontent.com/assets/2873216/21443250/8c59d1e4-c871-11e6-811c-200669bf975a.png)

**Comment by misaugstad** [comment]
Overhaul of mission infrastructure solves this problem #1319
