### ISSUE TITLE
Jumping doesn't change the panorama

### ISSUE THREAD

**Issue by manaswisaha** [ProjectSidewalk/SidewalkWebpage#493]
Sometimes, when the user clicks on the end-of-route jump message, the panorama doesn't change. This again is very rare and difficult to reproduce. The actual change of user position happens but the panorama isn't updated.

Some notes/logs I took while investigating this issue:
    1. E.g. Jumped to a different street (17899 to 23621) but the pano doesn’t change
    2. From taskid 6061 to street 16708 (FS4YGVKtA9MsEK6J9xyK2w)
    3. Current street: 2662 Jumped to 17568
    4. Current street: 19786 Jumped to street: 19785
        1. Street 19785: svl.panorama.getPano(); — ibxjTE0Qpcj839qArdeUjQ

Although, this issue is very tough to recreate even with these notes, as the streets to which the jump happens is random. So going to the same street would not produce the same behavior.

More investigation needed.

**Comment by misaugstad** [comment]
There is a newer issue for the same problem, #702

**Comment by misaugstad** [comment]
Oops, I was wrong about that, those are different issues :+1:
