### ISSUE TITLE
Mission complete dialog shows up immediately after a new mission starts

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#494]
This is one of those rare issues which is very difficult to reproduce. My theory is that it happens due to some previously incomplete mission which didn’t complete correctly. 

Possible scenario (not confirmed): it happens when you open a new tab while completing a mission, then start another mission in another tab, leaving the other mission incomplete.

Based on some preliminary investigation, this is how it is triggered:
In the `handleLoadComplete()` method, the new mission starts (`startTheMission()` method call). Within that, the `updateMissionProgress()` triggers the method that checks if the neighborhood is complete or not — that triggers the Mission Complete dialog.

**Comment by misaugstad** [comment]
This is fixed with the new mission infrastructure! #1319
