### ISSUE TITLE
Green animation of routes in the mission completion box doesn't appear sometimes

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#495]
During v2 testing, some edges cases came up where the green route animation in the mission complete dialog box doesn't show up (see screenshot).

Possible reasons:
1. Mission completed in the middle of a route. Hence, that route was not marked as complete. So if there weren't any previous routes, then that route doesn't show up in the dialog box. 
2. When the page is loaded and the user was at the end of the some previous mission, the tasks that were part of the mission weren't loaded. So if he finishes immediately after he walked a few steps, because of the above mentioned reason, no routes are animated on the screen.

![screen shot 2016-12-19 at 5 43 56 pm](https://cloud.githubusercontent.com/assets/2873216/21446294/51094e5a-c892-11e6-9a8e-c78aafc423d0.png)

Both of these have to be verified. Again, this issue is difficult to reproduce. My guess is its cause is a very specific user behavior (something similar to #494).

This was also seen in region 293 (data dump on the test server).

**Comment by misaugstad** [comment]
>Mission completed in the middle of a route. Hence, that route was not marked as complete. So if there weren't any previous routes, then that route doesn't show up in the dialog box.

This is covered by #1450 

>When the page is loaded and the user was at the end of the some previous mission, the tasks that were part of the mission weren't loaded. So if he finishes immediately after he walked a few steps, because of the above mentioned reason, no routes are animated on the screen.

This is covered in #324 

Since this has been separated out into two distinct issues, I'm going to close this one.
