### ISSUE TITLE
Tutorial: Replacing static yellow arrows with flashing yellow arrows

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#499]
The white arrows that are used for guiding the user in the tutorial is not visible immediately to the users. This came in the v2 informal usability study.

**Comment by jonfroehlich** [comment]
I think they should flash in yellow like we do for all other important indicators. This also produces a consistent design language for users.

**Comment by manaswis** [comment]
Duplicate of #453. Closing this issue.
