### ISSUE TITLE
Onboarding Font: Usage of Bolding

### ISSUE THREAD

**Issue by mattm401** [ProjectSidewalk/SidewalkWebpage#50]
![image](https://cloud.githubusercontent.com/assets/1121334/14474527/8e8a6e56-00cb-11e6-8991-f7fe60f37ed1.png)

The onboarding is excellent, but you should only use bold text to highlight the key bits in explanatory text.

**Comment by kotarohara** [comment]
Good point. I'll fix it when I get a chance.

**Comment by nguyenist** [comment]
@kotarohara created a pull request for this: https://github.com/ProjectSidewalk/SidewalkWebpage/commit/8e73c54403954c21a36825dab1740041e237bd72

**Comment by jonfroehlich** [comment]
I agree with Matt. I need to go over all the onboarding text and wordsmith it a bit for concision and to give feedback on bolding. Current bolding level is overwhelming.

**Comment by jonfroehlich** [comment]
I am going to review this and the overall onboarding text.

**Comment by jonfroehlich** [comment]
Did you fix the onboarding bug that prevented me from advancing on double click? If so, I can return to giving you feedback on onboarding.

**Comment by kotarohara** [comment]
Yes, it should be fixed.

**Comment by kotarohara** [comment]
Updated the onboarding. I update things I agreed (comments in pptx). I'll probably push it to prod tonight.

I agree #114 should be addressed, but I won't do it now.
