### ISSUE TITLE
Tutorial: The arrows to be labeled for third intersection should be reversed

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#500]
The arrows that guide the user to label the third intersection should be labeled in the reversed order i.e. the ramp closer to the user should be labeled first. 
In the usability study, it was seen that the user starts labeling immediately even before instruction is provided. But when they do see the instruction about the two curb ramps to label, they mark the ramp close to them first (while the tutorial instructs them to do the reverse).

**Comment by jonfroehlich** [comment]
I think we should fix this by having two arrows simultaneously or something. 

Note that I never ran into this problem myself... but I guess I waited for the tutorial to guide me through each step.

**Comment by manaswis** [comment]
PR #429 resolves this.
