### ISSUE TITLE
Rewrite mission text for the last mission of the neighborhood

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#501]
The mission text of completing the neighborhood doesn't sound great especially this part:

"100% of the **entire streets** in this neighborhood"
<img width="1180" alt="screen shot 2016-12-17 at 11 13 00 am" src="https://cloud.githubusercontent.com/assets/2873216/21444375/c75da46a-c87a-11e6-80c7-11423c9ade48.png">

This sentence needs rewording.

**Comment by misaugstad** [comment]
I removed this model when redoing mission infrastructure (PR #1319)
