### ISSUE TITLE
Onboarding: Explaining Click & Drag

### ISSUE THREAD

**Issue by mattm401** [ProjectSidewalk/SidewalkWebpage#51]
The second part of onboarding when you click and drag on the map.  It was very difficult to understand when I done something correctly.  You suggest with the "Hand Icon" to click and turn left... but the bottom right corner says "turn right", which is what I initially did and couldn't figure out why I was being directed to "move forward" or why I couldn't perform this action. I ended up going in a full circle until I found the second curb ramp:

![image](https://cloud.githubusercontent.com/assets/1121334/14474712/7572c746-00cc-11e6-8581-2d636bdbb5da.png)

**Comment by kotarohara** [comment]
I fixed the bug where the message at the bottom-right does not get hidden. I hope it helps...
