### ISSUE TITLE
I'm at 100% But Asks Me To Jump

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#510]
I'm at 100% in my current mission but UI asks me to jump

![image](https://cloud.githubusercontent.com/assets/1621749/21873561/3bd93026-d83d-11e6-835c-eb1e2460ba75.png)

Update: after clicking the bottom right hand corner message, I was greeted with this screen instantly:

![image](https://cloud.githubusercontent.com/assets/1621749/21873573/6752670e-d83d-11e6-9fca-18e4c5e22476.png)

**Comment by misaugstad** [comment]
I assume that what's happening is that you are over 99.5% complete but less than 100% complete. This should be an easy check we add in to just always round down to 99%.

**Comment by jonfroehlich** [comment]
Agree.

**Comment by misaugstad** [comment]
Closing via #1367
