### ISSUE TITLE
How Can We Make Auditing with Trackpads Easier/Faster

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#511]
I typically test Project Sidewalk with one of my Windows machines and an external mouse; however, over winter break, I was using my new MacBook Pro and its trackpad. In this case, I found auditing comparatively painful and tedious. I felt slower and it was a pain to perform click-and-drag (panning) operations. It was enough for me to investigate buying an external mouse for my mac.

So, the question I pose is: can we brainstorm ways to make using a trackpad less painful. One idea, which I previously raised, was to make the heads-up direction part of interface clickable, which would do one of two things: (i) it would either automatically point you in the direction you need to walk or (ii) it would walk you forward one step.

For (i), whenever the heads-up display has turn information (like below), clicking this would turn you so that you're pointing in this direction. 

![image](https://cloud.githubusercontent.com/assets/1621749/21873853/5fd0b0ce-d83f-11e6-8902-4a643dd93045.png)

For (ii), if the heads-up display says 'Walk Straight," then clicking this would move you forward one step.

![image](https://cloud.githubusercontent.com/assets/1621749/21873867/76ee929e-d83f-11e6-9f22-1aba55d6b1f6.png)

**Comment by misaugstad** [comment]
The main suggestion from this has been moved to #2538
