### ISSUE TITLE
Implement a way to check/uncheck all checkboxes in the admin map visualization

### ISSUE THREAD

**Issue by m-furman** [ProjectSidewalk/SidewalkWebpage#516]
Currently, the admin map visualization only allows users to select/deselect one label at a time. This would allow us to select/deselect all labels using just one checkbox/button.

**Comment by m-furman** [comment]
Implementation with a thin border under the header of the table (I prefer this one):
<img src="http://drive.google.com/uc?export=view&id=0B687BEjGtgFVaTNYNHZpcml2Yzg"  />

Implementation with a grey border around the 'check/uncheck all' checkbox:
<img src="http://drive.google.com/uc?export=view&id=0B687BEjGtgFVaDFrSjhOSmFMeTQ"  />

I realize the border around the checkbox is a bit off in the second image (I'll have to look into how to fix that), but are either of these acceptable? If not, I can try to look into using the legend circles as checkboxes (as was suggested on the page for issue #386), but I have a feeling that might be a bit difficult.

**Comment by jonfroehlich** [comment]
I like thin border version.

**Comment by manaswis** [comment]
I like the version with the thin border as well.
