### ISSUE TITLE
Rubrics for assessing the severity of the issues

### ISSUE THREAD

**Issue by mattm401** [ProjectSidewalk/SidewalkWebpage#53]
- It's still unclear how to score issues in the application (e.g., 1, 5); in the onboarding you actually suggest labeling something a "3" that I would assume is a "5".
- It isn't required to score an issue and I noticed that I was frequently forgetting to do this.

**Comment by kotarohara** [comment]
- I agree that we need some kind of rubrics for assessing the severity of the problems.
- The score is optional, so it's ok if you forget to provide that data. I kind of want to see if people provide that data.

**Comment by kotarohara** [comment]
This is related to #39

**Comment by kotarohara** [comment]
Added example images to the interface. I'm closing this and #39
