### ISSUE TITLE
In Version 2.1, No Smooth Animated Interpolation Between Locations When Double Clicking

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#533]
In version 2.1, there is no smooth animated interpolation between locations when double clicking to move. See below. Is there some function parameter we have to pass to enable this smooth movement animation on the double click to move? It's enabled when you click the arrow to move.

![image](https://cloud.githubusercontent.com/assets/1621749/24199024/89151f4e-0ede-11e7-9e59-e78c0e913966.png)

**Comment by manaswis** [comment]
I have noticed this as well. If you double click just a little ahead of the arrow (see picture below), then the smooth transition happens. 

![githubissue533](https://cloud.githubusercontent.com/assets/2873216/24204551/35ec3a58-0eef-11e7-96be-e287cc9ff37d.png)

I will look into how to do this.

**Comment by jonfroehlich** [comment]
Hmm, OK. Thanks. Looks like it's because of the distance traveled between the two points.
