### ISSUE TITLE
The 'deviceorientation event' only works in HTTPS

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#536]
The 'deviceorientation event' is Deprecated. We need to implement this differently.
I just saw this in Chrome console:

The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

_.z.addDomListener @ js:94 

![image](https://cloud.githubusercontent.com/assets/1621749/24201131/8bae88f6-0ee5-11e7-86df-5098d8094261.png)

**Comment by misaugstad** [comment]
We have switched to HTTPS when switching to Docker on UW servers, so this is no longer an issue.
