### ISSUE TITLE
Blank GSV Screen! Missing Imagery.

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#537]
Uh oh, just experienced my first major problem with version 2.1: the screen went blank (see below).

![image](https://cloud.githubusercontent.com/assets/1621749/24201208/bd0646b4-0ee5-11e7-9883-55833299fc02.png)

Looks like it's a depth map issue. From the console log:
SVLabel.js:184 Error loading depth map for pano xwrwSRUefCHJKEvckjDjDg
Cannot read property 'model' of undefined
At undefined(undefined)

![image](https://cloud.githubusercontent.com/assets/1621749/24201239/d82e57a6-0ee5-11e7-9a53-1c1867ffc407.png)

I am now perpetually stuck. As I walk, the screen continues to be blank. Not sure if that's because depth maps continue to not exist for my location or because the previous error threw the code into some malfunctioning state. **Update** it turns out, I'm not actually walking. I can't walk because double clicking the screen does nothing and there are now arrows to click to move. I also get this error when I double click the screen:
InvalidValueError: setPov: in property heading: NaN is not an accepted value
![image](https://cloud.githubusercontent.com/assets/1621749/24201462/77f4264e-0ee6-11e7-8615-320457a9cddf.png)

A few things:
1. We must be able to tell, a priori, whether a location has a depth map or not. If it doesn't, we need to handle this elegantly (e.g., pop-up message and teleport to new location)
2. This seems like a high priority to investigate and fix as it breaks the entire user experience.
3. I logged this in the Project Sidealk 'feedback' tool, so you should be able to immediately locate where I was.
4. I reloaded the browser and was brought to a different location and things worked again.

**Comment by jonfroehlich** [comment]
It happened again. The screen is blank and I am stuck and cannot complete a mission. @manaswis, this is a showstopper. We must investigate to see how prominent this problem is and come up with a solution.

![image](https://cloud.githubusercontent.com/assets/1621749/24249187/ae1d9328-0fa8-11e7-8ae1-0403eec086c9.png)

**Comment by jonfroehlich** [comment]
If we can't track down the root cause of the problem, at the very least we should be able to:

1. When user takes a step forward, check to see if a depth map exists for that next location. Note: this is even before we show the user their next location.
2. If no depth map exists, check the next GSV location in the walk direction. Try this for ~2 or 3 more step locations forward. If none have a depth map, we need to bail out of this street so pop-up teleport message and explain that there was a problem and we need to teleport them somewhere else in neighborhood.
3. If depth map exists, simply have user walk forward to that location.

**Comment by manaswis** [comment]
Related issue: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/309

Kotaro mentioned:
>A similar thing happened when we dropped people to locations where GSV images are not available.
>1. Once you get into that gray window state, the only fix is to refresh the window. It's a bug in GSV API and you can't do anything about it.
>2. Not sure how you can get into that gray window state... You should be taken to a spot where there is a GSV image when you click one of the white arrows or double click on the image.

**Comment by jonfroehlich** [comment]
@kotarohara mentions a bug in the GSV API but no external validation that this is true, correct? That is, he does not link to an official bug report on Google's website. So, can we be 100% confident that it's a bug on their end and not on our end?

**Comment by manaswis** [comment]
No, I don't think there is an external validation. However, in my current investigation, I checked the metadata that's received for those locations where there is a blank screen. The request returns a status code of "UNKNOWN__ERROR", which is defined by Google as:

> UNKNOWN_ERROR indicates that a Street View request could not be processed, though the exact reason is unknown.

I am looking into this further - looking into the code segments where there is a check for the status code, and find places where the check is missing (if any), and add a check for this status code and implement the algorithm that you mentioned in your previous post.

**Comment by jonfroehlich** [comment]
@manaswis: got it. Sounds good. Thank you!

**Comment by jonfroehlich** [comment]
I tried to do my morning test audit this morning and, once again, I encountered the GSV blank screen problem. I have tried to complete 4 missions since the 2.1 release. In 3 of the 4 missions, I have faced this problem that has prevented me from completing the mission. It's a huge showstopper.

![image](https://cloud.githubusercontent.com/assets/1621749/24295138/c9d0e7c4-106f-11e7-9738-d8fc4e9c8912.png)

Error loading depth map for pano ug6Wgdp7N6AHZ3FzbijOGA
Cannot read property 'model' of undefined
At undefined(undefined)
(anonymous) @ SVLabel.js:184
10https://geo0.ggpht.com/cbk?cb_client=apiv3&panoid=ug6Wgdp7N6AHZ3FzbijOGA&output=tile&x=0&y=0&zoom=0&nbt&fover=2 Failed to load resource: the server responded with a status of 404 ()

**Comment by manaswis** [comment]
Hmm. I would say for now try to audit another neighborhood. It looks like North Cleveland Park has a lot of these expired pano ids. I found that in Adam Morgan's neighborhood (the example below) too. Yesterday, I found these pano ids are not available even on Google Street View. An example:

<img width="1253" alt="googlestreetview_errorpanel" src="https://cloud.githubusercontent.com/assets/2873216/24299132/83c38dea-107e-11e7-8cd9-768a884804bd.png">

You get the above errors on Google Street View (see [here](https://www.google.co.in/maps/@38.9231686,-77.0473539,3a,75y,277.5h,74.75t/data=!3m6!1e1!3m4!1sKa9RvY6KuDxYhswObemS9g!2e0!7i13312!8i6656!6m1!1e1) and walk left or right on Calvert Street NW) when you try to walk in a direction where you don't have any imagery. Somehow, Google is still loading these ids when you load the panorama. So our solution definitely would have to detect this and move to a different location, as you had suggested. I am working on that.

**Comment by jonfroehlich** [comment]
What do you mean 'above errors.' Google simply prevents me from walking in that direction when I click on the arrow (i.e., nothing happens when I try to walk this way):

![image](https://cloud.githubusercontent.com/assets/1621749/24301975/60b51266-1087-11e7-9d57-dbd179202a28.png)

**Comment by manaswis** [comment]
Yes, Google doesn't allow you to walk but it shows these errors on the console. I was investigating this location using our interface and I got the blank screen for one of the pano ids that's included in the error list in my previous post.

**Comment by jonfroehlich** [comment]
Ah, I see.

Yes, the error printed to console is:
GET https://geo0.ggpht.com/cbk?cb_client=maps_sv.tactile&authuser=0&hl=en&panoid=QiFb1pQcs9EWWHK5NvyYHA&output=tile&x=0&y=0&zoom=0&nbt&fover=2 404 ()  cbk:1

![image](https://cloud.githubusercontent.com/assets/1621749/24303370/19443aa6-108c-11e7-8a4f-7e74c7d6707d.png)

**Comment by jonfroehlich** [comment]
Interesting, similar to @manaswis, I am now seeing the GSV blank screen problem in Google Street View itself! Check this out:

https://www.google.com/maps/@38.9287554,-77.0663951,3a,75y,85.19h,90t/data=!3m4!1e1!3m2!2e0!6s%2F%2Fgeo2.ggpht.com%2Fcbk%3Fpanoid%3DZynupA2MS2KJvpHEqgvDGA%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D83.83196%26pitch%3D0%26thumbfov%3D100!6m1!1e1
![image](https://cloud.githubusercontent.com/assets/1621749/24370114/302f6e2e-12f4-11e7-9dcd-c0f140f889db.png)

**Comment by jonfroehlich** [comment]
I just tweeted this to the GMaps team:

https://twitter.com/jonfroehlich/status/846422002948812800

![image](https://cloud.githubusercontent.com/assets/1621749/24370691/518aa9ce-12f6-11e7-915f-f144149cbc8a.png)

**Comment by jonfroehlich** [comment]
Given that we still don't have a workaround for this despite multiple days of work (thanks @manaswis) and because I actually now agree with @manaswis that this is an infrequent issue and that it is a problem with GSV and not us (doh!), perhaps the right approach is to do a quick fix:

1. Check for the GSV blank screen error on location load
2. If current location suffers from problem, pop-up message to user... something like this: "Uh, oh, something went wrong with Google Street View. We will need to transport you to another location in <neighborhood name>. Keep up the good work!"

**Comment by manaswis** [comment]
Sounds good. I will implement that.

**Comment by manaswis** [comment]
**Some notes/findings during my investigations**
About the GSV bug: 
I found that the navigation arrows (that link to adjacent panoramas) have the problem-causing panoid that doesn't have any imagery available. For e.g., for the location/pano id (lets call this the source panoid) where the blank screen was occurring when you clicked one of the problem-causing arrows, these are the links:

Link {"description":"Biltmore St NW","heading":204.2850341796875,"pano":"Ka9RvY6KuDxYhswObemS9g"}

Link {"description":"Calvert St NW","heading":297.2437438964844,"pano":"QiFb1pQcs9EWWHK5NvyYHA"} <--- This is the problematic one.

However, when you request for the metadata (using a different URL) for the source panoId, the links are different i.e. they have valid panoIds.

**PanoIds**:
This is a description of one of the API function:
>Request with a StreetViewPanoRequest, this returns panorama data given a reference ID which uniquely identifies the panorama. **Note that these reference IDs are only stable for the lifetime of the imagery of that panorama.**

Further, while debugging, at a point I was able to see some detailed panorama information, and it had a field called "time" (the timeline feature), which had panoIds of the location based on when it was taken. Each time had a different Id.

This confirms our guess that they expire pano ids when new imagery is available for a particular location.

**Comment by manaswis** [comment]
Added this pop-up:

<img width="720" alt="screen shot 2017-03-27 at 4 53 01 pm" src="https://cloud.githubusercontent.com/assets/2873216/24377607/f072f11a-130d-11e7-93f8-200917d46a3d.png">

Looks good?

**Comment by jonfroehlich** [comment]
Yep. Nice job!

We need to log this error to database. I assume we have a place for error logging like this (e.g., when user clicks jump button and says that they cannot continue on mission route).

**Comment by manaswis** [comment]
Yes, it is being logged.

**Comment by jonfroehlich** [comment]
Again. This time in Fort Stanton.

![image](https://cloud.githubusercontent.com/assets/1621749/24523898/a6b6c900-1562-11e7-9c66-b142ad3aae7a.png)

```
(svl.taskContainer.getCurrentTask()).getStreetEdgeId();
22357
```

**Comment by manaswis** [comment]
This is the new behavior that I saw today and that I captured in the code. It could be an artifact of the updates to the imagery that they did (happened the same day but can't say for sure). 

For every pano that is set, usually there are 2 pano_changed events both of the same panoid. In a few cases, I noticed that the first pano_changed event was for a valid panoId and the second one is a blank panoid. The second blank panoid is causing the blank screen. So I applied the same jump mechanism when a blank pano id is detected.

**Comment by manaswis** [comment]
I updated the dev-server with the latest changes. You can specifically test this location using: http://sidewalk-dev.umiacs.umd.edu/audit/street/19474

**Comment by manaswis** [comment]
Shall I deploy it on the production server? I have done my testing locally.

**Comment by jonfroehlich** [comment]
Sure. Thanks.

**Comment by manaswis** [comment]
Deployed it to the production server.
