### ISSUE TITLE
Admin Interface Map: Checkboxes Malfunctioning

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#538]
Notice how I have 'missing curb ramps' unchecked but yet it still shows on map. In fact, I can't get it to go away:

![image](https://cloud.githubusercontent.com/assets/1621749/24205170/03d51042-0ef1-11e7-8818-5adb824cd875.png)

@manaswis, did you do a code review and test of this?

**Comment by manaswis** [comment]
I did. I just checked again. It works for me. Can you list the exact steps you followed?

To note here is that this interface gets refreshed each time you click on each of the checkboxes. Maybe you clicked in quick succession two checkboxes? If that was the issue, then the new layered format should take care of that. It hasn't been pushed yet to the production server 'cause Maria is working on fixing some issues there.

**Comment by misaugstad** [comment]
Closing this issue because it seems to be resolved. Reopen if you think it isn't.
