### ISSUE TITLE
Mission Complete % Never Seems to Update

### ISSUE THREAD

**Issue by mattm401** [ProjectSidewalk/SidewalkWebpage#54]
![image](https://cloud.githubusercontent.com/assets/1121334/14475360/9c4c7dd2-00cf-11e6-9db7-d7eb51c32721.png)

After walking around for 5 - 10 minutes, the current mission never completed. In this picture I walked down to a dead end road and had to turn around; I noticed the Current Mission meter when to 18% and then back down to 10%; this is both unclear and a bit disheartening to me as a user.

**Comment by mattm401** [comment]
Using Jump doesn't make this better... and though you ask me to select from a two options for using jump... it's unclear what this does with respect to mission completeness... in fact, I got dumped into an industrial area that was very different from the nice residential area I was in before.

**Comment by mattm401** [comment]
Oh god, I just noticed the little Green/Red line in the minimap...

**Comment by mattm401** [comment]
What are you suppose to do if you're in a residential area that isn't designed to be accessible? I mean... I can't possible mark this entire neighborhood as impassable... it would take forever.

![image](https://cloud.githubusercontent.com/assets/1121334/14475539/76abcc80-00d0-11e6-9c75-0cff9591c410.png)

**Comment by mattm401** [comment]
You're probably going to have to make going "off mission" a little more noticeable; I had no idea.

**Comment by kotarohara** [comment]
Great points. 

1. "Off mission": This is related to the issue #5 . It's on my todo list.
2. "What to do when there are no sidewalks at all". Yeah, good point. I'm not sure what we can do about it. The problem is that we don't know if we have sidewalks or not a priori. We can probably infer _afterwards_ that there are no sidewalks if people are not labeling anything and keep walking. But I guess it doesn't really solve the interaction problem (i.e., people will be confused if they should label everything as No Sidewalk).

**Comment by kotarohara** [comment]
I made it so the app checks if the user is en route. If they are off by 50 meters (160 ft), the bottom-right message blinks.

![image](https://cloud.githubusercontent.com/assets/612263/14549122/faa71ce0-028a-11e6-8d3f-d95450c4b908.png)

**Comment by jonfroehlich** [comment]
We actually have two different points in here. I think Matt should try and list only one point at a time in the Issue tracker. 

Re: your fix to the off-mission problem. I think we might even want a pop-up dialog if they get far off track with a button that teleports them back to the most recent location on the mission track.

Re: Matt's other point, my feeling is that the user should label both sides of the street as not having a sidewalk... and try to do this every step or every few steps.
