### ISSUE TITLE
Tutorial: Train users to zoom in/out

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#541]
From Jon's recent comment on #531:

> With the new GSV placement location in the tutorial, it's very hard to actually see this corner & the fact that there is no curb ramp. Perhaps we could have user zoom here (& train them in on zooming). 
![image](https://cloud.githubusercontent.com/assets/1621749/24000125/c9012d76-0a30-11e7-925b-10f669c28182.png)

**Comment by manaswis** [comment]
Here is the sequence of screens for the new zoom feature implementation:

### 1: After labeling the first corner
![image](https://user-images.githubusercontent.com/2873216/26890056-48030246-4b7e-11e7-9265-4dbb0d384de0.png)

### 2: After the user clicks on the zoom-in button
![image](https://user-images.githubusercontent.com/2873216/26890075-5575528a-4b7e-11e7-90f6-7900c6026b58.png)

### 3: After labeling the curb ramp
![image](https://user-images.githubusercontent.com/2873216/26890112-74369990-4b7e-11e7-8e25-8fa3bab2dd94.png)

### 4: After labeling the missing curb ramp
![image](https://user-images.githubusercontent.com/2873216/26890130-82da0f86-4b7e-11e7-9ef1-37d81fe827b1.png)

### 5: After clicking the zoom-out button
![image](https://user-images.githubusercontent.com/2873216/26890143-903e9796-4b7e-11e7-8fa6-343288e69382.png)

### 6: The next step
![image](https://user-images.githubusercontent.com/2873216/26890162-9cac299e-4b7e-11e7-88c0-a458ba73b752.png)

**Comment by maddalihanumateja** [comment]
Looks good to me.

**Comment by misaugstad** [comment]
Looks good!

**Comment by jonfroehlich** [comment]
I agree. We may feel differently once we use the interactive version. :)

**Comment by manaswis** [comment]
Great! I have merged it to develop. Closing via PR #642.
