### ISSUE TITLE
Tutorial: Disable specific labeling order for the two curb ramp corner

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#542]
Allow the user to label either of the curb ramps first and not restrict them to follow a specific order as imposed currently by the instructions.

From Jon's comment in #531:

>6. This has been commonly said among the team but we should probably keep both of these arrows up and let the user label the curb ramps in the order they want rather than enforcing this weird right-to-left order that we do now (which confuses users). 
![image](https://cloud.githubusercontent.com/assets/1621749/24000324/4aa1c48a-0a31-11e7-9cb8-028495e2e841.png)
>See, I've already labeled the curb ramp but now the tutorial interface is telling me to label it again. This should not happen. It's confusing!
![image](https://cloud.githubusercontent.com/assets/1621749/24000340/58bf2bca-0a31-11e7-8a2e-0e62e13b90c9.png)

> Manaswi: Yes, this would have happened if you labeled the left curb ramp first while the script wanted you to finish the right one first. Would have to update the script to work for either curb ramps.

**Comment by maddalihanumateja** [comment]
Addressed by Pull request #649

**Comment by manaswis** [comment]
Closed via #649
