### ISSUE TITLE
Tutorial: Improve instruction text to pan at the two curb ramp corner

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#543]
From #531:
>Jon: I have observed users getting confused here too. They now see two curb ramps to label but the tutorial interface is telling them to continue panning. I think the UI needs to acknowledge this someway and say something like 'keep panning to the right' or something. Otherwise, I've seen users stop here and try to label the curb ramps (before they get to the correct pan position for the tutorial to continue). ![image](https://cloud.githubusercontent.com/assets/1621749/24000311/41ede5ee-0a31-11e7-9ddc-d2bbce7565f4.png)

Solution: Update the text to say something like "continue till you see two curb ramps".

**Comment by jonfroehlich** [comment]
Your recommended solution does not work. Study the screenshot carefully.

**Comment by manaswis** [comment]
Yes, you are right. In the current implementation, we need to continue panning, such that we reach a position where we can see the no sidewalk arrow, once the user labels the two curb ramps. 

A solution could be to update all the instruction texts to start with numbers (e.g. 1/6: <Instruction>) and then we can update the text to say "Continue panning till you see reach step 5" or something similar.

**Comment by jonfroehlich** [comment]
I think you can simply add in a message that says 'keep panning' or something.

The step thing seems complicated. Also note that the word 'step' is then overloaded for user as we typically mean step as a virtual step to move in Project Sidewlk.

**Comment by manaswis** [comment]
Closed via #696
