### ISSUE TITLE
Why Does Mission Show 0% But Other Stats are Saved?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#547]
Yesterday, I was testing v2.1 when I ran into this bug (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/537) that prevented me from continuing. I logged in again today and it appears that my audit work during that mission was saved (note: the interface says I have labeled 46 curb ramps, 6 obstacles, 6 surface problems) and yet the mission tracker shows 0% complete (see screenshot below). I don't get how this is possible. How could I have been credited with labeling those things but the mission is still at 0%. Confusing.

![image](https://cloud.githubusercontent.com/assets/1621749/24248506/2a83c980-0fa6-11e7-8708-84d1655ee801.png)

**Comment by misaugstad** [comment]
This is fixed in the mission infrastructure PR! #1319
