### ISSUE TITLE
If Users Are Not Rating, Pop-Up Message That Reminds Them to Rate

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#548]
We should track rating behavior--like we do if users are using keyboard shortcuts--and pop-up a message that politely encourages them to rate and that they can use the keyboard (1,2,3,4,5) to do so.

A message similar to this but specifically for rating severity:

![image](https://cloud.githubusercontent.com/assets/1621749/24248673/b72c9e2a-0fa6-11e7-9e79-4d1aaec10f5d.png)

@manaswis, thoughts?

**Comment by sagec108** [comment]
I created a similar pop-up message that reminds users to rate the area severity whenever the user closes the context menu a certain number of times (adjustable constant) without rating.

Closing the menu occurs in 3 ways, all of which are tracked
- Pressing the X button
- Pressing OK
- Clicking outside of the context menu

The current popup message looks like this and appears after 4 instances of failing to rate:






![popup_current](https://cloud.githubusercontent.com/assets/20068009/26323468/f194367e-3efc-11e7-8a7f-3003d5e3da92.png)

**Comment by jonfroehlich** [comment]
Consolidating thread from https://github.com/ProjectSidewalk/SidewalkWebpage/pull/606

Message ideas:
1. You can press keys 1 through 5 to rate the location accessibility for each label you place.
2. You can also press keys 1 through 5 to rate the area accessibility while you label.
3. Please rate area accessibility for each label you place using keys 1 through 5.
4. Remember to rate issue severity for each placed label using keys 1 through 5.
5. Please rate the accessibility of areas you label by pressing keys 1 through 5.
6. Please rate the accessibility of things you label by pressing keys 1 through 5.
7. Please rate the accessibility of your labels by pressing keys 1 through 5.
8. Please rate as you apply labels by pressing keys 1 through 5.
9. Don't forget to rate as you apply labels by pressing keys 1 through 5.
10. Don't forget to provide severity ratings for each label by pressing keys 1 through 5.
11. Please provide severity ratings for each label by pressing keys 1 through 5.

My vote is for 11 then 10.

Also, while I like that we are using @Soben713's pop-up message system, I do think that having a message pop-up with the rating context menu would be easier for the user to understand (e.g., the pop-up could have an arrow pointing to the rating menu along with the textual prompt). If we don't do this, then I think the message should only be visible when the context menu is visible (otherwise it's confusing). @sagec108, thoughts?

**Comment by sagec108** [comment]
My vote is for 5 (though if the "severity rating" phrase is understandable to users, I would vote for 11).

I do think the reminder could be clearer. I would prefer having the message pop-up when the context menu is visible. Highlighting the context menu may be also be a better solution than drawing arrows, as it does not get in the way of user interaction.

**Comment by jonfroehlich** [comment]
I don't like 5 because I don't understand 'areas.' That's not what we are asking them to rate. We specifically want them to include a rating for each label that they provide.

**Comment by sagec108** [comment]
Oh, I see what you mean. In that case, I think 11 is better because it emphasizes providing ratings for each label.

**Comment by misaugstad** [comment]
I like 11 > 8 > 10 > 9 > 7.

**Comment by jonfroehlich** [comment]
@sagec108, let's go with 11 then! :)

**Comment by sagec108** [comment]
Sounds good, I updated the text in the alert message to number 11.
