### ISSUE TITLE
Started Second Mission: 51% Completed

### ISSUE THREAD

**Issue by mattm401** [ProjectSidewalk/SidewalkWebpage#55]
![image](https://cloud.githubusercontent.com/assets/1121334/14475588/bb9d6966-00d0-11e6-938c-93fab3e6b3c3.png)

Got the mission notice to start the second mission (1000m), why did it jump to 1000m? Also, I started this second mission at 51%... unsure why? Maybe because I was aimlessly wandering before?

**Comment by mattm401** [comment]
I am also still in a neighborhood  that wasn't designed to be accessible... which is totally weird. I am not going to mark all this... I'd be here all day.

**Comment by mattm401** [comment]
![image](https://cloud.githubusercontent.com/assets/1121334/14475650/0c401fee-00d1-11e6-9be8-8ff862177d01.png)

It also appears like I broke this.

**Comment by mattm401** [comment]
Yea, this thing is totally busted... I am just walking in a circle?

**Comment by mattm401** [comment]
Finished... 2000m goal... starts at 40% complete... weird!

**Comment by mattm401** [comment]
And, I am repeating the same traverse as when I did the previous mission...

**Comment by mattm401** [comment]
So I clicked jump and got dropped to a random location and now I am walking around starting at 40%, following the path... I feel like this "path" system you have going on does not support free exploration. What if I don't want to follow your path!?

**Comment by kotarohara** [comment]
The mission starts at 51% because you have already walked 51% of distance (in the previous mission) that you are required to clear the mission. I know it's weird and I'm aware of this, but it's a rather low priority now...

**Comment by kotarohara** [comment]
I've been playing around with this and felt:

- It feels kind of weird when I have 50% completed right after finishing up the previous mission.
- It feels right that I have 50% completed on the mission completion bar when I come back after a while. 

I'm not sure what would be more natural thing to do. I'll think about it when I have time.

**Comment by jonfroehlich** [comment]
How was this resolved? You just closed it with a link to your commit: https://github.com/ProjectSidewalk/SidewalkWebpage/commit/6ce6ecb892878543388cb2a992d15842857f7436
