### ISSUE TITLE
Mission Tracker Says 100% But Midway Through a Street

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#553]
![image](https://cloud.githubusercontent.com/assets/1621749/24332747/1834a49a-121a-11e7-8399-55ffd69206ae.png)

I also added a comment using feedback tool:
![image](https://cloud.githubusercontent.com/assets/1621749/24332751/2771a598-121a-11e7-993b-7d2490ac95b6.png)

I'll update this status when I actually finish the mission (if the system allows me to).

**Comment by jonfroehlich** [comment]
Update: I took one additional step forward and I received the Mission Complete dialog. Interesting!

![image](https://cloud.githubusercontent.com/assets/1621749/24332776/59bed778-121a-11e7-8b6e-f77399114062.png)

**Comment by manaswis** [comment]
This is actually a valid behavior. The missions are based on distance. So if the distance was covered, while the user was auditing a street (even if in the middle of a street), the mission is completed.

**Comment by jonfroehlich** [comment]
It's fine that a mission stops in the middle of a street but it's confusing to reach 100% and not be done.

**Comment by manaswis** [comment]
Ah I see. Then this is the problem logged here - https://github.com/ProjectSidewalk/SidewalkWebpage/issues/512

**Comment by jonfroehlich** [comment]
Yep! If possible: I think we need to force the UI to not be 100% until you are at the very last location (no steps left).

**Comment by misaugstad** [comment]
This has been fixed in the mission infrastructure reorg #1319
