### ISSUE TITLE
New Landing Page: Animated 3-Step Gif Does Not Auto-Advance

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#564]
The animated 3-step GIF does not auto-advance through the three steps of Explore, Find Problems, Assess Severity:

![image](https://cloud.githubusercontent.com/assets/1621749/24800938/2c4dc0a6-1b70-11e7-8695-173ae1b04762.png)

**Comment by manaswis** [comment]
Closed via #597
