### ISSUE TITLE
New Landing Page: Explore, Find Problems, Assess Severity Don't Look Clickable

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#565]
The Explore, Find Problems, & Assess Severity buttons don't look clickable. If we want people to interact with these, they need to visually indicate interactivity somehow:

![image](https://cloud.githubusercontent.com/assets/1621749/24800990/644a2ef4-1b70-11e7-89cc-d9a50d7fd58f.png)

Looks like Rachael's not on github, otherwise I would tag her with this.

**Comment by rachmarr** [comment]
We haven't quite implemented the "line" portion as of yet, so that could help, otherwise maybe we can consider a file-folder look? So that each portion looks like a "tab". -Rachael

**Comment by rachmarr** [comment]
Hi All, 
Here is a quick mockup of what I am thinking (the tabs version mentioned above).
![_newmockupofexplaination](https://cloud.githubusercontent.com/assets/23280671/24871327/3e726a92-1de7-11e7-8b8e-9c9b56a9fd10.jpg)
 Let me know what you think!

**Comment by manaswis** [comment]
I like this one! It definitely looks clickable, and it has a good color coordination with the rest of the page as well - with alternating green elements every other section :)

**Comment by manaswis** [comment]
Closed via #597
