### ISSUE TITLE
If You Use Keyboard in Onboarding, Onboard Messages Do Not Advance

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#58]
If you use the keyboard to select label type, the onboard tutorial does not allow you to advance (probably because it's looking for mouse listener events or something). For example, in the screenshot below, I correctly placed a label like the tutorial told me to but it didn't realize that I actually did it via keyboard:

![image](https://cloud.githubusercontent.com/assets/1621749/14507408/7f5c8fa2-0190-11e6-8fac-443d7ddb8ccc.png)

**Comment by kotarohara** [comment]
That's right. It sounds like a right behavior for me. Keyboard shortcuts are for advanced users, so I don't intend to teach them in the onboarding.

**Comment by jonfroehlich** [comment]
Hmm, I disagree. It's confusing. You literally follow the directions perfectly (with the exception of not clicking on the button) and yet the onboarding tutorial does not advance.

Maybe just disable keyboard commands for the onboarding sequence then if you don't want to support it.

Also, for BusStop or perhaps for Tohme, we did train in users on keyboard commands.

**Comment by jonfroehlich** [comment]
We discussed this. Kotaro is going to disable keyboard commands for onboarding sequence for now.

In long term, we should come back to whether we want to onboard (in just one step) the use of keyboard commands. Could also put keyboard commands into the ? feature.

**Comment by kotarohara** [comment]
Fixed
