### ISSUE TITLE
Admin page takes a long time for server to generate

### ISSUE THREAD

**Issue by tongning** [ProjectSidewalk/SidewalkWebpage#588]
Even with the smaller test dataset, the server takes around 4-5 seconds to respond with the admin page after the initial request, according to the waterfall in Chrome dev tools. This may potentially be related to the OutOfMemory issues at #508.

I removed various elements of the admin page one at a time, to see which parts are contributing most to the page generation time. Documenting the results below for reference, time in seconds.

Original page:
(5.37, 4.45, 4.05, 4.55, 4.21)

Without the Recent Labels table:
(3.90, 3.61, 3.61, 3.76, 3.49)

Without the Activities table:
(4.19, 3.78, 3.57, 3.79, 3.66)

Without the Registered Users table:
(2.29, 2.28, 2.20, 2.13, 2.15)

The registered users table seems to be contributing a lot, especially with only ~150 users in the test dataset. Improving the table pagination so that the server doesn't have to return all of the data at once might help with this.

**Comment by manaswis** [comment]
Closing this issue as it is being tracked in #380
