### ISSUE TITLE
Analyze and improve server performance

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#589]
We need to better analyse and improve our server's performance. 

## Notes:
Here is the recent email exchange on this:

### Manaswi:
I checked the memory usage:

```
             total       used       free     shared    buffers     cached

Mem:          3830       3543        286          0        339       1542

-/+ buffers/cache:       1662       2168

Swap:          607         15        592
```

I think this is normal as I had allotted 3 GB to the application earlier.

However, I see some differences between the dev-server's usage with the production server's usage even though they share the same application configuration. For example, this is the memory usage of the dev server:

Dev-Server's usage
 ```
             total       used       free     shared    buffers     cached

Mem:          2887       2639        247          0        275        900

-/+ buffers/cache:       1463       1423

Swap:          607         33        574
```

The total memory is different. I was under the impression that configuration is the same. Am I missing anything?

Another difference in the load time of our admin page. Dev-server is faster than the production server. See below:

Production server:

Inline image 2
![image](https://cloud.githubusercontent.com/assets/2873216/25874727/16309486-34d1-11e7-9297-5c06b5534ef0.png)

Dev-server:

Inline image 1
![image](https://cloud.githubusercontent.com/assets/2873216/25874730/1b11dab4-34d1-11e7-8e78-2315f89e88f1.png)

Are there any differences in the hardware configuration between the two?

### Shawn (UMIACS):
While the `free` command gives a fairly decent representation of memory usage on a system, it’s not the best for comparing the usages between two processes as other processes on the system will influence it’s output.  For this I would recommend using the `top` command and sort the list by %MEM.  Using this we can see that the usage is fairly identical:

Sidewalk:

 ```
 PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND           
19457 sidewalk  20   0 2241m 1.2g  11m S  0.0 32.0 109:11.88 java      

```
Sidewalk-dev:

 ```
 PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND           
10996 sidewalk  20   0 2215m 972m  17m S  0.0 33.7  28:05.91 java    

```

Another quick note, the memory flag on the sidewalk java process seems to be set at 1G. I would expect it to be closer to ‘3072’ if you are setting the heap size to 3GB.   I don’t have output from the last time you changed this to compare, so this may be expected behavior, but it may be something to double check.

`sidewalk 19457  1.3 31.9 2295540 1254628 ?     Sl   May03 109:13 java -Xms1024m -Xmx1024m
`

As for performance… things could be better.

From my laptop I get a response time of around ~1.4 seconds on both pages. (MacOS 10.12.4, Safari, and on the UMIACS VPN). When using a tool such as apache benchmark to scale these tests up the results for the two pages are still fairly identical.

However, this benchmark also highlights some inefficiency at scale.  It took over 18 minutes to process 2000 request, running at a concurrency of 10-requests. As a comparison the UMIACS home page took 0.171 seconds to process the same number of requests.  Obviously the performance requirements of these two sites are different, but it may be something to consider taking a look at.  There are a number of online tools such as Google Page Insights [1] which analyze pages and provide best practice recommendations. 

For reference, this is the command I used for the benchmark:

`ab -k -c 10 -n 2000 sidewalk.umiacs.umd.edu/`

```
Sidewalk:
Concurrency Level:      10
Time taken for tests:   1286.754 seconds
Complete requests:      2000
Requests per second:    1.55 [#/sec] (mean)
Time per request:       6433.769 [ms] (mean)
Time per request:       643.377 [ms] (mean, across all concurrent requests)
Transfer rate:          36.73 [Kbytes/sec] received


Sidewalk-dev:
Concurrency Level:      10
Time taken for tests:   1085.839 seconds
Complete requests:      2000
Requests per second:    1.84 [#/sec] (mean)
Time per request:       5429.193 [ms] (mean)
Time per request:       542.919 [ms] (mean, across all concurrent requests)
Transfer rate:          45.33 [Kbytes/sec] received
```

As for your question about differences in hardware, these should be nearly identical.  The hypervisor they are running on may have different locations in our network, and a slight difference in CPUs they are running, but I would expect that to have a negligible impact.

**Comment by misaugstad** [comment]
Server performance is good nowadays, and when specific issues arise we create tickets for them and discuss with Jason. I don't think that this ticket needs to be open anymore.
