### ISSUE TITLE
Change Language on Mission Completed

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#60]
Current Language:
**Mission Complete!!!**
Good Job! You have successfully made 500 meters of this neighborhood accessible.

![image](https://cloud.githubusercontent.com/assets/1621749/14514674/de5e8a8e-01c0-11e6-9356-6f0388c12fda.png)

Suggested language for first mission completed in a neighborhood:
**Mission X Completed!** (where X=the overall number of completed missions)
Good Job! You just completed your first mission in <name of neighborhood>. You've audited X miles in <name of neighborhood> so far. Keep it up!

Suggested language for other missions completed in neighborhood:
**Mission X Completed!** (where X=the mission number)
Nice! You just finished auditing X miles in <name of neighborhood>. You've audited X miles in <name of neighborhood> so far and Y miles in total. Thanks for helping make <name of city> more accessible.

Also, for "Good Job!" and "Nice!" I think you should just have a string array of like 15 or 20 different things you could put here and randomly choose one for each message.

**Comment by nguyenist** [comment]
Here are 15-20 different strings you could use. Giving the app some personality never hurts. See <a href="https://medium.com/@awilkinson/slack-s-2-8-billion-dollar-secret-sauce-5c5ec7117908">this piece on Slack</a>): ```With Slack, a bubbly, bright UI, delightful interactions, and hilarious copywriting come together to create a personality. A personality which has triggered something powerful in its users: they care about it. They want to share it with others. It feels like a favorite co-worker, not a tool or utility.``` 
- Couldn’t have done it better myself.
- Aren’t you proud of yourself? We are.
- WOWZA. Even the sidewalks are impressed. Keep labeling!
- Your auditing is out of this world.
- Incredible. You're a machine! ...no wait, I am.
- Gold star. You can wear it proudly on your forehead all day if you'd like, we won't judge.
- Ooh la la! Those accessibility labels are to die for.
- We knew you had it in you all along. Great work!
- Wow you did really well. You also did good! Kind of like superman.
- You're one lightning bolt away from being a greek diety. Keep on going!
- "Great job. Every accomplishment starts with the decision to try." - That inspirational poster in your office
- The [mass x acceleration] is strong with this one. (Physics + Star Wars, get it?)
- Hey, check out the reflection in your computer screen. That's what awesome looks like.
- You. Are. Unstoppable. Keep it up!
- Today you are Harry Potter's golden snitch. Your wings are made of awesome.
- They say unicorns don't exist, but hey! We found you. Keep on keepin' on.
- "Uhhhhhhrr Ahhhhrrrrrrrrgggg " Translation: Awesome job! Keep going. - Chewbacca
- You're seriously talented. You could go pro at this.
- Forget Frodo, I would have picked you to take the one ring to Mordor. Great work!

**Comment by kotarohara** [comment]
@nguyenist This is an awesome list! Thanks :) I'll update the messages.
