### ISSUE TITLE
Landing Page: Results Button Jumps When Clicked

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#601]
The results button jumps when I try to click it and doesn't always go immediately to: 
http://sidewalk.umiacs.umd.edu/results

![image](https://cloud.githubusercontent.com/assets/1621749/26231416/0e2d8c50-3c1d-11e7-803c-a5ec766d8ceb.png)

**Comment by manaswis** [comment]
Closing via #603
