### ISSUE TITLE
Teleporting Automatically

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#61]
I was just on a street that ended in a deadend and suddenly I was transported to a brand new audit area. I think we need to give more feedback to the user about what's happening (before we transport them) or it's very disorienting. I fear that users will get confused or even frustrated (they may even think that they lost work).

**Comment by kotarohara** [comment]
Ya. I'll try to work on that.

**Comment by kotarohara** [comment]
I now show the following message when the tool jump you back into the neighborhood.

![image](https://cloud.githubusercontent.com/assets/612263/15404832/5dca3fca-1dcd-11e6-904e-18638c914a4e.png)

**Comment by jonfroehlich** [comment]
Can we update the message to something like this:

**Neighborhood Teleportation Complete!**
We just magically teleported you to a different location in your current neighborhood. This often happens when you reach the end of a road segment. Keep up the good work, and thanks for helping make this neighborhood more accessible for everyone!

**Comment by jonfroehlich** [comment]
Maybe take out word magically? Not sure. Just trying to make it fun--but maybe it feels too forced...
