### ISSUE TITLE
Add esc key as an option to close label context menu

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#611]
After placing a label, the context menu where severity is rated can be closed by
1. hitting enter
2. selecting another label
3. panning with mouse
4. clicking "OK" in the bottom right of the menu
5. clicking the "x" in the top right of the menu

The presence of the "x" in the top right makes me think that the esc key should be able to close the context menu. When I hit escape, it doesn't seem to do anything at all, so what do we think about including it?

Also, panning with the mouse closes the menu, but panning with the arrow keys does not; should this be consistent?

**Comment by jonfroehlich** [comment]
Sure. Esc can close context menu. 

Not sure about keys to pan. Probably should be consistent. We should vote as a team. 

PS how common is using keyboard for panning?
