### ISSUE TITLE
Changing label only updates cursor in GSV after movement

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#613]
[video](https://www.youtube.com/watch?v=6tOrmMRTGmg&feature=youtu.be)

The video above shows what I mean, but here is a description in words: I select one type of label, say a curb ramp, by hitting "c". Then I switch to another type of label, say no sidewalk, by hitting "n", but the image that shows up as the cursor stays as the curb ramp label icon _until I move the mouse_.

This happens for any combination labels, and it happens whether I had just placed a label or if I had just been switching types of label without placing any.

I see the same behavior under both Chrome (58.0.3029.110 (64-bit)) and Firefox (53.0.2 (64-bit)), though I am running Ubuntu 14.04, so who knows :)

And this has been happening to me for a couple weeks I think, I had just gotten used to it and forgot about it, but it isn't that new.

Anyone else seen this or anything like it?

**Comment by jonfroehlich** [comment]
I've seen it a ton. And always meant to make a video to show it explicitly (though you can see it in my previously recorded videos if you look closely). 

My guess is a mouse move causes a cursor refresh. Anyway to force this to occur?
