### ISSUE TITLE
Need backend code to filter out users who don't seem to be auditing

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#615]
Context: Automated walker tests carried out on the production site created a large number of audits without labels. This interferes with the published stats (% of DC mapped and miles covered). Code to filter out the (related missions)/(at least ignore users identified for testing/bots in the stats) doesn't seem to exist (needs confirmation). 

This would also come under quality control. 
1. Detecting suspicious activity. (Define this)(In this case, too many audits without labels).
2. We may need to confirm that a route truly doesn't need any labels before discarding it.

**Comment by jonfroehlich** [comment]
Thanks for the nice writeup. 

1. To filter out potentially poor quality workers or missions would be a difficult task and worthy of PhD research. This is what Soheil was working on. I have some ideas on this I can share at our next meeting

2. We will likely want diff types of filtering/data cleaning for quality control, research purposes, to calculate public facing stats and admin dashboard. We could certainly do something simple for the latter, however. 

3. Please don't do any more empty or non-real audits on production server.

**Comment by misaugstad** [comment]
@maddalihanumateja are we doing a very simple implementation of something like this to weed out turkers who aren't doing any labeling?

**Comment by maddalihanumateja** [comment]
No mikey. There is no filter right now. There were a lot of things I mentioned in the pull requests to include turker audits on the production site.

**Comment by misaugstad** [comment]
1. I meant to ask if we are going to implement, not if we had already implemented.

2. What does you mentioning "a lot of things" in some PR have to do with the question..?

**Comment by misaugstad** [comment]
We have created a new issue for this, #1082 so I am going to close this issue. I will reference it from the newer issue so we can look back at this one.
