### ISSUE TITLE
Google Map Avatar Guy Disappeared

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#62]
I was in the middle of auditing when suddenly my Google Map avatar guys disappeared. See screenshot:

![image](https://cloud.githubusercontent.com/assets/1621749/14514904/e7c84efa-01c2-11e6-9da8-ff7f3e86ce7d.png)

**Comment by kotarohara** [comment]
This is a bug in Google Maps and Street View APIs. I can't do anything about it.

**Comment by jonfroehlich** [comment]
Maybe keep it open though so that we don't get duplicates?
