### ISSUE TITLE
GSV Error Continued: Quick navigation results in undefined pano IDs

### ISSUE THREAD

**Issue by sagec108** [ProjectSidewalk/SidewalkWebpage#621]
Referencing the investigation in #608, the team found that one cause of the frequent GSV error pop-up was navigating too quickly. In the discussion, @manaswis suggested separating this issue from the issue of frequent GSV Error pop-up errors. 

One suggested solution for handling this bug is to limit the number of steps the user can take at a time (e.g cannot have more than 2 steps/sec) or to rephrase, letting the system process the step before allowing the user to take the next step.

**Comment by manaswis** [comment]
Closed via #744
