### ISSUE TITLE
onError Happened: Website Down

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#626]
We must fix the admin interface immediately to either remove the offending components that contribute to the memory leak or fix them. My suggestion is the former to solve this quickly. We should *not* be able to crash the website by using the admin interface. This is incredibly frustrating.

![image](https://cloud.githubusercontent.com/assets/1621749/26696834/0c87abee-46de-11e7-9565-16bbb51e1787.png)

**Comment by jonfroehlich** [comment]
Now I'm getting:

![image](https://cloud.githubusercontent.com/assets/1621749/26696983/975f49fc-46de-11e7-8062-58ee66ef577f.png)

**Comment by manaswis** [comment]
This was also (temporarily) resolved. See issue #546 and the https://github.com/ProjectSidewalk/SidewalkWebpage/issues/546#issuecomment-321861594.
