### ISSUE TITLE
What To Do In Cases Of Conflicting Information Based on GSV Timeshot

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#63]
I just found an area that lacked a curb ramp but in next image it was there:

![image](https://cloud.githubusercontent.com/assets/1621749/14514956/63675fec-01c3-11e6-8a7f-b8f34c0a8aec.png)

![image](https://cloud.githubusercontent.com/assets/1621749/14514959/69387f14-01c3-11e6-8315-fc6f7c828f40.png)

**Comment by jonfroehlich** [comment]
I think we need to have an FAQ page--lots of crowdsourcing pages have this and this can be an entry on that. So, really, we need a git issue for the FAQ page.

**Comment by kotarohara** [comment]
Added to FAQ
