### ISSUE TITLE
Stored panoramas and results of cropping experiments are missing!

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#633]
Needs to be located. It used to be in the folder - `/fs/jonf-sidewalk/Panoramas` on the sidewalk server. Possible cause could be that the folders got moved to some other location during the hypervisor update. TODO: Contact UMIACS to figure it out.

**Comment by manaswis** [comment]
Update: I logged into the server and checked the folder, the data is there. I see these folders
`scrapes  scrapes2  scrapes3  scrapes4  scrapes5  scrapes5.tar.gz  tohme`
@tongning can you confirm if anything is missing?

**Comment by jonfroehlich** [comment]
Um, this is weird. Why did @tongning report that this data was missing?

@tongning, can you do as @manaswis suggested and confirm if anything is missing. Also, can you explain:
- the organization of the scrapes folder
- where you exported the crop experiments to and your results writeup for this

**Comment by tongning** [comment]
Ah, I think I see what happened. The sidewalk server is configured to not allow directory listings under `/fs`, so if you run `ls` there, the folder will seem empty. The files only appear if you go directly to `/fs/jonf-sidewalk`. Sorry for the false alarm.

![sidewalk-ls](https://user-images.githubusercontent.com/7234278/26958819-9452e48c-4c81-11e7-8522-33affafc2a34.PNG)

Anyway, all the files appear to be in order. `scrapes{1-4}` are just older, so probably only `scrapes5` is needed for now. All of the files are grouped into folders corresponding to the first two characters of the panorama ID they are associated with.

For each panorama there is a file `<panoid>.jpg`, which is the panorama itself, and `<panoid>.xml`, which is some metadata about the panorama scraped from Google and includes depth data. There is also a `<panoid>.depth.txt`, which is just the depth data extracted from the xml and converted into a matrix form that can be more easily read.

If there are Curbramp or Missing Curbramp labels on the panorama, the bounding boxes for those labels will be in <panoid>_curbramp.txt and <panoid>_nocubramp.txt respectively. Each line in those files correspond to a distinct label. I think the format is just `x1 x2 y1 y2` with the top left corner of the image being the origin.

The size of these bounding boxes were determined using the auto-cropping algorithm, so these are effectively crops. I do have actual JPEG crops on [Google Drive](https://drive.google.com/drive/folders/0B5GfMjv5gBQ1clBPUkRZMDhPTzQ?usp=sharing), though they're probably somewhat dated by now. New crops can be generated using `CropRunner.py` in sidewalk-panorama-tools.

I tested the crop size determination algorithm using the Tohme data (so only curbramps) and made a couple error plots - here they are:

![predicted vs actual width](https://user-images.githubusercontent.com/7234278/26959596-a4a202ec-4c85-11e7-8d26-d35fc4c3afcd.PNG)
![distance vs error](https://user-images.githubusercontent.com/7234278/26959599-a62738c6-4c85-11e7-8049-773367cfd61f.PNG)
![distance vs bbox width ground truth](https://user-images.githubusercontent.com/7234278/26959602-a7cbf6a8-4c85-11e7-8607-ec0dd49487ae.PNG)

**Comment by manaswis** [comment]
Closing this issue. The panoramas have been located.
