### ISSUE TITLE
Things Needed for Potential SMU Collaboration (and API Improvements in General)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#639]
As discussed briefly yesterday, some folks at SMU would like to collaborate with us on Project Sidewalk. To help get them off the ground, they need:

- Access to the raw label data + metadata (e.g., severity ratings, label type, lat/long, x,y location in panorama, panoid, etc). Hopefully, this can be accessed through http://sidewalk.umiacs.umd.edu/developer. However, I just briefly looked at this and while the [Access Features API](http://sidewalk.umiacs.umd.edu/developer#access-api-access-feature-row) looks relevant, I don't think it's exactly what we want. I was envisioning an API that allows you to pass a lat/long bounding box (as the current API does) but then returns a JSON list of all labels + metadata in that area.

- Access to the underlying scraped panorama and LiDAR depth data given a panoid. For this, we will have to develop a "private" API that can only be used by us and partners (as I'm concerned about breaking Google TOS, though I haven't investigated this). Perhaps when using this API, the developer just has to pass in a key in order to get a result. Alternatively, we can just ship them a data dump of the panoramas and depth data (which is well organized) that they can use with the label data API.

Ideally, we would be able to prepare this relatively quickly but I realize the team is busy with the relaunch. It could be a task for @sagec108 though @maddalihanumateja is now in charge of the panorama and depth data scraper.

**Comment by maddalihanumateja** [comment]
Just started trying out the scraping code. Since tongning mentioned an API update I'm also curious about the potential number of failed downloads. Right now, I think shipping a data dump of panoramas is a better idea in the case that we decide to move ahead with the collaboration.

**Comment by jonfroehlich** [comment]
Ok, I think there are some concerns about running the scraping code on UMD domains as we wouldn't want them blocked. I believe @tongning was using AWS.

**Comment by jonfroehlich** [comment]
For the [Access Features API](http://sidewalk.umiacs.umd.edu/developer#access-api-access-feature-row), perhaps we change this API to be by neighborhood rather than lat/long bounding box coordinates. @manaswis brought up an important point during our 1:1. If someone uses the API and requests a large lat/long bounding box, this query could crash our backend with an out-of-memory error (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/508).

**Comment by tongning** [comment]
I ran the scripts on DigitalOcean but I can't think of any reason AWS wouldn't work. The scrapes should take up ~100GB so I think it would be a good idea to have at least 150-200GB of space available to save the panoramas. I used [sshfs](https://www.digitalocean.com/community/tutorials/how-to-use-sshfs-to-mount-remote-file-systems-over-ssh) to mount the Project Sidewalk server as a remote filesystem to avoid needing that much space on the cloud host, but that might not be necessary if the added cost is acceptable. The main issue with sshfs is that you have to reconnect if the SSH connection breaks (for instance if UMIACS reboots for updates.)

**Comment by misaugstad** [comment]
The different things mentioned here have been split into separate issues, so I'm closing this one. (#939 and #2483)
