### ISSUE TITLE
Strange Jump Based on GSV Car Side of Street

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#64]
Sometimes when you are walking on a large multi-lane street, the view will jump from one side of the street to the other... probably because of how the GSV car drove through those streets and how Google stitched together the data. I imagine this jumpiness could be a bit confusing to the user.

The following is an example of just one step forward, which jumps me to the other side of the round (though I'm still facing the same direction).

![image](https://cloud.githubusercontent.com/assets/1621749/14515061/45f6ed28-01c4-11e6-8b64-e96e67594c6e.png)

![image](https://cloud.githubusercontent.com/assets/1621749/14515068/4d6d8314-01c4-11e6-945d-0c5fe1543b45.png)

**Comment by kotarohara** [comment]
I'm aware of it and it but there isn't anything I can do about this as it's Street View API's behavior. I'm closing the issue.

**Comment by jonfroehlich** [comment]
Maybe we create an FAQ page w lil movies or animated gifs of common problems or idiosyncrasies that we can't fix
