### ISSUE TITLE
Weird Route Bug: Routed Up and Down Same Street

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#65]
I basically was routed up and down the same street (sorry, my little avatar guy is not visible):

![image](https://cloud.githubusercontent.com/assets/1621749/14515138/c9b14c4e-01c4-11e6-8e72-63cdc3d378aa.png)

It looks like this happened because of the median, so I was directed down both sides of the road. Not a bad thing, but again, could be confusing.

**Comment by kotarohara** [comment]
It happens because of the median. The street segment data (used to navigate a user) that I imported from OpenStreetMap has that kind of data.

**Comment by jonfroehlich** [comment]
OK, fair enough. Perhaps this is also a candidate for our FAQ.

Jon

On Thu, Apr 14, 2016 at 7:31 PM, Kotaro Hara <notifications@github.com>
wrote:

> It happens because of the median. The street segment data (used to
> navigate a user) that I imported from OpenStreetMap has that kind of data.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ProjectSidewalk/SidewalkWebpage/issues/65#issuecomment-210202306>
>



-- 
Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich <https://twitter.com/jonfroehlich> - Twitter
