### ISSUE TITLE
Reduce header size for the audit interface

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#652]
Reducing header size (only on the audit interface page) such that the tool fits in the screen without the need for scrolling down. It would be around 10 px.

**Comment by jonfroehlich** [comment]
And we can rescale the branding logo in photoshop as necessary so that we don't have to rely on the web browser's image scaling algorithm (which often results in blurry output).

**Comment by manaswis** [comment]
Closed via #677
