### ISSUE TITLE
Add versioning on the backend

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#653]
Have a table that indicates when the version that's being used, the date when it was deployed and the end date (date when the next version was deployed).

**Comment by jonfroehlich** [comment]
That's just one idea on how to make future analyses easier so that we can do version-based queries rather than date-based queries. The former feels more robust and less open to human error.

**Comment by misaugstad** [comment]
When this is done, an example of something that should be switched over to using this table is #873. It uses the date that some sort of logging began and it is hard-coded right now.

**Comment by misaugstad** [comment]
I'm writing the code for this now. What I'm thinking is to have just 3 columns (version_id: String, version_start_time: Timestamp, description: Option[String]). Can anyone think of additional information we would need to keep track of in a table for each version?

**Comment by jonfroehlich** [comment]
My immediate reaction is this looks good but I didn’t think too deeply about it :-)

**Comment by misaugstad** [comment]
Closing via #1345
