### ISSUE TITLE
Pop-up instruction to teach users to double click for walking

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#655]
Have a pop-up to say "Trouble walking ahead? You can walk in this direction by double clicking!" or something similar. The message would be displayed in a pop-up similar to this:

![image](https://user-images.githubusercontent.com/2873216/27048473-006bba5e-4f7a-11e7-8d7d-c24aedc83d08.png)
 
This is useful for the user to move in the direction where there isn't a navigation arrow to click and they are being routed in that direction. Example:

![image](https://user-images.githubusercontent.com/2873216/27048453-e57b601e-4f79-11e7-8dbd-1f1da6675b40.png)

There is a FAQ entry for this [here](http://localhost:9000/faq#what-to-do-when-navigation-arrow-disappears). However, having this would be useful.

**Comment by jonfroehlich** [comment]
How would we know to show the pop-up? I'm confused.

**Comment by manaswis** [comment]
Two options:

1. Show the pop-up if the user clicks the navigation arrow x times (similar to what we do for keyboard shortcuts and remind to rate)
2. Automatically detect when the arrow doesn't exist for the direction of the route. 
     This is hard but worth investigating. I know we can get information of the navigation arrows (also known as 'links' in GSV lingo). The challenge would be to link the direction of the route to the arrows.

**Comment by jonfroehlich** [comment]
I don't think 1. is a good signal. Will be noisy.

So, 2. is a better option but I agree that this will likely be hard. We should have an intern investigate imo.

**Comment by manaswis** [comment]
I agree.

**Comment by manaswis** [comment]
I'll assign it to @sbower213.

**Comment by misaugstad** [comment]
This is no longer a feature in GSV. We've replaced this with the new 'Stuck' button!
