### ISSUE TITLE
Corrective Guidance in the Tutorial: Inform user if the label is not placed in the right location

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#657]
Another good-to-have feature for relaunch (if time permits). 

Give user instruction to correct if the user applies the label in the incorrect location (or too far away from the correct location). Currently, the tutorial waits for the right input instead of telling the user that their action is incorrect.

Additional idea:
Show an animated arrow (top to bottom motion) pointed to the location to emphasize.

**Comment by jonfroehlich** [comment]
Yes. Good idea. We had this in our old tutorials (e.g., for Tohme, etc.)

**Comment by manaswis** [comment]
Closed via PR #684
