### ISSUE TITLE
5000 Meters Is Too Long for Mission Length

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#66]
I just finished a 5,000 meter mission and I almost dropped out a few times. It was way too long unfortunately and I was desperately wanting the mission to end (the current mission status bar is broken and the red path in the top-down GMaps view kept getting longer as soon as I reached its end).

So, I think 5,000 meters is too long. Perhaps the longest single audit length should be 2,500 meters within a mission.

Also, if I stop in the middle of the 5,000 meter audit and log back in later, will I resume my audit at the exact same place. If not, I think this is necessary.

**Comment by kotarohara** [comment]
Ok. The distance between 2500 and 5000 should be 2500 (related issue #55 ). If you feel that's too long, I'll cap every mission with half-ish of it. Like 1000-1500 meter or 1 mile.

**Comment by jonfroehlich** [comment]
Yah, it just felt exhausting. For some reason, when we break up the audit
into chunks, it doesn't feel that way. So, even if I do 5,000 meters but
broken up over multiple missions, it feels more sane/achievable and fun.

On Thu, Apr 14, 2016 at 7:26 PM, Kotaro Hara <notifications@github.com>
wrote:

> Ok. The distance between 2500 and 5000 should be 2500 (related issue #55
> <https://github.com/ProjectSidewalk/SidewalkWebpage/issues/55> ). If you
> feel that's too long, I'll cap every mission with half-ish of it. Like
> 1000-1500 meter or 1 mile.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ProjectSidewalk/SidewalkWebpage/issues/66#issuecomment-210201529>
>



-- 
Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich <https://twitter.com/jonfroehlich> - Twitter
