### ISSUE TITLE
Stuck in a 360 Selfie?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#668]
I am stuck in a 360 selfie and can't seem to move out of it. :)

svl.panorama.getPano();
"F:-3f2o0Du8fA0/WNw3jJ2edDI/AAAAAAACYqo/WO7MTt2u-ak4dqA_wRRC0q0uf6x78_A6wCLIB"
(svl.taskContainer.getCurrentTask()).getStreetEdgeId();
26319

![image](https://user-images.githubusercontent.com/1621749/27101871-520a0b22-5051-11e7-9626-e6f9bb4bc04f.png)

**Comment by manaswis** [comment]
Closed via PR #789
