### ISSUE TITLE
Stay Signed In

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#67]
I think Project Sidewalk should keep you signed in (or at least give you the option). This seems to be the way modern web apps work--not sure why ours is different. Every time I visit, I have to re-sign in.

![image](https://cloud.githubusercontent.com/assets/1621749/14540178/c06084ec-0251-11e6-9bf9-78bd26f7a884.png)

**Comment by mattm401** [comment]
I had the same thought.

**Comment by kotarohara** [comment]
Should be done. It will be effective when I upload the update version next time. I think your session will be reset every time I push the new version though.
