### ISSUE TITLE
Fix the Follow the Navigator and Audit the Street Dialog

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#675]
![image](https://user-images.githubusercontent.com/1621749/27151370-5d76b22c-5118-11e7-8fc3-e0561e7dbab5.png)

Two problems with this dialog:

1. The dialog is not centered vertically in the GSV pane
2. The text should be polished. I suggest

**Let's Take a Step!**
It looks like you've looked around this entire intersection, so it's time to explore other areas. Walk in the direction of the red line highlighted on the map.

**Comment by manaswis** [comment]
Updated in #671 

![image](https://user-images.githubusercontent.com/2873216/27284111-6141fb22-54c5-11e7-90eb-f32bc8cd4680.png)
