### ISSUE TITLE
GSV Error in Tutorial

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#679]
Uh oh, I got the GSV error in the tutorial on the sidewalk-dev server (however, this is not running @sagec108's new GSV error code). Not sure what triggered this... but clearly we should not jump people during the tutorial if this error does, for some weird reason, happen to occur.

![image](https://user-images.githubusercontent.com/1621749/27191187-0e5d46a8-51c5-11e7-9436-d7c260cb5133.png)

**Comment by manaswis** [comment]
Employed a temp fix of using the same tutorial pano ID. Since the walk tutorial will be updated soon and finding the other pano id is time consuming, this should work till we have our new tutorial up.

What do you guys think?

Check it out here - http://sidewalk-dev.umiacs.umd.edu/audit
