### ISSUE TITLE
Already Completed Onboarding Tutorial But Forcing Me To Retake It

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#68]
I completed the onboarding tutorial already.

On my Windows box at home, I don't have to complete the onboarding tutorial (this is the correct behavior) but when I try to use Project Sidewalk at work, it forces me to complete the onboarding tutorial again after I log in.

![image](https://cloud.githubusercontent.com/assets/1621749/14540298/4ebab302-0252-11e6-8504-da95575bb212.png)

**Comment by kotarohara** [comment]
Should be fixed.
