### ISSUE TITLE
Integrate Sidewalk logo into loading gif

### ISSUE THREAD

**Issue by sagec108** [ProjectSidewalk/SidewalkWebpage#689]
#658 added a loading gif to the page. Jon noted in the issue to incorporate the logo into the loading gif by perhaps adding a "Loading ..." message below a gif with the actual logo that incorporates the spinning animation.

Jon's comment for reference:
> Integrating the Project Sidewalk logo in some way (how about using the actual logo, centered on page, and then have the wheels spinning. @chishankar could likely make this animated gif for you pretty quickly). Perhaps add a message below this with "Loading..."

**Comment by jonfroehlich** [comment]
Where the wheel of the wheelchair itself spins indicating loading.

**Comment by jonfroehlich** [comment]
Here's a version. Took me literally 10 mins. :)

![ProjectSidewalk_Loading_WheelAnimation3_WithSidewalk_w100](https://user-images.githubusercontent.com/1621749/95016266-c9320100-0606-11eb-96fc-4a32a609f804.gif)

**Comment by jonfroehlich** [comment]
Integrating now:

## Loading audit page
![image](https://user-images.githubusercontent.com/1621749/95028501-792e5b00-0655-11eb-9a6e-4ac2eb7ca941.png)

![image](https://user-images.githubusercontent.com/1621749/95028515-92370c00-0655-11eb-9557-fa18a9bc452f.png)

## Loading results page

![image](https://user-images.githubusercontent.com/1621749/95028547-c01c5080-0655-11eb-969f-2b4cfe0cedbc.png)
