### ISSUE TITLE
Mouse Cursor Icon Does Not Change to Hand On Pan in Tutorial

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#69]
This is on Windows 7 with Chrome.

As you can see, during the tutorial, the mouse cursor does not correctly switch to a hand (which makes the hand animation confusing).

![image](https://cloud.githubusercontent.com/assets/1621749/14540331/81bcf1ca-0252-11e6-81f7-f3b574896d1d.png)

**Comment by kotarohara** [comment]
Duplicate of #42 .

**Comment by jonfroehlich** [comment]
Yay, we finally fixed this! Nice!
