### ISSUE TITLE
Consider using return/enter key to dismiss pop-ups

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#690]
I often want to use the return/enter key to dismiss a pop-up since its common practice elsewhere as well. However, do we want to have it because users might just dismiss the pop-up before reading it. Mouse click might encourage them to read the pop-up message. However, that maybe wrong - its my intuition.

What do you guys think?

**Comment by jonfroehlich** [comment]
I think return key to dismiss pop-up is fine

**Comment by manaswis** [comment]
#671 doesn't take care of OK buttons in mission dialog boxes

![image](https://user-images.githubusercontent.com/2873216/27295961-e9642490-54ec-11e7-9450-73d19909298e.png)

**Comment by manaswis** [comment]
Closed via #671.
