### ISSUE TITLE
Red line on the top-down map is displaced from the route

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#694]
![image](https://user-images.githubusercontent.com/2873216/27289009-7a5617ae-54d6-11e7-8860-c5fbeb7af6fe.png)

Screenshots showing the route at different points on this route (street Id: 5033; Direct Link: [on sidewalk-dev server](http://sidewalk-dev.umiacs.umd.edu/audit/street/5033)):

Start of the route:
![image](https://user-images.githubusercontent.com/2873216/27289077-ac5992a8-54d6-11e7-8c2e-3058546bedcd.png)

2 steps forward:
![image](https://user-images.githubusercontent.com/2873216/27289064-a24ff144-54d6-11e7-871d-391266f3bb41.png)

Moving further ahead and close to the point of the original screenshot:
![image](https://user-images.githubusercontent.com/2873216/27289035-9331578e-54d6-11e7-9fac-fcad285367e2.png)

### Another example

Street id: 9567
![image](https://user-images.githubusercontent.com/2873216/27343698-b1f88e9a-55b1-11e7-89c1-954536534145.png)

This is near street id: 21700 (half audited street below). 
![image](https://user-images.githubusercontent.com/2873216/27343125-fa106998-55af-11e7-882b-7ccdc6ab5336.png)

**Comment by jonfroehlich** [comment]
This is just an isolated incident, right?

**Comment by manaswis** [comment]
Yes. Haven't seen it on other streets.

**Comment by manaswis** [comment]
Its present on the main server as well which means it hasn't been caused due to any recent updates.

**Comment by jonfroehlich** [comment]
I think the key thing here is that it is *not* a systemic problem, which your original issue did not make clear.

**Comment by manaswis** [comment]
It happens for a few streets. I just updated the original issue post with another example. Its infrequent but happens.

**Comment by jonfroehlich** [comment]
![image](https://user-images.githubusercontent.com/1621749/29052011-e4154070-7bb4-11e7-90e3-78280d9af165.png)

**Comment by misaugstad** [comment]
This does not seem important, is not super common, and seems like it is the fault of OSM :(
