### ISSUE TITLE
Change 'Map Accessibility' Menu Item Name To Something Else

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#70]
The 'Map Accessibility' top-level menu name is confusing. To me, the name makes me think that the menu item opens a map. We need to have a verb rather than a noun here.

Alternatives:
Begin Auditing
Audit DC
Start Auditing
Audit

I also suggest moving this menu item to the most left menu item (so switch with Access Score).

**Comment by kotarohara** [comment]
I set it to Start Auditing. Also I hid the link to the Access Score as it is not polished yet at the moment ( #49 ). Should show up next time I upload the app.
