### ISSUE TITLE
Delete icon moves with you if the mouse was hovered over the label when user takes a step

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#705]
If the mouse pointer was hovering over the label, and the user walks using the keyboard, the delete icon goes with you unless you move the mouse pointer, at which point it hides. Looks like this:

![image](https://user-images.githubusercontent.com/2873216/27334403-36d38ce8-5597-11e7-8eb9-c8ef572653be.png)

![image](https://user-images.githubusercontent.com/2873216/27334382-282aae24-5597-11e7-8828-0776ae917cf8.png)

**Comment by manaswis** [comment]
To add, its not an artifact of the new changes. It exists on the main server as well.

**Comment by jonfroehlich** [comment]
Seems like something @sagec108 could rock quite easily. :)

**Comment by manaswis** [comment]
Closed via #709
