### ISSUE TITLE
Slight Update to "Contributing A Lot" Dialog. Increase Space Between Buttons.

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#710]
The buttons are too close together.

![image](https://user-images.githubusercontent.com/1621749/27338960-772a06e8-55a4-11e7-9210-5b91310f56cd.png)

Perhaps we also want to make the benefits for signing up more clear. What are key ROIs to the user for doing this? (In the past, we were going to use it for leaderboard type things, etc.... but we obviously haven't had a chance to implement this stuff).

**Comment by manaswis** [comment]
Closed via PR #740
