### ISSUE TITLE
Admin page: Onboarding time chart incorrect

### ISSUE THREAD

**Issue by adash12** [ProjectSidewalk/SidewalkWebpage#716]
The chart on the admin page which shows bounce rate completion time and bounce rate displays inaccurate data.
![image](https://user-images.githubusercontent.com/13080218/27347406-746700d6-55be-11e7-87fe-a92fe7d064a2.png)

The times and bounce rates are calculated based on earliest and latest Onboarding_Transitions per audit task, but it's not checked if the last Onboarding_Transition is an outro transition. Similarly with bounce rates, a bounce is considered as only a single Onboarding_Transition, not multiple Onboarding_Transitions that aren't finished with an outro.

Related to issue #288 and issue #342

**Comment by jonfroehlich** [comment]
This ticket doesn't make any sense to me but hopefully has sufficient information for @manaswis and @misaugstad

**Comment by adash12** [comment]
I discussed with Mikey and he said I could go ahead and fix it.
