### ISSUE TITLE
Tutorial: Deleting first curb ramp prevents tutorial from proceeding

### ISSUE THREAD

**Issue by sbower213** [ProjectSidewalk/SidewalkWebpage#719]
In the tutorial, if you delete the first curb ramp icon immediately after placing it (i.e. without rating), the tutorial will display the following message and not allow you to place any more feature icons: 
![tutorial freeze](https://user-images.githubusercontent.com/8651110/27350985-f2652336-55c9-11e7-9690-0c775f9b3ea1.png)

While you can click the undo button to re-display the curb ramp icon, a new message should probably be shown to provide some indication of this.

**Comment by jonfroehlich** [comment]
Yikes, good catch. We should check what happens when you delete labels throughout different parts of the tutorial

**Comment by manaswis** [comment]
Yes, currently its not handled. I'll add a message to tell the user to reapply the label by using undo/redo buttons if they deleted a label. Will also train them on undo and redo buttons.

**Comment by sbower213** [comment]
Just ran through the tutorial again. This also happens with the first missing curb ramp label placed, but not with the no sidewalk feature. I think the hangup is waiting for a rating on a current label when its been deleted.

**Comment by jonfroehlich** [comment]
@sbower213 you should always include screenshots to improve understanding of your textual description.

**Comment by manaswis** [comment]
Ideally, it will happen for all labels with ratings. We should make sure none of the labels are deleted during the onboarding process. I'll update it.

**Comment by jonfroehlich** [comment]
We need to fix this. I think either @manaswis or @sagec108 or @maddalihanumateja could do it.

**Comment by manaswis** [comment]
Its already in progress.

**Comment by manaswis** [comment]
Closed via #784
