### ISSUE TITLE
Update "What We Do With Your Labels" Text On Landing Page

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#720]
![image](https://user-images.githubusercontent.com/1621749/27351806-9014299a-55cc-11e7-82a9-775ea7fc5979.png)

I think we should change: "Your contributions help train machine learning algorithms to identify accessibility issues automatically" to "Your labels are used to improve city planning, to forecast future accessibility problems, to build new accessibility-aware mapping tools, and to train machine learning algorithms to identify accessibility issues automatically."

Perhaps we can trim my suggested sentence a bit but overall, it's more inline with the graphic.

**Comment by misaugstad** [comment]
How is this? I tried really hard to keep it to 4 lines.

![what_we_do](https://user-images.githubusercontent.com/6518824/27405315-18b7cbbc-569f-11e7-8171-cf22b4cdbd61.png)

If I include the part about forecasting, I don't see how to keep it to 4 lines, but with a 5th line we start hugging up against the next module, so we would need to shrink the image or increase the size of this module.

![what_we_do-longer](https://user-images.githubusercontent.com/6518824/27405478-b0c33af4-569f-11e7-8d1e-2cbc40e5a335.png)

**Comment by jonfroehlich** [comment]
I like the 4-line version better. Thanks for your edits.

Leah suggested: "... train machine learning algorithms to automatically find accessibility issues."

Which I like better. So, after that change, we should be good!

**Comment by misaugstad** [comment]
Closed via #738
