### ISSUE TITLE
Are We Logging Interaction With New Choropleth Map?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#721]
Are we logging when:
- users mouseover this map (probably lots of data and maybe not useful)
- when they click on a region
- when they actually click on 'click here'

Also, we should probably log the message that they are shown to inspire the click because I know this message changes...

Tagging @misaugstad

**Comment by misaugstad** [comment]
Good catch, yes definitely need to record this as well.

**Comment by manaswis** [comment]
Closed via #763
