### ISSUE TITLE
Cumulative Statistics on the Front Page Bleeds Over in Safari

### ISSUE THREAD

**Issue by chishankar** [ProjectSidewalk/SidewalkWebpage#727]
This does not seem to be an Issue on Chrome, but on Safari the front page statistics bleeds over to the next section:

![screen shot 2017-06-21 at 9 08 37 am](https://user-images.githubusercontent.com/25187819/27385689-8049d1dc-5661-11e7-8f97-2b5f254db335.png)

**Comment by jonfroehlich** [comment]
Good catch. Would be nice to fix this for relaunch... will have to see where this fits in our priority list.

**Comment by maddalihanumateja** [comment]
This doesn't happen on the Firefox and Mac OS X combo either.

**Comment by ThatOneGoat** [comment]
I was able to repro this with on a Mac OS using Safari:
![Screen Shot 2020-05-04 at 4 37 30 PM](https://user-images.githubusercontent.com/37346427/81027542-0d8c5b80-8e33-11ea-9efe-f1f709320c41.png)

I also tried it on Chrome, and the overflow issue wasn't there

**Comment by misaugstad** [comment]
closing via #2149
