### ISSUE TITLE
FAQ Page Off Center

### ISSUE THREAD

**Issue by chishankar** [ProjectSidewalk/SidewalkWebpage#728]
Not sure if this is a big problem or not, but the bottom of the FAQ page seems to be a little off center, this should be a quick fix though. 

![screen shot 2017-06-21 at 9 28 37 am](https://user-images.githubusercontent.com/25187819/27386680-8c6d0b34-5664-11e7-8c23-4eb15f57d80a.png)

**Comment by manaswis** [comment]
Closed via #790
