### ISSUE TITLE
FAQ Links Calibration

### ISSUE THREAD

**Issue by chishankar** [ProjectSidewalk/SidewalkWebpage#729]
When clicking on "Is Google Street View a reliable data source?" , the page goes past the title a little further down than it should be. 

Chrome:
![screen shot 2017-06-21 at 9 33 38 am](https://user-images.githubusercontent.com/25187819/27386755-c6c09224-5664-11e7-854b-c4c1ea994b92.png)

Safari:
![screen shot 2017-06-21 at 9 33 23 am](https://user-images.githubusercontent.com/25187819/27386756-c6c0c276-5664-11e7-95b3-ce6b3e797db4.png)

**Comment by chishankar** [comment]
I see that happening for most links. I am assuming it was programmed like that to get address the question. But maybe we can move the webpage up a little more so that the user can see the question that clicked on to see.

**Comment by jonfroehlich** [comment]
Agree

**Comment by sbower213** [comment]
I think the links jump to the right place (according to the browser), but the navbar is hiding the content we want to see. Found some potential fixes [here](https://github.com/twbs/bootstrap/issues/1768).

**Comment by chishankar** [comment]
Issue has been fixed. I also added Contact US to the FAQ panel and made it flush with the rest of the FAQ items. 
<img width="261" alt="screen shot 2017-06-29 at 4 42 55 pm" src="https://user-images.githubusercontent.com/25187819/27709520-692a37b4-5cea-11e7-9250-327c4584885f.png">

<img width="852" alt="screen shot 2017-06-29 at 4 43 01 pm" src="https://user-images.githubusercontent.com/25187819/27709521-692b02d4-5cea-11e7-93e3-84f9ad780c5a.png">

**Comment by manaswis** [comment]
Closed via #790
