### ISSUE TITLE
We Need To Do A Better Job Of Emphasizing Missions and Neighborhoods

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#73]
The mission screens should be oriented around neighborhoods and completing missions within neighbhorhoods. The 'mission complete' screens should show how much of a neighborhood the user has audited and encourage them to do more (e.g., only 1 mile left before you've completed audited\* Columbia Heights). We discussed this in our 1:1s--for example, we talked about lil animations that show how much the user has just audited during the most recent mission when the mission complete screen pops up.

I think we start users with smaller neighborhoods and then progress them to more 'difficult' larger neighborhoods.

We can use badges and other virtual incentives to track:
- number of miles walked
- number of labels of different types (with different tiers and badges for reaching, say, 100, 200, 500, etc.)
- number of neighborhoods completed
- other things?

*I realize the word 'audited' is not the most interesting/fun way of talking about the tasks in Project Sidewalk, so I'm open to alternatives.

**Comment by nguyenist** [comment]
Currently it says: 
`Audit the streets and and find all the accessibility attributes.`
Some ideas to consider: 
`Find and mark all of the accessibility attributes in this neighborhood.`
`Label the streets with accessibility attributes.`

**Comment by jonfroehlich** [comment]
This is related to #88 and #89. This is talking about the core user experience for using our tool. How we engage them and sustain interest in auditing via missions and feedback.

**Comment by kotarohara** [comment]
> I think we start users with smaller neighborhoods and then progress them to more 'difficult' larger neighborhoods.

This is a different issue. I'm not sure if we'll want to implement this feature. Let's defer it to later and decide once we launch.

**Comment by jonfroehlich** [comment]
This is also related to the leaderboards discussion: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1315. I could imagine that many badges also could translate to leaderboards (e.g., top 'auditor' in neighborhood X, most walked, etc.).

**Comment by misaugstad** [comment]
closing in favor of #2177 and #2178
