### ISSUE TITLE
Sign-in during missions changes progress

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#755]
Related to #734 and #285. Signing in during the middle of a mission adds to current mission progress after jumping to a new mission.

**Comment by maddalihanumateja** [comment]
From user testing we saw that only one user signed up for an account. This action started him on a new button and it wasn’t immediately clear to him if his progress was saved. He did feel negatively about this and explicitly stated he might have “dropped out” at this point. Every other user clicked on “No” to signing up so this wasn't a problem for them.

**Comment by adash12** [comment]
Fixed in #786

**Comment by manaswis** [comment]
Closed via PR #786
