### ISSUE TITLE
Mini footer visible under the onboarding intro/outro dialog box screen

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#758]
Mini footer visible under the onboarding intro/outro dialog box screen. See screenshots:

Footer visible under the dialog box:
![image](https://user-images.githubusercontent.com/2873216/27536628-079f5ca8-5a3e-11e7-9733-46e6a13a0592.png)

Closer look:
![image](https://user-images.githubusercontent.com/2873216/27536663-2c3d4cc8-5a3e-11e7-829e-607232f6d280.png)

When deployed on the server:
![image](https://user-images.githubusercontent.com/2873216/27536788-a3e8e368-5a3e-11e7-9dd5-0aeb4670b5e1.png)

**Comment by jonfroehlich** [comment]
What's the desired behavior here?

**Comment by manaswis** [comment]
It shouldn't be visible in this way. I think it should either be visible completely or hidden completely when the intro/outro dialog is shown.

**Comment by jonfroehlich** [comment]
Probably easiest to hide it then.

**Comment by manaswis** [comment]
Closed via #765
