### ISSUE TITLE
FAQ button link should open in a new tab

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#759]
The newly added FAQ Link on the navbar should open in a new tab.

![image](https://user-images.githubusercontent.com/2873216/27536870-0e2c8fea-5a3f-11e7-8ca7-715c43fbc5b0.png)

**Comment by jonfroehlich** [comment]
Not sure about this. Is the reasoning because otherwise you lose your place in the mission?

**Comment by manaswis** [comment]
Yes that's right. The users can go back and forth between the tabs to learn more.

**Comment by jonfroehlich** [comment]
Ok. I think that sites that open links in new tabs can be confusing for non-technical users but this is a better option than losing current position in mission.

**Comment by manaswis** [comment]
Closed via #762
