### ISSUE TITLE
Labels from tutorial can be retrieved by using undo and redo buttons repeatedly

### ISSUE THREAD

**Issue by sagec108** [ProjectSidewalk/SidewalkWebpage#769]
After completing the tutorial, I can retrieve labels placed in the tutorial by using undo and redo buttons in the mission. In the picture below, I had not placed any labels beside those in the tutorial.

![image](https://user-images.githubusercontent.com/20068009/27597323-059e5a24-5b30-11e7-944c-46fcc8ebfb36.png)

**Comment by jonfroehlich** [comment]
Clearly, the undo/redo stack needs to be cleared after finishing tutorial. Good catch Sage.

(Should we also clear the undo/redo after finishing a mission and after jumping--probably).

**Comment by sagec108** [comment]
Closed via PR #779
