### ISSUE TITLE
Panning with mouse inconsistently triggers "Let's take a step" pop-up

### ISSUE THREAD

**Issue by sagec108** [ProjectSidewalk/SidewalkWebpage#770]
Normally, panning around an intersection (after 360 degrees) without moving at the start of the mission will trigger the "Let's take a step" pop-up. This generally works as intended with keyboard panning.

Mouse drag panning does not always have the intended effect. Sometimes the pop-up will only show after rotating 720+ degrees.

**Comment by sagec108** [comment]
Update: This behavior is extremely inconsistent to the point that it is somewhat difficult to reproduce the bug on my computer. For the most part, mouse panning after a total of 330 degrees away from the initial direction triggers the pop-up.

**Comment by sagec108** [comment]
Update 2: This bug is caused when the user pans large angles at a time. Able to reproduce consistently. Fixes coming soon.

**Comment by manaswis** [comment]
Closed via #793
