### ISSUE TITLE
Logging in during a mission does not attribute labels pre-login to user

### ISSUE THREAD

**Issue by sbower213** [ProjectSidewalk/SidewalkWebpage#787]
Related to #786, any labels that a user makes before logging in during a mission are stored as if they were made by an anonymous user. This means that they do not show up on a user's dashboard, either. Ex:

In this mission, I made 12 labels, but only 4 of these were after I logged in.
![mission totals](https://user-images.githubusercontent.com/8651110/27703164-858ada50-5cd4-11e7-9625-b5bfac873056.png)

As a result, only 4 labels appeared on my dashboard for this route, and only parts of the route from after I logged in.
![mission saved data](https://user-images.githubusercontent.com/8651110/27703166-859832b8-5cd4-11e7-9ae9-4c381114da66.png)
![mission saved](https://user-images.githubusercontent.com/8651110/27703165-858fda32-5cd4-11e7-905a-ec7b48b42cc1.png)

**Comment by manaswis** [comment]
@sbower213 Just to clarify, this happens as a side-effect of the fix you made in #786? Or was it previously (before your fix) seen as well?

**Comment by sbower213** [comment]
@manaswis The issue happened implicitly before this, because logging in during a mission would cause the user to abandon their previous mission entirely. The difference is that now the user continues on the same mission and we can retain some of the later data of the same mission, as opposed to forcing them to a new mission.

**Comment by manaswis** [comment]
So once #783 is solved, it would solve this issue as well. Is that correct?

**Comment by sbower213** [comment]
Yep! Didn't see #783 when I made this issue, but I think they are close enough to be considered duplicates.

**Comment by manaswis** [comment]
Since #783 is what we need to do, can you update that issue thread with this issue content and close this one?

Thanks!
