### ISSUE TITLE
Logging in after starting anonymous may display irrelevant messages

### ISSUE THREAD

**Issue by sbower213** [ProjectSidewalk/SidewalkWebpage#788]
Related to #786, if a user starts a mission anonymously, then signs in right after starting, they will receive notices as if they were a first time user.

E.g. this alert popping up after logging in, despite not being a first time user:
![alert](https://user-images.githubusercontent.com/8651110/27703744-6da425e8-5cd6-11e7-89f1-3f16d7597bef.png)

While most people will either be already logged in when a mission starts or log in when prompted (later in the route), I feel that they should not see alerts that are irrelevant to them. However, this may be more work than is necessary for an uncommon case like this.

**Comment by misaugstad** [comment]
This is now a sub-problem of issue #1298
