### ISSUE TITLE
The Example Problems Pop-Up Dialog Design

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#79]
I really like that we now have this pop-up for every label when you click on the question mark:

![image](https://cloud.githubusercontent.com/assets/1621749/14624868/65852984-05ac-11e6-9763-2e24fb0ade5b.png)

However, I would prefer that: 

(1) we show our own rating UI with the answer rather than just text. I think this will help better reinforce the concept. That is, show this within the examples with the appropriate radiobutton selected:

![image](https://cloud.githubusercontent.com/assets/1621749/14624899/95dd7596-05ac-11e6-8bcc-c1754cdd25db.png)

To make this seem more like a screenshot and less interactive, you could make this into a sketch (either using Photoshop filter or literally just sketch it out).

(2) At the very least, I think we should show examples of Rating 1 (Passable) and Rating 5 (Not Passable) for every label. If we can make it fit, would be nice to show a middle value... so like Rating 1, 3, and 5 for every label.

**Comment by nguyenist** [comment]
![image](https://cloud.githubusercontent.com/assets/4484141/14730308/4f4a30b0-0813-11e6-9987-554bb813eb18.png)
Here's a first pass. Let me know if you'd like me to send you .pngs and if so, for which ratings, etc.

**Comment by kotarohara** [comment]
Done and up
