### ISSUE TITLE
Can Someone Quickly Make http://sidewalk.umiacs.umd.edu/api

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#797]
Can someone quickly make http://sidewalk.umiacs.umd.edu/api that simply loads http://sidewalk.umiacs.umd.edu/developer.

**Comment by manaswis** [comment]
I'll do it.


Best Regards,
Manaswi Saha
Ph.D. Student
Department of Computer Science
University of Maryland, College Park
http://cs.umd.edu/~manaswi/
Twitter - @manaswisaha <https://twitter.com/manaswisaha>
