### ISSUE TITLE
Filter out streets where Street View images are not available

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#8]
We need a way to filter out streets so they are not assigned to users.

**Comment by kotarohara** [comment]
I'm going to lower the priority of this as the issue is partially addressed on the client side: (i) if we drop a user on the street where we don't have Street View images, we drop them somewhere else; (ii) if a user hit the street where street without Street View while they are walking around, they can Jump to audit a different area.

I still want to filter out the streets where Street View images are not available a priori.

**Comment by danZzyy** [comment]
Is this something that will need to be done on the Scala side?

**Comment by kotarohara** [comment]
This is something that you can do offline, so you are welcome to use tools that you are familiar with. We can discuss more once you start.

**Comment by danZzyy** [comment]
I tired using Ghost.py for headless browsing but it always crashes after it has executed all the js functions I give it. Ghost is still in beta so I will now be investigating Spynner which is finished library. The good news is that the GSV javascript part works and is very straight forward.

**Comment by danZzyy** [comment]
Ghost did not work, Spynner's browser is crappy so now I am trying Selenium which has a Chrome webdriver. Hopefully this will behave similar to calling functions manually in console. Also I take back what I said about GSV js being straight forward since I discovered it uses an async function which makes trying to coordinate timing tricky. If that doesn't work maybe look at node.js? ¯\_(ツ)_/¯

**Comment by jonfroehlich** [comment]
Why do you need to coordinate timing? This doesn't need to be real-time. Just pass a callback function and wait for desired result, then move on to next GSV node on street. Right?

**Comment by kotarohara** [comment]
Yes. The things that @danZzyy is currently working on are: (i) learn how to use callback functions/polling to deal with asynchronous calls (that's what he meant by "coordinate timing," I think), (ii) understand that we have to run a JavaScript code on a process that runs browser to retrieve the GSV data we want (because Google does not provide APIs for other run-time environments), and (iii) store the output that we got on the browser process to a .txt or .csv file (which can be a bit of a problem as a browser process has limited access to system calls such as saving data to a file).

**Comment by jonfroehlich** [comment]
Thanks Kotaro. Node.js probably solves the issue of saving data to a file,
no?

On Fri, Jun 10, 2016 at 4:17 PM, Kotaro Hara <notifications@github.com>
wrote:

> Yes. The things that @danZzyy <https://github.com/danZzyy> is currently
> working on are: (i) learn how to use callback functions/polling to deal
> with asynchronous calls (that's what he meant by "coordinate timing," I
> think), (ii) understand that we have to run a JavaScript code on a process
> that runs browser to retrieve the GSV data we want (because Google does not
> provide APIs for other run-time environments), and (iii) store the output
> that we got on the browser process to a .txt or .csv file (which can be a
> bit of a problem as a browser process has limited access to system calls
> such as saving data to a file).
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ProjectSidewalk/SidewalkWebpage/issues/8#issuecomment-225284780>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABi-9TsJYJW_YtLvGEl_gZoL1SGeOY82ks5qKcZIgaJpZM4Hh997>
> .
>



-- 
Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich <https://twitter.com/jonfroehlich> - Twitter

**Comment by danZzyy** [comment]
we are using Phantom.js and yes it makes writing to a file simple.

**Comment by kotarohara** [comment]
Yes, Node.js can save file to local storage (or the code for the parent process can be written in anything). But since it cannot use the remote library like Google's API directly, so it still needs to create a browser process.

**Comment by danZzyy** [comment]
Finally made a working browser based script that uploads a file of street data and checks the availability. The result is loaded into a csv file and downloaded. The street data pulled from the database is split into 30 files of 1000 rows. These were uploaded in groups of 3 and  checked for availability  (more than 3 files caused the browser's developer tools to disconnect) and labeled AVAILABLE, UNAVAILABLE, or ERROR if there was an API error.  The csv files were concatenated into one file which I sent Kotaro.

**Comment by danZzyy** [comment]
This task will be finished with a map visualization of the coordinates and their street view availability.

**Comment by danZzyy** [comment]
![svavailable](https://cloud.githubusercontent.com/assets/13355765/16134436/21dc2878-33eb-11e6-9603-9b90a0ec787c.PNG)
The visualization takes a really long time to render 30k custom markers. I am not even sure it had completed by this point but it looks good and the availability/unavailability makes sense.

**Comment by jonfroehlich** [comment]
This looks great. Did the render eventually finish? If so, can you repost a
screenshot?

It looks like there are some roads without green or red dots, why would
this be?

On Thu, Jun 16, 2016 at 5:54 PM, Dan Zadorozhnyy <notifications@github.com>
wrote:

> [image: svavailable]
> <https://cloud.githubusercontent.com/assets/13355765/16134436/21dc2878-33eb-11e6-9603-9b90a0ec787c.PNG>
> The visualization takes a really long time to render 30k custom markers. I
> am not even sure it had completed by this point but it looks good and the
> availability/unavailability makes sense.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ProjectSidewalk/SidewalkWebpage/issues/8#issuecomment-226625172>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABi-9TUdKayI9MbGqGtJZQ9Dq53Xo89Eks5qMcYQgaJpZM4Hh997>
> .
>



-- 
Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich <https://twitter.com/jonfroehlich> - Twitter

**Comment by danZzyy** [comment]
I checked and that is what complete rendering looks like. The base map doesn't load until everything has been plotted.

**Comment by jonfroehlich** [comment]
Great. Thanks.

On Sat, Jun 18, 2016 at 12:32 PM, Dan Zadorozhnyy <notifications@github.com>
wrote:

> I checked and that is what complete rendering looks like. The base map
> doesn't load until everything has been plotted.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ProjectSidewalk/SidewalkWebpage/issues/8#issuecomment-226951611>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABi-9WxNHZg9zJE7_uEyH1MXCSaMwFpNks5qNB2BgaJpZM4Hh997>
> .
>



-- 
Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich <https://twitter.com/jonfroehlich> - Twitter

**Comment by danZzyy** [comment]
There was a bit of data that I missed since I was saving data at blocks of exactly 1000. There was a remainder of 262 (times 2 for both endpoints). I added those into the list and sent Kotaro the new html file and csv list.

**Comment by kotarohara** [comment]
Done.
