### ISSUE TITLE
Mission Screen: 'Audit XXXXft of Neighborhood" Should Be 'in' rather than 'of'

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#801]
Mission Screen: 'Audit XXXXft of Neighborhood" Should Be 'in' rather than 'of'

Not sure why we didn't catch this before.

**Comment by r-holland** [comment]
This look good? You want it changed both in mission title and in the instruction text, correct?

![image](https://user-images.githubusercontent.com/19720010/27795906-f07588b6-5fd5-11e7-84fe-458d9deb0b6c.png)

**Comment by jonfroehlich** [comment]
Yes. Good.

**Comment by manaswis** [comment]
Closed via PR #803
