### ISSUE TITLE
Differentiate between different neighborhoods with same name

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#806]
There are a few sets of neighborhoods that have the same name, which could be confusing to users. You can see an example on the choropleth:
![bellevue1](https://user-images.githubusercontent.com/6518824/27799059-bc2ab160-5fe1-11e7-8dfd-cffa8e6ad569.png)
![bellevue2](https://user-images.githubusercontent.com/6518824/27799058-bc18f8a8-5fe1-11e7-8523-56474574b626.png)

And this also causes an issue in the neighborhood completion percentage graph on the admin interface, since neighborhoods with the same name are grouped together:
![neighborhood-completion-issue](https://user-images.githubusercontent.com/6518824/27799071-cbedf904-5fe1-11e7-89e9-a7bdf81dd663.png)

This is also seen in the audit interface when it says which neighborhood you are auditing. 

This could be fixed by giving neighorhoods names like "Bellevue North", etc. This doesn't necessarily need to be changed in the database since they do still have unique numeric identifiers, but should at least be changed on the front end.

And my main concern right now is that the graph that is shown above is not entirely accurate, since it is missing entries.

**Comment by misaugstad** [comment]
Yeah I can deal with this. Should this be changed in the database or just on the viz side?

**Comment by jonfroehlich** [comment]
What are the implications for the choice here?

**Comment by misaugstad** [comment]
1. likelihood of causing problems elsewhere
2. ease of implementation

For 1, anything where we actually change the database does have some possibility that the thing we changed may have been used in a way that we didn't expect elsewhere, so the change could cause problems there. Changing on the viz side means that all changes are local to that area of the code and we don't have to worry about breaking anything else. After thinking a bit more about this, I think the probability that the neighborhood names are being used elsewhere in a way that would cause an issue is *very* low.

For 2, I originally thought that implementing on the viz side would be easier. However, thinking about the number of places where we would want to make the the change has brought me to my senses, and I think that a change to the database should happen. I have already done it with another table so I have similar code that I can work off of and this shouldn't be too difficult.

If you couldn't tell, I am now thinking that I should update the actual table :)

**Comment by jonfroehlich** [comment]
Sure. Do it.

**Comment by misaugstad** [comment]
Done! Here is what it looks like on the choropleth:

![brn](https://user-images.githubusercontent.com/6518824/27835366-cb393da8-60a8-11e7-8fc3-7b3738afa21a.png)
![brc](https://user-images.githubusercontent.com/6518824/27835365-cb38c440-60a8-11e7-9db0-e435b97c0e0c.png)
![brs](https://user-images.githubusercontent.com/6518824/27835367-cb3956a8-60a8-11e7-8afb-7298f07545c2.png)

Whereas they all said "Benning Ridge" beforehand.

Notes:
I decided to put the cardinal directions in parentheses to make it clear that these are our personal annotations, not the *actual* names of the neighborhoods. Especially since there is a neighborhood names "Hill East".

With each set of duplicates, I kept one of them with the original name, as you can see above. The criteria that I used to pick which one got the original name were as follows, in order of importance:
- for neighborhoods split into 2 regions:
  1.  The region that was noticeably larger (geographically) than the other got to keep the original name.
  2. If the regions were approximately the same size, the "center" region became the one that contained the neighborhood name on GMaps :) So whichever one seemed like it might have contained the "center" of that neighborhood. Though at this point, it was often just a coin flip.
- for neighborhoods split into 3+ regions:
  1. The region that was most centrally located (you can see in the image above, that one is clearly in the center).
  2. Particularly for neighborhoods split up into 5+ regions, the "center" was chosen to make the assignment of cardinal directions to the remaining regions easiest or most clear.


As expected, there are many more regions present in the neighborhood completion bar chart:
![all-the-neighborhoods](https://user-images.githubusercontent.com/6518824/27837176-d321a20a-60b0-11e7-8e1e-402006805ee8.png)


And the new names show up when beginning an audit and during auditing, etc:
![audit-north](https://user-images.githubusercontent.com/6518824/27836926-9cb2ac60-60af-11e7-8ca9-041f4c8be93e.png)
![audit-north2](https://user-images.githubusercontent.com/6518824/27836927-9cb5d4c6-60af-11e7-956e-175701c9ea67.png)
![mission-complete-douglass-north](https://user-images.githubusercontent.com/6518824/27836971-d358d7da-60af-11e7-916d-dcc153109905.png)

How does it look? Any changes you would like to see @jonfroehlich ?

**Comment by manaswis** [comment]
Nice post @misaugstad! :)

**Comment by manaswis** [comment]
Closed via #833

**Comment by manaswis** [comment]
Check out this neighborhood name :P

![image](https://user-images.githubusercontent.com/2873216/27938884-10e41674-628f-11e7-895b-9771bab65e34.png)

**Comment by misaugstad** [comment]
Hahahhh yeah I think that one is my favorite :stuck_out_tongue_closed_eyes:

**Comment by manaswis** [comment]
Its not even northeast..but "near" northeast and then south -- nesting of directions
