### ISSUE TITLE
I Just Logged In and Got Clapping and Cheering

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#81]
I literally just logged in on my home computer (had not done any audit work on this computer today) and the moment after I logged in, I got the following screen with the 'clapping and cheers' sound effect.

![image](https://cloud.githubusercontent.com/assets/1621749/14660840/b5f88206-0676-11e6-9060-feef2579b813.png)

**Comment by kotarohara** [comment]
Hmmm, weird you are seeing this mission... Will look into it.

**Comment by jonfroehlich** [comment]
This is probably related to #82.

**Comment by kotarohara** [comment]
This should not happen to new users. I'm closing this now.
