### ISSUE TITLE
Should We Make a Project Sidewalk Group on Facebook?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#811]
Advantages:
- Could have a clear 'call for action' and explanation of the website
- Users could post questions and receive answers from us (or others)
- Start to build community

Downsides:
- Another thing to manage
- Do we really need this?

**Comment by manaswis** [comment]
There is a recent issue #881 on the same topic where the discussion is on. Closing this one.
