### ISSUE TITLE
Just Logged In and Mission Bar Shows 100%

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#82]
I have not done any work yet--I haven't even taken a step and the mission bar shows 100%:

![image](https://cloud.githubusercontent.com/assets/1621749/14660848/cc4f2898-0676-11e6-90c5-39e7c2b9cc6b.png)

**Comment by kotarohara** [comment]
I don't think this is happening anymore. I'm closing it for now.
