### ISSUE TITLE
Update pop-ups on maps for "advanced" neighborhoods

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#820]
For those neighborhoods that we have identified as having weird/difficult/impossible routes, detailed in #718, we should update the popup messages on the choropleth and user dashboard map to tell users that these neighborhoods should only be done by experienced users, as discussed in #804.

We need to decide on what the new message should be. I'll throw out some ideas to get the convo started. Below the current text, which is...
\<neighborhood\>: X% Complete
Only X miles left!
Click here to help finish this neighborhood!

How about something like...
__Careful!__ This neighborhood is only for experienced users!
__Careful!__ This neighborhood is recommended for experienced users only!
__Careful!__ \<neighborhood\> recommended for experienced users only!
__Careful!__ not recommended for new users!
__Careful!__ \<neighborhood\> not recommended for new users!
Proceed with caution, recommended for experienced users only!
Proceed with caution, not recommended for new users!

**Comment by sbower213** [comment]
I personally like "Careful! This neighborhood is not recommended for new users." or something like "Caution: This neighborhood is recommended for experienced users only."

Here's a few screenshots to show potential differences in spacing. Not sure of the best balance between conciseness and clutter.
![image](https://user-images.githubusercontent.com/8651110/27871123-bdea9c80-6172-11e7-8c55-fac695c24357.png)
![image](https://user-images.githubusercontent.com/8651110/27871141-cf50a7e4-6172-11e7-8d37-6170b42cea8f.png)
![image](https://user-images.githubusercontent.com/8651110/27871171-e07e3888-6172-11e7-98a8-3a296fbe2705.png)

**Comment by misaugstad** [comment]
I kind of like the last option, since it is most obvious. Especially since it will only be present a few of the popups, I am more worried about it standing out than taking too much space.

**Comment by sbower213** [comment]
I have labelled Monumental Core, Navy Yard, Southwest Employment Area, and Southwest/Waterfront with the last version of the alert. Any other neighborhoods I should add?

**Comment by jonfroehlich** [comment]
> Any other neighborhoods I should add?

This can only be determined via testing. @r-holland: did you test any other neighborhoods for problems? My guess is that the downtown areas (with tunnels) are going to be most problematic.

**Comment by misaugstad** [comment]
That is all I have come upon so far. As Jon said, during stress testing, and we will be monitoring user feedback when we launch. As users report on problems in certain neighborhoods, we can thoroughly test those neighborhoods and add them to the list at that point.

**Comment by sbower213** [comment]
Ok. I will submit these as a PR for now, we can add more neighborhoods as need be after receiving more feedback/doing more testing.

**Comment by manaswis** [comment]
Closed via PR #830
