### ISSUE TITLE
Auto assign inexperienced users to easier neighborhoods

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#823]
For those neighborhoods that we have identified as having weird/difficult/impossible routes, detailed in #718, we should not auto-assign new/inexperienced users to these neighborhoods, as mentioned in #804. My big questions:
1. Do we think that stuff like this is going to be common in the future, i.e., should we use the region_properties table, maybe assigning a "difficulty" property to neighborhoods? Or should we just keep it as a temp/ad hoc thing?
2. How do we define an "experienced" user? My first thought is that they have audited at least ~2 miles?

**Comment by jonfroehlich** [comment]
1. We could. Not sure. We don't have a principled way of deciding/ranking difficulty, which seems like a prerequisite.
2. Again, need to come up with a strong rationale. Could be ~2 miles--but how many registered users (not us) would this include currently with our dataset?

**Comment by misaugstad** [comment]
For 2., a very rough estimate... at least 30, but no more than 100, which gives an idea of the order of magnitude. And that is out of the ~300 registered users.

**Comment by jonfroehlich** [comment]
OK, seems reasonable to me.

**Comment by manaswis** [comment]
Closed via #832
