### ISSUE TITLE
Tracking first mission

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#826]
In #700, we were discussing about tracking first mission. I'd like to continue the discussion and finalize before relaunch - whether we want to do it for the relaunch. Below is the quote from the past issue thread (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/700#issuecomment-309929905):

> I can see that an experienced anonymous user would find seeing the same pop-ups again annoying

>Now, to address the larger issue. I think we should store if the first mission has been completed by the user just like how we track onboarding. Then we can only show those messages if they haven't completed the first mission. Currently, there is no way for us to determine if the user is a first time user or are they visiting again.

Currently, the browser only keeps track of whether a user has completed onboarding. If they have, then the onboarding screen isn't shown to the anonymous user. However, each time a user loads the audit page, it is considered as the first mission for the anonymous user. Now that we have changed the first mission dialog to be:

![image](https://user-images.githubusercontent.com/19720010/27614234-5463ab12-5b6e-11e7-9165-e9fbee834ef6.png)

IMO, we should track the first mission. Else, each time an anonymous user revisits the page, it will load the first mission with its associated mission dialog box (the above screenshot) and the first mission pop-ups ("Let's get started", "Check both sides" etc).

**Comment by jonfroehlich** [comment]
I agree with you @manaswis. Seems like a "no brainer". What's the downside?

**Comment by manaswis** [comment]
Other than added dev time (which I believe shouldn't be too much), I don't see any downside.

**Comment by jonfroehlich** [comment]
OK!

**Comment by manaswis** [comment]
Closed via #834
