### ISSUE TITLE
Choosing Neighborhood Pop-Up Goes Off Screen Sometimes (For Large Neighborhoods)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#827]
This only happens for awkwardly shaped and large neighborhoods (both on user dashboard and admin dashboard).

For example: 
![image](https://user-images.githubusercontent.com/1621749/27874027-15a80544-617c-11e7-8739-5016893c9c6a.png)

Then if I re-click on neighborhood, pop-up centers in view:
![image](https://user-images.githubusercontent.com/1621749/27874044-28b87dbc-617c-11e7-924d-be8fcbff93e8.png)

See: https://youtu.be/pYgiIBV4S9Y

**Comment by misaugstad** [comment]
This has been fixed with later iterations of the maps!
