### ISSUE TITLE
Add simple GUI to admin dashboard for updating roles

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#837]
This should be pretty fast to make, doesn't need to be too pretty, but it would make it a lot easier to update the roles of users if we had a GUI for it instead of having to write queries.

Benefits:
- We don't have an easy way of updating roles on the production server
- Updating roles will be necessary for the entire lifetime of the tool, since more students will join the team over time and will need to be given the researcher role, and the admin role will need to be given/taken to project leads over time, so I think it deserves a GUI :)
- This may also make testing certain features related to roles on local systems easier

Notes:
- If we add in a GUI for this, I think that not allowing people to change Jon's role should be hard-coded in, either just by checking for his username in this tool, or by introducing a new role like "Owner".
- The GUI should also include a list of all users that have the Administrator or Researcher roles, so that an admin can take a glance at it, and know if someone is missing that should be included (also gives confidence that the update actually took place when it refreshes).

**Comment by jonfroehlich** [comment]
Sounds good to me.

Yes for new role re: Owner for me.

Who should do this. Note: I don't think you should. :) Perhaps @sbower213?

**Comment by manaswis** [comment]
Closed via #951
