### ISSUE TITLE
Directions are different than what Google Street View will let you do. 

### ISSUE THREAD

**Issue by chishankar** [ProjectSidewalk/SidewalkWebpage#838]
While I was testing some code. I came into a small problem, I am not sure if it has been resolved or not, but here it is.

While I was gong along a mission, it told me to go straight onto this road, however, google street view would not let me go. Below I have included a console log, a youtube video, and a screenshot to add more detail. 

YouTube video:
 https://youtu.be/C8W_jZM-f0I

ScreenShot:
<img width="1099" alt="screen shot 2017-07-07 at 12 01 59 pm" src="https://user-images.githubusercontent.com/25187819/27966418-29eb71ca-630d-11e7-87b9-9eb8b89987c0.png">

Console Log:
<img width="1048" alt="screen shot 2017-07-07 at 12 01 51 pm" src="https://user-images.githubusercontent.com/25187819/27966433-38b75228-630d-11e7-9e1d-aae140f8fcbc.png">

**Comment by jonfroehlich** [comment]
Could you double click to move in the routes direction?

(I didn't look at your video).

**Comment by manaswis** [comment]
@chishankar Could you try this in Google Street View? See the lat lng using `svl.map.getPosition()` in the console. Then use the latlng to jump to that location in the actual Google Street View. See if you can walk on that street there.

**Comment by jonfroehlich** [comment]
Note that this isn't necessarily a unique problem. I've certainly seen this before but typically double clicking in the right direction (on the road) works. And in cases where it doesn't, I typically use the feedback button to provide feedback to us about the route and then hit the Jump button, which has an option to indicate that you cannot go where we want you to go.

Also, my guess is that you could wade through either open (or closed) issues and find similar problems noted... 

Although the console does provide an interesting error that I don't think I've seen before "ERR_BLOCKED_BY_CLIENT"

**Comment by sbower213** [comment]
ERR_BLOCKED_BY_CLIENT occurs when an ad-blocker such as AdBlock Plus or uBlock prevents an element from loading. If I enable uBlock on PS i get similar errors thrown:

![image](https://user-images.githubusercontent.com/8651110/28023371-c319f2ea-655b-11e7-8183-762f03721805.png)

**Comment by misaugstad** [comment]
Right, this is something where you can double-click to move forward. and @sbower213 pointed out that the errors in the console have to do with an ad blocker. So I don't think there is an issue here to fix :)
