### ISSUE TITLE
Search Bar for Choropleth and Street?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#842]
From @r-holland and @chishankar usability tests, one user wanted a search bar for the choropleth map to more easily find a specific neighborhood to audit.

S/he also suggested wanting to search for streets. This latter suggestion is more relevant to AccessScore imo and is something we want to do.

**Comment by manaswis** [comment]
Searching for a neighborhood to select the neighborhood is part of the Summer projects list we have for PS. I think we should definitely have that.

**Comment by jonfroehlich** [comment]
Yah, as I was writing this Issue up--I tried to imagine a use case where this would be important. I could see it as valuable to AccessScore but not sure how it benefits a user for the Choropleth--because, I would imagine, that if they are searching for a neighborhood via a name, it's likely that they know the location and thus browsing (via mouse) would be faster.

**Comment by misaugstad** [comment]
The important part of this is covered by #1702 I believe.

**Comment by jonfroehlich** [comment]
This is still an important feature for our interactive visualizations so tagging @johnsonkuang and @manaswis so that they see this.
