### ISSUE TITLE
Red line in both directions on mini map

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#848]
Testing on the dev server, after finishing the tutorial as an anonymous user, I was placed at an intersection where there were red lines in both directions on the mini map. However, one direction was clearly the way to go, as following it caused the line to turn green, while going the other direction did nothing. (In the images, you can see popups from the tutorial, this may be a separate problem, and is being addressed in #847 )

![sidewalk-red-in-both-directions](https://user-images.githubusercontent.com/6518824/27990239-2a002e46-641e-11e7-840e-b11fd469a919.PNG)
![sidewalk-already-labeled-ramp](https://user-images.githubusercontent.com/6518824/27990240-327ac6ee-641e-11e7-8727-2bbb4411dbe0.PNG)
![sidewalk-phantom-ramp](https://user-images.githubusercontent.com/6518824/27990242-3f516760-641e-11e7-86fb-8402b87c480a.PNG)

**Comment by manaswis** [comment]
No reports of this issue occurring after the fix made in #850. Closing it for now. Can be reopened if the issue occurs again.
