### ISSUE TITLE
Green Icon Collision In Achievement Sidebar

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#85]
![image](https://cloud.githubusercontent.com/assets/1621749/14661904/820d909a-067f-11e6-8a8e-551fdc8ea76e.png)

**Comment by kotarohara** [comment]
Only if all the users provided so much data!

**Comment by jonfroehlich** [comment]
I don't think this is an enhancement. It's definitely a UI bug.

**Comment by jonfroehlich** [comment]
Kotaro is going to fix this so that all the 'balls visualizations' work in a fixed width. To do this, we will need larger balls to represent 20 and maybe 50. We should probably have labels on these balls to indicate 10x, 20x, and 50x--maybe like the notification labels in Apple iPhone or maybe within the ball itself.

**Comment by kotarohara** [comment]
@danZzyy pushed a fix to this. I'm closing the issue.

**Comment by jonfroehlich** [comment]
Can I see a screenshot?
