### ISSUE TITLE
Tutorial: when getting severity wrong, they should be told why

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#853]
In the tutorial, if a user gets the severity rating wrong for a label, the explanation of why the label should have been at that severity is not given when we tell them that they were wrong...

![sidewalk-missing-ramp1](https://user-images.githubusercontent.com/6518824/27999982-9cc64ca8-64f0-11e7-9bf1-165533d27c5d.PNG)
![sidewalk-missing-ramp2](https://user-images.githubusercontent.com/6518824/27999981-9cc611f2-64f0-11e7-803b-aac30ac13a3f.PNG)

In a user test, they didn't really read the text where it says that it is only a 3 since there is a curb ramp next to it and gave it a 5. Then it just says it has severity '3' and they were really confused, since a the curb ramp is missing, how could it be a 3?

I think the text should be modified
Hmmm, this is a slightly sever problem since it is next to an existing curb ramp. ...

**Comment by r-holland** [comment]
@misaugstad is this the wording you are looking for?

![image](https://user-images.githubusercontent.com/19720010/28085888-12cfdae4-664b-11e7-9812-1360c76024df.png)

In addition, if we make this modification for the missing curb ramp, should the text also be changed for the other labels in the tutorial (for consistency and to better explain severity ratings)?

![image](https://user-images.githubusercontent.com/19720010/28085822-dc1edb62-664a-11e7-9042-5c13c54862e4.png)

**Comment by misaugstad** [comment]
For reference, here is the current text to instruct for rating severity and when getting it wrong:
![sidewalk-tutorial-cb1](https://user-images.githubusercontent.com/6518824/28096906-5c38f4e8-667a-11e7-9bb7-6c5b5a3d7b84.png)
![sidewalk-tutorial-cb2](https://user-images.githubusercontent.com/6518824/28096907-5c3d83f0-667a-11e7-8d8c-e3c90745a6bb.png)

And I would update the text to something like "Hmm, it looks like this curb ramp would be easy for a wheelchair user to use, so __let's rate it as 1, passable__"

Thanks for taking this on @r-holland

**Comment by r-holland** [comment]
Potential options for correcting a user who fails to label a curb ramp as 1 in the tutorial:

1. "Hmm, it looks like this curb ramp would be easy for a wheelchair operator to use, so **let's rate it as 1, passable.**"
2. "Hmm, this curb ramp is clean and aligned with the crosswalk, so **let's rate it as a 1, passable.**"
3. "Hmm, this curb ramp looks clear of any issues, so **let's rate it as a 1, passable.**"
4. "Uh oh, you should **rate this curb ramp as 1, passable.** The ramp is clean and wide enough for a wheelchair to pass."
5. "Uh oh, you should **rate this curb ramp as 1, passable.** The ramp is unblocked, uncluttered, and undamaged."

It's late. I'll brainstorm some more text tomorrow.

**Comment by sarahsmo** [comment]
Before: 
![image](https://user-images.githubusercontent.com/31173144/30410018-8a85e674-98d6-11e7-91d2-0370bab23b4e.png)

After:
![image](https://user-images.githubusercontent.com/31173144/30410012-7fd2e3c6-98d6-11e7-8d85-78b26ac1b05a.png)

**Comment by misaugstad** [comment]
Update: we are going to wait on #1103 before deciding on the final text changes here.

**Comment by misaugstad** [comment]
Below I show each label where we rate severity in the tutorial, followed by the initial text that shows on the screen (and my suggestions for how to change it), and finally the text that is shown when you give the wrong severity rating (and my suggested changes).

@aileenzeng and possibly @jonfroehlich could you take a look at these suggested changes and let me know what you think? 

First label (curb ramp severity 2)
![tutorial-label1](https://user-images.githubusercontent.com/6518824/52167347-a0899380-26ce-11e9-82ce-59431b8e59be.png)

First label (curb ramp severity 2) initial text:
* current text: Now you can rate the quality of the curb ramp where 1 is passable and 5 is not passable for a wheelchair user. **Let's rate it as 2, somewhat passable.**
* suggested text: Now you can rate the quality of the curb ramp where 1 is passable and 5 is not passable for a wheelchair user. Because it points into traffic a bit **let's rate it as 2, somewhat passable.**

First label (curb ramp severity 2) correction text:
* current text: Uh-oh, you should rate this curb ramp as 2, somewhat passable. **Lets click "2" to set its quality.**
* suggested text: Uh-oh, you should rate this curb ramp as 2, somewhat passable. It is a high quality curb ramp but points into traffic a bit. **Let's click "2" to set its quality.**

Second label (curb ramp severity 2)
![tutorial-label2](https://user-images.githubusercontent.com/6518824/52167355-b39c6380-26ce-11e9-857e-1ba63a466251.png)

Second label (curb ramp severity 2) initial text:
* current text: Good, now **rate the quality** of the curb ramp.
* suggested text: no change

Second label (curb ramp severity 2) correction text:
* current text: Uh-oh, you should rate this curb ramp as 2, somewhat passable. **Lets click "2" to set its quality.**
* suggested text: Uh-oh, you should rate this curb ramp as 2, somewhat passable. It is a high quality curb ramp but it has no landing space at the top of the ramp for making turns. **Let's click "2" to set its quality.**

Third label (missing curb ramp severity 3)
![tutorial-label3](https://user-images.githubusercontent.com/6518824/52167357-bac37180-26ce-11e9-9f6e-7df70a107d46.png)

Third label (missing curb ramp severity 3) initial text:
* current text: Since this missing curb ramp is next to an existing curb ramp, this accessibility problem is less severe. So, let's **rate it as a 3**. When you rate accessibility, we just ask that you use **your best judgement!**
* suggested text: The text looks good to me, I just want to bold the word "let's" for consistency across instructions. Also I want to bold the word "use" before the 2nd bolded part, and get rid of the comma after the word "So".

Third label (missing curb ramp severity 3) correction text:
* current text: Hmm, this is a slightly severe problem. **Lets click "3" to change the severity of the missing curb ramp.**
* suggested text: Hmm, since this missing curb ramp is next to an existing curb ramp, this accessibility problem is less severe. **Let's click "3" to change the severity of the missing curb ramp.**

Fourth label (curb ramp severity 1)
![tutorial-label4](https://user-images.githubusercontent.com/6518824/52167362-c878f700-26ce-11e9-95fd-462a5f9db88b.png)

Fourth label (curb ramp severity 1) initial text:
* current text: Now **rate the curb ramp's quality.** Use your best judgement. You can also write in notes in the **Description Box**.
* suggested text: Now **rate the curb ramp's quality.** Use your best judgement. You can also write notes in the **Description Box**.

Fourth label (curb ramp severity 1) correction text:
* current text: Hmm, you should rate this curb ramp as 1, passable. **Lets click "1" to change its rating.**
* suggested text: Hmm, you should rate this curb ramp as 1, passable. This curb ramp is wide enough, has a friction strip, and doesn't point into traffic. **Let's click "1" to change its rating.**

Fifth label (curb ramp severity 1)
![tutorial-label5](https://user-images.githubusercontent.com/6518824/52167364-ce6ed800-26ce-11e9-9d2a-623e5155742d.png)

Fifth label (curb ramp severity 1) initial text:
* current text: Let's **rate the quality** of the curb ramp.
* suggested text: **Let's rate the quality** of the curb ramp.

Fifth label (curb ramp severity 1) correction text: this has the same text as for the fourth label, and I suggest the same changes

Sixth label
![tutorial-label6](https://user-images.githubusercontent.com/6518824/52167369-d75fa980-26ce-11e9-901e-af5ec6aae0c4.png)

Sixth label: all text is the same as the fifth label, and I suggest the same changes.

**Comment by jonfroehlich** [comment]
If we are making changes to tutorial maybe we also update animations and add in tagging? Thoughts?

**Comment by misaugstad** [comment]
yeah those all need to be done in the near future. I'm just breaking off a piece of it right now by doing the wording :blush: 

I'm working on the wording b/c I think it is best that either @aileenzeng or myself do it b/c we are most familiar with the labeling guide. I'm hoping other undergrads will work on the animations on the tagging.

**Comment by jonfroehlich** [comment]
Sounds good!

**Comment by misaugstad** [comment]
@aileenzeng or @jonfroehlich could you read through the suggested changes to make sure we have A+ text in the tutorial? :blush:

**Comment by jonfroehlich** [comment]
Just read them over, I think they look good. We did add length, though... and I'm worried that crowd workers already don't really read. :-/

**Comment by misaugstad** [comment]
Yeah that is the one concern :/

**Comment by aileenzeng** [comment]
The descriptions look good to me too!

**Comment by misaugstad** [comment]
closing via #1453
