### ISSUE TITLE
Front Page Stat Beelding over in Safari

### ISSUE THREAD

**Issue by chishankar** [ProjectSidewalk/SidewalkWebpage#859]
<img width="1389" alt="screen shot 2017-07-11 at 10 56 11 am" src="https://user-images.githubusercontent.com/25187819/28074852-b0142040-6627-11e7-89e4-f497ba4280d4.png">

The numbers still bleed over into the next section on the front page:

Browser: Safari

**Comment by chishankar** [comment]
@misaugstad @jonfroehlich

**Comment by misaugstad** [comment]
Duplicate of #727
