### ISSUE TITLE
Admin Interface: Add statistic for clicking Start Mapping vs selecting a region from the choropleth

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#860]
Add a stat showing the number of 'Start Mapping' clicks vs Choropleth Clicks. This will tell us how users are interacting with the landing page to go to the audit page.

This could be a section on the admin page showing total number of visits to the Audit page, and then the two values: #clicks on Start Mapping button and #clicks on choropleth to go to the audit page.

@misaugstad Other ideas welcome.

**Comment by misaugstad** [comment]
closed via #873
