### ISSUE TITLE
+/- keys zoom, but can break panning

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#864]
I tried to enter an "-" in a comment for a label, and it zoomed me out a bit, and my labels disappeared from SV and I could not pan. After hitting +/- and z/shift-z a few times, things went back to normal. There is a pic below where you can see console errors.

![sidewalk-pm1](https://user-images.githubusercontent.com/6518824/28094242-87b2ec3e-6669-11e7-807f-618457215a6d.png)

We only want to allow z and shift-z to zoom, right? If we want to allow +/-, then we need to disable it in text boxes. The +/- is also not restricted to our 3 specific zoom levels, it can end up between those zoom levels, which is may be what caused some of the errors.

**Comment by maddalihanumateja** [comment]
Related to #678 . This is probably a duplicate of the issue or they can be merged

**Comment by misaugstad** [comment]
Ahh, thank you. Searching for + and - doesn't work, I see. Should have searched for zoom, oops! :)
