### ISSUE TITLE
Need a "Returning you to this mission" message when returning user to in-progress mission

### ISSUE THREAD

**Issue by adevdash** [ProjectSidewalk/SidewalkWebpage#865]
For example, when a user retakes the tutorial they're returned to their current mission progress as of PR #824 . They're shown the mission beginning dialog when they're in the middle of a mission. This should be changed to a different dialog along the lines of "We're returning you to this mission..."

**Comment by misaugstad** [comment]
@lstrobel before you submit a PR, be sure to show us some mock-ups and suggested text so we can all iterate on it.

**Comment by lstrobel** [comment]
@misaugstad @jonfroehlich 
I threw together two quick mockups for what this modal could look like:

**This one is just a flavor on the existing mission modal, it would just replace the text**
![mockup 1](https://user-images.githubusercontent.com/12887715/50186251-1d071500-02cf-11e9-8af8-f2f53fb26ff5.png)

**This one is more simplified:**
![mockup 2](https://user-images.githubusercontent.com/12887715/50186421-930b7c00-02cf-11e9-9ccb-4d82c4a68271.png)

Some questions:
- If we iterate off of the first one, would we want to display Turkers' reward as well, like on the current mission modal?
- Should we change the text of the "OK" button?

**Comment by jonfroehlich** [comment]
Thanks Lukas!

Maybe OK button could be “Resume Mission”?

Also, can you make a mock that shows a map of what they’ve accomplished in current neighborhood with stats plus the current mission route and where they are in that mission (with possibly stats related to that mission too). This would be a more substantial change but I want to see what you come up with. Think mission screens in video games—perhaps look at a few for inspiration.

**Comment by lstrobel** [comment]
@jonfroehlich 

I developed two more mockups based off of your feedback:

**This one takes the information from the sidebar and presents it to you**
![complex mockup 1](https://user-images.githubusercontent.com/12887715/50188329-2051cf00-02d6-11e9-83ca-3c55c9f8c9e7.png)

**This one is a little more simple, which could be both a good or bad thing**
![complex mockup 2](https://user-images.githubusercontent.com/12887715/50188356-3cee0700-02d6-11e9-8a42-d1d683243bf4.png)

What do you think of the amount of information presented? If we can think of a good summary amount to show the user, I can further iterate on that design.

**Comment by lstrobel** [comment]
Here is an image of the current screen as in pr #1370 
![screenshot_2018-12-31 project sidewalk](https://user-images.githubusercontent.com/12887715/50569545-4f2b6480-0d1c-11e9-8747-0710e74e1f93.png)

**Comment by jonfroehlich** [comment]
Can you center the resume mission button in the dialog?

**Comment by lstrobel** [comment]
Sure, just added that to the pr!

**Comment by lstrobel** [comment]
New modal: 
![screenshot_2018-12-31 project sidewalk](https://user-images.githubusercontent.com/12887715/50570383-d4734100-0d3d-11e9-9782-5ed7856557be.png)

**Comment by misaugstad** [comment]
Closing via PR #1370
