### ISSUE TITLE
Completion on choropleth over 100%

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#868]
This is on the production server. I am having a hard time understanding how this is the case, but I will think a bit more on it and look carefully at the code in the next day or two.

![sidewalk-104-percent](https://user-images.githubusercontent.com/6518824/28251402-68aa423a-6a4a-11e7-8bad-ed66674e9d5d.png)

I also found Takoma (West) to be at 101%.

**Comment by jonfroehlich** [comment]
Double counting streets audited by different users?

Doing something strange w edge streets that are shared by two neighborhoods?

**Comment by jonfroehlich** [comment]
Also seeing this in the Admin Interface as noted in https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1078

![image](https://user-images.githubusercontent.com/1621749/30300664-c00890da-970a-11e7-99e2-b7c5a4c86f16.png)

**Comment by misaugstad** [comment]
Closing via #884 and #1175 
We can reopen if users start having problems with this again.
