### ISSUE TITLE
Reverse geocoding neighborhood names

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#87]
We want to associate each neighborhood with its name. Unfortunately the [neighborhood polygon data that we are currently using](http://opendata.dc.gov/datasets/a0225495cda9411db0373a1db40a64d5_21) do not come with neighborhood names. So we have to reverse geocode the neighborhood names using some existing APIs. 

We could try [Google Geocoding API](https://developers.google.com/maps/documentation/geocoding/intro#ReverseGeocoding). We need to: 

1. query each neighborhood latlng coordinate from the database, 
2. pass it to the API, 
3. parse the neighborhood name, and 
4. insert the neighborhood name into the database.

**Comment by jonfroehlich** [comment]
In the short term, couldn't we do this by hand for Washington DC. Sure, it won't scale automatically to other cities but how many neighborhoods are there in DC total? Like 100? Probably would only take an hour to manually create a table associating the neighborhood polygon data with semantic data (e.g., neighborhood name, demographics, whatever else we deem necessary).

**Comment by kotarohara** [comment]
Either way works.

On the related note, each neighborhood should correspond to the [DC 2010 Tract](http://www.neighborhoodinfodc.org/censustract10/census.html). So if someone can manually/automatically scrape neighborhood information, that would be great. Note, I get the feeling that there is cleaner/more formatted DC census data somewhere on the internet. So if someone can find that data, that works too.

**Comment by kotarohara** [comment]
This is done.

**Comment by jonfroehlich** [comment]
Really? That's awesome. Did you do it by hand or code?

**Comment by kotarohara** [comment]
I used an existing GIS tool (QGIS).

**Comment by jonfroehlich** [comment]
Neat.

**Comment by jonfroehlich** [comment]
Still, did you do it programmatically or by hand?
