### ISSUE TITLE
Verify if MTurk Qualifications can be used to assign workers to different experiments

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#872]
Context:
The existing mturk branch creates HITs and maps them to unique static routes. Ideally we want to assign workers to a certain experiment which decides the routes that will be audited. We could implement this by having an additional controller on the sidewalk-mturk server.
It might be easier to use create qualifications on mturk that will allow us to restrict the HITs that workers can see. This would also easily allow us to randomly assign conditions and routes without more overhead on our server. 
We could also assign HITs associated with a single experiment to a specific cloud VM. This would avoid dependency between the code for different experiments and make our experiment pipeline more robust.

**Comment by maddalihanumateja** [comment]
Initial task. As a test for this:
- [ ] Create a HIT Ha which assigns a custom qualification Qx to the worker
- [ ] Create another HIT Hb which is only visible to workers with qualification Qx

**Comment by maddalihanumateja** [comment]
Next task:

- [ ]  Create two HITs a and c of the same type. HIT a assigns a custom qualification x to the worker who accepts it but becomes hidden to workers who obtain qualification y. HIT c assigns a custom qualification y to the worker who accepts it but becomes hidden to workers who obtain qualification x. Make sure that these HITs appear in a single group to workers. When this happens MTurk will randomly assign HITs a and c to workers. 

- [ ]  Create two HITs b and d of the same type. HIT a requires qualification x for a worker to accept it. HIT d requires qualification x for a worker to accept it. 

The assumption is that workers who complete HIT a first and get qualification x will only be able to work on HIT b. HIT c is invisible to them so they cant obtain qualification y to access HIT d. Similarly those who a randomly assigned HIT c first will only be able to work on HIT d.

The final workflow should look like in the following image:
![image](https://user-images.githubusercontent.com/3580069/28320633-14b634f8-6b9f-11e7-9de0-7c8ada441083.png)

**Comment by maddalihanumateja** [comment]
@chishankar  when you are implementing these on MTurk make sure to test these workflows out on the worker sandbox. 

1. This may seem like an obvious point but make sure you can identify which HIT you are working on. For example, in the intermediate task, HITs a and c should have the same [HIT Type](http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMechanicalTurkRequester/Concepts_HITTypesArticle.html) to be in a single group. This means they have the same title, description, ... . You need to figure out how to identify them uniquely using other metadata elements (Give them different Requester annotation). It might not even be possible using the MTurk GUI, you might need to employ the API.

2. Also check whether the qualifications that are granted to workers can be hidden from them.

3. Check if HITs in the same group are assigned in a random order to workers.

**Comment by chishankar** [comment]
New Workflow: 

<img width="716" alt="screen shot 2017-07-31 at 12 17 14 pm" src="https://user-images.githubusercontent.com/25187819/28787449-4664e88c-75ea-11e7-8552-b33336e4a035.png">

**Comment by chishankar** [comment]
<img width="713" alt="screen shot 2017-07-31 at 12 18 33 pm" src="https://user-images.githubusercontent.com/25187819/28787507-73559f12-75ea-11e7-8bef-0b8078718174.png">

**Comment by chishankar** [comment]
Workflow model is here on my repo:

https://github.com/chishankar/MTurksWorkflow

**Comment by chishankar** [comment]
2. The qualification cannot be hidden from the users. 

I will check on number 3 above and try and get this working by Wednesday

**Comment by chishankar** [comment]
So a few things to talk about:
1. I understand and know how to make multiple HITs in a single Batch. A few problems arise from this however.

For example, lets say we have HIT A and HIT B in the same Batch. When Publishing this it, is not possible to set different qualifications per batch and it is also not possible to only allow the user to select one of those hits in a Single Batch. The user will have access to both. 

So one solution is this. We have a Batch with Two HIT's as describes above with a single qualification test. Now I did some digging and it seems we can solve this problem by checking the USER_ID with the USERS that have already done our HITS. In this link: 

https://stackoverflow.com/questions/2835915/in-mechanical-turk-how-do-you-limit-to-one-hit-per-worker

Someone posted a script that goes on our backend, in the server, that basically checks the USER ID against all the users that have taken HIT 1 or HIT 2 and basically replaces the URL in the following HIT to NULL, disabling the USER from taking 2 hits.

**Comment by chishankar** [comment]
My recommendation: This should be handled on the back end. Create Data structure that tracks USER_ID's and checks this against how many tasks they have done/if they have already done one.

**Comment by chishankar** [comment]
<img width="600" alt="screen shot 2017-08-01 at 1 46 16 pm" src="https://user-images.githubusercontent.com/25187819/28838988-27a86398-76c0-11e7-96d5-dbcccb523639.png">

<img width="606" alt="screen shot 2017-08-01 at 1 44 57 pm" src="https://user-images.githubusercontent.com/25187819/28838989-27ab04d6-76c0-11e7-8961-66174a143e54.png">

**Comment by misaugstad** [comment]
We have finished these experiments.
