### ISSUE TITLE
Specify page on which a link was clicked when logging the click

### ISSUE THREAD

**Issue by adash12** [ProjectSidewalk/SidewalkWebpage#874]
Mentioned in https://github.com/ProjectSidewalk/SidewalkWebpage/pull/873#issuecomment-316070674
Currently links that appear on multiple pages (i.e. links in navbar or footer) are logged using the same string. The page/route on which the link is clicked needs to be included in the string as well to differentiate the clicks.

**Comment by manaswis** [comment]
Could you describe the issue and the title in simple terms understandable to everyone who isn't involved in the implementation? I think you are using terms specifically based on the implementation you did.

**Comment by misaugstad** [comment]
Resolved by #875
