### ISSUE TITLE
Please Add Link to SidewalkWebpage Github on API Page

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#882]
Please add a link to the SidwealkWebpage github on [API ](http://sidewalk.umiacs.umd.edu/api)page along with a sentence about it.

Should probably go in the intro text here:

![image](https://user-images.githubusercontent.com/1621749/28371813-f74a44b8-6c6b-11e7-814e-14a9ceb53902.png)

**Comment by manaswis** [comment]
Added a sentence at the end of the intro: 
> You can also help contribute! The code is accessible on <a href="https://github.com/ProjectSidewalk/SidewalkWebpage" target="_blank">github</a>.

![image](https://user-images.githubusercontent.com/2873216/28398047-49d5f274-6cd3-11e7-9635-8c16142507a5.png)

The "contribute" links to the contribute section of the page. It shows the following:

![image](https://user-images.githubusercontent.com/2873216/28398587-db5ff468-6cd5-11e7-8192-d9e73bcc04d4.png)

**Comment by misaugstad** [comment]
Resolved by #885
