### ISSUE TITLE
Update About Page Personnel

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#890]
It's outdated.

http://sidewalk.umiacs.umd.edu/about

Need to add:
- Ryan Holland @r-holland 
- Chirag @chishankar 
- Aditya @adash12 
- Steven @sbower213 
- Sage Chen @sagec108 (as alumni)

![image](https://user-images.githubusercontent.com/1621749/28465230-fd434d70-6df5-11e7-9ae5-72bb784d045d.png)

**Comment by misaugstad** [comment]
Also @maddalihanumateja and @misaugstad :stuck_out_tongue:

**Comment by jonfroehlich** [comment]
Ha, yes. This is like a 5 minute task for someone. I could do it...

**Comment by jonfroehlich** [comment]
In fact, assigning myself so Manaswi can show me the branch + pull request model. I also have the data from https://makeabilitylab.umiacs.umd.edu/project/sidewalk/

**Comment by jonfroehlich** [comment]
I just submitted a pull request for this using the instructions [here ](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Process-for-contributing-new-code)but wafflebot didn't notice it for some reason...

**Comment by misaugstad** [comment]
Closed via PR #957
