### ISSUE TITLE
Choropleth results page for negative labels

### ISSUE THREAD

**Issue by sbower213** [ProjectSidewalk/SidewalkWebpage#892]
As discussed in the meeting today, we're going to make a new choropleth with counts of negative labels. The color will be deeper red for neighborhoods with more of these labels (I assume we should do this as a ratio of labels to currently mapped miles in each neighborhood?) and fade to gray for better neighborhoods. Alternatively, we fade to a much lighter red, and use gray for areas with insignificant data. I'm working on this right now.

**Comment by misaugstad** [comment]
>I assume we should do this as a ratio of labels to currently mapped miles in each neighborhood?

Yes exactly.

>Alternatively, we fade to a much lighter red, and use gray for areas with insignificant data.

This is what we are going for, yep.

**Comment by sbower213** [comment]
almost done with this choropleth! (after finally figuring out how scala mediates between backend queries and sending results back to users :p)

![image](https://user-images.githubusercontent.com/8651110/28559375-460ff51c-70e4-11e7-92bd-eaa2b27bf284.png)

currently, i'm assigning neighborhoods with less than 15% completion as entirely gray (i.e. insignificant data). the remaining neighborhoods are colored by their number of issues per 1,000 meters audited. we can tune this function to yield more variable results (e.g. so fewer neighborhoods appear as the same shade of light pink).

**Comment by manaswis** [comment]
Closed via #895
