### ISSUE TITLE
Update deploy script to save old deployed version's binary directory

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#894]
Currently, when the deploy script runs, it replaces the application's binary directory with the new one. So each time a new version is deployed, the old log files are overwritten unless manually saved in a different directory (which is what I do on the production server).

Need to update the deploy script to do this manual copy process automatically.

**Comment by misaugstad** [comment]
closing via #2126 since the logs are now being saved when we deploy a new version of the code
