### ISSUE TITLE
Interesting comments related to outdated GSV images

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#904]
![image](https://user-images.githubusercontent.com/2873216/28597698-5c9f6ce8-716d-11e7-9989-364eb64f5c4d.png)

**Comment by jonfroehlich** [comment]
Definitely!

**Comment by jonfroehlich** [comment]
Would be great to go back there with our tool now to see if there is updated GSV imagery since this comment is nearly a year old :P

**Comment by manaswis** [comment]
Yes!

**Comment by misaugstad** [comment]
closing b/c not actionable. glad to have it recorded as a closed issue though!

**Comment by jonfroehlich** [comment]
Related to our temporal tracking project. Tagging @athersharif so he sees this. :)
