### ISSUE TITLE
Results Choropleth: Logging of neighborhood clicks should be different than the landing page choropleth

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#905]
The logs below will give you an idea.

![image](https://user-images.githubusercontent.com/2873216/28598534-2aa122d6-7172-11e7-93cf-8029a986f06c.png)

Tagging @misaugstad and @sbower213

**Comment by jonfroehlich** [comment]
Yes, definitely. Surprised that: (i) this wasn't coded up correctly at first (given that it seems obvious and we talked about appropriate logging in Slack) and (ii) that the original choropleth doesn't have a more descriptive name either (e.g., landing_page_choropleth or CompletionRateChoropleth).

Good catch @manaswis!

**Comment by manaswis** [comment]
Closed via #906
