### ISSUE TITLE
See Results in NavBar Doesn't Highlight on Mouse Over

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#908]
Start Mapping has mouseover highlighting:

![image](https://user-images.githubusercontent.com/1621749/28599639-3254edac-717a-11e7-9c26-fe11f08b7d6e.png)

The See Results button does not (but should):
![image](https://user-images.githubusercontent.com/1621749/28599644-395a5a88-717a-11e7-8783-e2096b5a0156.png)

**Comment by misaugstad** [comment]
Oh I have something even worse.
![sidewalk-what](https://user-images.githubusercontent.com/6518824/28599693-91ebe270-717a-11e7-914a-35e83394309e.png)

**Comment by misaugstad** [comment]
This is what it looks like in Chrome (on Ubuntu), it looks normal in Firefox though.

**Comment by manaswis** [comment]
@misaugstad Its due to the cache (I think). I had the same issue. It becomes fine in few more loads.

**Comment by jonfroehlich** [comment]
That's weird. It's like it's not getting the CSS or something...

**Comment by jonfroehlich** [comment]
Aha, yes, my suspicions are confirmed. Thanks @manaswis

**Comment by misaugstad** [comment]
Okay yeah I think you are right, cause there are a lot of weird things going on, come to me updated CSS!

**Comment by sbower213** [comment]
I updated the CSS in #829, so when that PR is merged, the button should update on hover correctly. I'm actually surprised that hovering over "See Results" did anything at all in past testing; I only just added the hover code in this PR.
