### ISSUE TITLE
Results Choropleth: Load Time Needs To Be Close to 1s or Less :)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#909]
The load time for the results choropleth is too long. Can we improve this?

![image](https://user-images.githubusercontent.com/1621749/28600350-763de21c-717f-11e7-9ce0-eca167c1d860.png)

**Comment by jonfroehlich** [comment]
@sbower213 Can you report back on the status of this so someone else can finish it off please?

**Comment by jonfroehlich** [comment]
Possible task for @johannkm to take over, especially since he already performed one optimization task for us successfully.

**Comment by misaugstad** [comment]
The plan for this was to store intermediate results in some table, and update it periodically. (for some context) Not sure how far @sbower213 got on this.

**Comment by jonfroehlich** [comment]
@misaugstad, right. @sbower213 actually left a number of Issues as in-progress when his internship ended. For those issues, it's unclear what the state is--I specifically asked him here: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/909#issuecomment-326088528 but he's likely been busy with the start of the semester and GT collection.

**Comment by jonfroehlich** [comment]
This is only getting worse. I timed it today: 55.17 seconds. So, our load time is almost 1 minute. It should be more like 1s! :) Maybe @johannkm could attack this one? Or @adash12 (if he is actually coming back to the team).

Also,  some folks on Hacker News are reporting that the page is throwing a proxy error (probably due to increased traffic): https://news.ycombinator.com/item?id=15791334

**Comment by misaugstad** [comment]
Any attacking of this one should probably wait until I have finished with changing over from labels to issues.  Will come back to this once that has been implemented!

**Comment by jonfroehlich** [comment]
Sounds good.

**Comment by jonfroehlich** [comment]
@misaugstad not sure it makes sense to wait on this until you are done converting from labels to clusters (issues) given that your primary focus currently is on CSCW analysis rather than integrating this code into the backend for deployment (I believe).

So, as suggested on Slack, perhaps we have @adash12 take this on as his first task this semester. It's fairly high priority because, as noted by others, we are advertising the Results page but it is embarassingly slow.

The solution should be pretty easy: we need to precompute the results and store them in a table (the precomputation can be scheduled for nightly or something). @adash12, thoughts? Could you do this for your primary task this week as a way of ramping back up to our codebase, etc.

Also CC'ing @manaswis since she was the one that suggested @adash12 take this on.

**Comment by misaugstad** [comment]
>@misaugstad not sure it makes sense to wait on this until you are done converting from labels to clusters (issues) given that your primary focus currently is on CSCW analysis rather than integrating this code into the backend for deployment (I believe).

Right, especially if we are really wanting to use the viz now. It shouldn't be hard to switch it over to issues when that change is made.

>The solution should be pretty easy: we need to precompute the results and store them in a table (the precomputation can be scheduled for nightly or something). @adash12, thoughts? Could you do this for your primary task this week as a way of ramping back up to our codebase, etc.

As for updation, I am leaning a bit more towards real-time updating in a similar fashion to how the DC completion choropleth is updated. Whenever a user finishes an audit task, a function called `updateAuditTaskCompleteness` in `TaskController.scala` is called. It does a few things, including updating the `region_completion` table. We could call another function to update this new table @adash12  is writing here.

We would have to check how long it takes, but I think this would be fast enough if we only updated the region that the use is working in, instead of the entire table.

**Comment by jonfroehlich** [comment]
Sounds good Mikey. I like this approach.  Need to hear back from Aditya.

**Comment by misaugstad** [comment]
After I finish #1242 @aileenzeng can take a look at what the loading time is like, and see what other improvements can be made.

**Comment by misaugstad** [comment]
Actually, we are going to hold off on this for now. We may just scrap this and use a visualization that @manaswis was working on for a class in the Spring. This is going to the back burner for now.

**Comment by jonfroehlich** [comment]
Maybe. But perhaps showing a results vis vs accesscore vis has different functionality and purpose. Needs discussion.

**Comment by misaugstad** [comment]
After PR #1321 load time is closer to 5 seconds, still not good enough though!

**Comment by misaugstad** [comment]
Load time is down to less than 2 seconds, looks good to me :)
