### ISSUE TITLE
Design Inspiration: Grimouville

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#91]
After the webpage loads, click the diamond:

![image](https://cloud.githubusercontent.com/assets/1621749/14804793/660064d6-0b34-11e6-8c2e-1fd399764fed.png)

It's got great fluid movement (they are not using GSV) and a nice, animated overlaid map. It's a very immersive experience.

![image](https://cloud.githubusercontent.com/assets/1621749/14804806/813f15a8-0b34-11e6-975e-ebf470fb7c54.png)

(Sorry for posting this here, it's the easiest way to communicate with the team since we don't have a great mailing list at the moment).

**Comment by kotarohara** [comment]
I'm closing this as it is not really an issue.
