### ISSUE TITLE
When You Create A Post on Facebook, Facebook Now Pulls Strange Images from Page

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#911]
When you create a post on Facebook with http://projectsidewalk.io, Facebook used to show the same default image as Twitter:
![image](https://user-images.githubusercontent.com/1621749/28627940-32e7c920-71f1-11e7-898d-ef70eb12c43f.png)

But now shows this, which isn't particularly informative and seems confusing:
![image](https://user-images.githubusercontent.com/1621749/28627887-05243992-71f1-11e7-895a-5d1f03ce4ea1.png)

When I used the Facebook open [graph debugger](https://developers.facebook.com/tools/debug/og/object/?q=projectsidewalk.io), my suspicions were confirmed:
![image](https://user-images.githubusercontent.com/1621749/28628079-99440b16-71f1-11e7-8f7b-8b7974624618.png)

So, two things, I think we should have a much better thumbnail that is used for Facebook shares and also the text description is out-of-date and should likely be auto-generated based on current progress:
![image](https://user-images.githubusercontent.com/1621749/28628135-c3486a9c-71f1-11e7-8235-3c50cf192c0f.png)

**Comment by sbower213** [comment]
I found this post in the facebook forums which I was able to recreate successfully on my personal blog. https://www.facebook.com/help/community/question/?id=10200814000150949

Adding the `<meta property="og:[type]">` tags let you change the content that appears in a facebook link. I can go ahead and add/change these to update text. I'm not sure if  the meta tags can be dynamically generated to reflect distance, but I will look into it. It will be hard to test this, as facebook can't generate link previews for localhost.

**Comment by sbower213** [comment]
Also, our twitter description is "Help us make sidewalks more accessible, for everyone." Is this preferred to the text description that facebook currently uses? or should I investigate having a dynamically updated version of the current description?

**Comment by manaswis** [comment]
I think the text on the landing page should be auto-updated based on the distance covered. We might have to completely remove the "DC to Boston" or have alternate phrases based on the distance covered. 

Then if facebook pulls that text, wouldn't that work?

**Comment by manaswis** [comment]
@sbower213 Just saw your PR. So maybe the `<meta>` tags uses the same code that will be used in the "your work is making a difference" section to auto-update the distance covered. Would that work?

**Comment by manaswis** [comment]
@sbower213 I pushed your PR changes to production so that it could be tested. The graph object debugger that Jon had linked before shows the following when the click Fetch New Scrape Information:

![image](https://user-images.githubusercontent.com/2873216/28634614-bff951d0-7205-11e7-86f3-5a8799cb5c90.png)

URL to access the debugger: https://developers.facebook.com/tools/debug/og/object/

**Comment by manaswis** [comment]
Hmm, interesting. Even though it shows the above error, the section below shows the updated content:

![image](https://user-images.githubusercontent.com/2873216/28634785-4e136406-7206-11e7-9004-b9db28099816.png)

**Comment by manaswis** [comment]
It works on Facebook:

![image](https://user-images.githubusercontent.com/2873216/28634843-83869a22-7206-11e7-9b2e-c15255666891.png)

**Comment by manaswis** [comment]
Closed via #912
