### ISSUE TITLE
Update FAQ page to answer questions around understanding accessibility when labeling

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#915]
Stemming from a recent discussion over email, we should update the FAQ page to include questions around what sidewalk accessibility means, something similar to [Google's Guide on Answering accessibility questions on Google Maps](https://www.localguidesconnect.com/t5/How-do-I/Answering-accessibility-questions-on-Google-Maps/m-p/26#M2270). Google answers questions such as:

1. Is there a wheelchair-accessible entrance?
2. Is there wheelchair-accessible seating?
3. Is there wheelchair-accessible parking?
4. Is there a wheelchair-accessible elevator?

![image](https://user-images.githubusercontent.com/2873216/28646435-9ee1afcc-722f-11e7-9eb6-5e9a3d488922.png)

In a similar way, in our FAQ, we should answer these tough questions such as 
- What does it mean for a curb ramp to be accessible? 
- Is the sidewalk passable when an obstacle is present?
- How would they rate the severity of an issue? We partly already do that. We should do a better job.

Making them understand with the help of comparatives like the answer above by Google - 

> One meter is approximately the minimum comfortable width for two people to stand right next to each other.

Related issue #916

**Comment by jonfroehlich** [comment]
Hmm. Maybe we need two top-level links and pages. One that is an FAQ and has FAQ like Q & A and the other that is the labeling guide. Both would cross reference each other (e.g., the FAQ might have some high-level question about labeling and then say: "read more at our labeling guide" and the labeling guide might say, "for more general Q/A not related to labeling, see our FAQ").

**Comment by misaugstad** [comment]
Aaaand we now have a labeling guide!
