### ISSUE TITLE
Exploring Collaborations with Zooniverse

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#919]
Another longtime TODO (like [this one](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/917)) is exploring collaborations with Zooniverse. Zooniverse is, in my mind, the pinnacle of online crowdsourcing for science and has been extremely successful. A listing on Zooniverse could seriously drive traffic to our site and help us increase visibility and credibility.

Zooniverse actually has a Project Builder built into their website to allow scientists to create their own crowdsourcing experiences using a wizard-like interface (see https://www.zooniverse.org/lab). We obviously don't want to do this. I just asked about our case here: https://www.zooniverse.org/talk/18/403792. 

Depending on responses here, I will also email collab@zooniverse.org based on [this info](https://www.zooniverse.org/about/contact):

> If you are interested in collaborating with the Zooniverse, for instance on a custom-built project, please email collab@zooniverse.org. (Note that our Project Builder offers an effective way to set up a new project without needing to contact the team!)

**Comment by jonfroehlich** [comment]
OK, someone from Zooniverse got back to me about listing Project Sidewalk on their page ([link](https://www.zooniverse.org/talk/18/403792?comment=677710)). They said this:

> Hi Jon,
> 
> Thanks for getting in touch. Your project looks fantastic, and it's so amazing to hear that it was inspired by the Zooniverse! Unfortunately we do not list any projects on our site that were not build using our platform, however I'd be happy to discuss other forms of cross-promotion with you (such as blog posts, Tweets etc). Please email me at contact@zooniverse.org to talk about this in more detail.
> 
> Cheers,
> 
> Grant

I will follow up with them and keep this Issue updated.

**Comment by jonfroehlich** [comment]
I emailed this on Aug 1 to contact@zooniverse.org but I have not heard back:

> I chatted with Grant Miller briefly on the Zooniverse forums (link) about our new crowdsourcing tool called Project Sidewalk, which enables users to virtually walk through cities to locate, label, and assess sidewalks. As I mentioned on the forums, the tool is partially inspired by many of the great projects on Zooniverse like Snapshot Serengeti.
> 
> I originally asked if there was a way to formally collaborate or list Project Sidewalk on the Zooniverse site. It sounds like this is not possible because our project was not built using the Zooniverse platform; however, Grant suggested I email to discuss other forms of cross-promotion like blog posts, Tweets, etc. 
> 
> We are quite interested in this! Please let us know how to move forward.
> 
> Thank you,
> 
> Jon (Project Sidewalk PI).

**Comment by jonfroehlich** [comment]
I just followed-up on Aug 9th. We'll see.

**Comment by misaugstad** [comment]
@jonfroehlich what ended up happening with this?

**Comment by misaugstad** [comment]
Looks like collaboration with Zooniverse was denied :(

**Comment by jonfroehlich** [comment]
Actually, I received this email from Grant Miller on Oct 26, 2017 but then I never responded. I'll respond now.

> 
> Hi Jon,
> 
> I'm so sorry for such a terribly delayed reply! I'd be happy to give your project some promotion via our social media channels. If you send me some suggested tweets I'll post from our main account.
> 
> Cheers,
> 
> Grant

**Comment by jonfroehlich** [comment]
Just emailed him.

**Comment by misaugstad** [comment]
@jonfroehlich It looks like this has probably been seen through all the way? If there is more to do here, please reopen!
