### ISSUE TITLE
Possibly large number of missing panos again?

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#920]
I was auditing tonight in Palisades (neighborhood in northwest corner of DC) and was getting A LOT of black panos, occasionally getting 404 errors in browser. I logged a bunch of them through the feedback tool on the production server.

I then switched to capitol hill (south) and was getting fewer black/blank panos, but still got a maybe 3 in the course of 1000ft.

Not sure if this is a problem with us or Google, or I may have just been unlucky. Anyone else willing to do some stress testing on dev server to see if they find the same thing?

**Comment by maddalihanumateja** [comment]
Browser, OS and version? Also, was there any message on the javascript console when you got a black pano?

**Comment by maddalihanumateja** [comment]
Also tried auditing in palisades. Got this error. It might have something to do with google
<img width="1269" alt="screen shot 2017-07-27 at 9 10 46 pm" src="https://user-images.githubusercontent.com/3580069/28698300-779c5cb4-7310-11e7-9b41-2625632393f2.png">

**Comment by jonfroehlich** [comment]
Detecting and avoiding blank/black GSVs was something @sagec108 was working on.

@sagec108, do you have anytime to look into this?

**Comment by misaugstad** [comment]
@maddalihanumateja Those are precisely the errors I had, yes.

Google Chrome, version 60.0.3112.78 (Official Build) (64-bit) on Ubuntu 14.04.

**Comment by jonfroehlich** [comment]
I just tried to audit (on production server) to see if I would see this problem too and I ran into this issue:

![image](https://user-images.githubusercontent.com/1621749/28719554-56305252-7378-11e7-9d73-368124cd34ff.png)

**Comment by misaugstad** [comment]
@jonfroehlich were you able to audit even though you saw that error, or were you unable to..?

**Comment by jonfroehlich** [comment]
The page just stayed in that load state perpetually. I had to manually refresh browswer and then it worked.

**Comment by misaugstad** [comment]
Also, it seems that there are no pano ids associated with the black screens I was looking at, which isn't surprising...

![no-pano-id](https://user-images.githubusercontent.com/6518824/28721852-aca6e630-737f-11e7-8777-6824e2bfd5b2.png)

**Comment by jonfroehlich** [comment]
I did just run into a blank screen:

![image](https://user-images.githubusercontent.com/1621749/28721898-c7442908-737f-11e7-9061-a35bd0cbebb6.png)

**Comment by jonfroehlich** [comment]
Do we still think this is a problem? Do we need to take additional action or should we close out this Issue?

**Comment by misaugstad** [comment]
It seems that google has probably dealt with this. I haven't been having any issues for the past two weeks.
