### ISSUE TITLE
Sometimes I hit the 'Z' key and nothing happens

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#922]
Unfortunately, hard to show this one. It's happened a few times this morning. I try to hit the 'z' key and nothing happens. Like right now. Here's what the screen looks like (not like this is useful):

![image](https://user-images.githubusercontent.com/1621749/28722070-6bda053c-7380-11e7-9a65-71e99ebff5c0.png)

**Comment by jonfroehlich** [comment]
So, I am able to get the keyboard to work again by click on the Zoom In button then Zoom Out buttons. I'll keep trying to investigate.

**Comment by misaugstad** [comment]
Try hitting shift-z a few times, that sometimes fixes it for me as well

**Comment by misaugstad** [comment]
possibly related to #551 

I also have always had this problem while using the tool. I can't find an issue where it was discussed, but I remember talking about it with other. And I thought someone had told me ~a month ago that a fix was about to be pushed, but I still have the same issue all the time now.

**Comment by jonfroehlich** [comment]
Right, so, for some reason I think the 'zoom' tracker is buggy. And it must think that you are already all the way zoomed in so it just ignores the zoom command.

**Comment by jonfroehlich** [comment]
This is a possible task for @shivenbhatt. Will assign him once he accepts our Github collaboration request.

**Comment by jonfroehlich** [comment]
In conversation with @misaugstad yesterday, he said this happens quite frequently. Would be great to get this fixed @ShivenBhatt.

**Comment by misaugstad** [comment]
Fixed in PR #1279 nice work @ShivenBhatt !
