### ISSUE TITLE
InvalidValueError: setPov: in property heading: NaN is not an accepted value

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#923]
I just received the error: "InvalidValueError: setPov: in property heading: NaN is not an accepted value" and now I can no longer pan. :( I can move to different panos but still can't pan. Will likely have to refresh to fix.

![image](https://user-images.githubusercontent.com/1621749/28722321-523c0188-7381-11e7-8067-ba5bf2e683e9.png)

**Comment by misaugstad** [comment]
Haven't reproduced in past 2 years so I'm closing for now.
