### ISSUE TITLE
Completed Mission and Next Mission Started at 41%

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#924]
This morning, I was auditing Cleveland Park and I completed a mission. After accepting my next mission, the mission tracker (on sidebar) started at 41%. Shouldn't it start at 0% because I just started a new mission.

**Comment by misaugstad** [comment]
Bonus points!

But after you audited a bit more, did it go back down to ~5%, or did it just keep going up? I ask because I thought I remember really old issues talking about this sort of behavior.

**Comment by jonfroehlich** [comment]
It stayed at 41% and continued upwards. I was going to complete this mission to figure out what would happen next (e.g., if it would reset back to 0% or go to another arbitrary value) but then I ran into this problem: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/923, which prevented me for going any further in the mission (you'll note the screenshot in https://github.com/ProjectSidewalk/SidewalkWebpage/issues/923#issue-246367941 shows 64% but I started at 41%!)

**Comment by misaugstad** [comment]
This should be solved by the new mission infrastructure. Closing via PR #1319
