### ISSUE TITLE
Would be nice to know: how much of neighborhood is left to be audited

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#925]
The sidebar shows how much of a neighborhood a user has audited; however, I think it should also show: how much is left (perhaps visualized as just a text percentage or perhaps a little bar graph). I think this would be motivating.

The calculation for how much is left should be how much is left including routes audited by all users in this neighboorhood. Route assignments in a neighborhood should assign un-audited routes first.

![image](https://user-images.githubusercontent.com/1621749/28724798-4be8a0b8-7389-11e7-9450-22d750959963.png)

**Comment by misaugstad** [comment]
> Route assignments in a neighborhood should assign un-audited routes first.

The relevant issue for this is #839

**Comment by manaswis** [comment]
Related issue https://github.com/ProjectSidewalk/SidewalkWebpage/issues/846 - talks about adding a neighborhood progress bar in the mission completion dialog.

**Comment by misaugstad** [comment]
this is now captured by #1635
