### ISSUE TITLE
When a user finishes the last street in a region, ask if they want a new region

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#926]
If a user is auditing and they finish a street that brings the neighborhood completion (across ALL users) to 100%, then we should have a pop-up asking if they want to move on to a new neighborhood. Overlapping data is nice and all, but right now we are having a hard time hitting 100% coverage of DC, so we should be doing whatever we can to get users working on unaudited streets. And I think this could help with that.

This goes along with the idea of having a neighborhood completion (across all users) progress bar, as outlined in #925 

And before we do this, we should be making sure to assign users to unaudited streets (across all users), as outlined in #839

**Comment by manaswis** [comment]
I agree. I can work on #839 with you next week depending on my schedule. Let's talk about it on Monday.

**Comment by misaugstad** [comment]
This is music to my ears!

**Comment by jonfroehlich** [comment]
FYI: When you finish a neighborhood now, you get auto-assigned a new one. Unless something changed since I last completed a neighborhood.

**Comment by misaugstad** [comment]
Correct, but that is when you have personally finished the entire neighborhood. The situation I am talking about is where a user brings the total neighborhood completion (as seen on choropleth) to 100% even though they did not personally audit the entire neighborhood themself.

**Comment by jonfroehlich** [comment]
Oh, of course. Right on!

**Comment by manaswis** [comment]
Updating issue thread with the discussion on Slack:

The message should be something like the following:

"Congrats! You just helped complete `<neighborhood X>`. You can: (i) continue auditing in this neighborhood;  (ii) Take me to a new neighborhood"

The two options will be two buttons.

The layout with the buttons will be similar to the overlay we have for difficult neighborhoods:

![image](https://user-images.githubusercontent.com/2873216/29476423-f4f2d256-8431-11e7-9470-fbffa433b7fc.png)


Also, log events for these:

1. Add an event in the interactions log when this event is triggered - `NeighborhoodComplete_AcrossAllUsers` and store the region id in the note field. Also, log which option the user selects.
2. Add a log for `NeighborhoodComplete_ByUser` at the place where neighborhood is marked as complete for the user. Note this is when the user personally audits an entire neighborhood.

**Comment by manaswis** [comment]
Closed via #1011
