### ISSUE TITLE
Consider having a more informative navbar

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#928]
During my pilot with our long-time collaborator, he mentioned that he was searching for more options/links on the navbar. Currently, all our links that talk about Us and our team are in the footer, and people don't scroll down enough to get there. So we might lose out on people who might not be used to modern designs and prefer to see links on the navbar. 

Zooinverse does this well:

It has an informative navbar
![image](https://user-images.githubusercontent.com/2873216/28739653-97131104-73ca-11e7-9d4e-fb7bc8206f18.png)

As well as footer links:
![image](https://user-images.githubusercontent.com/2873216/28739658-a10018a6-73ca-11e7-9eb6-baeb0ca7e711.png)

I think this design would cater to a wider audience who aren't as design savvy as us.

**Comment by jonfroehlich** [comment]
I think this is worth discussing. Having: About Us and How to Label or something seems like two important links that should be up there.

**Comment by misaugstad** [comment]
We have since added How To Label, and a few other links. The navbar is poppin now!
