### ISSUE TITLE
The design of the icon on the status bar that indicates the walked distance

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#93]
The Distance status indicates how much a user has walked in that neighborhood. We changed the icon for this from a map icon to a footprint icon. 

![image](https://cloud.githubusercontent.com/assets/612263/15403168/b03a469a-1dc5-11e6-96b7-7c05785b496b.png)

Just wanted your opinion on which ones would look better among the following options (previous map icon, legs, and footprints).

<img src="https://cloud.githubusercontent.com/assets/612263/15403111/581647c0-1dc5-11e6-8176-e26aef59fe0b.png" width="48">
<img src="https://cloud.githubusercontent.com/assets/612263/15403114/5a368e8e-1dc5-11e6-8c37-5843a1d89e7c.png" width="48">
<img src="https://cloud.githubusercontent.com/assets/612263/15403117/5c7d96ce-1dc5-11e6-8fa7-ff23a328c253.png" width="48">

/cc @nguyenist @jonfroehlich

**Comment by jonfroehlich** [comment]
I like the sideways leg walking icon but it would need to be iterated on a bit to match the elegance of the other icons.

**Comment by nguyenist** [comment]
I don't think icons are necessary here. Simplicity is best where possible! 👍 

My recommendation would be to change this to:
0.00 miles [walked, labeled, etc.] -- add some sort of word that explains what the user has done.

Keep "X labels" as is. Remove the wheelchair image.

**Comment by kotarohara** [comment]
Ok. As we all voted for different design, I'll keep it as is for now. We can come back to this if it's necessary. I'm closing it for now.
