### ISSUE TITLE
User Dashboard: Does Something Show Up in Completed Missions Table Even If Not Complete

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#930]
For example, this user seemed to only label eight things and the map indicates that the user did not really walk and yet their dashboard shows a completed mission:

![image](https://user-images.githubusercontent.com/1621749/28740689-10a7101e-73d6-11e7-8298-8d42d84aa847.png)

User ID: 1cb7ac74-fc8f-465c-9425-96039fb07906

**Comment by misaugstad** [comment]
This could happen if the user was placed on a street that was longer than the distance of their first mission. So they finished their first mission and stopped auditing, but this is before they finished auditing the entire street. We consider audited distance to only include streets that the user has audited completely, so in rare cases we can have completed missions with no audited distance (and thus, nothing shown on the map).

Given that this behavior is actually correct, I'm going to close this issue for now.
