### ISSUE TITLE
Add a way for admins to log in on mturk branch

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#934]
Logging in has been removed from the Mturk branch. Well, at least the ability to get to any sign in page has been removed, though I suppose you could probably log in if you sent the right kind of data to /signIn.

This makes sense since turkers aren't supposed to be able to log in right now, but I think that we do want to allow admins only to be able to log in somehow. This way we can do clustering, perform GT resolution, but with the security of it not being just open to anyone who finds the endpoint.

**Comment by misaugstad** [comment]
If you go to [projectsidewalk.io/signIn](http://sidewalk.umiacs.umd.edu/signIn) you can enter credentials there, but on mturk branch, you get rerouted back to landing page.

**Comment by adash12** [comment]
Made changes on groundtruth-add-admin-sign-in: /gtresolution redirects to sign-in page if the user isn't logged in. Only admins can sign-in (an error message appears if user is a non-admin). After signing in, admin is redirected to the ground truth resolution tool.
Merged into groundtruth-resolution-dev

**Comment by misaugstad** [comment]
Implemented in #963
