### ISSUE TITLE
Anthony's Sidewalk Panorama Tools Needs to Be Part of Project Sidewalk Repo

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#938]
I was unaware until now that [Anthony's Sidewalk Panorama Tools](https://github.com/tongning/sidewalk-panorama-tools) are not actually in the ProjectSidewalk github repo. I think this is a mistake and will lead to problems. All of this code, updates to the code, and documentation should be in a sub-project of https://github.com/ProjectSidewalk.

**Comment by jonfroehlich** [comment]
Hey @tongning, now that you're back, can you work on doing this?

**Comment by tongning** [comment]
Moved code to https://github.com/ProjectSidewalk/sidewalk-panorama-tools and added a deprecation message to the original repo.
