### ISSUE TITLE
Make API for Pano Scraper

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#939]
As part of our API, I would like researchers to be able to download our scraped panos along with the labels (and all associated label metadata).

**Comment by maddalihanumateja** [comment]
I'm not too sure about that. We can probably give them the panorama ID but actually allowing to download panoramas needs more rigorous scrutiny.

**Comment by jonfroehlich** [comment]
We've discussed this before. We might have to make a private key (or something) so that it's not totally open access. We can discuss other things offline.

**Comment by jonfroehlich** [comment]
Closing this as we now provide GSV pano ids in our API.
