### ISSUE TITLE
Include Map of Neighborhood on Intro Mission Screen

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#94]
I think you should have the map of the neighborhood in this mission screen, both to give users more knowledge about what they're doing and to be consistent with later mission feedback screens.

![image](https://cloud.githubusercontent.com/assets/1621749/15505476/b8e99488-2191-11e6-99de-b817c7736ae6.png)

**Comment by misaugstad** [comment]
This is one of many possible ideas for what to do with the mission start screens (#2152). I think we are leaning towards something more in the realm of training users, but discussion is happening in #2152
