### ISSUE TITLE
Mission Sidebar Confusing

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#95]
![image](https://cloud.githubusercontent.com/assets/1621749/15505520/e297fcac-2191-11e6-81a0-6e97349e8585.png)

I just started my mission but my mission bar says '14%' -- why not 0%?

Also, the text "Make the 25% of this neighborhood more accessible" is confusing and not grammatically correct.

Does this indicate that the full mission bar is 25% and I'm currently 14% done with this 25% (so 3.5% overall)?

**Comment by kotarohara** [comment]
This should be fixed.

**Comment by kotarohara** [comment]
Actually I realized there are multiple points in this issue. 

- not starting from 0% should be fixed. 
- I removed the 25% mission.

So yeah, actually this is done.
