### ISSUE TITLE
Landing Page: Tweets Link to incorrect Project Sidewalk Twitter page

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#952]
![image](https://user-images.githubusercontent.com/2873216/29095998-020eafa6-7c61-11e7-9d8f-e62bb0daf76b.png)

The links are still linked to the old username - umd_sidewalk instead of projsidewalk

**Comment by jonfroehlich** [comment]
PR submitted here: https://github.com/ProjectSidewalk/SidewalkWebpage/pull/962

**Comment by manaswis** [comment]
Closed via #962
