### ISSUE TITLE
GSV nav arrows initially show in tutorial, until mouse enters GSV

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#954]
When the tutorial initially loads, the navigation arrows are in GSV
![arrows-nowyouseethem](https://user-images.githubusercontent.com/6518824/29102266-e4084560-7c85-11e7-8329-946d9a9f7e6b.png)

Then once the mouse enters the GSV pane, the arrows immediately disappear.
![arrows-nowyoudont](https://user-images.githubusercontent.com/6518824/29102273-ee42adc2-7c85-11e7-9efd-208f17a93864.png)

Not a big deal, just noting it here. The ideal behavior is that the arrows never show up.

**Comment by jonfroehlich** [comment]
Right. This should be fixed but low priority.

**Comment by misaugstad** [comment]
@ThatOneGoat this is relatively low priority, so I wouldn't spend a week on trying to fix this or anything, but I'd like you to take a look and see if you can figure it out!

**Comment by misaugstad** [comment]
closing via #2032
