### ISSUE TITLE
Overlapping Audit Routes Between Volunteers Analysis

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#955]
Audit routes within a neighborhood are currently assigned based on the user's *own* past audit history. That is, we guarantee on a per-user basis that a user will not have to re-audit a route. However, what we really want to do is assign audit routes on a global basis--that is, a user should be assigned routes that have *never* been audited by any user. This would allow us to finish DC much more quickly.

Given the current implementation, I would like to know how many street segments have, incidentally, had multiple auditors. Perhaps this is an unexpected opportunity for us to look at agreement between auditors for these street segments. We should look into this for CHI2018.

**Comment by misaugstad** [comment]
This issue has been replaced by a similar one in our data analysis repo (https://github.com/ProjectSidewalk/sidewalk-data-analysis/issues/7). And the current status of this analysis can be found here: https://github.com/ProjectSidewalk/sidewalk-data-analysis/blob/master/R/stats_for_paper.md#data-characteristics
