### ISSUE TITLE
Polygons from Tohme can still be created in current code

### ISSUE THREAD

**Issue by sbower213** [ProjectSidewalk/SidewalkWebpage#956]
Discovered in #945, some code still exists that allows users to draw polygons in the style of [Tohme](http://www.cs.umd.edu/~jonf/publications/Hara_Tohme-DetectingCurbRampsInGoogleStreetViewUsingCrowdsourcingComputerVisionAndMachineLearning_UIST2014.pdf). While this only occurred for me due to an error in how I was handling labels, this could result in unexpected behavior on the user's end if uncaught errors are pushed to production.

My code with errors:
![image](https://user-images.githubusercontent.com/8651110/29136046-05f7a0f6-7d0a-11e7-8e22-f86c8b0b2a84.png)

Tohme:
![image](https://user-images.githubusercontent.com/1621749/29136985-e70b1706-7d0c-11e7-81cb-3cb39a19d900.png)

This particular error happened in ContextMenu.js when I tried to access the properties of a "No Sidewalk" label's nonexistent ContextMenu. The error of "Cannot read property 'audit_task_id' of undefined" was thrown, and any subsequent "No Sidewalk" labels placed drew a polygon. We should isolate where this code is and why it is still referenced in our current code.

Screenshot of console: 
![image](https://user-images.githubusercontent.com/8651110/29139941-acbc0f92-7d16-11e7-8676-e4a5eda81409.png)

**Comment by sbower213** [comment]
To recreate this issue (going off code currently on #945), in ContextMenu.js comment out the line `svl.tracker.push('ContextMenu_Open', {'auditTaskId': labelProperties.audit_task_id}, {'temporaryLabelId': labelProperties.temporary_label_id});` [currently line 362]. Then paste the same line right before `self.updateRadioButtonimages();` [currently line 366]. Then open up an audit and try placing a few "No Sidewalk" or "Can't see the sidewalk" labels.

**Comment by manaswis** [comment]
Place the labels randomly or in some order?

**Comment by manaswis** [comment]
Also, does this occur after the fix you made?

**Comment by sbower213** [comment]
No order, just place a few consecutive "No Sidewalk" or "Can't see the sidewalk labels" and you'll see the polygon drawn.

This does not occur in the changes made #945; I fixed my erroneous code that brought this issue to light.

**Comment by misaugstad** [comment]
@manaswis should this still be open? I would say we can close it, since he fixed the error that cause that code to be called. Or do we want to keep this and have a discussion about whether we want to totally remove the old code instead of just keeping it outside an `if` statement?

**Comment by manaswis** [comment]
I think let's keep it open. It will serve as a reminder to look at it at some point.

**Comment by misaugstad** [comment]
I think we should remove the old code now :)

**Comment by jonfroehlich** [comment]
Agree. Perhaps copy the code below before we remove it (if it's easy/clean enough to do that)

**Comment by misaugstad** [comment]
When removing the old Tohme code, one thing I'd be doing is removing any references to a "Point" object in JavaScript. I think that right now a "Label" is a collection of "Points". Which made sense when labels were polygons, but now they are just a list of a single Point, so that can all be removed.
