### ISSUE TITLE
Typo in tutorial - "Click the Missing [Cub] Ramp Button" 

### ISSUE THREAD

**Issue by ajmed** [ProjectSidewalk/SidewalkWebpage#96]
The typo is in the first scene on the second curb. Notice the typo inside the tutorial textbox.

![image](https://cloud.githubusercontent.com/assets/16959700/15513674/b11a462c-21b3-11e6-93ff-725d17e7a359.png)

**Comment by kotarohara** [comment]
Thank you! I'll fix the typo.
