### ISSUE TITLE
Um, Why Does Cleveland Park Have 1,005 Missing Curb Ramps?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#973]
Someone should investigate this. If I had to guess, I imagine that a user labeled walkway extensions to house.

![image](https://user-images.githubusercontent.com/1621749/29221269-29011f2c-7e8c-11e7-822f-b02e91732f12.png)

![image](https://user-images.githubusercontent.com/1621749/29221297-42871faa-7e8c-11e7-84b1-238ebd5ad664.png)

**Comment by manaswis** [comment]
I have a guess why that might be the case. Our tutorial location is in Cleveland Park and every user goes through the tutorial, hence, the number of Missing Curb Ramps is high.

**Comment by jonfroehlich** [comment]
Are the labels gathered during tutorial marked as such? If not, we need to make this modification.

**Comment by misaugstad** [comment]
They are associated with specific panos that we know about, so we can always just filter out the panos we don't want

**Comment by manaswis** [comment]
Hmm, true. The tutorial pano id changed once when the pano id  of that location was expired. So there would be two sets of pano ids for the tutorials that would need to be filtered out.

**Comment by jonfroehlich** [comment]
Anything collected during tutorial should clearly be marked as such in database to ease querying. We also need to fix this Choropleth.

**Comment by misaugstad** [comment]
Hey, let's make a new table for everything! A new onboarding_panos table, why not!

**Comment by manaswis** [comment]
Or we would add a column `tutorial` to the label table and assign a boolean to it.

**Comment by jonfroehlich** [comment]
I think Michael's idea is more space and query efficient. Also, remember, we will want to analyze tutorial performance in detail for the paper so we need to easily be able to query this data and analyze things like time on tutorial, mouse interactions, labels, etc.

**Comment by manaswis** [comment]
Added more context by adding a map showing those labels to the original https://github.com/ProjectSidewalk/SidewalkWebpage/issues/973#issuecomment-321930239

**Comment by jonfroehlich** [comment]
Something weird is going on here with label counts. The screenshot in the first comment (which is from Aug 11) shows 1005 missing ramps. The screenshot in @misaugstad's [PR](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/1139) is from Oct 11 but yet shows only 994 missing ramps--despite it being two months later and lots more users taking the tutorial. How can label counts go down?

![image](https://user-images.githubusercontent.com/1621749/31470941-1fcfd76a-ae9b-11e7-941f-2ed9d684c181.png)

![image](https://user-images.githubusercontent.com/1621749/31470951-2b8ba9ee-ae9b-11e7-92df-100623a65550.png)

Note: this is *not* talking about the fix that @misaugstad submitted as part of the PR.

**Comment by misaugstad** [comment]
I was using a local dump for both images.

**Comment by jonfroehlich** [comment]
Ah, ok! Makes sense. Thanks.

**Comment by misaugstad** [comment]
Closed via #1139
