### ISSUE TITLE
Admin Interface: GSV is black within the view labels dialog

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#976]
After updating the query in PR #975 the panorama is not showing up, as in the image below.

![no_gsv](https://user-images.githubusercontent.com/6518824/29228712-e950f326-7ea8-11e7-927d-1a8ecb925b38.png)

**Comment by manaswis** [comment]
Interesting behavior. The GSV image is visible within the dialog immediately after you open the browser console.

![image](https://user-images.githubusercontent.com/2873216/29233054-eb557b10-7ebc-11e7-9a31-27b91173533a.png)

**Comment by manaswis** [comment]
Although the label appears displaced. It looks fine on the GSV image:

![image](https://user-images.githubusercontent.com/2873216/29233187-b66a4768-7ebd-11e7-848f-d8fa99cb1b17.png)

Same labels in the admin view label dialog:
![image](https://user-images.githubusercontent.com/2873216/29233222-da64b5f4-7ebd-11e7-873b-af97914d8b02.png)

![image](https://user-images.githubusercontent.com/2873216/29233196-c05faaec-7ebd-11e7-965b-4fcfc322e302.png)

**Comment by manaswis** [comment]
I think the blank GSV is related to this: https://github.com/ProjectSidewalk/SidewalkWebpage/pull/381/commits/4bc71448669e8bc60b94a9965b18849b2bf1a2dd from PR #381 of issue #317
