### ISSUE TITLE
Results Choropleth Needs to Filter Out Tutorial Labels

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#980]
As noted [here](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/973#issuecomment-321930239), Cleveland Park is the tutorial site. We should filter these labels out for the results Choropleth.

![image](https://user-images.githubusercontent.com/1621749/29243629-b5e3da66-7f71-11e7-98c3-336c88c73189.png)

(In addition, any analysis of user activity should treat tutorial labels completely differently from actual labels).

**Comment by misaugstad** [comment]
>(In addition, any analysis of user activity should treat tutorial labels completely differently from actual labels).

Should we also filter out tutorial labels from our total label count?

**Comment by jonfroehlich** [comment]
> Should we also filter out tutorial labels from our total label count?

I don't think it needs to be filtered out from landing page. For admin pages, we should discuss implications. Certainly, for the paper when we are analyzing severity patterns, we shouldn't include tutorial labels... We need to think about this more and discuss for each case (e.g., for paper, should we include tutorial labels when presenting the average # of labels contributed per labeler, etc.)

**Comment by jonfroehlich** [comment]
This Issue is strongly related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/973.

Can we make this a higher priority? I am giving a demo of our system on Friday and I want to be able to show the Results page but this dark red anomaly in Cleveland Park is distracting and erroneous. Perhaps @manaswis can take a swing at this one since it would be good to balance coding with the qualitative analysis...

Not sure why @misaugstad added the Needs Clarification tag. :)

**Comment by manaswis** [comment]
Sure, I will work on this on Thursday after the assignment deadline.

**Comment by misaugstad** [comment]
@jonfroehlich I added the needs clarification label since we had had decided neither how to implement this, nor in what places such labels should be removed.

However, we have discussed over Slack that we will try adding a `tutorial` column to the label table. And for now I am just going to do this for the choropleth, since it is more important. We can think about the rest of the cases afterwards.

**Comment by jonfroehlich** [comment]
Ah, yes, makes total sense. And to copy over our Slack discussion:

![image](https://user-images.githubusercontent.com/1621749/31457955-4f751476-ae73-11e7-98d6-e6339d54e936.png)

**Comment by manaswis** [comment]
Closed via #1139
