### ISSUE TITLE
1/2 mile mission given before 1/4 mile mission 

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#992]
The ideal should be 2 500ft, 1 1000ft, 1 1/4 mile, then the rest are 1/2 mile missions. This is the order in the old code (except 500ft were 1 1000ft missions).

**Comment by adash12** [comment]
This happens even before the shorter missions were introduced (i.e. in `2ada47f07156770f651e2c0f21bd9cfe49f4a1ee`, the hash of the commit in develop before the new missions were merged).

**Comment by adash12** [comment]
The first 1/2-mile mission that happens (i.e. after the second 1000-ft mission) is really a 2000-ft mission, but the way the mission dialog is set up, if a mission has a length that is less than or equal to 1000 feet, 1000ft is displayed. If the length is less than 0.25 miles, 1/4 miles is displayed, and if it's less than 0.5 miles, 1/2 mile is displayed. 2000 feet is between 0.25 and 0.50 miles, so it's displayed as a 1/2-mile mission. The mission after that is 1280 feet (the difference between one mile and 4000ft), which is less than 0.25 miles, so is displayed as 1/4 mile.

**Comment by manaswis** [comment]
Hmm, I see. Thanks for looking into this. But it isn't just the mission instruction, the mission itself is also set to 1/4 mile isn't it?

**Comment by adash12** [comment]
So the cumulative distance of the missions in order is 1000ft, 2000ft, 4000ft, 1 mile (5280 ft), 1.5 miles, etc.
This means that the actual mission distances in order are 1000ft, 1000ft, 2000ft, 1280 ft, 0.5 miles, 0.5 miles, etc.

The mission modal dialog and status field only display mission distances of 1000ft, 1/4 mile, 1/2 mile, 3/4 mile, and then integers up to 10, using the scheme I described above to decide what distance to display.

**Comment by manaswis** [comment]
Hmm, I see. So it looks like the mission table itself needs to be updated to fix this.

Thanks for the investigation. Doesn't look a high priority issue to solve right now.

**Comment by misaugstad** [comment]
It doesn't look like we are going to put dev effort into changing this before we finish with DC. When launching in a new city, we are going to totally rework the mission structure, as discussed in #1130, so I am going to close this issue. @manaswis feel free to reopen if you disagree.
