### ISSUE TITLE
Hitting +/- signs in feedback dialog zooms pano

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#999]
![image](https://user-images.githubusercontent.com/1621749/29427313-038d1990-834f-11e7-820f-3c7755f1c5ee.png)

**Comment by manaswis** [comment]
Yes, this is issue https://github.com/ProjectSidewalk/SidewalkWebpage/issues/678. @sbower213  has been working on it for 3 days but couldn't find a solution. Sage had tried it too. So he has switched to another issue for the time being. Its a tough problem. Is seems no way of disabling GSV's default zooming in shortcuts.

**Comment by manaswis** [comment]
And it is true for any text box element in the tool: feedback, description text, logins.

**Comment by jonfroehlich** [comment]
OK, I searched prior Issues before posting and I didn't see this specific issue mentioned for the feedback dialog. Also, I don't believe any prior Issue states that this is relevant to any textbox element as you did above (which is quite important).

**Comment by misaugstad** [comment]
closing via #1388
